### ISSUE TITLE
The NewPascal button is missing

### ISSUE THREAD

**Issue by Pethical** [LongDirtyAnimAlf/fpcupdeluxe#100]
![image](https://user-images.githubusercontent.com/10383468/53162577-96233100-35cc-11e9-83ff-1310d02b3407.png)

**Comment by LongDirtyAnimAlf** [comment]
NewPascal is not maintained and supported anymore.
So, I removed the SpeedButton.

It is, however, still available as a choice in the FPC and Lazarus version list.
