### ISSUE TITLE
Access violation in 1.6.2o on Debian 9.8x64

### ISSUE THREAD

**Issue by eugeneloza** [LongDirtyAnimAlf/fpcupdeluxe#101]
Hi! I've happened this issue before, but I thought that it was due to my Linux system instability. So, I reinstalled Debian 9.8x64 today, but FPCUpDeluxe 1.6.2o still doesn't install FPC+Lazarus trunk correctly:

```
(3104) Compiling synpropertyeditobjectlist.pas
EAccessViolation: Access violation
  $0000000000000000
  $0000000000A7BE54  SETTOOL,  line 1371 of exttools.pas
  $0000000000A7D11E  DESTROY,  line 1674 of exttools.pas

Makefile:3282: recipe for target 'useride' failed
make: *** [useride] Error 217
fpcupdeluxe: ERROR: LazarusNativeInstaller (BuildModuleCustom: UserIDE): make returned error code #512


ERROR: Fpcupdeluxe fatal error !
```
Just tried - version 1.6.2h works flawlessly. (It shows me `Error: the Fppkg configuration is corrupt.`, but that's another problem, and I believe I'll figure it out by myself :) // UPD: solved it)

**Comment by LongDirtyAnimAlf** [comment]
Would you mind trying the latest release ?
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.2q

**Comment by eugeneloza** [comment]
Yes, working perfectly! Thanks a lot!!!
