### ISSUE TITLE
3285 : only one else' per conditional. Stop

### ISSUE THREAD

**Issue by lazarosa** [LongDirtyAnimAlf/fpcupdeluxe#102]
Trying to setup lazarus/trunk & fpc/trunk with current v1.6.2o of fpcupdeluxe ends up with
"LazarusNativeInstaller (BuildModuleCustom: Lazbuild): make returned error code #512"
and "3285 : only one else' per conditional. Stop".

In Makefile we find:

```
ifdef LCL_PLATFORM
	./lazbuild$(SRCEXEEXT) --lazarusdir=. --build-ide= --ws=$(LCL_PLATFORM)
_else
ifdef LCL_PLATFORM
endif
	./lazbuild$(SRCEXEEXT) --lazarusdir=. --build-ide= --ws=$(LCL_PLATFORM)
else
ifdef LCL_PLATFORM
endif
	./lazbuild$(SRCEXEEXT) --lazarusdir=. --build-ide= --ws=$(LCL_PLATFORM)_
else
	./lazbuild$(SRCEXEEXT) --lazarusdir=. --build-ide=
endif
```
Reducing that manually to
```
ifdef LCL_PLATFORM
	./lazbuild$(SRCEXEEXT) --lazarusdir=. --build-ide= --ws=$(LCL_PLATFORM)
else
	./lazbuild$(SRCEXEEXT) --lazarusdir=. --build-ide=
endif
```
lets setup run fine again.
However, to get any time at all for this manual correction, one can insert after Line #1932
`ShowMessage('Verify Makefile now!');`
(this also needs to add "Dialogs" to the use clause in Line #38.

Professional programmers or the author will surely find the appropriate solution to suppress the multiple addition of Else; this is only an emergency solution at very beginner level, sorry for that ,-)

**Comment by LongDirtyAnimAlf** [comment]
This is surely a fpcupdeluxe-induced bug.
Will try to solve soon.

**Comment by LongDirtyAnimAlf** [comment]
New release should solve this issue.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.2q

**Comment by lazarosa** [comment]
Yes, it runs smoothly now. Thanks a lot!

**Comment by lazarosa** [comment]
I was happy too soon. Now, on a subsequent test, I got:

ifdef LCL_PLATFORM
	./lazbuild$(SRCEXEEXT) --lazarusdir=. --build-ide= --ws=$(LCL_PLATFORM)
else
ifdef LCL_PLATFORM
endif
	./lazbuild$(SRCEXEEXT) --lazarusdir=. --build-ide= --ws=$(LCL_PLATFORM)
else
ifdef LCL_PLATFORM
endif
	./lazbuild$(SRCEXEEXT) --lazarusdir=. --build-ide= --ws=$(LCL_PLATFORM)
else
	./lazbuild$(SRCEXEEXT) --lazarusdir=. --build-ide=
endif

So would

**Comment by LongDirtyAnimAlf** [comment]
Very strange !
Please remove the whole Makefile and run fpcupdeluxe again.

I am sorry for this, but I cannot reproduce this error on my own system(s).

**Comment by lazarosa** [comment]
Don't mention it. It confuses me too :-)
After I deleted the entire ./tunk-trunk folder, fpcupdeluxe-x86_64-linux ran without errors again. 
A second run, called again afterwards, also remained error-free. In fact, the /trunk-trunk/lazarus/Makefile still has the same timestamp as the copy I made before the second run. (And both are also binary identical.)
