### ISSUE TITLE
Failed launching on the Windows XP SP2 x64

### ISSUE THREAD

**Issue by kazalex** [LongDirtyAnimAlf/fpcupdeluxe#103]
```
---------------------------
fpcupdeluxe-x86_64-win64.exe - Entry Point Not Found
---------------------------
The procedure entry point SHGetKnownFolderPath could not be located in the dynamic link library shell32.dll. 
---------------------------
OK   
---------------------------
```

**Comment by sstvmaster** [comment]
It never works with XP (32 or 64).

![SHGetKnownFolderPath](https://user-images.githubusercontent.com/19416108/54382242-e6ebee00-468f-11e9-98ef-352ed84bb4da.JPG)

Look here: https://docs.microsoft.com/en-us/windows/desktop/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath

**Comment by kazalex** [comment]
Previously this function is not using.

**Comment by LongDirtyAnimAlf** [comment]
New release should solve this issue.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.2q

**Comment by kazalex** [comment]
Works fine. Many thanks.
