### ISSUE TITLE
Buttons width

### ISSUE THREAD

**Issue by Kashaket** [LongDirtyAnimAlf/fpcupdeluxe#104]
After latest update, OPM button doesn't fit in the form,
Also, please, add minimal width for the main form or make the halt button fixed to fit in the form
![image](https://user-images.githubusercontent.com/22324695/54487584-6ea84700-48a0-11e9-83f3-e5139a0bbfea.png)

**Comment by LongDirtyAnimAlf** [comment]
This will not be implemented.
I do agree with you that it would be better to solve.
But I find this acceptable.
