### ISSUE TITLE
mORMot installation  does not work (maybe messing with my Cygwin installation?)

### ISSUE THREAD

**Issue by bleuge** [LongDirtyAnimAlf/fpcupdeluxe#105]
I am using 1.6.2q, W10x64 here, I think it's messing with the git.exe installed in my cygwin installation:

Note: some spanish messages in the log, for example: 
>fatal: no es un repositorio git ( o ningún padre en el punto de montado /cygdrive)
means
>fatal:it's not a git repository (or no parent in the  mount point /cygdrive)

Log:

FPCUPdeluxe V1.6.2q for x86_64-win64-win32

Going to install the mORMot .
FPCUP(deluxe) is starting up.

Binutils/make dir:     C:\fpcbootstrap
Bootstrap dir:         C:\fpcbootstrap
FPC URL:               https://svn.freepascal.org/svn/fpc/trunk
FPC options:           
FPC source directory:  C:\fpcsrc
FPC install directory: C:\fpc
Lazarus URL:           https://svn.freepascal.org/svn/lazarus/tags/lazarus_2_0_0
Lazarus options:       
Lazarus directory:     C:\lazarus

Please stand back and enjoy !

fpcupdeluxe: info: 17/03/2019 10:14:13: fpcupdeluxe: V076 (20190316) started.
fpcupdeluxe: info: Windows major version: 10
fpcupdeluxe: info: Windows minor version: 0
fpcupdeluxe: info: Windows build number:  17763
fpcupdeluxe: info: UniversalInstaller (CheckAndGetTools): Init SSL interface success.
fpcupdeluxe: info: UniversalInstaller (DownloadBinUtils): Found GNU make binary here: C:\fpcbootstrap\make.exe.
fpcupdeluxe: info: UniversalInstaller (GetModule: mORMot): Getting module mORMot
fpcupdeluxe: info: UniversalInstaller (GetModule: mORMot): Going to download/update from GIT repository https://github.com/synopse/mORMot
fpcupdeluxe: info: UniversalInstaller (GetModule: mORMot): Please wait: this can take some time (if repo is big or has a large history).
Executing: C:\cygwin64\bin\git.exe rev-list --max-count=1 HEAD (working dir: C:\fpc\ccr\mORMot)
fatal: no es un repositorio git ( o ningún padre en el punto de montado /cygdrive)
Parando en el límite del sistema de archivos (GIT_DISCOVERY_ACROSS_FILESYSTEM no establecido).
Executing: C:\cygwin64\bin\git.exe rev-list --max-count=1 HEAD (working dir: C:\fpc\ccr\mORMot)
fatal: no es un repositorio git ( o ningún padre en el punto de montado /cygdrive)
Parando en el límite del sistema de archivos (GIT_DISCOVERY_ACROSS_FILESYSTEM no establecido).
Executing: C:\cygwin64\bin\git.exe status --porcelain (working dir: C:\fpc\ccr\mORMot)
fatal: no es un repositorio git ( o ningún padre en el punto de montado /cygdrive)
Parando en el límite del sistema de archivos (GIT_DISCOVERY_ACROSS_FILESYSTEM no establecido).
Executing: C:\cygwin64\bin\git.exe clone --recurse-submodules -b master https://github.com/synopse/mORMot/ C:\fpc\ccr\mORMot (working dir: )
Clonando en 'C:\fpc\ccr\mORMot'...
fatal: Invalid path '/cygdrive/c/fpc/C:\fpc\ccr\mORMot': No such file or directory
Executing: C:\cygwin64\bin\git.exe clone --recurse-submodules -b master https://github.com/synopse/mORMot/ C:\fpc\ccr\mORMot (working dir: )
Clonando en 'C:\fpc\ccr\mORMot'...
fatal: Invalid path '/cygdrive/c/fpc/C:\fpc\ccr\mORMot': No such file or directory
Executing: C:\cygwin64\bin\git.exe clone --recurse-submodules -b master https://github.com/synopse/mORMot/ C:\fpc\ccr\mORMot (working dir: )
Clonando en 'C:\fpc\ccr\mORMot'...
fatal: Invalid path '/cygdrive/c/fpc/C:\fpc\ccr\mORMot': No such file or directory
Executing: C:\cygwin64\bin\git.exe pull --all --recurse-submodules=yes (working dir: C:\fpc\ccr\mORMot)
fatal: no es un repositorio git ( o ningún padre en el punto de montado /cygdrive)
Parando en el límite del sistema de archivos (GIT_DISCOVERY_ACROSS_FILESYSTEM no establecido).

Executing: C:\cygwin64\bin\git.exe rev-list --max-count=1 HEAD (working dir: C:\fpc\ccr\mORMot)
fatal: no es un repositorio git ( o ningún padre en el punto de montado /cygdrive)
Parando en el límite del sistema de archivos (GIT_DISCOVERY_ACROSS_FILESYSTEM no establecido).
Executing: C:\cygwin64\bin\git.exe rev-list --max-count=1 HEAD (working dir: C:\fpc\ccr\mORMot)
fatal: no es un repositorio git ( o ningún padre en el punto de montado /cygdrive)
Parando en el límite del sistema de archivos (GIT_DISCOVERY_ACROSS_FILESYSTEM no establecido).
fpcupdeluxe: info: UniversalInstaller (GetModule: mORMot): Download/update from GIT repository ok.
fpcupdeluxe: info: UniversalInstaller (BuildModule: mORMot): Building module mORMot...

fpcupdeluxe: info: UniversalInstaller (BuildModule: mORMot): Building module mORMot running all InstallExecute commands in: 
Name=mORMot
Description="Very extensive full featured ORM framework for FPC and Delphi."
Installdir=$(basedir)/ccr/$(name)
Enabled=0
GITURL=https://github.com/synopse/mORMot
ArchiveURL=https://github.com/synopse/mORMot/archive/master.zip
UnInstall=rm -Rf $(Installdir)
Category=miscellaneous

fpcupdeluxe: info: UniversalInstaller (BuildModule: mORMot): Building module mORMot running all CreateInstaller commands in: 
Name=mORMot
Description="Very extensive full featured ORM framework for FPC and Delphi."
Installdir=$(basedir)/ccr/$(name)
Enabled=0
GITURL=https://github.com/synopse/mORMot
ArchiveURL=https://github.com/synopse/mORMot/archive/master.zip
UnInstall=rm -Rf $(Installdir)
Category=miscellaneous

SUCCESS: Fpcupdeluxe ended without errors.

**Comment by LongDirtyAnimAlf** [comment]
Fpcupdeluxe uses the avaiable GIT client when it can be found in the path.
In your case: the cygwin GIT client.

However, this client seems not to work for GitHub.

You can force fpcupdeluxe to use its own GIT-client.
![fpcuplocal](https://user-images.githubusercontent.com/10783972/54520511-286aea80-4969-11e9-8bd3-c807601dc016.JPG)

Check the "use local repo-client" in Setup+.

**Comment by bleuge** [comment]
Thanks you very much!
