### ISSUE TITLE
fpcupdeluxe-x86_64-darwin-cocoa v1.6.2q. ld: library not found for -lc

### ISSUE THREAD

**Issue by ludoza** [LongDirtyAnimAlf/fpcupdeluxe#106]
Hi,

Really feel 'tupid for posting this error but cannot understand why I'm getting it:

```
/Users/d-_-b/fpcupdeluxe/fpcsrc/compiler/ppcx64 fpmake.pp  -Fu/Users/d-_-b/fpcupdeluxe/fpcsrc/packages/fpmkunit/units_bs/x86_64-darwin -Fu/Users/d-_-b/fpcupdeluxe/fpcsrc/rtl/units/x86_64-darwin  -WM10.8 -Sg -vw-n-h-l-d-u-t-p-c-
ld: library not found for -lc
An error occurred while linking 
Error: Error while linking
Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted
make[1]: *** [packages_smart] Error 2
make: *** [build-stamp.x86_64-darwin] Error 2
```

I'm using fpc from brew and did change my `/etc/fpc.cfg` to resolve a `/usr/lib/crt1.10.5.o` error, might be overkill? 

```sh
air:~ d-_-b$ brew info fpc
fpc: stable 3.0.4 (bottled)
...
air:~ d-_-b$ cat /etc/fpc.cfg
-XR/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/
-Fl/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/
-Fl/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0
```

clang seems to work:

```sh
air:~ d-_-b$ echo "int main(int argc, const char **argv) {return 0;}" > cocoatest.c
air:~ d-_-b$ clang cocoatest.c -o cocoatest -framework Cocoa
```

my mac version:

```sh
air:~ d-_-b$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14
BuildVersion:	18A391
```

What am I missing?

Thanks,

**Comment by LongDirtyAnimAlf** [comment]
First: there are NO stupid questions !

I do not understand why you are getting this error.
However, fpcupdeluxe will install FPC by itself.
So, you do not need to install FPC with brew.
Just let fpcupdeluxe install its own FPC (and Lazarus) somewhere in your home-directory.
It should work (I hope).

**Comment by ludoza** [comment]
Sorry was a bit rude and "not smart" not supplying the full [stderr (gist)](https://gist.github.com/ludoza/ccac839edc1af2ba39459715f731b167) output.

I have laz 2.0 installed and laz 1.9 from svn working.

fpcupdeluxe did give me a successful build of laz and fpc on macOS 10.13. But then the laz bin asked me to upgrade to macOS 10.14. Which I did.

But now I cannot build trunk anymore :/

Any insight into the gist log would be appreciated!

**Comment by ludoza** [comment]
Seems I had to run:

```
$ xcode-select --install
```

after upgrading my macOS. 

v1.6.2r darwin cocoa worked for me compiling trunk for fpc and lazarus.

**Comment by LongDirtyAnimAlf** [comment]
Thanks for the feedback !
