### ISSUE TITLE
Feature Request: Get Current Version Info

### ISSUE THREAD

**Issue by BrainWaveCC** [LongDirtyAnimAlf/fpcupdeluxe#108]
**Feature requests:**

1. Please remember previous selections on the **Cross**, **Modules** and **ExtraSheet** tabs.  Currently only remembers **Basic**.

2. Add a button to check and determine **current versions/builds** vs **installed versions/builds** of just FPC and Lazarus.

Love this app....

**Comment by LongDirtyAnimAlf** [comment]
I have implemented 1. (in the new upcoming release 1.6.2r)
Due to the limitations of the original fpcup-code, it is not possible to implement 2. It would require very many code changes, and I have no time (at the moment) to implement these changes.

**Comment by BrainWaveCC** [comment]
Fair enough.  👍   Thanks for the update, it is much appreciated.
