### ISSUE TITLE
Problem with fppkg

### ISSUE THREAD

**Issue by Tj85710** [LongDirtyAnimAlf/fpcupdeluxe#112]
Hello,

I have very easily installed the latest version of Lazarus/fpc on a Ubuntu 18.04LTS system. Everything seems good, apart that I get an error message telling me that Fppkg is not properly installed. 

_The message is "The prefix of the Free Pascal Compiler Installation is required to create new configuration files for Fppkg. For example it has the units "lib/fpc and/or "lib64/fpc"_
Than I can browse the file system and I put the /usr/bin path. 
Than another panel says : 
_Error : there is a problem with the Fppkg configuration. (Fppkg reports that the RTL is not installed.)
Warning : Free Pascal compiler not found at the given prefix._

I have set /usr/bin as the prefix, according to the return of a $which fpc command. I can follow the links from /usr/bin/fpc and everything looks good. So, I don't understand why fppkg is complaining ? 

On another way, it seems that I don't really need this package management system, but who knows...

Anyway you have done a very good job with fpcupdelux, it is a very clever tool.

Best regards,

Thierry

**Comment by LongDirtyAnimAlf** [comment]
This is unfortunate.
I am still struggling with this whole Lazarus fppkg-thing.

However, your FPC resides in the install-dir that you have chosen. NOT in /usr/bin !!
So, point towards yourinstalldir/fpc !

**Comment by Tj85710** [comment]
Thanks for answering.

When I point to /home/thierry/fpcupdeluxe/fpc, the error message changes and I get "Error : There is a problem with the Fppkg configuration. (Fppkg reports that the RTL is not installed)."

Apart of this, Lazarus is working… I don't understand.

You are doing great, best regards,

Thierry

**Comment by mdbs99** [comment]
@LongDirtyAnimAlf this happens on Windows too.
Today I tried to compile a new Lazarus, setup to use trunk. As @Tj85710 described, everything seems good, but Lazarus give me this error related with fppkg.cfg.

I wasn't aware about `fppkg.cfg` until today. I searched in my other installations in I found this file in `ide\fpcsrc\utils\fpcmkcfg\` so, I've pointed to it. But it didn't work. It seems that this new Lazarus needs to use `%LocalAppdata%\Freepascal\fppkg\config` directory. However, as I (we) have many Lazarus "installations" in the same machine, it doesn't seem Ok.

What do you think? What is the workaround?

**Comment by Tj85710** [comment]
Lastly I hard no problem while installing Lazarus with the latest version of Focupdeluxe on my Mac.
On Windows I have used the "official" installer. I am now developping and debugging on a Windows (7 pro) VM (VirtualBox), I push my sources to a git server on a Synology and I can build the application right on the Mac. It's amazing !

Thierry

**Comment by LongDirtyAnimAlf** [comment]
This issue should be fixed by the latest releases.
