### ISSUE TITLE
IDE Compilation problem

### ISSUE THREAD

**Issue by hafedh-trimeche** [LongDirtyAnimAlf/fpcupdeluxe#113]
fpcupdeluxe: WARNING: FPCNativeInstaller (DownloadOpenSSL): No OpenSLL library files available for SSL. Going to download them.
fpcupdeluxe: WARNING: FPCNativeInstaller (GetFile): OpenSLL library files download and unpacking from https://indy.fulgan.com/SSL/openssl-1.0.2r-x64_86-win64.zip ok.
fpcupdeluxe: Performing a SVN/GIT/HG checkout ... please wait, could take some time.
fpcupdeluxe: info: FPC builder: Detected source version FPC: 3.3.1
fpcupdeluxe: info: FPC builder: Using FPC bootstrap compiler with version: 3.0.4
fpcupdeluxe: Performing a SVN/GIT/HG checkout ... please wait, could take some time.
fpcupdeluxe: info: Lazarus builder: Detected source version Lazarus: 2.1.0
fpcupdeluxe: info: Lazarus builder: Using FPC compiler with version: 3.3.1
fpcupdeluxe: Getting suggestedpackages sources ... please wait, could take some time.
fpcupdeluxe: Start of compile error summary.
D:\LazarusIDE\lazarus\components\tachart\tacustomsource.pas(1269,29) Error: (3128) Procedure directive "VIRTUAL" cannot be used with "INLINE"
fpcupdeluxe: Start of compile error summary.
tacustomsource.pas(1506) Fatal: (10026) There were 1 errors compiling module, stopping
D:\LazarusIDE\lazarus\components\tachart\tacustomsource.pas(1269,29) Error: (3128) Procedure directive "VIRTUAL" cannot be used with "INLINE"
fpcupdeluxe: Start of compile error summary.
Fatal: (1018) Compilation aborted
(3104) Compiling lazprojectgroups.pas
fpcupdeluxe: Start of compile error summary.
Error: D:\LazarusIDE\fpc\bin\x86_64-win64\ppcx64.exe returned an error exitcode
fpcupdeluxe: Start of compile error summary.
Error: (lazarus) Compile package TAChartLazarusPkg 1.0: stopped with exit code 1
fpcupdeluxe: Start of compile error summary.
Error: (lazarus) Compile package ChmHelpPkg 0.2: terminated
fpcupdeluxe: Start of compile error summary.
Error: (lazarus) Compile package Cody 1.1: terminated
fpcupdeluxe: Start of compile error summary.
Error: (lazarus) Compile package lazprojectgroups 0.7: terminated
fpcupdeluxe: Start of compile error summary.
Error: (lazarus) Compile package LazDebuggerLldb 0.0: terminated
fpcupdeluxe: Start of compile error summary.
Error: (lazarus) Compile package ToDoListLaz 1.0.2: terminated
fpcupdeluxe: Start of compile error summary.
Error: (lazarus) Compile package SQLDBLaz 1.0.2: terminated
fpcupdeluxe: Start of compile error summary.
Error: (lazarus) Compile package jcfidelazarus 2.0: terminated
fpcupdeluxe: Start of compile error summary.
Error: (lazarus) [TLazPackageGraph.CompileRequiredPackages] "Exit code 1"
fpcupdeluxe: Start of compile error summary.
Error: (lazarus) Building IDE: Compile AutoInstall Packages failed.
fpcupdeluxe: Start of compile error summary.
fpcupdeluxe: ERROR: UniversalInstaller (ConfigModule: suggestedpackages): Failure trying to rebuild Lazarus.
fpcupdeluxe: Done !!

**Comment by LongDirtyAnimAlf** [comment]
Was a Lazarus bug.
Solved in the meantime:
https://svn.freepascal.org/cgi-bin/viewvc.cgi?view=revision&root=lazarus&revision=60983
