### ISSUE TITLE
When I use FPCUPdeluxe only for FPC version 3.0.4 I hava problem.

### ISSUE THREAD

**Issue by DBtester1** [LongDirtyAnimAlf/fpcupdeluxe#116]
`Executing: make "--jobs=6" "FPC=/home/firefly/fpcupdeluxe/fpcbootstrap/ppca64" "--directory=/home/firefly/fpcupdeluxe/fpcsrc" "INSTALL_PREFIX=/home/firefly/fpcupdeluxe/fpc" "CPU_TARGET=aarch64" "OS_TARGET=linux" "distclean" (working dir: /home/firefly/fpcupdeluxe/fpcsrc)
Makefile:209: *** The Makefile doesn't support target aarch64-linux, please run fpcmake first.  Stop.
fpcupdeluxe: info: FPCNativeInstaller (CleanModule: FPC): Running make all install for FPC
Executing: make "--jobs=6" "FPC=/home/firefly/fpcupdeluxe/fpcbootstrap/ppca64" "INSTALL_PREFIX=/home/firefly/fpcupdeluxe/fpc" "INSTALL_BINDIR=/home/firefly/fpcupdeluxe/fpc/bin/aarch64-linux" "OS_SOURCE=linux" "CPU_SOURCE=aarch64" "OS_TARGET=linux" "CPU_TARGET=aarch64" "REVSTR=37149" "REVINC=force" "OVERRIDEVERSIONCHECK=1" "OPT=-Sg -vw-n-h-l-d-u-t-p-c-" "--directory=/home/firefly/fpcupdeluxe/fpcsrc" "all" "install" (working dir: /home/firefly/fpcupdeluxe/fpcsrc)
Makefile:209: *** The Makefile doesn't support target aarch64-linux, please run fpcmake first.  Stop.

fpcupdeluxe: ERROR: FPCNativeInstaller (CleanModule: FPC): Error running make for FPC failed with exit code 512
. Details: 

ERROR: Fpcupdeluxe fatal error !`

I use fpcupdeluxe-aarch64-linux
How can i do?

**Comment by LongDirtyAnimAlf** [comment]
You need at least FPC 3.2 or trunk to build for aarch64 !

**Comment by DBtester1** [comment]
Yes, I found  the  same question.
Now I'm try the trunk version.

**Comment by DBtester1** [comment]
/usr/bin/install: error writing '/home/firefly/fpcupdeluxe/fpc/lib/fpc/3.3.1/units/aarch64-linux/rtl/cpkoi8_u.ppu': No space left on device
/usr/bin/install: error writing '/home/firefly/fpcupdeluxe/fpc/lib/fpc/3.3.1/units/aarch64-linux/rtl/unicodedata.ppu': No space left on device
/usr/bin/install: error writing '/home/firefly/fpcupdeluxe/fpc/lib/fpc/3.3.1/units/aarch64-linux/rtl/unicodenumtable.ppu': No space left on device
Makefile:3578: recipe for target 'fpc_install' failed
Makefile:2078: recipe for target 'linux_install' failed
make[3]: *** [linux_install] Error 2
Makefile:2653: recipe for target 'rtl_distinstall' failed
make[2]: *** [rtl_distinstall] Error 2
Makefile:2903: recipe for target 'installbase' failed
make[1]: *** [installbase] Error 2
Makefile:2920: recipe for target 'installall' failed
make: *** [installall] Error 2

fpcupdeluxe: ERROR: FPCNativeInstaller (CleanModule: FPC): Error running make for FPC failed with exit code 512
. Details: 


ERROR: Fpcupdeluxe fatal error !
It also hava problem.

**Comment by LongDirtyAnimAlf** [comment]
> No space left on device

**Comment by DBtester1** [comment]
how much space do i need  to prepare?

**Comment by DBtester1** [comment]
I had compiled trunk version.
Add the directory with all FPC binaries on $PATH:export PATH=$PATH:$HOME/fpcupdeluxe/fpc/bin/aarch64-linux/aarch64-linux/
create a $HOME/.fpc.cfg, containing:#INCLUDE /home/firefly/fpcupdeluxe/fpc/bin/aarch64-linux//fpc.cfg
I run fpc hava  problem:
firefly@firefly:~/fpcupdeluxe/fpc/bin/aarch64-linux$ fpc
Free Pascal Compiler version 3.3.1-r41926 [2019/04/23] for aarch64
Copyright (c) 1993-2018 by Florian Klaempfl and others
Fatal: No source file name in command line
Fatal: Compilation aborted
Error: /home/firefly/fpcupdeluxe/fpc/bin/aarch64-linux/ppca64 returned an error exitcode
What's worry?

**Comment by DBtester1** [comment]
firefly@firefly:~/fpcupdeluxe/fpc/bin/aarch64-linux$ ./ppca64 
Free Pascal Compiler version 3.3.1-r41926 [2019/04/23] for aarch64
Copyright (c) 1993-2018 by Florian Klaempfl and others
/home/firefly/fpcupdeluxe/fpc/bin/aarch64-linux/ppca64 [options] <inputfile> [options]
 Put + after a boolean switch option to enable it, - to disable it.
  @<x>   Read compiler options from <x> in addition to the default fpc.cfg
  -a     The compiler does not delete the generated assembler file
      -a5        Don't generate Big Obj COFF files for GNU Binutils older than 2.25 (Windows, NativeNT)
      -al        List sourcecode lines in assembler file
      -an        List node info in assembler file (-dEXTDEBUG compiler)
      -ao        Add an extra option to external assembler call (ignored for internal)
      -ap        Use pipes instead of creating temporary assembler files
      -ar        List register allocation/release info in assembler file
      -at        List temp allocation/release info in assembler file
  -A<x>  Output format:
      -Adefault  Use default assembler
  -b     Generate browser info
      -bl        Generate local symbol info
  -B     Build all modules
  -C<x>  Code generation options:
When i in to /home/firefly/fpcupdeluxe/fpc/bin/aarch64-linux/ run ./ppca64 it's ok.

**Comment by LongDirtyAnimAlf** [comment]
Closing for now.
Please re-open when necessary.
