### ISSUE TITLE
I can make cross-compile from Linux x64 to Solaris x64

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#117]
subj. So pls add such cross to the app.

- cross/bin folder: I've got it at https://www.pilotlogic.com/sitejoom/index.php/downloads/search
And I copied file "....-ld" to filename ".....-gld" so Lazarus can link the sample app.

- cross/lib folder: I've got it from my Solaris 11.4 x86, I've got all .so* files from folders: /lib/amd64, /usr/lib/amd64, /usr/lib/xorg/amd64

Files:
https://nofile.io/f/kghqe3jBR6q/so.zip  -300M
https://nofile.io/f/UsQBsZ2EJYT/so2.zip  -2M
pls remove unneded files.

**Comment by Alexey-T** [comment]
![sola](https://user-images.githubusercontent.com/4154978/56655655-0f5a0580-669c-11e9-929f-49d5cf43a2fc.png)

**Comment by LongDirtyAnimAlf** [comment]
See latest release.

And the important note on the Lazarus forum:
https://forum.lazarus.freepascal.org/index.php/topic,34645.msg318926.html?PHPSESSID=bf43911005bf788ab072b3d73d1bfb4f#msg318926

**Comment by Alexey-T** [comment]
Thanks...
