### ISSUE TITLE
cleanup cross libs for Solaris

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#118]
I deleted these .so and app still links

VBox*
libpython*
libMagick*
libFLAC*
libedataserver*
libvorbis*
libgnome*

**Comment by Alexey-T** [comment]
@LongDirtyAnimAlf ?

**Comment by LongDirtyAnimAlf** [comment]
There should be much more libs that can be deleted. I am still checking and testing.

**Comment by Alexey-T** [comment]
Not solved?

**Comment by Alexey-T** [comment]
No progress?

**Comment by Alexey-T** [comment]
@LongDirtyAnimAlf ?

**Comment by LongDirtyAnimAlf** [comment]
Closing.
As I am not able to check which libs are needed for all kinds of cross-compiled apps, the libs will stay.

**Comment by LongDirtyAnimAlf** [comment]
Done.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/crosslibs_all/SolarisAMD64_Oracle_1104.zip
