### ISSUE TITLE
feature req: REMOVE cross compilers

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#119]
i want to remove eg FreeBSD cross and all its lines in fpc.cfg.

**Comment by Alexey-T** [comment]
It's done? button is here. Thanks...

**Comment by LongDirtyAnimAlf** [comment]
Feature has to be finished yet.
Its not easy to implement correctly.

**Comment by Alexey-T** [comment]
Tested yesterday- it don’t remove FPC.cfg lines so on next start deluxe still finds same 3 crosses, with deleted FreeBSD

**Comment by Alexey-T** [comment]
Not solved?

**Comment by LongDirtyAnimAlf** [comment]
Added and working in latest release.
