### ISSUE TITLE
Add "Report issue on GitHub" menu item to main menu

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#124]
subj. To open browser on GH.

**Comment by LongDirtyAnimAlf** [comment]
Will try to implement if time and knowledge permits.

**Comment by Alexey-T** [comment]
Use Lazarus method OpenURL with the url to GitHub issues page

**Comment by LongDirtyAnimAlf** [comment]
Done. As menu item.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/2486695e4558c49283fcee0a4d37205da1131936
Next release.
