### ISSUE TITLE
Linux Shell environment non-functional after installation

### ISSUE THREAD

**Issue by leagris** [LongDirtyAnimAlf/fpcupdeluxe#126]
#### fpcupdeluxe version:

Build 2019-04-25

#### OS/Environment:

Linux Ubuntu 18.
`4.18.0-17-generic #18-Ubuntu SMP Wed Mar 13 14:34:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

#### Issue details:

The installer is missing setting or recommendations of `PATH` and other Lazarus/FPC specific environment variables, to enable using FPC tool chains within a shell, to build outside of the Lazarus IDE with make, or call the fpc compiler tools from command-line without having to specify full path of all executables and dependencies.

##### Example of failure to use fpc tools from a shell:

```Shell
lea@meumeu:~/fpcupdeluxe/projects/fpc-rainbow$ make
lazbuild code/lcl/rainbow.lpi
make: lazbuild: Command not found
make: *** [Makefile:4: standalone] Error 127
lea@meumeu:~/fpcupdeluxe/projects/fpc-rainbow$ fpc

Command 'fpc' not found, but can be installed with:

sudo apt install fp-compiler-3.0.4
```

**Comment by LongDirtyAnimAlf** [comment]
This is on purpose.
Fpcupdeluxe makes an isolated install, without changing the path.
To prevent any changes on the system itself.

**Comment by leagris** [comment]
Oh! I did not get that at first.

So, fpcupdeluxe is just meant to be used within the Lazarus GUI presets, and is inappropriate for command-line use.

I thought I could use fpcupdeluxe to setup a user-land scope, contained and fully featured development and build environment for FreePascal.

There are other local dev environments that are anyway isolated from system.
This is the case for example, with the go dev environment.

I have this in my `.bashrc`, and it allow me to use the go language tools from within a shell:
```Bash
#With this line, you choose the architecture of your machine.  
#Those with 64 bit CPUs should enter "amd64" here.  
export GOARCH=amd64
 
#Your operating system
export GOOS=linux
 
#And now the location where the installer will place the finished files
#Don't forget to create this directory before installing
export GOBIN=$HOME/gobin
```

Thank-you for your clarification about fpcupdeluxe I was trying to use not the intended way.
Is that right that fpcupdeluxe is for GUI usage only?

**Comment by LongDirtyAnimAlf** [comment]
> Is that right that fpcupdeluxe is for GUI usage only?
Yes. Its for experimenting with FPC and Lazarus.
I always recommend to use the official installs available.

**Comment by eugeneloza** [comment]
>  Is that right that fpcupdeluxe is for GUI usage only?

Adding to bashrc
```
export PATH=$PATH:'/media/LINUX_SYS/FPC/fpc/bin/x86_64-linux/'
```
works flawlessly for me in command line :)

**Comment by LongDirtyAnimAlf** [comment]
Thanks for reporting !
