### ISSUE TITLE
Access violation during compiling trunk (Debian 64 bit) in 1.6.2w

### ISSUE THREAD

**Issue by eugeneloza** [LongDirtyAnimAlf/fpcupdeluxe#127]
Hi again!
I'm again having an access violation during installation of Trunk under Debian 64 bit. Since approximately 16 May on two similar Debian systems (Desktop and Notebook).
```
(3104) Compiling synpropertyeditobjectlist.pas
EAccessViolation: Access violation
  $0000000000000000
  $0000000000A81E34  SETTOOL,  line 1371 of exttools.pas
  $0000000000A830FE  DESTROY,  line 1674 of exttools.pas

Makefile:3282: recipe for target 'useride' failed
make: *** [useride] Error 217
fpcupdeluxe: ERROR: LazarusNativeInstaller (BuildModuleCustom: UserIDE): make returned error code #512

ERROR: Fpcupdeluxe fatal error !
```

A similar error goes for Fixes version. Thou I was able to install it correctly around 15 May at my home Desktop.
```
(3104) Compiling synpropertyeditobjectlist.pas
(1008) 977 lines compiled, 0.7 sec
(1022) 3 hint(s) issued
EAccessViolation: Access violation
  $0000000000000000
  $000000000057A0C7 line 1525 of exttools.pas
  $000000000057B2D1 line 1814 of exttools.pas

Makefile:3281: recipe for target 'useride' failed
make: *** [useride] Error 217
fpcupdeluxe: ERROR: LazarusNativeInstaller (BuildModuleCustom: UserIDE): make returned error code #512

ERROR: Fpcupdeluxe fatal error !
```
Stable version installed without any issues.

P.S. Very similar issue: https://github.com/LongDirtyAnimAlf/fpcupdeluxe/issues/101

**Comment by LongDirtyAnimAlf** [comment]
I have seen this error many times before.
And I am not able to pinpoint it.

However, I have made a updated pre-release of 1.6.2w.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.2w

It prevents the use of lazbuild on a very fresh install.
I hope this will help a bit.

Please try and report back.

**Comment by eugeneloza** [comment]
Yeah, the last version is working again (downloaded and compiled Trunk without any issues), thank you!
