### ISSUE TITLE
Cannot build FPGUI

### ISSUE THREAD

**Issue by Kashaket** [LongDirtyAnimAlf/fpcupdeluxe#129]
Win64, Latest FPC and Lazarus (TrunkGit)
OS Language: Ukrainian (charset is non-latin)

When i trying to compile Lazarus with fpGUI, i get the following error
![image](https://user-images.githubusercontent.com/22324695/58753142-c9c30080-84c3-11e9-927d-f00a3e89f7e9.png)

**Comment by Kashaket** [comment]
One of the keys to resolve problem is:
1) Rename gdi folder to x11 in Src/Corelib
[Or check where are x11 specified - because it's wrong option for windows]
2) Edit unit Src/Corelib/GDI/fpg_OLE_DragDrop.pas
```
Line 129:
Function    SetData (Const pformatetc : FORMATETC;var medium:STGMEDIUM;FRelease : BOOL):HRESULT; StdCall;
Line 632:
.SetData (Const pformatetc : FORMATETC;
var medium:STGMEDIUM;FRelease : BOOL):HRESULT; StdCall;        
```              
And, after all of that steps, it finally compiled! But... not in the fpcupdeluxe
@LongDirtyAnimAlf

**Comment by LongDirtyAnimAlf** [comment]
Will close. This is not really a fpcupdeluxe issue.
