### ISSUE TITLE
GTK3 on windows [link]

### ISSUE THREAD

**Issue by Kashaket** [LongDirtyAnimAlf/fpcupdeluxe#130]
Hello!
in order to compile program correctly with GTK widgetset under Windows, you can use the following bundle: http://www.tarnyko.net/dl/gtk.htm

I had some troubles installing GTK3, which caused because of using unflexible package managers in GTK project (vcpkg and msys)...
Msys have troubles with localization (it localizes nor the commands, nor the messages, but the command arguments, which is really DUMB concept) and with network connection, if the connection to msys git is slower than 75mbi/s
And, i cannot install vcpkg because i don't have MS VS 2016/2015
After a little, i found this: http://www.tarnyko.net/dl/gtk.htm
So, this link may help other windows users.

@LongDirtyAnimAlf , i think you can pin this issue or add link in readme file, thanks.

**Comment by LongDirtyAnimAlf** [comment]
Added short hint in readme !
Thanks.
