### ISSUE TITLE
Lazarus error with Anchor Docking

### ISSUE THREAD

**Issue by reminder2k1** [LongDirtyAnimAlf/fpcupdeluxe#134]
Hi, I'm glad to use this tools for build **stable fpc & lazarus version** with **cross compile feature** on my OSX (**Mojave 10.14.5**)... it's amazing & thx for that...
But when I tried to install modules **anchordocking**, lazarus can't be opened... can you suggesting me what should I do to use that modules?
Thx...

**Comment by LongDirtyAnimAlf** [comment]
Should be solved by now by the maintainers of Lazarus.
