### ISSUE TITLE
Fatal: Unable to open file /media/LINUX_SYS/FPC/fpc/bin/x86_64-linux/fpc.cfg

### ISSUE THREAD

**Issue by eugeneloza** [LongDirtyAnimAlf/fpcupdeluxe#135]
Hi all!
I'm having a trouble with Debian Stretch Linux 64 bit again :)
This time it's: `Fatal: Unable to open file /media/LINUX_SYS/FPC/fpc/bin/x86_64-linux/fpc.cfg`. The directory `fpc` doesn't exist at this moment.
Manifests for some time by now, for both **Trunk** and **Fixes** installation. The log below is for version V1.6.2x
Full log:
[190626.log](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/3330575/190626.log)

**Comment by LongDirtyAnimAlf** [comment]
I am unable to reproduce unfortunately.
Do you run fpcupdeluxe as root ?

**Comment by eugeneloza** [comment]
No, as a regular user.

**Comment by eugeneloza** [comment]
Oh, sorry, that was my bad!!! :fearful: 
I've forgotten, that I've made a hacky patch (.fpc.cfg file in home folder) to search for fpc.cfg in that exact location (for fpc work fine both in XFCE and in console). I've removed it and everything works flawlessly.
Sorry again.
