### ISSUE TITLE
Cannot install on aarch64 linux

### ISSUE THREAD

**Issue by chuahyen** [LongDirtyAnimAlf/fpcupdeluxe#136]
I downloaded the fpcupdexluxe aarch64-linux for a firefly ROC-RK3328-CC hardware running on ubuntu 18.04.
When i run the binary, it could not get any sources to compile it. 
Must i download the source and do every step to build it?

firefly@firefly:~/Downloads$ uname -a
Linux firefly 4.4.114 #63 SMP Thu Sep 20 19:36:41 CST 2018 aarch64 aarch64 aarch64 GNU/Linux

**Comment by LongDirtyAnimAlf** [comment]
Fpcupdeluxe should download the sources by itself.
It uses svn to do the job.
If the download of sources fails, please post the green-screen-output here, so I can have a look at the errors reported.

**Comment by peardox** [comment]
As this is still open I may as well just tag stuff on here

End of output says...

Makefile:209: *** The Makefile doesn't support target aarch64-linux, please run fpcmake first. Stop.

All output in ZIP this - [fpc.zip](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/3550981/fpc.zip)

=== NOTES FOR THE UNAWARE ===

Note that there's some 'brand confusion' when it comes to aarch64 as it can also be reported as arm64 in some cases

I'm building on a Jetson Nano ($99 SBC with GPU) which uses aarch64 CPU

simon@nano:~$ uname -a
Linux nano 4.9.140-tegra #1 SMP PREEMPT Tue Jul 16 17:04:49 PDT 2019 aarch64 aarch64 aarch64 GNU/Linux

Example of aarch64 / arm64 clash...

> apt list | grep aarch64
binutils-aarch64-linux-gnu/bionic-updates,bionic-security,now 2.30-21ubuntu1~18.04.2 arm64 [installed]
binutils-aarch64-linux-gnu-dbg/bionic-updates,bionic-security 2.30-21ubuntu1~18.04.2 arm64
qemu-efi-aarch64/bionic-updates 0~20180205.c0d9813c-2ubuntu0.1 all

The same command checking arm64 returns 29k+ packages :(

**Comment by LongDirtyAnimAlf** [comment]
You need FPC trunk or fixes for aarch64.
