### ISSUE TITLE
Can't update lazarus trunk version

### ISSUE THREAD

**Issue by Imantsg** [LongDirtyAnimAlf/fpcupdeluxe#137]
When I try to update Lazarus trunk using fpcupdeluxe I got this error:

`make.exe[1]: Leaving directory `D:/fpcupdeluxe/lazarus+fpc+latest/lazarus/ide'
D:\fpcupdeluxe\lazarus+fpc+latest\fpc\bin\x86_64-win64\make.exe: Leaving directory `D:/fpcupdeluxe/lazarus+fpc+latest/lazarus'
D:\fpcupdeluxe\lazarus+fpc+latest\fpc\bin\x86_64-win64\make.exe: Entering directory `D:/fpcupdeluxe/lazarus+fpc+latest/lazarus'
D:/fpcupdeluxe/lazarus+fpc+latest/fpc/bin/x86_64-win64/make.exe -C ide cleanide
make.exe[1]: Entering directory `D:/fpcupdeluxe/lazarus+fpc+latest/lazarus/ide'
C:/cygwin64/bin/rm.exe -f
C:/cygwin64/bin/rm.exe -f
C:/cygwin64/bin/rm.exe -f
C:/cygwin64/bin/rm.exe -f
C:/cygwin64/bin/rm.exe -f
C:/cygwin64/bin/rm.exe -f
C:/cygwin64/bin/rm.exe -f
C:/cygwin64/bin/rm.exe -f
C:/cygwin64/bin/rm.exe -f
C:/cygwin64/bin/rm.exe -f
C:/cygwin64/bin/rm.exe -f
C:/cygwin64/bin/rm.exe -f
C:/cygwin64/bin/rm.exe -f
C:/cygwin64/bin/rm.exe -f
C:/cygwin64/bin/rm.exe -f
C:/cygwin64/bin/rm.exe -f
C:/cygwin64/bin/rm.exe -f
C:/cygwin64/bin/rm.exe -f
C:/cygwin64/bin/rm.exe -f
C:/cygwin64/bin/rm.exe -f
C:/cygwin64/bin/rm.exe -f
make.exe[1]: Leaving directory `D:/fpcupdeluxe/lazarus+fpc+latest/lazarus/ide'
D:\fpcupdeluxe\lazarus+fpc+latest\fpc\bin\x86_64-win64\make.exe: Leaving directory `D:/fpcupdeluxe/lazarus+fpc+latest/lazarus'
D:\fpcupdeluxe\lazarus+fpc+latest\fpc\bin\x86_64-win64\make.exe: *** No rule to make target `cleanide ide'.  Stop.
Error: (lazarus) Build IDE: stopped with exit code 2
Error: (lazarus) Building IDE: Building IDE failed.
`

For clean builds it is working as intended.

**Comment by LongDirtyAnimAlf** [comment]
I have no clue about this error.
It seems that some binaries of cygwin are used. And that should not happen. And I do not know why.
Closing.
Please re-opem if any new info is available.
