### ISSUE TITLE
Raspberry Pi - Debian 10 Buster - fpc warning

### ISSUE THREAD

**Issue by ertankucukoglu** [LongDirtyAnimAlf/fpcupdeluxe#138]
Hello,

I am using FPCUPdeluxe V1.6.2x for arm-linux-gtk2.

After a successful installation of fpc and lazarus, I get following warnings:
```
Compile Project, Mode: Debug, Target: voltread: Success, Warnings: 2
voltread.lpr(22,1) Warning: "crtbegin.o" not found, this will probably cause a linking failure
voltread.lpr(22,1) Warning: "crtend.o" not found, this will probably cause a linking failure
1022 lines compiled, 27.8 sec
```

There is no such warnings in Debian 9 Stretch system (using fpcupdeluxe installation again). As to information in below thread it has to be added a different path if system is Debian Buster.
https://forum.lazarus.freepascal.org/index.php/topic,46227.msg328873.html#msg328873

I read following "-Fl" line in fpc.cfg file under Buster:
```
# library search path
-Fl/usr/lib/$FPCTARGET;/usr/lib/$FPCTARGET-gnu;/lib/$FPCTARGET;/lib/$FPCTARGET-gnu;/usr/lib/$FPCTARGET-gnueabihf;/usr/lib/gcc/
# end fpcup do not remove
```

When I change that relevant line in fpc.cfg to following (only added one path in the end of line), warnings are no more:
```
# library search path
-Fl/usr/lib/$FPCTARGET;/usr/lib/$FPCTARGET-gnu;/lib/$FPCTARGET;/lib/$FPCTARGET-gnu;/usr/lib/$FPCTARGET-gnueabihf;/usr/lib/gcc/;/usr/lib/gcc/$FPCTARGET-gnueabihf/8/
# end fpcup do not remove
```

I appreciate this modification or a better one to be added in next version, please.

Thanks & regards,
Ertan

**Comment by LongDirtyAnimAlf** [comment]
It should have worked already. But I have improved the GCC detection.

Please try the pre-release:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.2y

**Comment by ertankucukoglu** [comment]
That release is working fine.
