### ISSUE TITLE
Can't install in W10x64 [unable to open file fpcconfig_lazarusidemake.cfg]

### ISSUE THREAD

**Issue by bleuge** [LongDirtyAnimAlf/fpcupdeluxe#141]
Running in a Admin account, also tried to run it as "run as administrator", but also tried in a non-admin acc.
Tried many times, changing options, changing the version I use (currently last stable), but also tried actual prerelease, change paths, tried stable, tried trunk, etc... 
Always stop with:
Fatal: (11009) Unable to open file C:fpcconfig_lazarusidemake.cfg

I tried in a W7x64 (in a non admin account), and work ok.

**Comment by qindj** [comment]
same to me , version V1.6.2y for x86_64-win64-win32 on WIN10

**Comment by LongDirtyAnimAlf** [comment]
Should be solved by latest commits.
Please re-open if issue persists.

**Comment by SuperDisk** [comment]
Problem is still persisting for me.

**Comment by qindj** [comment]
this problem is very strange...
On my win10 laptop, it was "auto" fixed in 3 or 5 versions after V1.6.2.y ...

**Comment by SuperDisk** [comment]
I think I found the reason. In the top left of the window, there's a box for the install directory. It defaults to `C:\fpcupdeluxe` but you need to change it to `C:/fpcupdeluxe` or else you get the error described in this issue. I've had a similar problem where path separators get removed from the path with poorly written GNU tools in the past, so I think it's probably one of those being used under the hood to blame.

![image](https://user-images.githubusercontent.com/1688837/72464554-7f1c9d00-37a3-11ea-99eb-a3a63bfcbe85.png)
