### ISSUE TITLE
Can not build fpc for aarch64 on raspberry pi 4

### ISSUE THREAD

**Issue by costel78** [LongDirtyAnimAlf/fpcupdeluxe#142]
I get the same error trying to compile fpc-3.2.0 no matter if a use fpcupdeluxe (tried both 1.6.2x and 1.6.2y) or if manually compile it on a chroot using static-user qemu on gentoo amd64 machine. Root or normal user make no difference using fpcupdeluxe.

The error is:
make packages_smart FPC=/root/fpcupdeluxe/fpcsrc/compiler/ppca64 FPCFPMAKE=/root/fpcupdeluxe/fpcsrc/compiler/ppca64 RELEASE=1 'OPT=-Sg -vw-n-h-l-d-u-t-p-c-'
make -C packages smart
make -C fpmkunit bootstrap
/root/fpcupdeluxe/fpcsrc/compiler/ppca64 src/fpmkunit.pp  -Fu/root/fpcupdeluxe/fpcsrc/rtl/units/aarch64-linux -FUunits_bs/aarch64-linux -Fu../paszlib/src -Fu../hash/src -Fi../paszlib/src   -Fi../fcl-process/src/unix -Fu../fcl-process/src -Fi../fcl-process/src/linux -Fi../fcl-process/src/dummy -Fu../libtar/src -Sg -vw-n-h-l-d-u-t-p-c-
/root/fpcupdeluxe/fpcsrc/compiler/ppca64 fpmake.pp  -Fu/root/fpcupdeluxe/fpcsrc/packages/fpmkunit/units_bs/aarch64-linux -Fu/root/fpcupdeluxe/fpcsrc/rtl/units/aarch64-linux  -Sg -vw-n-h-l-d-u-t-p-c-
/usr/bin/ld: /usr/lib64/libc_nonshared.a(elf-init.oS): in function `__libc_csu_init':
(.text+0x4c): undefined reference to `_init'
fpmake.pp(49) Error: Error while linking
fpmake.pp(49) Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted
make[1]: *** [Makefile:2681: packages_smart] Error 2
make: *** [Makefile:2836: build-stamp.aarch64-linux] Error 2

fpcupdeluxe: ERROR: FPCNativeInstaller (CleanModule: FPC): Error running make for FPC failed with exit code 512
. Details:

ERROR: Fpcupdeluxe fatal error !

**Comment by LongDirtyAnimAlf** [comment]
> /usr/bin/ld: /usr/lib64/libc_nonshared.a(elf-init.oS): in function __libc_csu_init': (.text+0x4c): undefined reference to _init

The above is a very strange error. I have not a single clue as to why this happens.
I will try to investigate, but with little expectations.

**Comment by LongDirtyAnimAlf** [comment]
Closed due to no feedback. Please re-open if needed.
