### ISSUE TITLE
Consider replacing cpucount.pas with the more effective NumCPULib

### ISSUE THREAD

**Issue by Xor-el** [LongDirtyAnimAlf/fpcupdeluxe#143]
While [cpucount](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/blob/master/cpucount.pas) works, there are scenarios where it just defaults to 1 when it is very possible to get the true CPU count thereby leading to unoptimal performance.
I suggest you replace cpucount.pas with [NumCPULib](https://github.com/Xor-el/NumCPULib4Pascal/blob/master/NumCPULib/src/NumCPULib.pas) which aims to get the true CPU count on all OSes supported by FPC and not just defaulting to 1 as cpucount does.

**Comment by LongDirtyAnimAlf** [comment]
Done:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/4fae0d0f2a7f126d71e0871db79fdac7a1fd0301
Thanks !
