### ISSUE TITLE
Add Linux-musl for i386 and ARM

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#145]
Alpine Linux supports x32, x64, ARM and some others. Pls add x32 and ARM files too.

**Comment by synopse** [comment]
isn't create a link to musl enough?
see e.g. https://hub.docker.com/r/frolvlad/alpine-fpc/dockerfile/

**Comment by Alexey-T** [comment]
Not enough, Musl has different binary loader

**Comment by LongDirtyAnimAlf** [comment]
Please point me to the location of these "files", and I will add them.

**Comment by adromir** [comment]
Just wondering if the crooscompilers for "regular" linux and linux-musl could be seperated? So far they are installed into the same crosscompiler folder, so you can't have both compilers at the same time

**Comment by LongDirtyAnimAlf** [comment]
> tsystem =
>        (
>              system_none,               { 0 }
>              obsolete_system_i386_GO32V1,{ 1 }
>              system_i386_GO32V2,        { 2 }
>              system_i386_linux,         { 3 }
>              system_i386_OS2,           { 4 }
>              system_i386_Win32,         { 5 }
>              system_i386_freebsd,       { 6 }
>              system_m68k_Amiga,         { 7 }
>              system_m68k_Atari,         { 8 }
>              system_m68k_macos,         { 9 }
>              system_m68k_linux,         { 10 }
>              system_m68k_PalmOS,        { 11 }
>              obsolete_system_alpha_linux,{ 12 }
>              system_powerpc_linux,      { 13 }
>              system_powerpc_macos,      { 14 }
>              system_i386_solaris,       { 15 }
>              system_i386_beos,          { 16 }
>              system_i386_netbsd,        { 17 }
>              system_m68k_netbsd,        { 18 }
>              system_i386_Netware,       { 19 }
>              obsolete_system_i386_qnx,  { 20 }
>              system_i386_wdosx,         { 21 }
>              system_sparc_solaris,      { 22 }
>              system_sparc_linux,        { 23 }
>              system_i386_openbsd,       { 24 }
>              obsolete_system_m68k_openbsd,{ 25 }
>              system_x86_64_linux,       { 26 }
>              system_powerpc_darwin,     { 27 }
>              system_i386_EMX,           { 28 }
>              system_powerpc_netbsd,     { 29 }
>              system_powerpc_openbsd,    { 30 }
>              system_arm_linux,          { 31 }
>              system_i386_watcom,        { 32 }
>              system_powerpc_MorphOS,    { 33 }
>              system_x86_64_freebsd,     { 34 }
>              system_i386_netwlibc,      { 35 }
>              system_powerpc_Amiga,      { 36 }
>              system_x86_64_win64,       { 37 }
>              system_arm_wince,          { 38 }
>              obsolete_system_ia64_win64,{ 39 }
>              system_i386_wince,         { 40 }
>              system_x86_6432_linux,     { 41 }
>              system_arm_gba,            { 42 }
>              system_powerpc64_linux,    { 43 }
>              system_i386_darwin,        { 44 }
>              system_arm_palmos,         { 45 }
>              system_powerpc64_darwin,   { 46 }
>              system_arm_nds,            { 47 }
>              system_i386_embedded,      { 48 }
>              system_m68k_embedded,      { 49 }
>              obsolete_system_alpha_embedded,{ 50 }
>              system_powerpc_embedded,   { 51 }
>              system_sparc_embedded,     { 52 }
>              obsolete_system_vm_embedded,{ 53 }
>              obsolete_system_ia64_embedded,{ 54 }
>              system_x86_64_embedded,    { 55 }
>              system_mips_embedded,      { 56 }
>              system_arm_embedded,       { 57 }
>              system_powerpc64_embedded, { 58 }
>              system_i386_symbian,       { 59 }
>              system_arm_symbian,        { 60 }
>              system_x86_64_darwin,      { 61 }
>              system_avr_embedded,       { 62 }
>              system_i386_haiku,         { 63 }
>              system_arm_darwin,         { 64 }
>              system_x86_64_solaris,     { 65 }
>              system_mipseb_linux,       { 66 }
>              system_mipsel_linux,       { 67 }
>              system_i386_nativent,      { 68 }
>              system_i386_iphonesim,     { 69 }
>              system_powerpc_wii,        { 70 }
>              system_x86_64_openbsd,     { 71 }
>              system_x86_64_netbsd,      { 72 }
>              system_powerpc_aix,        { 73 }
>              system_powerpc64_aix,      { 74 }
>              system_jvm_java32,         { 75 }
>              system_jvm_android32,      { 76 }
>              system_arm_android,        { 77 }
>              system_i386_android,       { 78 }
>              system_i8086_msdos,        { 79 }
>              system_mipsel_android,     { 80 }
>              system_mipseb_embedded,    { 81 }
>              system_mipsel_embedded,    { 82 }
>              system_i386_aros,          { 83 }
>              system_x86_64_aros,        { 84 }
>              system_x86_64_dragonfly,   { 85 }
>              system_aarch64_darwin,     { 86 }
>              system_x86_64_iphonesim,   { 87 }
>              system_aarch64_linux,      { 88 }
>              system_i8086_win16,        { 89 }
>              system_i8086_embedded,     { 90 }
>              system_arm_aros,           { 91 }
>              system_wasm_wasm32,        { 92 }
>              system_sparc64_linux,      { 93 }
>              system_sparc64_solaris,    { 94 }
>              system_arm_netbsd,         { 95 }
>              system_riscv32_linux,      { 96 }
>              system_riscv64_linux,      { 97 }
>              system_riscv64_embedded,   { 98 }
>              system_riscv32_embedded,   { 99 }
>              system_aarch64_android,    { 100 }
>              system_x86_64_android,     { 101 }
>              system_x86_64_haiku        { 102 }
>        );                                           
Above is a copy of the FPC compiler info on supported targets.
As you van see, linux-musl is not supported as a separate target.
Therefor, the compiler cannot distinguish between them.

**Comment by LongDirtyAnimAlf** [comment]
Closing due to no feedback.
Please re-open when needed.
