### ISSUE TITLE
Linux-arm cross compiler for original Raspberry Pi ARMV6Z and FPV2

### ISSUE THREAD

**Issue by mriscoc** [LongDirtyAnimAlf/fpcupdeluxe#148]
I have a little problem:

When I use fpcupdeluxe to install a Linux-arm cross compiler, the executable produced by Lazarus runs on Raspberry Pi B2 and B3, but not in the original one. That is because the compiler is using the options: 
Fpcupdeluxe: FPC cross-builder: Building compiler for Linux-arm (OPT: -dFPC_ARMHF ) [CROSSOPT: **-CpARMV7A** **-CfVFPV3** -OoFASTMATH -CaEABIHF ]. The original raspberry pi is **ARMV6Z** and **FPV2**. How can I change those options?

OS: Win10x64
Laz: 2.0.5 x32
FPC: 3.0.4

Thanks.

**Comment by LongDirtyAnimAlf** [comment]
![armsetup](https://user-images.githubusercontent.com/10783972/68051061-cdfb8000-fce6-11e9-8c48-c63939fce424.JPG)

**Comment by LongDirtyAnimAlf** [comment]
Use Setup+ as shown in the above screenshot.

**Comment by mriscoc** [comment]
Thank you, your setup works ok. Maybe in the future will be great if a ARMv6 Item could be added to CPU list to allow to have both cross compilers at the same time.

**Comment by mriscoc** [comment]
Closed
