### ISSUE TITLE
win32-i386 on Windows 10 x64 not working

### ISSUE THREAD

**Issue by TB1234** [LongDirtyAnimAlf/fpcupdeluxe#150]
FPCUPdeluxe V. 1.6.2y x86_64-win64-win32
FP: 3.0.4

I try to create an cross compiler for win32-i386. On Windows 10 x64 that does not work. I got an error from make. FPC told me, the build works without errors and shows me, that the compiler should be available. But it isn't.

    C:/fpcupdeluxe/fpcsrc/compiler/ppc.exe -Ur -Xs -O2 -n -Fi../inc -Fi../x86_64 -FE. -FUC:/fpcupdeluxe/fpcsrc/rtl/units/x86_64-win64 -vw-n-h-l-d-u-t-p-c- -dFPC_SOFT_FPUX80 -dx86_64 -dRELEASE -Fu../inc -Fi../charmaps ../charmaps/cpall.pas
    C:/fpcupdeluxe/fpcsrc/compiler/ppc.exe -Ur -Xs -O2 -n -Fi../inc -Fi../x86_64 -FE. -FUC:/fpcupdeluxe/fpcsrc/rtl/units/x86_64-win64 -vw-n-h-l-d-u-t-p-c- -dFPC_SOFT_FPUX80 -dx86_64 -dRELEASE ../inc/lineinfo.pp
    C:/fpcupdeluxe/fpcsrc/compiler/ppc.exe -Ur -Xs -O2 -n -Fi../inc -Fi../x86_64 -FE. -FUC:/fpcupdeluxe/fpcsrc/rtl/units/x86_64-win64 -vw-n-h-l-d-u-t-p-c- -dFPC_SOFT_FPUX80 -dx86_64 -dRELEASE ../inc/lnfodwrf.pp
    C:/fpcupdeluxe/fpcbootstrap/make.exe 'FPC=C:/fpcupdeluxe/fpcsrc/compiler/ppc.exe' OS_TARGET=win64 CPU_TARGET=x86_64 PPC_TARGET=i386 EXENAME=ppcross386.exe CROSSBINDIR= BINUTILSPREFIX= CROSSCYCLEBOOTSTRAP=1 cycleclean compiler CYCLELEVEL=2
    C:/fpcupdeluxe/fpcbootstrap/make.exe -C utils cleanall
    C:/fpcupdeluxe/fpcsrc/compiler/ppc.exe -Ur -Xs -O2 -n -Fui386 -Fusystems -FuC:/fpcupdeluxe/fpcsrc/rtl/units/x86_64-win64 -Fii386 -FE. -FUi386/units/x86_64-win64 -dRELEASE -vw-n-h-l-d-u-t-p-c- -dFPC_SOFT_FPUX80    -dREVINC -di386 -dGDB -dBROWSERLOG -Fux86 -Sew pp.pas
    fpcdefs.inc(259,2) Error: User defined: Cross-compiling from systems without support for an 80 bit extended floating point type to i386 is not yet supported at this time
    fpcdefs.inc(259,2) Error: User defined: Cross-compiling from systems without support for an 80 bit extended floating point type to i386 is not yet supported at this time
    fpcdefs.inc(259,2) Error: User defined: Cross-compiling from systems without support for an 80 bit extended floating point type to i386 is not yet supported at this time
    fpcdefs.inc(259,2) Error: User defined: Cross-compiling from systems without support for an 80 bit extended floating point type to i386 is not yet supported at this time
    constexp.pas(87,1) Fatal: There were 4 errors compiling module, stopping
    Fatal: Compilation aborted
    make.exe[1]: *** [cycle] Error 2
    C:\fpcupdeluxe\fpcbootstrap\make.exe: *** [compiler_cycle] Error 2
    fpcupdeluxe: info: FPCCrossInstaller (BuildModuleCustom: FPC): Running cross compiler fpc make for i386-win32 failed with an error code. Optional module; continuing regardless.
    SUCCESS: Fpcupdeluxe ended without errors.

Any ideas what I can do, or it is not possible to create a i386 compiler on Win10 x64?

But also the FPCUP should regocnize that the build failed.

**Comment by LongDirtyAnimAlf** [comment]
As the error shows: not possible with 3.0.4 due to lacking support for 80 bit float.
This is only possible with trunk or fixes 3.2

**Comment by TB1234** [comment]
Thank you! After moving to the trunk version, everything works fine! :)
