### ISSUE TITLE
Pi1 A (for laughs)

### ISSUE THREAD

**Issue by peardox** [LongDirtyAnimAlf/fpcupdeluxe#151]
Didn't think it'd work...

To be fair to FPCUpdeluxe it's almost 7 years old, the first model released with 256M Ram - the first column of https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications

==========================
simon@pi1:~/src $ cat /proc/cpuinfo
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 0002
Serial          : 0000000064a65344

simon@pi1:~/src $ ./fpcupdeluxe-armv6hf-linux 
An unhandled exception occurred at $00026320:
EAccessViolation: Access violation
  $00026320

**Comment by LongDirtyAnimAlf** [comment]
It would have been nice if fpcupdeluxe would run on RPi 1
If I have some extra spare time, I will investigate this.
Closing for now.
