### ISSUE TITLE
Running make for FPC failed with exit code 2

### ISSUE THREAD

**Issue by rchastain** [LongDirtyAnimAlf/fpcupdeluxe#152]
Hello! Congratulations for your nice software. I used it successfully some time ago, but today my attempt failed. There seems to be an issue with _make.exe_. Log file attached.
[error.txt](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/3828723/error.txt)

Best regards.
Roland

**Comment by LongDirtyAnimAlf** [comment]
Confirmed. Will look into it !

**Comment by LongDirtyAnimAlf** [comment]
Should be solved with latest release.

**Comment by rchastain** [comment]
Thank you for the latest release. I tried to install FPC trunk. I got a message "unexpected exception" from fpcupdeluxe. But it seems that the installation is done.
The last line of the output was:
`Installation package utils-pas2js for target x86_64-win64 succeeded`
I tried twice and the same thing happened each time.
Log attached.
Regards.
Roland
[fpcupdeluxe-x86_64-win64.log](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/3830233/fpcupdeluxe-x86_64-win64.log)

**Comment by LongDirtyAnimAlf** [comment]
Confirmed. Looking into it again.

**Comment by LongDirtyAnimAlf** [comment]
Seems something was wrong with the SVN server.
If you delete the Lazarus sources and run again, does that work ?

**Comment by rchastain** [comment]
After removing _C:\fpcupdeluxe_ and retrying, installation successful. Thank you!
