### ISSUE TITLE
Error on linking Lazarus library when cross compile from Win64 to Linux x64

### ISSUE THREAD

**Issue by datiscum** [LongDirtyAnimAlf/fpcupdeluxe#156]
I installed fpcupdatedeluxe (V091 20191110) the first time on the system yesterday.

Compiling a win64(nativ)/win32 library will work OK.

Crosscompile win32 will work.

With crosscompile the following error occurs when linking:
D:\FPC_3_2\cross\bin\x86_64-linux\x86_64-linux-ld.exe: cannot find /lib64/ld-linux-x86-64.so.2

The folder lib64 does not exist in the path (D:\FPC_3_2\cross\lib\x86_64-linux\) that was created automatically.
Alle .so files are directly under "D:\FPC_3_2\cross\lib\x86_64-linux\".
Creating a new lib64 folder in it didn't help either.
I could only help myself by adding a new line in fpc.cfg.

#IFDEF FPC_CROSSCOMPILING
#IFDEF LINUX
#IFDEF CPUX86_64
#- Inserted by fpcup 13.11.2019 23:24:51
-FDD:\FPC_3_2\cross\bin\x86_64-linux\
-XPx86_64-linux-
-FlD:\FPC_3_2\cross\lib\x86_64-linux\
-Xr/usr/lib
#- I have added the next line so that the lbrary can be linked.
-FL D:\FPC_3_2\cross\lib\x86_64-linux\ld-linux-x86-64.so.2
#ENDIF
#ENDIF
#ENDIF

Is there a better solution to this problem ?

**Comment by LongDirtyAnimAlf** [comment]
I have done a lot of effort, but I cannot reproduce this error !
Perhaps you have more luck with the new release:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.4e

**Comment by Alexey-T** [comment]
1.6.4e - now I see error
```
Compile Project, OS: haiku, Target: project1: Exit code 1, Errors: 3
Error: /home/user/fpcupdeluxe/cross/bin/x86_64-haiku/x86_64-unknown-haiku-ld: /usr/lib/gcc/x86_64-linux-gnu/7/crtbegin.o: relocation R_X86_64_32 against hidden symbol `__TMC_END__' can not be used when making a shared object
Error: /home/user/fpcupdeluxe/cross/bin/x86_64-haiku/x86_64-unknown-haiku-ld: final link failed: nonrepresentable section on output
project1.lpr(21,1) Error: Error while linking
```

**Comment by LongDirtyAnimAlf** [comment]
My bad.
Please download again:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/1.6.4e/fpcupdeluxe-x86_64-linux

**Comment by Alexey-T** [comment]
Again the same error..

**Comment by Alexey-T** [comment]
Ops, ignore my above comment, wrong issue

**Comment by datiscum** [comment]
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.4e didn't do the trick

**Comment by datiscum** [comment]
Please generate the following line in the fpc.cfg:
(The path must of course be changed during the installation)
-XRD:\FPC_3_2\cross\lib\x86_64-linux\

Completet it should look like this.

# begin fpcup do not remove x86_64-linux
# cross compile settings dependent on both target OS and target CPU
#IFDEF FPC_CROSSCOMPILING
#IFDEF LINUX
#IFDEF CPUX86_64
# Inserted by fpcup 13.11.2019 23:24:51
-FDD:\FPC_3_2\cross\bin\x86_64-linux\
-XPx86_64-linux-
-FlD:\FPC_3_2\cross\lib\x86_64-linux\
-Xr/usr/lib
-XRD:\FPC_3_2\cross\lib\x86_64-linux\
#ENDIF
#ENDIF
#ENDIF
# end fpcup do not remove

Now I can create a Linux Library (.so) file under Win64.

Thanks,
