### ISSUE TITLE
Haiku libs - more files required

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#157]
On starting CudaText, i see error msg.
These .so links are visible in the libQt5Pas.so file at the end of file!

![qq](https://user-images.githubusercontent.com/4154978/68938475-83323b80-07af-11ea-9c76-841eabd3524d.png)

**Comment by Alexey-T** [comment]
Pls test with CudaText binary:
http://www.uvviewsoft.com/cudatext/files/haiku/

**Comment by LongDirtyAnimAlf** [comment]
Well, for sure, you need to have QT5 installed  to run a QT5 app !!
