### ISSUE TITLE
Error running cocoa version of the app on Cataline

### ISSUE THREAD

**Issue by margerum** [LongDirtyAnimAlf/fpcupdeluxe#159]
When I try to run `fpcupdeluxe-x86_64-darwin-cocoa.app` from finder, I get "The application ... can't be opened".

If I try to run it from the terminal 

`open -a fpcupdeluxe-x86_64-darwin-cocoa.app`

I get 

`LSOpenURLsWithRole() failed for the application /Users/michaelmargerum/Desktop/fpcdeluxe/fpcupdeluxe-x86_64-darwin-cocoa.app with error -10810.`

This is 1.64d and 1.64e that I am seeing this issue

**Comment by qindj** [comment]
@margerum 
It seems that the app is not executable (without enough permissions).

try: 
1. open the terminal
2. cd to the folder you put fpcupdeluxe
3. sudo chmod +x fpcupdeluxe-x86_64-darwin-cocoa.app/Contents/MacOS/fpcupdeluxe-x86_64-darwin-cocoa
4. try open it again

**Comment by messiashenrique** [comment]
> @margerum
> It seems that the app is not executable (without enough permissions).
> 
> try:
> 
>     1. open the terminal
> 
>     2. cd to the folder you put fpcupdeluxe
> 
>     3. sudo chmod +x fpcupdeluxe-x86_64-darwin-cocoa.app/Contents/MacOS/fpcupdeluxe-x86_64-darwin-cocoa
> 
>     4. try open it again

Yes!!! It work! Excellent help! Thanks!

**Comment by qindj** [comment]
> > @margerum
> > It seems that the app is not executable (without enough permissions).
> > try:
> > ```
> > 1. open the terminal
> > 
> > 2. cd to the folder you put fpcupdeluxe
> > 
> > 3. sudo chmod +x fpcupdeluxe-x86_64-darwin-cocoa.app/Contents/MacOS/fpcupdeluxe-x86_64-darwin-cocoa
> > 
> > 4. try open it again
> > ```
> 
> Yes!!! It work! Excellent help! Thanks!

Never mind! Glad to help!

**Comment by LongDirtyAnimAlf** [comment]
Good to hear.
But this remains strange.

When building the zip, the executable flag is set for fpcupdeluxe.
This works perfect on all OSX versions, but Catalina.

I guess its a safety feature.

**Comment by qindj** [comment]
Upgraded to Catalina last month , has many problems relative to Lazarus, such as "can't link library, ld: -liconv", have to run "xcode-select --install"
