### ISSUE TITLE
unit math missing for cross compiler jvm-android V1.6.4e for x86_64-linux-gtk2

### ISSUE THREAD

**Issue by Morabaraba** [LongDirtyAnimAlf/fpcupdeluxe#160]
I build the stable fpc and laz from svn 100%. But then i try to install the jvm-android cross compiler and get the following error:

```sh
ucomplex.pp(26,10) Fatal: Can't find unit math used by UComplex
```

For the whole [FPCUPdeluxe V1.6.4e for x86_64-linux-gtk2 output](https://pastebin.com/5QFB67DS).

This is on ubuntu 64-bit.

```sh
uname -a
Linux db-vb 5.0.0-31-generic #33-Ubuntu SMP Mon Sep 30 18:51:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Any suggestions would be appreciated.

**Comment by LongDirtyAnimAlf** [comment]
Closing due to no feedback.
Please re-open when needed.
