### ISSUE TITLE
cross-binutils installed in un-workable directory on Windows.

### ISSUE THREAD

**Issue by chapmanworld** [LongDirtyAnimAlf/fpcupdeluxe#161]
First up - big thanks for fpcupdeluxe, it's been a massive help to me!
I just installed fpc+laz on windows, and then installed the linux x86_64 cross compiler. My base directory is "C:\lazarus" and so the cross-binutils are installed under "c:\lazarus\cross\" and the libs therefore "C:\lazarus\cross\lib\x86_64-linux"

When linking a regular (lcl) application, this works fine, but if you select "File / New / Library" from the lazarus menu, to build a ".so" project, the linker fails to find  "ld-linux-x86-64.so.2"  which is in the directory "C:\lazarus\cross\lib\x86_64-linux"

Resolving this means adding an option "-XRC:\lazarus\cross\lib\x86_64-linux" to the FPC configuration, but unfortunately the linker appears to be hard coded to expect it's lib files under a "lib64" directory. So along with the above compiler switch, the .so files from the cross compiler must be moved to "C:\lazarus\cross\lib\x86_64-linux\lib64" 

It would be helpful if fpcupdeluxe could place the .so files in this directory "C:\lazarus\cross\lib\x86_64-linux\lib64" and conditionally add the "-XRC:\lazarus\cross\lib\x86_64-linux" option to fpc.cfg

Thanks!

**Comment by chapmanworld** [comment]
++ This probably affects other cross-compilers on windows, I've yet to test it.

**Comment by LongDirtyAnimAlf** [comment]
Please have a look inside libc.so
I suspect this is a text-file, that includes some files with a path.
Please remove the path of these included files and try again !

**Comment by chapmanworld** [comment]
There doesn't appear to be any mention of 'lib64' in libc.so...

/* GNU ld script
   Use the shared library, but some functions are only in
   the static library, so try that secondarily.  */
OUTPUT_FORMAT(elf64-x86-64)
GROUP ( libc.so.6 libc_nonshared.a  AS_NEEDED ( ld-linux-x86-64.so.2 ) )

**Comment by LongDirtyAnimAlf** [comment]
Thanks for the feedback.

I have tried to use -XR in the past. But this resulted in crashing apps due to FPC bugs.

One is already solved.
https://bugs.freepascal.org/view.php?id=36345

I have created a new bug-report:
https://bugs.freepascal.org/view.php?id=36395

**Comment by LongDirtyAnimAlf** [comment]
The bugs are resolved by FPC developers.
But I am still waiting for some more feedback.

**Comment by LongDirtyAnimAlf** [comment]
Would you mind trying the latest release of fpcupdeluxe ?

Please use it to update FPC.
It will patch the FPC sources, so cross-linking of a library will succeed.
Please test of the resulting library works on the target system.

Thanks.

**Comment by chapmanworld** [comment]
Thank you.
I'm trying to test but the current fpc trunk does not build for cross-compile:
  system.pp(704,1) Fatal: Internal error 2015030501
I'll keep trying various revisions and update here.

**Comment by LongDirtyAnimAlf** [comment]
Thanks !

**Comment by chapmanworld** [comment]
This is all working now.

Out of the box, built trunk fpc+laz for windows, added cross compiler for linux. (all x64).
I tested building and consuming both a DLL on Windows and a Shared Object on Linux, and was able to call the exported method. 

Great work, thank you for the fix!
