### ISSUE TITLE
removing a compiler will rm -rf all your files (the entire current working directory from where you started it)

### ISSUE THREAD

**Issue by prof7bit** [LongDirtyAnimAlf/fpcupdeluxe#162]
I just deleted my entire downloads folder because I ran fpcupdeluxe from within it.

Operating system: Kubuntu Bionic LTS, 64 bit
fpcupdeluxe: 1.6.4h

steps to reproduce:

**WARNING**

Do not do this from within any important folder, make a new empty folder, copy fpcupdeluxe into it and **change into this directory** (important!) before you begin, otherwise **it will rm -rf all your files and folders!**

* install the fixes branches of fpc and lazarus
* install a cross compiler (for example windows-i386)
* click the "remove compiler" button

Expected result: It does what it says.
Actual result: It does what it says and then it goes on and also deletes the entire current working directory including itself!

**Comment by prof7bit** [comment]
**WARNING**

**Do not do this from within any important folder, make a new empty older, copy fpcupdeluxe into it and change into this directory before you begin, otherwise it will rm -rf all your files and folders!**

it is even easier to reproduce:

* download fpcupdeluxe-x86_64-linux, make it executable
* make sore there are no ini files for it already
* also make sure there is no install dir already
* go to the cross tab, select i386 windows, click "remove compiler"

It will create the following output:

````

FPCUPdeluxe V1.6.4h for x86_64-linux-gtk2

FPCUP(deluxe) is starting up.

Bootstrap dir:         /home/bernd/fpcupdeluxe/fpcbootstrap
FPCupdeluxe basedir:   /home/bernd/fpcupdeluxe
FPC URL:               https://svn.freepascal.org/svn/fpc/tags/release_3_0_4
FPC options:           
FPC source directory:  /home/bernd/fpcupdeluxe/fpcsrc
FPC install directory: /home/bernd/fpcupdeluxe/fpc
Lazarus URL:           https://svn.freepascal.org/svn/lazarus/tags/lazarus_2_0_6
Lazarus options:       
Lazarus directory:     /home/bernd/fpcupdeluxe/lazarus

Please stand back and enjoy !

fpcupdeluxe: info: Non existing directory: /home/bernd/fpcupdeluxe. Going to create it.
fpcupdeluxe: info: 3-12-19 09:10:19: fpcupdeluxe: V095 (20191203) started.
fpcupdeluxe: info: LazarusCrossInstaller (CleanModule: LCL): No Lazarus source [yet] ... nothing to be done
fpcupdeluxe: info: LazarusCrossInstaller (CleanModule: LCL): Error deleting LCL directory /home/bernd/fpcupdeluxe/lazarus/lcl/units/i386-win32
fpcupdeluxe: info: LazarusCrossInstaller (CleanModule: Components): No Lazarus source [yet] ... nothing to be done
fpcupdeluxe: info: LazarusCrossInstaller (CleanModule: Components): Error deleting Components directory /home/bernd/fpcupdeluxe/lazarus/components/lazutils/lib/i386-win32
fpcupdeluxe: info: LazarusCrossInstaller (CleanModule: Packager): No Lazarus source [yet] ... nothing to be done
fpcupdeluxe: info: LazarusCrossInstaller (CleanModule: Packager): Error deleting Packager directory /home/bernd/fpcupdeluxe/lazarus/packager/units/i386-win32
fpcupdeluxe: info: FPCCrossInstaller (CleanModule: FPC): No FPC source [yet] ... nothing to be done
````
then **the contents of the current working directory will be deleted!** If you run it from within your home dir then may the backup gods have mercy upon your soul!

**Comment by LongDirtyAnimAlf** [comment]
Will work on this right away !!
Sorry for this very serious bugger !!

**Comment by prof7bit** [comment]
here is an strace from when it happens:

[fpcuptrace.txt](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/3915609/fpcuptrace.txt)

I started it in the folder /home/bernd/opt/fpcup/ which I made for this purpose and when you grep the strace file you will find 4 occurrences of unlink:

```
[pid 12063] unlink("/home/bernd/opt/fpcup/fpcupdeluxe-x86_64-linux") = 0
[pid 12063] unlink("/home/bernd/opt/fpcup/fpcup.ini") = 0
[pid 12063] unlink("/home/bernd/opt/fpcup/fpcupdeluxe.ini") = 0
[pid 12063] unlink("/home/bernd/opt/fpcup/settings.ini") = 0

```

**Comment by prof7bit** [comment]
I am trying to debug it.

First I tried to pause it immediately before it happens, for this I inserted this instrumentation into installerManager.pas in TSequencerRun() around line 1742

````
if FStateMachine[InstructionPointer].param = 'FPC' then begin
  if FStateMachine[InstructionPointer].instr = SMuninstallmodule then begin
    infoln('foo'); // <-- set breakpoint here
  end;
end;
````

Now I can single step only a few more steps until I find this:

installerFpc.pas, function TFPCCrossInstaller.UnInstallModule, line 1244
````
if DeleteDirectoryEx(aDir)=false then
````
The variable aDir has a value of '' and in DeleteDirectory this will be expanded to be the current working directory. This one call of DeleteDirectory will then recursively delety the entire working directory! One step beyond line 1244 in the debugger and all files are gone!

The question is: why can aDir be '' and should DeleteDir even attempt to do anything when called with an empty string?

Why is BinUtilsPath an empty string, is it maybe because the binutlis have been already installed on my machine by other means and not by fpcupdeluxe? I seem to have no problem building cross compilers and using them on this machine, something must be wrong with that code that results in an empty string for BinUtilsPath although it says BinsAvailable = True.

Please tell me which part I should debug next on my machine to find the reason if you cannot reproduce it on yours, I will try to help.

**Comment by prof7bit** [comment]
The same hapens a second time a few lines further down at line 1266, the LibsPath is also an empty string.

**Comment by LongDirtyAnimAlf** [comment]
It was bad coding.
I am revising it all !!

**Comment by LongDirtyAnimAlf** [comment]
If you dare, you might try:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.6a

**Comment by prof7bit** [comment]
Seems to work, it did not delete any wrong files anymore. I will continue to use this version to see whether there are any regressions but so far it looks good.

Thank you for reacting so fast and providing a fix!

**Comment by LongDirtyAnimAlf** [comment]
Thanks for reporting and testing !
