### ISSUE TITLE
Strange issue when reporting number of cores

### ISSUE THREAD

**Issue by Xor-el** [LongDirtyAnimAlf/fpcupdeluxe#163]
Hello, I noticed something strange today with fpcupdeluxe when reporting number of cores on my FreeBSD machine.

If I download the already compiled fpcupdeluxe binary and run it, it reports my number of cores as 1 even though I have 2 cores in my FreeBSD machine.
But if I download the source and compile fpcupdeluxe *on my FreeBSD machine*, it reports the correct number of cores.
I guess this might be an issue with the cross compiler not correctly identifying that it is compiling for a FreeBSD machine.

**Comment by LongDirtyAnimAlf** [comment]
Fpcupdeluxe does not use all available cores !

It reports the amount of cores it uses.
And that depends also on the amount of available memory !

But this is a strange issue.

**Comment by Xor-el** [comment]
Yes, it's strange indeed.

**Comment by LongDirtyAnimAlf** [comment]
As I have no idea about this, I will close this issue.
Please re-open when needed.
