### ISSUE TITLE
[feature-request] button to recreate the shortcut or instructions to do it manually

### ISSUE THREAD

**Issue by cpicanco** [LongDirtyAnimAlf/fpcupdeluxe#164]
Does it make any sense to you? Today I reopened an old folder and I simply don't know where is the god damnt short cut to start lazarus. Sorry for the words, my bad. Just love you guys.

**Comment by LongDirtyAnimAlf** [comment]
Will be available in next release (on Extra-Sheet) !

**Comment by cpicanco** [comment]
Thank you @LongDirtyAnimAlf

**Comment by LongDirtyAnimAlf** [comment]
You might try:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.6a

**Comment by cpicanco** [comment]
Excelent! Will try it today!
