### ISSUE TITLE
FPC Version: fixes3.2 and Lazarus Version: fixes2.0, does not continue installing

### ISSUE THREAD

**Issue by tr3esoftware** [LongDirtyAnimAlf/fpcupdeluxe#165]
FPC Version: fixes3.2 and Lazarus Version: fixes2.0, does not continue installing

It stands infinitely at: FPCNativeInstaller (GetFile): Downloading https://svn.freepascal.org/svn/lazarus/binaries/x86_64-win64/gdb/bin

**Comment by LongDirtyAnimAlf** [comment]
Would you mind trying this pre-release ?

https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.6b

**Comment by LongDirtyAnimAlf** [comment]
Due to no feedback, I will close.
But please re-open if needed !
