### ISSUE TITLE
DragonFly cross from Linux x64 is broken?

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#166]
Last deluxe, on making empty form app, i got FPC 3.3 error
Error: /home/user/fpcupdeluxe/cross/bin/x86_64-dragonfly/x86_64-unknown-dragonfly-ld: /home/user/fpcupdeluxe/cross/lib/x86_64-dragonfly//libc.so: .dynsym local symbol at index 4 (>= sh_info of 2)

Lazarus 2.1.0 r62405 FPC 3.3.1 x86_64-linux-gtk2

**Comment by Alexey-T** [comment]
To test it in lazarus, just apply the patch
https://bugs.freepascal.org/view.php?id=36409

**Comment by LongDirtyAnimAlf** [comment]
Yes, you will receive this error.
And you can Google this error.
The app will just build fine and run on the Dragon.
This error can be skipped. Its a binutils thing.

Please re-open in case of any problems regarding this.
