### ISSUE TITLE
Install version trunkgit FPC and Lazarus in linux debian 64bits

### ISSUE THREAD

**Issue by StraightFree** [LongDirtyAnimAlf/fpcupdeluxe#167]
Hello dear,

I want to do tests on rtti and custom attributes. In this forum (https://forum.lazarus.freepascal.org/index.php/topic,47769.0.html) I was told that the trunkgit version supports this feature.

I tried to install the trunkgit version of FPC and Lazarus.
According to the figure:

![image](https://user-images.githubusercontent.com/39309001/71100051-15ed3e00-2193-11ea-983e-762dbc95a056.png)

The installation of FPC occurred without any error.
However, in the installation of Lazarus gave the following error.

`
fpcupdeluxe: info: Lazarus native builder: Detected source version Lazarus: 2.1.0
fpcupdeluxe: info: Lazarus native builder: Using FPC compiler with version: 3.3.1
fpcupdeluxe: info: LazarusNativeInstaller (BuildModuleCustom: Lazbuild): Running: make lazbuild
fpcupdeluxe: info: LazarusNativeInstaller (BuildModuleCustom: Lazbuild): make. Params: FPC=/home/administrador/Documentos/dev/fpcupdeluxe/trunkgit/fpc/bin/x86_64-linux/fpc.sh,PP=/home/administrador/Documentos/dev/fpcupdeluxe/trunkgit/fpc/bin/x86_64-linux/ppcx64,USESVN2REVISIONINC=0,--directory=.,PREFIX=/home/administrador/Documentos/dev/fpcupdeluxe/trunkgit/lazarus,INSTALL_PREFIX=/home/administrador/Documentos/dev/fpcupdeluxe/trunkgit/lazarus,FPCDIR=/home/administrador/Documentos/dev/fpcupdeluxe/trunkgit/fpcsrc,FPCMAKE=/home/administrador/Documentos/dev/fpcupdeluxe/trunkgit/fpc/bin/x86_64-linux/fpcmake,PPUMOVE=/home/administrador/Documentos/dev/fpcupdeluxe/trunkgit/fpc/bin/x86_64-linux/ppumove,OPT=-vw-n-h-l-d-u-t-p-c-,lazbuild
Executing: make FPC=/home/administrador/Documentos/dev/fpcupdeluxe/trunkgit/fpc/bin/x86_64-linux/fpc.sh PP=/home/administrador/Documentos/dev/fpcupdeluxe/trunkgit/fpc/bin/x86_64-linux/ppcx64 USESVN2REVISIONINC=0 --directory=. PREFIX=/home/administrador/Documentos/dev/fpcupdeluxe/trunkgit/lazarus INSTALL_PREFIX=/home/administrador/Documentos/dev/fpcupdeluxe/trunkgit/lazarus FPCDIR=/home/administrador/Documentos/dev/fpcupdeluxe/trunkgit/fpcsrc FPCMAKE=/home/administrador/Documentos/dev/fpcupdeluxe/trunkgit/fpc/bin/x86_64-linux/fpcmake PPUMOVE=/home/administrador/Documentos/dev/fpcupdeluxe/trunkgit/fpc/bin/x86_64-linux/ppumove OPT=-vw-n-h-l-d-u-t-p-c- lazbuild (working dir: /home/administrador/Documentos/dev/fpcupdeluxe/trunkgit/lazarus)
make -C packager/registration
/home/administrador/Documentos/dev/fpcupdeluxe/trunkgit/fpc/bin/x86_64-linux/fpc.sh -MObjFPC -Scghi -O1 -g -gl -l -vewnhibq -Fu. -Fu/home/administrador/Documentos/dev/fpcupdeluxe/trunkgit/fpcsrc/rtl -FE. -FU../units/x86_64-linux -Cg -vw-n-h-l-d-u-t-p-c- -dx86_64 fcllaz.pas
(1002) Target OS: Linux for x86-64
(3104) Compiling fcllaz.pas
Fatal: (10022) Can't find unit system used by fcllaz
Fatal: (1018) Compilation aborted
Error: /home/administrador/Documentos/dev/fpcupdeluxe/trunkgit/fpc/bin/x86_64-linux/ppcx64 returned an error exitcode
make: *** [Makefile:3253: registration] Error 2
fpcupdeluxe: ERROR: LazarusNativeInstaller (BuildModuleCustom: Lazbuild): make returned error code #512`

`ERROR: Fpcupdeluxe fatal error !`

Does anyone know why I'm having this error or have any suggestions to fix?

Thank you all for the attention!

**Comment by LongDirtyAnimAlf** [comment]
Would you mind trying the newest release ?

**Comment by StraightFree** [comment]
> Would you mind trying the newest release ?

Thank you for your work.

It worked perfectly on the new release 1.6.6c.

Following the guidance of this topic (https://forum.lazarus.freepascal.org/index.php/topic,47835.0.html) I was able to install earlier with release 1.6.4h.

Thanks again for your attention.

**Comment by LongDirtyAnimAlf** [comment]
You're welcome.
