### ISSUE TITLE
Does not work on linux with qt 5.14

### ISSUE THREAD

**Issue by sgmihai** [LongDirtyAnimAlf/fpcupdeluxe#168]
Trying to install fpc stable + lazarus stable:
Please stand back and enjoy !
fpcupdeluxe: info: 26-12-19 22:50:29: fpcupdeluxe: V099 (20191220) started.

fpcupdeluxe: Got an unexpected exception ... don't know what to do unfortunately.

Same behaviour on qt 5.13 before I upgraded.
No other error messages, no logs.
How to reproduce. Install a linux distribution with a kde plasma (like manjaro kde, which I am using) and run fpcupdeluxe-x86_64-linux-qt5 (downloaded the latest from releases).

**Comment by Alexey-T** [comment]
Run it from Terminal to see lib errors from OS
Maybe mussed libqt5pas???

**Comment by LongDirtyAnimAlf** [comment]
Please try newest release:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.6d

**Comment by sgmihai** [comment]
Fixed ! Got fpc+laz trunk installed from it. thanks.
