### ISSUE TITLE
App from c:\fpcupdeluxe304 overwrote files from c:\fpcupdeluxe

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#170]
I had FPC 3.3 in c:\fpcupdeluxe.
now I need separate dir with FPC 3.0.4 and so copied fresh Deluxe into c:\fpcupdeluxe304.
But it overwrote FPC 3.3 with my choice of 3.0.4 and broke that old folder of FPC 3.3.
It didnt install FPC|Laz into c:\fcpupdeluxe304.

**Comment by LongDirtyAnimAlf** [comment]
Correct. Confirmed.
New (upcoming) release (1.6.8a) will solve.
