### ISSUE TITLE
Issue downloading CrossLib Tools when trying to install OpenBSD x86_64 Cross Compiler

### ISSUE THREAD

**Issue by Xor-el** [LongDirtyAnimAlf/fpcupdeluxe#171]
Hi, I tried installing OpenBSD x86_64 cross compiler on my Windows PC but it seems like the CrossLib Tools link is invalid as FPCUPDeluxe could not download it.
could you please check this out. Thanks.

**Comment by Xor-el** [comment]
Error message

> 
> Fpcupdeluxe failed due to missing cross binary tools.
> Looking for fpcupdeluxe cross-tools on GitHub (if any).
> Going to download the right cross-bins. Can (will) take some time !
> Please wait: Going to download the zip binary-tools from https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/wincrossbins_v1.0/WinCrossBinsOpenBSDx64.zip
> Please wait: Going to download the rar binary-tools from https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/wincrossbins_v1.0/WinCrossBinsOpenBSDx64.rar
> No luck in getting then cross-tools ... aborting.

**Comment by Alexey-T** [comment]
#169

**Comment by Xor-el** [comment]
Thanks for the information.
