### ISSUE TITLE
Issue Cross Compiling from Windows to Solaris x86_64

### ISSUE THREAD

**Issue by Xor-el** [LongDirtyAnimAlf/fpcupdeluxe#172]
Hi, I can cross compile from my Win 64 box to Solaris x86_64 but linking fails.

I get the Error message 

> Error while linking

This error happens on Today's Trunk and cross compiler

**Comment by LongDirtyAnimAlf** [comment]
Should be solved by now.
New releases and new libs.
Please re-open when needed.
