### ISSUE TITLE
Cross Compiled Lazarus GUI App complains about missing dependency

### ISSUE THREAD

**Issue by Xor-el** [LongDirtyAnimAlf/fpcupdeluxe#173]
![VirtualBox_GhostBSD 19 09 64-bits_12_01_2020_17_26_08](https://user-images.githubusercontent.com/12124088/72222089-57d68d80-3561-11ea-9900-198940e437e6.png)

Do note that this is just a basic empty Lazarus GUI app.

**Comment by levzenin** [comment]
> ![VirtualBox_GhostBSD 19 09 64-bits_12_01_2020_17_26_08](https://user-images.githubusercontent.com/12124088/72222089-57d68d80-3561-11ea-9900-198940e437e6.png)
> 
> Do note that this is just a basic empty Lazarus GUI app.

Provide more information please.
- Operating System(s?)
- Architecture
- FPC and Lazarus versions

**Comment by gcarreno** [comment]
Hey @Xor-el ,

If you cross compile from Ubuntu latest and then run your app on some other distribution with outdated/different libs( like RaspberryPi ), this will sometimes happen.

This happens regardless of what distribution you use, as long as they differ in terms of installed dynamic libs.

Remember that you have to make sure that the application you compile is dynamically linked with the same `*.dll` or `*.so` libraries on the compile machine, that exist on the run machine.

On Linux a simple `ldd lazarus-application` will inform you of the dynamically linked libraries that said application needs to run. This is done on the linking phase of when Lazarus compiles and links said `lazarus-application`.

On the compile machine you will have no missing ones, on the running machine the same command will inform you which ones are either missing **OR** have different versions.

You can solve this in one of two ways:
1. Make sure compile system has same dyn libs as running system.
  * `ldconfig -p` will give you complete list of dyn libs.
2. Don't cross compile. After all, Free Pascal has the motto: "Write once, **compile** anywhere", Right?

This has nothing to do with `fpcupdeluxe` and you should close this issue, please.

Cheers,
Gus

P.S.: I'm sorry if I come across as a bit condescending. Not my intention at all, just trying to cover all the angles.

**Comment by LongDirtyAnimAlf** [comment]
Closing due to no feedback.
