### ISSUE TITLE
ld-musl-x86_64

### ISSUE THREAD

**Issue by JonnyTech** [LongDirtyAnimAlf/fpcupdeluxe#174]
Installing trunk versions adds `-FL/lib/ld-musl-x86_64.so.1` to the end of `fpc/bin/x86_64-linux/fpc.cfg` which breaks building with errors like `Error loading shared library` and `Error relocating symbol not found`. Removing the line fixes building - on Linux x64.

**Comment by LongDirtyAnimAlf** [comment]
This is definitely a bad bugger. Will investigate.

**Comment by LongDirtyAnimAlf** [comment]
Please give me somewhat more info about:
your system
fpcupdeluxe version
a copy of the command screen after using fpcupdeluxe (right-click; select and copy).

**Comment by JonnyTech** [comment]
Release v1.6.8a of fpcupdeluxe-x86_64-linux on Debian Buster.

Going to package manager and removing anything containing `musl` then rerunning fpcupdeluxe fixed the issue.

Did not keep logs but can recreate if necessary.

**Comment by LongDirtyAnimAlf** [comment]
Now this becomes clear. Will be solved in the next release !
Thanks for reporting.

**Comment by JonnyTech** [comment]
Great! Thanks for the quick response. I shall close this and reopen if it occurs after future updates.
