### ISSUE TITLE
Add confirmation dialog before installing.

### ISSUE THREAD

**Issue by pakLebah** [LongDirtyAnimAlf/fpcupdeluxe#175]
Please, add confirmation dialog before installing anything. The confirmation dialog should also explains what it’s about to do, what version is about to be installed, where the folder it’s going to be installed in, what files/folder is going to deleted/affected, etc. Do _not_ let the user click a button then the app just goes install anything without any confirmation and explanation. I’ve got it installed wrong a version that I didn’t want. Twice.

Thank you.

**Comment by LongDirtyAnimAlf** [comment]
Implemented.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2g
