### ISSUE TITLE
Failed to build Lazarus fixes using FPC fixes.

### ISSUE THREAD

**Issue by pakLebah** [LongDirtyAnimAlf/fpcupdeluxe#176]
I’m trying to build latest Lazarus fixes (not trunk) using latest FPC fixes (not trunk) or Lazarus 2.0 fixes using FPC 3.2 fixes on Mac Mojave. But it failed while it should not.

Here’s some error messages from fpcUpDeluxe before it failed:

> fpcupdeluxe: info: FPC native builder: Detected source version FPC: 3.2.0
> fpcupdeluxe: info: FPC native builder: Using FPC bootstrap compiler with version: 3.0.4
> fpcupdeluxe: info: Lazarus: WARNING: found modified files.
> fpcupdeluxe: info: LazarusNativeInstaller (GetModule: Lazarus): Lazarus is at revision: 62558
> fpcupdeluxe: WARNING: LazarusNativeInstaller (GetModule: Lazarus): Going to patch Lazarus sources !!
> fpcupdeluxe: info: Lazarus native builder: Detected source version Lazarus: 2.0.7
> fpcupdeluxe: info: Lazarus native builder: Using FPC compiler with version: 3.2.0
> fpcupdeluxe: Start of compile error summary.
> &lt;home&gt;freepascal/lazarus/components/lazutils/dynhasharray.pp(173,5) Error: (4032) Can't assign values to const variable
> fpcupdeluxe: Start of compile error summary.
> &lt;home&gt;/freepascal/lazarus/components/lazutils/dynhasharray.pp(945,28) Error: (4032) Can't assign values to const variable
> fpcupdeluxe: Start of compile error summary.
> dynhasharray.pp(948) Fatal: (10026) There were 2 errors compiling module, stopping
> &lt;home&gt;/freepascal/lazarus/components/lazutils/dynhasharray.pp(945,28) Error: (4032) Can't assign values to const variable
> fpcupdeluxe: Start of compile error summary.
> Fatal: (1018) Compilation aborted
> dynhasharray.pp(948) Fatal: (10026) There were 2 errors compiling module, stopping
> fpcupdeluxe: Start of compile error summary.
> Error: &lt;home&gt;/freepascal/fpc/bin/x86_64-darwin/ppcx64 returned an error exitcode
> fpcupdeluxe: Start of compile error summary.
> fpcupdeluxe: ERROR: LazarusNativeInstaller (BuildModuleCustom: Lazbuild): make returned error code #512
> fpcupdeluxe: Done !!

**Note**: “&lt;home&gt;” is the folder of installation.

What’s wrong? Is there any way to achieve what I want using fpcupdeluxe?

Thank you.

**Comment by LongDirtyAnimAlf** [comment]
I guess this is solved by upstream (FPC and LAzarus).
