### ISSUE TITLE
Failed to install lazarus on windows x64

### ISSUE THREAD

**Issue by Makhaon** [LongDirtyAnimAlf/fpcupdeluxe#177]
I try to install trunk and stable lazarus version but without success. This is log:

fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): Start checkout/update of FPC sources.
Executing: C:\Program Files (x86)\CollabNet\svn.exe info D:\fpcupdeluxe_4\fpcsrc (working dir: )
svn: E155007: 'D:\fpcupdeluxe_4\fpcsrc' is not a working copy
Executing: C:\Program Files (x86)\CollabNet\svn.exe info D:\fpcupdeluxe_4\fpcsrc (working dir: )
svn: E155007: 'D:\fpcupdeluxe_4\fpcsrc' is not a working copy
fpcupdeluxe: info: Directory D:\fpcupdeluxe_4\fpcsrc is not an SVN repository (or a repository with the wrong remote URL).
fpcupdeluxe: info: FPCNativeInstaller (DownloadFromSVN: FPC): Creating directory D:\fpcupdeluxe_4\fpcsrc for SVN checkout.
Executing: C:\Program Files (x86)\CollabNet\svn.exe info D:\fpcupdeluxe_4\fpcsrc (working dir: )
svn: E155007: 'D:\fpcupdeluxe_4\fpcsrc' is not a working copy
fpcupdeluxe: info: FPCNativeInstaller (DownloadFromSVN: FPC): Running SVN checkout or update.
Executing: C:\Program Files (x86)\CollabNet\svn.exe info D:\fpcupdeluxe_4\fpcsrc (working dir: )
svn: E155007: 'D:\fpcupdeluxe_4\fpcsrc' is not a working copy
Executing: C:\Program Files (x86)\CollabNet\svn.exe info D:\fpcupdeluxe_4\fpcsrc (working dir: )
svn: E155007: 'D:\fpcupdeluxe_4\fpcsrc' is not a working copy
Executing: C:\Program Files (x86)\CollabNet\svn.exe checkout --quiet --non-interactive --trust-server-cert -r HEAD https://svn.freepascal.org/svn/fpc/tags/release_3_0_4/ D:\fpcupdeluxe_4\fpcsrc (working dir: )
svn: E175002: REPORT of '/svn/fpc/!svn/me': Could not read response body: Secure connection truncated (https://svn.freepascal.org)
fpcupdeluxe: WARNING: SVN client error return code: 1
Executing: C:\Program Files (x86)\CollabNet\svn.exe cleanup --non-interactive D:\fpcupdeluxe_4\fpcsrc (working dir: )
Executing: C:\Program Files (x86)\CollabNet\svn.exe checkout --quiet --non-interactive --trust-server-cert -r HEAD https://svn.freepascal.org/svn/fpc/tags/release_3_0_4/ D:\fpcupdeluxe_4\fpcsrc (working dir: )
svn: E175002: REPORT of '/svn/fpc/!svn/me': Could not read response body: Secure connection truncated (https://svn.freepascal.org)
fpcupdeluxe: WARNING: SVN client error return code: 1
Executing: C:\Program Files (x86)\CollabNet\svn.exe cleanup --non-interactive D:\fpcupdeluxe_4\fpcsrc (working dir: )
Executing: C:\Program Files (x86)\CollabNet\svn.exe checkout --quiet --non-interactive --trust-server-cert -r HEAD https://svn.freepascal.org/svn/fpc/tags/release_3_0_4/ D:\fpcupdeluxe_4\fpcsrc (working dir: )
svn: E175002: REPORT of '/svn/fpc/!svn/me': Could not read response body: Secure connection truncated (https://svn.freepascal.org)
fpcupdeluxe: WARNING: SVN client error return code: 1
Executing: C:\Program Files (x86)\CollabNet\svn.exe cleanup --non-interactive D:\fpcupdeluxe_4\fpcsrc (working dir: )
Executing: C:\Program Files (x86)\CollabNet\svn.exe checkout --quiet --non-interactive --trust-server-cert -r HEAD https://svn.freepascal.org/svn/fpc/tags/release_3_0_4/ D:\fpcupdeluxe_4\fpcsrc (working dir: )
svn: E175002: REPORT of '/svn/fpc/!svn/me': Could not read response body: Secure connection truncated (https://svn.freepascal.org)
fpcupdeluxe: WARNING: SVN client error return code: 1
Executing: C:\Program Files (x86)\CollabNet\svn.exe cleanup --non-interactive D:\fpcupdeluxe_4\fpcsrc (working dir: )
Executing: C:\Program Files (x86)\CollabNet\svn.exe checkout --quiet --non-interactive --trust-server-cert -r HEAD https://svn.freepascal.org/svn/fpc/tags/release_3_0_4/ D:\fpcupdeluxe_4\fpcsrc (working dir: )
svn: E175002: REPORT of '/svn/fpc/!svn/me': Could not read response body: Secure connection truncated (https://svn.freepascal.org)
fpcupdeluxe: WARNING: SVN client error return code: 1
Executing: C:\Program Files (x86)\CollabNet\svn.exe cleanup --non-interactive D:\fpcupdeluxe_4\fpcsrc (working dir: )
Executing: C:\Program Files (x86)\CollabNet\svn.exe checkout --quiet --non-interactive --trust-server-cert -r HEAD https://svn.freepascal.org/svn/fpc/tags/release_3_0_4/ D:\fpcupdeluxe_4\fpcsrc (working dir: )
svn: E175002: REPORT of '/svn/fpc/!svn/me': Could not read response body: Secure connection truncated (https://svn.freepascal.org)
fpcupdeluxe: WARNING: SVN client error return code: 1
Executing: C:\Program Files (x86)\CollabNet\svn.exe cleanup --non-interactive D:\fpcupdeluxe_4\fpcsrc (working dir: )
Executing: C:\Program Files (x86)\CollabNet\svn.exe checkout --quiet --non-interactive --trust-server-cert -r HEAD https://svn.freepascal.org/svn/fpc/tags/release_3_0_4/ D:\fpcupdeluxe_4\fpcsrc (working dir: )
svn: E175002: REPORT of '/svn/fpc/!svn/me': Could not read response body: Secure connection truncated (https://svn.freepascal.org)
fpcupdeluxe: WARNING: SVN client error return code: 1
Executing: C:\Program Files (x86)\CollabNet\svn.exe cleanup --non-interactive D:\fpcupdeluxe_4\fpcsrc (working dir: )
Executing: C:\Program Files (x86)\CollabNet\svn.exe checkout --quiet --non-interactive --trust-server-cert -r HEAD https://svn.freepascal.org/svn/fpc/tags/release_3_0_4/ D:\fpcupdeluxe_4\fpcsrc (working dir: )
svn: E175002: REPORT of '/svn/fpc/!svn/me': Could not read response body: Secure connection truncated (https://svn.freepascal.org)
fpcupdeluxe: WARNING: SVN client error return code: 1
Executing: C:\Program Files (x86)\CollabNet\svn.exe cleanup --non-interactive D:\fpcupdeluxe_4\fpcsrc (working dir: )
Executing: C:\Program Files (x86)\CollabNet\svn.exe checkout --quiet --non-interactive --trust-server-cert -r HEAD https://svn.freepascal.org/svn/fpc/tags/release_3_0_4/ D:\fpcupdeluxe_4\fpcsrc (working dir: )
svn: E175002: REPORT of '/svn/fpc/!svn/me': Could not read response body: Secure connection truncated (https://svn.freepascal.org)
fpcupdeluxe: WARNING: SVN client error return code: 1
Executing: C:\Program Files (x86)\CollabNet\svn.exe cleanup --non-interactive D:\fpcupdeluxe_4\fpcsrc (working dir: )
Executing: C:\Program Files (x86)\CollabNet\svn.exe checkout --quiet --non-interactive --trust-server-cert -r HEAD https://svn.freepascal.org/svn/fpc/tags/release_3_0_4/ D:\fpcupdeluxe_4\fpcsrc (working dir: )
svn: E175002: Unable to connect to a repository at URL 'https://svn.freepascal.org/svn/fpc/tags/release_3_0_4'
svn: E175002: OPTIONS of 'https://svn.freepascal.org/svn/fpc/tags/release_3_0_4': could not connect to server (https://svn.freepascal.org)
fpcupdeluxe: WARNING: SVN client error return code: 1
Executing: C:\Program Files (x86)\CollabNet\svn.exe cleanup --non-interactive D:\fpcupdeluxe_4\fpcsrc (working dir: )
Executing: C:\Program Files (x86)\CollabNet\svn.exe checkout --quiet --non-interactive --trust-server-cert -r HEAD https://svn.freepascal.org/svn/fpc/tags/release_3_0_4/ D:\fpcupdeluxe_4\fpcsrc (working dir: )
svn: E175002: REPORT of '/svn/fpc/!svn/me': Could not read response body: Secure connection truncated (https://svn.freepascal.org)
fpcupdeluxe: WARNING: SVN client error return code: 1
Executing: C:\Program Files (x86)\CollabNet\svn.exe cleanup --non-interactive D:\fpcupdeluxe_4\fpcsrc (working dir: )
Executing: C:\Program Files (x86)\CollabNet\svn.exe update --quiet --non-interactive --trust-server-cert -r HEAD D:\fpcupdeluxe_4\fpcsrc (working dir: )
svn: E175002: REPORT of '/svn/fpc/!svn/me': Could not read response body: Secure connection truncated (https://svn.freepascal.org)
fpcupdeluxe: ERROR: SVN client error return code: 1
Executing: C:\Program Files (x86)\CollabNet\svn.exe info D:\fpcupdeluxe_4\fpcsrc (working dir: )
Path: D:\fpcupdeluxe_4\fpcsrc
Working Copy Root Path: D:\fpcupdeluxe_4\fpcsrc
URL: https://svn.freepascal.org/svn/fpc/tags/release_3_0_4
Repository Root: https://svn.freepascal.org/svn/fpc
Repository UUID: 3ad0048d-3df7-0310-abae-a5850022a9f2
Revision: 44143
Node Kind: directory
Schedule: normal

fpcupdeluxe: info: FPCNativeInstaller (DownloadFromSVN: FPC): SVN gave error code: 1

fpcupdeluxe: info: FPCNativeInstaller (DownloadFromSVN: FPC): SVN gave error message: Path: D:\fpcupdeluxe_4\fpcsrc
Working Copy Root Path: D:\fpcupdeluxe_4\fpcsrc
URL: https://svn.freepascal.org/svn/fpc/tags/release_3_0_4
Repository Root: https://svn.freepascal.org/svn/fpc
Repository UUID: 3ad0048d-3df7-0310-abae-a5850022a9f2
Revision: 44143
Node Kind: directory
Schedule: normal

fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC was at revision: failure
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC is now at revision: luxe_4
fpcupdeluxe: ERROR: FPCNativeInstaller (GetModule: FPC): Checkout/update of FPC sources failure.

ERROR: Fpcupdeluxe fatal error !

**Comment by LongDirtyAnimAlf** [comment]
This is a SVN error. That happens when svn is not working 100%.
There were some problems at the time your reported this issue.
Please try again !

**Comment by LongDirtyAnimAlf** [comment]
Closing due to no feedback.
Please re-open when needed.

**Comment by Makhaon** [comment]
This advice helped fix the issue:
https://stackoverflow.com/questions/21086006/svn-e175002-report-of-xxxx-demo-svn-vcc-default-could-not-read-response-b
"svn cleanup" and after "svn update" in the fpcsrc folder helped me.
