### ISSUE TITLE
Compiler for Win32 installed, but does not work

### ISSUE THREAD

**Issue by gorn** [LongDirtyAnimAlf/fpcupdeluxe#178]
On Linux (Mint) I have tried to install Crosso compiler for CPU=i386 OS=windows. When I go to "Cross" tab, select these options and "Install Compiler" everything seems OK (That went well !!!).

**However** when I try to compile for in Lazarus IDE it **fails with**
```
Erro: Illegal parameter -Twin32
```
When I go to Options > Compiler Options and press Show Options I receive **more descriptive error**

```
Compiler "/home/gorn/lazarus/fpcupdeluxe/fpc/bin/x86_64-linux/fpc.sh" does not support target x86_64-win32
```

Details:

- Trying to compile in lazarus by setting Target OS in Options > Compiler Options > Config and Target to Win32 plus Compiler Options > Additions and Overrides > Set "LCLWidgetType" to Value "win32"
- It seems to me that it generates all the intermediate thing correclty (for example lots of data into `/fpcupdeluxe/fpc/lib/fpc/3.0.4/units/i386-win32` directory and `ppcross386` binary in  into `/fpcupdeluxe/fpc/bin/x86_64-linux` directory.
- Command line parameters are `'/home/gorn/lazarus/fpcupdeluxe/fpc/bin/x86_64-linux/fpc.sh'  -Twin32 -MObjFPC -Scghi -CX -O1 -XX -l -vewnhibq -Filib/x86_64-win32 -Fu../lazarus/fpcupdeluxe/lazarus/components/turbopower_ipro/units/x86_64-win32/win32 -Fu../lazarus/fpcupdeluxe/lazarus/components/rtticontrols/lib/x86_64-win32/win32 -Fu../lazarus/fpcupdeluxe/lazarus/components/printers/lib/x86_64-win32/win32 -Fu../lazarus/fpcupdeluxe/lazarus/components/ideintf/units/x86_64-win32/win32 -Fu../lazarus/fpcupdeluxe/lazarus/components/sdf/lib/x86_64-win32/win32 -Fu../lazarus/fpcupdeluxe/lazarus/components/lazcontrols/lib/x86_64-win32/win32 -Fu../lazarus/fpcupdeluxe/lazarus/components/cairocanvas/lib/x86_64-win32/win32 -Fu../lazarus/fpcupdeluxe/lazarus/lcl/units/x86_64-win32/win32 -Fu../lazarus/fpcupdeluxe/lazarus/lcl/units/x86_64-win32 -Fu../lazarus/fpcupdeluxe/lazarus/components/lazutils/lib/x86_64-win32 -Fu../lazarus/fpcupdeluxe/lazarus/packager/units/x86_64-win32 -Fu. -FUlib/x86_64-win32 -FE. "-oMatchMatcher-x86_64-win32-Release Windows.exe" -dLCL -dLCLwin32 -dNODEBUG`

**Comment by LongDirtyAnimAlf** [comment]
Try this: CPU=x86_64 OS=windows.
It seems to me that you are in need of the 64 bit compiler for Windows !

**Comment by LongDirtyAnimAlf** [comment]
Closing due to no feedback.
Please re-open when needed.
