### ISSUE TITLE
Cannot handle none cross'es

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#179]
just installed fpc 3.2fixes from scratch.
cross dir is empty.
Deluxe 1.6.8b Linux x64 gtk2.

on "cross" tab I press [Auto update compilers] and app shows empty log
![Screenshot from 2020-02-18 20-25-49](https://user-images.githubusercontent.com/4154978/74761536-42096600-528d-11ea-95a9-e0b62ca782aa.png)

and it unchecks all radiobuttons!
wish: disable this button if no crosses.

**Comment by LongDirtyAnimAlf** [comment]
A bit implemented ... ;-) .
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.8c
