### ISSUE TITLE
Form "InfoForm"

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#180]
from Options dialog of deluxe, click List button near CPU and OS dropdowns. this form is shown.

- make verbose title in it
- make its memo/listbox BorderSpacing.Around=6
- add ButtonPanel with OK/Cancel buttons

**Comment by LongDirtyAnimAlf** [comment]
Implemented. Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.8c

**Comment by LongDirtyAnimAlf** [comment]
Closed due to no feedback. Please re-open if needed.
