### ISSUE TITLE
Options dialog - fields OS/CPU are editable

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#182]
and also i can enter there any nonsence.

**Comment by LongDirtyAnimAlf** [comment]
Implemented. Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.8c

**Comment by LongDirtyAnimAlf** [comment]
Closed due to no feedback. Please re-open if needed.
