### ISSUE TITLE
Need the option to use macOS system FPC 3.0.4 as bootstrap compiler for FPC trunk

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#184]
Otherwise i cannot install fpc trunk, wrong 3.0.0 bootstrap is used.

**Comment by LongDirtyAnimAlf** [comment]
Please try:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/1.6.8c/fpcupdeluxe-x86_64-darwin-cocoa.zip

**Comment by LongDirtyAnimAlf** [comment]
Closed due to no feedback. Please re-open id needed.
