### ISSUE TITLE
Issue while try to compile arm embedded on win7 

### ISSUE THREAD

**Issue by Blowcake** [LongDirtyAnimAlf/fpcupdeluxe#187]
While i succeeded in compile arm / linux , i tried afterwards arm embedded..

fpcupdeluxe stalls at this stage: (gui do not respond anymore, greyed out when selected)

Last lines from output:
Fpcupdeluxe failed due to missing cross binary tools.
Looking for fpcupdeluxe cross-tools on GitHub (if any).
Going to look for the right cross-bins. Can (will) take some time !
Looking for: WinCrossBinsEmbeddedARM

At this point.. nothing happens, it hangs.

If i can help to test fixes, i will do my best .o)

**Comment by LongDirtyAnimAlf** [comment]
I guess its a problem with GitHub.
GitHub uses throttling to prevent to many API requests.
Behind the screen, fpcupdeluxe tries to use as many download methods as possible.
The failure of these methods could cause GitHub to throttle the requests.

I will look into it somewhat more.

In the meantime, the libs and bins can be found here:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/wincrossbins_v1.0/WinCrossBinsEmbeddedARM.zip
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/crosslibs_v1.1/CrossLibsEmbeddedARM.zip

But them in arm-embedded and off you go !!

**Comment by LongDirtyAnimAlf** [comment]
Closing due to no feedback. Re-open if needed.
