### ISSUE TITLE
App runs "svn info" 5 times

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#190]
OpenBSD 6.6 x64, i see 5 calls of "svn info", why not one?
![opp](https://user-images.githubusercontent.com/4154978/77247945-d8db9080-6c46-11ea-90e5-762aedf404bd.png)

**Comment by LongDirtyAnimAlf** [comment]
This is to handle all kinds or svn quirks and errors.
It will remain this way.
