### ISSUE TITLE
Make .log file

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#192]
App don't write log file, it only writes SMALL portion of log when it fails (like I shown in OpenBSD issue).
Pls create .log file.
Pls create it in the app folder, near the binary, better than in /tmp.
Pls write captions to log on each start like `--------- Start: yyyy.mm.dd hh:mm:ss ---------`
Log is needed when any FPC/Laz/Cross installation is started.

**Comment by LongDirtyAnimAlf** [comment]
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.8e

**Comment by Alexey-T** [comment]
Solved
