### ISSUE TITLE
Build errors on x86_64-darwin-cocoa

### ISSUE THREAD

**Issue by HermanSchoenfeld** [LongDirtyAnimAlf/fpcupdeluxe#193]
FPCUPdeluxe V1.6.8e for x86_64-darwin-cocoa

Going to install/update FPC and Lazarus with given options.
FPCUP(deluxe) is starting up.

Bootstrap dir:         /Users/Developer/fpcupdeluxe/fpcbootstrap
FPCupdeluxe basedir:   /Users/Developer/fpcupdeluxe
FPC URL:               https://svn.freepascal.org/svn/fpc/tags/release_3_0_4
FPC options:           
FPC source directory:  /Users/Developer/fpcupdeluxe/fpcsrc
FPC install directory: /Users/Developer/fpcupdeluxe/fpc
Lazarus URL:           https://svn.freepascal.org/svn/lazarus/trunk
Lazarus options:       
Lazarus directory:     /Users/Developer/fpcupdeluxe/lazarus

Please stand back and enjoy !

fpcupdeluxe: info: 23-3-20 12:02:11: fpcupdeluxe: V204 (20200321) started.
fpcupdeluxe: info: FPCNativeInstaller (CleanModule: FPC): Running  distclean failed: could not find cleanup compiler. Will try again later
fpcupdeluxe: info: FPCNativeInstaller (CleanModule: FPC): Deleting some FPC package config files.
fpcupdeluxe: info: FPCNativeInstaller (CheckModule: FPC): checking FPC sources with TSVNClient
Executing: /usr/bin/svn info /Users/Developer/fpcupdeluxe/fpcsrc (working dir: )
Path: /Users/Developer/fpcupdeluxe/fpcsrc
Working Copy Root Path: /Users/Developer/fpcupdeluxe/fpcsrc
URL: https://svn.freepascal.org/svn/fpc/tags/release_3_0_4
Relative URL: ^/tags/release_3_0_4
Repository Root: https://svn.freepascal.org/svn/fpc
Repository UUID: 3ad0048d-3df7-0310-abae-a5850022a9f2
Revision: 44345
Node Kind: directory
Schedule: normal
Last Changed Author: marco
Last Changed Rev: 37149
Last Changed Date: 2017-09-06 03:14:06 +1000 (Wed, 06 Sep 2017)

fpcupdeluxe: info: FPCNativeInstaller (CheckModule: FPC): sources ok.
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): Start checkout/update of FPC sources.
Executing: /usr/bin/svn info /Users/Developer/fpcupdeluxe/fpcsrc (working dir: )
Path: /Users/Developer/fpcupdeluxe/fpcsrc
Working Copy Root Path: /Users/Developer/fpcupdeluxe/fpcsrc
URL: https://svn.freepascal.org/svn/fpc/tags/release_3_0_4
Relative URL: ^/tags/release_3_0_4
Repository Root: https://svn.freepascal.org/svn/fpc
Repository UUID: 3ad0048d-3df7-0310-abae-a5850022a9f2
Revision: 44345
Node Kind: directory
Schedule: normal
Last Changed Author: marco
Last Changed Rev: 37149
Last Changed Date: 2017-09-06 03:14:06 +1000 (Wed, 06 Sep 2017)

Executing: /usr/bin/svn info /Users/Developer/fpcupdeluxe/fpcsrc (working dir: )
Path: /Users/Developer/fpcupdeluxe/fpcsrc
Working Copy Root Path: /Users/Developer/fpcupdeluxe/fpcsrc
URL: https://svn.freepascal.org/svn/fpc/tags/release_3_0_4
Relative URL: ^/tags/release_3_0_4
Repository Root: https://svn.freepascal.org/svn/fpc
Repository UUID: 3ad0048d-3df7-0310-abae-a5850022a9f2
Revision: 44345
Node Kind: directory
Schedule: normal
Last Changed Author: marco
Last Changed Rev: 37149
Last Changed Date: 2017-09-06 03:14:06 +1000 (Wed, 06 Sep 2017)

Executing: /usr/bin/svn status --depth infinity /Users/Developer/fpcupdeluxe/fpcsrc (working dir: )
?       /Users/Developer/fpcupdeluxe/fpcsrc/compiler/revision.inc
fpcupdeluxe: info: FPCNativeInstaller (DownloadFromSVN: FPC): Running SVN checkout or update.
Executing: /usr/bin/svn info /Users/Developer/fpcupdeluxe/fpcsrc (working dir: )
Path: /Users/Developer/fpcupdeluxe/fpcsrc
Working Copy Root Path: /Users/Developer/fpcupdeluxe/fpcsrc
URL: https://svn.freepascal.org/svn/fpc/tags/release_3_0_4
Relative URL: ^/tags/release_3_0_4
Repository Root: https://svn.freepascal.org/svn/fpc
Repository UUID: 3ad0048d-3df7-0310-abae-a5850022a9f2
Revision: 44345
Node Kind: directory
Schedule: normal
Last Changed Author: marco
Last Changed Rev: 37149
Last Changed Date: 2017-09-06 03:14:06 +1000 (Wed, 06 Sep 2017)

Executing: /usr/bin/svn cleanup --non-interactive /Users/Developer/fpcupdeluxe/fpcsrc (working dir: )
Executing: /usr/bin/svn update --quiet --non-interactive --trust-server-cert -r HEAD /Users/Developer/fpcupdeluxe/fpcsrc (working dir: )
Executing: /usr/bin/svn info /Users/Developer/fpcupdeluxe/fpcsrc (working dir: )
Path: /Users/Developer/fpcupdeluxe/fpcsrc
Working Copy Root Path: /Users/Developer/fpcupdeluxe/fpcsrc
URL: https://svn.freepascal.org/svn/fpc/tags/release_3_0_4
Relative URL: ^/tags/release_3_0_4
Repository Root: https://svn.freepascal.org/svn/fpc
Repository UUID: 3ad0048d-3df7-0310-abae-a5850022a9f2
Revision: 44345
Node Kind: directory
Schedule: normal
Last Changed Author: marco
Last Changed Rev: 37149
Last Changed Date: 2017-09-06 03:14:06 +1000 (Wed, 06 Sep 2017)

fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC is at revision: 37149
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): No updates for FPC found.
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): Online fpcpatch_linux_linker_stable_3_0_4.patch for FPC wil be applied !
fpcupdeluxe: info: FPCNativeInstaller (GetFile): Downloading https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/patches_v1.0/fpcpatch_linux_linker_stable_3_0_4.patch
fpcupdeluxe: info: FPCNativeInstaller (GetFile): Could not download file with URL https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/patches_v1.0/fpcpatch_linux_linker_stable_3_0_4.patch into /Users/Developer/fpcupdeluxe/patchfpc (filename: fpcpatch_linux_linker_stable_3_0_4.patch)
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): Online fpcpatch_darwin_makepackages_stable_3_0_4.patch for FPC wil be applied !
fpcupdeluxe: info: FPCNativeInstaller (GetFile): Downloading https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/patches_v1.0/fpcpatch_darwin_makepackages_stable_3_0_4.patch
fpcupdeluxe: info: FPCNativeInstaller (GetFile): Could not download file with URL https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/patches_v1.0/fpcpatch_darwin_makepackages_stable_3_0_4.patch into /Users/Developer/fpcupdeluxe/patchfpc (filename: fpcpatch_darwin_makepackages_stable_3_0_4.patch)
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): Online fpcpatch_all_makesearchpath_stable_3_0_4.patch for FPC wil be applied !
fpcupdeluxe: info: FPCNativeInstaller (GetFile): Downloading https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/patches_v1.0/fpcpatch_all_makesearchpath_stable_3_0_4.patch
fpcupdeluxe: info: FPCNativeInstaller (GetFile): Could not download file with URL https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/patches_v1.0/fpcpatch_all_makesearchpath_stable_3_0_4.patch into /Users/Developer/fpcupdeluxe/patchfpc (filename: fpcpatch_all_makesearchpath_stable_3_0_4.patch)
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): No FPC patches defined.
fpcupdeluxe: info: FPCNativeInstaller (BuildModule: FPC): Building module FPC...
fpcupdeluxe: info: FPC native builder: Detected source version FPC: 3.0.4
fpcupdeluxe: info: FPCNativeInstaller (BuildModule: FPC): To compile this FPC, we need (required) a compiler with version 3.0.0 or 3.0.2
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Looking for a bootstrap compiler from official FPC bootstrap binaries.
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Looking for official FPC bootstrapper with version 3.0.2
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Looking for official FPC bootstrapper with version 3.0.0
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Got a V3.0.0 bootstrap compiler from official FPC bootstrap sources.
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Now looking for a better [version] bootstrap compiler from Github FPCUP(deluxe) releases.
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Looking online for a FPCUP(deluxe) bootstrapper with version 3.0.2
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Success: found a FPCUP(deluxe) bootstrapper with version 3.0.2
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Got a better [version] bootstrap compiler from FPCUP(deluxe) bootstrap binaries.
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): This is important for OSX Cataline, that dislikes FPC multi-arch binaries.
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Check if we already have a bootstrap compiler with version 3.0.2
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): No correct bootstrapper. Going to download bootstrapper from https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/bootstrappers_v1.0/fpcup-3_0_2-x86_64-darwin-ppcx64
fpcupdeluxe: info: FPCNativeInstaller (GetFile): Downloading https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/bootstrappers_v1.0/fpcup-3_0_2-x86_64-darwin-ppcx64
fpcupdeluxe: info: FPCNativeInstaller (GetFile): Could not download file with URL https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/bootstrappers_v1.0/fpcup-3_0_2-x86_64-darwin-ppcx64 into /var/folders/dw/3jf0d1t15dz1n68qd_lbyjr80000gn/T (filename: FPCUPTMP00000.zip)
fpcupdeluxe: ERROR: FPCNativeInstaller (GetFile): Getting/extracting bootstrap compiler failed. Archive: /var/folders/dw/3jf0d1t15dz1n68qd_lbyjr80000gn/T/FPCUPTMP00000.zip
fpcupdeluxe: info: FPCNativeInstaller (DownloadBinUtils): Found GNU make binary here: make.
fpcupdeluxe: ERROR: FPCNativeInstaller (BuildModuleCustom: FPC): FPC bootstrap version error: 0.0.0 ! Should never happen: expect many errors !!
fpcupdeluxe: info: FPCNativeInstaller (BuildModuleCustom: FPC): Running CleanModule once more before building FPC from sources, due to previous CleanModule failure.
fpcupdeluxe: info: FPCNativeInstaller (CleanModule: FPC): Running  distclean failed: could not find cleanup compiler. Will try again later
fpcupdeluxe: info: FPCNativeInstaller (CleanModule: FPC): Deleting some FPC package config files.
fpcupdeluxe: info: FPCNativeInstaller (CleanModule: FPC): Now building FPC revision 37149
fpcupdeluxe: info: FPCNativeInstaller (CleanModule: FPC): Running make all install for FPC
Executing: make --jobs=8 PP=/Users/Developer/fpcupdeluxe/fpcbootstrap/ppcx64 FPCMAKE=/Users/Developer/fpcupdeluxe/fpc/bin/x86_64-darwin/fpcmake PPUMOVE=/Users/Developer/fpcupdeluxe/fpc/bin/x86_64-darwin/ppumove FPCDIR=/Users/Developer/fpcupdeluxe/fpcsrc PREFIX=/Users/Developer/fpcupdeluxe/fpc INSTALL_PREFIX=/Users/Developer/fpcupdeluxe/fpc INSTALL_BINDIR=/Users/Developer/fpcupdeluxe/fpc/bin/x86_64-darwin OS_SOURCE=darwin CPU_SOURCE=x86_64 OS_TARGET=darwin CPU_TARGET=x86_64 OVERRIDEVERSIONCHECK=1 REVSTR=37149 'OPT=-WM10.8 -Sg -vw-n-h-l-d-u-t-p-c- -dREVINC' --directory=/Users/Developer/fpcupdeluxe/fpcsrc all install (working dir: /Users/Developer/fpcupdeluxe/fpcsrc)
Makefile:135: *** Compiler /Users/Developer/fpcupdeluxe/fpcbootstrap/ppcx64 not found.  Stop.

fpcupdeluxe: ERROR: FPCNativeInstaller (CleanModule: FPC): Error running make for FPC failed with exit code 512
. Details:

ERROR: Fpcupdeluxe fatal error !

**Comment by LongDirtyAnimAlf** [comment]
The log is clear. Bootstrapper was found. But no permission to store it into the temporary directory.
Will make the necessary changes. Stay tuned.

**Comment by LongDirtyAnimAlf** [comment]
Would you mind trying the latest release ?

https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.8e

**Comment by HermanSchoenfeld** [comment]
Fixed.

**Comment by LongDirtyAnimAlf** [comment]
Thanks for the feedback.
