### ISSUE TITLE
Logfile name on OpenBSD is 'fpcuprevisions.log' while on Linux it's different

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#196]

**Comment by LongDirtyAnimAlf** [comment]
I have enabled cross-compiling towards OpenBSD.
Would you mind testing.

https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/latest

This could/should be the best release everof fpcupdeluxe, if all works as expected.
Thanks.

**Comment by Alexey-T** [comment]
Very interesting, will test!

**Comment by Alexey-T** [comment]
Cross works... good. I made Cudatext for openbsd now. Tkx! (But still cannot install FPC...)

**Comment by LongDirtyAnimAlf** [comment]
Seems solved.
