### ISSUE TITLE
Wrong 'ld' found on OpenBSD

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#198]
```
fpcupdeluxe: WARNING: FPCNativeInstaller (DownloadBinUtils): Found ld binary here: /usr/bin/ld. But it is not GNU ld. Expect errors
fpcupdeluxe: WARNING: FPCNativeInstaller (DownloadBinUtils): Found GNU ld.bfd binary here: /usr/bin/ld.bfd. Could be used through symlinking.
```

Can you help here? ld is from OS, so what to do with this?

**Comment by LongDirtyAnimAlf** [comment]
Its a warning.
FPC needs ld from GNU binutils on most systems.
OpenBSD has ld from llvm. That might or might not work.
Normally, ld.bfd is a GNU ld.
If you look at the FPC sources; t_bsd.pas :

var
  LdProgram: string='ld';
begin
  if target_info.system in (systems_openbsd+[system_x86_64_dragonfly]) then
    LdProgram:='ld.bfd';
  LibrarySuffix:=' ';

So, it should use ld.bfd from GNU. Its just a warning to show this to the user.

**Comment by Alexey-T** [comment]
Solved, tkx
