### ISSUE TITLE
ppc386.exe not found, error

### ISSUE THREAD

**Issue by sstvmaster** [LongDirtyAnimAlf/fpcupdeluxe#199]
Hi,

this error appears when i try to install fixes/fixes.

OS: Win10 Pro x64
fpcupdeluxe: 1.6.8g win32

`fpcupdeluxe: info: FPCNativeInstaller (SimpleExportFromSVN: DownloadBinUtils): Downloading: strip.exe into C:\lazarus_fixes\fpcbootstrap success.
fpcupdeluxe: info: FPCNativeInstaller (DownloadBinUtils): Found GNU make binary here: C:\lazarus_fixes\fpcbootstrap\make.exe.
fpcupdeluxe: ERROR: FPCNativeInstaller (BuildModuleCustom: FPC): FPC bootstrap version error: 0.0.0 ! Should never happen: expect many errors !!
fpcupdeluxe: info: FPCNativeInstaller (BuildModuleCustom: FPC): Running CleanModule once more before building FPC from sources, due to previous CleanModule failure.
fpcupdeluxe: info: FPCNativeInstaller (CleanModule: FPC): Running  distclean failed: could not find cleanup compiler. Will try again later
fpcupdeluxe: info: FPCNativeInstaller (CleanModule: FPC): Deleting some FPC package config files.
fpcupdeluxe: info: FPCNativeInstaller (CleanModule: FPC): Now building FPC revision 44327
fpcupdeluxe: info: FPCNativeInstaller (CleanModule: FPC): Running C:\lazarus_fixes\fpcbootstrap\make.exe all install for FPC
Executing: C:\lazarus_fixes\fpcbootstrap\make.exe --jobs=4 PP=C:\lazarus_fixes\fpcbootstrap\ppc386.exe FPCMAKE=C:\lazarus_fixes\fpc\bin\i386-win32\fpcmake.exe PPUMOVE=C:\lazarus_fixes\fpc\bin\i386-win32\ppumove.exe FPCDIR=C:\lazarus_fixes\fpcsrc PREFIX=C:\lazarus_fixes\fpc INSTALL_PREFIX=C:\lazarus_fixes\fpc UPXPROG=echo COPYTREE=echo OS_SOURCE=win32 CPU_SOURCE=i386 OS_TARGET=win32 CPU_TARGET=i386 REVSTR=44327 "OPT=-vw-n-h-l-d-u-t-p-c- -dREVINC" --directory=C:\lazarus_fixes\fpcsrc all install (working dir: C:\lazarus_fixes\fpcsrc)
Makefile:135: *** Compiler C:/lazarus_fixes/fpcbootstrap/ppc386.exe not found.  Stop.

fpcupdeluxe: ERROR: FPCNativeInstaller (CleanModule: FPC): Error running C:\lazarus_fixes\fpcbootstrap\make.exe for FPC failed with exit code 2
. Details:

ERROR: Fpcupdeluxe fatal error !`

**Comment by LongDirtyAnimAlf** [comment]
Confirmed.
For the time being, check, in Setup+, the box Üse only fpcupdeluxe bootstrappers".

**Comment by LongDirtyAnimAlf** [comment]
Would you mind trying the latest ?
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/latest

**Comment by sstvmaster** [comment]
1.6.8h -> SUCCESS: Fpcupdeluxe ended without errors.

Thank you !

**Comment by LongDirtyAnimAlf** [comment]
Thanks for testing. However, 1.6.8h still contained some small buggers.
I will release 1.6.8i today ... that should solve all (I hope).
