### ISSUE TITLE
Menu for "Uninstall cross compiler"

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#200]
I have cross "arm android".
To remove it, i much 1) check "android" 2) check "arm"

Will be better if I can click "Remove compiler" which shows listbox of all installed cross'es, to delete chosen item.

PS. Name button then "Remove..."

**Comment by LongDirtyAnimAlf** [comment]
If this is an easy option for me to implement, I will do so.
But now, I have to use my time again for my work.
So, will leave this open util a decision is made, or the feature is implemented.

**Comment by LongDirtyAnimAlf** [comment]
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/issues/207

Nice addition. But closing for the same reason.
