### ISSUE TITLE
Unable to install trunk or stable version following error appear 

### ISSUE THREAD

**Issue by fiazhnd** [LongDirtyAnimAlf/fpcupdeluxe#202]
Unable to install trunk or stable version following error appear 
fpcupdeluxe: Start of compile error summary.
fpcupdeluxe: ERROR: SVN client error return code: 1
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC is at revision: \fpcsr
fpcupdeluxe: Start of compile error summary.
fpcupdeluxe: ERROR: FPCNativeInstaller (GetModule: FPC): Checkout/update of FPC sources failure.
fpcupdeluxe: Done !!

**Comment by LongDirtyAnimAlf** [comment]
Please give more info about your system: OS, CPU, ...

Additional advice.
In Setup+ you can tell fpcupdeluxe to use local repo client (if you are on Windows).
That could help.

**Comment by fiazhnd** [comment]
Window 10 Pro 64bit
Processor Intel Core i3-3217U

**Comment by rufusroflpunch** [comment]
I get same error on OS X Catalina, x64.

**Comment by LongDirtyAnimAlf** [comment]
Closing this issue. Please re-open if relevant again.
