### ISSUE TITLE
Cross Compiling Linux 32 from x86_64 fails.

### ISSUE THREAD

**Issue by oliverhbailey** [LongDirtyAnimAlf/fpcupdeluxe#203]
There are issues with cross compiling on Debian 10 x86_64 to Linux 32. The paths for local fpcupdeluxe are not set for local installation folders. It appears some are local while others are in the /usr/lib folders. Building or installing a cross compiler seems to have no effect at all and the folder structure is neither clear or documented. Look at other open source compilers and the difference between install for all users and a local user. This documentation is sporadic, in many cases incomplete, and contradictory with nothing ever being updated fully.  Its sad that such a good compiler has such terrible support and testing. Cross compiling use to work, and now its terribly broken because there is no accurate or current documentation that explains anything fully. Using fpcupdeluxe, the trunk.zip for fpc and lazarus were properly installed and working. 64 bit projects compiled properly. Next, the cross installation of linux-i386 was installed. The cross compiler is there and the components seem to have all be compiled but linking fails. Since i386 was deprecated two years ago by the GNU foundation, technically the /usr/i686 is the current folder structure. i686 is still supported, i386 is not. When i386 was depricated, minimum support went from the i386 to the i486.
Some good documentation on folder structures would help the developer who supports this, fix it, and other developers know where to look when problems occur. I tried to paste the messages screen with the missing cario linker file for the i386, but it appears the i386 linker is looking in the x86_64 library folder. But even worse is the fact there is no complete documentation on the folder structure of lazarus or fpc, and fpcupdeluxe seems to have a different structure again. Once again, look at other development tools to see how to set this up properly at installation time. And tell us in the Wiki is we need to crreate a script file to set the paths or not. It is not clear if these have to be set or are set when fpcupdeluxe runs the first time and creates these items as compilers are added, updated, and removed. That type of information isn't optional, its required if you want this tool to be of any use.

**Comment by LongDirtyAnimAlf** [comment]
Please use the official install and available online info about FPC and Lazarus to accomplish what you want.

Fpcupdeluxe is a tool that can help you install FPC and Lazarus. There is no obligation to use it. It is not endorsed by FPC or Lazarus maintainers. You can ask questions about its use on the forum. Answers will be given by me and many other users.

**Comment by oliverhbailey** [comment]
I tried that approach first, and it doesn't work either. I'm using Debian
10. When Debian 10 was released, it uses the new multiarch system which
changed. Multiarch is fairly transparent now and the gcc and g++ compilers
for x86_64 simply need dpkg to add the i386 architecture, apt update, and
apt upgrade to add currently installed packages. You compile both with gcc
or g++ x86_64 and simply use -m32 to generate and link to 32 bit code.

So neither lazarus system works with debian 10. Gcc and g++ work correctly.
I'm an operating system architect and have been since the days of the CP/M.
I was an alpha tester of Turbo Pascal and Delphi 1.0 and wrote most the
first 50 device drivers for Windows NT. I've been involved with Linux
development for the past 20 years and work with Yocto, Buildroot, LFS, and
Linux kernels daily for many processor architectures.

I'm writing a new edition  of a book on cross-platform development from
2004 and going to replace the Delphi/Kylix chapter with Lazarus. But in the
past few days, too many problems have appeared in the component libraries,
convoluded documentation, and poor or inaccurate documentation.

I can't recommend a tool that configuration is not easy to understand for
experienced developers. And this tool lacks some essentials to a
successfully adopted tool. I went through the fourms snd many of these
issues have been around too many years. I noticed snother experienced
developer that comment about champion quality and big companies will adopt
the product. From a professional view two things have to occur to get
financial support of open source projects. The first is visible progress of
problem resolution. Some of the basic components are still not working and
should be. The second is ease of configuration and installation for all
users by root or administrators, and ease of installation and configuration
for the local user.

There is simply too much old documentation mixed with unfinished updates to
trust this tool with survive too much longer. I think the documentation
needs to be forked immediately and rapid progress to get the older class
libraries finished should be an immediate priority. Its also imperiative to
fix reported issues permanently the first time. This is not a matter of
lack of help, it priortizing the list to available help and experience
levels.

A great example is fpupdeluxe and fpc switcher. No where does it say these
are not lazarus supported projects. And that would be only a matter of have
a wiki page of 3rd party projects that are tested or supported by lazarus
of fpc.

I was more impressed with older verdions that could be easily configured to
cross compile by accurate wiki information. Now there are different
compiler versions for different platforms. Pick three of the most popular
that are easiest to port and maintain. Remove Darwin, Embedded. and Android
for now. Focus on maintaining Linux 32 bit, arm, aarch64, and Windows 32/64
as a start. And keep them up to date.

I can't honestly recommend this tool in its current state. What I can
recommend is gcc for cross-platform on Linux 64, 32, arm, aarch64, win32,
Win 64, netBSD, openBSD, and FreeBSD using eclipse. I can also recommend
.net on Windows, Linux, netBSD, openBSD, and FreeBSD using a couple of
techniques, editors, and debuggers. Those have remained stable, consistent,
and have maintained compatibility over the years.

This project is in despsrate need of leadership and organization if it is
going to survive the next two years.

I hope the developers wake up and smell the roses very soon

Regards,
Oliver H. Bailey

**Comment by LongDirtyAnimAlf** [comment]
Well, you are entitled to your opinion naturally. And I will not counter you in that.
But.
You might try to help me in improving fpcupdeluxe in becoming a tool that can be of help for you and (already) many others.
I am now using it to cross-compile all fpcupdeluxe binaries that are released, from a single Windows 10 machine. So, I am myself a happy user.

**Comment by oliverhbailey** [comment]
Don,
Interesting. I downloaded the source 2 days ago and did an initial build.
Using the downloaded fpcupdeluxe-linux-x86_64 version, I started with the
trunk.zip fpc and lazarus, they both seem to work well although there are
some issues with visual lazarus components that have turned up in the past
day. A couple of questions, are you the maintainer of the svn downloads,
and the git downloadable lazarus cross build installers? If so that may be
one way for my readers to get around the problems I am experiencing with
some of the cross building issues. I have a number of systems that I do
cross development on. How can I help?

Oliver

**Comment by LongDirtyAnimAlf** [comment]
Thanks for your help offer. Very welcome.
All stuff that is hosted here, is maintained by me.
Fpcupdeluxe builds cross-compilers on the fly, from sources. It uses binary utilities and libs that are also hosted here. You can find them as releases under special tags.
There are ready-made cross-compilers by FPC. You can find directions on how to get them and use them on the FPC website.
As stated before, fpcupeluxe should/could offer you all that is needed for successful cross-development. Improvements by userfeedback are needed to keep this tool current.

**Comment by oliverhbailey** [comment]
Hi Don,
I believe that I found the problem with Linux 32 it cross from Linux
x86_64. The following appears on the Free Pascal Wiki Cross Compiling page.

Change the fpc.cfg file with the following lines

#ifdef cpui386
-Fl/usr/lib/gcc/x86_64-linux-gnu/6/32#endif

to these lines:

#ifdef cpui386
-Fl/usr/lib/gcc/x86_64-linux-gnu/6/32
-Fl/usr/lib32#endif

Which fpc.cfg file would be changed, or is there a path inclusion in the
fpcupdeluxe_Lazarus initialization file that should be added?

Regards,

Oliver

**Comment by oliverhbailey** [comment]
I apologize. The error I'm getting is in the messages box below.

[image: image.png]

Thank you,
Oliver

**Comment by LongDirtyAnimAlf** [comment]
There is no message box image visible. Please try again.

**Comment by oliverhbailey** [comment]
Hi Don,
I attached a png file of the message box. Sorry about that.

I added the path to /usr/lib32 as instructed in the cross compiling wiki
page with no change. I also added the i386-linux-ld ans i386-linux-as
scripts which led me to message box attached. There was no linker executed
before adding the scripts. I am at a complete loss, but I was curious if I
download the cross compiler libs zip file, can I store them in the local
folder tree and add the path. Or should I do that. I know you probably know
the answer, so I would like to do that if it is known to work.

Thanks,
Oliver

**Comment by LongDirtyAnimAlf** [comment]
Yes, you are lost.
Fpcupdeluxe has a lot of build-in knowledge to be able to build a cross-compiler.
I want to give you the advice to start new.
Fpcupdeluxe has installed everything in a directory of your choice. Remove all except fpcscr and lazarus directory.
Run fpcupdeluxe again to install FPC and Lazarus.
And also to install the cross-compiler.
Test the install with a basic app like a form with a single button. That way, you know the basic install works.

**Comment by oliverhbailey** [comment]
Attached is the fpcsrc/3.0.4/bin and units folder listings, the libs are
there.

**Comment by LongDirtyAnimAlf** [comment]
This looks very good. Fpcup is behaving as it should.
It has detected that your system binary utilities are able to compile for x64 as well as for i386. So, there is no need to download special binary utilities.
It has detected that sufficient i386 libraries are available inside /usr/lib/i386-linux-gnu to build the cross-compiler. So, no additional libraries are downloaded.
Also, your GUI app for linux i386 can be compiled. So, you are set and done. All utilities and libraries are available and good.
That is the way it should go if all goes well.
Now, you can also install cross-compilers for Windows, Mac, OpenBSD, Raspberry Pi and Android. and more.

**Comment by oliverhbailey** [comment]
Good morning Don,
I installed the Win32, Win64, and ARM cross compilers. I have
successfully built and tested Win32, Win64, ARM (Raspberry Pi 3), and Linux
64.

I have found the reason that i386 fails to link on Debian 10, but don't
know how to solve it. I am using XFCE, which I use on most all my systems.
Debian 10, now uses Wayland instead of X11. There is a test program called
weston that I installed and ran the morning to test display windows, and
nested windows. Nothing displayed inside the Window. I then installed
gnome-terminal because it does use the wayland compositor, and when I
executed gnome-terminal, it displayed in the weston display and not the
main display. There is nothing that discusses this, except a note that
Wayland doesn't support xfce, mate, or cinnamon yet. What's worse, is there
are no instructions on how to roll-back to X11 from Wayland. This is not
well publicized by Debian and that is the exact reason that other
distributions went back to X11.

This is not just a problem for lazarus. I've tried other cross-compiles for
linux-i386 from this as well. Only gcc based console apps compile using
make. And 32 bit GTK+ apps don't find the libraries. So, I'm going to a
non-XFCE desktop to pick this up and will get back to you, Wayland has
other issues as well, like not having the ability to support
remote-desktop-protocol.

Just wanted to share what I found. I'll kep you posted as I find the way
around this.

Regards,
Oliver

**Comment by LongDirtyAnimAlf** [comment]
Ok. Thanks for your feedback.
I will close this issue now.
Wayland is something not related to the functioning of fpcupdeluxe .
Please open a new issue when something related occurs.

**Comment by oliverhbailey** [comment]
Hi Don,
I successfully cross compiled and ran Win32, Win64, and ARM (Raspberry Pi).
This is a linker problem because its not looking in the right folders for
the i386 startup object files for i386. This screen tells the story. It's
looking in folder that don't exist within the ~/fpcupdeluxe sub folder. Its
too difficult to finger the folder structure out and it's not documented
anywhere. This goes back to fpc and lazarus projects, not you. As much as I
would like to include Lazarus, it is just not a good working product. I'm
covering other projects that cross compile fine. If this path issue could
be resolved for the i386, it wou;d be great, but I haven't even received a
response from the lazarus or fpc people, and going through the forums, this
has happened before.

Thanks for you help.

Oliver

**Comment by oliverhbailey** [comment]
Hi Don,
For some reason, the cross compiling instructions in the free pascal no
longer work for Windows 10. If you do a straight Lazarus
installation (downloading Lazarus and FPC from the Lazarus site), the
follow the cross compile instructions by downloading the win64-wini386
installation, nothing will cross compile because the win32-i386 libraries
aren't created and it looks in the win64-x86_64 libraries folder and fails.
It is not possible to use the Lazarus cross compiling instructions and get
a working cross compiler under Windows 10 with the current service pack.
The same problem exists if the Lazarus installation is uninstalled and
fpcupdeluxe is installed for Windows. A cross compiler cannot be installed
and used to build a Win32 program under Windows.
This is the same exact problem that exists in Debian 10 using fpcupdeluxe
for Linux-x86_64. The only difference is that the cross libraries are
built, but there is no linker run-time libraries for the gnu C compiler.
Ironically, the Windows cross compilers both work in Linux and work
perfectly for doing Win64 and Win32 cross development if Wine64 and Win32
are built.

The reason for the failure is due to the mandate that each operating system
has to support cross-platform execution transparently the executable
extension (exe for windows, .o or the executable flag in Linux, and .dmg
for Mac).

This has caused changes in the installation of multi-arch in GNU Linux, and
Windows 10, which has the Window Subsystem for Linux (WSL) installed in the
last several updates.

Under GNU Linux 10 (Debian Buster) release, dpkg s used to add additional
architectures (dpkg --add architecture i386), followed by apt update and
apt upgrade to install all support files (build-essential, binutils, and
the cross compilers) via normal apt commands. Using Eclipse, code blocks,
and netbeans for cross development has gotten much easier since the 64 bit
compilers, linkers, and assemblers are fully capable of generating 32 bit
bit code, assembly language, and executable programs with only the addition
of the 32 bit libraries.
It doesn't appear that FPC or lazarus has been updated to relect these
changes in the installed versions or the wiki instructions.

For example, if your turn on the Windows Subsystem for Linux (WSL) in
options, you cab build and test native Linux executable programs by calling
the subsystem. You can also run FPC text mode programs from within the FP
or FPC environment on Windows 10. This is also true of Visual Studio on
Windows and Linux for cross development.

I haven't tested under Windows 7, but I do a lot of cross development on
Windows and Linux. I write a book in 2004 that covered these topics and I
am working on the new version of that book.

Unfortunately, if the FPC and Lazarus teams don't implement the changes, I
believe they will find themselves with an truly great system will be at End
of Life because of falling behind.

I wanted to let you know that you've inherited the shortcoming of the FPC
and Lazarus project by default or so it seems. I also noticed the Lazarus
install does not install in the programs folder under Windows 10, even
though it uses NSIS as the installer. NSIS actually checks and can install
to the default programs folder based in Windows version.

In any case, I wanted to see if developing on Windows for Win64 and 32 was
a better option so I could still mention FPC in my new book. As it stands
today,, I have to remove all mention of FPC and Lazarus since it cannot
cross compile under Windows or Linux from 64bit to 32bit natively on either
platform. If this changes in the next month, please let me know. I have
been a big Pascal and Delphi user for decades. I alpha tested Turbo Pascal
and Delphi from the beginning.

Take Care,
Oliver Bailey

**Comment by oliverhbailey** [comment]
Hello Don,
I keep trying to get around these path issues but I need some accurate path
information to do so.

On the fpcupdeluxe wike page the default config file folder is as follows:
Linux

For Linux (and other Unix-like systems) the default configuration folder is:

~/.lazarus

There is no folder in the home folder that has lazarus in it, visible
or invisible.

I am attempting to build an LLVM version of the fpc compiler. The FPC
wike page state that I should cd into the fpc compiler folder. So I cd
into the ./fpcupdeluxe/fpcsrc/compiler folder to compile. The build
should happen with "make LLVM=1", and the cross compiler should be
built.

The problem is that the path structure for fpc is completely
different, and there is no documentation on what the paths for
fpcupdeluxe have been changed too.

Normally, a project of this scope would have a setup.sh file created
to adjust the paths to the working directory. This is demonstrated in
several tools that may have different configurations with a base
folder such as buildroot, yocto, or crosstool-NG.

If you prefer I post this in the fourm, just let me know. I hate to
keep bothering you, but it would be nice if fpcupdeluxe was usable by
developers who routinely use other open source tools and are familiar
with the typical ways of setting up multiple versions.

Thank you,

Oliver Bailey

**Comment by LongDirtyAnimAlf** [comment]
Don't worry. You may bother me.
I am happy with your feedback. It can help improving fpcupdeluxe and FPC and Lazarus.
I am a bit busy now. So maybe, my replies will be late and short.
I will come back to you.

**Comment by oliverhbailey** [comment]
So, I'm finding ways to set the paths for each cross compile. I started by
building a cross compiler for llvm. I have the cross compiler built and
will add the component libraries next. FPC cross compiler is supported by
the FPC wiki, so this should be too big a problem.

I'll keep this going for each cross compiler that runs on Linux. I started
with LLVM because all of the platforms you support can be run in a qemu
virtual machine from within lazarus. I'm not doing this all for you, but I
will provide an example of how you can execute a lazarus program for one
supported platform. After the first ones, you can easily figure out how to
do the other supported platforms.

Later,
Oliver

PS - Are you in the United States?

**Comment by LongDirtyAnimAlf** [comment]
Nop. No USA. But very Dutch ... :-)

**Comment by oliverhbailey** [comment]
One of the problems:
someone during the build of a cross compiler and library s shell is execute
with the environment. Somehow the path to the ~/fpcupdeluxe/lazarus folder
is bing inserted after the paaths to the compiler and units. Its causing
the part of the path under Linux to be truncated and the installation of
the units and libraries are not properly set. This is happening under
Debian 10.3 (buster). It appears to be how the default fpc.cfg are set
initially. I can compile the cross compiler and libraries, but when the
shell is executed. the paths get truncated and the actuall installation of
the libraries and startup object files for link fail to get processed,
returning a path error.

Oliver
