### ISSUE TITLE
Unable to build 3.2rc1 for x86_64-cocoa

### ISSUE THREAD

**Issue by rufusroflpunch** [LongDirtyAnimAlf/fpcupdeluxe#204]
I'm on Catalina trying to build the latest RC, 3.2rc1 using 1.6.8k. I'm receiving the following error:

> Start compiling package cocoaint for target x86_64-darwin.
       Compiling cocoaint/BuildUnit_cocoaint.pp
Compiled package cocoaint
Installing package cocoaint
The installer encountered the following error:
Unable to open file "cocoaint/units/x86_64-darwin/CoreGraphics.ppu"
make[2]: *** [packages_distinstall] Error 2
make[1]: *** [installother] Error 2
make: *** [installall] Error 2
fpcupdeluxe: ERROR: FPCNativeInstaller (CleanModule: FPC): Error running make for FPC failed with exit code 512
. Details:
 ERROR: Fpcupdeluxe fatal error !

**Comment by LongDirtyAnimAlf** [comment]
Confirmed. Will look into it !

**Comment by LongDirtyAnimAlf** [comment]
I completely forgot that I have seen this error before.
And that a normal FPC install gets an auto-magical patch to prevent it.
So. The patch:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/patches_v1.0/fpcpatch_darwin_makepackages_fixes_3_2.patch
In Setup+, you can add this patch for FPC.
Please test.

**Comment by rufusroflpunch** [comment]
I added that patch into the FPC patches section under Setup+, but I am still getting the same error.

**Comment by LongDirtyAnimAlf** [comment]
In that case I am lost ... also due to the fact that I cannot reproduce this issue with the patched FPC.

**Comment by rufusroflpunch** [comment]
Is there anything I need to do for a patch besides add it to the FPC patch list at the bottom of the Setup+ screen?

**Comment by LongDirtyAnimAlf** [comment]
Well. The patching should work this way. And you should get a warning on the screen that the sources are patched.
If not, please look at the patch itself. It is a single line change. You can make this change yourself in the sources. And tell fpcupdeluxe (in Setup+) just to do a rebuild only, without update.

**Comment by LongDirtyAnimAlf** [comment]
Should be solved upstream.
