### ISSUE TITLE
Unable to cross compile from mac os to aarch64 darwin and x86_64 isim

### ISSUE THREAD

**Issue by github-account-0x00** [LongDirtyAnimAlf/fpcupdeluxe#205]
I am trying to compile for iOS on a mac, used the trunk of both lazarus and fpc and then the AArch64 darwin crosscompiler. Managed to compile x86_64 darwin fine but when I changed the target architecture to AArch64 darwin(or x86_64 isim) in lazarus and pressed OK it gave me the error:
The project uses target OS=darwin and CPU=aarch64.
The system.ppu for this target was not found in the FPC binary directories.
Make sure fpc is installed correctly for this target and the fpc.cfg contains the right directories.

Base OS: MacOS Catalina 10.15.4
Target architecture: AArch64
Target OS: Darwin
Release v1.6.8k of fpcupdeluxe-x86_64-darwin-cocoa.zip

I got the same error when I try compiling for arm darwin too.
 How can I go about solving this? Any help is much appreciated

**Comment by LongDirtyAnimAlf** [comment]
Would you mind trying the latest release and give feedback about this issue ?
Thanks.
