### ISSUE TITLE
Release 1.6.8 Cocoa x86-64 - Not an executable (+ fix)

### ISSUE THREAD

**Issue by Hansaplast** [LongDirtyAnimAlf/fpcupdeluxe#208]
Just downloaded the 1.6.8 release for Cocoa (x86-64) and found the executable (/fpcupdeluxe-x86_64-darwin-cocoa.app/Contents/MacOS/fpcupdeluxe-x86_64-darwin-cocoa) to not being an executable.

Quick work around fixed it:

`chmod +x fpcupdeluxe-x86_64-darwin-cocoa.app/Contents/MacOS/fpcupdeluxe-x86_64-darwin-cocoa`

The link that I downloaded twice (Google Chrome):
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/1.6.8k/fpcupdeluxe-x86_64-darwin-cocoa.zip

**Comment by LongDirtyAnimAlf** [comment]
I have had this report a number of times. When I pack the Darwin app, the exe-flag is set. After download on Mac, the exe-flag is unset. You might test if this is correct by using a Linux-system to download the Mac-zip. I am interested in your findings.

**Comment by Hansaplast** [comment]
Just did a few test ...

I downloaded the on a Unix system: exe-flag is not set.
Tried extracting it on the Mac with Entropy: exe-flag is not set.
Downloaded it with Safari: same thing.
Downloaded it with Firefox: same thing.

Note: both Safari and Chrome were complaining that these files were not considered safe. Firefox did not complain. Not sure if that is related?

Maybe pack it as a DMG (not sure if that is an option) ?
I distribute my own apps as a zip sometimes as well, but haven't encountered this issue yet.
Then again; it's been a few weeks that I last used a ZIP for distribution.

Interesting observation: 
I just created a ZIP for one of my Lazarus apps. Placed it on my website and Downloaded it. It just works and I didn't get a warning from Chrome. However, my .app bundle was signed so maybe that is the key difference. Or are you generating the binary not under macOS maybe?

**Comment by LongDirtyAnimAlf** [comment]
Nope.
All binaries, including Mac, are created on Windows. I have hacked into the pas-zipper to set the exe-flag when zipping. Seems this still does not work.

**Comment by Hansaplast** [comment]
Ah OK, I guess that could cause the exe-flag not coming thru. 😞

**Comment by Hansaplast** [comment]
Anything I can do to help/test?

**Comment by Hansaplast** [comment]
Maybe something useful to add: I use these steps to make the script generated by FPCUpDeluxe an app.
1) I add a "&" at the end of line of the generate script, so I will not see a Terminal window open.
2) I run the script below to then make it an .app
3) I add an icon with copy and paste (it is probably an option to add an icon right away as well by adding a plist file and copying an icns file to the bundle resources)

I call the script appify.sh and it is called like so:

`appify.sh  Lazarus_fpcdeluxe Lazarus`

The script:

```
#!/usr/bin/env bash

APPNAME=${2:-$(basename "${1}" '.sh')};
DIR="${APPNAME}.app/Contents/MacOS";

if [ -a "${APPNAME}.app" ]; then
	echo "${PWD}/${APPNAME}.app already exists :(";
	exit 1;
fi;

mkdir -p "${DIR}";
cp "${1}" "${DIR}/${APPNAME}";
chmod +x "${DIR}/${APPNAME}";

echo "${PWD}/$APPNAME.app";
```

**Comment by LongDirtyAnimAlf** [comment]
Sorry, bit busy fighting with the mORMot.
Will come back to this issue in a few days.
Thanks for the help anyway !!

**Comment by LongDirtyAnimAlf** [comment]
You are welcome to try the new zips. These should execute out-of-the-zip !!

https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/1.6.8u/fpcupdeluxe-x86_64-darwin-qt5.zip

https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/1.6.8u/fpcupdeluxe-x86_64-darwin-cocoa.zip

**Comment by Hansaplast** [comment]
I'll give it a try! Thanks!

**Comment by Hansaplast** [comment]
First note: the lime green text should probably be a different color (maybe clHotlight?).
Not sure if this was the same in previous version, I just notice now that I can barely read it 😜 
("FPC Version" and "Lazarus version").

**Comment by Hansaplast** [comment]
Probably due to lack of experience, but somehow I cannot get Lazarus to be build.
I even removed the fpcupdeluxe directory and started from scratch, but it keeps trying to compile some Carbon stuff, if I'm reading this right - I'm compiling for x86_64, darwin, and couldn't find a way to force cocoa (running macOS Catalina, so 32 bit is not an option);

...
/fpcupdeluxe/fpcupdeluxe/lazarus/lcl/interfaces/./carbon/carbonbars.pp(16,2) Error: (2023) User defined: only cpu i386 is supported
...
/fpcupdeluxe/lazarus/lcl/interfaces/./carbon/carbondef.pp(187,1) Fatal: (10026) There were 1 errors compiling module, stopping

**Comment by LongDirtyAnimAlf** [comment]
Confirmed.
This is a fpcupdeluxe bugger.
Will solve.

**Comment by LongDirtyAnimAlf** [comment]
Should be fixed by latest release !

**Comment by Hansaplast** [comment]
Will give it a try right away! 👍🏻

**Comment by Hansaplast** [comment]
Seems to work great! Thanks for the hard work! 👍🏻

**Comment by LongDirtyAnimAlf** [comment]
You are welcome !

**Comment by Hansaplast** [comment]
p.s. let me know if you need help with testing on macOS. I'd be happy to assist.
