### ISSUE TITLE
Cross Compilation For 68K Amiga, MorphOS and AROS

### ISSUE THREAD

**Issue by phaze101** [LongDirtyAnimAlf/fpcupdeluxe#209]
Hi, it possible to add cross compilation for 68K Amiga, MorphOS and AROS

**Comment by LongDirtyAnimAlf** [comment]
Would you mind testing ?
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.8l

**Comment by phaze101** [comment]
Yes sure will let you know. I can see you added AROS and MorphOS but not 68K Amiga

**Comment by phaze101** [comment]
Sorry forgot to say that I will do this by tomorrow evening and will report back here.

**Comment by phaze101** [comment]
Hi, here are my results  for AROS and MORHOS

Program used is same one used in this video since it proves that works on all platforms, https://www.youtube.com/watch?v=yKGS6fcLLOE.

Debug Mode - AROS_i386, AORS_x64 and MorphOS in debug mode all dispaled the following error.
Compile Project, Mode: Debug_Aros_i386, OS: aros, CPU: i386, Target: bin\Debug\i386-aros\project1: Exit code 1, Errors: 1
Fatal: Can't find unit lnfodwrf used by project1

Release - AROS_i386 and AROS_x64
Compile Project, Mode: Release_Aros_i386, OS: aros, CPU: i386, Target: bin\Release\i386-aros\project1: Exit code 1, Errors: 1
project1.lpr(24,1) Error: Util i386-aros-collect-aros.exe not found, switching to external linking

Release - MorphOS
This one compiled and ran on an official copy of MorphOS. It did give an error related to the debugger for some reason but it was still good to run. See attached file.

I hope this helps and can I please ask what is the status of Amiga 68K.

One final note I was able to compile the same code for Windows x64 and Linux x64 (debug and release) without any issues.

Thanks for all the help so far.

![MorphOS](https://user-images.githubusercontent.com/50155919/79003102-c8358080-7b49-11ea-8607-14b43a0c88bf.png)

**Comment by LongDirtyAnimAlf** [comment]
Good feedback. Thanks.
About the issues.

1: Can't find unit lnfodwrf.
This is a FPC problem. If you want the debugger info into the executable, lnfodwrf is needed. But not enabled by FPC. Work-around: compile without debugging.

2: Util i386-aros-collect-aros.exe not found.
I have compiled the binutils from AROS itself. With the default GNU linker. However, FPC itself wants the special Aros linker. This is hardcoded into the FPC compiler. Will look into this.

3: Amiga m68k already running on my system. Will release soon, after bit more testing.

**Comment by LongDirtyAnimAlf** [comment]
Amiga added.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.8l

**Comment by phaze101** [comment]
Hi, I tried the 68K

Debug - Amiga 
Doesn't compile with same issue of AROS
Compile Project, Mode: Debug_Amiga_m68K, OS: amiga, CPU: m68k, Target: bin\Debug\m68k-amiga\project1: Exit code 1, Errors: 1
Fatal: Can't find unit lnfodwrf used by project1

Release - Amiga
It compiled by my code didnt work. Will try to come up with a different one. It also displays like morphos the same things about the debugger.

![a68K_release](https://user-images.githubusercontent.com/50155919/79018777-8d910f80-7b6c-11ea-8310-3510b3798ea6.png)

![A68K](https://user-images.githubusercontent.com/50155919/79018584-0c397d00-7b6c-11ea-8f61-4c632a8018e8.png)


I hope this help and looking forward for next release

**Comment by phaze101** [comment]
Slight update. Console Free Pascal Code for the Amiga worked without issues. So maybe the Gui Libraries are not there like for MorphOS and AROS or I am missing something :)

![Console68K](https://user-images.githubusercontent.com/50155919/79024219-2bd7a200-7b7a-11ea-885e-6f0564ba3f23.png)

**Comment by LongDirtyAnimAlf** [comment]
Again, you have to disable the debugging to get rid of the lnfodwrf error. FPC does not include this unit for these targets !
The command line hello world is very promissing !!
Always start cross-compiling tests with command lines only. This will show you if the basic setup is working.
And yes, there are no libraries [yet] for GUI. I need your help for that. I do not have these systems.
However, the latest version of fpcupdeluxe can install a special version of Lazarus that should/could be able to compile GUI apps for you. See for an entry named "aroslazarus" in the Lazarus versions list.
Make this a new FPC and LAzarus install(in a separate install directory), and give it a test. Perhaps it will work.

**Comment by LongDirtyAnimAlf** [comment]
About the resource error.
You might try setting
RequireDerivedFormResource:=False;
in your lpr file.

**Comment by phaze101** [comment]
Hi yes, I understand the about the debugger error. It was for information purposes to make you aware, that it was the same for 68K.
Yes I should have done it from start for command line. The reason I didn't as stated is that that video shows it working on all machines so I thought it would be the same. 
Will give it a try regarding the new Lazarus.
Thanks a lot for your help so far. You have made a dream come true with this tool and adding Amiga support.
Any progress on AROS?
I have to admit I am no expert in Free Pascal but I am enjoying this journey.

**Comment by LongDirtyAnimAlf** [comment]
All targets were added into the latest release of fpcupdeluxe.
Please test.

**Comment by LongDirtyAnimAlf** [comment]
![Aros](https://user-images.githubusercontent.com/10783972/79228964-929ed900-7e62-11ea-8bcd-7336161aafee.JPG)

Working !!

**Comment by phaze101** [comment]
Hi Sorry I was a bit under the weather and hardly switched my laptop. Will be checking and let you know.

**Comment by phaze101** [comment]
I updated compiler for AROS and same error for me, it cant build it. I am using release 1.6.8m.

Here is the error (The usual one). I guess now I am missing something.

![Error](https://user-images.githubusercontent.com/50155919/79671699-6e296080-81c4-11ea-8800-8cd57d13e654.png)

**Comment by LongDirtyAnimAlf** [comment]
To be expected. You need the newly compiled binaries.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/wincrossbins_v1.1/WinCrossBinsArosx64.zip

**Comment by phaze101** [comment]
Thanks this worked. Actually I do not know how to thank you enough for this and for all your help. I was wondering so much in the FB group to try to find a solution to this until I stumbled on your util. Great tool. One last question. It there a way to build the compiler with the new AROS tools or there is going to be a new update that does it.

**Comment by LongDirtyAnimAlf** [comment]
The current version should work 100% on every new install. Just the binary tools were changed a bit ! That is why I asked you to change them yourself.
Thanks.
Crossing from Linux to Aros should also work.
Mac is work in progress.
