### ISSUE TITLE
parts download problem

### ISSUE THREAD

**Issue by Awkward-im** [LongDirtyAnimAlf/fpcupdeluxe#210]
Windows 7, x86
when i trying to install FPC/Lazarus, fpcupdeluxe can't find SSL libraries and writing to log what want to download it. Since this moment no answer from fpcupdeluxe. i can move window but always see faded program window and "busy" cursor. Have not so fast internet connection via USB modem (smartphone with internet through wifi )

**Comment by Awkward-im** [comment]
If i place libeay32.dll and ssleay32.dll in program directory i see downloading wget.exe and sevenzip and got the same "busy" window.
always.

**Comment by LongDirtyAnimAlf** [comment]
I am aware of this problem.
Its hard to solve for me, as I do not have win7, 32 bit.
But I will look into it.
But pacing the two files into the fpcupdeluxe directory is a good first step !!

**Comment by LongDirtyAnimAlf** [comment]
The new release would/could be better in handling this.
Please test and report.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.8o

**Comment by Awkward-im** [comment]
Looks like problem was solved. data's downloading fine

**Comment by LongDirtyAnimAlf** [comment]
Ok. Thank you. Closing.
