### ISSUE TITLE
Help(kinda off-topic): Need to pick your brain, can't find contact

### ISSUE THREAD

**Issue by gcarreno** [LongDirtyAnimAlf/fpcupdeluxe#211]
Hey Don,

I'm the person behind the [setup-lazarus](https://github.com/gcarreno/setup-lazarus) GitHub Action.

I've got it to a point where it almost mimics [travis-lazarus](https://github.com/nielsAD/travis-lazarus), which is a way to get Lazarus setup on Travis-CI. The only thing missing is for the action to work with `macos-latest` to fully implement `travis-lazarus`.

I now want to use this [Lazarus package repo](https://packages.lazarus-ide.org/) to give `setup-lazarus` the ability to install 3rd party packages before compiling the `TestApplication.lpi`.

I'm completely baffled as how to do it via the command line with `lazbuild` only.

Could you please gimme a helping hand via: guscarreno `at` gmail `period` com ?

Thanks so much in advance!!

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Don,

I'm sorry if I stepped over any bounds, if so I apologise.

In the mean time I was able to solve my problem.

I'll close this issue.

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
Don't worry. All ok !
I am glad you could solve your issue.
