### ISSUE TITLE
release 1.6.8n?

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#214]
```

Release v1.6.8n of fpcupdeluxe

@LongDirtyAnimAlf LongDirtyAnimAlf released this 1 hour ago

Threading !!!!
```
what it means?

**Comment by LongDirtyAnimAlf** [comment]
It means that nearly all long duration processes are now running in a separate thread. The GUI will remain responsive and tbe process can be interrupted.
Please test.
