### ISSUE TITLE
Add 2.0.8 to *.ini file as Lazarus stable, please

### ISSUE THREAD

**Issue by gcarreno** [LongDirtyAnimAlf/fpcupdeluxe#216]
Hey Don,

Don't know if you noticed, but 2.0.8 is now the new stable release for Lazarus:

[Lazarus Release 2.0.8](https://forum.lazarus.freepascal.org/index.php?topic=49356.0)

Or you noticed but you're pretty busy. Sorry if it's this one.

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
Pre-release has new 2.0.8
You might try.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.8o

**Comment by gcarreno** [comment]
Thanks Don!!

I updated my end by hand, but I'll download a new version when you get a new release out, not a pre-release.

Will close.
