### ISSUE TITLE
Missing directory seperator in build paths

### ISSUE THREAD

**Issue by peardox** [LongDirtyAnimAlf/fpcupdeluxe#217]
The path below should be C:lazall\config_lazarus\idemake.cfg looking at the filesystem

fpcupdeluxe: info: FPCUPdeluxe V1.6.8m for x86_64-win64 running on Win64-10.0.18363

Fatal: (11009) Unable to open file **C:lazallconfig_lazarusidemake.cfg**
Fatal: (1018) Compilation aborted
Error: C:\lazall\fpc\bin\x86_64-win64\ppcx64.exe returned an error exitcode
make.exe[2]: *** [idepkg] Error 2
C:\lazall\fpc\bin\x86_64-win64\make.exe[1]: *** [idepkg] Error 2
Error: (lazarus) Build IDE: stopped with exit code 2
Error: (lazarus) Building IDE: Building IDE failed.
C:\lazall\fpcbootstrap\make.exe: *** [useride] Error 2

fpcupdeluxe: ERROR: UniversalInstaller (ConfigModule: suggestedpackages): Failure trying to rebuild Lazarus.
Details:

ERROR: Fpcupdeluxe fatal error !

**Comment by peardox** [comment]
I worked out how to get around this error

Basically my path has loads of dev tools in it so there are existing make utilities (this appears to be the main problem)

Opening a Windows command prompt (not powershell) and setting path=c:\windows then running fpcupdeluxe from the command line removes any possible clashes and the installer works perfectly.

It seems a good option to build this into a new release so other people don't have thee same issue

**Comment by LongDirtyAnimAlf** [comment]
Would you mind trying the new release to check if this issue will be solved ?
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.8o

**Comment by LongDirtyAnimAlf** [comment]
Closing due to no feedback.
