### ISSUE TITLE
Error message after recompile ide (1.6.8o)

### ISSUE THREAD

**Issue by sstvmaster** [LongDirtyAnimAlf/fpcupdeluxe#218]
I downloaded 1.6.8o and updated my trunk/trunk version. This compiled ok with fpcupdeluxe, after that i open the trunk IDE and run IDE recompile to get back the modules. After the IDE recompile ended it tries to restart itself. And now there is a error message, see attachment.
![error_after_ide_recompile](https://user-images.githubusercontent.com/19416108/80918795-00a23600-8d67-11ea-9d48-aea43caa1d51.jpg)

**Comment by LongDirtyAnimAlf** [comment]
Confirmed.
Interesting bugger. Not sure if caused by fpcupdeluxe or Lazarus itself.
Will look into it.

**Comment by LongDirtyAnimAlf** [comment]
This is caused by FPC.
Its also reported on the forum and discussed.
So I will close this issue here.
