### ISSUE TITLE
1.6.8.o win7 32 bit

### ISSUE THREAD

**Issue by Awkward-im** [LongDirtyAnimAlf/fpcupdeluxe#220]
trying to install stable FPC and Lazarus. freezed on t_linux.pas patching

**Comment by LongDirtyAnimAlf** [comment]
You are welcome to try a pre-release:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.8o

**Comment by LongDirtyAnimAlf** [comment]
Closing due to no feedback.
