### ISSUE TITLE
better About dialog

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#222]
current dialog is poor
![Screenshot from 2020-05-11 14-17-23](https://user-images.githubusercontent.com/4154978/81556168-8b4fea00-9392-11ea-9497-558c798de51a.png)

CudaText dlg shows Widgetset, CPU, OS, FPC ver
![Screenshot from 2020-05-11 14-17-29](https://user-images.githubusercontent.com/4154978/81556215-9efb5080-9392-11ea-925f-5895ecc6815e.png)

**Comment by Alexey-T** [comment]
```
  labelPlatform.Caption:= Format('%s-%s-%s, fpc %s', [
    LowerCase({$I %FPCTARGETOS%}),
    {$I %FPCTARGETCPU%},
    GetLCLWidgetTypeName,
    {$I %FPCVersion%}
    ]);             
```

**Comment by LongDirtyAnimAlf** [comment]
Done.
Next release.
