### ISSUE TITLE
Please help Me to build FPCdeluxe for Arch Linux latest stable ARM64 architecture

### ISSUE THREAD

**Issue by JanuszChmiel** [LongDirtyAnimAlf/fpcupdeluxe#225]
Dear specialist,
Because I Am helpless to build Lazarus, latest Lazarus from Github by using make clean, I would like to know, how to build yours GUi tool on Arch Linux ARM64 Bit edition. I have downloaded fpc-3.2.0rc1-arm-android.cross.x86_64-linux.tar
from ftp.freepascal.org 
site. I have extracted .tar file and I have executed install.sh script. I can run Fpc and other binaries with no issue. COmpiler and other FP related binaries resides in /usr/bin

Thank you very much for yours instructions. Make can not build FPC deluxe so I do not know which commands should I try to type?
I can not extract .deb for ARM64 Debian and extract files like from .zip archive. It is not very good idea to mix modules for other Linux distro to other distribution. So I want to build from scratch.
Thank you very much for yours advices.

**Comment by LongDirtyAnimAlf** [comment]
Its not fully clear for me what you want to accomplish.
I guess you are running FPC and Lazarus on your ARM64 system ?
Please tell me why you should need an Android cross-compiler for building fpcupdeluxe ?

**Comment by JanuszChmiel** [comment]
I Am using Android, Termux, Proot and Arch Linux ARM 64. I have wanted to
get some Linux ARM64 BItz FPC, but it is not available on
ftp.freepascal.org. There is only Linux ARM edition. Arch Linux Aur
repository ARM64 do not contain prebuild Linux ARM64 Bit edition. There is
only FPC-src but without Linux ARM64 BIt compiler.
My goal is to have latest stable Lazarus for Linux ARM64. And final Goal is
to use Pandroid, which have been created to compile Pascal apps for Android
from Linux X86 system.
I have finally compiled ppcjvm thanks to Debian based distros.

**Comment by LongDirtyAnimAlf** [comment]
Well.
If you want to build for Android, its easy.
You need to cross-compile towards Android.
Please read the info for cross-compilation.
Or use fpcupdeluxe to do the magic.
Plenty of info on the forum.

**Comment by JanuszChmiel** [comment]
Thank youv ery much for yours kind access to my plea.

**Comment by LongDirtyAnimAlf** [comment]
Let me ask you in more detail.
Are you running an Arch-Linux on arm64 and you want to cross-compile for Android ?

**Comment by JanuszChmiel** [comment]
Yes. I would like to have latest stable Lazarus for Linux ARM64 and I would
like to have ppcjvm and yes, my goal is to compiler Pascal apps on Android
device thanks to Linux which will run on Android thanks to Termux and Proot.
Because having ppcjvm cross compiled for Android ARM64 is no The solution.
There is new package on The Github, Pandroid package. It is package
compatible with lazarus installable Lazarus package. And my goal is to build
.apk packages on Android devices by using Linux, Lazarus and ppcjvm.
My first dream has to build and develop very simple IDE for Android, which
would allow programmers to create and compile Pascal apps on Android devices
with no need to use Linux or Lazarus.

But it was too complex task for Me. First of all, Android build tools, Open
JDK, and apache ANT. Those apps would had to run directly on Android without
Linux, termux or Proot.
Too complex.
Because Termux and Proot is very matured project, and because ARchLinux
ARM64 is very stable on Android, I can try it out.
Sure. Lazarus is IDE which allocate much RAm and The question is, if I will
have The success to run Lazarus. It is possible to compile it without
problems. But making it usable with its GUI.
When I will have The lazarus functioning, I will have The chance to add Lamw
and Pandroid package to Lazarus. But it will start to be very big binary,
may be, that it will fail on such non standard environment.


https://github.com/zeljkoc/PandroidPackage

My goal is to avoid using of X86 Intel based big computer or laptop to build
professional ANdroid app thanks to using Pascal.
Termux and Proot is so stable that even complex Gradle Java or Kotlin based
apps can be build.
I have even compiled Shortwave Radio player for more than 10 minutes without
crash. There is even attempt to implement shared memory support. Userland
uses special approach which even allow x11vnc sharing memory to work with
X11 server. But implemented sharing memory support has significant stability
issues. Some X11 apps are causing X11 server auto termination while loading.
But The reality is, that Userland Android app implement robust shared memory
support usable for non X11 apps such as mysql.
It would be complex task for very experienced C programmers to implement
robust and really stable shared memory support on Linux which run on
Android.
Unfortunately, Lazarus build in macro interpreter uses some sharing memory.
BUt I hope, that it is so simple shared memory task, that it will run even
with other Androidshmem library compatible with Termux.

**Comment by LongDirtyAnimAlf** [comment]
This is good info. Thanks !!
I will have a try in adjusting fpcupdeluxe to help you in your quest.
Will keep you informed.

**Comment by LongDirtyAnimAlf** [comment]
As our first goal, I would like to propose to get FPC installed and running on Android, with its own FPC-IDE.
Next step would be compiling for Android.

**Comment by JanuszChmiel** [comment]
I must use Arch Linux and Termux for this task. I have downloaded ARM64
Linux compatible FPC and now I have also compiled ppcjvm. Yes, Free pascal
package contain its little text mode based IDE. It run on Linux.

Making standalone IDE is too complex. Because if I would like to combine
Lamw and Pandroid Lazarus package, I do not have The chance to build Lazarus
which would run directly as A android app. it is task for very experienced
programmer. And making separate Ide which will interpret .lpr Lazarus files
and other XML lazarus related would be also not easy task.
This is The reason why I want to use Termux and Proot and Arch Linux. It is
even possible to prepare functioning Lazarus IDE which will run
aautomatically so user would not need to type on Linux terminal.
We could use Debian no root on Github for this task. As A good info. I have
successfully compiled ppcjvm. It is ARM 64 compatible Linux binary
executable from Arch Linux ARM64 which run from Termux by using Termux as A
terminal.

**Comment by JanuszChmiel** [comment]
Because FPC and PPVJCM work, it is time to build Lazarus to be able to build
FPCdeluxe thanks to it and not only this package. I will be able to add
lazarus packages later to lazarus binary. The important condition is that
Lazarus will be usable from Linux which run without systemd and system bus,
strict userspace variant of Linux.
So I Am starting to download Lazarus source and building it.

**Comment by JanuszChmiel** [comment]
aThe most positive fact on Termux, Proot and other Linux distributions is
The possibility to run Open JDk, Apache Ant and other helper tools without
issues. Open JDk for Termux has several issues, CPu have been overloaded so
it has caused colt phone reboot and freezes.
Sure. There are professional apps which are able to build Java apps to .dex
and compile them to .apk without Linux Termux and Proot. But I do not know,
how those apps are working. Where somebody has got Android build tools for
Android not for Linux. Or if there are some hydden commands installed inside
Android on devices.
But I must use The posisiblity which I AM having and those possibilities are
functional, even slightly slower thanks to Proot system calls but it work
and do not cause phone mother board overwarming.
I have downloaded FPC for Linux Aarh64 here.

ftp://ftp.freepascal.org/pub/fpc/beta/3.2.0-rc1/aarch64-linux/

It is slightly older compiler, but it is possible to compile even newer
release thaks to it.

**Comment by JanuszChmiel** [comment]
aaaGoog question is how to correctly start lazarus after it will be
correctly compiled and build. ./lazarus, or should I use startlazarus to get
GTk GUI of this app?

I have preloaded androidshmem.so library to support build in Lazarus macro
interpreter. Which call some shmem functions. May be, that this interpreter
play The crucial role to interprete .lpi and other files with project
information.

**Comment by JanuszChmiel** [comment]
So I now have lazarus 2.1.0 functional. I  have welcome dialog window with
tabs to specify compiler paths and oher thinks. I have made error, that I
did not used subversion instead.
But really, GUI of Lazarus is correctly working.

**Comment by LongDirtyAnimAlf** [comment]
That is good news. Closing this issue. Please re-open if needed.
