### ISSUE TITLE
on pressing Halt button during compilation of cross Linux64->Win64, deluxe hanged

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#226]
![Screenshot from 2020-05-17 08-21-08](https://user-images.githubusercontent.com/4154978/82136515-84542c00-9817-11ea-9dcc-f489e0d9235d.png)

**Comment by LongDirtyAnimAlf** [comment]
Latest release could solve.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.8r
