### ISSUE TITLE
button "set install path" is not Ok aligned in UI

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#228]
Ubuntu 20 x64

![Screenshot from 2020-05-17 16-24-26](https://user-images.githubusercontent.com/4154978/82148127-23e6de00-985b-11ea-9f44-cebe6412d121.png)

**Comment by LongDirtyAnimAlf** [comment]
Done.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.8s
