### ISSUE TITLE
Linux x86_64, zeos module installation error, v1.6.8r

### ISSUE THREAD

**Issue by ertankucukoglu** [LongDirtyAnimAlf/fpcupdeluxe#230]
Hello,

It is not possible to install any of available zeos database components. I got below
![image](https://user-images.githubusercontent.com/14805520/82179585-5c33fe00-98e7-11ea-8354-1236fa43204b.png)

Nothing specific to error in log or anywhere that I can find. Turning on Be extra verbose under Setup+ is not helping.

**Comment by LongDirtyAnimAlf** [comment]
Their seems to be an exception.
If so, this is a fpcupdeluxe bugger.
Will look into it.

**Comment by LongDirtyAnimAlf** [comment]
Solved.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.8s
