### ISSUE TITLE
MS Surface Pro X has Win10 on ARM64, need cross for it

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#231]
![Screenshot from 2020-05-18 14-20-39](https://user-images.githubusercontent.com/4154978/82207651-dded5100-9912-11ea-8681-870ad4b78d67.png)

error on installing that cross

**Comment by LongDirtyAnimAlf** [comment]
Please check.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.8s

**Comment by Alexey-T** [comment]
you are fast. thanks, will check it soon.

**Comment by Alexey-T** [comment]
it gives another error msgbox.
![Screenshot from 2020-05-18 19-59-59](https://user-images.githubusercontent.com/4154978/82239912-30923180-9942-11ea-8d29-ee31a46bb5d0.png)

**Comment by Alexey-T** [comment]
UI bugs fixed
![Screenshot from 2020-05-18 20-00-41](https://user-images.githubusercontent.com/4154978/82239965-47d11f00-9942-11ea-957e-addbdfa8d3f4.png)

**Comment by Alexey-T** [comment]
and log is cleared (UI bug)
![Screenshot from 2020-05-18 20-02-01](https://user-images.githubusercontent.com/4154978/82240090-81098f00-9942-11ea-93ab-009fdef4f15e.png)

**Comment by LongDirtyAnimAlf** [comment]
As you can see: not supported by fixes.
You need trunk.

**Comment by Alexey-T** [comment]
okay, so I cannot test w/o trunk, sorry

**Comment by Alexey-T** [comment]
something in broken in ur code, deluxe with FPC trunk cannot install subj.
![Screenshot from 2020-05-18 20-46-44](https://user-images.githubusercontent.com/4154978/82243756-caf57380-9948-11ea-8abc-a5fbbd9d59f5.png)

**Comment by LongDirtyAnimAlf** [comment]
Sorry about this. New release.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.8t

**Comment by Alexey-T** [comment]
this version also fails - 3.3 trunk log
[crs-winarm.txt](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/4646444/crs-winarm.txt)

**Comment by LongDirtyAnimAlf** [comment]
Good.
This is a FPC bugger.
A patch for it can be found in the patch-tag. Name contains "win64" or like.
However, if you enable onlibe patching and rebuild FPC, followed by a rebuild of cross, all will also be well.
Would be good of you can confirm this FPC bugger.

**Comment by LongDirtyAnimAlf** [comment]
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/patches_v1.0/fpcpatch_winarm64.patch

**Comment by Alexey-T** [comment]
I run "svn patch thisfilename" from /home/user/fpcupdeluxe_fpc33/fpcupdeluxe/fpc/units/x86_64-linux
but got a SVN error. so I dont know how to patch and how to build FPC

**Comment by Alexey-T** [comment]
applied it 

```
user@user-Notebook:~/fpcupdeluxe_fpc33/fpcupdeluxe/fpcsrc$ svn patch fpcpatch_winarm64.patch 
U         rtl/win64/Makefile
user@user-Notebook:~/fpcupdeluxe_fpc33/fpcupdeluxe/fpcsrc$
```
now how to rebuild FPC?

**Comment by Alexey-T** [comment]
maybe I can wait for FPC trunk update and press button in UI to apply all patches?

**Comment by LongDirtyAnimAlf** [comment]
![addpatch](https://user-images.githubusercontent.com/10783972/82285415-b7272d00-999b-11ea-9d27-ec8bbbda3d18.JPG)
Fpcupdeluxe makes life easy for you !
Just add the patch as shown. Press the FPC only button. Followed by the crosscompiler.

**Comment by Alexey-T** [comment]
thanks, will do that.

**Comment by Alexey-T** [comment]
after 1st compiling of cross, deluxe CLOSED in the middle of process. 2nd try: it worked.

**Comment by LongDirtyAnimAlf** [comment]
Keep me informed. I do not have a Win ARM64 device. Would be good to see some results.

**Comment by LongDirtyAnimAlf** [comment]
Closing.
Sidenote: patch is not needed anymore. FPC trunk issues are solved upstream.

**Comment by Alexey-T** [comment]
Thanks anyway

**Comment by Alexey-T** [comment]
now with fpc trunk-- task suceeded! cross added.
(fpc patch was rejected... but task ok.)
