### ISSUE TITLE
buttons "Add fpc patch"/"Rem fpc patch" overlap on Linux gtk2

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#233]
![Screenshot from 2020-05-19 10-05-50](https://user-images.githubusercontent.com/4154978/82295657-bea8ff00-99b8-11ea-9896-630c6cdeba18.png)

**Comment by LongDirtyAnimAlf** [comment]
Done. Next release.
