### ISSUE TITLE
need FPC 3.2fixes patch to support Win-ARM64 cross

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#234]
Can you please make this patch?

**Comment by LongDirtyAnimAlf** [comment]
Sorry. Will not do. This will mean updating all FPC makefiles, changes of sources, implement trunk changes into fixes. No time. And this is a FPC developers task. I am not a FPC core developer.
You might file a bug-request, but I guess they will reject it for the upcoming 3.2 release.

**Comment by Alexey-T** [comment]
now with fpc trunk-- task suceeded! cross added.
(fpc patch was rejected... but task ok.)
