### ISSUE TITLE
Debian 10 Linux x86_64, libqt5Pas link error

### ISSUE THREAD

**Issue by ertankucukoglu** [LongDirtyAnimAlf/fpcupdeluxe#235]
Hello,

Using v1.6.8t on Debian 10 x86_64 with fpc fixes3.2, lazarus fixes2.0
Everything goes well until linking of lazarus binary. Screen capture is as following
![image](https://user-images.githubusercontent.com/14805520/82320285-b1513c00-99db-11ea-8fae-f198960c5d30.png)
This is inside Hyper-V VM machine. I have trouble getting log file only.

Checking my system I seem to have necessary QT 5 libraries install
```
qt5-default/stable,stable,now 5.11.3+dfsg1-1+deb10u3 amd64 [installed]
libqt5pas1/stable,now 2.6~beta-6 amd64 [installed]
```
I do not have libqt5pas-dev installed though. Not sure if that is a must.

I am also not sure if that is related with some recent changes in Lazarus as I could not see anything in my google searches.

I could build just fine on same system about a week ago.

Any help is appreciated.

Thanks & regards,
Ertan

**Comment by LongDirtyAnimAlf** [comment]
Mmmm ... this linking with QT5 is very strange. Did you do anything with QT5, because this realy should not happen with the gtk2 version.

**Comment by ertankucukoglu** [comment]
On the OS side, I moved OS from MBR boot to UEFI boot in the VM. This is basically to boot it using Gen2 under Hyper-V. I am not sure if that applies though.

I also removed old fpcupdeluxe and install new one. I had a problem of zeos installation and wanted to test with new version.

Since I saw qt5 link trial, I also installed qt5-default and libqt5pas1 to see if they will be of any help. They did not.

I only post my issue in here after all these.

If interested and have time, I can arrange a remote access thru AnyDesk, TeamViewer 12, Alpemix. Only over windows, as my service provider is not assigning me a real IP address for direct access.

**Comment by ertankucukoglu** [comment]
Just tested with V1.6.8r on same system and no problems on linking as you can see below.
![image](https://user-images.githubusercontent.com/14805520/82367981-4c1e3a80-9a1d-11ea-93bd-cc88754c4ae7.png)

**Comment by LongDirtyAnimAlf** [comment]
This is very helpfull. Thanks.
Bit busy today. Will try to solve tomorrow.

**Comment by peardox** [comment]
Same thing occurred on Ubuntu 20 for me

**Comment by LongDirtyAnimAlf** [comment]
I can confirm this. Will remove this release.
However, I (still) do not have a clue about how this could happen.

**Comment by LongDirtyAnimAlf** [comment]
Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.8u

This is a very strange bugger. As you (perhaps) know, all binaries are build on a single Windows machine. I guess the pre-compiled ppu files got mixed up. I have now also separated all ppu-build directories. Hopefully, this will prevent this issue.
![aquirk](https://user-images.githubusercontent.com/10783972/82412178-7a2e6980-9a73-11ea-95a8-27188dd91be4.JPG)

**Comment by ertankucukoglu** [comment]
Got it crashed first time. Second time it completed just fine.
I could not see anything in log files or anywhere. Maybe it was one time problem.

Thank you.

P.S. I could also install zeos_stable just fine this time.
