### ISSUE TITLE
Linux x86_64, closing and opening changes selected items by one less

### ISSUE THREAD

**Issue by ertankucukoglu** [LongDirtyAnimAlf/fpcupdeluxe#236]
Hello,

I currently use FPC fixes3.2 and Lazarus fixes2.0 branches. Each time I open fpcupdeluxe it selects FPC fixes and Lazarus fixes which are one item prior in each list.

Just tested and same problem exists on Win64 version, too.

Nothing like a big problem but exists for quite a long time now.

Thanks & regards,
Ertan

**Comment by LongDirtyAnimAlf** [comment]
This will stay this way.
Fixes will always be the latest fixes. So, if you happen to install latest fixes (atm 3.2) this will happen.

When fixes 3.3 or 3.4 are created by FPC, fixes will point towards these new fixes.
And an install of fixes 3.2 will now be shown as fixes 3.2
