### ISSUE TITLE
Can I create Laz4Android thanks to yours tool?

### ISSUE THREAD

**Issue by JanuszChmiel** [LongDirtyAnimAlf/fpcupdeluxe#237]
Do you think, that yours tool can be used to create something like Laz4Android, which will support compilation targets to JVM, ARM and AArch64? If yes, is it always possible to select only one target at A time, patiently wait till build process will finish and when build process will be finished, Should I choose next target and choose it and press update install button? I have tried latest stable Lazarus 2.08, because official laz4android contain outdated Lazarus and every new Lazarus version is more accessible with screen reader, contain speed improvements, memory allocations improvements, ETC. My goal is to have Lazarus which will support ARM, AArch64 and JVM. Ppcjvm.exe which will be usable to create even Android based classes. Thank you very much for yours answer.

**Comment by LongDirtyAnimAlf** [comment]
I do not know all the details of Laz4Android.
But I guess fpcupdeluxe could do the same for you.

Its should be as simple as installing a prefered FPC and Lazarus version.
Followed by the building of the desired cross-compilers.

The above is the way I do it myself.
And this setup is used to build apk (sometimes together with LAMW) for ARM and ARM64 (with Gradle).

I have never had the need to use Laz4Android to build for Android.
But fpcupdeluxe could include some features of it, if needed.

**Comment by JanuszChmiel** [comment]
aaXes, you have right. I have really downloaded newest Lazarus and FPC and I
have used Lazandroid module wizard to build needed compilers for ARM and
other similar CPu targets.
Unfortunately, newest Lamw contain some issues. So I had to return to The
version from February of this year.

**Comment by LongDirtyAnimAlf** [comment]
LAMW issues can also be solved.
What are your LAMW issues ?

**Comment by JanuszChmiel** [comment]
Every Lamw based project can not be build. I Am getting errors inside
compiled Lamw units.
Because I do not see I have ddecided that I will use some of The demo
examples which are The part of Lamw for The needs of visually impaired
users.
I can not develp GUi in Lamw myself, because it is strictly visual based
platform. It is robust and professional work. And I do not want to degradate
The project. It has many advantages and I even think, that it will be The
most used free and opensource package for Android apps development by using
FPC and Lazarus.
Sighted programmers are very happy, because they can have benefit from
canvas based desktop, where they can design forms with up to date result
when they will find some pixel values.
Unfortunately, because Lamw units need to use real .lmf form files with The
various object position values, it is impossible to use it effectively for
visually impaireds programmers.
My onlyone solution for Me is to use The following bundle.
Which is not visual.
https://github.com/zeljkoc/PandroidPackage.git

Because this bunlde uses various non visual Pascal units, which can use
adjectives to specify object position allingment such as altop, albottom,
alright, alleft, it is even possible to slightly give object The necessary
values without numbers.
Sure. I know, that visual designers can produce more visually attractive
layouts. But when I have shown my mother The GUi of my app, there was no
problem. All letters have been shown correctly, no object overlapping.
There is even second similar project for Free Pascal, but it is not so
matured.
Android APi functions can not be used.

The biggest Free Pascal community issue is The lack of volunteers, who would
try to develop fully automated pascal app, which would be able to generate
Android Pascal APi header .pas and .inc files with no need to relay on
compiled .jar files from Google, ut rather by analysing legally vailable
Android APi source codes.
But this project is so complex, that it would had to involve many developers
and The question is, if so complex task can be anticipated to do from
programmers as A free iniative.

As A result, not all Android APi headers are correctly finished. But as a
basic module it is enough. I can play live streams by using Android media
player, may be that I could even detect if headphones have been disconnected
or not.
It is also possible to monitor incoming call to give readio player stop
instruction.

If you would know some absolvents or student of facultee of informatic
sciences, please give them The suggestion to develop automated tool to
generate Pascal APi header files by using opensource source code of Android
APi functions.

**Comment by LongDirtyAnimAlf** [comment]
Understood.

Would the FPC pas2js compiler be of any help for you ?
It would allow you to also target other platforms.

**Comment by JanuszChmiel** [comment]
It is good compiler. But it is not easy to study Pascal and Javascript
language together to compile functioning WEB apps.
There is big commercial project studio word is in its name, but Free Pascal
Pas2JS units are combining Javascript and Pascal language and there is A
question, if I could use more Pascal language than Javascript.
You have right. WEB apps development is modern todays trend and there is
more and more possibilityes while developing.
But when I have analysed Pas2JS Audio unit, it was so complex to understand
it, that I could not determine how to type commands to open live MP3 stream
for example. Yes, WEB apps development allow also coding without giving
object position values. The question is, if I have a right impression, if
can i really code without numbers. Because Pas2JS apps can work in two
modes. Console mode and object GUI.
And sure, it would be nice to create GUI with radio buttons, button,
comboboxes, ETC.
If somebody will have so much programmers experience and will develop simple
to understand Pas2JS units, which would be very similar to Pascal with no
need to use Javascript commands in The app source, it would be my biggest
positive moment on my life.

**Comment by LongDirtyAnimAlf** [comment]
I do not understand all that you have written so far. I am sorry about that.
But if you have any question or request related to fpcupdeluxe, you are welcome.

For other things, I am normally very short in time. Besides, I have a business to run and the Corona makes this very difficult and time consuming.
