### ISSUE TITLE
FPC runtime error 217

### ISSUE THREAD

**Issue by skoro** [LongDirtyAnimAlf/fpcupdeluxe#239]
Hello!
I'm using fpcupdeluxe 1.6.8u and 1.6.8q and every time of building Lazarus (stable) I'm getting the error **FPC runtime error 217**.
I should outline that the error happens only during Lazarus building, fpc (stable) builds fine.
My spec:
Kubuntu 20.04
QT 5.12.8
libqt5pas1:2.6~beta-6build1 (-dev package of the same version is also installed)

**Comment by LongDirtyAnimAlf** [comment]
You might try to disable the use of jobs.
See Setup+ : "Use jobs for GNU make".

**Comment by skoro** [comment]
Thanks a lot but it doesn't work. I was trying different combinations of fpc and lazarus. fpc was ok but lazarus from 20 tries only 2 or 3 were successful ("jobs for make" option was disabled).

**Comment by LongDirtyAnimAlf** [comment]
This is an unresolved issue when using lazbuild.
Many bug-reports have been filed already. You may take a look at the bugtracker of Lazarus.
As this is not related to fpcupdeluxe, I will close this issue.
But rest assured: many hours (also by me) have already been invested in trying to solve this.
