### ISSUE TITLE
Feature request: Adjustable font size console output?

### ISSUE THREAD

**Issue by Hansaplast** [LongDirtyAnimAlf/fpcupdeluxe#243]
Feature request;
Would it be possible to make the font size for the console output (the black area) user configurable? 

Maybe I'm overlooking an option, but I have the hardest time reading the output there. I find myself always having to copy the text to a text editor so I can read what the output is.

Keep up the good work! 👍🏻

**Comment by LongDirtyAnimAlf** [comment]
This should already be possible by Ctrl-mousewheel !
As all browsers allow. Hope it will work for you too.

**Comment by Hansaplast** [comment]
Under macOS, CTRL+MouseWheel will actually zoom in the entire screen. So everything will get bigger - like using a magnifying glass - and one has to move the mouse around to be able see every corner of the screen. It also does not exactly make the text more readable either (it is like zooming into a text on a photo, text gets blurry).
So unfortunately, not exactly a workable fix.

Maybe add a Speedbutton to toggle the font between standard (size=11, what you are using right now) and zoomed(size=0, the default font size) ?

I'd understand if you don't have the time to do this.
Thanks for responding though.

**Comment by LongDirtyAnimAlf** [comment]
For me, it works as expected.
Doing CTRL-Mousewheel inside the black window.

![macsmall](https://user-images.githubusercontent.com/10783972/84523206-3debd300-acd8-11ea-8c41-8d8fddaa6c71.JPG)
![macbig](https://user-images.githubusercontent.com/10783972/84523216-417f5a00-acd8-11ea-8947-b715e7f58a0b.JPG)

**Comment by Hansaplast** [comment]
I checked all my settings (Mouse, Steermouse and Accessibility settings) on my Mac, but zooming does not work this way on my Mac, strangely enough ... it literally zooms the entire screen.

After some online searching, it _appears_ that zooming the entire screen is the default zoom method under macOS ([Apple Reference link](https://support.apple.com/guide/mac-help/mouse-zoom-image-larger-mchlp2975/mac)): "... you can use it to zoom in on part of the **screen**. ..."
I was unable to find any special settings to increase the font in a control.

Any suggestions would be most welcome. 😊 

Some version info, if useful:

- Mac Pro (2013 Trashcan) with a normal monitor (not Retina or HiDPI).

- macOS 10.15.5 with supplemental update (June 1st, 2020).

- FPCUPdeluxe v1.6.8v build 221,  Build-date: 2020-06-07,  darwin_x86_64-cocoa, fpc 3.2.0

**Comment by LongDirtyAnimAlf** [comment]
Strange. macOS 10.15.3 in a VM on Windows works flawless,
It is not a Mac function. Its just the OnMouseWheel function of SynEdit. Nothing fancy. And working on a VM but not in real life.
I do not have a Mac, so I am going to close this issue, due to the fact that I will not be able to solve.

**Comment by Hansaplast** [comment]
I totally understand you have bigger fish to fry, and not having a Mac most certainly doesn't make it any easier. Looking at your code though, and quite a bit of online searching, I did find a way to fix this (tested this on my Mac):

Based on what I found in the Lazarus Forum ([link](https://forum.lazarus.freepascal.org/index.php?topic=44907.0)), this would fix this issue.
From that particular post:

> There exists a handy constant ssModifier defined in unit Controls:
> `ssModifier = {$if defined(darwin) or defined(macos) or defined(iphonesim)} ssMeta {$else} ssCtrl {$endif};`

The easy fix: Lines 1120 and onwards, in the procedure **CommandOutputScreenMouseWheel** of **fpcupdeluxemainform.pas**:

Change this line of code (line 1123):

```
  if ssCtrl in Shift then
```    
to:

```
  if ssModifier in Shift then
```    

I have no clue why ssCtrl does not seem to work properly on my Macs, and I tested this on 3 Macs (macOS 10.15.5, 10.15.4), and 2 VM's (VMWare Fusion, macOS 10.15.5 and macOS 10.14). From what I read in the Lazarus Forum, this is not an uncommon issue.

The change above would make for an easy fix, keeping the CTRL key for all non-macOS platforms, and the Command key under macOS.

Since this would be a super easy fix, I hope you'd be willing to include this in future versions of fpcupdeluxe (I'm very grateful that you created this application - its been super helpful for me).

**Comment by LongDirtyAnimAlf** [comment]
For sure included !
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/27eec6d2d2078b8a0524e20f9edea39a4fc5159d
Thanks very much !!

**Comment by Hansaplast** [comment]
You're welcome, and thanks for including the change 😊

**Comment by Hansaplast** [comment]
p.s. This kind-a sounds like nit-picking, which I most certainly do not intend that way, as I very much appreciate the application you've build. 
For me, ssModifier was a new thing to learn as well haha ...

Anyhoo, in no way critical, but I noticed you're using:

```
  {$ifdef Darwin}
  if ssModifier in Shift then
  {$else}
  if ssCtrl in Shift then
  {$endif}
```

But these lines can be written by one single line, since ssModifier already includes the same Darwin-check:

`  if ssModifier in Shift then`
 
ssModifier is defined in the controls.pas unit as:

```
  // Mac and iOS use Meta instead of Ctrl for those shortcuts
  ssModifier = {$if defined(darwin) or defined(macos) or defined(iphonesim)} ssMeta {$else} ssCtrl {$endif}; 
```

Of course you could also write it as:

```
  {$ifdef Darwin}
  if ssMeta in Shift then   // ssMeta instead of ssModifier
  {$else}
  if ssCtrl in Shift then
  {$endif}
```

**Comment by LongDirtyAnimAlf** [comment]
I have done something in between, that makes some sense and some not.
;-)

**Comment by Hansaplast** [comment]
👍🏻😁
