### ISSUE TITLE
Failed to install module lamw

### ISSUE THREAD

**Issue by e-files** [LongDirtyAnimAlf/fpcupdeluxe#244]
fpcupdeluxe: ERROR: UniversalInstaller (GetModule: lamw-ant): Error downloading from http://mirror.serverion.com/apache//ant/binaries/apache-ant-1.10.7-bin.zip

apache-ant-1.10.7-bin.zip no longer exist.

latest version
http://mirror.serverion.com/apache//ant/binaries/apache-ant-1.10.8-bin.zip

**Comment by LongDirtyAnimAlf** [comment]
Thanks !!
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/0f4076e622dd52f6beefb941dfdf89371cc8a6a1
