### ISSUE TITLE
Release v1.6.8w not working on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by tuurke63** [LongDirtyAnimAlf/fpcupdeluxe#245]
I am unable to get the installation working on this operating system. I downloaded "fpcupdeluxe-x86_64-linux" and copied the file to the desktop. I then execute "cd Desktop" followed by "sudo ./fpcupdeluxe-x86_64-linux".

The setup shows me the user interface. I leave all settings as default, select "fixes" for both fpc and Lazarus, then click the "install/update fpc+lazarus" button.

The program then logs an error "fpcupdeluxe: ERROR: FPCNativeInstaller (BuildModule: FPC): /root/fpcupdeluxe/fpcsrc/Makefile not found. Severe error. Should not happen. Aborting." 

and that's it. it's not getting any further. Am I doing something wrong?

**Comment by LongDirtyAnimAlf** [comment]
Would you mind trying to run as a normal user.
This could be related to root issues that I did not cover.

**Comment by tuurke63** [comment]
As a normal user, these are the errors I get:

fpcupdeluxe: Start of compile error summary.
fpcupdeluxe: ERROR: Tried to get FPC version from Makefile.fpc, but no Makefile.fpc found
fpcupdeluxe: Start of compile error summary.
fpcupdeluxe: ERROR: FPCNativeInstaller (BuildModule: FPC): /home/arthur/Desktop/fpcupdeluxe/fpcsrc/Makefile not found. Severe error. Should not happen. Aborting.
fpcupdeluxe: Done !!

**Comment by LongDirtyAnimAlf** [comment]
If the Makefile cannot be found, the FPC sources are not there.
Can you check if SVN has downloaded all sources ?
Can you show the whole output of fpcupdeluxe ?

**Comment by tuurke63** [comment]
I have downloaded version .X and it gave a more sensible error message about my machine missing subversion! I have installed that and now it works! Thanks!

Hey, how does one keep fpcupdeluxe itself up-to-date on a machine, will it automatically do that or do I have to download/install each new installer?  Thanks for your amazing work!

**Comment by LongDirtyAnimAlf** [comment]
Fpcupdeluxe has an self-update detector build-in. But that feature is disabled by default, due to some users reporting problems when Internet connection is unreliable. Will look into something more suitable.
