### ISSUE TITLE
Error compiling fpc stable + lazarus trunk

### ISSUE THREAD

**Issue by sgmihai** [LongDirtyAnimAlf/fpcupdeluxe#246]
This is what I get:
https://0bin.net/paste/OHToruv5BPnWHT21#QT8TK6IHW2z12Y9v74hs17DYdcXq5RKf6QUzXba8Eb9
host: linux 64 bit kde (qt). Latest fpcupdeule linux64 qt binary from yesterday.
Just select fpc stable + lazarus trunk and click install. Lazarus stable seems to work.

Not sure if this is a fpcupdeluxe issue or a problem with the lazarus code.
I got a popu message saying this might be cause by a leftover ppc process, and to try and close it. But there's no such process running when I get the error.

Please try and see if you can reproduce and identify the problem. Thanks.

**Comment by LongDirtyAnimAlf** [comment]
This is a known issue. Please have a look at the Lazarus bugtracker and look for lazbuild errors.
At this moment, the Lazarus team is unable to solve. 
Just re-run fpcupdeluxe !

**Comment by LongDirtyAnimAlf** [comment]
Closing. Will report back if this is solved by either Lazarus team or me.
