### ISSUE TITLE
Error Building IDE v1.6.8 (chmreader)

### ISSUE THREAD

**Issue by hafedh-trimeche** [LongDirtyAnimAlf/fpcupdeluxe#247]
FPC: 3.2.0
Lazarus: 2.0.8
D:\LazFree\fpc\units\i386-win32\chm\chmreader.ppu:chmreader.pas(80,12) Fatal: (10022) Can't find unit chmreader used by ChmLangRef
Fatal: (1018) Compilation aborted
Error: D:\LazFree\fpc\bin\i386-win32\ppc386.exe returned an error exitcode
make[2]: *** [idepkg] Error 2
make[1]: *** [idepkg] Error 2
Error: (lazarus) Build IDE: stopped with exit code 2
Error: (lazarus) Building IDE: Building IDE failed.
make: *** [useride] Error 2
fpcupdeluxe: ERROR: LazarusNativeInstaller (BuildModuleCustom: UserIDE): make.exe returned exit status #2

ERROR: Fpcupdeluxe fatal error !
Sequencer (UserIDE): Failure running fpcupdeluxe: error executing sequence UserIDE
Sequencer (Lazarus): Failure running fpcupdeluxe: error executing sequence Lazarus
Sequencer (Defaultwin32): Failure running fpcupdeluxe: error executing sequence Defaultwin32

**Comment by LongDirtyAnimAlf** [comment]
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/issues/259

Related ?

**Comment by gcarreno** [comment]
> #259
> 
> Related ?

Definitely related, if not the same, actually!!
