### ISSUE TITLE
Is it possible to add Socks5 proxy support?

### ISSUE THREAD

**Issue by edwinyzh** [LongDirtyAnimAlf/fpcupdeluxe#248]
As the title says. Thanks!

**Comment by LongDirtyAnimAlf** [comment]
Well.
There is not that much pascal code for socks5. Only Indy supports this type of proxy AFAIK.
However, we could use curl to connect through a socks5 proxy. That would not be that hard. But that leaves svn and git. Do you have any idea about how to use these together with socks5 ? That would be of great help !

**Comment by edwinyzh** [comment]
Sorry, but all I know is that TortoiseSVN can check out repositories through socks5 proxy.

**Comment by LongDirtyAnimAlf** [comment]
I that case, I am not able to implement.
You will need a third party tools to socksify through the proxy.

https://github.com/haad/proxychains
https://serverfault.com/questions/73475/how-can-i-set-proxy-for-subversion-with-ssh-tunnel
