### ISSUE TITLE
auto-add Lazarus option for Qt5 for Haiku

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#256]
I need to add "-dLCLQT5" for "Lazars optioons" coz Haiku dont have gtk2! many ppl dont know this! Can deluxe auto do this?

**Comment by LongDirtyAnimAlf** [comment]
This should not be necessary. Please try again on a vanilla install. The default widgetset on Haiku should be QT5.
And please state if this is x86 or x86_64.
