### ISSUE TITLE
after compiling Laz on Haiku, deluxe cannot place startlazarus shortcut on Desktop

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#260]

**Comment by LongDirtyAnimAlf** [comment]
That is correct behavior. I do not know how to do this on Haiku.
If time permits, I will dive into this. Closing for now.

**Comment by Begasus** [comment]
Link to the shortcut should point to `/boot/home/Desktop` :)
