### ISSUE TITLE
Release v1.6.8y of fpc(laz)up fails on darwin when getting/extracting bootstrap compiler.

### ISSUE THREAD

**Issue by ollydev** [LongDirtyAnimAlf/fpcupdeluxe#262]
Posting here since this seems like the more active repository and the code bases seem to be shared.

I've been using fpclazup on github actions for some time now, it's great. However the latest release (v1.6.8y) fails getting a bootstrap compiler only on macOS.

Working (1.6.4)
https://github.com/ollydev/Test/runs/850748180?check_suite_focus=true#step:2:123

Fails (1.6.8v)
https://github.com/ollydev/Test/runs/850748163?check_suite_focus=true#step:2:127

As a side note, both don't get a bootstrap compiler from Github FPCUP(deluxe) releases. That might be expected though.

Thanks.

**Comment by LongDirtyAnimAlf** [comment]
> As a side note, both don't get a bootstrap compiler from Github FPCUP(deluxe) releases. That might be expected though.

It should (must) get a bootloader through GitHub ! So, this is not expected (by me). Can you give me some more info about this ?

**Comment by ollydev** [comment]
@LongDirtyAnimAlf 

Ok Lots of debugging later...

> As a side note, both don't get a bootstrap compiler from Github FPCUP(deluxe) releases. That might be expected though.

It was failing to find a bootloader because githubs own servers (github action VMs) are rate limited to the github API! Crazy...

My question is, is it still needed to get bootloaders through github for new FPC versions?
You can see when github actions worked on [1.6.4](https://github.com/ollydev/Test/runs/850748180?check_suite_focus=true#step:2:123), it used `ftp://ftp.freepascal.org/pub/fpc/dist/3.0.0/bootstrap/x86_64-macosx-10.7-ppcx64.tar.bz2` and seemed to work? Did I get lucky?

Finally, if bootloaders aren't found on github there are a few bugs:

1) After downloading, `BootstrapFilePath` is `/Users/macvm/development/tmp/fpcup00002/x86_64-macosx-10.7-ppcx64.tar.bz2`
fpclazup thinks the file extension is `.7-ppcx64.tar.bz2` and this obviously doesn't match any of the match compression extensions so no command is ran.

2) `OperationSucceeded:=(ExecuteCommand(FTar,['-jxf',BootstrapFilePath,'-C',BootstrapFileArchiveDir,'-O','*'+CompilerName],FVerbose)=0);` Has the `-O` flag, which seems to write it to stdout and needs removing.

**Comment by LongDirtyAnimAlf** [comment]
Thanks for debugging. Will look into this.
And yes, GitHub is rate limited. Fpcupdeluxe has a build-in cache for the GitHub api, but this cache is only valid within a running fpcupdeluxe. A (re)start will clean the cache.

**Comment by LongDirtyAnimAlf** [comment]
You are welcome to try:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.8z

**Comment by ollydev** [comment]
Thanks! I merged your changes into fpcup and it worked fine using a bootstrapper from FPC.
```
./fpcup --installdir=laz --fpcURL=https://svn.freepascal.org/svn/fpc/tags/release_3_2_0/ --lazURL=https://svn.freepascal.org/svn/lazarus/tags/lazarus_2_0_10/ --lclplatform=cocoa --noconfirm --verbose
```
https://github.com/ollydev/Test/runs/854853971?check_suite_focus=true

Just to clear up some confusion, the VM github actions provides is permanently rate limited it seems (403 error) so fpcup can never access `api.github.com`. A cache system would be useless for this use.

This is why I was curious if using offical FPC bootstrappers for FPC 3.2.0 would work, which it seems to!

I hope you can publish a new release of fpcup soon with these changes so I don't have to distribute my own fpcup binary, Thanks!

**Comment by LongDirtyAnimAlf** [comment]
Glad it worked !
Will leave this issue open until fpcup has been updated.

**Comment by LongDirtyAnimAlf** [comment]
Done.
