### ISSUE TITLE
(Request for Comment) Sparta and CHM collision with FPC 3.2.0 and Laz 2.0.8

### ISSUE THREAD

**Issue by gcarreno** [LongDirtyAnimAlf/fpcupdeluxe#263]
Hey Don,

After my #259 and some one's #247, I think it's plain that `lazarus/components/sparta` at SVN Rev. 63482 and `fpcsrc/packages/chm` at Rev. 45643 are clashing.

I'm also aware that it's not an `fpcupdeluxe` problem per se.

So, my request is the following: Where should I make this known? 

Or is it already a known issue on the FPC side of things?

In the case it's known, and it has a fix, would it be useful to have `fpcupdeluxe` patch the source?
**Aside Note:** Well, it does have a fix, since FPC/Lazarus trunk have no issue with `sparta` and `chm`.

Many thanks,
Gus

**Comment by LongDirtyAnimAlf** [comment]
> Aside Note: Well, it does have a fix, since FPC/Lazarus trunk have no issue with sparta and chm.

Will close this as a problem not directly related to fpcupdeluxe.
