### ISSUE TITLE
jplib does not compile-install, and as a result jppack

### ISSUE THREAD

**Issue by dkounal** [LongDirtyAnimAlf/fpcupdeluxe#266]
Using FPC 3.2, FPCUPdeluxe 1.6.8y and https://svn.freepascal.org/svn/lazarus/tags/lazarus_2_0_10
The following error is returned by all module above in the tile when trying to install them
C:\fpcupdeluxe\fpc\units\i386-win32\chm\chmreader.ppu:chmreader.pas(80,12) Fatal: (10022) Can't find unit chmreader used by ChmLangRef

**Comment by gcarreno** [comment]
Hey @dkounal 

Oh look, `chmreader` rears it's ugly head again!!

Do you have `anchordocking` installed? It's a known issue that `sparta` and `chm` don't mix, and `anchordocking` depends on `sparta`.

If you don't have `anchordocking`, and subsequentially `sparta`, installed, then this could be a whole other cookie.

If you don't have it installed, could you list your installed components, please? Thanks!

@LongDirtyAnimAlf  doesn't want to chase this white rabbit, and I understand, a bit :stuck_out_tongue:, I'm having the same issue across `Lazarus 2.0.8 and 2.0.10` with `FPC 3.2.0` as per #259 

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
https://forum.lazarus.freepascal.org/index.php/topic,50528.0.html

**Comment by gcarreno** [comment]
Hey @LongDirtyAnimAlf ,

By posting this forum entry, are you saying for us to deal with it or that, since you're aware of it, you'll take care of it?

Just curious, not asking for anything. If you want us to deal with it I'm good!!

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
The forum post by the people responsible for FPC and Lazarus tell you all you need to know.
The issue is known. And will not be solved.
Me, just a simple FPC and Lazarus user, does not dear to dream to solve this if the experts themselves do not want to solve this due to very valid reasons.

**Comment by gcarreno** [comment]
Hi @LongDirtyAnimAlf ,

Okydokes, I get you and respect that.

I'll try and use the forum post info to suss out a temp solution until both `FPC` and `Lazarus` stable version catch up to the trunk revision where it's now, cuz trunk doesn't have this issue, and I'll stop moaning about it :wink:

Thanks, again, for all your patience!!

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey @LongDirtyAnimAlf ,

Sorry, can't keep this out of my mind, and it's nothing to do with you, just this bafflement stuck in my head.

What REALLY baffles me is that, that last forum post and the bug track issue I found, both have revisions lower than `Lazarus 2.0.10`, both say the problem is solved and only on `Lazarus trunk` is the issue solved, ARGHHH !!!!!1!!!1!11!1!

Sorry, just wanted to vent my lack of comprehension on this whole issue. I'll try and stop thinking about and do what I said on the comment above.

Cheers,
Gus
