### ISSUE TITLE
(Feature Request): Application exit shortcut

### ISSUE THREAD

**Issue by gcarreno** [LongDirtyAnimAlf/fpcupdeluxe#270]
Hey Don,

Would it be possible to add an action (Default action: FileExit) with a shortcut of `CTRL+Q` for Linux and `ALT+X` for Windows?

If you prefer I can do a PR, since I've boiler-plated this so many times that I have it on an MD file in a repo here, :stuck_out_tongue_winking_eye: 

Cheers,
Gus

PS: Please don't kill me!! I know I'm a tad annoying at times :stuck_out_tongue_winking_eye:

**Comment by LongDirtyAnimAlf** [comment]
Please detail for me which actions you expect from this shortcut.

**Comment by gcarreno** [comment]
Hi @LongDirtyAnimAlf ,

I'll do one better, I'll detail all of what I do and then you decide if you want it.

## Steps to what I mean

### Add File or similar top menu entry

Add a "&File", or any other name you see fit, menu entry on the to the left of "&Issues", with no action.

### Application exit menu entry and action

Create a default action from the action editor, the one that's under the File category and is "E&xit".

Leave the short cut empty.

Create a menu entry under the "&File", or similar and add the above action to it.

### Adding shortcuts according to platform

I usually add a `procedure TForm.InitShortcuts()` to my main form and then call it on `TForm.OnCreate()`, you can choose to do it where ever you want.

Add this unit to your main form, for the `VK_*` key constants:

```pascal
uses
  LCLType;
```

This is my `TForm.InitShortcuts()`:

```pascal
procedure TfrmMain.InitShortCuts;
begin
{$IFDEF LINUX}
  actFileExit.ShortCut := KeyToShortCut(VK_Q, [ssCtrl]);
{$ENDIF}
{$IFDEF WINDOWS}
  actFileExit.ShortCut := KeyToShortCut(VK_X, [ssAlt]);
{$ENDIF}
end;
```

And voila, that's it.

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
Thanks. Implemented.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/7e3718aa6d5708852944138c5769b0eefd4ae5ea

**Comment by gcarreno** [comment]
Hey @LongDirtyAnimAlf ,

Thank you SO VERY MUCH!!

Cheers,
Gus
