### ISSUE TITLE
Failure to detect previous svn revision after pulling updates

### ISSUE THREAD

**Issue by prof7bit** [LongDirtyAnimAlf/fpcupdeluxe#271]
I just noticed this in the log output while updating the compiler

````
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC was at revision: failure
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC is now at revision: 45770
````

My system is Linux x86_64.

**Comment by gcarreno** [comment]
Hi @prof7bit ,

Could I ask you to give a bit more details?

I'm asking, since based on your small details it seems that you had a non existent `fpcsrc` folder and `SVN` did a full download of the source.

I'm butting my nose on this one cuz I posted an issue related to `fpcupdeluxe` having problems with `SVN` commands and I want to see if somebody else has stumbled upon it, in another way.

Cheers,
Gus

**Comment by prof7bit** [comment]
No, the source was existing, the svn update took only one or two seconds.

**Comment by LongDirtyAnimAlf** [comment]
I have added some extra means to detect the previous revision. Will be available in next release.
About your issue:
I have no clue about this. Should (even could) not have happened.

**Comment by gcarreno** [comment]
Hey @LongDirtyAnimAlf ,

Dunno if you noticed but me and @prof7bit are using Linux, Ubuntu in my case, and we are having version/revision issues.

This thought has been nagging me in the back of my mind: 

* Could it be something related to `SVN` and not `fpcupdeluxe`?
* Has `SVN` changed something in the output of `svn info` that is tripping your detection?

It maybe nothing to do with anything, but I would be remiss if I wouldn't ponit it out, I think.

I'm using `SVN` version:

```shell
$ svn --version
svn, version 1.13.0 (r1867053)
   compiled Mar 24 2020, 12:33:36 on x86_64-pc-linux-gnu
```

@prof7bit : What's your version, please?

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
I do not think that changes in SVN have any influence.

However.

Fpcupdeluxe is being used in many systems and under circumstances unimaginable different than anything I had in mind when designing and supporting the app itself. In these cases, the only way out is to be able to reproduce the issue. So, I need all info needed to reproduce the issue and take measures.

**Comment by gcarreno** [comment]
Hey @LongDirtyAnimAlf ,

You are absolutely right and I have to admit I've been very lazy and kinda shifted the testing your way.

I'll do some testing on my end to try to find out if I can reproduce any of the things I've posted before and I'll update one of the existing issues or I'll create a new one with more info.

Sorry that I was lazy. I should've not rage erase that folder and paid closer attention to the logs for you. Will try harder next time.

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey @LongDirtyAnimAlf ,

You asked for more data points for better evaluation? I've just posted 3 new issues and a comment on #269 for you to look at :stuck_out_tongue_winking_eye: 

Cheers,
Gus
