### ISSUE TITLE
[Question] What version of SynEdit are you using?

### ISSUE THREAD

**Issue by gcarreno** [LongDirtyAnimAlf/fpcupdeluxe#275]
Hey @LongDirtyAnimAlf ,

I wanted to do a PR with what I asked on #270 (Application exit shortcut) and, if we're creating a "&File" top menu, maybe add:

* Save log to file
* Open log folder

And with `Lazarus 2.1.0(trunk)` I got some weird `Form.Left` and `Form.Top` errors so I tried `Lazarus 2.0.10` and it was complaining about missing properties on `SynEdit`.

Could you give me a better understanding of your setup so I can help you with a PR?

Many thanks in advance. I know I've been on your back a lot recently and I thought giving you a break would be a nice gesture and also gesture of good faith.

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
Save log done. Next release.
Open log will not be implemented.

The other errors are not related to fpcupdeluxe itself. There are changes between Lazarus trunk and Lazarus stable that are not compatible. That causes these errors.

**Comment by gcarreno** [comment]
Hey @LongDirtyAnimAlf ,

> Open log will not be implemented.

I'm sorry to have dropped this one without explanation. I thought it in my head and then was sure I explained it to you before. Dumb ass me!!

The "Open Log Folder" action would only make sense if you had a default log folder where you saved logs every time a "Run" ended. This way, the "Save log" action would have to be more like "Save Log As...".

This is what was in my head:
1. Option One, have only a "Save Log...", the user has the responsibility to save a log for debug purposes.
2. Options Two, `fpcupdeluxe` has the responsibility to save all logs(with some kind of log rotation and size occupied limit), hence the necessity of a "Open Logs Folder", and a "Save Log As...", well, just in case, eheheh

At the moment you implemented Option One and **I'm** fine if **you're** fine with it :stuck_out_tongue_winking_eye: !

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
You are right.
I will limit the responsibilities of fpcupdeluxe. Its just an installer script de luxe.
Many feature request pass my desk. Many are implemented, but only if they fit the primary functionality of this tool.
This is needed due to time and resource limits hampering this poor and lonely programmer .
