### ISSUE TITLE
Trying to "View Form" on fpcupdeluxe source gives error message and freezes Lazarus IDE

### ISSUE THREAD

**Issue by gcarreno** [LongDirtyAnimAlf/fpcupdeluxe#277]
Hey @LongDirtyAnimAlf ,

Sorry for causing you grief again with something I'm reporting!!

Every time I try to view the main form of `fpcupdeluxe` on the `Lazarus` IDE I get this error:
![fpcupdeluxe-error-show-form](https://user-images.githubusercontent.com/81799/87853456-15bc4900-c902-11ea-90b8-5bca40ad7481.png)

If you choose "Abort", the IDE closes it's windows but then you have to `kill -9 PID` to make it go completely away.

If you choose "Ok", well, this was a bit catastrophic the only time I chose it, since it froze my whole Gnome Session and I had to reboot the machine. Even after CTRL+ALT+F3 and killing the process on `tty3` the Gnome Session was still fubar. Didn't feel comfortable trying it again.

That function does not exist in your source code and I haven't yet had the time to see if that is LCL code in action.

If it is, how the F*ck, is your form calling a Send Message when in design mode?!?! Should you not test for that in any component so to avoid such issues?

Probably it's not even your fault... I dunno, need to investigate further.

Curious thing is, using `lazbuild` on your source, all goes well and it even runs nice :stuck_out_tongue: 

< whining > I want the ability to send you nice Pull Requests, and your source is actively disabling that, BUAAA < /whining >

Using source code: `fpcupdeluxe v1.8.0b` at a768c73.

Let's see now, folder `fpcsrc` is at (`FPC 3.3.1`):
```shell
$ svn info
Path: .
Working Copy Root Path: /home/gcarreno/FreePascal/fpcsrc
URL: https://svn.freepascal.org/svn/fpc/trunk
Relative URL: ^/trunk
Repository Root: https://svn.freepascal.org/svn/fpc
Repository UUID: 3ad0048d-3df7-0310-abae-a5850022a9f2
Revision: 45763
Node Kind: directory
Schedule: normal
Last Changed Author: pierre
Last Changed Rev: 45763
Last Changed Date: 2020-07-11 00:23:56 +0100 (Sat, 11 Jul 2020)
```
And folder `lazarus` is at (`Lazarus 2.1.0`):
```shell
$ svn info
Path: .
Working Copy Root Path: /home/gcarreno/FreePascal/lazarus
URL: https://svn.freepascal.org/svn/lazarus/trunk
Relative URL: ^/trunk
Repository Root: https://svn.freepascal.org/svn/lazarus
Repository UUID: 4005530d-fff6-0310-9dd1-cebe43e6787f
Revision: 63540
Node Kind: directory
Schedule: normal
Last Changed Author: martin
Last Changed Rev: 63540
Last Changed Date: 2020-07-10 20:38:45 +0100 (Fri, 10 Jul 2020)
```

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
Pull works. Pull request accepted in the recent past:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/pulls?q=is%3Apr+is%3Aclosed

The issues you report seem to be related to Lazarus.
And, to be honest, I do not completely understand your remarks.

**Comment by gcarreno** [comment]
Hey @LongDirtyAnimAlf ,

Never mind.

I'm really sorry that I'm really bad at making light humour.

Will close.

Cheers,
Gus
