### ISSUE TITLE
TSynEdit is showing representation of new line char on what should be multiple lines

### ISSUE THREAD

**Issue by gcarreno** [LongDirtyAnimAlf/fpcupdeluxe#282]
The content of the image should be multiple lines, not one line with the new line graphic, many times:

![fpcupdeluxe-tsynedit-line-breaks](https://user-images.githubusercontent.com/81799/88105395-c002cd80-cb9b-11ea-8800-a138a8d1299f.png)

**Comment by LongDirtyAnimAlf** [comment]
Fixed. Thanks for reporting.
