### ISSUE TITLE
[For Your Information] FYI, fpcupdeluxe.lpi goes boom on Lazarus with anchordocking

### ISSUE THREAD

**Issue by gcarreno** [LongDirtyAnimAlf/fpcupdeluxe#283]
You should close this issue once you've read it.

Don't think you can do anything about it, but it is quite odd, none the less.

This is ok and fine:
![fpcupdeluxe-lazarus-no-anchordocking](https://user-images.githubusercontent.com/81799/88107157-8a131880-cb9e-11ea-8a0d-67148f948f24.png)

This goes boom, as you can see:
![fpcupdeluxe-lazarus-with-anchordocking](https://user-images.githubusercontent.com/81799/88107317-ccd4f080-cb9e-11ea-970c-e7461c2212fb.png)

**Comment by LongDirtyAnimAlf** [comment]
Indeed not related to fpcupdeluxe. Its a Lazarus bugger. Will close.
