### ISSUE TITLE
Error install compiler arm - linux under windows

### ISSUE THREAD

**Issue by elmarfaber** [LongDirtyAnimAlf/fpcupdeluxe#287]
Hello,

I get the following error if I would install the cross compiler arm/linux.
I try it for the stable version and the trunk version - no luck.

24.07.2020 13:25:18: fpcupdeluxe: V303 (20200721) started.
**FPCUPdeluxe V1.8.0d for x86_64-win64 running on Win64-10.0.18363**

Found valid svn.exe application.
Found valid svn.exe application.
Found valid git.exe application.
Found valid git.exe application.
Found valid hg.exe application.
fpcupdeluxe: info: FPCCrossInstaller (CleanModule: FPC): Running make distclean twice for target arm-linux
fpcupdeluxe: Executing: E:\Entwicklung\Lazarus\Stable\fpcbootstrap\make.exe FPC=E:\Entwicklung\Lazarus\Stable\fpcbootstrap\ppcx64.exe --directory=E:\Entwicklung\Lazarus\Stable\fpcsrc FPCMAKE=E:\Entwicklung\Lazarus\Stable\fpc\bin\x86_64-win64\fpcmake.exe PPUMOVE=E:\Entwicklung\Lazarus\Stable\fpc\bin\x86_64-win64\ppumove.exe FPCDIR=E:\Entwicklung\Lazarus\Stable\fpcsrc PREFIX=E:\Entwicklung\Lazarus\Stable\fpc INSTALL_PREFIX=E:\Entwicklung\Lazarus\Stable\fpc UPXPROG=echo CPU_SOURCE=x86_64 OS_SOURCE=win64 OS_TARGET=linux CPU_TARGET=arm distclean (working dir: E:\Entwicklung\Lazarus\Stable\fpcsrc)

...
...
...

E:/Entwicklung/Lazarus/Stable/fpcbootstrap/make.exe -C utils cleanall
echo '45643' > revision.inc
E:/Entwicklung/Lazarus/Stable/fpc/bin/x86_64-win64/fpc.exe -Ur -Xs -O2 -n -Fux86_64 -Fusystems -FuE:/Entwicklung/Lazarus/Stable/fpcsrc/rtl/units/x86_64-win64 -Fix86_64 -FE. -FUx86_64/units/x86_64-win64 -dRELEASE -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF   -dREVINC -dx86_64 -dGDB -dBROWSERLOG -Fux86 -Sew version.pas
version.pas(94,8) Error: Operator is not overloaded: "ShortString" + "Word"
version.pas(100) Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted
Error: E:\Entwicklung\Lazarus\Stable\fpc\bin\x86_64-win64\ppcx64.exe returned an error exitcode
make.exe[1]: *** [cycle] Error 2
E:\Entwicklung\Lazarus\Stable\fpcbootstrap\make.exe: *** [compiler_cycle] Error 2
fpcupdeluxe: ERROR: FPCCrossInstaller (BuildModuleCustom: FPC): Running cross compiler fpc E:\Entwicklung\Lazarus\Stable\fpcbootstrap\make.exe for arm-linux failed with an error code.

ERROR: Fpcupdeluxe fatal error !
Sequencer (FPCCleanBuildOnly): Failure running fpcupdeluxe: error executing sequence FPCCleanBuildOnly
Sequencer (Only): Failure running fpcupdeluxe: error executing sequence Only
Building cross-tools failed. Aborting.

Best regards

Elmar

**Comment by LongDirtyAnimAlf** [comment]
Strange error.
I have tried to reproduce, but to no avail.
On your system, the native install went well. The cross errors out. However, both compile the same files. Very strange.
Will look into it.

**Comment by elmarfaber** [comment]
I install on the Computer a new Windows 10 Professional and now the installation works fine but the 
fails under windows. One message with libiconv-2.dll was missing then come the message:
Debugger error
Ooops, the debugger entered the error state 
Save your work now!

Hit stop, and hope the best, we're pulling the plug.

Best regards

**Comment by LongDirtyAnimAlf** [comment]
Would you please test the newest release ?
Thanks.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2a

**Comment by elmarfaber** [comment]
So I have tested the new version. But I get the following error:
Debugger error

Ooops, the debugger entered the error state
Save your work now!

Hit Stop, and hope the best, ew're pulling the plug.

**Comment by LongDirtyAnimAlf** [comment]
Sorry for that.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2b
This one will work ... ;-)

**Comment by LongDirtyAnimAlf** [comment]
Closing. I guess this one is solved.
Please re-open if needed.
