### ISSUE TITLE
show special tip to user, when res-compiler cannot work

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#288]
For this err
```
Can't call the resource compiler "/home/debian/fpcupdeluxe2020/stable/fpc/bin/arm-linux/fpcres", switching to external mode
```
deluxe can show to user some msgbox, about that user needs more RAM.
deluxe can find this line in the output log.

**Comment by LongDirtyAnimAlf** [comment]
Already there.

https://github.com/LongDirtyAnimAlf/fpcupdeluxe/blob/3f3ffca5c48c35515c98baf0a894b58bee0a4d4e/fpcupdeluxemainform.pas#L1426
