### ISSUE TITLE
Odroid C1 - Ubuntu 20.04-3.10 mate

### ISSUE THREAD

**Issue by elmarfaber** [LongDirtyAnimAlf/fpcupdeluxe#292]
Hello,
I try to install it on the odroid c1 ubuntu system an after some time I get the following error:

The installer encountered the following error:
Compilation of "BuildUnit_chm.pp" failed
make[2]: *** [Makefile:1729: smart] Fehler 1
make[1]: *** [Makefile:2681: packages_smart] Fehler 2
make: *** [Makefile:2836: build-stamp.arm-linux] Fehler 2
make[2]: Verzeichnis „/home/odroid/Schreibtisch/fpcupdeluxe/fpcupdeluxe/fpcsrc/packages“ wird verlassen
make[1]: Verzeichnis „/home/odroid/Schreibtisch/fpcupdeluxe/fpcupdeluxe/fpcsrc“ wird verlassen
make: Verzeichnis „/home/odroid/Schreibtisch/fpcupdeluxe/fpcupdeluxe/fpcsrc“ wird verlassen

fpcupdeluxe: ERROR: FPCNativeInstaller (BuildModuleCustom: FPC): Error running /usr/bin/make for FPC failed with exit code 512
. Details: 

ERROR: Fpcupdeluxe fatal error !
Sequencer (FPC): Failure running fpcupdeluxe: error executing sequence FPC
Sequencer (DefaultSimple): Failure running fpcupdeluxe: error executing sequence DefaultSimple

Compilation of "BuildUnit_chm.pp" failed
make[2]: *** [Makefile:1729: smart] Fehler 1
fpcupdeluxe: Start of compile error summary.
fpcupdeluxe: ERROR: FPCNativeInstaller (BuildModuleCustom: FPC): Error running /usr/bin/make for FPC failed with exit code 512
. Details:
fpcupdeluxe: Done !!

Is there a chance to install the Lazarus system?

A apt-get installation of lazarus works fine but I can not install the Industrial  package
because the online package manager doesn't work and a manual install fails.

Thank you very much for your project!

Best regards 

Elmar

**Comment by LongDirtyAnimAlf** [comment]
Would you please test the newest release ?
Thanks.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2a

**Comment by LongDirtyAnimAlf** [comment]
Closing due to no feedback.
Please re-open if needed.
