### ISSUE TITLE
Building Lazarus breaks on RPi, MAKEFLAGS must be set to "-j1"

### ISSUE THREAD

**Issue by tednilsen** [LongDirtyAnimAlf/fpcupdeluxe#293]
* FPCUPdeluxe V1.8.0e (fpcupdeluxe-arm-linux)
* Raspberry Pi 3
* Linux 5.4.51-v7+ armv7l
* Raspbian GNU/Linux 10 (buster)
* Lazarus trunk.git db5e3f4d05eb822df895ab1fe615760c1f6799a7
* FPC trunk.git 60773c21b99c3d8317c7698413713f1fa7b2551b

I discovered that Lazarus will not build (RPi3 unless there is only one job at a time, so I changed my ENV to this:
`export MAKEFLAGS="-j1"`
...and Lazarus is now building perfectly

Cheers!

**Comment by LongDirtyAnimAlf** [comment]
Thanks. Will include this in next release.

**Comment by LongDirtyAnimAlf** [comment]
Please test:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2f

**Comment by LongDirtyAnimAlf** [comment]
Closing due to no feedback.
Please re-open when needed.
Please leave closed when solved.
