### ISSUE TITLE
Cross Compile to linux in Catalina

### ISSUE THREAD

**Issue by reminder2k1** [LongDirtyAnimAlf/fpcupdeluxe#294]
Hi, i have a problem with cross compile to linux x86_64 in catalina.

<img width="1792" alt="Screen Shot 2020-08-07 at 12 01 14" src="https://user-images.githubusercontent.com/967982/89610943-0d728080-d8a6-11ea-83ae-ad7e6b88cfa9.png">

Can you give me a suggest?

**Comment by LongDirtyAnimAlf** [comment]
This is a bug. Will solve when back from holiday !

**Comment by LongDirtyAnimAlf** [comment]
Would you please test the newest release ?
Thanks.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2a

**Comment by LongDirtyAnimAlf** [comment]
Closing due to no feedback.
