### ISSUE TITLE
Does not install libiconv-2.dll required by debugger on Win64-x86_64

### ISSUE THREAD

**Issue by chapmanworld** [LongDirtyAnimAlf/fpcupdeluxe#295]
<lazdir>\fpcbootstrap\gdb\x86_64-win64 is missing libiconv-2.dll which is "apparently" now required by the gdb debugger for windows on x86_64.

**Comment by LongDirtyAnimAlf** [comment]
Confirmed. Will solve when back from holiday.

**Comment by LongDirtyAnimAlf** [comment]
Would you please test the newest release ?
Thanks.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2a

**Comment by pult** [comment]
1,8,2,a
"fpcupdeluxe" does not load "libiconv-2.dll" automatically into "fpcbootstrap\gdb\x86_64-win64\"

When gdb configered to "C:\fpcupdeluxe\fpcbootstrap\gdb\$(TargetCPU)-$(TargetOS)\gdb.exe"
"libiconv-2.dll" need to manually copy
from "fpcupdeluxe\fpc\bin\x86_64-win64\"
into "fpcupdeluxe\fpcbootstrap\gdb\x86_64-win64\"

It not needed when gdb configured to "C:\fpcupdeluxe\fpc\bin\x86_64-win64\gdb.exe"
But it not work for debug "i386-win32". For "i386-win32" need use "fpcbootstrap\gdb\$(TargetCPU)-$(TargetOS)\"  == (fpcbootstrap\gdb\i386-win32).

**Comment by LongDirtyAnimAlf** [comment]
Thanks for the report. Should be fixed. Please test !
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2b

**Comment by pult** [comment]
1,8,2b
work fine - "libiconv-2.dll" now is exist
