### ISSUE TITLE
Mac Cross - Illegal parameter: -WM10.8

### ISSUE THREAD

**Issue by peardox** [LongDirtyAnimAlf/fpcupdeluxe#297]
Building the arm/darwin or aarch64/darwin cross compilers results in an Illegal parameter error

Here's the arch64 one (arm's the same except for saying arm rather than aarch64)

`Fpcupdeluxe: FPC cross-builder: Building compiler for darwin-aarch64.
fpcupdeluxe: info: FPC aarch64-darwin cross-builder: Detected source version FPC (compiler): 3.2.0
fpcupdeluxe: info: FPC aarch64-darwin cross-builder: Using compiler with version: 3.2.0
fpcupdeluxe: Start of compile error summary.
Error: Illegal parameter: -WM10.8
fpcupdeluxe: Start of compile error summary.
Error: Illegal parameter: -WM10.8
fpcupdeluxe: Start of compile error summary.
Error: Illegal parameter: -WM10.8
fpcupdeluxe: Start of compile error summary.
fpcupdeluxe: Start of compile error summary.
fpcupdeluxe: ERROR: FPCCrossInstaller (BuildModuleCustom: FPC): Running cross compiler fpc /usr/bin/make for aarch64-darwin failed with an error code.
fpcupdeluxe: Done !!

`

**Comment by LongDirtyAnimAlf** [comment]
Please tell me your build system !
E.g. :
Are you on Windows or Mac or Linux ?
What processor ?

**Comment by peardox** [comment]
Mac x86_64 i7

It'll run on other platforms? Needs XCode AFAIK...

**Comment by LongDirtyAnimAlf** [comment]
I need to know what version of FPC you are using. There have been many Darwin / iOS related changes included in FPC trunk. So, trunk differs from all other FPC versions.

`It'll run on other platforms? Needs XCode AFAIK...`
Yes, you can build from other platforms, if binutils and library are available.

**Comment by LongDirtyAnimAlf** [comment]
Would you please test the newest release ?
Thanks.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2a

**Comment by peardox** [comment]
Sorry for taking so long to get back to you

Is FPCUpDeluxe self-contained? You see I have a functioning setup I have cobbled together so I want to be 100% positive that trying out the latest build is has a fall-back if it don't work.

Should I just tar my entire ~/fpcupdeluxe dir? What about dot-directories and ~/Desktop/Lazarus_fpcupdeluxe (looks like gibberish)

**Comment by LongDirtyAnimAlf** [comment]
Yes, fpcupdeluxe if fully self-contained.
Me myself, I even add an "up"-directory into the fpcupdeluxe dir, containing its own version of fpcupdeluxe binary. Pointing to this tree.
Besides, I have a different installs of FPC and Lazarus, all build with fpcupdeluxe, all fully isolated.

My advice to you.
Just leave this install as it is.
And build a new install in a separate directory.

**Comment by LongDirtyAnimAlf** [comment]
Closing due to no feedback.
Please re-open if needed.
