### ISSUE TITLE
Can't install FPC+Lazarus

### ISSUE THREAD

**Issue by JoeJoeTV** [LongDirtyAnimAlf/fpcupdeluxe#298]
When trying to install FPC+Lazarus after a fresh start, I got this error(only the end of the log, it compiled the files before fine):
```
Free Pascal Compiler version 3.2.0-r45643 [2020/08/18] for x86_64
Copyright (c) 1993-2020 by Florian Klaempfl and others
(1002) Target OS: Linux for x86-64
(3104) Compiling allsyneditdsgn.pas
(3104) Compiling syndesignstringconstants.pas
(1010) Writing Resource String Table file: syndesignstringconstants.rsj
(3104) Compiling syneditlazdsgn.pas
(3104) Compiling synpropertyeditobjectlist.pas
An unhandled exception occurred at $0000000000000000:
EAccessViolation: Access violation
  $0000000000000000
  $00000000009F1804  SETTOOL,  line 1323 of exttools.pas
  $00000000009F2A5E  DESTROY,  line 1622 of exttools.pas
make: *** [Makefile:3610: useride] Fehler 217
/opt/fpcupdeluxe/lazarus/components/synedit/design/allsyneditdsgn.pas(11,3) Hint: (5023) Unit "SynDesignStringConstants" not used in allsyneditdsgn
(1008) 977 lines compiled, 0.5 sec
(1022) 3 hint(s) issued
Info: (lazarus) Execute Title="Build IDE"
Info: (lazarus) Working Directory="/opt/fpcupdeluxe/lazarus/"
Info: (lazarus) Executable="/usr/bin/make"
Info: (lazarus) Param[0]="-make: Verzeichnis „/opt/fpcupdeluxe/lazarus“ wird verlassen
fpcupdeluxe: ERROR: LazarusNativeInstaller (BuildModuleCustom: UserIDE): make returned exit status #512


ERROR: Fpcupdeluxe fatal error !
Sequencer (UserIDE): Failure running fpcupdeluxe: error executing sequence UserIDE
Sequencer (Lazarus): Failure running fpcupdeluxe: error executing sequence Lazarus
Sequencer (Default): Failure running fpcupdeluxe: error executing sequence Default
```

Specs:
FPCUPdeluxe Version: 1.8.0e
OS: Linux Mint 20 Cinnamon 64bit

**Comment by JoeJoeTV** [comment]
I got it to work. I also had LAMW Manager installed and after removing that, I could install FPC+lazarus using FPCUPdeluxe. And it still worked after reinstalling LAMW Manager after.

**Comment by JoeJoeTV** [comment]
Ok, I am getting this error again and I don't have LAMW4Linux installed currently. It worked before, but now I just can't get it to work. I tried deleting everything from the install folder, but it still won't work. It's the same error.

**Comment by LongDirtyAnimAlf** [comment]
Related:
https://bugs.freepascal.org/view.php?id=37179
I am closing this issue. Its not a fpcupdeluxe problem, but a Lazarus problem that must be solved by the Lazarus team.
However, this bugger is very hard to solve. I am still looking at ways to circumvent it, but to no avail.
I will report here if anything changes.
