### ISSUE TITLE
1.8.0e for FreeBSD x64 cannot install FPC stable (git and svn)

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#301]
It shows "got an unexpected exception, don't know what to do" in edit box and stops.
OS: GhostBSD last 

![bsd-err](https://user-images.githubusercontent.com/4154978/90956535-1b242a80-e490-11ea-9b49-937d7da1aaba.png)

**Comment by Alexey-T** [comment]
@LongDirtyAnimAlf ?

**Comment by LongDirtyAnimAlf** [comment]
Would you please test the newest release ?
Thanks.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2a

**Comment by Alexey-T** [comment]
With new version-

![Screenshot from 2020-10-12 17-14-55](https://user-images.githubusercontent.com/4154978/95756503-8a5b1580-0cae-11eb-8c5b-269c53ba394a.png)

**Comment by LongDirtyAnimAlf** [comment]
Have you installed gmake ?
Can you do a "which gmake"?

**Comment by Alexey-T** [comment]
no, I didn't. "which gmake" gives none.
It is GhostBSD with built in desktop.

**Comment by Alexey-T** [comment]
Can you show sane error when gmake not found?

**Comment by LongDirtyAnimAlf** [comment]
I guess that fpcuupdeluxe should have done this. It checks for the availability of GNU make (gmake). I do not know why this is not reported.
Will look into and implement a check !

**Comment by Alexey-T** [comment]
You have this...
```
function TInstaller.GetMake: string;
const
  {$if (defined(BSD) and not defined(DARWIN)) or (defined(Solaris))}
  GNUMake='gmake';
  {$else}
  GNUMake='make';
  {$endif}
begin
  if FMake = '' then
    {$IFDEF MSWINDOWS}
    //Only use our own make !!
    FMake := IncludeTrailingPathDelimiter(FMakeDir) + GNUMake + '.exe';
    {$ELSE}
    FMake:=Which(GNUMake);
    if FMake='' then raise Exception.CreateFmt('%s not found. Please install GNU make.',[GNUMake]);
    {$ENDIF MSWINDOWS}
  Result := FMake;
end;
```

**Comment by Alexey-T** [comment]
I guess exception is catched later so UI shows error in the black field.

**Comment by LongDirtyAnimAlf** [comment]
Implemented.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/fda0c44ffd4b19a313b038d428a1631d3df5eb4c
Next release.
