### ISSUE TITLE
Linux Mint 19.2 Error installing.

### ISSUE THREAD

**Issue by AnthoniG** [LongDirtyAnimAlf/fpcupdeluxe#302]
It stops and outputs the following
`
make[6]: *** [linux_all] Error 2
make[5]: *** [rtl] Error 2
make[4]: *** [next] Error 2
make[3]: *** [ppc1] Error 2
make[2]: *** [cycle] Error 2
make[1]: *** [compiler_cycle] Error 2
make: *** [build-stamp.i386-linux] Error 2
syscall.inc(69,11) Error: Identifier not found "sysenter_supported"
syscall.inc(101,19) Error: Unknown identifier "SYSENTER_SUPPORTED"
syscall.inc(146,19) Error: Unknown identifier "SYSENTER_SUPPORTED"
syscall.inc(198,19) Error: Unknown identifier "SYSENTER_SUPPORTED"
syscall.inc(255,19) Error: Unknown identifier "SYSENTER_SUPPORTED"
syscall.inc(317,19) Error: Unknown identifier "SYSENTER_SUPPORTED"
syscall.inc(385,19) Error: Unknown identifier "SYSENTER_SUPPORTED"
syscall.inc(460,19) Error: Unknown identifier "SYSENTER_SUPPORTED"
system.inc(178,4) Fatal: Cannot open include file "x86_64.inc"
Fatal: Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode
Makefile:3833: recipe for target 'system.ppu' failed
Makefile:2040: recipe for target 'linux_all' failed
Makefile:4435: recipe for target 'rtl' failed
Makefile:4308: recipe for target 'next' failed
Makefile:4313: recipe for target 'ppc1' failed
Makefile:4325: recipe for target 'cycle' failed
Makefile:2799: recipe for target 'compiler_cycle' failed
Makefile:2831: recipe for target 'build-stamp.i386-linux' failed

fpcupdeluxe: ERROR: FPCNativeInstaller (CleanModule: FPC): Error running /usr/bin/make for FPC failed with exit code 512
. Details: 

ERROR: Fpcupdeluxe fatal error !
Sequencer (FPC): Failure running fpcupdeluxe: error executing sequence FPC
Sequencer (Default): Failure running fpcupdeluxe: error executing sequence Default
`

Do not have a clue what that even means. Fairly new to Linux scene.
Help please.

**Comment by LongDirtyAnimAlf** [comment]
Would you please test the newest release ?
Thanks.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2a

**Comment by AnthoniG** [comment]
Will do. Just got a lot on my plate at moment

**Comment by LongDirtyAnimAlf** [comment]
Closing due to no feedback.
Please re-open if needed.
