### ISSUE TITLE
Lazarus fails to build on Windows 7 32 bits

### ISSUE THREAD

**Issue by HwapX** [LongDirtyAnimAlf/fpcupdeluxe#303]
Lazarus fails to build on Windows 7 32 bit, to me isn't clear what caused the failure.
C:\home\apps\fpcupdeluxe\fixes is a new folder, trunk builds fine.

Log: https://gist.github.com/HwapX/1b4b684dd0d2ab86a9685f4e9eeb4342

**Comment by HwapX** [comment]
I think its related to:
https://lists.freepascal.org/pipermail/fpc-devel/2020-September/043118.html
https://bugs.freepascal.org/view.php?id=0035991

**Comment by sstvmaster** [comment]
Same here with fixes/fixes, trunk OK.
[up.log](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/5160622/up.log)

**Comment by LongDirtyAnimAlf** [comment]
Would you please test the newest release ?
Thanks.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2a

**Comment by sstvmaster** [comment]
Same.
[2020-10-12_1800.log](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/5366175/2020-10-12_1800.log)

**Comment by LongDirtyAnimAlf** [comment]
Confirmed.

**Comment by LongDirtyAnimAlf** [comment]
This is a Lazarus bugger.
I have filed this bug. And added a patch to solve.
https://bugs.freepascal.org/view.php?id=37923

**Comment by LongDirtyAnimAlf** [comment]
The people of Lazarus took just one day to solve this issue !!
https://bugs.freepascal.org/view.php?id=37923

Closing.

**Comment by sstvmaster** [comment]
Many Thanks
