### ISSUE TITLE
Problem with cross compilation in QT

### ISSUE THREAD

**Issue by XinYiMan** [LongDirtyAnimAlf/fpcupdeluxe#304]
Hi guys, I have installed lazarus QT version (on my ubuntu machine) and the cross compiler for arm64. Except that when I cross compile I get the following message.

/fpcupdeluxe/20200830_qt5/cross/bin/aarch64-linux/aarch64-linux-ld: cannot find -lQt5Pas

how do i solve?

**Comment by LongDirtyAnimAlf** [comment]
I have prepared new libs.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/crosslibs_v1.2/CrossLibsLinuxAarch64.zip
Just copy them over your old libs and you can cross towards QT5.
