### ISSUE TITLE
How to keep fpcupdeluxe "current"?

### ISSUE THREAD

**Issue by tuurke63** [LongDirtyAnimAlf/fpcupdeluxe#306]
Sorry if this is a dumb question, but if I install Lazarus+fpc on Windows using fpcupdeluxe, how do I keep the installation "current" with the latest versions? 

Will fpcupdeluxe automatically update itself and "know" about the latest versions or how is it supposed to work?

Kind regards,
Arthur

**Comment by LongDirtyAnimAlf** [comment]
No.
It has an update reminder. But this feature is disabled by default. To prevent time-outs when accessing the Internet for possible updates.
However, in Setup+, you can enable this feature.
See: "Check for fpcupdeluxe updates (default=no)".
