### ISSUE TITLE
Release 1.8.0e x64 windows, freeze on OpenSSL download

### ISSUE THREAD

**Issue by Awkward-im** [LongDirtyAnimAlf/fpcupdeluxe#307]
Old problem still exists. When program trying to download OpenSSL library, it can't do it.
Maybe archive filename was changed, maybe captcha is problem, maybe something else.
As i understands, timeout needs.

**Comment by LongDirtyAnimAlf** [comment]
Well, it seems that Indy does no longer make its openssl available.
https://indy.fulgan.com/SSL/
Next release will use another URL to get the library files. Will keep this issue open until this release.

**Comment by Awkward-im** [comment]
i went to parent files directory (/OpenSSL), passed Captcha, entered child folder and download https://indy.fulgan.com/SSL/Archive/Experimental/openssl-1.0.2o-x64-VC2017.zip manually. Date was fresh. So, maybe names there was changed... or captcha don't let do it. anyway, better to use  timeouts to not let program to freeze

**Comment by LongDirtyAnimAlf** [comment]
Would you please test the newest release ?
Thanks.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2a

**Comment by Awkward-im** [comment]
well, now SSL libraries downloaded and unpacked fast. Program updating directory right now but looks like all ok.

**Comment by LongDirtyAnimAlf** [comment]
Ok. Thanks for testing. Closing.
