### ISSUE TITLE
Another error on installing fpc 3.2.0 on freebsd x64

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#310]
Installed gmake. It began but failed.
[freebsd-fpc.log](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/5366149/freebsd-fpc.log)

**Comment by Alexey-T** [comment]
```
[user@user-ghostbsd-pc /usr/home/user/Desktop]$ gmake -v
GNU Make 4.3
Built for amd64-portbld-freebsd12.2
```

**Comment by LongDirtyAnimAlf** [comment]
Please try FPC trunk !?
Thanks.

**Comment by Alexey-T** [comment]
Tried-- the same error 512 and same same gmake error

**Comment by LongDirtyAnimAlf** [comment]
if you do an:
ld -v
you will see that ld of FreeBSD is a ling towards lld from llvm. FPC will not work with lld. You need to use the GNU binutils on FreeBSD.

You can check your install by doing
ld -v
as -v
Normally, the binutils binaries will be installed in /usr/local/bin.
If you go into that directory (if the bins are installed), do (watch the ./):
./ld -v
./as -v
Use GNU make and GNU binutils and you are good to go !

**Comment by LongDirtyAnimAlf** [comment]
If you have a hard time to install the newest binutils, I have them made available.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/freebsdx64crossbins_v1.0/binutils-2.33.1_2.1.txz

Install:
pkg-static install binutils-2.33.1_2.1.txz

**Comment by Alexey-T** [comment]
>Use GNU make and GNU binutils and you are good to go !

How do I tell deluxe+FPC to use them?

No options here
![Screenshot from 2020-10-13 11-09-09](https://user-images.githubusercontent.com/4154978/95833613-8da0e080-0d44-11eb-8a5f-770bd26886a7.png)

**Comment by LongDirtyAnimAlf** [comment]
There is no way to tell FPC to use a certain linker. Just edit the symlink.
Look at "/usr/bin/ld". You wil see that this is a symlink.
Edit it to point towards /usr/local/bin/ld

**Comment by LongDirtyAnimAlf** [comment]
I found a way to get things working without changing the symlink.
You might try.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/1.8.2b/fpcupdeluxe-x86_64-freebsd12

**Comment by Alexey-T** [comment]
oh. That's good. Will try soon.

**Comment by Alexey-T** [comment]
it works now!
