### ISSUE TITLE
Freebsd 12 with fpc 3.2fixes - crash on compiling

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#311]
With FPC trunk it was OK. but I cannot use trunk - runtime AV on my codes. 3.2fixes is needed for me.
![bsd](https://user-images.githubusercontent.com/4154978/96509716-206ddd80-1265-11eb-9063-44f925864f77.png)

**Comment by Alexey-T** [comment]
Did restart - same error again. did 2nd restart - same error.

**Comment by LongDirtyAnimAlf** [comment]
You need to patch FPC to get things running on FreeBSD.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/patches_v1.0/fpcpatch_dragonfly_fixes_3_2_1.patch
Just download this patch and add it into FPC patches in Setup+

**Comment by Alexey-T** [comment]
Thanks, will test
