### ISSUE TITLE
Question: freebsd patch

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#314]
#311 - you gave the patch. It helped on freebsd 12. If I appliy the patch on my Linux PC (fpc 3.2fixes) and cross compile there to Freebsd - binary will work on Freebsd v12 and v11?

**Comment by LongDirtyAnimAlf** [comment]
Cross-compiling should work without this patch. AFAIK, the fpcup-bin-tools for Linux have already ld.bfd as linker.
And should work on FreeBSD11 and FreeBSD12 due to linking with libc and not using system calls.

**Comment by Alexey-T** [comment]
Ok. Checked it now- before this pch, binary crashes, with pch it works
