### ISSUE TITLE
Cross compile to Linux x86_64 from Win64

### ISSUE THREAD

**Issue by lgadina** [LongDirtyAnimAlf/fpcupdeluxe#317]
Hi, i have a problem with cross compile to linux x86_64 from Win64

> echo '47400' > revision.inc
> 
> C:/Work/ProS/fpcdeluxe/fpc/bin/x86_64-win64/fpc.exe -Ur -Xs -O2 -n -Fux86_64 -Fusystems -FuC:/Work/ProS/fpcdeluxe/fpcsrc/rtl/units/x86_64-win64 -Fix86_64 -FEx86_64/bin/x86_64-win64 -FUx86_64/units/x86_64-win64 -dRELEASE -vw-n-h-l-d-u-t-p-c- -dFPC_SOFT_FPUX80   -dREVINC -dx86_64 -dGDB -dBROWSERLOG -Fux86 -Fix86 version.pas
> version.pas(103,8) Error: Operator is not overloaded: "ShortString" + "Word"
> version.pas(109) Fatal: There were 1 errors compiling module, stopping
> Fatal: Compilation aborted
> Error: C:\Work\ProS\fpcdeluxe\fpc\bin\x86_64-win64\ppcx64.exe returned an error exitcode
> make.exe[2]: *** [ppc.exe] Error 1
> make.exe[2]: Leaving directory `C:/Work/ProS/fpcdeluxe/fpcsrc/compiler'
> make.exe[1]: *** [cycle] Error 2
> make.exe[1]: Leaving directory `C:/Work/ProS/fpcdeluxe/fpcsrc/compiler'
> C:\Work\ProS\fpcdeluxe\fpcbootstrap\make.exe: *** [compiler_cycle] Error 2
> C:\Work\ProS\fpcdeluxe\fpcbootstrap\make.exe: Leaving directory `C:/Work/ProS/fpcdeluxe/fpcsrc'
> fpcupdeluxe: ERROR: FPCCrossInstaller (BuildModuleCustom: FPC): Running cross compiler fpc C:\Work\ProS\fpcdeluxe\fpcbootstrap\make.exe for x86_64-linux failed with an error code.
> 
> 
> ERROR: Fpcupdeluxe fatal error !
> Sequencer (FPCCleanBuildOnly): Failure running fpcupdeluxe: error executing sequence FPCCleanBuildOnly
> Sequencer (Only): Failure running fpcupdeluxe: error executing sequence Only
> Building cross-tools failed. Aborting.
> 

I modified makefile, and now the another error

> echo "'47400'" > revision.inc
> C:/Work/ProS/fpcdeluxe/fpc/bin/x86_64-win64/fpc.exe -Ur -Xs -O2 -n -Fux86_64 -Fusystems -FuC:/Work/ProS/fpcdeluxe/fpcsrc/rtl/units/x86_64-win64 -Fix86_64 -FEx86_64/bin/x86_64-win64 -FUx86_64/units/x86_64-win64 -dRELEASE -vw-n-h-l-d-u-t-p-c- -dFPC_SOFT_FPUX80   -dREVINC -dx86_64 -dGDB -dBROWSERLOG -Fux86 -Fix86 version.pas
> C:/Work/ProS/fpcdeluxe/fpc/bin/x86_64-win64/fpc.exe -Ur -Xs -O2 -n -Fux86_64 -Fusystems -FuC:/Work/ProS/fpcdeluxe/fpcsrc/rtl/units/x86_64-win64 -Fix86_64 -FEx86_64/bin/x86_64-win64 -FUx86_64/units/x86_64-win64 -dRELEASE -vw-n-h-l-d-u-t-p-c- -dFPC_SOFT_FPUX80   -dREVINC -dx86_64 -dGDB -dBROWSERLOG -Fux86 -Fix86 pp.pas
> C:/Users/aevdokimov/AppData/Local/Programs/Git/usr/bin/mv.exe -f x86_64/bin/x86_64-win64/pp.exe ppc.exe
> make.exe[2]: Leaving directory `C:/Work/ProS/fpcdeluxe/fpcsrc/compiler'
> C:/Work/ProS/fpcdeluxe/fpcbootstrap/make.exe 'FPC=/c/Work/ProS/fpcdeluxe/fpcsrc/compiler/ppc.exe' OS_TARGET=win64 CROSSBINDIR= BINUTILSPREFIX= CROSSCYCLEBOOTSTRAP=1 CYCLELEVEL=2 rtlclean
> make.exe[2]: Entering directory `C:/Work/ProS/fpcdeluxe/fpcsrc/compiler'
> make.exe[2]: Leaving directory `C:/Work/ProS/fpcdeluxe/fpcsrc/compiler'
> makefile:135: *** Compiler /c/Work/ProS/fpcdeluxe/fpcsrc/compiler/ppc.exe not found.  Stop.
> make.exe[1]: *** [cycle] Error 2
> make.exe[1]: Leaving directory `C:/Work/ProS/fpcdeluxe/fpcsrc/compiler'
> C:\Work\ProS\fpcdeluxe\fpcbootstrap\make.exe: *** [compiler_cycle] Error 2
> C:\Work\ProS\fpcdeluxe\fpcbootstrap\make.exe: Leaving directory `C:/Work/ProS/fpcdeluxe/fpcsrc'
> fpcupdeluxe: ERROR: FPCCrossInstaller (BuildModuleCustom: FPC): Running cross compiler fpc C:\Work\ProS\fpcdeluxe\fpcbootstrap\make.exe for x86_64-linux failed with an error code.
> 
> 
> ERROR: Fpcupdeluxe fatal error !
> Sequencer (FPCCleanBuildOnly): Failure running fpcupdeluxe: error executing sequence FPCCleanBuildOnly
> Sequencer (Only): Failure running fpcupdeluxe: error executing sequence Only
> Building cross-tools failed. Aborting.

the same behavior occurs when cross compiling from Win64 to aarch64.
Can you give me a suggest?

**Comment by LongDirtyAnimAlf** [comment]
Please test:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2f

**Comment by LongDirtyAnimAlf** [comment]
Closing due to no feedback.
Please re-open when needed.
Please leave closed when solved.
