### ISSUE TITLE
Package TurboPowerIProDsgn?

### ISSUE THREAD

**Issue by fliegermichl** [LongDirtyAnimAlf/fpcupdeluxe#318]
Hi,
if i install an Lazarus Release this package ist installed automatically. if i use fpcupdeluxe it isn't. This has as an effect that hintwindows in the sourceeditor are not correctly formatted. (html tags are simply removed)

**Comment by LongDirtyAnimAlf** [comment]
That is on purpose.
Fpcupdeluxe must work on many many systems. Not all standard packages are working that well on all of these systems. That is why a basic Lazarus is installed. Its up to the user to add the packages that the user needs after this basic install.

**Comment by fliegermichl** [comment]
thank you for reply,
ok, this reason is acceptable for me
