### ISSUE TITLE
macOS - Big Sur - pp.pas(280,36) Error: Error while linking (with fix)

### ISSUE THREAD

**Issue by Hansaplast** [LongDirtyAnimAlf/fpcupdeluxe#319]
On macOS Big Sur I get the error:

```
An error occurred while linking
pp.pas(280,36) Error: Error while linking
pp.pas(280,36) Fatal: There were 1 errors compiling module, stopping
```

Based on a message in fpc-devel mailing list ([link](https://www.mail-archive.com/fpc-devel@lists.freepascal.org/msg40256.html)) I found this option to be working when added as an **FPC option** under "**Setup+**". 

`-XR/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
`

I honestly do not know if there will be implications for older macOS version, just thought I'd mention it here as it may be helpful for other. Maybe an option to add this to the predefined options, or maybe this works for all macOS versions?

**Comment by Hansaplast** [comment]
Woops funny typo in the title 😜

**Comment by Hansaplast** [comment]
Note: all this assuming that the XCode command line tools are installed of course.

**Comment by LongDirtyAnimAlf** [comment]
A couple of days ago, a fix was included into fpcupdeluxe.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/5bd21a3be9c3b96635c39556572179d9b0228197
Will be available in next release (soon).
Thanks.

**Comment by Hansaplast** [comment]
No hurry - we have a workaround for now 😊 
Thanks though, your hard work is much appreciated!
