### ISSUE TITLE
macOS - Missing trunk version info?

### ISSUE THREAD

**Issue by Hansaplast** [LongDirtyAnimAlf/fpcupdeluxe#320]
I rebuild FPC and Lazarus from Trunk a few times (under macOS Big Sur 11.0.1), but no matter what I try; I no longer see the version information in the about dialog. Not sure if this is a Lazarus problem or  an FPCUpDeluxe bug?

The copy button in the About dialog results in just this (note that it does display the "r", but no revision number):
`Lazarus 2.1.0 r FPC 3.3.1 x86_64-darwin-cocoa`

Where this used to be something like this (copied from elsewhere, so the version info is not relevant for the build I just did):
`Lazarus 2.0.11 r64142M FPC 3.2.0 x86_64-darwin-cocoa`

Screenshot: the About dialog after compiling FPC and Lazarus both from Trunk.

Previously there used to be SVN version info.

If this is Lazarus related, then please let me know so I can open a bug in BugTracker. 😊 

![screenshot-lazarus-about](https://user-images.githubusercontent.com/2313949/99879353-d6ce3500-2c0c-11eb-9071-904499f02fb0.png)

**Comment by LongDirtyAnimAlf** [comment]
Works for me using the latest release.

![macrevision](https://user-images.githubusercontent.com/10783972/100144566-3f304700-2e97-11eb-9996-0d5b4e0f404c.JPG)

**Comment by Hansaplast** [comment]
Strange, I just updated to the latest release and it still is not showing the revision info 😞 
Any idea what may causing this?

Note: to make sure it wasn't a "left over", I completely removed FPCUpDeluxe (deleted the entire dir) and downloaded and installed it again. However, now I cannot build anything (stable or trunk) - any suggestions what I may be mssing?:

```
Going to install both FPC trunk and Lazarus trunk.
FPCUP(deluxe) is starting up.

FPCupdeluxe basedir:       /Users/hans/fpcupdeluxe/fpcupdeluxe
Bootstrap dir:             /Users/hans/fpcupdeluxe/fpcupdeluxe/fpcbootstrap

FPC URL:                   https://svn.freepascal.org/svn/fpc/trunk
FPC source directory:      /Users/hans/fpcupdeluxe/fpcupdeluxe/fpcsrc
FPC install directory:     /Users/hans/fpcupdeluxe/fpcupdeluxe/fpc
FPC options:               

Lazarus URL:               https://svn.freepascal.org/svn/lazarus/trunk
Lazarus source directory:  /Users/hans/fpcupdeluxe/fpcupdeluxe/lazarus
Lazarus install directory: /Users/hans/fpcupdeluxe/fpcupdeluxe/lazarus
Lazarus options:           

Please stand back and enjoy !

24-11-20 23:21:49: fpcupdeluxe: V314 (20201115) started.
FPCUPdeluxe V1.8.2e for x86_64-darwin running on macOS 11.0.1

Checking dev-libs for: cocoa
fpcupdeluxe: info: FPCNativeInstaller (CleanModule: FPC): No FPC source directory (/Users/hans/fpcupdeluxe/fpcupdeluxe/fpcsrc) found [yet] ... nothing to be done
Found valid bsdtar application.
Found valid make application.
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): Start checkout/update of FPC sources.
fpcupdeluxe: WARNING: FPCNativeInstaller (DownloadFromSVN: FPC): svn is needed, but cannot be found on the system !!
fpcupdeluxe: ERROR: Tried to get FPC version from version.pas, but no version.pas found
fpcupdeluxe: ERROR: Tried to get FPC version from Makefile.fpc, but no Makefile.fpc found
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC is at revision: 
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): No updates for FPC found.
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): No FPC patches defined.
fpcupdeluxe: info: FPCNativeInstaller (BuildModule: FPC): Building module FPC...
fpcupdeluxe: ERROR: FPCNativeInstaller (BuildModule: FPC): /Users/hans/fpcupdeluxe/fpcupdeluxe/fpcsrc/Makefile not found. Severe error. Should not happen. Aborting.

ERROR: Fpcupdeluxe fatal error !
Sequencer (FPC): Failure running fpcupdeluxe: error executing sequence FPC
Sequencer (Default): Failure running fpcupdeluxe: error executing sequence Default
```

**Comment by LongDirtyAnimAlf** [comment]
Official FPC sources are made available through svn. As you can see in the above message.
FPC URL:                   https://svn.freepascal.org/svn/fpc/trunk
Your Mac does not have SVN anymore. It does have GIT however.
Therefor, you need to choose the GIT sources.
GIT sources do not have revision-numbers like SVN does. So, fpcupdeluxe tries to get the revision from these GIT sources.
On my Mac (10.15), this works.

**Comment by Hansaplast** [comment]
I did not think of that - doh! That makes totally sense.
My apologies for not seeing that 😞 

Note: 
svn still exists (/Library/Developer/CommandLineTools/usr/bin/svn) for those that upgraded macOS and XCode ([source](https://developer.apple.com/forums/thread/666689)). However, it is no longer in the environment search path (I assume).
I presume new installs will not have it so this will not be a permanent fix. 

Making an alias (not sure why the developer that suggested this didn't add it to the environment path):
`alias svn=/Library/Developer/CommandLineTools/usr/bin/svn`

Made it work for now. For M1 users and for future installations this will most likely fail of course.

Note with this change (running FPCUpDeluxe 1.8.2e), I still have to add this FPC option in "Setup+":

`-XR/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk`

**Comment by LongDirtyAnimAlf** [comment]
Thanks for the update.
Did you finally install using SVN or GIT ?
That is important for me to resolve the version issue.

**Comment by Hansaplast** [comment]
Apologies for the limited info.

I first try to use the svn that was still on my system. 
To get the path (/Library/Developer/CommandLineTools/usr/bin/) added to the environment I added it to "/private/etc/paths" (this way it appears in env when starting a zsh shell). 
Even though every zsh that I open (default under macOS), can find svn, FPCUpDeluxe keeps giving a warning that svn cannot be found. So I removed that change again.

Next I followed your advice and installed svn with brew. However this resulted in the same error (FPCUpDeluxe cannot find svn on the system). So I removed brew again.

Next I linked the existing svn:

`ln -s /Library/Developer/CommandLineTools/usr/bin/svn /usr/local/bin/svn`

Again, FPCUpDeluxe reports that it cannot find svn, even though any terminal window I open, right away works with svn (I thired "sh" and "zsh" - they both work).

So ... now I'm wondering why it cannot find svn?

**Comment by Hansaplast** [comment]
Note:
Next thing I tried: I copied "svn" to /usr/local/bin (instead of having it linked), and it still produces the same error in FPCUpDeluxe. Testing with "which svn" (in Terminal) returns correctly /usr/local/bin/svn.

(I briefly skimmed through the FPCUpDeluxe code and it tests if svn exists, if not, then it uses which() to determine the location of svn?)

**Comment by LongDirtyAnimAlf** [comment]
Fpcupdeluxe tries to isolate itself for as much as possible to prevent spoiling other installs of FPC and Lazarus.
That is why the PATH is not used. And it also does not look in /local.
Also, fpcupdeluxe should not depend on SVN if its not there.
So, why not use GIT.
FPC itself wil switch towards GIT with the next release !

**Comment by LongDirtyAnimAlf** [comment]
I will add:
/Library/Developer/CommandLineTools/usr/bin/svn
as a standard searchpath for SVN on Darwin, so it will be found.
Next release.

**Comment by Hansaplast** [comment]
Where does FPCUpDeluxe look for svn?

Not something I expect you to solve; but for me the revision numbers are important for when I report a bug.
And as I understand from you, right now Git is being used on my system and that's why I do not see revision numbers.

**Comment by LongDirtyAnimAlf** [comment]
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2f
