### ISSUE TITLE
cross compilation error for Arm: cannot find -lrt

### ISSUE THREAD

**Issue by KeesBleijenberg** [LongDirtyAnimAlf/fpcupdeluxe#321]
I try to use Indy 10 on Lazarus. I use fpcdeluxe to setup a cross compile environment. Until now everything went fine and I could compile and link serveral cross platform projects for ArmV7, Windows and Linux 64 bits. 
But the mini project below does not work:
program exportSmData;
{$mode objfpc}{$H+}
uses
  {$IFDEF UNIX}
  cthreads,
  {$ENDIF}
  Classes, SysUtils, idException, idHttp;
var cc: TidHttp;
begin
     cc:=TIdHttp.create(nil);
     cc.free;
end.

This compiles and links fine for targets Windows and Linux 64 bits. When I target Linux on Armv7 (for a Raspberry Pi) I get a link error:
....\cross\bin\arm-linux\arm-linux-gnueabihf-ld.exe: cannot find -lrt. 
A missing library? I did not install Indy on lazarus but use the units directly (to avoid package problems). I wonder if this is a Indy problem. I don't understand the error message and wonder what to do. 

Greetings,
Kees

**Comment by LongDirtyAnimAlf** [comment]
Inside the cross lib directory , there are the libraries needed for cross-compiling.
The PI-libs are located at "cross\lib\arm-linux"
Look inside for a file named librt.so.1
Copy (duplicate) this file to librt.so
And compile again.

**Comment by KeesBleijenberg** [comment]
Thank you LongDirtyAnimAlf. It worked.
I don't understand why. Can you explain or point me to a explanation?

**Comment by LongDirtyAnimAlf** [comment]
Well.
Cross-linking is always a a bit tricky. On Linux, there are always symlinks available for all versions. Sometimes Lazarus links against a .so file. Sometimes against a .so.1 file. Sometimes against a .so.6.6 So, when crossing, many versions are needed. Thats it.
