### ISSUE TITLE
Error using svn client from msys64

### ISSUE THREAD

**Issue by bleuge** [LongDirtyAnimAlf/fpcupdeluxe#322]
I guess fpcupdeluxe is very clever and detected the svn client in my msys64 installation. 
But there is something wrong while using it.
I am on W10LTC x64, msys64 is installed in c:\msys64\.
I copied fpcupdeluxe in c:\fpc\fpcupdlx and ran it.
Selected trunk, trunk and install, svn client produced an error creating this folder: 
c:/fpc/fpcupdlx/c:\fpc\fpcsrc 

Something related to / \ folder and how it uses it. 

I resolved it, deleting the svn client from msys64 (renamed it) and let fpcupdeluxe use its own one. 
I

**Comment by LongDirtyAnimAlf** [comment]
> I guess fpcupdeluxe is very clever and detected the svn client in my msys64 installation.

Yes. I does try to detect SVN if its already there.
However, this should not happen.
Will look into.

**Comment by LongDirtyAnimAlf** [comment]
Latest release should solve.

https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2f

**Comment by LongDirtyAnimAlf** [comment]
Closing due to no feedback.
Please re-open when needed.
Please leave closed when solved.
