### ISSUE TITLE
acces violation cross compiling Indy 10 for arm 

### ISSUE THREAD

**Issue by KeesBleijenberg** [LongDirtyAnimAlf/fpcupdeluxe#323]
The mini project below

program testProject;
uses IdGlobal;
begin
  writeln('Blah');
end.

compiles and links fine for targets Windows, Linux 64 bits and Linux on ArmV7. 
The executable runs fine on Win64 and Linux Ubuntu. But on the Raspberry Pi I get:
An unhandled exception occurred at $00010D40:
EAccessViolation: Access violation
  $00010D40
Running with sudo does not help.

If I remove the line: uses IdGlobal, the executable runs without problems on the Raspberry Pi.

If I only add IdGlobal in the project inspector in Lazarus and remove the line 'uses IdGlobal', the executable runs without problems on the Raspberry Pi. 

I did not install Indy 10 in Lazarus. I use the units directly.

I wonder is this a problem with the compiler, fpcUpdeluxe or Indy 10. 
Is it possible to run Indy 10 on a Raspberry PI?

Greetings,
Kees

**Comment by LongDirtyAnimAlf** [comment]
On my Pi, a program with Indy runs flawless.
You might do ldd yourexe (see screenshot) to see what libs are required.
![armindy](https://user-images.githubusercontent.com/10783972/100524341-a7449d00-31b7-11eb-884b-8270b8a80c84.JPG)

**Comment by KeesBleijenberg** [comment]
I did ldd -v .testproject and got:

	/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so => /usr/lib/arm-linux-gnueabihf/libarmmem-v6l.so (0xb6f35000)
	librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0xb6f1e000)
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xb6f0b000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6dbd000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb6d93000)
	/lib/ld-linux-armhf.so.3 (0xb6f48000)

	Version information:
	./testProject:
		libdl.so.2 (GLIBC_2.4) => /lib/arm-linux-gnueabihf/libdl.so.2
		librt.so.1 (GLIBC_2.4) => /lib/arm-linux-gnueabihf/librt.so.1
		libc.so.6 (GLIBC_2.4) => /lib/arm-linux-gnueabihf/libc.so.6
	/usr/lib/arm-linux-gnueabihf/libarmmem-v6l.so:
		libc.so.6 (GLIBC_2.4) => /lib/arm-linux-gnueabihf/libc.so.6
	/lib/arm-linux-gnueabihf/librt.so.1:
		ld-linux-armhf.so.3 (GLIBC_PRIVATE) => /lib/ld-linux-armhf.so.3
		ld-linux-armhf.so.3 (GLIBC_2.4) => /lib/ld-linux-armhf.so.3
		libc.so.6 (GLIBC_2.28) => /lib/arm-linux-gnueabihf/libc.so.6
		libc.so.6 (GLIBC_PRIVATE) => /lib/arm-linux-gnueabihf/libc.so.6
		libc.so.6 (GLIBC_2.4) => /lib/arm-linux-gnueabihf/libc.so.6
		libpthread.so.0 (GLIBC_PRIVATE) => /lib/arm-linux-gnueabihf/libpthread.so.0
		libpthread.so.0 (GLIBC_2.4) => /lib/arm-linux-gnueabihf/libpthread.so.0
	/lib/arm-linux-gnueabihf/libdl.so.2:
		ld-linux-armhf.so.3 (GLIBC_PRIVATE) => /lib/ld-linux-armhf.so.3
		ld-linux-armhf.so.3 (GLIBC_2.4) => /lib/ld-linux-armhf.so.3
		libc.so.6 (GLIBC_PRIVATE) => /lib/arm-linux-gnueabihf/libc.so.6
		libc.so.6 (GLIBC_2.4) => /lib/arm-linux-gnueabihf/libc.so.6
	/lib/arm-linux-gnueabihf/libc.so.6:
		ld-linux-armhf.so.3 (GLIBC_2.4) => /lib/ld-linux-armhf.so.3
		ld-linux-armhf.so.3 (GLIBC_PRIVATE) => /lib/ld-linux-armhf.so.3
	/lib/arm-linux-gnueabihf/libpthread.so.0:
		ld-linux-armhf.so.3 (GLIBC_PRIVATE) => /lib/ld-linux-armhf.so.3
		ld-linux-armhf.so.3 (GLIBC_2.4) => /lib/ld-linux-armhf.so.3
		libc.so.6 (GLIBC_PRIVATE) => /lib/arm-linux-gnueabihf/libc.so.6
		libc.so.6 (GLIBC_2.4) => /lib/arm-linux-gnueabihf/libc.so.6

Seems okay to me. I checked and I could find all libs. 
I don't understand why the program runs fine on your Pi. Maybe because I'am running Diet Pi. I'll try to compile the program on the pi and insert some diagnostic writelln's in the startup code of some units. I'am running out of options here.
