### ISSUE TITLE
Compilation problem adding package IndyLaz to project 

### ISSUE THREAD

**Issue by KeesBleijenberg** [LongDirtyAnimAlf/fpcupdeluxe#324]
I've installed Indy in Lazarus without problems.
The command line project targets Unix on Arm. 
If I add requirement package IndyLaz, lazarus starts compiling and I get the error:
IdDsnPropEdBindingVCL.pas(80,3) Fatal: Cannot find IdSocketHandle used by IdDsnPropEdBindingVCL, incompatible ppu=C:\fpcupdeluxe\fpcupdeluxe\ccr\indy\Lib\lib\arm-linux\IdSocketHandle.ppu, package indylaz

Is this a Indy problem or a fpcUpdeluxe problem and how do I fix this?

Kees

**Comment by LongDirtyAnimAlf** [comment]
IdDsnPropEdBindingVCL
As far as I know, this will never compile on anything other than Windows. It has VCL in its name. And that needs Windows.
Did you set GTK2 as your project widget target in Lazarus ?

**Comment by LongDirtyAnimAlf** [comment]
My comment above was plain wrong.
But.
Is this problem still present ?

**Comment by LongDirtyAnimAlf** [comment]
On my Pi, Indy compiles without problem !

![indy-pi-01](https://user-images.githubusercontent.com/10783972/101885811-e9e47d00-3b9a-11eb-9f83-598fe355da82.JPG)

**Comment by KeesBleijenberg** [comment]
This has probably something to do with my very old headless PI with dietPi on it.  I wonder why the program compiles and links, but does not run. 
Which version of the PI and what OS do you use?

**Comment by LongDirtyAnimAlf** [comment]
I am also running headless. Arch Linux for armv7l. Version 5.4.72.
I always run arch-linux. Headless. Without windows manager. Managed through ssh. Sometimes with LXDE as GUI. Combined with VNC for headless GUI.

**Comment by KeesBleijenberg** [comment]
I installed fp and fpc on the Pi and compiled the project. I had to add the path to the runtime libs (for syncobjs.pas... ) and the Indy libs. The generated executable runs fine on the pi.

Cross compiling of the same code in Lazarus and then copying the executable to the pi, does not work. So probably something goes wrong in Lazarus?? Not what I expected. 
How to investigate this?

**Comment by LongDirtyAnimAlf** [comment]
I just cross-compiled the app and it runs without problems !
In fact, all my cross-Pi-apps run fine on any of my Pi's.

Send your binary to me (as a zip) attached to a message.

**Comment by KeesBleijenberg** [comment]
This is what I've done:
Download the latest lazarus and fpc with fpcUpdeluxe for Arm-Linux, Windows x86_64 and Linux x86_64. Removed Indy 10. 
Created the project and cleaned all directories. 
Copied the Indy source that worked in FP on the Pi to <projectDir>\indy
Compiled: Error -> something about idVCLstream.
Added to 'other unit files' indy\lib\system
Compile -> No errors, just warnings. New executable is created
The executable does not run on the pi. 
[exportSmData.zip](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/5682824/exportSmData.zip)

**Comment by LongDirtyAnimAlf** [comment]
No problemo.

![pi01](https://user-images.githubusercontent.com/10783972/101981779-909a4d80-3c6f-11eb-8925-500ab83ece67.JPG)

**Comment by KeesBleijenberg** [comment]
Thank you for your help!

So the executable runs on your pi, but not on mine. 
I tried to compile with arm version v6 (My old pi uses v6 and not v7). That didn't help.
I saw you installed LXDE. I installed that program which installs X Window. No luck.

I'am stuck. What can I try?

**Comment by LongDirtyAnimAlf** [comment]
You can send me the binary that runs on your system. I will have a look at it.

**Comment by KeesBleijenberg** [comment]
In the zip is the binary that does not run on my pi
[exportSmData_v6.zip](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/5683372/exportSmData_v6.zip)

The project exportSmData:
[exportSmData_src.zip](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/5683378/exportSmData_src.zip)

The error is: 
An unhandled exception occurred at $00010B00:
EAccessViolation: Access violation
  $00010B00

**Comment by KeesBleijenberg** [comment]
I've put writeln('xxx'); as first line in the initialization of idGlobals. This line should be executed as one of the first lines. But I don't see 'xxx' if I execute the compiled file. I only get the unhandled exception. 
I also wonder why this same code  runs fine when compiled with fp and fpc on the  pi.

**Comment by LongDirtyAnimAlf** [comment]
> You can send me the binary that runs on your system. I will have a look at it.

I need the one that runs on your system !

**Comment by KeesBleijenberg** [comment]
Huh... Which binary do you mean.?The binary that runs on Windows (my OS)? My English is not so good...
This is the executable for win64:
[exportSmData_win.zip](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/5684383/exportSmData_win.zip)

**Comment by LongDirtyAnimAlf** [comment]
Nee.
Ik wil graag the binary die op het Raspberry systeem gewoon werkt. Dus degene die op het systeem zelf gecompileerd is en daar ook werkt. Dan kan ik in de werkende binary kijken of ik iets kan ontdekken !

**Comment by KeesBleijenberg** [comment]
Ah... dutch. 
[exportSmData_FP.zip](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/5684434/exportSmData_FP.zip)

**Comment by LongDirtyAnimAlf** [comment]
I see many differences between binaries that you send to me !
I have included screenshot so you can see for yourself.
If you want a good answer, you need to provide me with the right data.
So.
1: make a very simple project that demonstrates your problem.
2: compile this project on your Pi to get a working version.
3: cross-compile this project to get a non-working version.
4: send me the 2 binaries and the project source (the lpi+lpr+lps+units)

![102009348-2e0c8480-3d37-11eb-86e5-2af601059e4c](https://user-images.githubusercontent.com/10783972/102019660-06d4a800-3d75-11eb-99a2-40306cedbe69.jpeg)

**Comment by KeesBleijenberg** [comment]
[exportSmData.zip](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/5688668/exportSmData.zip)
This what I've done:

Create in Lazarus a simple project exportSmData on my Windows machine in the map d:\exportSmData
targetOs = Linux 
targetCpuFamilie = Arm
targetProcessor = ArmV6

code:
program exportSmData;
uses IdGlobal;
begin
   writeln('start');
end.

create a subdir \exportSmData\indy
copy all *.pas and all *.inc preserving directory structure (in the zip in the map indy)

Add the map indy\system in program options 'Other unit files' 
Build -> copy exportSmData to the pi -> run on the pi -> Access Violation 

Create a map /home/kees/SlimmeMeter/exportSmData on the pi.
Copy the map indy and its contents in this map
Create a map fpc-base in this map and put the files syncobjs.pp (and rename to syncobjs.pas) and iconvenc.pas in this map.

Start fp 
add in options, directories 
/usr/lib/arm-linux-gnueabihf/fpc/3.0.4/units/arm-linux/rtl                                                                             /usr/lib/arm-linux-gnueabihf/fpc/3.0.4/units/arm-linux/rtl-extra     
/usr/lib/arm-linux-gnueabihf/fpc/3.0.4/units/arm-linux/rtl-objpas
/home/kees/SlimmeMeter/exportSmData/indy/Lib/System
/home/kees/SlimmeMeter/exportSmData/fpc-base
set compiler target to armv6
Build the project 
Run ./exportSmData. Output: 'indy_start' and next line 'start'.
The text 'indy_start' is from the code I put in the initialization of IdGlobal.pas.

The binaries are in the zip (crossCompiling\bin\exportSmData and onPi\bin\exportSmData
I cannot explain the difference in size of the executables.

I've installed fpc on the pi without fpcUpDeluxe. I don't know how exactly.

Thanks for your help.
Kees

**Comment by LongDirtyAnimAlf** [comment]
As a starter. The project you gave me did not compile out-of-the-box. Meaning: its not the project that you are using when cross-compiling. As this is a problem that needs to be solved in the details, this is a bad start.
Again, I ask you. If you want valuable help, please give me data that is similar to your setup.
You give me a zip. I unpack. Open the cross-project. Does not compile. Have to change the paths. Compiles with a binary in a different location as yours.
All of the above makes this hard to solve !

Result:
Below is a screenshot of the readelf archive summary of three exe's.
Left: your cross-compiled exe.
Middle: your native exe.
Right: my cross-compiled exe.
As you can see: your cross-exe is for ARMV7 + VFPV3 + Thumb 2
As you can see: other exe are for ARMV6 + VFPV2 + Thumb 1

There you are.

![pi03](https://user-images.githubusercontent.com/10783972/102113133-f38b1080-3e38-11eb-98c2-17c0434ac3b6.JPG)

**Comment by KeesBleijenberg** [comment]
I don't understand. I've unzipped the send zip on my computer. Unzipped the indy and fpc-base map and opened the exportSmData.lpi in lazarus. In the menu project, project-options, config and target, the options target-processor (-Cp) says ARMV6 and not armv7.
On the pi in fp I go to menu, Options, Compiler, tab Processor, both Optimizing target processor and Code generation target processor says ARMV6. What is wrong?

**Comment by KeesBleijenberg** [comment]
I deleted the executable and in project, project options I chose config and target. 
Then I set Target OS to Linux, Target CPU family to arm and Target processor to ArmV6 (see config_target.png).
I build the project, copied the executable to the pi and did:

root@DietPi:/home/kees/SlimmeMeter/exportSmData# readelf -h -A ./exportSmData
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           ARM
  Version:                           0x1
  Entry point address:               0x10570
  Start of program headers:          52 (bytes into file)
  Start of section headers:          2384344 (bytes into file)
  Flags:                             0x5000400, Version5 EABI, hard-float ABI
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         7
  Size of section headers:           40 (bytes)
  Number of section headers:         34
  Section header string table index: 31
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_enum_size: int
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
root@DietPi:/home/kees/SlimmeMeter/exportSmData#

So the executable is for v7 (Tag_CPU_arch: v7) and not v6? If so, is this a Lazarus bug of fpc bug? Or do I misunderstand something?
If I compile with FP on the pi the executable is indeed for v6.
This would also explain why the executable does run on your pi and not on mine. My pi is and old version that needs v6 while  your pi works fine with v7.

![config_target](https://user-images.githubusercontent.com/11313453/102194898-24f9ef80-3ebe-11eb-97cc-aead0f1d3f01.png)

**Comment by LongDirtyAnimAlf** [comment]
Lets start new. And please follow my instructions closely. We have to tune our setups. Make them similar.
1:
Use fpcupdeluxe for a new install of FPC stable and Lazarus trunk. In some new directory. Do this with a copy of fpcupdeluxe inside this directory. I normally out fpcup inside a directory named up as a subdirectory of the install directory.
2:
Use fpcupdeluxe to build cross for arm linux.
3:
Cross-compile a hello world for arm.
4:
Look at it with readelf and show the results.

**Comment by KeesBleijenberg** [comment]
I'am not sure if my procedure creates exactly the same lazarus installation. Therefore I'll write down exactly what I did:

create a new directory c:\fpcupdeluxe
create a new directory c:\fpcupdeluxe\up
download fpcupdeluxe-x86_64-win64.exe from https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases and save it in c:\fpcupdeluxe\up
In fpcupdeluxe I chose fpc stable and lazarus trunk (I was using trunk/trunk)
I set the install path to c:\fpcupdeluxe
click on Install/update FPC + Laz
No problems.
click on tab cross
select cpu = arm and OS = linux, click install compiler
I let fpcupdeluxe download and install crosstools
Fpcupdeluxe ended without errors

Start Lazarus
Menu -> File -> new -> Simple Program.
Typed in this code:

program HelloWorld;
begin
  writeln('Hello World');
end.

Save as HelloWorld.lpr
Menu->Project-> Project Options -> Config and Target  (the default settings are not okay so...)
	Target OS = Linux
	Target CPU-family = arm
	Target processor = ARMV6
	
Menu -> Run -> Build
No errors. There is a file c:\fpcupdeluxe\projects\HelloWorld. 
Copied the file to the pi

On the pi readelf -h -A ./HelloWorld
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           ARM
  Version:                           0x1
  Entry point address:               0x100ec
  Start of program headers:          52 (bytes into file)
  Start of section headers:          428124 (bytes into file)
  Flags:                             0x5000200, Version5 EABI, soft-float ABI
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         4
  Size of section headers:           40 (bytes)
  Number of section headers:         14
  Section header string table index: 11
Attribute Section: aeabi
File Attributes
  Tag_CPU_arch: v4T
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-1

I hope this is good enough. I wonder if this armV4? Why 4?

**Comment by LongDirtyAnimAlf** [comment]
This is good. Thanks for the details info. You did everything 100% ok !
Conclusions.
1:
You have used the win64 version of fpcupdeluxe. While this is good for building a win64 version of Lazarus and win64 apps, its not good for cross-compiling. Win64 has some very particular floating point issues, causing problems when crossing towards other systems, especially 32 bit. So, it is not recomended, also not by the FPC devs. !
Install the win32 version of all:
Please delete all directories except Lazarus, fpcsrc and up. Delete fpcupdeluxe binary and the two dll's.
Get a win32 version of fpcupdeluxe, put it in the up directory, have FPC and Lazarus installed again and also the cross-compiler. Make and run and analyze the hello-world-app again.
2:
The ARMV4 binary is also for me a big unknown. Perhaps related to the win64 base. I will look into it.

**Comment by KeesBleijenberg** [comment]
I've done the same thing but now with the win32 installer for fpcupdeluxe
the readelf output:
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           ARM
  Version:                           0x1
  Entry point address:               0x100ec
  Start of program headers:          52 (bytes into file)
  Start of section headers:          428124 (bytes into file)
  Flags:                             0x5000200, Version5 EABI, soft-float ABI
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         4
  Size of section headers:           40 (bytes)
  Number of section headers:         14
  Section header string table index: 11
Attribute Section: aeabi
File Attributes
  Tag_CPU_arch: v4T
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-1

Still armv4.
Probably this is a Lazarus/fpcupdeluxe issue and not a fpc issue, because fp does the right thing.

It's sad to hear that you can't cross compile from win64. My final goal (this pi experiment is just a test) is to convert a Delphi 5 project (or at least the non ui parts) to Win64, mac Os and Linux.

**Comment by LongDirtyAnimAlf** [comment]
You can now cross towards win64 !
Just choose win64 and x86_64.
Make a gui with a button and cross towards armv6 and test run it on Pi.

**Comment by KeesBleijenberg** [comment]
Okay. So I can cross compile with the win32 version of Lazarus to the pi and win64.
Your second suggestion, a UI with a button running on the PI,  doesn't work (as expected). I get a unhandled exception.
First I want to investigate cross compiling of the Indy program to pi (console app). It doen't look.

**Comment by KeesBleijenberg** [comment]
I tried to cross compile for the pi the 'hello world' application with the win32 version of Lazarus. I added the line uses IdGlobal. I copied the executable to the pi. readelf now says that the arm version is armV6. That is good. 
But I still get a unhandled exception. This does not look good.

**Comment by LongDirtyAnimAlf** [comment]
This is getting more interesting by the minute !
Lets give it another try. See included screenshot of the Setup+ screen. We are going to override the default cross-compiler settings for arm-linux.
After adding the changes as per screenshot, please rebuild the arm-linux cross-compiler.
After success, please rebuild your apps and try to run them.
Fingers crossed.

![pi04](https://user-images.githubusercontent.com/10783972/102455110-50f0ae80-403f-11eb-8b2b-161c25bded20.JPG)

**Comment by KeesBleijenberg** [comment]
I've changed the settings in the cross compile settings and rebuild in fpcupdeluxe -> no problems.

HelloWorld app without uses IdGlobal and reference to other indy units. 
The executable runs without exception (on the pi). 
Arm version: 4. Why?
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           ARM
  Version:                           0x1
  Entry point address:               0x100ec
  Start of program headers:          52 (bytes into file)
  Start of section headers:          428924 (bytes into file)
  Flags:                             0x5000200, Version5 EABI, soft-float ABI
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         4
  Size of section headers:           40 (bytes)
  Number of section headers:         14
  Section header string table index: 11
Attribute Section: aeabi
File Attributes
  Tag_CPU_arch: v4T
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-1
  
Then I added the line uses IdGlobal
I've added in project options, compiler options, other unit files the map d:\exportSmData\indy\System\
Rebuild. The size of the executable is now 2.2 Mb
The application runs without exception. Improvement!
Arm version 6.
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           ARM
  Version:                           0x1
  Entry point address:               0x10570
  Start of program headers:          52 (bytes into file)
  Start of section headers:          2178508 (bytes into file)
  Flags:                             0x5000400, Version5 EABI, hard-float ABI
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         7
  Size of section headers:           40 (bytes)
  Number of section headers:         31
  Section header string table index: 28
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "6"
  Tag_CPU_arch: v6
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-1
  Tag_FP_arch: VFPv2
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_enum_size: int
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
  
Then I added the line 
uses IdGlobal uses IdGlobal, IdMultipartFormData, IdBaseComponent, IdComponent, IdTCPConnection, IdTCPClient, IdHTTP;
I add in project options 'other units' indy\System; indy\Protocols; indy\Core
The executable is now 7.2 Mb
It runs without exception!
Arm version 6
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           ARM
  Version:                           0x1
  Entry point address:               0x10610
  Start of program headers:          52 (bytes into file)
  Start of section headers:          7242624 (bytes into file)
  Flags:                             0x5000400, Version5 EABI, hard-float ABI
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         7
  Size of section headers:           40 (bytes)
  Number of section headers:         31
  Section header string table index: 28
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "6"
  Tag_CPU_arch: v6
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-1
  Tag_FP_arch: VFPv2
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_enum_size: int
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6

The main problem 'the unhandled exception' is solved. Which is nice!! 
The only puzzling thing is that the simplest Hello World ends up using Arm4. Another version is no problem as long as it smaller then version 7.
No I'll try to get the components to work. Thanks!

**Comment by LongDirtyAnimAlf** [comment]
This is very good news !
You did encounter the softfloat vs hardfloat on arm. Nearly all arm-linux use hardfloat. That is why fpcupdeluxe defaults to hardfloat.
Your distro seems to be softfloat. Or something similar. So, you had to adjust the standard settings.
Also Android is non-hardfloat.
Glad to have solved your issue.

**Comment by LongDirtyAnimAlf** [comment]
https://android.googlesource.com/platform/ndk/+/ndk-r12-release/docs/HardFloatAbi.md

**Comment by LongDirtyAnimAlf** [comment]
I have added ARMV6 as a cross-cpu-target.
You might try/test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/1.8.2h/fpcupdeluxe-i386-win32.exe
Closing this issue.
Reference:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/issues/148

**Comment by KeesBleijenberg** [comment]
I tried the  ARMV6 as a cross-cpu-target. And it worked. The executable is v6 on the pi and runs without exception.
