### ISSUE TITLE
Cross compiling from linux x86_64 to darwin x86_64 fails with linking and shared library file not found errors

### ISSUE THREAD

**Issue by m-audio91** [LongDirtyAnimAlf/fpcupdeluxe#329]
Hi
I've been away from programming for a while, now decided to fresh install and continue my projects.
The problem is I'm not able to cross-compile from linux x86_64 to MacOS darwin x86_64 anymore.
I've followed my old installation procedure which was working without issues (1-install these specific dependencies `sudo apt install libgtk2.0-dev gdb subversion git unrar clang` > 2-install fpcupdeluxe > 3-set installation location > 4-select trunk+trunk and install > 5-install cross-compilers i386linux+i386win32+x86_64darwin > 6-open projects and go) and my projects where not touched in any way. I'm just selecting target and hit build.
Tried with both Peppermint 10 (my preferred environment) and the new Kubuntu 20.4 LTS. Both fresh VMs. deluxe v1.8.2h (now) and v1.8.2f (two weeks ago).
This is the error message:
`Error: /home/mrb/dev/lazfpctrunkcross/cross/bin/all-apple/bin/ld: error while loading shared libraries: libBlocksRuntime.so: cannot open shared object file: No such file or directory`
It is mentioning libBlocksRuntime.so but I can see it is available in this directory:
`/home/mrb/dev/lazfpctrunkcross/cross/bin/all-apple/lib`
Hand copying it to a global /lib folder of the OS suppresses this error but raises another similar error for another library file and not all the files available in the mentioned folder.   
Any new dependency introduced for darwin x86_64? because the procedure I mentioned earlier was working without anything extra on same Peppermint 10 iso image.  

Thanks.

**Comment by m-audio91** [comment]
I've redone the procedure this time with fpcupdeluxe v1.6.4g which was near the last modified date of one of my compiled programs and it works with the exact same procedure mentioned above. so I guess it might be something newly introduced ?

**Comment by gcarreno** [comment]
Hey @m-audio91 

Could I trouble you to find out if you can cross compile from `x86_64` to `i386` but not a console apps, a gtk2 one?
Doing this by just installing the cross-compiler for linux-i386 on `fpcupdeluxe`.

I'm asking cuz I was only able to cross compile console apps, since they do not dynamically link to anything, if they're quite basic.

If you do, **MANY**, **MANY**, **many thanks** in advance since I've been banging my head for a while about the `crtbegin.o` error and just today had the clearness of mind to solve it:

To solve this in my Ubuntu 20.10 64b, I had to install: 
```shell
$ sudo apt install libgcc-9-dev:i386
```
and add the folder `/usr/lib/gcc/i686-linux-gnu/9/` to `-Fl` on a Build Mode(I named it Release-linux-i386) just for Linux 32bits.

I'm not completely sure this is related to your issue, but it did solve my cross-compilation issues and can possibly help yours?

In any case I need to bug @LongDirtyAnimAlf to include some kind of warning about the `crtbegin.o` issue on cross compiling from x86_64 to i386 under Linux.

Cheers,
Gus

**Comment by m-audio91** [comment]
Hey @gcarreno 
Sure, VMs are life savers (just a few clicks and revert to a clean installation state in no time). my other try (1st post) was also on this Peppermint 10 x86_64 VM and I was only testing GUI GTK2 applications and both 1386linux and i386win32 targets where fine (only x86_64 darwin was the problem). this time I ran `apt update` `apt upgrade` beforehand. in addition, I did a Console program compilation test. And there was no error in cross-compiling both GUI GTK2 application and CLI console program for 1386 linux. (fpcupdeluxe v1.8.2h, lazarus trunk r64244  fpc trunk r47821)

**Comment by m-audio91** [comment]
@LongDirtyAnimAlf  
I can think about two things:  
**1**: there must be a way for the newer fpcupdeluxe to tell the linker that it has those library files inside `lazinstallpath/cross/bin/all-apple/lib` (libblocksruntime.so and libtapi.so.12git) so hand copying becomes unnecessary.  
**2**: shared library file `libtinfo.so.6` which was the last error in linking is [available in Fedora and some other distros](https://pkgs.org/download/libtinfo.so.6()(64bit)) but the latest version available for apt distros, searched by `apt-file` mentioned by @gcarreno shows as `libtinfo.so.5.9`. so they have not included `libtinfo.so.6` yet and manually renaming 5.9 to 6 didn't work for me. but I went through all the hassle and installed a Fedora 33 workstation. after installing all the things, and hand copying those library files mentioned in `1` into `/lib64` directory, I'm now able to cross-compile for x86_64 darwin again. it shows some errors like `Error: /home/mrb/dev/lazfpctrunkcross/cross/bin/all-apple/bin/ld: /lib64/libtinfo.so.6: no version information available (required by /lib64/libtapi.so.12git)` but compiles OK.   
Thanks.

**Comment by LongDirtyAnimAlf** [comment]
Confirmed.
This is a fpcupdeluxe bugger.
Will look into this.

**Comment by LongDirtyAnimAlf** [comment]
Should be solved by new binary utilities.
Please remove the "cross/bin/all-apple" directory.
Re-run fpcupdeluxe to install cross-compiler. New bins will be downloaded and should work.

**Comment by m-audio91** [comment]
OK I did it now on Peppermint 10 and fpcupdeluxe 1.8.2h failed installing cross-compiler for darwin x86_64:
```
/usr/bin/make -C rtl all
/usr/bin/make -C darwin all
/home/mrb/dev/lazfpctrunkcross/fpc/bin/x86_64-linux/ppcrossx64 -Ur -dFPC_USE_LIBC -Tdarwin -Ur -Xs -O2 -n -Fi../inc -Fi../x86_64 -Fi../unix -Fi../bsd -Fi../bsd/x86_64 -Fi../darwin/x86_64 -FD/home/mrb/dev/lazfpctrunkcross/cross/bin/all-apple/bin -FE. -FU/home/mrb/dev/lazfpctrunkcross/fpcsrc/rtl/units/x86_64-darwin -Fl/usr/lib/gcc/x86_64-linux-gnu/7 -vw-n-h-l-d-u-t-p-c- -dx86_64 -dRELEASE -Xd -Fl/home/mrb/dev/lazfpctrunkcross/cross/lib/all-darwin/MacOSX11.0.sdk/usr/lib  -Us -Sg ../bsd/system.pp
/home/mrb/dev/lazfpctrunkcross/cross/bin/all-apple/bin/clang: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
system.pp(398) Error: Can't call the assembler, error 127 switching to external assembling
system.pp(398) Fatal: There were 2 errors compiling module, stopping
make[1]: *** [darwin_all] Error 2
make: *** [rtl] Error 2
Fatal: Compilation aborted
Makefile:3247: recipe for target 'system.ppu' failed
Makefile:2739: recipe for target 'darwin_all' failed
Makefile:2918: recipe for target 'rtl' failed
fpcupdeluxe: ERROR: FPCCrossInstaller (BuildModuleCustom: FPC): Running cross compiler fpc /usr/bin/make for x86_64-darwin failed with an error code.


ERROR: Fpcupdeluxe fatal error !
Sequencer (FPCCleanBuildOnly): Failure running fpcupdeluxe: error executing sequence FPCCleanBuildOnly
Sequencer (Only): Failure running fpcupdeluxe: error executing sequence Only
```
see `libtinfo.so.6: cannot open shared object file: No such file or directory`

**Comment by LongDirtyAnimAlf** [comment]
Please try to use Google to get some info about this missing library. This might be related to your OS. A symlink might help you. Or an install of ncurses.
