### ISSUE TITLE
[FR] Include Ultibo edition

### ISSUE THREAD

**Issue by JonnyTech** [LongDirtyAnimAlf/fpcupdeluxe#330]
Would it be possible to include Ultibo editions of Free Pascal and Lazarus (https://github.com/ultibohub)?

Ultibo currently has an installer script: https://github.com/ultibohub/Tools/releases/latest/download/ultiboinstaller.sh

```
Linux installer for Free Pascal and Lazarus (Ultibo edition)
------------------------------------------------------------
This installation will download the sources for:
  Ultibo core
  Ultibo examples
  Free Pascal (Ultibo edition)
  Lazarus IDE (Ultibo edition)

Then it will build all of the above, this will take several
minutes to complete depending on the speed of your system.

The installation will not interfere with any existing
development environments including other installations
of Free Pascal and Lazarus.

Continue (y/n)?
```
It builds a cross compiler for `arm-none-eabi` which `fpcupdeluxe` does not currently include support for.

```
# Require the following programs 
require "arm-none-eabi-as" "binutils-arm-none-eabi"
require "arm-none-eabi-ld" "binutils-arm-none-eabi"
require "arm-none-eabi-objcopy" "binutils-arm-none-eabi"
```
It would be fantastic to be able to use `fpcupdeluxe` with Ultibo.

**Comment by LongDirtyAnimAlf** [comment]
Please test the latest pre-release. Ultibo is added, both as install-target and as cross-target.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2i

**Comment by JonnyTech** [comment]
Wow, fantastic, I was not expecting a yes, let alone a full implementation - thank you very much indeed! I will install it later although I may not be able to test the results for a few days. I shall close this FR/issue once I can confirm that the cross-compiled binaries produced do indeed work.

**Comment by JonnyTech** [comment]
I just tried v1.8.21 and in the `cross` tab selected `arm` and `ultibo` - when clicking `install compiler` got a `makefile` error:

```
Going to install a cross-compiler from available sources.
Fpcupdeluxe: FPC cross-builder: Building compiler for ultibo-arm (OPT: -dFPC_ARMHF ) [CROSSOPT: -CpARMV7A -CfVFPV3 -CIARM -CaEABIHF -OoFASTMATH ] {SUBARCH: armv7a}.
FPCUP(deluxe) is starting up.

FPCupdeluxe basedir:       /home/user/development
Bootstrap dir:             /home/user/development/fpcbootstrap

FPC URL:                   https://svn.freepascal.org/svn/fpc/trunk
FPC source directory:      /home/user/development/fpcsrc
FPC install directory:     /home/user/development/fpc
FPC options:               -dFPC_ARMHF 

Lazarus URL:               https://svn.freepascal.org/svn/lazarus/tags/lazarus_2_0_10
Lazarus source directory:  /home/user/development/lazarus
Lazarus install directory: /home/user/development/lazarus
Lazarus options:           

Please stand back and enjoy !

2-1-21 23:59:40: fpcupdeluxe: V318 (20201227) started.
FPCUPdeluxe V1.8.2i for x86_64-linux running on Debian GNU/Linux

Found valid as application.
Found valid gunzip application.
Found valid tar application.
Found valid make application.
fpcupdeluxe: info: FPCCrossInstaller (CleanModule: FPC): Running make distclean twice for target arm-ultibo
fpcupdeluxe: Executing: /usr/bin/make --jobs=4 FPMAKEOPT=--threads=4 FPC=/home/user/development/fpcbootstrap/ppcx64 --directory=/home/user/development/fpcsrc FPCMAKE=/home/user/development/fpc/bin/x86_64-linux/fpcmake PPUMOVE=/home/user/development/fpc/bin/x86_64-linux/ppumove FPCDIR=/home/user/development/fpcsrc PREFIX=/home/user/development/fpc INSTALL_PREFIX=/home/user/development/fpc INSTALL_BINDIR=/home/user/development/fpc/bin/x86_64-linux OS_TARGET=ultibo CPU_TARGET=arm SUBARCH=armv7a distclean (working dir: /home/user/development/fpcsrc)
Makefile:233: *** The Makefile doesn't support target arm-ultibo, please run fpcmake first.  Stop.


ERROR: Fpcupdeluxe fatal error !
Sequencer (FPCCleanBuildOnly): Failure running fpcupdeluxe: error executing sequence FPCCleanBuildOnly
Sequencer (Only): Failure running fpcupdeluxe: error executing sequence Only
Building cross-tools failed. Aborting.
```

**Comment by LongDirtyAnimAlf** [comment]
For sure you will get this error with a normal FPC and Lazarus install !
Ultibo needs its own version of FPC and Lazarus. As these versions are available at their website.

So, use fpcupdeluxe to install (in a new directory) the FPC and Lazarus Ultibo versions. I made them available as install-choices in the first tab.

**Comment by JonnyTech** [comment]
Installing ultibo fpc+lazarus into a new empty folder yields this error: [ultibo.txt](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/5767009/ultibo.txt). Trying a second time gives same error.

```
fpcupdeluxe: Executing: /usr/bin/make --directory=/home/user/ultibo/lazarus FPC=/home/user/ultibo/fpc/bin/x86_64-linux/fpc.sh PP=/home/user/ultibo/fpc/bin/x86_64-linux/ppcx64 USESVN2REVISIONINC=0 PREFIX=/home/user/ultibo/lazarus INSTALL_PREFIX=/home/user/ultibo/lazarus LAZARUS_INSTALL_DIR=/home/user/ultibo/lazarus/ FPCDIR=/home/user/ultibo/fpcsrc/source FPCMAKE=/home/user/ultibo/fpc/bin/x86_64-linux/fpcmake PPUMOVE=/home/user/ultibo/fpc/bin/x86_64-linux/ppumove OPT=-vw-n-h-l-d-u-t-p-c- lazbuild (working dir: /home/user/ultibo/lazarus)
Makefile:220: *** The Makefile doesn't support target x86_64-linux, please run fpcmake first.  Stop.
fpcupdeluxe: ERROR: LazarusNativeInstaller (BuildModuleCustom: Lazbuild): make returned exit status #512
```
![ultibo](https://user-images.githubusercontent.com/3584732/103585099-6b99a300-4eda-11eb-84d8-0ec787b6834f.png)

What do you recommend?

**Comment by LongDirtyAnimAlf** [comment]
Confirmed. Will try to solve.

**Comment by LongDirtyAnimAlf** [comment]
Uploaded new binary. Should solve. Please try again.

https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/1.8.2i/fpcupdeluxe-x86_64-linux

**Comment by JonnyTech** [comment]
Sorry, another error log: [ultibo.txt](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/5773151/ultibo.txt)

Contents of lower log window:
```
fpcupdeluxe: Performing a SVN/GIT/HG/FTP checkout ... please wait, could take some time.
fpcupdeluxe: Performing a SVN/GIT/HG/FTP checkout ... please wait, could take some time.
fpcupdeluxe: WARNING: FPCNativeInstaller (DownloadFromFTP: Core): Core sources are already there.
fpcupdeluxe: Performing a SVN/GIT/HG/FTP checkout ... please wait, could take some time.
fpcupdeluxe: WARNING: FPCNativeInstaller (DownloadFromFTP: Core): Core sources will be replaced.
fpcupdeluxe: Performing a SVN/GIT/HG/FTP checkout ... please wait, could take some time.
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC is at revision: 32846
fpcupdeluxe: info: FPC native builder: Detected source version FPC (source): 3.1.1
fpcupdeluxe: info: FPC native builder: Using FPC bootstrap compiler with version: 3.0.2
fpcupdeluxe: Start of compile error summary.
fpcupdeluxe: ERROR: LazarusNativeInstaller (CheckModule: Lazarus): Could not determine what repoclient to use for Lazarus sources !
fpcupdeluxe: Performing a SVN/GIT/HG/FTP checkout ... please wait, could take some time.
fpcupdeluxe: info: LazarusNativeInstaller (GetModule: Lazarus): Lazarus is at revision: unknown
fpcupdeluxe: info: Lazarus native builder: Detected source version Lazarus: 1.6U
fpcupdeluxe: info: Lazarus native builder: Using FPC compiler with version: 3.1.1
fpcupdeluxe: Start of compile error summary.
fpcupdeluxe: ERROR: LazarusNativeInstaller (BuildModuleCustom: UserIDE): lazbuild returned error code 55552
Details:
fpcupdeluxe: Done !!
```
Then re-running, ie pressing the install button without closing first, it installs ok: [ultibo2.txt](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/5773173/ultibo2.txt)

Lower log window:
```
fpcupdeluxe: Start of compile error summary.
fpcupdeluxe: ERROR: FPCNativeInstaller (CheckModule: FPC): Could not determine what repoclient to use for FPC sources !
fpcupdeluxe: Performing a SVN/GIT/HG/FTP checkout ... please wait, could take some time.
fpcupdeluxe: WARNING: FPCNativeInstaller (DownloadFromFTP: FPC): FPC sources are already there.
fpcupdeluxe: Performing a SVN/GIT/HG/FTP checkout ... please wait, could take some time.
fpcupdeluxe: WARNING: FPCNativeInstaller (DownloadFromFTP: FPC): FPC sources will be replaced.
fpcupdeluxe: Performing a SVN/GIT/HG/FTP checkout ... please wait, could take some time.
fpcupdeluxe: Performing a SVN/GIT/HG/FTP checkout ... please wait, could take some time.
fpcupdeluxe: WARNING: FPCNativeInstaller (DownloadFromFTP: Core): Core sources are already there.
fpcupdeluxe: Performing a SVN/GIT/HG/FTP checkout ... please wait, could take some time.
fpcupdeluxe: WARNING: FPCNativeInstaller (DownloadFromFTP: Core): Core sources will be replaced.
fpcupdeluxe: Performing a SVN/GIT/HG/FTP checkout ... please wait, could take some time.
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC is at revision: 32846
fpcupdeluxe: info: FPC native builder: Detected source version FPC (source): 3.1.1
fpcupdeluxe: info: FPC native builder: Using FPC bootstrap compiler with version: 3.0.2
fpcupdeluxe: Start of compile error summary.
fpcupdeluxe: ERROR: LazarusNativeInstaller (CheckModule: Lazarus): Could not determine what repoclient to use for Lazarus sources !
fpcupdeluxe: Performing a SVN/GIT/HG/FTP checkout ... please wait, could take some time.
fpcupdeluxe: WARNING: LazarusNativeInstaller (DownloadFromFTP: Lazarus): Lazarus sources are already there.
fpcupdeluxe: Performing a SVN/GIT/HG/FTP checkout ... please wait, could take some time.
fpcupdeluxe: WARNING: LazarusNativeInstaller (DownloadFromFTP: Lazarus): Lazarus sources will be replaced.
fpcupdeluxe: Performing a SVN/GIT/HG/FTP checkout ... please wait, could take some time.
fpcupdeluxe: info: LazarusNativeInstaller (GetModule: Lazarus): Lazarus is at revision: unknown
fpcupdeluxe: info: Lazarus native builder: Detected source version Lazarus: 1.6U
fpcupdeluxe: info: Lazarus native builder: Using FPC compiler with version: 3.1.1
fpcupdeluxe: Getting suggestedpackages sources ... please wait, could take some time.
fpcupdeluxe: Done !!
```
When starting `/home/user/ultibo/lazarus/lazarus` an error is shown:
```
Compiler "/home/user/ultibo/fpc/bin/x86_64-linux/fpc.sh" does not support target arm-ultibo
```
![laz](https://user-images.githubusercontent.com/3584732/103712844-c1417e80-4fb2-11eb-81c9-7c6b8d060ed9.png)

**Comment by LongDirtyAnimAlf** [comment]
For sure it will fail at this moment. You need to install the cross-compiler for arm-ultibo also.

**Comment by JonnyTech** [comment]
Great, that seems to work. But when I try compiling from fpc or lazarus for ultibo it complains that the necessary cfg files are missing.

The installer script creates them here: https://github.com/ultibohub/Tools/blob/a3981545f55fe7d7f0d2a9c3a9d27d326420bf08/Installer/Core/Linux/ultiboinstaller.sh#L497

Can fpcupdeluxe do the same?

**Comment by LongDirtyAnimAlf** [comment]
`But when I try compiling from fpc or lazarus for ultibo it complains that the necessary cfg files are missing.`

You need to be more precise.
Fpcupdeluxe creates its own config-files.
Please describe the errors encountered in detail.

**Comment by JonnyTech** [comment]
Ultibo has 4 targets that it compiles to; `Raspberry Pi`, `Raspberry Pi2`, `Raspberry Pi3`, `QEMU`. Each requires a specific configuration file. Their installer creates the 4 files through a series of `echo` commands. It is almost like cross-compiling. More details [here](https://ultibo.org/wiki/Building_for_Raspbian#Creating_the_Configuration_files). This is the content of each config file:

```
# Raspberry Pi (A/B/A+/B+/Zero) specific config file
-CfVFPV2
-CIARM
-CaEABIHF
-OoFASTMATH
-dRPI
-XParm-none-eabi-
-Fu$BASE/fpc/units/armv6-ultibo/rtl
-Fu$BASE/fpc/units/armv6-ultibo/packages
-Fl$BASE/fpc/units/armv6-ultibo/lib
-Fl$BASE/fpc/units/armv6-ultibo/lib/vc4

# Raspberry Pi 2B specific config file
-CfVFPV3
-CIARM
-CaEABIHF
-OoFASTMATH
-dRPI2
-XParm-none-eabi-
-Fu$BASE/fpc/units/armv7-ultibo/rtl
-Fu$BASE/fpc/units/armv7-ultibo/packages
-Fl$BASE/fpc/units/armv7-ultibo/lib
-Fl$BASE/fpc/units/armv7-ultibo/lib/vc4

# Raspberry Pi 3B specific config file
-CfVFPV3
-CIARM
-CaEABIHF
-OoFASTMATH
-dRPI3
-XParm-none-eabi-
-Fu$BASE/fpc/units/armv7-ultibo/rtl
-Fu$BASE/fpc/units/armv7-ultibo/packages
-Fl$BASE/fpc/units/armv7-ultibo/lib
-Fl$BASE/fpc/units/armv7-ultibo/lib/vc4

# QEMU VersatilePB specific config file
-CfVFPV3
-CIARM
-CaEABIHF
-OoFASTMATH
-dQEMUVPB
-XParm-none-eabi-
-Fu$BASE/fpc/units/armv7-ultibo/rtl
-Fu$BASE/fpc/units/armv7-ultibo/packages
-Fl$BASE/fpc/units/armv7-ultibo/lib
```

`$BASE` is the path to the `fpc` executable binary.

I know that `fpcupdeluxe` creates its own config files but they are irrelevant for Ultibo as without the above flags the executables will not be created for the desired hardware.

My request is if these `.cfg` can be created so that once `fpcupdeluxe` is done then the setup is complete.

**Comment by LongDirtyAnimAlf** [comment]
Yes, I have seem these config-files. But that was not my question.

> Great, that seems to work. But when I try compiling from fpc or lazarus for ultibo it complains that the necessary cfg files are missing.

Please provide details about the above error/complaint.

**Comment by JonnyTech** [comment]
With the config files generated by `fpcupdeluxe`, compiling to executables works flawlessly. Thank you, that is perfect.

But the whole point of Ultibo is not to compile to native executables, rather it creates kernel images for various targets. Without those specific .cfg files above then a user cannot use Ultibo as intended.

These screenshots may help - I started a blank project, changed the platform target options only (not added any cfg settings) but the compiler will look for the .cfg files which are not currently created by `fpcupdeluxe`:

![ultibo1](https://user-images.githubusercontent.com/3584732/104824751-9b3a9a80-584c-11eb-95b6-8c0e9f1348b3.png)
![ultibo2](https://user-images.githubusercontent.com/3584732/104824752-9bd33100-584c-11eb-98ff-b4ac0e65068c.png)
![ultibo3](https://user-images.githubusercontent.com/3584732/104824753-9c6bc780-584c-11eb-909b-d8af816b14ee.png)

**Comment by LongDirtyAnimAlf** [comment]
This is very good info. Thanks !
Will see if its possible to integrate this into fpcupdeluxe.

**Comment by LongDirtyAnimAlf** [comment]
Uploaded new binaries.
Please test:
1: Install/Update FPC Ultibo.
2: Install/Update Ultibo cross-compiler.

Limitation:
If you choose "arm" as Ultibo cross-cpu target, fpcupdeluxe will build for armv7.
If you choose "armv6" as Ultibo cross-cpu target, fpcupdeluxe will build for armv6.
These two cannot co-exist. This is a fpcupdeluxe limitation.

**Comment by JonnyTech** [comment]
Thank you, I shall be able to test tomorrow.

With regards to the arm v6/v7 limitation, can the cross compiler be installed to a different folder?

When testing, I will also install from their official script to see how they do it.

**Comment by JonnyTech** [comment]
Sorry for the long delay, have been unable to get to my development system due to lockdown restrictions.

The latest pre-release (v1.8.2j) does not install cfg files, but there is a typo: `Ultibo-$FPCSUBARCH` should be `ultibo-$FPCSUBARCH`, due to Linux case-sensitive filesystem.

**Comment by LongDirtyAnimAlf** [comment]
You might test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2j

I have added an Ultibo quick-install button.
That installs FPC, Lazarus and a crosser for armv7a.

**Comment by JonnyTech** [comment]
Greay, thanks, will test in the next few days.

**Comment by LongDirtyAnimAlf** [comment]
Implemented in latest release.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2k

**Comment by JonnyTech** [comment]
There have been some changes to their official installer:

https://github.com/ultibohub/Tools/commits/master/Installer/Core/Linux/ultiboinstaller.sh

Do these have any impact on `fpcupdeluxe`?
