### ISSUE TITLE
Compiling with cthreads causes linking failure

### ISSUE THREAD

**Issue by JonnyTech** [LongDirtyAnimAlf/fpcupdeluxe#331]
On Linux-x64 used `fpcupdeluxe` to install `fpc` trunk and cross-compiler for `arm linux` as I am also targetting Raspberry Pi.

Here is a very minimal(!) example - I need `cthreads` in my final program:
```
program hello;
uses cthreads;
begin
end.
```
When compiling for native system I get warnings:
```
Target OS: Linux for x86-64
Compiling hello.pp
Linking hello.x86_64-linux
hello.pp(4,1) Warning: "crti.o" not found, this will probably cause a linking failure
hello.pp(4,1) Warning: "crtbegin.o" not found, this will probably cause a linking failure
hello.pp(4,1) Warning: "crtend.o" not found, this will probably cause a linking failure
hello.pp(4,1) Warning: "crtn.o" not found, this will probably cause a linking failure
4 lines compiled, 0.1 sec, 179264 bytes code, 76400 bytes data
4 warning(s) issued
```
When compiling for the pi I get warnings and errors:
```
Target OS: Linux for ARMHF
Compiling hello.pp
Linking hello
hello.pp(4,1) Warning: "crti.o" not found, this will probably cause a linking failure
hello.pp(4,1) Warning: "crtbegin.o" not found, this will probably cause a linking failure
hello.pp(4,1) Warning: "crtend.o" not found, this will probably cause a linking failure
hello.pp(4,1) Warning: "crtn.o" not found, this will probably cause a linking failure
/usr/bin/arm-linux-gnueabihf-ld: //home/user/development/fpc/units/arm-linux/rtl/cprt0.o: in function `_haltproc_eabi':
(.text+0x88): undefined reference to `_fini'
/usr/bin/arm-linux-gnueabihf-ld: (.text+0x90): undefined reference to `_init'
hello.pp(4,1) Error: Error while linking
hello.pp(4,1) Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted
```
Commenting the line `uses cthreads;` has no problems:
```
Target OS: Linux for x86-64
Compiling hello.pp
Linking hello.x86_64-linux
4 lines compiled, 0.1 sec, 145648 bytes code, 56616 bytes data
Target OS: Linux for ARMHF
Compiling hello.pp
Linking hello
4 lines compiled, 0.1 sec, 201424 bytes code, 47684 bytes data
```
Is this a `fpcupdeluxe` installation issue or am I being an idiot?

**Comment by JonnyTech** [comment]
Managed to get access to a pi - compiling natively on the pi:
```
Free Pascal Compiler version 3.3.1-r47911 [2020/12/30] for arm
Copyright (c) 1993-2020 by Florian Klaempfl and others
Target OS: Linux for ARMHF
Compiling hello.pp
Linking test
4 lines compiled, 0.6 sec, 238896 bytes code, 64364 bytes data
```
So it is something to do with cross compiling but unsure what it could be.

**Comment by LongDirtyAnimAlf** [comment]
I guess you have installed FPC and Lazarus in "/home/user/development" on your Linux machine.
It seems that fpcupdeluxe is using binary tools from an external source: /usr/bin/arm-linux-gnueabihf-ld
Normally, fpcupdeluxe uses its own tools and libs. The fpcupdeluxe libs provide "crti.o"and family to allow for successfull linking.

Question:
Are the pi-arm-tools located in "/home/user/development/cross" ?
Did fpcupdeluxe install them ?

Libs can be found here:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/crosslibs_v1.1/CrossLibsLinuxARM.zip

**Comment by JonnyTech** [comment]
> I guess you have installed FPC and Lazarus in "/home/user/development" on your Linux machine.

Yes, that was the default offered.

> Are the pi-arm-tools located in "/home/user/development/cross" ?

Yes.

> Did fpcupdeluxe install them ?

Yes.

> Libs can be found here:

Thanks. I think that I shall delete the whole `development` folder and get `fpcupdeluxe` to do a clean install again and shall report back.

**Comment by JonnyTech** [comment]
Deleting the install folder and reinstalling trunk then arm-cross fixed the issue - it must have gotten confused somewhere the first time. Thanks for your comments.
