### ISSUE TITLE
Admin rights and windows

### ISSUE THREAD

**Issue by mehmetulukaya** [LongDirtyAnimAlf/fpcupdeluxe#333]
Hello,

I am using fpcupdeluxe for trunk edition of Lazarus and it is working but my user account hasn't got admin rights.
So is it possible to install without admin rights?

Thanks in advance

**Comment by LongDirtyAnimAlf** [comment]
I have never used fpcupdeluxe with elevated permissions myself. So, the answer would be:
Yes, you can use fpcupdeluxe without elevated permissions.
