### ISSUE TITLE
Is it possible to make an cross compiler ARM-Linux -> AVR embedded?

### ISSUE THREAD

**Issue by fliegermichl** [LongDirtyAnimAlf/fpcupdeluxe#334]
I like to connect a Arduino board to the Raspberry Pi and program it from there. So i need and cross compiler ARM-Linux to AVR- embedded.

**Comment by LongDirtyAnimAlf** [comment]
Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/1.8.2i/fpcupdeluxe-arm-linux

**Comment by fliegermichl** [comment]
if i compare objpas.pp within Lazarus on Windows and Raspberry Pi then i find in the windows version
{$IFDEF FPC_HAS_FEATURE_ANSISTRINGS}

this is not the case in the Version on the Raspberry

In both cases i have installed "FPC stable" and "Lazarus fixes". how can it be that there are different sources?

**Comment by LongDirtyAnimAlf** [comment]
Stable is a moving target. Few years ago, stable was 3.0.0. Now its 3.2.0.
Have a look at version.pas in the compiler sources. That will tell you exactly what version you are looking at.

**Comment by fliegermichl** [comment]
i have deleted /home/pi/fpcupdeluxe completely and reinstalled with FPC = trunk and Lazarus = fixes.
now it is running fine!
thank you very mutch
