### ISSUE TITLE
1.8.2j / Compiling ide error..

### ISSUE THREAD

**Issue by FezaCakir** [LongDirtyAnimAlf/fpcupdeluxe#335]
![Error](https://user-images.githubusercontent.com/14251329/106377950-b6132000-63b1-11eb-823f-641fcb974870.png)

**Comment by gocher68** [comment]
Which boostrap compiler do you use?
In the Logging you can find something like this:
fpcupdeluxe: info: FPC native builder: Using FPC bootstrap compiler with version: 3.2.0
if it is a old one go to folder fpcbootstrap and delete the compiler (ppcx64).
Start Install/Update FPZ+Laz ...

**Comment by LongDirtyAnimAlf** [comment]
Its a very strange error, indicating that (perhaps) the Lazarus sources can no longer be found.
At the moment, I have no idea how to reproduce and/or solve this.

Sidenote:
I have retracted 1.8.2j
There were some serious bugs introduced by recent changes.
I am in the process of solving them.

**Comment by FezaCakir** [comment]
I've deleted installed folder and re-run fpcupdeluxe-x86_64-linux. Problem is resolved.

**Comment by LongDirtyAnimAlf** [comment]
Thanks for your feedback.
