### ISSUE TITLE
Idea-- shorter log for compiling

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#338]
see current log when many files are compiled-

![Screenshot from 2021-02-02 21-34-05](https://user-images.githubusercontent.com/4154978/106646243-8e34df80-659e-11eb-8147-644ad36311e7.png)

it's lines
```
<spaces>Compiling filename.ext
or
<spaces>Compling dir/dir/filename.ext
```

let's shorten this-- put ALL these lines into one SynEdit line. so all lines will overwrite previous lines of the same kind.
all consecutive lines. so any line of __different kind__ will go to next SynEdit line.

**Comment by LongDirtyAnimAlf** [comment]
Will not implement.
This is how FPC (or its makefile) itself outputs its build results.
We need to maintain correlation between auto-build by fpcupdeluxe and manual build. Especially when errors happen.
