### ISSUE TITLE
offline mode for "ALIASfpcURL" "ALIASlazURL"

### ISSUE THREAD

**Issue by mariuszmaximus** [LongDirtyAnimAlf/fpcupdeluxe#339]
Is possible use local ZIP in "ALIASfpcURL" "ALIASlazURL" ?

**Comment by LongDirtyAnimAlf** [comment]
Fpcupdeluxe needs some structure regarding the FPC and Lazarus sources and their location.
So, this will not be easy to implement.
However.
Upload your zips somewhere, so I can have a look at their contents and have a go at implementing this.

**Comment by LongDirtyAnimAlf** [comment]
Closing due to no feedback. Please re-open when needed.
