### ISSUE TITLE
Error installing/updating trunk/trunk

### ISSUE THREAD

**Issue by sstvmaster** [LongDirtyAnimAlf/fpcupdeluxe#342]
Hi Don,

`
    C:/!LAZ/laztrunk/fpcbootstrap/ppc386.exe -Ur -Xs -O2 -n -Fui386 -Fusystems -FuC:/!LAZ/laztrunk/fpcsrc/rtl/units/i386-win32 -Fii386 -FEi386/bin/i386-win32 -FUi386/units/i386-win32 -dRELEASE -vw-n-h-l-d-u-t-p-c-   -dREVINC -di386 -dGDB -dBROWSERLOG -Fux86 -Fix86 version.pas
    C:/!LAZ/laztrunk/fpcbootstrap/ppc386.exe -Ur -Xs -O2 -n -Fui386 -Fusystems -FuC:/!LAZ/laztrunk/fpcsrc/rtl/units/i386-win32 -Fii386 -FEi386/bin/i386-win32 -FUi386/units/i386-win32 -dRELEASE -vw-n-h-l-d-u-t-p-c-   -dREVINC -di386 -dGDB -dBROWSERLOG -Fux86 -Fix86 pp.pas
    t_embed.pas(1704,3) Fatal: Syntax error, "NIL" expected but "(" found
    Fatal: Compilation aborted
    make[4]: *** [next] Error 2
    make[3]: *** [ppc1.exe] Error 2
    make[2]: *** [cycle] Error 2
    make[1]: *** [compiler_cycle] Error 2
    make: *** [build-stamp.i386-win32] Error 2
     
    fpcupdeluxe: ERROR: FPCNativeInstaller (BuildModuleCustom: FPC): Error running C:\!LAZ\laztrunk\fpcbootstrap\make.exe for FPC failed with exit code 2
    . Details:
     
     
    ERROR: Fpcupdeluxe fatal error !
    Sequencer (FPC): Failure running fpcupdeluxe: error executing sequence FPC
    Sequencer (Defaultwin32): Failure running fpcupdeluxe: error executing sequence Defaultwin32
     
`

I got this error, see also
- https://forum.lazarus.freepascal.org/index.php/topic,34645.msg394141.html#msg394141
- https://forum.lazarus.freepascal.org/index.php?topic=53334.msg394496#msg394496

Many thanks, Maik

**Comment by sstvmaster** [comment]
Nothing?

**Comment by LongDirtyAnimAlf** [comment]
I am very busy getting fpcupdeluxe ready for some extra features regarding embedded development.
Its a lot of work.

Your issue has been and will be addressed.
I have already tried to reproduce your problem by installing a system exactly as your, in the same directory also.
No problems whatsoever.

So, please provide me of the version of your bootstrapper:
C:\!LAZ\laztrunk\fpcbootstrap\ppc386.exe -iW

**Comment by michael-ring** [comment]
Actually the error you see is in code provided by me to fpc....

the crashing line should be inside of:
function TlinkerEmbedded.GenerateUF2(binFile,uf2File : string;baseAddress : longWord):boolean;

but I do not see why this error should pop up.

Can you please check if md5 of t_embed.pas is ad0b0f01bba3e5257695fdd84c30c745, and if not, provide your version?

Thank you,

Michael

**Comment by sstvmaster** [comment]
It is ok, if you are busy.

> So, please provide me of the version of your bootstrapper:
> C:!LAZ\laztrunk\fpcbootstrap\ppc386.exe -iW

`C:\Users\Maik>C:\!LAZ\laztrunk\fpcbootstrap\ppc386.exe -iW
3.0.4`

**Comment by LongDirtyAnimAlf** [comment]
That is old. It should be 3.2.0
Would you mind deleting the bootstrapper and run fpcupdeluxe again ?
It should download a 3.2.0 version if all goes well.

**Comment by sstvmaster** [comment]
Hi Michael,

the md5 of the file in my fpcsrc is: 8fc26d4d36aba0a10b8a0e5ac147a297
the lastest from svn is: 940719325b960e95fe2e55a61b9ce181

**Comment by michael-ring** [comment]
Both in git and on svn the md5 of ./compiler/systems/t_embed.pas is ad0b0f01bba3e5257695fdd84c30c745

So if Don's tip does not yet solve the issue I'd propose that you do a fresh run of fpcupdeluxe (a recent version) in a new directory....

**Comment by sstvmaster** [comment]
So i have removed fpcsrc and fpcbootstrap directory, now it works, thanks both!!!
