### ISSUE TITLE
Inconsistent directory structure in cross/lib/

### ISSUE THREAD

**Issue by michael-ring** [LongDirtyAnimAlf/fpcupdeluxe#346]
arm-embedded looks best to me, subdirs are
cross/lib/arm-embedded/armv6m cross/lib/arm-embedded/armv7m etc.... 

but there are some stray files in cross/lib that look in the wrong place as they all are arch specific

arm-freertos has an extra lib directory:
cross/lib/arm-freertos/lib/ , with this directory removed all would be fine..

avr-embedded is similar to arm-embedded, proper subdirectories but a good number of files in the base directory that look wrong at that place.

xtensa-freertos has no arch specific subdirectories but there are already 2 archs (lx6 and lx106) which are for sure not link compatible.

**Comment by LongDirtyAnimAlf** [comment]
cross/lib/arm-freertos/lib/ 
Your release of the freertos libs is used. This release contains this extra path.
I will be happy if you remove this extra path from the released zip.

Will need to look into xtensa.

**Comment by michael-ring** [comment]
let me fix my release for freertos, that is the better solution....

**Comment by michael-ring** [comment]
looking mostly good now, only found problematic files were in arm-embedded, there are still some .o files in the main directory of cross/lib/arm-embedded

**Comment by michael-ring** [comment]
correction, onr more bad apple:
cross/lib/avr-embedded

**Comment by michael-ring** [comment]
I today found out the hard way that those extra files in arm-embedded directory actually are a Prio-1 issue.
There is a libgcc.a in that directory and exactly this version is found when linking code for the Pico. As it seems to be for another arch the code links but crashes and burns.... When I delete the files in this directory all is back to normal

**Comment by michael-ring** [comment]
Still not fixed.... Kills Pico Target SOS.....

**Comment by michael-ring** [comment]
I created a workarround by renaming the libgcc.a I use to libgcc-armv6m, so pico is safe, but the root casuse persists, the files in the directory must go away in a subarch directory where they belong

**Comment by michael-ring** [comment]
Still not fixed in latest build

**Comment by michael-ring** [comment]
fixed in latest release
