### ISSUE TITLE
Order of entries in fpc.cfg needs to be changed for embedded targets

### ISSUE THREAD

**Issue by michael-ring** [LongDirtyAnimAlf/fpcupdeluxe#347]
When I use the order in fpc.cfg as generated by fpcupdeluxe I get the error message that system.ppu cannot be found.
Reason is (I think) that $FPCABI is not defined in my lpi file and will get defined in fpc.cfg but that entry comes after that the -Fu entries are evaluated so the entries get discarded.

By simply putting those rules behind the definition of -CaEABI the issue is fixed....

Hope that this is an easy fix for you......

Here's an example for the working entries:

```
#IFDEF FPC_CROSSCOMPILING
#IFDEF EMBEDDED
#IFDEF CPUARM
#IFDEF CPUARMV6M
-CaEABI
-Fl/Users/ring/fpcupdeluxe-embedded/cross/lib/arm-embedded/
#ENDIF CPUARMV6M
-FD/Users/ring/fpcupdeluxe-embedded/cross/bin/arm-embedded/
-XParm-embedded-
-Fu/Users/ring/fpcupdeluxe-embedded/fpc/units/arm-embedded/$FPCSUBARCH/$FPCABI/rtl
-Fu/Users/ring/fpcupdeluxe-embedded/fpc/units/arm-embedded/$FPCSUBARCH/$FPCABI/packages
#ENDIF CPUARM
#ENDIF EMBEDDED
#ENDIF FPC_CROSSCOMPILING
# end fpcup do not remove
```

**Comment by LongDirtyAnimAlf** [comment]
The change is easy. I trust you for its improved function.
However.
I did encounter a Lazarus error (system.ppu not found). Few days ago already. Looked into the sources of Lazarus. Lazarus will not look into subdirs. So, fpcupdeluxe creates an empty system.ppu in the appropriate units directory to fool Lazarus into thinking all is there. It was limited to Windows only. Will now expand this trick to all systems.

**Comment by michael-ring** [comment]
fixed in latest release, thank you!
