### ISSUE TITLE
armv6 CPU shows selections for other subarchs (which can confuse)

### ISSUE THREAD

**Issue by michael-ring** [LongDirtyAnimAlf/fpcupdeluxe#348]
I wanted to build armv6m subarch on Windows but I get an error message that armv6 is only for ultibo and Rpi

I checked twice, in the dialog I definitely selected armv6m. I have the same issue with armv7m and armv7em

**Comment by michael-ring** [comment]
Found out that this was half my error, I accidentially selected armv6 in CPU.
the invalid entries for armv6 should better be greyed out.....

**Comment by LongDirtyAnimAlf** [comment]
I will remove the armv6 item from the CPU list. The subarchs will do.
