### ISSUE TITLE
[Darwin] Crossoptions cannot be changed in 'Set Subarch' Dialog

### ISSUE THREAD

**Issue by michael-ring** [LongDirtyAnimAlf/fpcupdeluxe#350]
To be able to build a debug RTL I need to add -O1 -g to the crossopts. When I add those entries in the 'Set Subarch' Dialog they are not used. 

So either make the crossopts field read-only and offer debug options as an extra button or take over the manually changes done to this field (my preference)

**Comment by michael-ring** [comment]
i found out why I see this issue, it is something that can also be seen in setup dialogs in lazarus, so likely nothing easy to fix.
So I add -O1 and -g to Cross Build Options and then click in Bintools edit --> My changed Build Options work...

**Comment by michael-ring** [comment]
A workarround exists (see comment above) Feel free to close this issue when the fix for the problem has to be done in lcl

**Comment by LongDirtyAnimAlf** [comment]
Is this issue still current in latest release ? If caused by LCL will close.

**Comment by michael-ring** [comment]
Still there, and I found more nasty little issues that are LCL related, but I guess fixing is also the responsibility of LCL team as at least the initial issue is also in Lazarus.
