### ISSUE TITLE
[Darwin] Building cross-compiler twice in a row creates error

### ISSUE THREAD

**Issue by michael-ring** [LongDirtyAnimAlf/fpcupdeluxe#351]
I am using your fresh commit from today, manually built fpcupdeluxe.

When I build arm-embedded-armv7em for the first time all is fine, when I then build it a second time I get this error,
no idea why there is this permission denied in src/fpmkunit.pp in the build packages phase. the crosscompiler itself is built fine.

```
fpcupdeluxe: Executing: /usr/bin/make --directory=/Users/ring/fpcupdeluxe-embedded/fpcsrc FPCMAKE=/Users/ring/fpcupdeluxe-embedded/fpc/bin/x86_64-darwin/fpcmake PPUMOVE=/Users/ring/fpcupdeluxe-embedded/fpc/bin/x86_64-darwin/ppumove PREFIX=/Users/ring/fpcupdeluxe-embedded/fpc INSTALL_PREFIX=/Users/ring/fpcupdeluxe-embedded/fpc FPCDIR=/Users/ring/fpcupdeluxe-embedded/fpcsrc INSTALL_BINDIR=/Users/ring/fpcupdeluxe-embedded/fpc/bin/x86_64-darwin CROSSBINDIR=/Users/ring/fpcupdeluxe-embedded/cross/bin/arm-embedded FPC=/Users/ring/fpcupdeluxe-embedded/fpc/bin/x86_64-darwin/ppcarm packages CROSSINSTALL=1 CPU_SOURCE=x86_64 OS_SOURCE=darwin OS_TARGET=embedded CPU_TARGET=arm SUBARCH=armv7em NOGDBMI=1 REVSTR=48669 REVINC=force BINUTILSPREFIX=arm-embedded- CROSSOPT=-Cparmv7em -CfFPV4_SP_D16 -OoFASTMATH -CaEABIHF -XParm-embedded- OPT=-Fl/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -XR/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -ap (working dir: /Users/ring/fpcupdeluxe-embedded/fpcsrc)
/Library/Developer/CommandLineTools/usr/bin/make -C packages all
/Library/Developer/CommandLineTools/usr/bin/make -C ../rtl all FPC=
/Library/Developer/CommandLineTools/usr/bin/make -C embedded all
make[2]: src/fpmkunit.pp: Permission denied
make[1]: *** [fpmake] Error 2
make: *** [packages] Error 2
/Library/Developer/CommandLineTools/usr/bin/make -C fpmkunit bootstrap FPC=
src/fpmkunit.pp  -Fu/Users/ring/fpcupdeluxe-embedded/fpcsrc/rtl -FUunits_bs/x86_64-darwin -Fu../paszlib/src -Fu../hash/src -Fi../paszlib/src   -Fi../fcl-process/src/unix -Fu../fcl-process/src -Fi../fcl-process/src/darwin -Fi../fcl-process/src/dummy -Fu../libtar/src -Fl/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -XR/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -ap
fpcupdeluxe: ERROR: FPCCrossInstaller (BuildModuleCustom: FPC): Running cross compiler fpc /usr/bin/make for arm-embedded failed with an error code.


ERROR: Fpcupdeluxe fatal error !
Sequencer (FPCCleanBuildOnly): Failure running fpcupdeluxe: error executing sequence FPCCleanBuildOnly
Sequencer (Only): Failure running fpcupdeluxe: error executing sequence Only
Building cross-tools failed. Aborting.
```

**Comment by michael-ring** [comment]
I think the issue is brand new (from last commit) when I use the prebuilt 1.8.2j version I can recompile as often as I want

**Comment by LongDirtyAnimAlf** [comment]
The last commit contains a check if a rebuild of the cross-compiler is needed.
Version and revision of cross-compiler are compared with the native compiler: no difference -> no rebuild.
This should massively shorten compile times for similar subarchs.
I guess this is the source of the error.

**Comment by LongDirtyAnimAlf** [comment]
The newest pre-release is there. Lots of bugfixes.
But most important: repeated builds must be tested (again) !

https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2j

**Comment by michael-ring** [comment]
Loooking good, I tried several rebuilds, all were fine.
There is one thing where I am not sure if it's ok:
I have first build arm-embedded with several subarchs and have then switched to arm-freeros
Base compiler was not rebuilt, this may be ok but I am not sure, I would have expected a rebuild because of the different 'OS'

**Comment by michael-ring** [comment]
On aarch64 I also see no errors, but I do not see the message here that compiler was not built when I build a different subarch. I am on commit dfdb402

**Comment by michael-ring** [comment]
I think we can close this one, haven't seen issues anymore and it does not hurt that on aarch all seems to be rebuilt, it if faster than light....
