### ISSUE TITLE
Default binutils settings for freertos/embedded ar different

### ISSUE THREAD

**Issue by michael-ring** [LongDirtyAnimAlf/fpcupdeluxe#352]
This one is very cosmetic (and very likely caused by myself):
Embedded:
-XParm-embedded-
FreeRTOS:
-XParm-none-eabi-

'correct' settings should be arm-freertos for FreeRTOS Target, at least whne we want to play by the book.
For compatibility I also added the arm-none-eabi- versions of binutils because I guessed people will sometimes use the one or the other version.

**Comment by LongDirtyAnimAlf** [comment]
I would definitely be in favor of the standard names: arm-none-eabi.
All binutils for arm embedded (freertos = embedded) are called like that.

**Comment by michael-ring** [comment]
Same here, I never liked those strange default names by freepascal. But who am i to judge 8-)

**Comment by LongDirtyAnimAlf** [comment]
Please test latest pre-release:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2j

**Comment by michael-ring** [comment]
Nothing changed!??!! what did you want to do, make both embedded and freertos arm-none-eabi? If yes then you failed for embedded... I build the pico target and then manuall armv7em

**Comment by LongDirtyAnimAlf** [comment]
There are many issues and changes now. So, its not totally clear for the changes you were expecting to be implemented.
So, here's my request. Could you please state the changes you want(ed) to see as the next message in this issue ?
Thanks !

**Comment by michael-ring** [comment]
Same binutils should be used for embedded and freertos. prefered by both of us seems to be arm-none-eabi- but currently on mac/windows I see that always arm-embedded- is used so offort to switch arm-embedded- to arm-none-eabi- is likely higher because more binutils versions need to be renamed. for freertos (I guess) the effort would be less as likely only windows and mac verisons of binutils exist. So it it your choice which direction to go, but in the end I think it makes sense that all binutils for arm are either named  arm-embedded-* arm-none-eabi-*

**Comment by LongDirtyAnimAlf** [comment]
As all arm embedded binutils floating round on the Internet are also named arm-none-eabi- my preference would indeed be arm-none-eabi- for compatibility with custom binutils.

**Comment by michael-ring** [comment]
Here are the binutils/gdb builds for you to re-create your zipfiles:
http://temp.michael-ring.org/binutils_gdb-aarch64-darwin.zip
http://temp.michael-ring.org/binutils_gdb-x86_64-darwin.zip

for x86_64 there is also a gdb fix for debugging inside....

**Comment by michael-ring** [comment]
Looking good on x86_64-darwin
Looking good on aarch64-darwin
Looking good on win64

**Comment by LongDirtyAnimAlf** [comment]
Seen this ?
https://github.com/PicoCPP/RPI-pico-FreeRTOS

**Comment by michael-ring** [comment]
nice!

Haven't yet looked for something like this but the board has enough flash/ram to play nice with FreeRTOS.

When the basics of pico work good then freertos is next. I am not expecting too much surprises as long as only CPU0 gets used by freertos. But it is good to see that others are also working on this.

**Comment by michael-ring** [comment]
Fixed in latest release
