### ISSUE TITLE
Freshly compiled Lazarus complains about missing system.ppu

### ISSUE THREAD

**Issue by michael-ring** [LongDirtyAnimAlf/fpcupdeluxe#353]
After building all the crosscompilers I needed I now finally started lazarus for the first time, it complains about missing.ppu:
<img width="621" alt="Bildschirmfoto 2021-02-20 um 18 40 44" src="https://user-images.githubusercontent.com/6280531/108603986-76859580-73ab-11eb-9d5c-f06d827d48f9.png">

**Comment by michael-ring** [comment]
Here's my fpc.cfg
[fpc.cfg.txt](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/6015910/fpc.cfg.txt)

**Comment by LongDirtyAnimAlf** [comment]
Yep. Seen it. Also for arm64 so it seems.
Will look into this.
Perhaps needs a trick as with embedded.

**Comment by michael-ring** [comment]
I just updated to dfdb402 on my aarch64 darwin mac and build fpcupdeluxe from source, there I cannot reproduce the issue atm...

**Comment by michael-ring** [comment]
Retried again on darwin-x86_64, this time no issue, did not change the fpcupdeluxe version.

**Comment by LongDirtyAnimAlf** [comment]
Strange issue. Might be closed ?

**Comment by michael-ring** [comment]
Yeah, let's close it and reopen when this happens frequently....
