### ISSUE TITLE
Missing icons on bottom buttons

### ISSUE THREAD

**Issue by gcarreno** [LongDirtyAnimAlf/fpcupdeluxe#354]
Hey Don(@LongDirtyAnimAlf),

This seems quite odd. I've never had missing button icons before:
![fpcupdeluxe-missing-icons](https://user-images.githubusercontent.com/81799/108606531-76d55f00-73b2-11eb-82cd-7155fba8c0b1.png)

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
Well. Yes. This is strange !
You are on a Linux themed WM ?

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

> You are on a Linux themed WM ?

Ooops, my bad, forgot to mention my specs: Ubuntu 20.10 64b Dark theme

I'm not sure this relates, but I had a similar issue on [corona](https://github.com/wp-xyz/corona).
When I was doing release builds but instead of using the `corona.lpi` I copied it to `corona_release.lpi`, since I'm still coordinating with Werner(@wp-xyz) on how to apply Build Modes, a single image was missing: The app icon from the about form.
Once I was using the `corona.lpi` file, it magically reappears!!
Quite odd behaviour that I haven't tracked yet, since it happened yesterday, just before bed time.

It now slips my mind how you have your resources, but if I'm not mistaken, all in the `*.lfm`, right?

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
All in the *.lfm !

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

> All in the *.lfm !

Yeah, figures!!

So, under those premises, I'm as stunned as you.
It would make tons of sense that **ALL** the resources would fail on my particular issue, but noooo, just the one.

In your case, you're missing 2 and some text?
What I also feel is even stranger is that the OPM buttons is missing both the image and the text. Unless that's your intention, image but no text.

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
The OPM button is gone.
It has become an Ultibo button without text.
So no text is ok. Missing glyph is very strange error.

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

> The OPM button is gone.
> It has become an Ultibo button without text.

Then you should also change the Hint since it's saying: "Install the famous Online Package Manager".

And BTW, just FYI, both the Wio and Pico Hint state: "Get FPC for SAM embedded"

> So no text is ok. Missing glyph is very strange error.

Okydokes. I'll let you ponder on the possibilities. I know I'll dig into my copied `*.lpi` issue sometime.

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
![up](https://user-images.githubusercontent.com/10783972/108608338-9bd3cd00-73c6-11eb-99a9-49314cbd3376.JPG)

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

Under wine:
![fpcupdeluxe-wine-i386-win32](https://user-images.githubusercontent.com/81799/108608621-1d742c80-73c0-11eb-8388-05f12e28391e.png)

Funny enough, the hints on Wio and Pico now do not match those on `x86_64-linux`
- `x86_64-linux`
  - Wio Hint: Get FPC for SAM Embedded
  - Pico Hint: Get FPC for SAM Embedded
  - Ultibo Hint: Install the famous Online Package Manager
- `i386-win32`
  - Wio Hint: Get FPC for SAMD51 Embedded
  - Pico Hint: Get FPC for armv6m RPi Pico
  - Ultibo Hint: Install the famous Online Package Manager

Also, the button with the old guy with a cane has the wrong Hint.

Have you uploaded new version of binaries recently?
My `x86_64-linux` is dated: Thu 18 Feb 2021 13∶51∶20 GMT
My `i386-win32` is dated: Sat 20 Feb 2021 21∶06∶52 GMT

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
Good news: I am able to reproduce ! So, this will be solved.

![buttons](https://user-images.githubusercontent.com/10783972/108616370-1f181180-740d-11eb-9196-9e4279a4c7be.JPG)

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

> Good news: I am able to reproduce ! So, this will be solved.

That's awesome!!

I'm now quite curious, what was it?

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
Please test latest pre-release:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2j

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

Have you uploaded new binaries? Cuz, that's the one I've been testing as you can attest from the Screen Captures.

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

Sorry to insist, but I need an answer to this before I can report back and close the issue. Please?!

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
Yes, I have uploaded new binaries.

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

Thanks Don!!

I'll download, test, screen capture and report back in a moment.

Cheers,
Gus

**Comment by gcarreno** [comment]
Hi Don(@LongDirtyAnimAlf),

All clear my friend, as you can see:

- `i386-win32`
  
![fpcupdeluxe-button-icons-ok-win32](https://user-images.githubusercontent.com/81799/108909586-a4bddc00-761c-11eb-9449-2b3863938326.png)

- `x86_64-linux`
  
![fpcupdeluxe-button-icons-ok-linux64](https://user-images.githubusercontent.com/81799/108909702-c5863180-761c-11eb-927c-f3e26e596029.png)

- Hints all match and seem to be correct

Thanks Don!!

Please close at your leisure.

Cheers,
Gus
