### ISSUE TITLE
Web Service Toolkit - wst compile error

### ISSUE THREAD

**Issue by ertankucukoglu** [LongDirtyAnimAlf/fpcupdeluxe#357]
Hello,

I already shared log thru e-mail. I wanted to test wst for a possible project and could not install it on Windows 64Bit, Lazarus 64Bit version.

I am not sure about exact source where wst is downloaded. However, fpcupdeluxe seems to get 0.8 version. On the other hand 0.7 is the official release as to their web site.

I believe error is because of wst code and not fpcupdeluxe. So, I would like to try installing 0.7 release. Problem is I simply do not know how to do that or if it is even possible.

Any help is appreciated.

Relevant log lines:
```
(3104) Compiling C:\fpcupdeluxe\ccr\wst\type_lib_edtr\ufrmsaveoption.pas
(3104) Compiling C:\fpcupdeluxe\ccr\wst\type_lib_edtr\ueditoptions.pas
(3104) Compiling C:\fpcupdeluxe\ccr\wst\ws_helper\generatorj.pas
C:\fpcupdeluxe\ccr\wst\ide\lazarus\wst_design.pas(16,3) Fatal: (10022) Can't find unit parserdefs used by wst_design
Fatal: (1018) Compilation aborted
Error: C:\fpcupdeluxe\fpc\bin\x86_64-win64\ppcx64.exe returned an error exitcode
Error: (lazarus) Compile package wst_design 0.8: stopped with exit code 1
Error: (lazarus) [TLazPackageGraph.CompileRequiredPackages] "Exit code 1"
Error: (lazarus) Building IDE: Compile AutoInstall Packages failed.
make: *** [useride] Error 2

fpcupdeluxe: ERROR: UniversalInstaller (ConfigModule: wst): Failure trying to rebuild Lazarus. 
Details: 


ERROR: Fpcupdeluxe fatal error !
Sequencer (wst): Failure running fpcupdeluxe: error executing sequence wst
Sequencer (Only): Failure running fpcupdeluxe: error executing sequence Only
```

I have only below file in my system relevant to above error
![image](https://user-images.githubusercontent.com/14805520/108758479-3285c280-755c-11eb-93cb-8bd76c6910ae.png)

Thanks & Regards,
Ertan

**Comment by LongDirtyAnimAlf** [comment]
This might help.
https://forum.lazarus.freepascal.org/index.php/topic,39273.msg268984.html#msg268984

**Comment by ertankucukoglu** [comment]
So, My understanding, I am suggested to manually modify `wst_design.lpk` and `wst_global.inc`

My `wst_global.inc` file seems almost identical to above link. But, I could not see how I should modify `wst_design.lpk` file as it is now an XML file and includes are going in sequential XML tags like below
```
      <Item43>
        <Filename Value="..\..\ws_helper\metadata_generator.pas"/>
        <UnitName Value="metadata_generator"/>
      </Item43>
      <Item44>
        <Filename Value="..\..\ws_helper\parserdefs.pas"/>
        <UnitName Value="parserdefs"/>
      </Item44>
      <Item45>
        <Filename Value="..\..\ws_helper\parserutils.pas"/>
        <UnitName Value="parserutils"/>
      </Item45>
```
I just do not know if removing Item44 is just fine.

**Comment by LongDirtyAnimAlf** [comment]
You might want to test this pre-release. It will do the dirty wst-work for you !
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2n

**Comment by LongDirtyAnimAlf** [comment]
Closing. No feedback.
