### ISSUE TITLE
Add extra tools for embedded development

### ISSUE THREAD

**Issue by michael-ring** [LongDirtyAnimAlf/fpcupdeluxe#358]
I have now created a Release here:

https://github.com/michael-ring/develtools4fpc/releases/tag/v1.0.0-1

can you please check if I did everything correct for easy implementation in fpcupdeluxe?

The idea would be to install those tools when a cross-compiler is installed. Currently makes sense for arm-embedded arm-freertos avr-embedded targets.

This release is at the moment Darwin-only, releases for linux-x64 and windows-x86 will follow.

**Comment by LongDirtyAnimAlf** [comment]
Thanks. Implemented. Closing.
