### ISSUE TITLE
Installation of GDB is kind of inconsistent

### ISSUE THREAD

**Issue by michael-ring** [LongDirtyAnimAlf/fpcupdeluxe#359]
I have now installed my usual set of crosscompilers,

all arm-embedded, all freertos-embedded, tried avr and xtensa lx6.

```
./fpcsrc/packages/ide/fakegdb
./fpcbootstrap/gdb
./fpcbootstrap/gdb/xtensa-freertos/gdb
./fpcbootstrap/gdb/xtensa-freertos/xtensa-esp32-elf-gdb
./fpcbootstrap/gdb/arm-embedded/gdb
./fpcbootstrap/gdb/arm-embedded/arm-none-eabi-gdb
./fpcbootstrap/gdb/arm-freertos/gdb
./fpcbootstrap/gdb/arm-freertos/arm-none-eabi-gdb
./cross/bin/avr-embedded/avr-gdb
```

What I do not understand is why gdb's end up in fpcbootstrap, is there a reason for putting the files there and not leavong them in cross/bin/xxxx ?

Also, when compiling gdb I saw the intersting option that one gdb can support severalarchitectures, so how do you think of removing gdb from the core package and putting it in devtools4fpc? 

Also, I am done building gdb for windows, it will also need to come with a few dll's that have to either be in the path or in the current directory, will your copy step (when it survives) also copy the dll's?

**Comment by LongDirtyAnimAlf** [comment]
If you look into the settings of Lazarus, you will see that the path towards gdb has some magic. So Lazarus will auto-magically use the right debugger, dependend on os and cpu.

**Comment by michael-ring** [comment]
did not know that....
