### ISSUE TITLE
I have updated devtools4fpc but old files get installed

### ISSUE THREAD

**Issue by michael-ring** [LongDirtyAnimAlf/fpcupdeluxe#361]
I have now finally created devtools4fpc for linux, windows and mac but the new release does not get installed.
I also tried a fresh install of fpcupdeluxe in a new directory, but there the version 1.0.0-1 gets installed although I have released 1.0.1-1.

Also, can it work that devtools get reinstalled when the directory is deleted and then a crosscompiler is built (or rebuilt)?

One thing worth mentioning, I have simplified the directory structure, the x86_64-xxxx directories are gone.

**Comment by LongDirtyAnimAlf** [comment]
Great !

* but the new release does not get installed.
The installer must be changes to be able to get the latest release.
So, fpcupdeluxe must know what logic these releases will follow.
Or, some smart GitHub search must be used to find the latest release.
Don't know yet. How to know what is the latest release.

* Also, can it work that devtools get reinstalled when the directory is 
deleted and then a crosscompiler is built (or rebuilt)?
That must be a precise definition : when will or must the re-install 
happen.


------ Origineel bericht ------
Van: "Michael Ring" <notifications@github.com>
Aan: "LongDirtyAnimAlf/fpcupdeluxe" <fpcupdeluxe@noreply.github.com>
CC: "Subscribed" <subscribed@noreply.github.com>
Verzonden: 28-2-2021 11:49:04
Onderwerp: [LongDirtyAnimAlf/fpcupdeluxe] I have updated devtools4fpc 
but old files get installed (#361)

**Comment by LongDirtyAnimAlf** [comment]
Great !

* but the new release does not get installed.
The installer must be changes to be able to get the latest release.
So, fpcupdeluxe must know what logic these releases will follow.
Or, some smart GitHub search must be used to find the latest release.
Don't know yet. How to know what is the latest release.

* Also, can it work that devtools get reinstalled when the directory is deleted and then a crosscompiler is built (or rebuilt)?
That must be a precise definition : when will or must the re-install happen.

**Comment by michael-ring** [comment]
The github search should work, I have created increasing TAGs for the releases as with freertos-libs.

On definition:
In a perfect world the version of tools would be checked on each 'install compiler' and 'update all' call, and it should not matter if the core compiler is already there, a simple install/update of an (existing) subarch should trigger the check/install.
When there is no way to check versions then if the directory ccr/develtools4fpc does not exist it should be fetched on installUpdate of a subarch.

The develtools currently make sense for embeded arm+avr+mipsel and freertos arm. (Maybe midterm freertos  riscv32 will also become a usecase, I have a few of the new espressif chips on order, but this is not something for now) 

Which reminds me, if possible the same logic should be in place for the freertos libs in freertos targets, I will likely add the freertos libraries for pico in the next 1-2 weeks, they have to be a seperate build because Pi Foundation did not follow CMSIS rules for naming Interrupt handlers.

**Comment by michael-ring** [comment]
FYI, I have hacked the old release to use the new binaries, as a workaround this is ok.

**Comment by LongDirtyAnimAlf** [comment]
Latest commit should install newest version.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/fdea00ef38f60877604bf1c6e14e512442ac07d4
Please test.
Now, we have to find a way to implement the right configuration for Lazarus to use the new debugger.

**Comment by LongDirtyAnimAlf** [comment]
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2m

**Comment by michael-ring** [comment]
Did not work as expected.

The testcase I did was:

Use speedbutton to build pico in a fresh directory
build armv7em
checked that ccr/devtools4fpc exists
deleted devtools4fpc directory
build armv7em again
ccr directory still empty.

also exited restarted fpcupdeluxe and built armv7m --> same result directory does not exist

**Comment by LongDirtyAnimAlf** [comment]
This is the expected behavior. The tools only get installed when using the speed-button.
I try to maintain the principle of separation of responsibilities when programming.
So, a custom speedbutton can do anything. But choosing to install a cross-compiler will only install this cross-compiler.

That is why this discussion is important. We need to design a structured way to setup this whole toolchain. And add wiki info if needed.
I am willing to consider installing the tools together with the cross-compiler. But perhaps there is another way that also validates the separation of responsibilities. I dunno. Please tell me your ideas.

**Comment by michael-ring** [comment]
I understand your point, but the speedbuttons are not the best solution, because they do not apply to a user that cares for avr.
Also, rebuilding everything to update only the devtools feels wrong.
What about adding two buttons to extras, not exactly my favorite but a button 'refresh devtools4fpc' and 'refresh freertos libraries' could be an option, not sure how generic those buttons are.

Or are modules the answer to a better solution? there I see the option to install or uninstall. I see that mbf and mbf-freertos are there, could it be an option to use uninstall / install of a module and to created a devtools4fpc and freertoslibs module.

I never used modules, so please forgive my lack of knowledge for what they are used for.... I tried installing anchordocking via modules, but that crashed and burned so I never used that tab again.

**Comment by LongDirtyAnimAlf** [comment]
Modules are sources external to fpcupdeluxe. Many people use fpcupdeluxe for an install of FPC+Lazarus+LAMW, together with cross-compilers for Android development.
The install of devtools4fpc is also done through a module, although hidden.
And yes, I like the idea of extra buttons for avr/arm/xtensa embedded/freertos to handle the whole install and or refresh !

**Comment by LongDirtyAnimAlf** [comment]
I could make a single embedded speedbutton replacing the Wio and Pico button.
This button opens a subform with all kind of options for embedded.
Including cross-compiler, tools, libraries, whatever !

**Comment by michael-ring** [comment]
Just started thinking if we could solve two problems with one solution..... Brace for impact, some wild ideas coming next....

When a subarch gets installed ther could be a status file that says 'arm embedded armv7em' was installed. When then arm embedded armv7m gets installed a 2nd statusfile is created.
When freertos libs get installed or devtools4fpc gets installed same thing happens. So after a install there is a list of 'things that were installed by the user'.
What could happen next is that when there is an 'update' button and a dialog could pop up with a list of all modules that were installed by the user and the user can select which modules should get updated/rebuilt. This would mostly solve the issue of manually rebuilding crosscompilers when embedded-mir or trunk changes.

**Comment by michael-ring** [comment]
I am trying to think here from the support perspective, some user complains... My Wio has eaten my dog, what can I do?
You know very little of the environment so the first hint could be:
Hey, are you on latest, I know we fixed the issue that Wio eats cats, can you try if it also works for dogs..

Please hit the update button and make sure that you update your crosscompilers and freertos. When done, please come back to me.

**Comment by michael-ring** [comment]
I have another usecase from today which goes in a similar direction, I fixed a nasty issue with a missing segment missing in linker script for pico.

For others that means that they will have to rebuild the crosscompiler based on latest embedded-mir

The current solution is to rebuild fpc under basic so that the cloned version on disk is latest.
Then I thought next step is to 'remove compiler' an use 'install compiler' to rebuild the crosscompiler as it is not good enough to rebuild the rtl.

But that fails, I get the message:

fpcupdeluxe: WARNING: Skipping cross-compiler build step: seems to be up to date !!

likely because the svn revision has not changed because the changes I did were done on git.

solution was to delete ppcarm to force a rebuild of the crosscompiler.

I am writing this here because I think we need to look one step beyond the initial installation, the question is also how to handle changes on an existing install.

Currently I'd recommend to delete the complete fpcupdeluxe directory and to rebuild it from scratch because it is the easiest was to get to the expected result, but this is definitely not the best way to do things...

**Comment by LongDirtyAnimAlf** [comment]
> Currently I'd recommend a user to delete the complete fpcupdeluxe directory

The above advice is not good. We need to think of something else.

And yes, the rebuild only happens when revisions differ. Revisions change when sources change. If sources change without revision change, there is no way to track these changes.
Again, we need to think of something else. Perhaps a checksum of some kind.

**Comment by LongDirtyAnimAlf** [comment]
Two other possibilities.
1: A rebuild of FPC will always delete all cross-binaries.
2: If the filedate of FPC is newer than a cross-binary then rebuild cross-binary.

**Comment by michael-ring** [comment]
1: will likely create questions by the user because something unexpected will happen. For example user decides to refresh his lazarus and hits the FPC+Laz button. As a consequence his embedded code will not compile anymore.

2: looks to me like the better solution and I guess as a first step this is the way to go without making things a lot more complicated.

best solution would be that the whole process works automagically because FPCUPdeluxe knows all variants that the user has built and either does the update for those on it's own or shows the dialog I mentioned above to ask the user what to do next. I mostly think about the embedded target here, I have never done anything serious besides Embedded controllers with Lazarus so I do not know how much complexity level rises when you resolve dependencies and try to rebuild the user's environment when the fpc/lazarus code changes. 

So to keep things simple it feels like 2: and a little of docs on the wiki on how to solve the usecase will already help a lot, for all the rest it really depends on if doing more than this opens up a can of worms that will only make 0.1% of your userbase happy....

**Comment by LongDirtyAnimAlf** [comment]
Implemented 2. Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2m
The latest release will also detect all subarchs. And auto-update them when update all compilers is pressed.

**Comment by michael-ring** [comment]
Totally like it! This creates a workflow that is easy to explain.....
One case I did not test: What is the expected bahaviour when I have 3 subarchs installed and build of subarch 2 fails, will 'Update All'  continue or will is stop with an error (I think stopping with an error is slightly better....)

Now back to the main topic, how does updating the bin-tools and freertos libs fit in the picture?

**Comment by LongDirtyAnimAlf** [comment]
> What is the expected bahaviour when I have 3 subarchs installed and build of subarch 2 fails

The build will continue. But if that is preferred is another question.

> Now back to the main topic, how does updating the bin-tools and freertos libs fit in the picture?

Exactly. Dunno [yet]. 
At the moment, the libs can be deleted. And will be updated by fpcupdeluxe when building cross-compiler. That is ok by me.
The tools are hidden at the moment. I can unhide them. Then, a simple update of the tools-module will update the tools. Cannot be more simple. And fully user controlled.

**Comment by michael-ring** [comment]
That was also my thought, please un hide them and I will run a few tests...

**Comment by LongDirtyAnimAlf** [comment]
Unhidden. Module name: develtools4fpc.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2m

**Comment by LongDirtyAnimAlf** [comment]
Sorry. Made a small mistake. Will upload unhidden in a few moments.

**Comment by LongDirtyAnimAlf** [comment]
Now ok.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2m

**Comment by michael-ring** [comment]
looking good on Mac, will now test on Windows

**Comment by michael-ring** [comment]
Windows also worked nicely, closing issue....
