### ISSUE TITLE
Setup+ option to build with debug information

### ISSUE THREAD

**Issue by Bi0T1N** [LongDirtyAnimAlf/fpcupdeluxe#362]
Hello,
I thought it might be a good idea to provide a simple way to build FPC/Lazarus with debug information since I had to check several times which command line parameters are the right ones. Thus I thought a simple checkbox in the Setup+ window might be a good idea, especially if you're a normal user but faced e.g. a compiler error and to provide detailed information you've to build a debug version of the compiler.
Another idea that would allow different options than a simple 'debug checkbox' is a `TComboBox` way but then the window might need more changes as there is not much space around the 'Options Override'.
What's your opinion about it?

**Comment by LongDirtyAnimAlf** [comment]
Its a good idea.
Will think about a way to implement.
Keep you informed.

**Comment by LongDirtyAnimAlf** [comment]
Implemented. Setup+. Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2m

**Comment by Bi0T1N** [comment]
That was quick and it works fine here, thanks.
