### ISSUE TITLE
cross build to mipsel error(win10, lazarus 2.1.0, fpc 3.3.1)

### ISSUE THREAD

**Issue by lfyey121** [LongDirtyAnimAlf/fpcupdeluxe#364]
source:

program testCross;

{$mode objfpc}{$H+}

uses
  {$IFDEF UNIX}
  cthreads,
  {$ENDIF}
  {$IFDEF HASAMIGA}
  athreads,
  {$ENDIF}
  Interfaces, // this includes the LCL widgetset
  Forms, testMain
  { you can add units after this };

{$R *.res}

begin
  RequireDerivedFormResource:=True;
  Application.Title:='project1';
  Application.Scaled:=True;
  Application.Initialize;
  Application.CreateForm(TForm1, Form1);
  Application.Run;
end. 

![1615437169(1)](https://user-images.githubusercontent.com/11315122/110736145-1c6b4800-8266-11eb-8060-5efbd815213c.png)

Debug: D:\fpcupdeluxe2\cross\bin\mipsel-linux\mipsel-linux-gnu-ld.exe: D:\fpcupdeluxe2\cross\lib\mipsel-linux\\libpthread.so.0: error adding symbols: file in wrong format

**Comment by LongDirtyAnimAlf** [comment]
I have looked into this error and cannot solve. I do not have the mipsel libs available.
If you have them, please re-open and attach a zip containing these libs.
Thanks.
