### ISSUE TITLE
JCL package not compiling 

### ISSUE THREAD

**Issue by Tesla2k** [LongDirtyAnimAlf/fpcupdeluxe#365]
Hello,
I have installed Lazarus with fpcupdeluxe on Windows. The 32Bit Version. FPC and Lazarus both in the stable Version.
Afterwards I installed the JCL Module, but when I try to compile the Package in Lazarus I get the following errors:

```
JclStrings.pas(5393,10) Error: function header doesn't match the previous declaration "CompareNaturalStr(const AnsiString;const AnsiString):LongInt;"
JclStrings.pas(5398,10) Error: function header doesn't match the previous declaration "CompareNaturalText(const AnsiString;const AnsiString):LongInt;"
```

This is mentioned in [this](https://issuetracker.delphi-jedi.org/view.php?id=5454) bug report 
But the last entry is from 2013 and with the message, that there is a patch for this.

Can it be that fpcupdeluxe installs an old version or why is this issue still around?

**Comment by LongDirtyAnimAlf** [comment]
This is not a fpcupdeluxe issue, but a JCL issue.

The latest sources contain errors. These need to be resolved upstream.
Besides, JCL cannot be used out-of-the-box. It needs to be installed.

Have a look here.
https://github.com/LongDirtyAnimAlf/FPC-USB-HID/tree/master/jcl/jcl/source
https://github.com/LongDirtyAnimAlf/FPC-USB-HID/tree/master/jedi
https://github.com/LongDirtyAnimAlf/FPC-USB-HID/tree/master/jvcl/jvcl

Closing.

**Comment by LongDirtyAnimAlf** [comment]
Re-opening.
Will look into this issue again, due to the fact that, as you pointed out, old sources from a GitHub repo are used.

**Comment by LongDirtyAnimAlf** [comment]
I have looked into the latest jcl sources. These still contain many errors and are (at the moment) not compatible with FPC.
Again, as this is not related to fpcupdeluxe, I will close this issue.

**Comment by Tesla2k** [comment]
As of the comment [here](https://github.com/project-jedi/jcl/pull/41#issuecomment-512843672) JCL and JVCL are not supposed to support FPC and Lazarus.
Maybe you can add a short note in the description of the module, that it is not officially supported and may not work. So everybody is prewarned.
