### ISSUE TITLE
check on startup, that 'make' is installed in Linux/BSD/Solaris

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#367]
w/o 'make' installed, app cannot work, ie it cannot install FPC 3.2fixes. so why to wait until user presses btn? let's check 'make' on start.

I have clean Xubuntu.

**Comment by LongDirtyAnimAlf** [comment]
Will not be implemented.
While I agree that an earlier check might be better, the app will wait until real run before a check is made.
