### ISSUE TITLE
Warning msg about utils

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#370]
>fpcupdeluxe: WARNING: Make, binutils, subversion/svn [and gdb] are also required !!

- pls fix blurry part: `[and gdb]`. If Laz neeeds gdb then write `Make, binutils, subversion, gdb`. If gdb is optional, write `Make, binutils, subversion, gdb (optional)`
- pls write `Subversion/Git` instead of only subversion

**Comment by LongDirtyAnimAlf** [comment]
Done (more or less).
