### ISSUE TITLE
Can't build lazarus trunk + fpc trunk on Windows 64 bit

### ISSUE THREAD

**Issue by Imantsg** [LongDirtyAnimAlf/fpcupdeluxe#371]
I got this error while building lazarus + fpc
![2021-03-29](https://user-images.githubusercontent.com/11457410/112841909-b70eb800-90a9-11eb-9a59-181ec044d04a.png)

**Comment by LongDirtyAnimAlf** [comment]
Latest release might solve ([m]any) issues !!
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2p
Please test.

**Comment by LongDirtyAnimAlf** [comment]
Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2q

**Comment by Imantsg** [comment]
I tested with 1.8.2r and it works now
