### ISSUE TITLE
The online fpcupdeluxe logger shows no data

### ISSUE THREAD

**Issue by gcarreno** [LongDirtyAnimAlf/fpcupdeluxe#377]
Hey Don(@LongDirtyAnimAlf),

As of
```console
$ date
Tue 13 Apr 01:57:44 BST 2021
```

If we access https://www.batterybutcher.com:8843/root/getinfohtml, we get this:
![fpcupdeluxe-online-logger-html-empty](https://user-images.githubusercontent.com/81799/114480972-7cedfc00-9bfb-11eb-9139-6d036214e702.png)

If we access https://www.batterybutcher.com:8843/root/getinfojson we get and empty array: []

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
Confirmed. This (mORMot) database is running on an AWS instance. Need to look into.
Will keep this issue open until solved.

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

Thanks for the quick reply!

> Will keep this issue open until solved.

Okydokes, I'll leave it at your discretion.

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
Server is running again.
However.
Not much data is shown, due to the fact that it has not collected data since long !

**Comment by gcarreno** [comment]
That's okay. As long as it's running I guess it's ok.
