### ISSUE TITLE
fpcupdeluxe 1.8.2p stops abruptly with no apparent error

### ISSUE THREAD

**Issue by gcarreno** [LongDirtyAnimAlf/fpcupdeluxe#378]
Hey Don(@LongDirtyAnimAlf),

I've just downloaded v1.8.2.p and after pressing FPC button, it abruptly stops here:

```
...
/usr/bin/make -C x11 distclean
/usr/bin/make -C xforms distclean
/usr/bin/make -C zlib distclean
/usr/bin/make -C zorba distclean
/usr/bin/make -C fpmkunit clean_bootstrap
fpcupdeluxe: info: FPCNativeInstaller (CleanModule: FPC): Deleting some FPC package config files.
```

There's no error reported, it just exits.
It doesn't even get to the `svn update` part, odd, just quits on the `make clean` twice...

This is for FPC trunk at revision 49195
Ubuntu 20.10 64b (x86_64-linux)

Here's a zip of all the `*.ini` and the full log:
[fpcupdeluxe-v1.8.2p.error.zip](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/6308008/fpcupdeluxe-v1.8.2p.error.zip)

**EDIT1**: Just noticed this on the `TEdit` above the `TSynEdit`:
`fpcupdeluxe: Got an unexpected exception ... don't know what to do unfortunately.`

**EDIT2**: Just confirmed that v1.8.2n doesn't stop there and continues without any issues.

What do you think is causing this?

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
Thanks for testing. I will try to reproduce.

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

> Thanks for testing. [snip]

Quite welcome. That's what I'm here for :smile: 

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

Left a comment on commit 22f72bf saying it works now :)

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

OOOOPPSSS, spoke too soon!!

It was able to compile FPC but it hit another exception right after linking Lazarus for the first time.

A zip with log and `*.ini`:
[fpcupdeluxe-v1.8.2.q-lazarus-only.zip](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/6308547/fpcupdeluxe-v1.8.2.q-lazarus-only.zip)

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

From the looks of it commit f7ed0fe has solved both FPC and Lazarus Exceptions.
I'm closing this one.

Please reopen if need be.

Cheers,
Gus
