### ISSUE TITLE
The online fpcupdeluxe logger is running but seems to not collect any data

### ISSUE THREAD

**Issue by gcarreno** [LongDirtyAnimAlf/fpcupdeluxe#379]
Hey Don(@LongDirtyAnimAlf),

Sorry for pestering you with this again.(Couldn't re-open the previous issue)
If you think the online logger is not that important then just ignore me.

It seems that the server is running but somehow there is no collection of data, well, apart from that single entry that is missing a Country.

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
Should be fixed.
