### ISSUE TITLE
Is this error Lazarus related or fpcupdeluxe related?

### ISSUE THREAD

**Issue by gcarreno** [LongDirtyAnimAlf/fpcupdeluxe#380]
Hey Don(@LongDirtyAnimAlf),

Just stumbled upon this on revision 64997 of Lazarus:
```
(3104) Compiling /home/gcarreno/FreePascal/lazarus/debugger/frames/debugger_class_options.pas
/home/gcarreno/FreePascal/lazarus/debugger/frames/debugger_class_options.pas(647,27) Error: (5000) Identifier not found "lisDebugOptionsFrmEditClass"
/home/gcarreno/FreePascal/lazarus/debugger/frames/debugger_class_options.pas(648,33) Error: (5000) Identifier not found "lisDebugOptionsFrmEditClassWarn"
```

Should I wait for the Lazarus devs to find it, or is it related to fpcupdeluxe?

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
This is Lazarus related. Just be patient. They will find it in a few hours/days. Or else, report the bugger !

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

Yeah that was my suspicion. Just needed someone a bit more knowledgeable to confirm.

> They will find it in a few hours/days. Or else, report the bugger !

Yup, will monitor this and take appropriate action.

You now, the post script thing I suggested on #376 would be awesome to have while this thing hasn't been solved!!!

Cheers,
Gus
