### ISSUE TITLE
fpcupdeluxe and xtensa targets

### ISSUE THREAD

**Issue by michael-ring** [LongDirtyAnimAlf/fpcupdeluxe#381]
I started didding deeper into the xtensa-freertos target and realized that it does not work out of the box.

I am currently seeing the following issues:

fpc.cfg:

```
# begin fpcup do not remove xtensa-freertos
# Inserted by fpcup 21-4-21 09:25:07
# Cross compile settings dependent on both target OS and target CPU
#IFDEF FPC_CROSSCOMPILING
#IFDEF FREERTOS
#IFDEF CPUXTENSA
#IFDEF CPULX6
-Cfhard
-Fl/Users/ring/fpcupdeluxe/cross/lib/xtensa-freertos/lx6/
#ENDIF CPULX6
#IFDEF CPULX106
-Fl/Users/ring/fpcupdeluxe/cross/lib/xtensa-freertos/lx106/
#ENDIF CPULX106
```
wrong place
```
-FD/Users/ring/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/
-XPxtensa-esp32-elf-
-Wpesp32
-Fl/Users/ring/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/lib/
```

```
-Fu/Users/ring/fpcupdeluxe/fpc/units/xtensa-freertos/$FPCSUBARCH/rtl
-Fu/Users/ring/fpcupdeluxe/fpc/units/xtensa-freertos/$FPCSUBARCH/packages
#ENDIF CPUXTENSA
#ENDIF FREERTOS
#ENDIF FPC_CROSSCOMPILING
# end fpcup do not remove

```
the entries in bold are in the wrong place, they are esp32 specific so they should be within the
#IFDEF CPULX6
define

It will also likely be necessary to update the libs to be in sync with latest version of

https://github.com/ccrause/fpc-esp-freertos/

I will update this issue with new findings, no need to act on your side atm, I will add a comment when I think I have found all qwirks.

**Comment by michael-ring** [comment]
This should be the correct setting:
```
#IFDEF CPUXTENSA
#IFDEF CPULX6
-Cfhard
-Fl/Users/ring/fpcupdeluxe/cross/lib/xtensa-freertos/lx6/
-Fl/Users/ring/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/lib/
-FD/Users/ring/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/
-XPxtensa-esp32-elf-
-Wpesp32
#ENDIF CPULX6
#IFDEF CPULX106
-Fl/Users/ring/fpcupdeluxe/cross/lib/xtensa-freertos/lx106/
-Fl/Users/ring/.espressif/tools/xtensa-lx106-elf/esp-2020r3-49-gd5524c1-8.4.0/xtensa-lx106-elf/lib/
-FD/Users/ring/.espressif/tools/xtensa-lx106-elf/esp-2020r3-49-gd5524c1-8.4.0/xtensa-lx106-elf/bin/
-XPxtensa-lx106-elf-
-Wpesp8266
#ENDIF CPULX106
-Fu/Users/ring/fpcupdeluxe/fpc/units/xtensa-freertos/$FPCSUBARCH/rtl
-Fu/Users/ring/fpcupdeluxe/fpc/units/xtensa-freertos/$FPCSUBARCH/packages
#ENDIF CPUXTENSA
```

**Comment by michael-ring** [comment]
Not sure if you can find out value for -Ff (likely not), in that case user has to set it manually, preferably in the subarch dialog

**Comment by michael-ring** [comment]
libstdc++.a is missing in the cross package for lx106, it is available for esp32:
```
find ~/fpcupdeluxe -name libstdc++.a                                                                                                                                               
/Users/ring/fpcupdeluxe/cross/lib/xtensa-freertos/lx6/libstdc++.a
```

**Comment by michael-ring** [comment]
Building crosscompiler fails when there is only lx106 installed, cannot find crossbinutils. I have to rename lx106 tools to xtensa-esp32-elf-* to make building cross compiler word

**Comment by michael-ring** [comment]
based on crossbin tools for linux I configured directory structure for lx106, currently main problem is that there is no differentiation between lx106 and lx6 so sdks will likely clash when both are installed.

**Comment by michael-ring** [comment]
Things are now ready....

I have created a release here:

https://github.com/michael-ring/espsdk4fpc/releases

and have provided binutils,sdk and prebuilt libs for esp32 and esp8266.

Please let me know if I should organize the files in any different way.

The fix on fpcupdeluxe side that is then still needed is that fpc.cfg is not created properly (see above) and that for lx106 (esp8266) build the wrong binutils are used (esp32 instead of lx106)

We then do not need esp-idf sdk anymore, installing fpcupdeluxe is enough for esp on linux & mac (windows fpc does not support esp targets at all)

**Comment by michael-ring** [comment]
Wow, hard to believe that I create this in April, time flies......

Do you think you can implement this?

**Comment by LongDirtyAnimAlf** [comment]
Please try.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.2.0a

**Comment by michael-ring** [comment]
Tried and works.... Still have to check again with Christo's ESP32 Repository.
One Hint: Corrently there is nothing extensa specific in embedded on github so your esp32 button should better set trunk as fpc release for building.
Many thanks for integrating this!

Michael
