### ISSUE TITLE
UI buttons issue

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#382]
Lower row of buttons have different distances (by x) between buttons-- small, middle, big. I suggest to make only 1 value.
macOS-x64

**Comment by LongDirtyAnimAlf** [comment]
Related ?
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/issues/390

**Comment by Alexey-T** [comment]
yes, the same
