### ISSUE TITLE
Cannot install on Apple Silicon M1 MacBook Air 

### ISSUE THREAD

**Issue by acaland-uni** [LongDirtyAnimAlf/fpcupdeluxe#384]
Hello,
I am downloaded the latest `fpcupdeluxe-aarch64-darwin-cocoa` release but as soon as I launch the app I got the following error:

`The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10826 "kLSNoLaunchPermissionErr: User doesn't have permission to launch the app (managed networks)" UserInfo={_LSFunction=_LSLaunchWithRunningboard, _LSLine=2508, NSUnderlyingError=0x12cf2a9a0 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x12cf2b120 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed with error: 153}}}}}`

I have tried both to update permissions recursively (755) and removed the apple quarantine flag, but none of them solved the problem. I have also noticed there is no icon included in the package.

**Comment by nop-code** [comment]
Same here, no luck with chmod, quarantine-flag, whatsoever.
Re-signing the app with an ad-hoc signature worked for me though:
`sudo codesign --force --deep --sign - /Applications/fpcupdeluxe-aarch64-darwin-cocoa.app`

**Comment by LongDirtyAnimAlf** [comment]
I do not own a Mac. All work is done on Windows, with a Mac 10.15 VM.
So, I cannot codesign myself.
However, I got some help by a very friendly user (he gave me access to his Apple credentials), but this signing still needs some finetuning. I will keep this issue open until more news.

**Comment by LongDirtyAnimAlf** [comment]
Should all be solved.
Don't forget to do a attr -c fpcupdeluxe-aarch64-darwin-cocoa.app
