### ISSUE TITLE
Huge Memory use and infinite waiting when compiling help files in linux

### ISSUE THREAD

**Issue by cpicanco** [LongDirtyAnimAlf/fpcupdeluxe#386]
Hi @LongDirtyAnimAlf ,

I think I found a bug, I send an email of the log in the second run of a FPC+LAZARUS trunk install (with "build help files" Check Box checked in the setup). Without this checkbox, a first installation was successful.

Please take a look at the time passed and memory used:

![fpcupdeluxe_memory](https://user-images.githubusercontent.com/6511849/118741482-b6caa780-b824-11eb-884f-6d9127473f5d.png)

**Comment by LongDirtyAnimAlf** [comment]
Please provide me with more info.
CPU.
OS.
Up-version.

**Comment by cpicanco** [comment]
![fpcupdeluxe_memory_2](https://user-images.githubusercontent.com/6511849/118758751-053c6e00-b846-11eb-83a1-702922fe06f4.png)

**Comment by cpicanco** [comment]
The istro is BunsenLabs Lithium (a Debian based one).

**Comment by cpicanco** [comment]
Installing the stable version with the last version of fpcupdelux was ok! Maybe is that a trunk only problem??

**Comment by cpicanco** [comment]
Stale
