### ISSUE TITLE
Webassembly crosscompiler

### ISSUE THREAD

**Issue by tondrej** [LongDirtyAnimAlf/fpcupdeluxe#387]
Hi, first of all I'd like to thank you for this tool and your work on this project! It really makes it easy and quick to install/update my development environment  - it's really a great time saver - much appreciated!

Would it be possible to add [Webassembly](https://wiki.freepascal.org/WebAssembly/Compiler) cross-compilers (WASI/embedded)?

Thank you!

**Comment by LongDirtyAnimAlf** [comment]
Will have a look !

**Comment by LongDirtyAnimAlf** [comment]
I have had a look. And in need of some feedback.

As fpcupdeluxe cannot use custom installs of tools, I have tried to use the tools from here:
https://github.com/WebAssembly/wasi-sdk/releases
These releases to not contain the llvm-mc assembler. So I have tried to use clang to assemble as described by the webassembly tools for using c.

However, FPC adds some options that are not compatible with clang.
If I remove these options, the cross-compiler successfully builds, together with a few ported rtl units. ! 
So, success. But not 100%.

See agllvmmc.pas :
//asmcmd : '--assemble --arch=wasm32 -mattr=+sign-ext --filetype=obj -o $OBJ $EXTRAOPT $ASM';
asmcmd : '--assemble -o $OBJ $EXTRAOPT $ASM';

As the official tools do not contain llvm-mc, I am unsure on how to proceed.
Would it be possible to define a custom assembler for wabi ?
And tell FPC to use clang from the "official" SDK as assembler ?

Thanks for feedback.

**Comment by tondrej** [comment]
As they mention LLVM 11 in the [prerequisites](https://wiki.freepascal.org/WebAssembly/Compiler#Prerequisites) I've tried (on Debian Buster) installing llvm-11 and clang-11 and created symlinks in /usr/local/bin so that FPC finds those two tools, I've prefixed the links with 'wasm32-wasi-' and 'wasm32-embedded-' for each.

`make all OS_TARGET=wasi CPU_TARGET=wasm32 OPT="-O-" PP={fpc.sh from fpcupdeluxe build of fpc 3.2.2}
`

then works and produces a cross-compiler which I can use to compile/link a .pas unit (no classes) to produce a .wasm binary.

`OS_TARGET=embedded`

fails on rebuilding rtl-extra package but the units compiled until that point are enough to cross-compile a .pas unit (again, no classes) to a .wasm binary (targetting wasm32-embedded).

This is as far as I've got. I think I lack the expertise required to be of any help here, sorry.

**Comment by LongDirtyAnimAlf** [comment]
Please try:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2u

**Comment by tondrej** [comment]
Thank you very much for such a swift response!

I'm using fpcupdeluxe built from latest source code. Both cross-compilers are installed without errors (I've tried on Debian Linux earlier and now on Windows). A quick test compiles a basic .pas unit to wasm (embedded) without a problem, compiling for wasi fails with an error:
(using Windows right now)
```
C:\code\test\fpc-wasm>C:\fpcup-trunk\fpc\bin\i386-win32\fpc.exe -Twasi -Pwasm32 lib.pas
Free Pascal Compiler version 3.3.1-r49425 [2021/06/01] for wasm32
Copyright (c) 1993-2021 by Florian Klaempfl and others
Target OS: The WebAssembly System Interface (WASI)
Compiling lib.pas
Assembling lib
wasm-ld C:\fpcup-trunk\fpc\units\wasm32-wasi\rtl\system.o lib.o C:\fpcup-trunk\fpc\units\wasm32-wasi\rtl\si_prc.o   $MAP -o lib.wasm --export-dynamic --no-entry --allow-undefined --strip-all
wasm-ld: error: cannot open $MAP: no such file or directory
Error: Error while linking
Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted
Error: C:\fpcup-trunk\fpc\bin\i386-win32\ppcrosswasm32.exe returned an error exitcode
```
Same error on Debian. Any idea where the $MAP identifier comes from and how to fix this?
Cheers!

**Comment by LongDirtyAnimAlf** [comment]
Please report to me if this error is still happening with the latest releases of fpcupdeluxe, FPC and Lazarus.
Thanks.

**Comment by LongDirtyAnimAlf** [comment]
Closing due to no feedback.
Please re-open when needed.
