### ISSUE TITLE
1.8.2t Fails to install RasPi-Pico

### ISSUE THREAD

**Issue by oliverhbailey** [LongDirtyAnimAlf/fpcupdeluxe#388]
Using the latest trunk and following the instructions on the Lazarus Wiki, the Pico FPC compiler fails to install. The embedded tools have been successfully installed however.

**Comment by LongDirtyAnimAlf** [comment]
Would you mind telling me your OS and CPU ?

**Comment by oliverhbailey** [comment]
Hi Don,

Windows 10 updated last week. Dell Inspirion 7550, i7 Quad core, 8 threads,
16 GB RAM, 2 TB hard drive.

**Comment by oliverhbailey** [comment]
Hi Don,
It works as described on Debian 10, Mint, and Manjaro (all latest releases.
I also tried it on a prior Windows 10 update and it works. So this seems to
be related to Windows 10 current update. Not uncommon - Mono and C# are
just about non-functional right now.

I wanted to let you know it does work, just not on the latest Windows
release.

Take care,
Oliver

**Comment by LongDirtyAnimAlf** [comment]
Closing.
Please re-open when needed.
