### ISSUE TITLE
problems with "fpcupdeluxe-x86_64-linux" 

### ISSUE THREAD

**Issue by Aro-de** [LongDirtyAnimAlf/fpcupdeluxe#389]
Hello,

I'm having major problems with the fpcupdeluxe program.

The version release v1.8.2t of fpcupdeluxe - "fpcupdeluxe-x86_64-linux" does not work correctly for me.

Also "Source code (zip)" unpacked and started under Lazarus Version 2.0.0 + dfsg-2 FPC - version 3.0.4

brings exactly the same result!

The selection trunk, fixes or stable makes no difference.

The error: The subdirectory / fpc is created.
No further subdirectories are created.
The new directory / fpc remains empty!

"Building module FPC" expects files in the directory that do not exist and returns false as the result.

**Comment by LongDirtyAnimAlf** [comment]
Thanks for the report. I need more info.
* directory that you choose to install
*  linux type (OS name)
* a copy of the output screen after the error

**Comment by Aro-de** [comment]
Deepin - Version 20.2 - 64 Bit - Kernel 5.10.18 - amd64 Desktop
CPU: Intel(R) Core(TM) i3-7100U 2.40 GHz 4GB RAM

The attempt in different directories brought no change.
Everyone has unrestricted access to the directory.

Output after program start :
 
Welcome @ FPCUPdeluxe.
FPCUPdeluxe V1.8.2t for x86_64-linux-gtk2
Running on Deepin
CPU cores used: 4
Available physical memory: 3834 MB
Available swap: 6143 MB

Current install drectory: /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t

Got settings from install directory


Output after instal Button :

Going to install/update FPC and Lazarus with given options.
FPCUP(deluxe) is starting up.

FPCupdeluxe basedir:       /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t
Bootstrap dir:             /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/fpcbootstrap

FPC URL:                   https://svn.freepascal.org/svn/fpc/tags/release_3_2_2
FPC source directory:      /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/fpcsrc
FPC install directory:     /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/fpc
FPC options:               

Lazarus URL:               https://svn.freepascal.org/svn/lazarus/tags/lazarus_2_0_12
Lazarus source directory:  /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/lazarus
Lazarus install directory: /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/lazarus
Lazarus options:           -g -gl -O1

Please stand back and enjoy !

31-5-21 13:36:50: fpcupdeluxe: V336 (20210521) started.
FPCUPdeluxe V1.8.2t for x86_64-linux running on Deepin

Checking dev-libs for: gtk2
fpcupdeluxe: debug: FPCNativeInstaller (CleanModule: FPC): Entering ...
fpcupdeluxe: info: FPCNativeInstaller (CleanModule: FPC): No FPC source directory (/media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/fpcsrc) found [yet] ... nothing to be done
Found valid as application.
Found valid gunzip application.
Found valid tar application.
Found valid make application.
fpcupdeluxe: debug: FPCNativeInstaller (SetPath): Set path to: /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/fpc/bin/x86_64-linux:/media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/fpcbootstrap:/media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/fpc:/media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/fpc/bin:/media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/fpc/utils:/media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/fpcsrc:/media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/fpcsrc/compiler:/media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/fpcsrc/utils:/bin:/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/snap/bin
fpcupdeluxe: debug: FPCNativeInstaller (CheckModule: FPC): Entering ...
fpcupdeluxe: debug: FPCNativeInstaller (GetModule: FPC): Entering ...
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): Start checkout/update of FPC sources.
fpcupdeluxe: WARNING: FPCNativeInstaller (DownloadFromSVN: FPC): svn is needed, but cannot be found on the system !!
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC is at revision: 49371
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): No updates for FPC found.
fpcupdeluxe: WARNING: FPCNativeInstaller (GetModule: FPC): Going to patch FPC sources !!
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): Trying to patch FPC with /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/patchfpc/darwinmakefile.patch
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC has been patched successfully with /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/patchfpc/darwinmakefile.patch.
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): Trying to patch FPC with /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/patchfpc/fpc302rtti.patch
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC has been patched successfully with /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/patchfpc/fpc302rtti.patch.
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): Trying to patch FPC with /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/patchfpc/openbsd302.patch
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC has been patched successfully with /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/patchfpc/openbsd302.patch.
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): Trying to patch FPC with /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/patchfpc/openbsdtrunk.patch
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC has been patched successfully with /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/patchfpc/openbsdtrunk.patch.
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): Trying to patch FPC with /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/patchfpc/solaris.patch
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC has been patched successfully with /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/patchfpc/solaris.patch.
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): Trying to patch FPC with /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/patchfpc/netbsdfixes.patch
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC has been patched successfully with /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/patchfpc/netbsdfixes.patch.
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): Trying to patch FPC with /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/patchfpc/pas2js.patch
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC has been patched successfully with /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/patchfpc/pas2js.patch.
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): Trying to patch FPC with /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/patchfpc/openssl.patch
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC has been patched successfully with /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/patchfpc/openssl.patch.
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): Trying to patch FPC with /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/patchfpc/fpc300rtti.patch
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC has been patched successfully with /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/patchfpc/fpc300rtti.patch.
fpcupdeluxe: debug: FPCNativeInstaller (BuildModule: FPC): Entering ...
fpcupdeluxe: info: FPCNativeInstaller (BuildModule: FPC): Building module FPC...
fpcupdeluxe: ERROR: FPCNativeInstaller (BuildModule: FPC): /media/aro/_dde_data/home/aro/LazProject/fpcupdeluxe-1.8.2t/fpcsrc/Makefile not found. Severe error. Should not happen. Aborting.
fpcupdeluxe: ERROR: Sequencer (FPC): Failure running fpcupdeluxe: error executing sequence FPC; instr: SMbuildmodule; line: 6, param: FPC

fpcupdeluxe: ERROR: Sequencer (Default): Failure running fpcupdeluxe: error executing sequence Default; instr: SMdo; line: 3, param: FPC

ERROR: Fpcupdeluxe fatal error !
Sequencer (FPC): Failure running fpcupdeluxe: error executing sequence FPC
Sequencer (Default): Failure running fpcupdeluxe: error executing sequence Default

**Comment by LongDirtyAnimAlf** [comment]
Deluxe complains that svn is not available on your system. Please install it (subversion), cleanup the install-directory, and run up again.

**Comment by Aro-de** [comment]
Thank you very much.
That helped.
