### ISSUE TITLE
not equal spacing between UI buttons, 1.8.2t

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#390]
![delx](https://user-images.githubusercontent.com/4154978/121424755-5ee21500-c97a-11eb-97c8-08c21710a826.png)

**Comment by LongDirtyAnimAlf** [comment]
Please test. New binaries.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2u
