### ISSUE TITLE
cross compile and glibc 2.19 version

### ISSUE THREAD

**Issue by RDL-28** [LongDirtyAnimAlf/fpcupdeluxe#392]
Hello.
My system has glibc 2.19 (debian 8 jessie)
Your compilation binaries "CrossBinsLinuxi386.zip" and "CrossLibsLinuxi386.zip" are made with glib 2.27.

So I am getting the error:
/home/administrator/lazarus/cross/bin/i386-linux/i386-linux-ld: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /home/administrator/lazarus/cross/bin/i386-linux/i386-linux-ld)

Can you please help me get the binaries for glibc 2.19?

**Comment by LongDirtyAnimAlf** [comment]
It should be possible to install the jessie multilib versions of libc, gcc and binutils on your system.

**Comment by RDL-28** [comment]
I have installed these libraries, but I am not sure what to do next. How do I link them to fpcudeluxe_lazarus?

**Comment by LongDirtyAnimAlf** [comment]
Is this issue still valid with the latest release of fpcupdeluxe ?
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.0.1a
