### ISSUE TITLE
What is the best way to change the URL for the Sources?

### ISSUE THREAD

**Issue by mdbs99** [LongDirtyAnimAlf/fpcupdeluxe#397]
I've installed Lazarus from `fixes` source option, which means `branches/fixes_2_0`.
Now I would like to update the sources using `2.1.0`, which means `trunk`, but when I tried to update I got this error:
```[Window Title]
URL mismatch error

[Content]
Fpcupdeluxe encountered a (fatal) URL error.
Most common cause: overwtiting an existing install.
Sources with different URL cannot be installed in same directory.
Please select an new install directory when changing versions.
```
Either fpcupdeluxe has an option to change it (nowadays, using a new version) or can I do this manually editing some file?

If the UI continues not allowing this change, maybe it is a better idea disable those options once it was already installed...

Thanks.

**Comment by LongDirtyAnimAlf** [comment]
In Setup+ you can enable the URL switch by checking the appropriate checkbox.
However, this does not work well. I experience many errors when switching.

Besides.

Lazarus is changing towards Gitlab. This will make switching VERY easy !!

However.
Updating (switching) Lazarus might still result in errors due to incompatibilities between versions !

**Comment by mdbs99** [comment]
> Updating (switching) Lazarus might still result in errors due to incompatibilities between versions !

Maybe we can switching just forward without errors?
In my case, I want go forward to the `trunk` and it would be nice if it's allowed. But if the user wants to go back in branches, it's up to them take this risc — fpcupdeluxe can just show a warning message and that might be enough.

What do you think?

**Comment by LongDirtyAnimAlf** [comment]
Again. Changes of breaking when switching versions are huge.
Again. The new gitlab repo make switching so easy that even fpcupdeluxe cannot prevent it anymore !
So please have some patience. Version-switching will be very easy when gitlab is online.
And there is nothing I can do to prevent this ... :-)

**Comment by mdbs99** [comment]
@LongDirtyAnimAlf that's Ok!
I'm Ok. I can wait, of course. We always can download from a new branch and replace the configuration files, copying from the version that have all components installed.
I'll close that issue. Thanks.
