### ISSUE TITLE
Trouble compiling recent FPC/Lazarus on macOS 10.11.6

### ISSUE THREAD

**Issue by elder-n00b** [LongDirtyAnimAlf/fpcupdeluxe#399]
I am having trouble compiling a recent FPC/Lazarus on macOS 10.11.6. I have tried this:

FPC 3.0.4 + Lazarus 1.8.4 -- were installed before, and no problem recompiling them again, 1.8.5 is OK too

FPC 3.2.0 (`release_3_2_0`) -- compiles

FPC 3.2.0 (`release_3_2_0`) + Lazarus 1.8.4 (`lazarus_1_8_4`) -- fails with:<details>
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C tools
/Applications/Xcode.app/Contents/Developer/usr/bin/make --assume-new=lazres.pp lazres
/Users/username/Applications/fpcup/fpc/bin/x86_64-darwin/fpc.sh -gl -gw -Fu. -Fu../components/lazutils/lib/x86_64-darwin -Fu../lcl/units/x86_64-darwin -Fu../lcl/units/x86_64-darwin/nogui -Fu/Users/username/Applications/fpcup/fpcsrc/rtl -FE. -FU. -vw-n-h-l-d-u-t-p-c- -g -gl -dx86_64 lazres.pp
Target OS: Darwin for x86_64
Compiling lazres.pp
Linking ./lazres
ld: unexpected token: !tapi-tbd-v2 file '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib//libiconv.tbd' for architecture x86_64
make[1]: *** [all] Error 2
make: *** [lazbuild] Error 2
An error occurred while linking 
Error: Error while linking
Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted
Error: /Users/username/Applications/fpcup/fpc/bin/x86_64-darwin/ppcx64 returned an error exitcode
fpcupdeluxe: ERROR: LazarusNativeInstaller (BuildModuleCustom: Lazbuild): make returned exit status #512


ERROR: Fpcupdeluxe fatal error !
Sequencer (UserIDE): Failure running fpcupdeluxe: error executing sequence UserIDE
Sequencer (Lazarus): Failure running fpcupdeluxe: error executing sequence Lazarus
Sequencer (Only): Failure running fpcupdeluxe: error executing sequence Only
```
</details>

FPC 3.2.0 (`release_3_2_0`) + Lazarus 2.0.0 (`lazarus_2_0_0`) -- fails as above

FPC 3.2.x +  Lazarus 2.2.x (both the `fixes` branches) -- fails with:<details>
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make echotime
/Users/username/Applications/fpcup/fpcsrc/compiler/ppc2.tmp: invalid or unsupported format for signature
/Users/username/Applications/fpcup/fpcsrc/compiler/ppc3.tmp: invalid or unsupported format for signature
Start now 10:11:11
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate: can't write output file: /Users/username/Applications/fpcup/fpcsrc/compiler/ppc3.tmp.cstemp (Invalid argument)
ppc3.tmp: the codesign_allocate helper tool cannot be found or used
make[1]: *** [compiler_cycle] Error 2
make: *** [build-stamp.x86_64-darwin] Error 2

fpcupdeluxe: ERROR: FPCNativeInstaller (CleanModule: FPC): Error running /usr/bin/make for FPC failed with exit code 512
. Details: 


ERROR: Fpcupdeluxe fatal error !
Sequencer (FPC): Failure running fpcupdeluxe: error executing sequence FPC
Sequencer (Default): Failure running fpcupdeluxe: error executing sequence Default
```
</details>

FPC 3.2.2 (`release_3_2_2`) + Lazarus 2.0.12 (`lazarus_2_0_12`, i.e. both `stable`) -- fails with:<details>
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make echotime
/Users/username/Applications/fpcup/fpcsrc/compiler/ppc2.tmp: invalid or unsupported format for signature
/Users/username/Applications/fpcup/fpcsrc/compiler/ppc3.tmp: invalid or unsupported format for signature
Start now 13:06:37
ppc3.tmp: invalid or unsupported format for signature
make[1]: *** [compiler_cycle] Error 2
make: *** [build-stamp.x86_64-darwin] Error 2

fpcupdeluxe: ERROR: FPCNativeInstaller (CleanModule: FPC): Error running /usr/bin/make for FPC failed with exit code 512
. Details: 


ERROR: Fpcupdeluxe fatal error !
Sequencer (FPC): Failure running fpcupdeluxe: error executing sequence FPC
Sequencer (Default): Failure running fpcupdeluxe: error executing sequence Default
```
</details>

I tried to compile Lazarus 1.9 but got a weird error `Could not download file with URL ftp://ftp.freepascal.org/pub/lazarus/snapshots/lazarus-1.9.0-58999-20180915-src.zip/`. The URL is good without the trailing slash.

I noticed that the binary download page directs to use the 32 bit build on older (< 10.12) macs. 
So I tried setting "i386/darwin" in "setup+" but got the same results. 

On a side note, I ended up with 3 pairs of `Lazarus_fpcup` and `Lazarus_fpcupdeluxe` (in `/Applications`, `/Users/username`, and `/Users/username/Desktop`) plus a `Lazarus.app` alias also in `Desktop`, in addition to `startlazarus` and `startlazarus.app` in the Lazarus folder, and I'm a bit confused.

---
macOS 10.11.6 
Xcode 7.3.1
fpcupdeluxe: V1.8.2z 
```
27-7-21 10:04:32: fpcupdeluxe: V344 (20210726) started.
FPCUPdeluxe V1.8.2z for x86_64-darwin running on Mac OS X 10.11.6
```

**Comment by LongDirtyAnimAlf** [comment]
Seems to me that this problem is not related to fpcupdeluxe.
I would like to advice you to try the official downloads for your Mac. These might work better !
And please check/review your XCode version.
Besided.
I do not have a Mac. Only a VM running OSX 11. So, unless somebody gives me a VMDK for an older version of OSX I cannot imagine being able to solve this issue.

**Comment by LongDirtyAnimAlf** [comment]
![Capture](https://user-images.githubusercontent.com/10783972/127274039-bccb1567-512c-4d42-b313-9d63d9effb17.PNG)

**Comment by elder-n00b** [comment]
Indeed the compilation problems do not seem related to fpcupdeluxe, perhaps I asked in the wrong place.
I guess I close the issue, thanks for support.
