### ISSUE TITLE
FPC Linking Problem

### ISSUE THREAD

**Issue by Snify89** [LongDirtyAnimAlf/fpcupdeluxe#400]
Hello,

I have used fpcupdeluxe for X86_64 (Linux) and successfully installed Lazarus with FPC.
Compiling works just great on my linux machine (X64).
I would like to cross compile to i386 (X86 Linux), so I used fpcupdeluxe again.
Everything went well so far. However the linking process doesn't work and I get this error:

Error: /home/myuser/fpcupdeluxe_fix/cross/bin/i386-linux/i386-linux-ld: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /home/myuser/fpcupdeluxe_fix/cross/bin/i386-linux/i386-linux-ld)

Is there any way to make this work?

Thank you very much for your help in advance!

PS.: My Linux System is openSuse Leap 42.3

**Comment by LongDirtyAnimAlf** [comment]
Well.
Linking a 32bit binary with a lib64 glibc will definitely not work.
Question: did you install the multilibs needed to cross-compile or run apps for i386 on your system ?

**Comment by Snify89** [comment]
> cross-compile or run apps

Thank you for the reply. I really appreciate this. 
I have installed the latest FPC and Lazarus.
Then I used the cross installation i386 for linux to the same path. 
FPCUPdeluxe then downloaded and installed some libs and bins to the "cross" folder.
(linuxx64crossbins_v1.1/CrossBinsLinuxi386.zip & crosslibs_v1.2/CrossLibsLinuxi386.zip)

I haven't done anything else yet. 
What would be the next step?

Thank you in advance for your help.

**Comment by LongDirtyAnimAlf** [comment]
Thats good info. Thanks.
If the libs are downloaded, fpcupdeluxe should use them ! If not, this might be a up-bugger.
I will investigate.

**Comment by Snify89** [comment]
> 
> 
> Thats good info. Thanks.
> If the libs are downloaded, fpcupdeluxe should use them ! If not, this might be a up-bugger.
> I will investigate.

Alright. Thank you for your time! 
If you need any further information, let me know. 
Maybe my Linux is missing some stuff that I need to install (with YaST2) ...

I am really not that advanced with Linux, but I am always trying my best and learn something new every day :)

**Comment by Snify89** [comment]
I have attached my fpc.cfg file.
The file is located at /home/mzuser/fpcupdeluxe_fix/fpc/bin/x86_64-linux

[fpc.txt](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/6891998/fpc.txt)

Maybe this helps. Thank you again for investigating.

**Comment by LongDirtyAnimAlf** [comment]
What happens if you add this into the custom options of your project ?
`-FL/home/myuser/fpcupdeluxe_fix/cross/lib/i386-linux/ld-linux.so.2`

**Comment by Snify89** [comment]
Thank you for coming back to me on this.
I have already tried to add the path to the Libraries (-FL), but the same error occurs...
In fact, the -FL parameter should point to a directory, not a file?!

`WARNING: library search path does not exist: /home/myuser/fpcupdeluxe_fix/cross/lib/i386-linux/ld-linux.so.2
HINT: using config file /home/myuser/fpcupdeluxe_fix/fpc/bin/x86_64-linux/fpc.cfg
WARNING: ppu exists twice: /home/myuser/fpcupdeluxe_fix/fpc/lib/fpc/3.2.3/units/i386-linux/fv/dialogs.ppu, /home/myuser/fpcupdeluxe_fix/lazarus/lcl/units/i386-linux/dialogs.ppu
WARNING: ppu exists twice: /home/myuser/fpcupdeluxe_fix/fpc/lib/fpc/3.2.3/units/i386-linux/fv/menus.ppu, /home/myuser/fpcupdeluxe_fix/lazarus/lcl/units/i386-linux/menus.ppu
WARNING: orphaned file found: /home/myuser/fpcupdeluxe_fix/projects/lib/i386-linux/unit1.o
WARNING: orphaned file found: /home/myuser/fpcupdeluxe_fix/projects/lib/i386-linux/unit1.ppu`

If I add just the path, the same errors occur, except the warning for the path doesn't exist.
Still, this is the error.

`Error: /home/myuser/fpcupdeluxe_fix/cross/bin/i386-linux/i386-linux-ld: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /home/myuser/fpcupdeluxe_fix/cross/bin/i386-linux/i386-linux-ld)`

When I try to run the mentioned i386-linux-ld binary without any parameters (e.g. ./i386-linux-ld - and even with sudo), the same GLIBC_2.27 Error occurs.

**Comment by LongDirtyAnimAlf** [comment]
Look closely here: https://www.freepascal.org/docs-html/user/userap1.html
There is a difference between option -Fl (lowercase L) and -FL (uppercase L).
Please use the uppercase -FL as stated by me.

**Comment by Snify89** [comment]
> 
> 
> Look closely here: https://www.freepascal.org/docs-html/user/userap1.html
> There is a difference between option -Fl (lowercase L) and -FL (uppercase L).
> Please use the uppercase -FL as stated by me.

You are right. Sorry.
I have added the commandline to the custom options but nothing has changed.

Same errors:
`Compile Project, CPU: i386, Target: /home/herbst/fpcupdeluxe_fix/projects/project1: Exit code 1, Errors: 2, Hints: 2
Hint: Start of reading config file /home/herbst/fpcupdeluxe_fix/fpc/bin/x86_64-linux/fpc.cfg
Hint: End of reading config file /home/herbst/fpcupdeluxe_fix/fpc/bin/x86_64-linux/fpc.cfg
Verbose: Free Pascal Compiler version 3.2.3-r49611 [2021/07/27] for i386
Verbose: Copyright (c) 1993-2021 by Florian Klaempfl and others
Verbose: Target OS: Linux for i386
Verbose: Compiling /home/herbst/fpcupdeluxe_fix/projects/project1.lpr
Verbose: Compiling unit1.pas
Verbose: Compiling resource /home/herbst/fpcupdeluxe_fix/projects/lib/i386-linux/project1.or
Error: /home/herbst/fpcupdeluxe_fix/cross/bin/i386-linux/i386-linux-ld: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /home/herbst/fpcupdeluxe_fix/cross/bin/i386-linux/i386-linux-ld)
Linking /home/herbst/fpcupdeluxe_fix/projects/project1
project1.lpr(25,1) Error: Error while linking
project1.lpr(25,1) Verbose: There were 1 errors compiling module, stopping
Verbose: Compilation aborted
Verbose: /home/herbst/fpcupdeluxe_fix/fpc/bin/x86_64-linux/ppcross386 returned an error exitcode
`

![Unbenannt](https://user-images.githubusercontent.com/5088625/127445723-1dd36779-f42e-426a-b098-24e61c9c37e5.png)

**Comment by LongDirtyAnimAlf** [comment]
We are getting closer. Now I want to know the location of the dynamic linker on your system.
Open a command terminal and execute something like: "file /usr/bin/bash". Or "file /usr/bin/ls". Or "file /bin/ls"
This should show you the dynamic linker used. Please show me the output.

**Comment by Snify89** [comment]
`herbst@Server:~/fpcupdeluxe_fix/cross/lib/i386-linux> file /usr/bin/bash
/usr/bin/bash: cannot open `/usr/bin/bash' (No such file or directory)
herbst@Server:~/fpcupdeluxe_fix/cross/lib/i386-linux> file /usr/bin/ls
/usr/bin/ls: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.0.0, BuildID[sha1]=608c53728150ae7f62970559ebc62ec875f95fbd, stripped
herbst@Server:~/fpcupdeluxe_fix/cross/lib/i386-linux> file /bin/ls
/bin/ls: symbolic link to /usr/bin/ls
`
these are my outputs. Hope this helps.

**Comment by LongDirtyAnimAlf** [comment]
Thanks. And now the output of:
`file /home/herbst/fpcupdeluxe_fix/cross/bin/i386-linux/i386-linux-ld`

**Comment by Snify89** [comment]
> file /home/herbst/fpcupdeluxe_fix/cross/bin/i386-linux/i386-linux-ld

herbst@Server:/fpcupdeluxe_fix/cross/lib/i386-linux> file /home/herbst/fpcupdeluxe_fix/cross/bin/i386-linux/i386-linux-ld
/home/herbst/fpcupdeluxe_fix/cross/bin/i386-linux/i386-linux-ld: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=a2ba4af6673eb369146fd80b8268347db94cd798, stripped

**Comment by LongDirtyAnimAlf** [comment]
Allright. 
The linux versions between fpcupdeluxe cross-binaries and your system differ too much.
Please try to install the Suse package:
cross-i386-binutils

**Comment by Snify89** [comment]
> 
> 
> Allright.
> The linux versions between fpcupdeluxe cross-binaries and your system differ too much.
> Please try to install the Suse package:
> cross-i386-binutils

Thank you for your help. Do you have any idea which one I should/could pick?
![Unbenannt2](https://user-images.githubusercontent.com/5088625/127452256-87b82b85-7b19-42eb-8017-0439ecfd69c8.png)

**Comment by LongDirtyAnimAlf** [comment]
Enough:
binutils
cross-i386-binutils
If you want to cross-compile towards raspberry Pi:
cross-arm-binutils

**Comment by Snify89** [comment]
> 
> 
> Enough:
> binutils
> cross-i386-binutils
> If you want to cross-compile towards raspberry Pi:
> cross-arm-binutils

I don't need arm architecture.
So I have these packages installed with the shown version(s).
Maybe it is a misconfiguration or maybe I need to download/install an additional package from somehwere else?! 

Sorry to bother you. I guess we got the answer finally and can say, that this issue is caused on my end. I just don't know enough to make this work. If you still have any ideas, please let me know. I really appreciate any support/help. Thank you in advance.

**Comment by LongDirtyAnimAlf** [comment]
No need to excuse yourself. We are here to help. And solving this issue also may help others.
All good now. The correct binary utilities are installed on your system.
Next steps.
Delete the "/home/herbst/fpcupdeluxe_fix/cross/bin/i386-linux directory".
Run fpcupdeluxe again. If it bothers you with the message that the tools are missing, click no. And report back for the next step.

**Comment by Snify89** [comment]
> 
> 
> No need to excuse yourself. We are here to help. And solving this issue also may help others.
> All good now. The correct binary utilities are installed on your system.
> Next steps.
> Delete the "/home/herbst/fpcupdeluxe_fix/cross/bin/i386-linux directory".
> Run fpcupdeluxe again. If it bothers you with the message that the tools are missing, click no. And report back for the next step.

Alright thank you. 
I have deleted the bin folder and redownloaded the newest fpcupdeluxe 1.8.2z.002 and startet it.
No message upon start of fpcdeluxe (except optional logging). 
After changing the install path to /home/herbst/fpcupdeluxe_fix it says:

`
Welcome @ FPCUPdeluxe.
FPCUPdeluxe V1.8.2z.002 for x86_64-linux-gtk2
Running on openSUSE Leap
CPU cores used: 2
Available physical memory: 7868 MB
Available swap: 4095 MB

Current install drectory: /home/herbst/fpcupdeluxe_fix

Got settings from install directory

Found crosscompiler for i386-linux
`

**Comment by LongDirtyAnimAlf** [comment]
Only have fpcupdeluxe perform a renewed install of the cross-compiler !
And no worries if it complains about missing tools. Just stop it there and report back.

**Comment by Snify89** [comment]
I clicked on "Install Compiler" (i386 / Linux), clicked on "No" when asking for downloading and got these results in the terminal output:


Going to install a cross-compiler from available sources.
Fpcupdeluxe: FPC cross-builder: Building compiler for linux-i386.
FPCUP(deluxe) is starting up.

FPCupdeluxe basedir:       /home/herbst/fpcupdeluxe_fix
Bootstrap dir:             /home/herbst/fpcupdeluxe_fix/fpcbootstrap

FPC URL:                   https://svn.freepascal.org/svn/fpc/branches/fixes_3_2
FPC source directory:      /home/herbst/fpcupdeluxe_fix/fpcsrc
FPC install directory:     /home/herbst/fpcupdeluxe_fix/fpc
FPC options:               

Lazarus URL:               https://svn.freepascal.org/svn/lazarus/branches/fixes_2_2
Lazarus source directory:  /home/herbst/fpcupdeluxe_fix/lazarus
Lazarus install directory: /home/herbst/fpcupdeluxe_fix/lazarus
Lazarus options:           -g -gl -O1

Please stand back and enjoy !

29-7-21 11:12:24: fpcupdeluxe: V346 (20210727) started.
FPCUPdeluxe V1.8.2z.002 for x86_64-linux running on openSUSE Leap

Found valid as application.
Found valid gunzip application.
Found valid tar application.
Found valid make application.
fpcupdeluxe: WARNING: Skipping cross-compiler clean step: compiler seems to be up to date !!
fpcupdeluxe: info: FPCCrossInstaller (CleanModule: FPC): Running make rtl_distclean,packages_distclean twice for target i386-linux
fpcupdeluxe: Executing: /usr/bin/make --jobs=2 FPMAKEOPT=--threads=2 FPC=/home/herbst/fpcupdeluxe_fix/fpc/bin/x86_64-linux/ppcx64 --directory=/home/herbst/fpcupdeluxe_fix/fpcsrc FPCMAKE=/home/herbst/fpcupdeluxe_fix/fpc/bin/x86_64-linux/fpcmake PPUMOVE=/home/herbst/fpcupdeluxe_fix/fpc/bin/x86_64-linux/ppumove FPCDIR=/home/herbst/fpcupdeluxe_fix/fpcsrc PREFIX=/home/herbst/fpcupdeluxe_fix/fpc INSTALL_PREFIX=/home/herbst/fpcupdeluxe_fix/fpc INSTALL_BINDIR=/home/herbst/fpcupdeluxe_fix/fpc/bin/x86_64-linux OS_TARGET=linux CPU_TARGET=i386 rtl_distclean packages_distclean (working dir: /home/herbst/fpcupdeluxe_fix/fpcsrc)
/usr/bin/make -C rtl distclean
/usr/bin/make -C linux cleanall
/usr/bin/make -C linux distclean
/usr/bin/make -C packages distclean
/usr/bin/make -C fpmkunit clean_bootstrap
Warning: Removed non empty directory "ide/units/i386-linux/"
fpcupdeluxe: Executing: /usr/bin/make --jobs=2 FPMAKEOPT=--threads=2 FPC=/home/herbst/fpcupdeluxe_fix/fpc/bin/x86_64-linux/ppcx64 --directory=/home/herbst/fpcupdeluxe_fix/fpcsrc FPCMAKE=/home/herbst/fpcupdeluxe_fix/fpc/bin/x86_64-linux/fpcmake PPUMOVE=/home/herbst/fpcupdeluxe_fix/fpc/bin/x86_64-linux/ppumove FPCDIR=/home/herbst/fpcupdeluxe_fix/fpcsrc PREFIX=/home/herbst/fpcupdeluxe_fix/fpc INSTALL_PREFIX=/home/herbst/fpcupdeluxe_fix/fpc INSTALL_BINDIR=/home/herbst/fpcupdeluxe_fix/fpc/bin/x86_64-linux OS_TARGET=linux CPU_TARGET=i386 rtl_distclean packages_distclean (working dir: /home/herbst/fpcupdeluxe_fix/fpcsrc)
/usr/bin/make -C rtl distclean
/usr/bin/make -C linux cleanall
/usr/bin/make -C linux distclean
/usr/bin/make -C packages distclean
/usr/bin/make -C fcl-report distclean
/usr/bin/make -C lua distclean
/usr/bin/make -C gdbint distclean
/usr/bin/make -C sqlite distclean
/usr/bin/make -C fuse distclean
/usr/bin/make -C ldap distclean
/usr/bin/make -C libgbafpc distclean
/usr/bin/make -C sdl distclean
/usr/bin/make -C rtl-extra distclean
/usr/bin/make -C libcurl distclean
/usr/bin/make -C dts distclean
/usr/bin/make -C zorba distclean
/usr/bin/make -C gtk2 distclean
/usr/bin/make -C pthreads distclean
/usr/bin/make -C gnome1 distclean
/usr/bin/make -C opencl distclean
/usr/bin/make -C oracle distclean
/usr/bin/make -C newt distclean
/usr/bin/make -C imagemagick distclean
/usr/bin/make -C pcap distclean
/usr/bin/make -C bfd distclean
/usr/bin/make -C amunits distclean
/usr/bin/make -C fpgtk distclean
/usr/bin/make -C hash distclean
/usr/bin/make -C libgc distclean
/usr/bin/make -C chm distclean
/usr/bin/make -C pasjpeg distclean
/usr/bin/make -C fcl-sdo distclean
/usr/bin/make -C nvapi distclean
/usr/bin/make -C ami-extra distclean
/usr/bin/make -C fcl-stl distclean
/usr/bin/make -C bzip2 distclean
/usr/bin/make -C ncurses distclean
/usr/bin/make -C cdrom distclean
/usr/bin/make -C fcl-registry distclean
/usr/bin/make -C rtl-console distclean
/usr/bin/make -C fcl-process distclean
/usr/bin/make -C os2units distclean
/usr/bin/make -C a52 distclean
/usr/bin/make -C objcrtl distclean
/usr/bin/make -C palmunits distclean
/usr/bin/make -C odata distclean
/usr/bin/make -C paszlib distclean
/usr/bin/make -C postgres distclean
/usr/bin/make -C mysql distclean
/usr/bin/make -C libsee distclean
/usr/bin/make -C httpd24 distclean
/usr/bin/make -C libc distclean
/usr/bin/make -C fcl-sound distclean
/usr/bin/make -C winunits-base distclean
/usr/bin/make -C uuid distclean
/usr/bin/make -C svgalib distclean
/usr/bin/make -C libxml distclean
/usr/bin/make -C cairo distclean
/usr/bin/make -C libffi distclean
/usr/bin/make -C tcl distclean
/usr/bin/make -C libfontconfig distclean
/usr/bin/make -C zlib distclean
/usr/bin/make -C fftw distclean
/usr/bin/make -C ptc distclean
/usr/bin/make -C graph distclean
/usr/bin/make -C arosunits distclean
/usr/bin/make -C regexpr distclean
/usr/bin/make -C winunits-jedi distclean
/usr/bin/make -C fv distclean
/usr/bin/make -C fcl-js distclean
/usr/bin/make -C libmicrohttpd distclean
/usr/bin/make -C fcl-json distclean
/usr/bin/make -C iconvenc distclean
/usr/bin/make -C dbus distclean
/usr/bin/make -C ggi distclean
/usr/bin/make -C aspell distclean
/usr/bin/make -C odbc distclean
/usr/bin/make -C webidl distclean
/usr/bin/make -C fcl-base distclean
/usr/bin/make -C librsvg distclean
/usr/bin/make -C vcl-compat distclean
/usr/bin/make -C libusb distclean
/usr/bin/make -C libogcfpc distclean
/usr/bin/make -C hermes distclean
/usr/bin/make -C rtl-unicode distclean
/usr/bin/make -C opengl distclean
/usr/bin/make -C utmp distclean
/usr/bin/make -C unzip distclean
/usr/bin/make -C fcl-extra distclean
/usr/bin/make -C pxlib distclean
/usr/bin/make -C morphunits distclean
/usr/bin/make -C fcl-image distclean
/usr/bin/make -C fpindexer distclean
/usr/bin/make -C os4units distclean
/usr/bin/make -C fpmkunit distclean
/usr/bin/make -C numlib distclean
/usr/bin/make -C sndfile distclean
/usr/bin/make -C fcl-pdf distclean
/usr/bin/make -C oggvorbis distclean
/usr/bin/make -C fcl-xml distclean
/usr/bin/make -C fcl-res distclean
/usr/bin/make -C openal distclean
/usr/bin/make -C fppkg distclean
/usr/bin/make -C unixutil distclean
/usr/bin/make -C modplug distclean
/usr/bin/make -C fcl-fpcunit distclean
/usr/bin/make -C symbolic distclean
/usr/bin/make -C rexx distclean
/usr/bin/make -C httpd13 distclean
/usr/bin/make -C fcl-net distclean
/usr/bin/make -C libpng distclean
/usr/bin/make -C syslog distclean
/usr/bin/make -C libndsfpc distclean
/usr/bin/make -C cocoaint distclean
/usr/bin/make -C libmagic distclean
/usr/bin/make -C rtl-generics distclean
/usr/bin/make -C imlib distclean
/usr/bin/make -C libtar distclean
/usr/bin/make -C rtl-objpas distclean
/usr/bin/make -C users distclean
/usr/bin/make -C mad distclean
/usr/bin/make -C fcl-passrc distclean
/usr/bin/make -C iosxlocale distclean
/usr/bin/make -C gmp distclean
/usr/bin/make -C xforms distclean
/usr/bin/make -C dblib distclean
/usr/bin/make -C fcl-db distclean
/usr/bin/make -C proj4 distclean
/usr/bin/make -C fastcgi distclean
/usr/bin/make -C opengles distclean
/usr/bin/make -C openssl distclean
/usr/bin/make -C fcl-web distclean
/usr/bin/make -C x11 distclean
/usr/bin/make -C httpd22 distclean
/usr/bin/make -C libcups distclean
/usr/bin/make -C tosunits distclean
/usr/bin/make -C tplylib distclean
/usr/bin/make -C googleapi distclean
/usr/bin/make -C libgd distclean
/usr/bin/make -C gtk1 distclean
/usr/bin/make -C ide distclean
/usr/bin/make -C fakegdb distclean
/usr/bin/make -C compiler distclean
/usr/bin/make -C httpd20 distclean
/usr/bin/make -C pastojs distclean
/usr/bin/make -C univint distclean
/usr/bin/make -C winceunits distclean
/usr/bin/make -C gnutls distclean
/usr/bin/make -C gdbm distclean
/usr/bin/make -C matroska distclean
/usr/bin/make -C ibase distclean
/usr/bin/make -C jni distclean
/usr/bin/make -C libenet distclean
/usr/bin/make -C fcl-async distclean
/usr/bin/make -C libvlc distclean
/usr/bin/make -C fpmkunit clean_bootstrap
fpcupdeluxe: info: FPCCrossInstaller (BuildModule: FPC): Building module FPC...
fpcupdeluxe: info: FPC i386-linux cross-builder: Detected source version FPC (source): 3.2.3
fpcupdeluxe: info: FPCCrossInstaller (BuildModuleCustom: FPC): Looking for crosstools and crosslibs on system. Please wait.
fpcupdeluxe: ERROR: Failed to get crossbinutils

fpcupdeluxe: TAny_linux-i386: Found correct library in directory /home/herbst/fpcupdeluxe_fix/cross/lib/i386-linux

Fpcupdeluxe failed due to missing cross binary tools.

Underneath the logs:

Fpcupdeluxe: FPC cross-builder: Building compiler for linux-i386.
fpcupdeluxe: WARNING: Skipping cross-compiler clean step: compiler seems to be up to date !!
fpcupdeluxe: info: FPC i386-linux cross-builder: Detected source version FPC (source): 3.2.3
fpcupdeluxe: Start of compile error summary.
fpcupdeluxe: ERROR: Failed to get crossbinutils
Missing correct cross libraries
fpcupdeluxe: Done !!

**Comment by LongDirtyAnimAlf** [comment]
Good !
Now you have to wait a bit for a new update of fpcupdeluxe. Some changes need to be made to be able to use the utils that are now installed on your system !
In the meantime, I need one more piece of information: the location of these tools.
Do:
"which i386-linux-gnu-ld"
and
"which i586-suse-linux-ld"

**Comment by Snify89** [comment]
> 
> 
> Good !
> Now you have to wait a bit for a new update of fpcupdeluxe. Some changes need to be made to be able to use the utils that are now installed on your system !
> In the meantime, I need one more piece of information: the location of these tools.
> Do:
> "which i386-linux-gnu-ld"
> and
> "which i586-suse-linux-ld"

Thank you so much for taking care of this issue!
Wish I could contribute something, somehow.
It's great to know, that developers like take their time to listen and take their time to help/support.

This is my output:

```
herbst@Server:> which i386-linux-gnu-ld
which: no i386-linux-gnu-ld in (/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/home/herbst/.dotnet/tools)
herbst@Server:> which i586-suse-linux-ld
/usr/bin/i586-suse-linux-ld
```

Let me know anytime, if you need any further information.

**Comment by LongDirtyAnimAlf** [comment]
Please test:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/1.8.2z.004/fpcupdeluxe-x86_64-linux

**Comment by Snify89** [comment]
> 
> 
> Please test:
> https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/1.8.2z.004/fpcupdeluxe-x86_64-linux

Alright thank you. I will test this in the next hour or so. 
What are your instructions? How should/can I proceed?

**Comment by LongDirtyAnimAlf** [comment]
Just replace the old fpcupdeluxe binary with the new one.
And let the new one install the cross-compiler.
That' s it (I hope).

**Comment by Snify89** [comment]
> Just replace the old fpcupdeluxe binary with the new one.
> And let the new one install the cross-compiler.
> That' s it (I hope).

Just did what you told me. 
I still can't link the project. :(

Here is the new output from lazarus:

```
Compile Project, CPU: i386, Target: /home/herbst/fpcupdeluxe_fix/projects/project1: Exit code 1, Errors: 6, Hints: 2
Hint: Start of reading config file /home/herbst/fpcupdeluxe_fix/fpc/bin/x86_64-linux/fpc.cfg
Hint: End of reading config file /home/herbst/fpcupdeluxe_fix/fpc/bin/x86_64-linux/fpc.cfg
Verbose: Free Pascal Compiler version 3.2.3-r49611 [2021/07/27] for i386
Verbose: Copyright (c) 1993-2021 by Florian Klaempfl and others
Verbose: Target OS: Linux for i386
Verbose: Compiling /home/herbst/fpcupdeluxe_fix/projects/project1.lpr
Verbose: Compiling unit1.pas
Verbose: Compiling resource /home/herbst/fpcupdeluxe_fix/projects/lib/i386-linux/project1.or
Verbose: Linking /home/herbst/fpcupdeluxe_fix/projects/project1
Error: /usr/bin/i586-suse-linux-ld: /home/herbst/fpcupdeluxe_fix/cross/lib/i386-linux//libxcb-shm.so.0: undefined reference to `xcb_send_request_with_fds'
Error: /usr/bin/i586-suse-linux-ld: /home/herbst/fpcupdeluxe_fix/cross/lib/i386-linux//libpangoft2-1.0.so.0: undefined reference to `FcWeightToOpenType'
Error: /usr/bin/i586-suse-linux-ld: /home/herbst/fpcupdeluxe_fix/cross/lib/i386-linux//libpangoft2-1.0.so.0: undefined reference to `FcWeightFromOpenType'
Error: /usr/bin/i586-suse-linux-ld: /home/herbst/fpcupdeluxe_fix/cross/lib/i386-linux//libcairo.so: undefined reference to `FT_Get_Var_Design_Coordinates'
Error: /usr/bin/i586-suse-linux-ld: /home/herbst/fpcupdeluxe_fix/cross/lib/i386-linux//libharfbuzz.so.0: undefined reference to `FT_Get_Var_Blend_Coordinates'
project1.lpr(25,1) Error: Error while linking
project1.lpr(25,1) Verbose: There were 1 errors compiling module, stopping
Verbose: Compilation aborted
Verbose: /home/herbst/fpcupdeluxe_fix/fpc/bin/x86_64-linux/ppcross386 returned an error exitcode
```
I added the complete output from fpcupdeluxe to investigate.
So sorry, that I ran into this issue with my limited knowledge. 
Feel free to abort and/or ask for further information.

[fpcupdeluxe output.txt](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/6899897/fpcupdeluxe.output.txt)

**Comment by LongDirtyAnimAlf** [comment]
We have reached the limit about the help fpcupdeluxe can provide.
The linking problem has been solved. By using the binutils that are native to your system.

Now you are trying to compile a GUI application.
To compile a GUI app, you need all kinds of libraries. 
Fpcupdeluxe provides a set of libraries that are known to work in general. Your system is different. You need to provide the libs for i386 that are needed to compile/run an i386 app on a x86_64 system.
You have to do your own research now. Please look for knowledge about compiling and/or running an i386 GUI-app on your x86_64 system.

**Comment by Snify89** [comment]
> 
> 
> We have reached the limit about the help fpcupdeluxe can provide.
> The linking problem has been solved. By using the binutils that are native to your system.
> 
> Now you are trying to compile a GUI application.
> To compile a GUI app, you need all kinds of libraries.
> Fpcupdeluxe provides a set of libraries that are known to work in general. Your system is different. You need to provide the libs for i386 that are needed to compile/run an i386 app on a x86_64 system.
> You have to do your own research now. Please look for knowledge about compiling and/or running an i386 GUI-app on your x86_64 system.

I understand. 
Thank you so very much for your time, help and support. 
I really appreciate what you are doing to/for this community.
As soon as I come up with the rest of a solution, I will post it here for others.

Stay healthy out there and take care!
Really, you are doing a great job and a huge favor for all the FreePascal developers out there!
Keep up your good work for as long as you want/can.

**Comment by Snify89** [comment]
One last question. 
Is it advisable to recompile/reinstall/reboot the cross compiler stuff after I might have found a solution (e.g. installed missing packages, etc.)?

Or is it possible to make this work in an instant, without touching anyhting in fpcupdeluxe?

**Comment by LongDirtyAnimAlf** [comment]
> Is it advisable to recompile/reinstall/reboot the cross compiler stuff after I might have found a solution (e.g. installed missing packages, etc.)?

Yes, you need to re-run fpcupdeluxe for the cross-compiler install only. So, only do the install-crosscompiler thing. Don't be afraid that it fails. That's ok.
Fpcupdeluxe has a lot of magic inside to find the appropriate system tools and libraries.
As your system is a bit different, I expect some changes will be needed to find the right libs on your system. But that's ok. It will make fpcupdeluxe better. That is the reason our effort to get things running is important !

If you succeed in getting the right libs, I will add this into fpcupdeluxe, together with the instructions (the commands you used to get the libs).

**Comment by Snify89** [comment]
> 
> 
> > Is it advisable to recompile/reinstall/reboot the cross compiler stuff after I might have found a solution (e.g. installed missing packages, etc.)?
> 
> Yes, you need to re-run fpcupdeluxe for the cross-compiler install only. So, only do the install-crosscompiler thing. Don't be afraid that it fails. That's ok.
> Fpcupdeluxe has a lot of magic inside to find the appropriate system tools and libraries.
> As your system is a bit different, I expect some changes will be needed to find the right libs on your system. But that's ok. It will make fpcupdeluxe better. That is the reason our effort to get things running is important !
> 
> If you succeed in getting the right libs, I will add this into fpcupdeluxe, together with the instructions (the commands you used to get the libs).

Alright, thank you. I will try my best to make this work :)

**Comment by LongDirtyAnimAlf** [comment]
I have added two scripts.
The first for installing the normal libs to get fpcupdeluxe and Lazarus running on Suse.
The second for installing cross-libs for i386.
Scripts:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/blob/master/installscripts/suse_x86-64.sh
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/blob/master/crossscripts/suse_s_any_to_i386.sh
Latest releae:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.0.1

**Comment by Snify89** [comment]
Thank you very much for the scripts! I appreciate the effort and get the idea, what's missing for suse.
Currently I am not able to test these on my system... 
Besides I am trying to figure out to compile the GNU Debugger for my suse as the WinX64 host, so I can remote debug my applications from Windows. But I can't find the mingw64 libs right now.

If you got some spare time, etc. you might make debugging easier with fpcupdeluxe by proper compiling the gnu debugger for various targets and hosts.

As soon as I get the time. I will try out the scripts :)

Again, thank you so much for your effort and support! Keep up the amazing work you are doing for the community. This is much appreciated!
