### ISSUE TITLE
git suggestions.

### ISSUE THREAD

**Issue by ollydev** [LongDirtyAnimAlf/fpcupdeluxe#402]
Could choosing commit or branch/tag be supported in the URL?

For example:

Clone at a specific commit:
https://gitlab.com/freepascal.org/lazarus/lazarus/commit/368d15ea481675674f1a2a5bf7adf9fb42dd527c

Clone at branch/tag
https://gitlab.com/freepascal.org/lazarus/lazarus/tree/main

---

Extra:

Could fpcup try to get cross compile binaries if instructed? I (think?) fpcupdelxue does this.

AArch64 cross binaries:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/crosslibs_v1.1/CrossLibsLinuxAarch64.zip
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/linuxx64crossbins_v1.0/CrossBinsLinuxAarch64.zip

And whatever else you provide.

---

Bonus:

I created a github action for fpcup! Once fpc & lazarus gitlab switch is complete it would be nice to link it in fpcup README.

https://github.com/ollydev/setup-lazarus-fpcup#example-usage

**Comment by LongDirtyAnimAlf** [comment]
The whole Gitlab thing has to be ironed out. It needs to be seen how fpcupdeluxe should handle branches and tags in a user friendly way (and GUI). If Gitlab is up and fpcupdeluxe is ready, you are very welcome to give feedback and improve fpcupdeluxe !

Fpcup will not download the cross-utils. There is too much user-interaction needed to accomplish this task.
However, it might be a usefull feature.
Please file a Github issue for fpcup at its Github repo. If time permits I will look into this.
Thanks.

> I created a github action for fpcup! Once fpc & lazarus gitlab switch is complete it would be nice to link it in fpcup README.

Will do !

**Comment by prof7bit** [comment]
I have a question that is semi-related:

There is an option in the setup dialog "auto switch repository URLs" but I have never seen it do anything, neither with svn nor with git. Currently I am playing around with the other git repos from Graeme and others but once I checked out a repo I cannot switch to a different repo anymore.

Once all branches are in the same repo it should be trivial to switch between branches instantly, but theoretically even a switching of the repo URL should be possible. It should even be possible to migrate an old svn checkout to git (or generally clone into a non-empty directory): https://stackoverflow.com/questions/2411031/how-do-i-clone-into-a-non-empty-directory.

**Comment by LongDirtyAnimAlf** [comment]
> but I have never seen it do anything

On a SVN repo it allowed users to switch (the URL) from e.g FPC 302 to 304. This is how stable URL's with SVN worked.
And yes, when everything is on Gitlab, switching is a no-brainer. Fpcupdeluxe is already prepared to handle this.
All other URL-switching will still be problematic.

**Comment by LongDirtyAnimAlf** [comment]
You might try:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.0.0d

**Comment by LongDirtyAnimAlf** [comment]
No feedback.
Closing.
