### ISSUE TITLE
[Feature] migration of existing source folders from svn to git

### ISSUE THREAD

**Issue by prof7bit** [LongDirtyAnimAlf/fpcupdeluxe#404]
Once gitlab will be up and running it would be nice if there was functionality to move an existing installation from svn to the gitlab repository: 

  * It would detect which branch it is on, 
  * then replace it with a git checkout of the HEAD of the same branch 
  * and additionally generate a diff of all changes between the old source tree and the new checkout in order to not lose any local patches that might have been forgotten or to be able to undo this change entirely if any unwanted things happen.

Most importantly this would preserve the Lazarus configuration folder and would provide a seamless one-click upgrade experience for people (like one of my colleagues for example) who have just recently been converted into fpcupdeluxe users during long conversations and might not yet be fully convinced of its power. It would be much easier to continue arguing in favor of fpcupdeluxe (especially with very impatient colleagues of mine as for example the one sitting behind the door right next to me) if it was possible to continue using it with only a few mouse clicks and not forcing them to rename and move around folders and files manually again.

This would be a very helpful feature.

**Comment by LongDirtyAnimAlf** [comment]
> it would be nice if there was functionality to move an existing installation from svn to the gitlab

Yes, that would be very nice !
I will try to implement such a switch. But that will not be easy. Needs a lot of testing. and testing is difficult without having gitlab FPC sources available.
Will keep this issue open until I know more.

**Comment by LongDirtyAnimAlf** [comment]
You might try:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.0.0d

**Comment by prof7bit** [comment]
The conversion to git has worked flawlessly on the first try!

Then I switched from fixes-2.0 to fixes-2.2 and it failed to compile because they renamed the treeview package and I needed to manually dig around in the package configuration files, but this is probably not in the scope of fpcupdeluxe to fix, so as far as I am concerned this issue can be closed.
