### ISSUE TITLE
git clone aksing for credentials, setup stuck at downloading source

### ISSUE THREAD

**Issue by mondworker** [LongDirtyAnimAlf/fpcupdeluxe#405]
When the setup tries to download the source with the command 

C:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe clone --recurse-submodules --branch release_3_2_2 https://gitlab.com/freepascal.org/fpc/source/ C:\fpcupdeluxe\fpcsrc

the setup gets stuck and can't continue. I've tried the command line manually and git asks for credentials. Is the a way to change this?

**Comment by LongDirtyAnimAlf** [comment]
> Is the a way to change this

Nop. The FPC source repo is not yet public. The moment the developers are ready, this repo will be made public and can be used by fpcupdeluxe !
The above will happen today or within the next few days.
