### ISSUE TITLE
freeze on FPCBuild download

### ISSUE THREAD

**Issue by Awkward-im** [LongDirtyAnimAlf/fpcupdeluxe#406]
program freezes on trying to download https://github.com/fpc/FPCBuild/raw/master/install/binw64/cpp.exe
coz no file cpp.exe in https://github.com/fpc/FPCBuild/tree/master/install/binw64

**Comment by LongDirtyAnimAlf** [comment]
Uploaded a new binary. Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/v2.0.0d/fpcupdeluxe-x86_64-win64.exe

**Comment by Awkward-im** [comment]
Can't check coz NOW it freezed on trying to download unrar from SF (yes, SF is hard to access sometime), so, looks like will need to check again little later.

**Comment by LongDirtyAnimAlf** [comment]
I guess I could/should remove unrar ... not that much needed anymore.

**Comment by LongDirtyAnimAlf** [comment]
Closing. Should be solved.
