### ISSUE TITLE
Lazarus GUI transfer

### ISSUE THREAD

**Issue by CharlyTango** [LongDirtyAnimAlf/fpcupdeluxe#408]
Hi,
Installing Lazarus with fpcupdeluxe works like a breeze.
But some work runs in tweaking the GUI, either in docked mode or windowed mode. Open Windows, Position, Desktops, Codetools -- all individual Setup.

Similar to installing Modules -- it would be nice to copy/transfer these individual settings form an old installation to an new one. Or a possibility to backup and restore the necessary files.

Thanks in advance

**Comment by mdbs99** [comment]
The configuration is in `config_lazarus` folder - you can replace them from the old to new installation.

**Comment by LongDirtyAnimAlf** [comment]
This has been requested before. And is impossible to implement. Lazarus has too many install-quirks.
A feature like this would result in many bugs that would need a lot of time and effort to solve.
Sorry about this. Closing.
