### ISSUE TITLE
Getting the sources using a specific Git commit

### ISSUE THREAD

**Issue by mdbs99** [LongDirtyAnimAlf/fpcupdeluxe#409]
I've tried the first Release v2.0.1 for Windows, which uses Git, and it worked perfectly (thank you).

However, I would like know how can I set a specific commit, as we used to do for FPC and Lazarus revisions, in "Setup+" option?

**Comment by LongDirtyAnimAlf** [comment]
New release: https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.0.1a
Please test if adding the revision/hash in Setup+ works for you.
Thanks.

**Comment by mdbs99** [comment]
@LongDirtyAnimAlf it worked perfectly, thanks!
(sorry my delay)
