### ISSUE TITLE
fpcupdeluxe-2.01 fails using GIT on Windows and Linux

### ISSUE THREAD

**Issue by oliverhbailey** [LongDirtyAnimAlf/fpcupdeluxe#410]
This fails on Windows 10 with an infinite loop for user authentication on Github. When you authenticate and close the browser window as instructed, fpcupdeluxe fails and send the user back to authenticate again, and the loop continues. On Linux, it just fails, never taking the user to authenticate. The Win95 icon on the button doesn't show up on the Linux either. I have tested on Debian 9, and 10 with the same results.

**Comment by mdbs99** [comment]
I've tested today the [release v2.0.1 for Windows](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.0.1) for Windows (mine is also Win10) without any issues. I could get sources, testing for many branches such `2.0.10`, `2.0.12`, `fixes-2.2`, and `trunk` (master).

Perhaps, you are trying to use SVN "old sources", which is no more available.

Anyway, I used GitLab option.

**Comment by oliverhbailey** [comment]
Hi Marcos,
First of all, Gitlab does work, but git doesn't. I outlined the steps and
there have been other posts about similar issues. As I stated, the git
feature goes into an infinite loop logging in. And the Linux version never
brings up the login for git, it just fails with the same errors. With 46
years in software and hardware development, I would say there is a problem
with fpcupdeluxe. Thank you for your anyway.

Oliver

**Comment by mdbs99** [comment]
Hello Oliver,
I wouldn't meant that it might not have a problem with fpcupdeluxe, I just wanted to share that, in my case, I haven't any problems with this version.
Just for curiosity, if GitLab works—and it's the original repository for FPC and Lazarus now, beeing Github just a copy—why don't you use it? It's a Git engine anyway.

**Comment by oliverhbailey** [comment]
Carlos,
I have reasons on why I am testing all the features of this program. If the option doesn't work then it should be fixed or removed. If I wanted to fix it, I would download the sources and do so, instead I chose to leave a bug report and details. I did not intend or want to engage in a discussion about the problem. Once again, I documented what happened and let's leave it at that. I wasn't looking to engage in conversation or a debate.

Regards,
Oliver Bailey

**Comment by LongDirtyAnimAlf** [comment]
Please provide more details, because I do not understand why user authentication on Github should be necessary.
And, ASAIK, fpcupdeluxe provides no means for user authentication except when using a http proxy.
So (also), what URL/repo are you trying to check out ?

**Comment by oliverhbailey** [comment]
Hello Don,
I downloaded 2.0.1 win64 that was posted 5 days ago. I went selected git
and trunk for fpc and lazarus. I don't use a proxy and I pressed
update/install. I tried this on Debian 10.10 first. It came back with a
strange error message. I sent it using the send button for the display and
log.
I then tried it on Windows 10 latest build, and a window popped up stating
github needed authentacation and when I clicked ok it opened the browser
and asked if I would allow fpcupdeluxe access. I pressed ok. When I was
returned to fpcupdeluxe, it generated the same error as the Linux version
and took me back to the authentication dialog box again and an endless loop
started. I sent that log severa times as well.

I do have a github account. I use git from the command line and it never
requires authentication depending on how you download.

I have up, went to gitlab and everything work fine from the gitlab trunk.
It appears 3.31 and 2.10 were the trunk versions. I would hope the minor
versions were in the log that was sent.

If not, I'll do a screen video and send it so you can trace my steps frame
by frame. You should also know the Win 95 icon does show on Linux and the
button left of halt is partially cover by halt in the default main window
at startup.

Let me know if you want the screen video.

Regards,
Oliver

**Comment by oliverhbailey** [comment]
Don,
Widows update did a reboot last night and the problem went away.
Interesting though, that machine has Windows Subsystem for Linux 2 active.
I wonder if this this was related! In either case, I just ran the git
version and all the issues went away, and no prompt for authentication. Its
somewhat frustrating with Microsoft using the stable version of Windows for
beta testing features that are suppose to be finished and working.

Oliver

**Comment by LongDirtyAnimAlf** [comment]
Thanks for the feedback.
I guess we can consider this issue as more or less "solved". So will close.
Please re-open when necessary.
