### ISSUE TITLE
Embedded Target not building anymore

### ISSUE THREAD

**Issue by michael-ring** [LongDirtyAnimAlf/fpcupdeluxe#411]
Hi Don,

I need your advice here.....

I tried building embedded target on fpcupdeluxe-2.01 but it fails when building Lazarus, my guess would be that graeme's mirror is not good anymore as svn is down but I did not investigate.

So for me this means for the moment the following todo's:

I need to upgrade to latest fpc trunk, currently the version I use still references svn.....

Then there is the problem with lazarus, how to best cover this?

Can we move the embedded target to the gitlab page, there (hopefully) lazarus will build just fine... Or is this page reserved to gitlab only projects --> would this mean that I have to move the embedded target to gitlab?

Any Ideas welcome!

Michael

**Comment by michael-ring** [comment]
Just found out that graeme already did take down both fpc and lazarus mirrors.... Need to find a way to sync to latest git sources from gitlab...

**Comment by LongDirtyAnimAlf** [comment]
Is this helpful ?
https://github.com/fpc

**Comment by LongDirtyAnimAlf** [comment]
Would it be an idea to add embedded as a branch into the official FPC sources ?

**Comment by michael-ring** [comment]
I guess a fork will do, I already forced fpcsources on gitlabI then I can do pull requests to give back to fpc.

**Comment by LongDirtyAnimAlf** [comment]
With the latest deluxe, any embedded button will install:
FPCTarget:='embedded.git'; [=https://github.com/michael-ring/freepascal.git]
LazarusTarget:='trunk.gitlab'; [Lazarus trunk from official gitlab]

**Comment by michael-ring** [comment]
Did not try the buttons.... Sorry.... 

So one workarround could be to replace the dead lazarus entry in the non-gitlab view with the gitlab entry or to move embedded to the gitlab view (unless this causes some crashing and burning....)
If possible put embedded to gitlab and then we can switch to my gitlab fork once I have forced git to merge my changes to the gitlab fork of freepascal...... The fork on github is now dead anyway since graeme's base is missing.....

**Comment by michael-ring** [comment]
I have now pushed my changes to 

https://gitlab.com/michael-ring/freepascal-sources.git

I have hacked my local fpcup.ini and compilers compile without issue. I need to do testing with this new fork but from my point of view this is already a good start, git versions now get properly written into the compiler.
From my point of view embedded can move to to the gitlab page.....

**Comment by LongDirtyAnimAlf** [comment]
That is good !!
Will implement the changes in up !

**Comment by LongDirtyAnimAlf** [comment]
Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.0.1b

**Comment by michael-ring** [comment]
Works fine for avr and arm, xtensa builds fail. But this is something that I can fix on my side, so for the fpcupdeluxe-part I think we are fine. Can you remove the old embedded tag from the non-gitlab screen? compiling works now as you fixed the lazarus trunk part but it still burns svn tags in the fpc binary so we better get rid of it. I will also sooner or later delete the github repo, at that point it will stop working anyway.
