### ISSUE TITLE
Patch files not applied

### ISSUE THREAD

**Issue by prof7bit** [LongDirtyAnimAlf/fpcupdeluxe#412]
I'm trying to use the "Add Laz. Patch" Button to add a patch for lazarus sources because I am trying to hunt down a bug and unfortunately because you do not surround `git pull` with `git stash` and `git stash pop` or provide any other means to make local changes before it compiles my only option at the moment seems to use patch files.

From the log it seems it wants to use /usr/bin/patch -p 0 -N --no-backup-if-mismatch -i   <some.patch>

I created the patch with git diff but the output of git diff does not seem to be compatible with the patch tool (probably it should be applied with git apply and not with patch).

The error message is:

```
can't find file to patch at input line 5
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/tools/svn2revisioninc.pas b/tools/svn2revisioninc.pas
|index 8cfe27f062..77e98417cc 100644
|--- a/tools/svn2revisioninc.pas
|+++ b/tools/svn2revisioninc.pas
--------------------------
File to patch: 
```

**Comment by prof7bit** [comment]
found it, I need to use
```
git diff --no-prefix
```
to create my patch. But it would still be nice if it would preserve local changes by wrapping it in `git stash` and `git stash pop` so it would behave more like `svn up` where I can pull from upstream even in the presence of local changes and it will automatically merge them.

Closing this bug and going to make a new one for this purpose.

**Comment by LongDirtyAnimAlf** [comment]
Please attach patch-file so I am able to access this issue.

**Comment by prof7bit** [comment]
The patch file created with `git diff` started with 

```
|diff --git a/tools/svn2revisioninc.pas b/tools/svn2revisioninc.pas
|index 8cfe27f062..77e98417cc 100644
|--- a/tools/svn2revisioninc.pas
|+++ b/tools/svn2revisioninc.pas

```
but if I create the patch with `git diff --no-prefix` it starts with 

```
diff --git tools/svn2revisioninc.pas tools/svn2revisioninc.pas
index 8cfe27f062..9c6bb2d835 100644
--- tools/svn2revisioninc.pas
+++ tools/svn2revisioninc.pas

```
Note that the a/ and b/ path prefixes were the problem. If the patches are created with --no-prefix then everything works as expected, therefore I closed this bug because it actually is not a bug at all.
