### ISSUE TITLE
something is wrong with revision.inc

### ISSUE THREAD

**Issue by prof7bit** [LongDirtyAnimAlf/fpcupdeluxe#413]
```
bernd@bernd:~/fpcupdeluxe/lazarus (fixes_2_2)$ cat ide/revision.inc 
// Created by Svn2RevisionInc
const RevisionStr = 'fixes_2_2-0-gc60b5f9a7e';

```
it refers to 0 commits after fixes_2_2

but if I issue the command `git describe` then it will correctly output `t-fixes-2_2-153-gc60b5f9a7e`
which is 153 commits after the tag "t-fixes" which is what I would expect.

I tried to debug svn2revisioninc.pas but I cannot for the life of me figure out how to call it to ever produce this wrong RevisionStr, when I call it manually it will always create exactly what I would expect. I tried to insert some writeln() inside it to figure out what command it actually calls to produce this wrong string but no output appears in the log, I even tried to let svn2revisioninc create a file to log the parameters in argv but it seems svn2revisioninc is never executed at all! And yet there automatically appears a `revision.inc` that claims it is created by Svn2RevisionInc. What is going on here?

**Comment by LongDirtyAnimAlf** [comment]
Fpcupdeluxe does not use svn2revision. It creates its own revision.inc. The fact that it looks like created by the svn-tool, is due to the fact that Lazarus only parses this file if it looks like this.
About revisions in general.
The move towards git has changed a lot. FPC and Lazarus do different things, use different naming schemes, use different revision algorithms.
Fpcupdeluxe tries to unify this. Into a universal revision-string. To be used to checkout and identify commits.
This is still a moving target. And expected to change in the near future.

**Comment by prof7bit** [comment]
IMHO git describe is the right idaa, I am using this too in some of my own projects. You can quickly see whether one version is older than another version and you can take this string and directly use it to refer to the commit for checkout.

I'm currently trying to debug svn2revisioninc and it seems it is riddled with bugs, it does not even run without crashing if hg is not installed (accessing array elements out of bounds) and for some strange reason it cannot call the git binary with parameters for some very strange reason. And it is overly complicated. If you ask me it should be rewritten from scratch with only a 10th of the code that is in there and only do straightforward things in a straighttforward manner.

**Comment by LongDirtyAnimAlf** [comment]
Well. One should not use SVN2revision for GIT ... ;-)
So, I agree 100% about the rewrite.
Fpcupdeluxe also uses git describe, but this command "fails" when switching branches and tags.

**Comment by prof7bit** [comment]
svn2revisioninc contains code for git, after a dozen other useless git commands it eventually tries to call git describe, theoretically it should work. At one point for a brief moment a few minutes ago I had it working and outputting the correct revision, but I am already losing motivation for digging around in this code.

**Comment by prof7bit** [comment]
why would `git describe --tags` ever fail? For me this always returns something useful if there is at least one tag at the root of the repository. And as it seems the lazarus repository contains tags at the beginning of all branches, so it will always return the right thing. What is it that fails for you?

**Comment by prof7bit** [comment]
How are you calling git describe to get an output like "fixes_2_2-0-gc60b5f9a7e"? 
If I call it in the same branch I get something that looks like "t-fixes-2_2-153-gc60b5f9a7e"

**Comment by LongDirtyAnimAlf** [comment]
Look at the code from here:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/blob/master/gitclient.pas#L632

**Comment by prof7bit** [comment]
On my PC at home I have a version of fpcupdeluxe that also works (not sure which one), but it seems in 2.0.1c you broke it again.

**Comment by LongDirtyAnimAlf** [comment]
About 2.0.1c : what error ?

**Comment by prof7bit** [comment]
it outputs `fixes_2_2-0-gc60b5f9a7e` but it should output `t-fixes-2_2-153-gc60b5f9a7e`

This is because you have the `--all` option in there, so it will rather use the branch "fixes_2_2" instead of the tag "t-fixes_2_2" that has been intentionally placed at the start of this branch for exactly this purpose.

**Comment by LongDirtyAnimAlf** [comment]
This seems to be a valid point for Lazarus.
I would appreciate if you could investigate if the same is valid for FPC.
Thanks !!

**Comment by prof7bit** [comment]
The FPC devs don't (yet) seem to have placed tags to mark branch beginnings, they have instead tagged releases (the older ones do not even have branch names, just anonymous branches with tags to mark the end) and also they have some tags inside the various branches where they bumped the version number. 

For example if I checkout `fixes_3_2` and do` git describe --tags` it will output `3.2.3-380-gf58f92f005` and if I look at the git log then I can see that 380 commits ago there is a tag `3.2.3` and it marks the commit where they bumped the version from 3.2.1 to 3.2.3. So in this case `3.2.3-380-gf58f92f005` would mean "we are 380 commits after the tag '3.2.3' in the current branch" (which would be ok as a description as far as I'm concerned)

If I check out a tag instead of a branch name then git describe --tags --long will just output 0 commits ahead of that tag name, like for example `release_2_2_4-0-g9331a2e959` (which is fine for me, since because it is a tag it is fixed, no matter how often I pull it will stay there).

Branch names are actually very much like tags, the only difference is they automatically move forward when you commit while a tag stays fixed at that commit. Both of them are actually just named labels attached to a specific commit, tags will always stay where they have been placed, branches will automatically move forward with every new commit and always mark the tip of a branch.

Since `git describe --tags` always searches the current branch backwards until it comes across a tag (any tag, the first tag it finds on its way backward) and then outputs that tag name and the distance from it it should always output something meaningful as long as there are tags in strategic places that have a meaningful names.

At least it is more meaningful than the naked commit hash, it includes a number that counts upwards from the most recent "milestone" and it is up to the devs to place tags with meaningful names at meaningful points in the tree. Fortunately in git the devs can always add more tags later if they find they forgot to mark an important point.

I would always use git describe --tags (or git describe --tags --long) and if you find a branch where this really does not find a meaningful tag that marks the beginning of that branch we could ask the devs to add a tag at the beginning of the branch.
