### ISSUE TITLE
Build fail on MacOSX embedded or trunk fpcmkcfg not found

### ISSUE THREAD

**Issue by michael-ring** [LongDirtyAnimAlf/fpcupdeluxe#414]
I downloaded latest V2.0.1c and tried building both fpc+lazarus in either trunk/trunk or embedded/trunk.
Both fail with same error 

/Users/ring/fpcupdeluxe-test/fpc/bin/x86_64-darwin/fpcmkcfg not found.

Going to install/update FPC and Lazarus with given options.
FPCUP(deluxe) is starting up.

FPCupdeluxe basedir:       /Users/ring/fpcupdeluxe-test
Bootstrap dir:             /Users/ring/fpcupdeluxe-test/fpcbootstrap

FPC URL:                   https://gitlab.com/freepascal.org/fpc/source
FPC source directory:      /Users/ring/fpcupdeluxe-test/fpcsrc
FPC install directory:     /Users/ring/fpcupdeluxe-test/fpc
FPC options:               

Lazarus URL:               https://gitlab.com/freepascal.org/lazarus/lazarus
Lazarus source directory:  /Users/ring/fpcupdeluxe-test/lazarus
Lazarus install directory: /Users/ring/fpcupdeluxe-test/lazarus
Lazarus options:           -g -gl -O1

Please stand back and enjoy !

20-8-21 13:53:44: fpcupdeluxe: V412 (20210818) started.
FPCUPdeluxe V2.0.1c for x86_64-darwin running on macOS 11.5.2

Checking dev-libs for: cocoa
fpcupdeluxe: info: FPCNativeInstaller (CleanModule: FPC): No FPC source directory (/Users/ring/fpcupdeluxe-test/fpcsrc) found [yet] ... nothing to be done
Found valid bsdtar application.
Found valid make application.
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): Start checkout/update of FPC sources.
fpcupdeluxe: Executing: /usr/bin/git log -n 1 --grep=^git-svn-id: (working dir: /Users/ring/fpcupdeluxe-test/fpcsrc)
fpcupdeluxe: Executing: /usr/bin/git log -g -1 --pretty=oneline (working dir: /Users/ring/fpcupdeluxe-test/fpcsrc)
fpcupdeluxe: Executing: /usr/bin/git describe --tags --all --long --always (working dir: /Users/ring/fpcupdeluxe-test/fpcsrc)
fpcupdeluxe: Executing: /usr/bin/git describe --tags --long --always (working dir: /Users/ring/fpcupdeluxe-test/fpcsrc)
fpcupdeluxe: info: FPCNativeInstaller (GitClient: FPC): Running GIT checkout or update.
fpcupdeluxe: Executing: /usr/bin/git status --porcelain (working dir: /Users/ring/fpcupdeluxe-test/fpcsrc)
fpcupdeluxe: Executing: /usr/bin/git clone --recurse-submodules -b main https://gitlab.com/freepascal.org/fpc/source/ /Users/ring/fpcupdeluxe-test/fpcsrc (working dir: /Users/ring/fpcupdeluxe-test/fpcsrc)
Cloning into '/Users/ring/fpcupdeluxe-test/fpcsrc'...
Updating files:  26% (5358/20103)
Updating files:  27% (5428/20103)
Updating files:  28% (5629/20103)
Updating files:  29% (5830/20103)
Updating files:  30% (6031/20103)
Updating files:  31% (6232/20103)
Updating files:  32% (6433/20103)
Updating files:  33% (6634/20103)
Updating files:  34% (6836/20103)
Updating files:  35% (7037/20103)
Updating files:  36% (7238/20103)
Updating files:  37% (7439/20103)
Updating files:  38% (7640/20103)
Updating files:  39% (7841/20103)
Updating files:  40% (8042/20103)
Updating files:  41% (8243/20103)
Updating files:  42% (8444/20103)
Updating files:  43% (8645/20103)
Updating files:  44% (8846/20103)
Updating files:  45% (9047/20103)
Updating files:  46% (9248/20103)
Updating files:  47% (9449/20103)
Updating files:  47% (9610/20103)
Updating files:  48% (9650/20103)
Updating files:  49% (9851/20103)
Updating files:  50% (10052/20103)
Updating files:  51% (10253/20103)
Updating files:  52% (10454/20103)
Updating files:  53% (10655/20103)
Updating files:  54% (10856/20103)
Updating files:  55% (11057/20103)
Updating files:  56% (11258/20103)
Updating files:  57% (11459/20103)
Updating files:  58% (11660/20103)
Updating files:  59% (11861/20103)
Updating files:  60% (12062/20103)
Updating files:  61% (12263/20103)
Updating files:  62% (12464/20103)
Updating files:  63% (12665/20103)
Updating files:  64% (12866/20103)
Updating files:  65% (13067/20103)
Updating files:  66% (13268/20103)
Updating files:  67% (13470/20103)
Updating files:  68% (13671/20103)
Updating files:  69% (13872/20103)
Updating files:  70% (14073/20103)
Updating files:  71% (14274/20103)
Updating files:  72% (14475/20103)
Updating files:  73% (14676/20103)
Updating files:  74% (14877/20103)
Updating files:  75% (15078/20103)
Updating files:  76% (15279/20103)
Updating files:  77% (15480/20103)
Updating files:  77% (15607/20103)
Updating files:  78% (15681/20103)
Updating files:  79% (15882/20103)
Updating files:  80% (16083/20103)
Updating files:  81% (16284/20103)
Updating files:  82% (16485/20103)
Updating files:  83% (16686/20103)
Updating files:  84% (16887/20103)
Updating files:  85% (17088/20103)
Updating files:  86% (17289/20103)
Updating files:  87% (17490/20103)
Updating files:  88% (17691/20103)
Updating files:  89% (17892/20103)
Updating files:  90% (18093/20103)
Updating files:  91% (18294/20103)
Updating files:  92% (18495/20103)
Updating files:  93% (18696/20103)
Updating files:  94% (18897/20103)
Updating files:  95% (19098/20103)
Updating files:  96% (19299/20103)
Updating files:  97% (19500/20103)
Updating files:  98% (19701/20103)
Updating files:  99% (19902/20103)
Updating files: 100% (20103/20103)
Updating files: 100% (20103/20103), done.
fpcupdeluxe: Executing: /usr/bin/git rev-parse --abbrev-ref HEAD (working dir: /Users/ring/fpcupdeluxe-test/fpcsrc)
main
fpcupdeluxe: Executing: /usr/bin/git pull (working dir: /Users/ring/fpcupdeluxe-test/fpcsrc)
Already up to date.
fpcupdeluxe: Executing: /usr/bin/git log -g -1 --pretty=oneline (working dir: /Users/ring/fpcupdeluxe-test/fpcsrc)
a45123a87b2b5440928e4bcd053a9b784534816d HEAD@{0}: clone: from https://gitlab.com/freepascal.org/fpc/source/
fpcupdeluxe: Executing: /usr/bin/git describe --tags --all --long --always (working dir: /Users/ring/fpcupdeluxe-test/fpcsrc)
heads/main-0-ga45123a87b
fpcupdeluxe: Executing: /usr/bin/git log -n 1 --grep=^git-svn-id: (working dir: /Users/ring/fpcupdeluxe-test/fpcsrc)
commit b878d461c8e7f1eaa4a928c285f0208ea8f5ad7a
Author: nickysn <nickysn@gmail.com>
Date:   Fri Jul 23 23:23:47 2021 +0000
    * fixed compilation for i8086 and 8-bit targets after r49622. The conditional
      ifdef checks for the ordinal helpers rewritten to be less dependendant on
      defines, such as CPU16/CPU32/CPU64 and instead use sizeof(integer),
      sizeof(nativeint) and sizeof(nativeuint)
    
    git-svn-id: trunk@49634 -
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC was at revision/hash: FRET_UNKNOWN_REVISION
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC is now at revision/hash: main-0-ga45123a87b
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): No FPC patches defined.
fpcupdeluxe: info: FPCNativeInstaller (BuildModule: RevisionFPC): Building module RevisionFPC...
fpcupdeluxe: info: FPC native builder: Detected source version FPC (source): 3.3.1
fpcupdeluxe: info: FPCNativeInstaller (BuildModule: RevisionFPC): To compile this FPC, we need (required) a compiler with version 3.2.0 or 3.2.2
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Looking for official FPC bootstrapper with version 3.2.2
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Looking for official FPC bootstrapper with version 3.2.0
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Looking for official FPC bootstrapper with version 3.0.4
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Got a V3.0.4 bootstrap compiler from official FPC bootstrap sources.
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Now looking for a better [version] bootstrap compiler from Github FPCUP(deluxe) releases.
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Looking online for a FPCUP(deluxe) bootstrapper with name: fpcup-3_2_2-x86_64-darwin-ppcx64
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Success: found a FPCUP(deluxe) bootstrapper with version 3.2.2
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Got a better [version] bootstrap compiler from FPCUP(deluxe) bootstrap binaries.
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): This is important for OSX Cataline, that dislikes FPC multi-arch binaries.
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Check if we already have a bootstrap compiler with version 3.2.2
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): No correct bootstrapper. Going to download bootstrapper from https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/bootstrappers_v1.0/fpcup-3_2_2-x86_64-darwin-ppcx64
fpcupdeluxe: info: FPCNativeInstaller (GetFile): Downloading https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/bootstrappers_v1.0/fpcup-3_2_2-x86_64-darwin-ppcx64
Download progress fpcup-3_2_2-x86_64-darwin-ppcx64: starting.
Download progress fpcup-3_2_2-x86_64-darwin-ppcx64: Starting download.
Download progress fpcup-3_2_2-x86_64-darwin-ppcx64: download ready !
fpcupdeluxe: info: FPCNativeInstaller (GetFile): Success. Going to copy /Users/ring/fpcupdeluxe-test/tmp/fpcup00000/ppcx64 to /Users/ring/fpcupdeluxe-test/fpcbootstrap/ppcx64
fpcupdeluxe: info: FPCNativeInstaller (BuildModule: RevisionFPC): To compile this FPC, we will use a fresh compiler with version : 3.2.2
Found valid make application.
fpcupdeluxe: info: FPC native builder: Using FPC bootstrap compiler with version: 3.2.2
fpcupdeluxe: Executing: /usr/bin/make --jobs=16 FPMAKEOPT=--threads=16 PP=/Users/ring/fpcupdeluxe-test/fpcbootstrap/ppcx64 FPCMAKE=/Users/ring/fpcupdeluxe-test/fpc/bin/x86_64-darwin/fpcmake PPUMOVE=/Users/ring/fpcupdeluxe-test/fpc/bin/x86_64-darwin/ppumove PREFIX=/Users/ring/fpcupdeluxe-test/fpc INSTALL_PREFIX=/Users/ring/fpcupdeluxe-test/fpc FPCDIR=/Users/ring/fpcupdeluxe-test/fpcsrc INSTALL_BINDIR=/Users/ring/fpcupdeluxe-test/fpc/bin/x86_64-darwin OS_SOURCE=darwin CPU_SOURCE=x86_64 OS_TARGET=darwin CPU_TARGET=x86_64 OPT=-Fl/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -XR/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -WM10.8 -Sg -vw-n-h-l-d-u-t-p-c- --directory=/Users/ring/fpcupdeluxe-test/fpcsrc/compiler revision (working dir: /Users/ring/fpcupdeluxe-test/fpcsrc/compiler)
/Library/Developer/CommandLineTools/usr/bin/make revision.inc
/Library/Developer/CommandLineTools/usr/bin/make revision.inc REVINC=force
/bin/echo "'8687-ga45123a87b'" > revision.inc
/Users/ring/fpcupdeluxe-test/fpc/bin/x86_64-darwin/fpcmkcfg not found.
/Users/ring/fpcupdeluxe-test/fpc/bin/fpcmkcfg not found.
fpcupdeluxe: ERROR: FPCNativeInstaller (BuildModuleCustom: RevisionFPC): Could not find fpcmkcfg executable. Aborting.

**Comment by LongDirtyAnimAlf** [comment]
Confirmed.
I have deleted this release due to this error !
Sorry about this.
