### ISSUE TITLE
No system wide libQt5Pas.so found. Some QT5 trickery will be used

### ISSUE THREAD

**Issue by prof7bit** [LongDirtyAnimAlf/fpcupdeluxe#417]
Using the qt version on Kubuntu.

It works, it has always been working. I just noticed the message that appears when I start fpcupdeluxe:

```
No system wide libQt5Pas.so found. Some QT5 trickery will be used
```
But I have it installed:

```
$ ldconfig -p | grep libQt5Pas
        libQt5Pas.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libQt5Pas.so.1
        libQt5Pas.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libQt5Pas.so
```
so whatever trickery it does, it seems to work but it does not seem to be necessary.

**Comment by LongDirtyAnimAlf** [comment]
This was a bugger of fpcupdeluxe when looking for QT5.
The trickery relates to rpath linking of the final executable and copy of QT5 libs.
A new release (few days) will solve.
