### ISSUE TITLE
[Feature] git stash / git stash pop (or apply the generated diff automatically again after pull)

### ISSUE THREAD

**Issue by prof7bit** [LongDirtyAnimAlf/fpcupdeluxe#418]
for small changes or quick experiments it is often convenient to just hack away in the working copy without making a new branch and then rebase these uncommitted changes to upstream on every pull with the sequence

```
git stash
git pull
git stash pop

```
`git stash` is the equivalent of fpcupdeluxe storing a diff of uncommitted changes before resetting the working copy to the latest upstream commit. The difference is it does not create a diff file but rather keeps it in an internal stack of commits in the local repo that can be manipulated and used with git commands.

The equivalent of `git stash pop` would be to apply the latest diff and delete it again after the latest upstream has been checked out, so all uncommitted changes are applied again on top of current upstream before compiling the sources. And once the changes are tested and working it should be easy for the user to use the local changes to create a pull request or create a diff (compatible with git apply) to attach to a bug report or feature request, or maybe even a local branch to better manage it if it is not yet ready to submit.

Using the stash mechanism instead of creating a diff would probably better integrate into the git workflow, one can for example easily create a new branch from the current stash if needed. But for most purposes it would probably be totally enough to just (optionally, make it a checkbox in the settings) automatically re-apply the diff that was automatically created.

### Feature 2
In the same way you can already add patch files to apply after pull you could specify the name of a local branch to automatically merge after pull and before compile. And fpcupdeluxe could also (optionally) try to rebase this branch to upstream after every pull. This would be a killer feature!

### Feature 3 
I don't think there is a need to create more than one diff per commit hash, currently you are appending more and more "f" to the end of the filename, I would just overwrite the previous one.

**Comment by LongDirtyAnimAlf** [comment]
Unfortunately, I will never be able to implement this. Time and resources are lacking.
You could/might try to fork fpcupdeluxe and implement this. And request a pull.
Sorry about this.

**Comment by prof7bit** [comment]
Maybe instead just allow to execute a user provided command/script/batch after pull and before compile. This would allow for arbitrary complexity, users could implement any (and more) of the above mentioned things, for example merge all their half dozen open merge request branches, or test if they can still merge or need updating, etc.

Would this be an acceptable compromise?

**Comment by LongDirtyAnimAlf** [comment]
This has been asked before. So this might be a good idea.
Please elaborate on this feature.
To you want a custom shell script to be executed. Or only GIT command from a test based command list. Or a kind of terminal window.
Please let me know about your ideas on how to implement this.
Thanks.

**Comment by prof7bit** [comment]
A custom shell script would be best. For example right now I would like to use it to issue a bunch of merge commands for a bunch of local branches with small (unfinished, untested) Lazarus fixes and translation updates I am working on. But I could also want to execute arbitrary other commands. A shell script would be most practical. Its output and stderr could be redirected to the lower log window, so it is immediately visible if it produces errors. The script should be executed with working directory set to the root directory of the repo, one script for FPC, one for Lazarus. The script itself can be in any location, so users can organize this along with their patches in a dedicated separate folder.
