### ISSUE TITLE
Desktop link must not contain relative path in Exec entry.

### ISSUE THREAD

**Issue by prof7bit** [LongDirtyAnimAlf/fpcupdeluxe#419]
This will not work (anymore): 
```
Exec=./lazarus --pcp="/home/bernd/fpcupdeluxe/config_lazarus" %f
Path=/home/bernd/fpcupdeluxe/lazarus/
```
At least not on Kubuntu 21.04:

```
--($)-- plasmashell --version
plasmashell 5.21.4
--(bernd@Saturn)-(/home/bernd)--
--($)-- kf5-config --version
Qt: 5.15.2
KDE Frameworks: 5.80.0
kf5-config: 1.0
```

It will complain with 'Error code 100, "./lazarus" can not be found'

The specification https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables says either a full path or only the name that can be found in $PATH.

I remember this has been working in the past, but I am not sure whether you changed something or whether it happened after I upgraded to Kubuntu 21.04 recently, because for a long time already I have been using only my own manually created shortcut and ignored / deleted the generated one. At work I have an older Kubuntu and next week I'm going to see if they changed something in KDE, because I remember I have been using these generated desktop links on that machine quite recently and they worked.

**Comment by LongDirtyAnimAlf** [comment]
I am on a 2 week trip to the mountains ...
With only a telephone ...
Will resume activities in 2 weeks !

**Comment by prof7bit** [comment]
Enjoy your vacation, but please don't fall off a cliff while climbing there!

Meanwhile I have determined that they changed something in recent KDE versions, on the LTE version it still works.
