### ISSUE TITLE
fpcupdeluxe 2.0.1 i386 compilation "BuildUnit_oracle.pp" failed

### ISSUE THREAD

**Issue by supercim** [LongDirtyAnimAlf/fpcupdeluxe#422]
![fpcupdeluxe_n](https://user-images.githubusercontent.com/46600156/130458287-43332047-368c-409c-ab8f-2f8a8f7b6ce5.jpg)

After deleted old installation of fpcupdeluxe ('c:\fpcupdeluxe'),  whether I choose to install only ide or ide/fpc i receive this error:
"Error inside worker thread for package oracle: Compilation of "BuildUnit_oracle.pp" failed"

**Comment by synopse** [comment]
Try with Lazarus stable or 2.0.12 instead of trunk.

**Comment by supercim** [comment]
It doesn't work, same error with 2.0.12

**Comment by LongDirtyAnimAlf** [comment]
https://lists.freepascal.org/pipermail/fpc-devel/2021-August/043968.html

**Comment by LongDirtyAnimAlf** [comment]
Seems to be a known problem with a lot of discussions !!

**Comment by supercim** [comment]
In a old virtual machine with windows 10 fpcupdeluxe 32 bit works fine: in this machine they are not present
 'common.dll' neither in ' 'c:\windows\system32' nor in 'c:\windows\syswow64'.... In the updated windows 10, where fpcupdeluxe 
gave error , are present both files: deleted both, fpcupdeluxe 32bit works well. Thank you very much

**Comment by prof7bit** [comment]
Wow! From the linked thread: "On 64bit Windows system32 contains only 64 bit system files. syswow64 
contains only 32 bit files", so the folder with the name "64" is for 32 bit files and the folder with name "32" is for 64 bit files. This is a truly intuitive concept! Nobody will accidentally make his installer install files into the wrong folders anymore, not even Microsoft themselves... oh, wait...

**Comment by LongDirtyAnimAlf** [comment]
As this is not related to fpcupdeluxe, will close.
