### ISSUE TITLE
Qt5: always overwriting the config for main window position and size

### ISSUE THREAD

**Issue by prof7bit** [LongDirtyAnimAlf/fpcupdeluxe#423]
In installerlazarus.pas, Lines 1142..1150 there is the following code:

```
        {$ifdef LCLQT5}
        //Set default sizes and position
        LazarusConfig.SetVariable(EnvironmentConfig, 'Desktops/Desktop1/MainIDE/CustomPosition/Left', '10');
        LazarusConfig.SetVariable(EnvironmentConfig, 'Desktops/Desktop1/MainIDE/CustomPosition/Top', '30');
        LazarusConfig.SetVariable(EnvironmentConfig, 'Desktops/Desktop1/MainIDE/CustomPosition/Width', '900');
        LazarusConfig.SetVariable(EnvironmentConfig, 'Desktops/Desktop1/MainIDE/CustomPosition/Height', '60');
        LazarusConfig.SetVariable(EnvironmentConfig, 'Desktops/Desktop1/MainIDE/Visible/Value', 'True');
        {$endif}

```
Is this really needed?

Maybe you could use SetVariableIfNewFile(), depending on what the actual reason was for this workaround in the first place, maybe these lines could also be removed entirely.

Also a default for left, top of 10, 30 is very odd, I bet most people would want this to be 0, 0.

This is only a minor annoyance, but it is still a little bit annoying to have the main window lose size and position every time I have run fpcupdeluxe. Also why is it only used for Qt5, shouldn't this be widgetset-agnostic? At least a bit of documentation would not hurt to better understand why these lines are there (if they still need to be there and it is not just a leftover from older times, from the git blame it looks like these are at least 3 years old but I couldn't figure out why you added it). I have never had any problems while using GTK2 and having Lazarus figure out its default config values on its own, so I would expect the same outcome in Qt5 too.

**Comment by prof7bit** [comment]
I have added a pull request, so you need only on mouse click to remove these lines if you wish.

**Comment by LongDirtyAnimAlf** [comment]
See pull. Thanks !
