### ISSUE TITLE
revision.inc contains text without quotation?

### ISSUE THREAD

**Issue by eugeneloza** [LongDirtyAnimAlf/fpcupdeluxe#427]
I'm experiencing a weird issue with FPCUpDeluxe both in 2.0.1 release and latest 2.0.1b while trying to install either Trunk or Stable:

![2021-08-30 00_55_32-Greenshot](https://user-images.githubusercontent.com/10726162/131266637-d0491b94-783d-4974-9553-0012c6a9a892.png)

Indeed, C:\FPC\fpcsrc\compiler\revision.inc contains text without quotations:

[revision.zip](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/7073286/revision.zip)

And therefore e.g. 

```Pascal
function full_version_string:string;
begin
  full_version_string := version_nr+'.'+release_nr+'.'+patch_nr+minorpatch
{$ifdef REVINC}
  +'-'+{$i revision.inc}
{$endif REVINC}
  ;
end;
```
fails to produce a `String` result.

However, a few other users reported that they don't have any issues installing new versions with the same 2.0.1b version of FPCUpDeluxe under the same Windows 10 x64 bit. I wonder, can it be some leftover from previous installations? Some system environment variable can get in the way? `Echo` is broken by some installed app, like `Mingw64`?

**Comment by LongDirtyAnimAlf** [comment]
Yes, echo is broken by cygwin or mingw in the path. A new release will try to solve this.
This issue is kept open until new release.

**Comment by LongDirtyAnimAlf** [comment]
You are welcome to try this pre-release:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/2.0.1d

**Comment by eugeneloza** [comment]
Nope, it fails with the same error message:
![2021-09-08 14_14_43-Greenshot](https://user-images.githubusercontent.com/10726162/132499938-ff29b199-0c6f-432c-9452-5ca2513a17ef.png)

**Comment by LongDirtyAnimAlf** [comment]
Please test:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/2.0.1e

**Comment by eugeneloza** [comment]
Now the error message is different (for some reason it can't find "echotime"):
![2021-09-08 22_41_04-Greenshot](https://user-images.githubusercontent.com/10726162/132574905-31716fc5-c7e2-44f4-b303-add30e5d2aa4.png)

And revision.inc is properly quoted:
[revision.zip](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/7131442/revision.zip)

**Comment by eugeneloza** [comment]
Tried getting stable FPC+Lazarus with the same result.

**Comment by LongDirtyAnimAlf** [comment]
My bag of tricks is nearly empty.
New binary. Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/2.0.1e/fpcupdeluxe-x86_64-win64.exe

**Comment by eugeneloza** [comment]
Again complains about "echotime"

![2021-09-09 00_38_58-Greenshot](https://user-images.githubusercontent.com/10726162/132589284-318cfb98-c54c-4c01-8af8-3f45bb959dca.png)

**Comment by LongDirtyAnimAlf** [comment]
New binaries. Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/2.0.1e
This is my last effort to solve. My tricks are exhausted unfortunately.

**Comment by eugeneloza** [comment]
Nope, unfortunately it returned to the "previous state" - when the `revision.inc`

![2021-09-10 20_42_11-Greenshot](https://user-images.githubusercontent.com/10726162/132895420-f1e7320b-9b20-4039-a234-e0c3aa911e69.png)

I guess it's the right time for me to try building FpcUpDeluxe from the sources then :) I think we can close this issue, I'll ping you if I'll be able to come up with any working solution.

**Comment by LongDirtyAnimAlf** [comment]
Thanks !
