### ISSUE TITLE
allow patches with prefix a/ and b/ (try using -p1 if -p0 fails)

### ISSUE THREAD

**Issue by prof7bit** [LongDirtyAnimAlf/fpcupdeluxe#428]
When using git it will become commonplace to have patches formatted with `git diff` or `git format-patch` and these prepend by default prefixes like a/ and b/ in front of the paths. A patch created by `git diff` and usable by `git apply` or by `patch -p1` starts with a header like this:

```
diff --git a/ide/projectinspector.pas b/ide/projectinspector.pas
index 26ba1a2244..4ee5b58a49 100644
--- a/ide/projectinspector.pas
+++ b/ide/projectinspector.pas
```

while a patch acceptable by `patch -p0` (current only possibility in fpcupdeluxe) would need to start like this:

```
diff --git a/ide/projectinspector.pas b/ide/projectinspector.pas
index 26ba1a2244..4ee5b58a49 100644
--- ide/projectinspector.pas
+++ ide/projectinspector.pas

```
As it turns out now I have to edit all patch files I receive from devs while trying to test their changes by hand to remove the prefixes or tell them to generate then with `git diff --no-prefix` which is very uncommon and nobody does this.

I would change the patching logic such that if it fails to apply the patch with -p0 also try again to apply it with -p1. Or maybe even the other way around and try -p1 first because most patches will now come straight out of git and will be of the -p1 type.

Also you should add the -t option for batch processing, so it outputs an error instead of trying to read user input from stdin.

**Comment by LongDirtyAnimAlf** [comment]
You are welcome to try this pre-release:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/2.0.1d

**Comment by LongDirtyAnimAlf** [comment]
Please test:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/2.0.1e

**Comment by prof7bit** [comment]
Is working, tested with both types of patches :-)

closing this bug
