### ISSUE TITLE
It is ill-advised to cross from Windows 64 bit message

### ISSUE THREAD

**Issue by i2van** [LongDirtyAnimAlf/fpcupdeluxe#429]
What is the meaning of `It is ill-advised to cross from Windows 64 bit` message?https://github.com/LongDirtyAnimAlf/fpcupdeluxe/blob/c73e89a4fc19fafe6825d6e381686c74242bfd8e/fpcupdeluxemainform.pas#L2335 I have never experienced issues with cross-compiling under x64 (linux, darwin).

Could this message be suppressed in options? It prevents updating all cross-compilers in batch mode; it is shown for **each cross-compiler**, not only for first one.

**Comment by LongDirtyAnimAlf** [comment]
The message should be suppressed in batch-mode. This was a bugger and has been fixed in sources.
The FPC devs themselves are against the use of Win64 for crossing. That is the source of this message.

**Comment by i2van** [comment]
For those who interested I [asked for clarification](https://gitlab.com/freepascal.org/fpc/source/-/issues/39348) on FreePascal forum.

**Comment by zedxxx** [comment]
I use fpcupdeluxe x64 and want to install FPC for win32 and win64 targets. 

1. FPC for win64 installed from "Basic" tab without any problem.
2. Installing FPC for win32 from "Cross" tab and here I got this message. So, I try ignore it and install cross compiler for win32. It also installs without problems.

Now, according to the issue with `Extended` type I wrote this test:

```
program TestProject;
var
  D: Double;
  E: Extended;
begin
  E := 3.14;
  Writeln(E);

  Writeln('Double:   ', SizeOf(D) );
  Writeln('Extended: ', SizeOf(E) );
end.
```
for win32 it output `8` and `10`, for win64 - `8` and `8` (for win64 Extended is an alias for Double) - so all seems to work!

Can you explain what is the problem with win32 cross-compiler under win64 and what should I do to get both win32 and win64 compilers with fpcupdeluxe?

**Comment by LongDirtyAnimAlf** [comment]
To get both win32 and win64, just install win32. It will also install win64 cross-compiler.
This is the method advised by the FPC devs.
Few years ago, an 80-bit softfloat (extended) utility  was added into FPC. This 80 bit soft emulation is enabled by fpcupdeluxe to enable correct crossing from win64 to win32. Its slow and sometimes not accurate.

**Comment by zedxxx** [comment]
Should I use fpcupdeluxe x64 or x32?

I switched to x32 and install FPC from Basic tab. It installs only win32 compiler. Cross-compiler is not automatically installed. Is it a bug?

**Comment by LongDirtyAnimAlf** [comment]
You should I use fpcupdeluxe  x32.
If you press "install/update FPC+Laz", the cross-compiler for win64 will be automagically installed.
If you press "FPC only", the cross-compiler for win64 needs to be installed by you, in the cross-tab.
