### ISSUE TITLE
Ugly font spacing on MacOSX 

### ISSUE THREAD

**Issue by michael-ring** [LongDirtyAnimAlf/fpcupdeluxe#430]
The font spacing in 2.0.1d's terminal window looks pretty ugly on my mac, please see for yourself:

<img width="938" alt="Bildschirmfoto 2021-09-08 um 12 55 24" src="https://user-images.githubusercontent.com/6280531/132497542-38a97dc9-1d46-423f-93f6-9abd698a8dc7.png">

**Comment by LongDirtyAnimAlf** [comment]
Hmmmmm ... the default font has been changed by user request.
Perhaps it should be reverted for MaxOSX.

**Comment by michael-ring** [comment]
New Font is nice, is this a fixed width font? look at 'We'  and 'wi' (in Darwin) it looks as if a non fixed width font is used@fixed width....

**Comment by michael-ring** [comment]
Welcome back from your vacation!

**Comment by LongDirtyAnimAlf** [comment]
Please test:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/2.0.1e

**Comment by LongDirtyAnimAlf** [comment]
> Welcome back from your vacation!

You're welcome !!

**Comment by prof7bit** [comment]
Ok, maybe the Monospace alias does not work on all systems :-(

This change was my fault.

But at least it can be configured now.

**Comment by michael-ring** [comment]
fixed, thank you!

**Comment by michael-ring** [comment]
Saw you fixed the font issue, looks nice with the new font!
