### ISSUE TITLE
fpc embedded version is missing in gitlab view

### ISSUE THREAD

**Issue by michael-ring** [LongDirtyAnimAlf/fpcupdeluxe#432]
Sniff.. I do not find the embedded version for fpc in the gitlab view, accident or on purpose?

**Comment by LongDirtyAnimAlf** [comment]
No rational !
I need your help in this.
The frontend with GitLab checkbox was made when only FPC sources were made available on GitLab.
So, the choice for GitLab resulted in official FPC and Lazarus sources. All other sources were available on GitHub and friends.
Things have changed. And embedded has also become available on GitLab.
So GitLab checkbox might or might not show all GitLab sources or only official FPC/Laz sources.
I would welcome your opinion about this.
Thanks.

**Comment by michael-ring** [comment]
Honestly, I do not understand at all why there is a differentiation between Gitlab Sources and other sources. svn stuff is dead now and graeme has taken down his mirrors, so from what I can tell the non-gitlab view is a mess right now because in some cases building works because your mirror gets used but in other cases things crash & burn.

For me, the more logical choice would be to have a view with current stuff, no matter where it comes from and then the 2nd tab with legacy like all the zip files you offer which are duplicates to the branches on gitlab.

I remember when I first used fpcupdeluxe I was overwhelmed by the huge number of choices, which stable should I use, the different stable versions are scattered arround in the list and which is the best one to use????

I know there must be a good reason to offer so much choice, but can't this be the content of the non-default view and the default view can stay clean and relatively easy to understand.  

Unless of course there is a technical reason that you need to separate github from gitlab, but what should that be, in the end both sources use git.

**Comment by LongDirtyAnimAlf** [comment]
> Unless of course there is a technical reason that you need to separate github from gitlab

Yes, there is a technical reason. But, being software, this can be changed.

I will review the default view.
(the default view will already be GitLab in the new release)

**Comment by LongDirtyAnimAlf** [comment]
New binaries. Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/2.0.1e
Please note:
Make a new install to prevent settings from an old install influencing the new binaries.
Run fpcupdeluxe from an empty directory.

**Comment by michael-ring** [comment]
Hmmm.... fpcupdeluxe is doing mostly nothing:

I tried both trunk and embedded, same result, it does also not matter if I am in gitlab view or old view:


Going to install/update FPC and Lazarus with given options.
FPCUP(deluxe) is starting up.

FPCupdeluxe basedir:       /Users/ring/fpcupdeluxe
Bootstrap dir:             /Users/ring/fpcupdeluxe/fpcbootstrap

FPC URL:                   https://gitlab.com/freepascal.org/fpc/source
FPC source directory:      /Users/ring/fpcupdeluxe/fpcsrc
FPC install directory:     /Users/ring/fpcupdeluxe/fpc
FPC options:               

Lazarus URL:               https://gitlab.com/freepascal.org/lazarus/lazarus
Lazarus source directory:  /Users/ring/fpcupdeluxe/lazarus
Lazarus install directory: /Users/ring/fpcupdeluxe/lazarus
Lazarus options:           -g -gl -O1

Please stand back and enjoy !

10-9-21 17:40:02: fpcupdeluxe: V415 (20210908) started.
FPCUPdeluxe V2.0.1e for x86_64-darwin running on macOS 11.5.2

Checking dev-libs for: cocoa
fpcupdeluxe: info: FPCNativeInstaller (CleanModule: FPC): No FPC source directory (/Users/ring/fpcupdeluxe/fpcsrc) found [yet] ... nothing to be done


ERROR: Fpcupdeluxe fatal error !
Sequencer (FPC): Failure running fpcupdeluxe: error executing sequence FPC
Sequencer (Default): Failure running fpcupdeluxe: error executing sequence Default

**Comment by LongDirtyAnimAlf** [comment]
Sorry about this.
New binaries. Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/2.0.1e

**Comment by michael-ring** [comment]
new binaries work for both aarch64 and x86_64, thank you!
