### ISSUE TITLE
Creating a desktop icon fails on darwin-aarch64

### ISSUE THREAD

**Issue by michael-ring** [LongDirtyAnimAlf/fpcupdeluxe#433]
On darwin-x86_64 a desktop icon can be created as usual, but on aarch64 I see the right text in the buildlog:
Fpcupdeluxe has created a shortcut link in your home-directory to start Lazarus.
Shortcut-link: Lazarus_fpcupdeluxe-test
Lazarus MUST be started with this link !!
Fpcupdeluxe has also (tried to) create a desktop shortcut with the same name.

but there is no link on desktop.

**Comment by michael-ring** [comment]
Still an issue in release from today

**Comment by LongDirtyAnimAlf** [comment]
Unfortunately, I will never be able to solve this. No suitable system available.
If needed and necessary, you might help by debugging on your system.

**Comment by nop-code** [comment]
No issues here, shortcut "Lazarus_fpcupdeluxe" got placed on the desktop as advertised.
FPCUPdeluxe V2.0.1e (reports V2.2.0a in the about-dialog)
MacBook Air M1, macOS 11.5.2

**Comment by michael-ring** [comment]
Desktop Icons are now also working again for me, closing...
