### ISSUE TITLE
Error on 2.0.1e MacOS 11.5.2

### ISSUE THREAD

**Issue by qindj** [LongDirtyAnimAlf/fpcupdeluxe#435]
Hi, admin

something wrong on 2.0.1e:

`
FPCUP(deluxe) is starting up.

FPCupdeluxe basedir:       /Users/qindj/fpcupdeluxe
Bootstrap dir:             /Users/qindj/fpcupdeluxe/fpcbootstrap

FPC URL:                   https://gitlab.com/freepascal.org/fpc/source
FPC source directory:      /Users/qindj/fpcupdeluxe/fpcsrc
FPC install directory:     /Users/qindj/fpcupdeluxe/fpc
FPC options:               

Lazarus URL:               https://gitlab.com/freepascal.org/lazarus/lazarus
Lazarus source directory:  /Users/qindj/fpcupdeluxe/lazarus
Lazarus install directory: /Users/qindj/fpcupdeluxe/lazarus
Lazarus options:           -g -gl -O1

Please stand back and enjoy !

13-9-21 08:40:00: fpcupdeluxe: V415 (20210908) started.
FPCUPdeluxe V2.0.1e for x86_64-darwin running on macOS 11.5.2

Checking dev-libs for: cocoa
fpcupdeluxe: info: FPCNativeInstaller (CleanModule: FPC): No FPC source directory (/Users/qindj/fpcupdeluxe/fpcsrc) found [yet] ... nothing to be done

ERROR: Fpcupdeluxe fatal error !
Sequencer (FPC): Failure running fpcupdeluxe: error executing sequence FPC
Sequencer (Default): Failure running fpcupdeluxe: error executing sequence Default
`

re-download 2.0.1d, everything is ok.

**Comment by LongDirtyAnimAlf** [comment]
Please test newest release !

**Comment by qindj** [comment]
fixed, thanks!
