### ISSUE TITLE
When pulling from GitLab there is redirection

### ISSUE THREAD

**Issue by gcarreno** [LongDirtyAnimAlf/fpcupdeluxe#436]
Hey Don(@LongDirtyAnimAlf),

This is more of a small inconvenience than a bug, but when performing a `git pull` by hand I get:
```console
$ git pull
warning: redirecting to https://gitlab.com/freepascal.org/fpc/source.git/
```

So could you add the `.git` at the end of the URLs?

Please keep in mind I'm on Ubuntu 21.04 64b

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
I have seen this "inconvenience".
This behavior cannot be changed due to internal logic of fpcupdeluxe.
Sorry about this.

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

Okydokes, no problem then :smile: 

Cheers,
Gus
