### ISSUE TITLE
Somehow git processes, still running on background, are left open.

### ISSUE THREAD

**Issue by gcarreno** [LongDirtyAnimAlf/fpcupdeluxe#437]
Hey Don(@LongDirtyAnimAlf),

Please keep in mind that I'm on Ubuntu 21.04 64b.

So I finally bit the bullet and attempted to update my trunk install from the `SVN` it was, into the new `GIT` from GitLab.

Somehow, `fpcupdeluxe` is continuing to do it's thing but the `GIT` process it started has not finished.

I had to do a `killall git` to make sure the `GIT` process was dead.

This also means that the repos are not getting `pull`ed to completion and all this is baffling me cuz `TProcess` should not let you continue until the call that is made to `git pull` ends, right?

I'm now performing manual `git pull`s in order to get the repos in a correct state and I'll report further.

I'm also now suspicious of the call to `git fetch --tags`. I'm not sure it lingers in the background or not...

This is all very strange :-\

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

After trying to perform a manual pull it failed cuz the repo had no local branch.

Had a look at `.git/config` and indeed there was no `[branch "main"]` entry on that file.

Then I tried to add it and try a `git merge origin/main` since the fetch part of the pull was already done. But it exploded saying that it could not perform the merge since it would re-write `.gitignore`. ARGHHHH

Looks like the effort to have `fpcupdeluxe` do a `SVN` to `GIT` swap has some kinks to solve :)

Giving up for the time being and attempting a clean install :pray: 

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
> Giving up for the time being and attempting a clean install

Me too. It has been a bumpy road towards GIT. I am now leaving SVN behind.

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

Yeah, but have you made sure that the `GIT` processes are complete **BEFORE** anything else can continue?

I know this happened on the migration form `SVN` to `GIT`, but I still don't know if the regular update when already on `GIT` will **NOT** leave run away processes.

I think you should re-open this issue just because it's not `SVN` related but `GIT` related!

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
> Yeah, but have you made sure that the GIT processes are complete BEFORE anything else can continue?
Yes.
Please try to isolate this problem.
At this moment, I do not know how to reproduce and investigate.
So, please try to create a test-setup that shows this issue.

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

Oh crap, sorry, I completely forgot that you work with Windows and just have VMs for testing the Linux stuff :(

Yeah, I suppose I need to give you some type of reproducible pattern...

Will you re-open this issue or should I create a new one when I can get a concrete how to?

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
Please create a new issue with a reproduceable pattern. Thanks.

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

Okidokes, will do!! :smile: 

Cheers,
Gus
