### ISSUE TITLE
On the GUI downloader the OnActivate code uis run more than once, and it's MY FAULT

### ISSUE THREAD

**Issue by gcarreno** [LongDirtyAnimAlf/fpcupdeluxe#438]
Hey Don(@LongDirtyAnimAlf),

We both looked at the code and forgot to make sure that the `OnActivate` event's code of the form only runs once.

On Linux, if I click on the Main form and then click on the Downloader form again, for a while it flashes the info that it's assessing the file's size with the progress bar at 0...

It then resumes the download but I'm not even sure what's happening...

I'll need to have a look at MY code and then YOURS to make sure we didn't collectively effed up this :-\

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
Fixed ! Thanks for reporting.

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

MANY thanks!!

I've also fixed it on my original repo :smile: 

Cheers,
Gus
