### ISSUE TITLE
UI button "mORMot" overlaps the next button

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#440]
![Screenshot from 2021-09-25 21-12-37](https://user-images.githubusercontent.com/4154978/134781865-72bf4ad6-7e58-474f-b27d-e56fc6623c56.png)

**Comment by LongDirtyAnimAlf** [comment]
This is correct behavior. Just make the main window wider.
Or I might remove the Win95 button as it seems that this is not used by many.

**Comment by Alexey-T** [comment]
Better remove Win95 button...

**Comment by LongDirtyAnimAlf** [comment]
This behavior will not be changed. But some buttons might be removed in the future.
