### ISSUE TITLE
'Gus downloader' window

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#441]
![Screenshot from 2021-09-26 15-10-52](https://user-images.githubusercontent.com/4154978/134807441-318b039b-23e6-4972-90bf-ff5c6805fad5.png)

* make its wider, to 700 px wide, for example
* make the digits not be updated SO FAST (each 50msec), make the update only per each 2seconds.
* collapse the HOME dir to `~/`
* floating numbers are not needed here, pls make them integers (truncated)

**Comment by LongDirtyAnimAlf** [comment]
Everything was set to autosize, so this truncation should not happen. However, I will set the form width to a minimum of 700px.
As this is a borrowed piece of software, all other things will remain the same. The proposed changes might be considered as an improvement, but I will stick to the original authors preferences.
