### ISSUE TITLE
button 'Win95' doesn't have an icon

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#443]
![Screenshot from 2021-09-26 15-51-40](https://user-images.githubusercontent.com/4154978/134808804-cd199027-a19f-44d7-8f5f-22bbd2569e54.png)

**Comment by LongDirtyAnimAlf** [comment]
This has happened before with other icons too.
Will look into fixing it.

**Comment by LongDirtyAnimAlf** [comment]
Fixed. Next release.
