### ISSUE TITLE
[Enhancement] Get the filename label to shorten it's name

### ISSUE THREAD

**Issue by gcarreno** [LongDirtyAnimAlf/fpcupdeluxe#446]
Hey Don(@LongDirtyAnimAlf),

It's curious how sometimes things align: After I read about #441 I stumbled upon:
[How to shorten full path names?](https://forum.lazarus.freepascal.org/index.php/topic,52578.0.html)

And on that thread I've learned about:
```pas
uses
  FileCtrl;

  function MinimizeName(FileName: String; Canvas: TCanvas; MaxWidth: Integer): String;
```

From the thread, because `TLabel` descends from `TGraphicControl` which exposes a `TCanvas`, this should work.

So, could you please give it a try and thanks Don!!

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

As of [Release 1.4.8](https://github.com/gcarreno/TestDownloadProgressBar/releases/tag/v1.4.8) I'm now using the above mentioned function:
```pas
implementation

uses
{...}
, FileCtrl
{...}
;

procedure TfrmThreadSequential.FormActivate(Sender: TObject);
{...}
begin
{...}
    lblTop.Caption:= MiniMizeName(
      FDownloads[index].Filename,
      lblTop.Canvas,
      lblTop.ClientWidth
    );
{...}
end;
```

Hope this helps more than just pointing at the new release :wink: 

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
Implemented. Thanks.

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

No probs, you're more than welcome !!!

Cheers,
Gus
