### ISSUE TITLE
Make FPC/Lazarus truly portable

### ISSUE THREAD

**Issue by Snify89** [LongDirtyAnimAlf/fpcupdeluxe#448]
fpcupdeluxe is awesome.
Are there any plans to configure this mechanism or such, to make FPC/Lazarus truly portable?
Everything seems to be hard coded with paths, etc. that you can't move the directory somewhere else.
This is also an issue if you install to a USB-Drive with different drive letters without any admin-rights.

Thank you for reading and considering :)

**Comment by LongDirtyAnimAlf** [comment]
Thanks !

You are not the first to ask for this.
And the answer is simple: FPC and Lazarus themselves do not work when using relative paths for their settings.
This could be circumvented by adding extra functionality into fpcupdeluxe that might rewrite all the paths. But this WILL introduce many many bugs. So, although very desirable, this will not be implemented.

Sorry about this.

**Comment by Snify89** [comment]
Thank you for the info!

I would like to mention some workaround(s) for others (Windows only!):

**Workaround 1:**
1. Install FPC/Lazarus to a solid path, without any white spaces or special characters in it's path (e.g. C:\Lazarus)
2. Move/Copy your installation folder and deploy it somewhere else using a junction hard link. (google helps)

**Disadvantage(s):**
1. The drive "C:" may not be present on some other PC.
2. You may have no rights to either create a junction link or to access the "C:" root location.
3. "C:\Lazarus" is already deployed/present.

**Workaround 2:**
1. Create an empty folder with no white spaces or special characters in it's path (e.g. C:\Lazarus)
2. Pick a free (not assigned) drive letter between A and Z (e.g. J:) => the drive letter will later be hard coded!
3. Open cmd and use: >> _subst J: "C:\Lazarus"_ << => this maps the path C:\Lazarus to a virtual drive "J"
4. Install FPC/Lazarus to the virtual drive.
5. Move/Copy your installation folder and deploy it somewhere else using _subst J: "C:\somenewpath"_

**Disadvantage(s):**
1. The drive letter may be already in use/used and you might have to dismount it first (careful).
2. You may need admin-privileges to use the command "subst" (not tested with lower privileged users)
3. No auto start mount
4. Please refer to the "subst" documentation for more info or limitations, etc.

**Ideas/Tips:**
1. Use a proper path where all (low privileged) users have access to. (e.g. temp directory or public appdata)
2. Use environment variables somehow (e.g. set %MY_PATH%) (might work or not)
3. Use a localhost UNC Path?! (might need admin privileges or might not work at all)
