### ISSUE TITLE
fpcupdeluxe works in Linux but not in macOS, ld: library not found for -lc

### ISSUE THREAD

**Issue by han-k59** [LongDirtyAnimAlf/fpcupdeluxe#452]
While it worked previously in macOS it doesn't work anymore. I'm using macOS High Sierra and the latest version of fpcupdeluxe.  In Linux it all works fine but in macOS I get the following error

 ld: library not found for -lc

Selecting stable or trunk doesn't make any difference.
Any idea how to fix, avoid this? 
Thanks, 
Han

/Users/h/Desktop/lazarus_fpcup/fpcbootstrap/ppcx64 -Ur -dFPC_USE_LIBC -Ur -Xs -O2 -n -Fi../inc -Fi../x86_64 -Fi../unix -Fi../bsd -Fi../bsd/x86_64 -Fi../darwin/x86_64 -FE. -FU/Users/h/Desktop/lazarus_fpcup/fpcsrc/rtl/units/x86_64-darwin -Fl10.8/usr/lib -XR10.8 -WM10.8 -Sg -vw-n-h-l-d-u-t-p-c- -dREVINC -dx86_64 -dRELEASE ../inc/ufloat128.pp
/Library/Developer/CommandLineTools/usr/bin/make cycleclean
/Library/Developer/CommandLineTools/usr/bin/make -C utils cleanall
/Library/Developer/CommandLineTools/usr/bin/make compiler
/bin/echo "'9423-gca242e9ad0'" > revision.inc
/Users/h/Desktop/lazarus_fpcup/fpcbootstrap/ppcx64 -Ur -Xs -O2 -n -Fux86_64 -Fusystems -Fu/Users/h/Desktop/lazarus_fpcup/fpcsrc/rtl/units/x86_64-darwin -Fix86_64 -FEx86_64/bin/x86_64-darwin -FUx86_64/units/x86_64-darwin -dRELEASE -Fl10.8/usr/lib -XR10.8 -WM10.8 -Sg -vw-n-h-l-d-u-t-p-c- -dREVINC   -dREVINC -dx86_64 -dGDB -Fux86 -Fix86 version.pas
/Users/h/Desktop/lazarus_fpcup/fpcbootstrap/ppcx64 -Ur -Xs -O2 -n -Fux86_64 -Fusystems -Fu/Users/h/Desktop/lazarus_fpcup/fpcsrc/rtl/units/x86_64-darwin -Fix86_64 -FEx86_64/bin/x86_64-darwin -FUx86_64/units/x86_64-darwin -dRELEASE -Fl10.8/usr/lib -XR10.8 -WM10.8 -Sg -vw-n-h-l-d-u-t-p-c- -dREVINC   -dREVINC -dx86_64 -dGDB -Fux86 -Fix86 -o/Users/h/Desktop/lazarus_fpcup/fpcsrc/compiler/ppc1 pp.pas
ld: library not found for -lc
make[4]: *** [next] Error 2
An error occurred while linking 
pp.pas(288,36) Error: Error while linking
pp.pas(288,36) Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted
make[3]: *** [ppc1] Error 2
make[2]: *** [cycle] Error 2
make[1]: *** [compiler_cycle] Error 2
make: *** [build-stamp.x86_64-darwin] Error 2

fpcupdeluxe: ERROR: FPCNativeInstaller (CleanModule: FPC): Error running /usr/bin/make for FPC failed with exit code 512
. Details: 

ERROR: Fpcupdeluxe fatal error !
Sequencer (FPC): Failure running fpcupdeluxe: error executing sequence FPC
Sequencer (Only): Failure running fpcupdeluxe: error executing sequence Only

**Comment by trevoz** [comment]
Have you installed the standalone Xcode command line tools?

If yes, you need to tell FPC where to find the library by adding OPT="-XR/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/" to the make command line. I have no idea how you do this in FPCupDeluxe as I don't use it. To build FPC manually, refer to my Wiki instructions: https://wiki.lazarus.freepascal.org/Installing_Lazarus_on_macOS#Installing_non-release_versions_of_FPC

**Comment by LongDirtyAnimAlf** [comment]
The build process does not find libc.dylib.
Please try to locate it on your system and tell me the location:
`which libc.dylib`

**Comment by Kontrano** [comment]
That file is at:
/usr/lib/libc.dylib

Using High Sierra. 
I also tried to find the xcode version and got this:

hs-iMac:~ h$ /usr/bin/xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

**Comment by Kontrano** [comment]
That file is at:
/usr/lib/libc.dylib

Some info of my system:
hs-iMac:~ h$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by LongDirtyAnimAlf** [comment]
Thanks.
Would you mind testing (its a new binary, replacing the old one):
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/v2.2.0c/fpcupdeluxe-x86_64-darwin-cocoa.zip

**Comment by han-k59** [comment]
Not at all, I like to fix it :)  (p.s Kontrano is me)

I tried it with v2.2.0e, build 420. Unfortunally simular error. I have atttached the complete log. 
[log fpcupdeluxe.txt](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/7533444/log.fpcupdeluxe.txt)

Han
Below to bottom log

fpcupdeluxe: Performing SVN/GIT/HG/FTP/URL checkout/download. Please wait, could take some time.
fpcupdeluxe: Performing SVN/GIT/HG/FTP/URL checkout/download. Please wait, could take some time.
fpcupdeluxe: Performing SVN/GIT/HG/FTP/URL checkout/download. Please wait, could take some time.
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC was at revision/hash: FRET_UNKNOWN_REVISION
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC is now at revision/hash: 3.3.1-9621-gfeb5bde09c
fpcupdeluxe: info: FPC native builder: Detected source version FPC (source): 3.3.1
fpcupdeluxe: info: FPC native builder: Using FPC bootstrap compiler with version: 3.2.0
fpcupdeluxe: Start of compile error summary.
pp.pas(288,36) Error: Error while linking
fpcupdeluxe: Start of compile error summary.
pp.pas(288,36) Fatal: There were 1 errors compiling module, stopping
pp.pas(288,36) Error: Error while linking
fpcupdeluxe: Start of compile error summary.
Fatal: Compilation aborted
pp.pas(288,36) Fatal: There were 1 errors compiling module, stopping
fpcupdeluxe: Start of compile error summary.
fpcupdeluxe: ERROR: FPCNativeInstaller (BuildModuleCustom: FPC): Error running /usr/bin/make for FPC failed with exit code 512
. Details:
fpcupdeluxe: Done !!

**Comment by LongDirtyAnimAlf** [comment]
Thanks. The error is clear now.
Will try to solve (again).

**Comment by LongDirtyAnimAlf** [comment]
Here you go:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/v2.2.0c/fpcupdeluxe-x86_64-darwin-cocoa.zip

**Comment by han-k59** [comment]
Thanks. I have tried it. It was amost finished compiling but failed on a different error. Here is the full log:
[log fpcupdeluxe2.txt](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/7533755/log.fpcupdeluxe2.txt)

I will now try to install a stable version. Maybe it was the trunk

And this is the failure:
Compiling ./fcl-web/src/base/fpoauth2ini.pp
Compiling ./fcl-web/src/jwt/fpjwasha256.pp
fpjwasha256.pp(14,37) Error: Identifier not found "TJWTSigner"
fpjwasha256.pp(14,37) Error: Class type expected, but got "<erroneous type>"
fpjwasha256.pp(17,57) Error: Identifier not found "TJWTKey"
fpjwasha256.pp(18,56) Error: Identifier not found "TJWTKey"
fpjwasha256.pp(16,20) Error: There is no method in an ancestor class to be overridden: "class AlgorithmName:AnsiString(0);"
fpjwasha256.pp(17,14) Error: There is no method in an ancestor class to be overridden: "CreateSignature(TJWT;<erroneous type>):AnsiString(0);"
fpjwasha256.pp(18,14) Error: There is no method in an ancestor class to be overridden: "Verify(const AnsiString;<erroneous type>):Boolean;"
fpjwasha256.pp(21,1) Fatal: There were 7 errors compiling module, stopping
Fatal: Compilation aborted
Start compiling package fpgtk for target x86_64-darwin.
       Compiling fpgtk/BuildUnit_fpgtk.pp
       Compiling ./fpgtk/src/fpglib.pp
       Compiling ./fpgtk/src/fpgtk.pp
       Compiling ./fpgtk/src/fpgtkext.pp
[ 93%] Compiled package fpgtk
make[1]: *** [packages_smart] Error 2
make: *** [build-stamp.x86_64-darwin] Error 2
The installer encountered the following error:
Error inside worker thread for package fcl-web: (0/1) Failed compiling: fcl-web: Compilation of "BuildUnit_fcl_web.pp" failed

fpcupdeluxe: ERROR: FPCNativeInstaller (BuildModuleCustom: FPC): Error running /usr/bin/make for FPC failed with exit code 512
. Details: 


ERROR: Fpcupdeluxe fatal error !
Sequencer (FPC): Failure running fpcupdeluxe: error executing sequence FPC
Sequencer (Default): Failure running fpcupdeluxe: error executing sequence Default

**Comment by han-k59** [comment]
After trying to install stable & stable I got a new error.  See below Looks like fpcupdeluxe is working but compiling is very critical. I will try older version but this is puzzeling:


(3104) Compiling tadatapointseditor.pas
/Users/h/Desktop/lazarus_fpcup/lazarus/components/tachart/tadatapointseditor.pas(228,23) Error: (5000) Identifier not found "desMoveUp"
/Users/h/Desktop/lazarus_fpcup/lazarus/components/tachart/tadatapointseditor.pas(229,25) Error: (5000) Identifier not found "desMoveDown"
/Users/h/Desktop/lazarus_fpcup/lazarus/components/tachart/tadatapointseditor.pas(342,76) Error: (5000) Identifier not found "DefSeparatorSettings"
/Users/h/Desktop/lazarus_fpcup/lazarus/components/tachart/tadatapointseditor.pas(346,17) Error: (5000) Identifier not found "desNoNumber"
(3104) Compiling /Users/h/Desktop/lazarus_fpcup/lazarus/components/jcf2/Ui/Settings/frNotIdentifierCapsSettings.pas
/Users/h/Desktop/lazarus_fpcup/lazarus/components/tachart/tadatapointseditor.pas(354,15) Error: (5000) Identifier not found "desNoInteger"
tadatapointseditor.pas(363) Fatal: (10026) There were 5 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: /Users/h/Desktop/lazarus_fpcup/fpc/bin/x86_64-darwin/ppcx64 returned an error exitcode
Error: (lazarus) Compile package TAChartLazarusPkg 1.0: stopped with exit code 1
Error: (lazarus) Compile package jcfidelazarus 2.0: terminated
Error: (lazarus) [TLazPackageGraph.CompileRequiredPackages] "Exit code 1"
Error: (lazarus) Building IDE: Compile AutoInstall Packages failed.
make: *** [useride] Error 2
fpcupdeluxe: ERROR: LazarusNativeInstaller (BuildModuleCustom: UserIDE): make returned exit status #512

**Comment by han-k59** [comment]
The last problem is now solved. I had to remove all old files and directories of fpcupdeluxe and started blank. Now it works as desired.

This is something to address. In the old versions of fpcupdeluxe you could not install at the same directory. This is possible using the newer version. I assumed the new version was taking care of deleting old files but it doesn't seem to work 100% correct or not at all.  

LongDirtyAnimAlf and Trevoz, both thanks for the support. I'm a happy programmer again.

Han

**Comment by LongDirtyAnimAlf** [comment]
You're welcome.
