### ISSUE TITLE
Cannot install FPC 3.2-fixes from git on macOS 10.8

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#453]
Git is present here! I can run it in console!
```
users-Mac:~ user$ which git
/opt/local/bin/git
users-Mac:~ user$ 
```
But log tells you cannot find git.
```

Going to install/update FPC only with given options.
FPCUP(deluxe) is starting up.

FPCupdeluxe basedir:       /Users/user/fpcupdeluxe/fpcupdeluxe
Bootstrap dir:             /Users/user/fpcupdeluxe/fpcupdeluxe/fpcbootstrap

FPC URL:                   https://gitlab.com/freepascal.org/fpc/source
FPC source directory:      /Users/user/fpcupdeluxe/fpcupdeluxe/fpcsrc
FPC install directory:     /Users/user/fpcupdeluxe/fpcupdeluxe/fpc
FPC options:               

Lazarus URL:               https://gitlab.com/freepascal.org/lazarus/lazarus
Lazarus source directory:  /Users/user/fpcupdeluxe/fpcupdeluxe/lazarus
Lazarus install directory: /Users/user/fpcupdeluxe/fpcupdeluxe/lazarus
Lazarus options:           -g -gl -O1

Please stand back and enjoy !

12-10-21 19:54:30: fpcupdeluxe: V418 (20211003) started.
FPCUPdeluxe V2.2.0c for x86_64-darwin running on Mac OS X 10.8.5

fpcupdeluxe: info: FPCNativeInstaller (CleanModule: FPC): No FPC source directory (/Users/user/fpcupdeluxe/fpcupdeluxe/fpcsrc) found [yet] ... nothing to be done
Found valid bsdtar application.
Found valid make application.
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): Start checkout/update of FPC sources.
fpcupdeluxe: WARNING: FPCNativeInstaller (GitClient: FPC): git is needed, but cannot be found on the system !!
fpcupdeluxe: ERROR: FPCNativeInstaller (GetModule: FPC): Checkout/update of FPC sources failure.


ERROR: Fpcupdeluxe fatal error !
Sequencer (FPC): Failure running fpcupdeluxe: error executing sequence FPC
Sequencer (Only): Failure running fpcupdeluxe: error executing sequence Only
```

**Comment by trevoz** [comment]
Your third party git version is not compatible with macOS 10.8. Why not install the Xcode standalone command line tools? If you wish to persist with a third party git client, you need the older git version 2.2.1 for macOS 10.8.

**Comment by trevoz** [comment]
Specifically, git-2.2.1-intel-universal-snow-leopard from https://sourceforge.net/projects/git-osx-installer/files/

**Comment by Alexey-T** [comment]
I still suffer from this. :(

**Comment by trevoz** [comment]
Have you tried following my manual instructions at https://wiki.lazarus.freepascal.org/Installing_Lazarus_on_macOS#Lazarus_Fixes_2.2 ?

**Comment by Alexey-T** [comment]
@trevoz No, coz I need the help for FPC installing, not for the Lazarus...

@LongDirtyAnimAlf I don't know why Deluxe always runs Git from /usr/bin/git, while my Git installer (I got the last Git installer from https://sourceforge.net/projects/git-osx-installer/files/git-2.33.0-intel-universal-mavericks.dmg/download?use_mirror=autoselect ) puts Git to different path?

**Comment by trevoz** [comment]
You need to read further down for FPC fixes_3_2:  https://wiki.lazarus.freepascal.org/Installing_Lazarus_on_macOS#FPC_Fixes_3.2

**Comment by LongDirtyAnimAlf** [comment]
There are several fixes pending for the new release of fpcupdeluxe.
1: it will look in /usr/local/bin for a GIT on all unix systems (including OSX).
2: installing from gitlab by using zipped sources (no need for GIT).

**Comment by Alexey-T** [comment]
Bravo! I wait for this update. Thanks

**Comment by Alexey-T** [comment]
@trevoz You wiki text defeats the Deluxe app use case. I will wait for Deluxe update

**Comment by LongDirtyAnimAlf** [comment]
Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.2.0e
And.
Do not report FPC errors like codesigning problems.
Only report fpcupdeluxe issues.

**Comment by barracuda156** [comment]
> You need to read further down for FPC fixes_3_2: https://wiki.lazarus.freepascal.org/Installing_Lazarus_on_macOS#FPC_Fixes_3.2

I wonder how compatibility info there is derived – it is partly incorrect.
