### ISSUE TITLE
fpcupdeluxe installs quite old version of Zeos 7.2

### ISSUE THREAD

**Issue by marsupilami79** [LongDirtyAnimAlf/fpcupdeluxe#456]
Hello,

Zeos users have reported that fpcupdeluxe installs quite old versions of Zeos, namely Zeos 7.2.6 which seems to have problems compiling on a current FPC for 64 bits (see [https://sourceforge.net/p/zeoslib/tickets/516/#2ac9/cb40](https://sourceforge.net/p/zeoslib/tickets/516/#2ac9/cb40)) I submitted a pull request that should change the reference in fpcupdeluxe to Zeos 7.2.14 which is the current stable version. See #455 .

Best regards,

Jan

**Comment by LongDirtyAnimAlf** [comment]
Next version will install updated version !
