### ISSUE TITLE
Can't compile Lazarus

### ISSUE THREAD

**Issue by henriquewerlang** [LongDirtyAnimAlf/fpcupdeluxe#457]
I trying to compile Lazarus project, but always get this error:
C:\fpcupdeluxe\lazarus\ide\lazarus.pp(83,2) Fatal: (2013) Cannot open include file "revision.inc"
Fatal: (1018) Compilation aborted
Error: C:\fpcupdeluxe\fpc\bin\i386-win32\ppc386.exe returned an error exitcode
make[3]: *** [lazarus.exe] Error 1
make[3]: Leaving directory `C:/fpcupdeluxe/lazarus/ide'
make[2]: *** [idepkg] Error 2
make[2]: Leaving directory `C:/fpcupdeluxe/lazarus/ide'
make[1]: *** [idepkg] Error 2
make[1]: Leaving directory `C:/fpcupdeluxe/lazarus'
Error: (lazarus) Build IDE: stopped with exit code 2
Error: (lazarus) Building IDE: Building IDE failed.
make: *** [useride] Error 2
make: Leaving directory `C:/fpcupdeluxe/lazarus'
fpcupdeluxe: ERROR: LazarusNativeInstaller (BuildModuleCustom: UserIDE): make.exe returned exit status #2

ERROR: Fpcupdeluxe fatal error !
Sequencer (UserIDE): Failure running fpcupdeluxe: error executing sequence UserIDE
Sequencer (Lazarus): Failure running fpcupdeluxe: error executing sequence Lazarus
Sequencer (Defaultwin32): Failure running fpcupdeluxe: error executing sequence Defaultwin32

**Comment by LongDirtyAnimAlf** [comment]
Which version of fpcupdeluxe do you use ?
Thanks.

**Comment by henriquewerlang** [comment]
The master branche.

**Comment by LongDirtyAnimAlf** [comment]
Please use a tag. So up 1.8.2. Or up 2.2.0c. Or do you build your own version ?

**Comment by henriquewerlang** [comment]
So, I removed all the repositories, and i rebooted the installation and everything worked.
