### ISSUE TITLE
how to build ppcjvm for Android Aarch64 

### ISSUE THREAD

**Issue by JanuszChmiel** [LongDirtyAnimAlf/fpcupdeluxe#458]
Dear Don,
My dream is to use PPCJVM not from Windows or Linux, but directly from Android OS with CPU AArch64. COuld be possible to extend yours builder to allow that?
If it is not possible to achieve this goal for Android aarch64, would be possible to make this for Linux Aarch64 Bit architecture? But I need to have no fpc but ppcjvm. Ppcjvm should be capable to build CPU JVM and target Android. Why? Because it is possible to build GUI with no need to use .xml files and position values for every object and this is ideal for visually impaired developers with no sight at all, who like Pascal programming language.
Ideal solution would be to have PPCJVM for Android, aarch64. Thank you for your advices.
Now I Am currently have PPCJVm.exe which can compile JVM CPU target and OS Android but it is PPCJVM for WIndows.

**Comment by LongDirtyAnimAlf** [comment]
How do you imagine to run fpcupdeluxe on Android ?
This would be an interesting development !

**Comment by JanuszChmiel** [comment]
I have thought, that it is possible tocross compile PPCJVM on IBM/PC compatible machine. And that I could run PPCJVM on Android machine by using  The same approach, which MR Nicolas Mougin has introduced as opensource solution.
His RFO Basic compiler for Android. It executes also some Binary modules on Android machines by using Shell. So It would be possible to add PPCJVM AArch64 which would compile to Android JVM target on Android device.
Sure, PPCJVM would be cross compiled on normal PC. My main goal is to use Pandroid branch directly on Android device with no need to use big computer. I Am aware that build and compilation would be slower. I would had to buy modern Samsung phone which has high quality CPU equal by its pperformance to The IBM/PC compatible CPUS.
But if such cross compilation is impossible thanks to The nature of Free Pascal compiler, you can close this issue.

**Comment by LongDirtyAnimAlf** [comment]
Well. Now I understand.
You will never be able to run a FPC GUI program (like fpcupdeluxe) on an Android machine. Unless in a x11/GTK simulated environment.
Only command line tools will work.
You might file a feature-request for this at:
https://github.com/LongDirtyAnimAlf/Reiniero-fpcup

**Comment by JanuszChmiel** [comment]
I have found out, that it is even possible to run complete Lazarus IDE on Android device thanks to Proot, Termux and some compatible Linux distribution.
I would even try to use this approach, but unfortunately, accessibility of Lazarus with Orca screen readeru is not good. So if I would like to add new Lazarus package, Orca can not read The necessary textual button description for Me.
OK, you can close this issue, I will be continue to work with Termux, Proot, Lazarus and some Linux distro such As archLinux.
Thanks to BVNC, it is possible to control Linux X11 app by using VNC protocol. And Orca speak by using Pulseaudio sound server for Termux.
