### ISSUE TITLE
would it be possable to flatpak this?

### ISSUE THREAD

**Issue by pyrotek45** [LongDirtyAnimAlf/fpcupdeluxe#459]
i use linux and mostly flatpak applications now these days. currently lazarus does not have a flatpak option but this being a flatpak would be even better. would it be possible to make a flatpak version of this to download lazarus and fpc into a sandbox and use it for dev work?

**Comment by LongDirtyAnimAlf** [comment]
Which distro do you use ?

**Comment by pyrotek45** [comment]
Fedora Silverblue, although I have to use the fedora workstation edition atm for dev work. I would just like to be able to do fpc work inside a container of some kind. 

Currently programs like vscode and other ide's that are available in flatpak cannot by defualt access the host binaries. But it would be extremely useful if something like Lazarus could be packaged into a flatpak making it portable and sandboxed.  The benefit would be it could always be up to date without the distro devs having to update their version, and since it would be in a sandbox, it could eliminate guesswork on where fpc is located for other fpc libraries later down the line.

**Comment by LongDirtyAnimAlf** [comment]
I do not have that much knowledge about Flatpak. But FPC as well as Lazarus use absolute paths in their setup. So I do not know if portability is ever possible.

**Comment by afriess** [comment]
flatpack and snap are a 'linux in a container' so it is best useable for compiled programs and fixed depencies. fpcupdeluxe build fpc and Lazarus on baremetall. If you change packages it is also so possible to need morde dependencies in the flatpack and to completly recompile Lazarus and/or sometimes fpc. 
If you have a flatpack for a compiler enviroment, you can use fpcupdeluxe inside this flatpack/snap. 

On the other side, if you have a flatpack/snap for fpc and another for Lazarus, can they work togehter ?! I didnt know., i am only a user of some snaps.

**Comment by LongDirtyAnimAlf** [comment]
I have looked into flatpacks.
They claim to make things easier.
But AFAIU, I would need to create a flatpack for any distro that has users for fpcupdeluxe ?
Am I correct ?
Is so, that would be not realistic for me as a two handed one-brainer.

**Comment by pyrotek45** [comment]
> I have looked into flatpacks.
> They claim to make things easier.
> But AFAIU, I would need to create a flatpack for any distro that has users for fpcupdeluxe ?
> Am I correct ?
> Is so, that would be not realistic for me as a two handed one-brainer.

I'm not sure what you mean, you would only have to make *one* flatpak binary, then, any distro that has flatpak installed can then run your flatpak on their machine without any extra configuration (since it's a container, it's going to be reproducible based on your flatpak)

**Comment by afriess** [comment]
> I'm not sure what you mean, you would only have to make one flatpak binary, then, any distro that has flatpak installed can then run your flatpak on their machine without any extra configuration (since it's a container, it's going to be reproducible based on your flatpak)
So 'some' or 'any'body can make a flatpak with fpcupdeluxe inside. IMHO fpcupdeluxe should only included, not create such packs.

**Comment by LongDirtyAnimAlf** [comment]
I cannot imagine that a single flatpack would serve all distros. If that is what is suggested here.
All those versions. Different (library) dependencies. Different windows managers. Fpcupdeluxe is distributed as a binary.

Anyhow.

I can naturally give it a try.
Please tell me what distro I should target to start with ?
And how I would get my flatpack accepted by upstream ?

**Comment by pyrotek45** [comment]
> > I'm not sure what you mean, you would only have to make one flatpak binary, then, any distro that has flatpak installed can then run your flatpak on their machine without any extra configuration (since it's a container, it's going to be reproducible based on your flatpak)
> So 'some' or 'any'body can make a flatpak with fpcupdeluxe inside. IMHO fpcupdeluxe should only included, not create such packs.

You lost me. What are you talking about? Fpcupdeluxe is a program that downloads and configures Lazarus and fpc on a host system. The problem is that some distros are switching to read only file systems and many users are now eager to use flatpaks for their main programs, since flatpaks offer extra layers of reproducibility and security via container technology. 

My post here was asking if fpcupdeluxe could be put inside a flatpak, for a reproducible Lazarus deployment solution that any distro could use, assuming they have flatpak installed. 

This would be great for users that would like to keep their dev environment seperarate from their host, or for devs that are moving to read only/immutable filesystems.

**Comment by pyrotek45** [comment]
> I cannot imagine that a single flatpack would serve all distros. If that is what is suggested here.
> All those versions. Different (library) dependencies. Different windows managers. Fpcupdeluxe is distributed as a binary.
> 
> Anyhow.
> 
> I can naturally give it a try.
> Please tell me what distro I should target to start with ?
> And how I would get my flatpack accepted by upstream ?

Iirc you dont target a distro, you target a flatpak runtime. Think docker. When you package an app in flatpak it gets wrapped in a container. That container will have all the dependencies included or use the flatpak runtime and libraries defined in the flatpak manifest. Flatpak was designed to be able to package applications and deploy them on any system that has flatpak installed, much like docker in a way.

**Comment by pyrotek45** [comment]
I'm not an expert on flatpaks by any means, although I have packaged a few of my own simple programs using flatpak builder. I'm sure flatpaking an application like fpcupdeluxe will be no easy feat. 

I suppose the goal would be to be able to have a flatpak be able to setup Lazarus either inside the flatpak  container itself or on the host system. I think the latter makes more sense, allowing it to work much the same way it does now, with the added benefit of being distro agnostic. However if it could deploy a Lazarus setup inside the flatpak, that could have some added benefits as well. Mostly reproducible builds of Lazarus on any distro with flatpak.

**Comment by LongDirtyAnimAlf** [comment]
I have now tried for many hours to get a working flatpak for fpcupdeluxe. To no avail unfortunately.
I am closing while my time is limited. Sorry about this.
You may have a look at: https://github.com/flathub/org.freedesktop.Sdk.Extension.freepascal
Please open again if you have instructions for me to get things running.

**Comment by pyrotek45** [comment]
Thank you for giving it a shot!
