### ISSUE TITLE
Cross compiling from Linux to Darwin aarch64 works only if Android cross compiler is created. 

### ISSUE THREAD

**Issue by han-k59** [LongDirtyAnimAlf/fpcupdeluxe#461]
I have noted the following:

I working from Linux and want to cross compile to MacOS M1.  Cross compiling to Darwin & X86_64 works straight out of the box. But for Darwin & aarch64 I did run in problems.

Installing the cross compiler to Darwin & aarch64 works without error but when used Lazarus gives and error "can't compile to ....."

After several tries, I discovered that cross compiling to Darwin & aarch64 only works if the cross compiler to Android & aarch64 (and arm?)  is installed. I have done it now twice and the problem is repeatable.  So I assume something is missing in the cross compiler installation for Darwin & aarch64 but can be corrected by installing the Android & aarch64  cross compiler.

Han

**Comment by LongDirtyAnimAlf** [comment]
I have tried to reproduce, but could not.
On a vanilla install, I installed x86_64 and aarch64 cross-compilers for Darwin. Without anything else. All went well, including the build of an app for Darwin.
Which version of fpcupdeluxe do you use ?

**Comment by han-k59** [comment]
FPCUPdeluxe V2.2.0c build 418
Build-date 2021-10-03

I have tested it twice and it is reproducible. I will try again. 
I could provide the VM virtual machine running Ubuntu 20.4 where it happens but it is a 12 gbyte packed file.

Han

**Comment by LongDirtyAnimAlf** [comment]
> I could provide the VM virtual machine running Ubuntu 20.4 where it happens but it is a 12 gbyte packed file.

That is ok for me !

**Comment by han-k59** [comment]
I have recreated the situation. First remove all files. Install fpc trunk and lazarus trunk. Then install cross compiler aarch64-darwin. I get the attached error.

![fpcupdeluxe error darwin](https://user-images.githubusercontent.com/46811539/141675638-3244104a-1c0c-4db9-b4f9-4a746c9a9287.png)

Working on the virtual machine to demonstrate it.

**Comment by LongDirtyAnimAlf** [comment]
![Capture](https://user-images.githubusercontent.com/10783972/141676201-a0c6925d-6d30-4e2c-bb17-be258c2128d1.JPG)
What is that minus-sign ?

**Comment by han-k59** [comment]
No idea but it doesn't belong there. The file fpc.sh is available but not -fpc.sh. Do you still need a virtual machine for an investigation?

**Comment by LongDirtyAnimAlf** [comment]
> Do you still need a virtual machine for an investigation?

That would make debug-life easier !

**Comment by han-k59** [comment]
Will provide the machine. Requires some time. This is in the Lazarus options:
![Untitled](https://user-images.githubusercontent.com/46811539/141676556-d19b4a77-8b6d-4727-92e2-adcee8963c84.png)

**Comment by LongDirtyAnimAlf** [comment]
That looks good.
I just tried to reproduce. Without success. All runs 100% on my Mint64 VM.
Did you also delete the whole cross-directory containing libs and bins ?

**Comment by han-k59** [comment]
Yes to reproduce it I deleted all fpcupdeluxe files and folders. The virtual machine will be available online in about one hour as a rar archive. It was too big for a zip archive.

**Comment by han-k59** [comment]
Here is the lubuntu virtual machine in a rar archive. Was location at Windows computer. You can copy & paste file to it.

Link:
https://drive.google.com/file/d/1URVKPRF_W3Y9nNMnBiFQqQiJhs0caP1q/view?usp=sharing

User: h
Passw: h

Program to compile:
/home/h/astap.fpc/astap_linux cross_compile_to_Darwin .lpi

Location fpcupdeluxe:
/home/h

Thanks for the effort.
Han

**Comment by LongDirtyAnimAlf** [comment]
![Screenshot (5)_LI](https://user-images.githubusercontent.com/10783972/141683304-acafcbc8-6b93-4eaa-ba49-7403ec758138.jpg)
Try the above: scan sources.

**Comment by han-k59** [comment]
Yes that works and fixes the problem. Why is this menu created?

**Comment by LongDirtyAnimAlf** [comment]
This menu is not created. Its there all the time. This command refreshed the Lazarus cache. In the past, I have tried to run this command through fpcupdeluxe, but failed.
