### ISSUE TITLE
Win x32 installing of FPC fixes-3.2 has the crap file

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#464]
```
Extracted #10. File python27.dll out of #14
```

**Comment by LongDirtyAnimAlf** [comment]
Please elaborate on this.
I do not understand what you mean.

**Comment by Alexey-T** [comment]
The 1st post is a line - this is one of lines "Extracted #........." which I see in the fpcupdeluxe log. When I install FPC fixes-3-2. So it tells us that some of packages of fpcupdeluxe contains PYTHON DLL. Why python dll is needed?

**Comment by LongDirtyAnimAlf** [comment]
Ok.
Python27.dll is part of the hg windows client that is downloaded by fpcupdeluxe.
