### ISSUE TITLE
Windows - make both win32 and win64 EXE co-exist

### ISSUE THREAD

**Issue by the-Arioch** [LongDirtyAnimAlf/fpcupdeluxe#473]
I run `fpcupdeluxe-x86_64-win64.exe` 2.2.0e version, it installs me Win64 IDE.

Now i want to compile Win32 applications too, so i try to install cross-compilation. FPCupdeluxe suggests me agaisnt that, claiming there will be problem with debugging. I wonder how Delphi does it, but okay, thanks for warning. CodeTyphon makes separate build too, so perhaps there are issues with GDB on Windows.

However, what specifically should i do? It would be a nice thing to have a clear article for newcomers.

Okay, i download `fpcupdeluxe-i386-win32.exe` and launch it. It shows me the same `d:\fpcupdeluxe\` folder it used before. Good, no need to download sources yet again. Still, it would be good to outright tell user if win32 and win64 versions of fpcupdeluxe can co-exist in same folder or not. Do not leave newb user in F.U.D. state...

But okay, i run `fpcupdeluxe-i386-win32.exe` and compile IDE and...   ...it replaces the same desktop icon.

Using CodeTyphon Control Center i get two disctinct launch shortcuts, for 32-bit and 64-bit IDEs, to develop both win32 and win64 builds of my apps. It would be nice if fpcupdeluxe could do the same, it builds two IDEs - then make user able to run both, not one at time.

**Comment by LongDirtyAnimAlf** [comment]
The preferred way of installing on Windows is to install the win32 version of FPC and Lazarus by using the win32 version of fpcupdeluxe. If you use this way of installing, a win64 cross-compiler gets also installed to enable you to compile for win32 and win64 using the same install. You only need to change the target when compiling (OS: win64, CPU: x86_64). No need for two separate installs.

**Comment by the-Arioch** [comment]
Could this then be advertized when trying to add win32 cross-compilation into win64 fpcupdeluxe ?

_And personally i think being able to add prefix/suffix to desktop shortcuts could help you goal to compare several slightly different laz builds, having them in different folders, so would be a useful addition anyway._
