### ISSUE TITLE
can description for JVCL module be changed?

### ISSUE THREAD

**Issue by the-Arioch** [LongDirtyAnimAlf/fpcupdeluxe#474]
https://sourceforge.net/p/lazarus-ccr/bugs/49/#8687

Originally, in Delphi world, JediVCL was an add-on library working on top of JCL (Jedi CodeLib).

In fpcupdeluxe there are both modules, JCL and JVCL, so natural idea would be install one after another, like in Delphi.

However, it turns out that they are not coupled in FPC, JCL is original code (having compatibiliy with both Delphi and FPC) while LazJVCL fork was detouched from JCL and rebased upon FPC RTL instead. So, they are two independent projects in FPC world, very different from Delphi world.

Can this change be clearly put in the JCL and JVCL modules description ?

**Comment by LongDirtyAnimAlf** [comment]
JCL is taken from here:
GITURL=https://github.com/project-jedi/jcl 

JVCL is taken from here
SVNURL=svn://svn.code.sf.net/p/lazarus-ccr/svn/components/jvcllaz

> Can this change be clearly put in the JCL and JVCL modules description ?

Tell me how and I will implement this.

**Comment by the-Arioch** [comment]
You can start from wp's message at the link to JVCL tracker:  You do not need JCL for the Lazarus port of JVCL. Maybe even including the link into decription?

However, i'd put "NOT" as bold big letters there. JVCL original was always built on top of JCL, if it is different at Laz - then it is a radical departure and has to be told to user immediately.

**Comment by LongDirtyAnimAlf** [comment]
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/af8c9ebd66c5f7ae7f6f7ffa8cab134309f40c2e
