### ISSUE TITLE
some strange error 'TNormalUnzipper: could not unzip file'

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#475]
- 2.2.0c on Linux x64 gtk2
- installing on Linux x64 the cross-tools for NetBSD x64
- got the console error 'cannot unzip', and wrong indicator in the Gus Downloader
- freezed

![netbsd](https://user-images.githubusercontent.com/4154978/144623328-9fb32976-914e-4cd0-99ba-1e986a40bfe1.png)

- restarted Deluxe, then it went OK w/o the error

**Comment by LongDirtyAnimAlf** [comment]
Not able to reproduce. Perhaps a single unique hickup of deluxe.
