### ISSUE TITLE
FPCUPdeluxe on Haiku

### ISSUE THREAD

**Issue by Begasus** [LongDirtyAnimAlf/fpcupdeluxe#476]
I would like to thank you here, as of today we have a package that can be installed through our package manager on Haiku for both 32bit and 64bit, just wanted to share the info. :)

![FPCUPdeluxe](https://user-images.githubusercontent.com/16057090/147092328-5b70ef6c-b883-48a7-aee7-ad9540ad89ac.png)

**Comment by LongDirtyAnimAlf** [comment]
Well thanks you !
That is good news !!
And, as a very interesting side note: the up-released Haiku binaries were cross-compiled on a Win10 machine.

**Comment by Begasus** [comment]
> the up-released Haiku binaries were cross-compiled on a Win10 machine.

Yeah, saw this when launching fpcupdeluxe :) Haven't figured out how to build fpcdeluxe on Haiku, but at least we've got a binary that supplies all we need for FPC/Lazarus :+1:
