### ISSUE TITLE
Suggestion:  FPCupDeluxe Self Update?

### ISSUE THREAD

**Issue by TonyStone31** [LongDirtyAnimAlf/fpcupdeluxe#477]
Hey, I was just thinking, it doesnt seem it would be very hard for you do have FPCupDeluxe doing a self update in the same way you update Lazarus.... Just build from the source here?  Is it a possible feature?

**Comment by LongDirtyAnimAlf** [comment]
This feature is already more or less available.
You can install fpcupdeluxe by through the modules. And compile it by yourself.
Is that something acceptable ?

**Comment by LongDirtyAnimAlf** [comment]
Closing due to no feedback.

**Comment by TonyStone31** [comment]
Sorry for the lack of feedback.  I think building it myself is acceptable however your tool maybe just made me very lazy with how easy you make it to do different Lazarus builds! :)  I think I was just thinking it would be cool for FPCupDeluxe to be able to check check GIT and rebuild itself when there is an update.  I am often checking my version from the about menu then coming here to grab a new release for Linux.  Maybe it is more work than necessary maybe an automatic update is available notification would be more than acceptable?  By the way thanks for all your work on this tool!

**Comment by TonyStone31** [comment]
> This feature is already more or less available. You can install fpcupdeluxe by through the modules. And compile it by yourself. Is that something acceptable ?

I guess I don't understand what you mean by "install fpcupdeluxe through the modules".  Can you clarify that for me a little?  Maybe I am missing something.

**Comment by LongDirtyAnimAlf** [comment]
![Screenshot 2022-10-22 173258](https://user-images.githubusercontent.com/10783972/197350981-7ec95b73-3bf9-45ef-8186-eb04d5d1bbd5.png)

**Comment by LongDirtyAnimAlf** [comment]
The above might work good enough (I hope) for now !

**Comment by TonyStone31** [comment]
Oh wow... I missed all of that!  I will take a look to ight when I have time to play on the computer.  I'm sure it works great!  Thank you again
