### ISSUE TITLE
Is it possible to install Lazarus 2.2.0RC1 or 2.2.0RC2?

### ISSUE THREAD

**Issue by eugeneloza** [LongDirtyAnimAlf/fpcupdeluxe#479]
Hi! It doesn't seem like 2.2.0RC1 and 2.2.0RC2 versions of Lazarus are available options for installation though the versions exists:

https://sourceforge.net/projects/lazarus/files/Lazarus%20Windows%2064%20bits/Lazarus%202.2RC1/

However, on GitLab I could find only RC2 tag, but not RC1:

![2022-01-06-084848_1366x768_scrot](https://user-images.githubusercontent.com/10726162/148341179-54387a0d-8e62-42f4-888d-67bb4bfef578.png)

**Comment by LongDirtyAnimAlf** [comment]
Does this work ?

![Capture](https://user-images.githubusercontent.com/10783972/148382657-57c16bf8-01f6-4eb2-8166-012c83593cd5.JPG)
