### ISSUE TITLE
Modules: FPC's svn seems down.

### ISSUE THREAD

**Issue by the-Arioch** [LongDirtyAnimAlf/fpcupdeluxe#483]
Trying to install LNET module FPCUPDELUXE never ends it.

http://svn.freepascal.org/svn/fpcprojects/lnet/trunk - the server seems totally down.
FPC announced moving off SVN back in August 2021, now they probably pulled the plug.

This specific component seem moved to https://gitlab.com/freepascal.org/fpc/projects/-/tree/master/lnet/trunk
Just for the pattern, i think you have to move ALL modules that were hosted on FPC's SVN server and this would be of help.

As of that specific library, [according to wiki](https://wiki.freepascal.org/lNet#Download) the alive repository is yet different.
https://github.com/almindor/lnet

**Comment by LongDirtyAnimAlf** [comment]
Done.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/be160fc80fa4e354f88ef163c515926910c550c9
