### ISSUE TITLE
WIsh: single-thread mode

### ISSUE THREAD

**Issue by the-Arioch** [LongDirtyAnimAlf/fpcupdeluxe#486]
It is hard to debug issues, when Lazarus compilation failes, but the log window has randomly interleaved messages from 4 or more applications.

There should be an option to limit LazBuild and others to a single CPU core/thread, so log window would start showing logical sequence leading to the error.

**Comment by LongDirtyAnimAlf** [comment]
In Setup+, there is a checkbox for using jobs.
Does this work for you ?

**Comment by LongDirtyAnimAlf** [comment]
Closing due to lack of feedback.
