### ISSUE TITLE
Add ".git" to Gitlab URL

### ISSUE THREAD

**Issue by Snify89** [LongDirtyAnimAlf/fpcupdeluxe#489]
I get this error with my git client on Oracle Linux 7.9 and fpcupdeluxe

https://stackoverflow.com/questions/32533379/git-error-rpc-failed-result-22-http-code-404

Appending the ".git" suffix should help

Thanks :)

**Comment by LongDirtyAnimAlf** [comment]
This addition would solve your issue indeed.
However.
It might break all existing installs. So changes have to be made very carefully.
Will look into this.

**Comment by LongDirtyAnimAlf** [comment]
Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.2.0i

**Comment by Snify89** [comment]
I can confirm, that I can now successfully pull and fetch the stable branch. However this is tested with gitlab only.
I don't know if github works. I can also see, that the upper 2 edit fields on the right side, are not apennded with the .git suffix.

Still, thank you very much for this fix. 

I have also additional stuff for you to that might help.

I am using the latest oracle linux 7.9 distro with gui.
So I installed these packages to make Lazarus/FPC(updeluxe) work:

yum install git
yum install gdk-pixbuf2-devel
yum install pango-devel
yum install gtk2-devel
yum install glibc-devel
yum install gcc

**Comment by LongDirtyAnimAlf** [comment]
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/6065c67659a0c8b6844928eec09193f794111e56
