### ISSUE TITLE
Windows installation hangs up because libeay32.dll and ssleay32.dll fail to download

### ISSUE THREAD

**Issue by dexter4** [LongDirtyAnimAlf/fpcupdeluxe#490]
fpcupdeluxe Windows installation hangs up in the beginning because it fails to download file:
http://gitlab.com/freepascal.com/lazarus/binaries/-raw/main/i386-win32/openssl/libeay32.dll

This problem constantly happens on both 32-bit and 64-bit versions of Windows 7.

The workaround solution:
1) manually download files libeay32.dll and ssleay32.dll from the address below:
https://indy.fulgan.com/SSL/
openssl-1.0.2u-i386-win32.zip
openssl-1.0.2u-x64_86-win64.zip
2) put both files libeay32.dll and ssleay32.dll into the same directory where fpcupdeluxe-i386-win32.exe is located.

fpcupdeluxe installer should be updated to use cached copies of libeay32.dll and ssleay32.dll files in case when these files fail to download from gitlab.com portal.

**Comment by LongDirtyAnimAlf** [comment]
> fpcupdeluxe installer should be updated to use cached copies of libeay32.dll and ssleay32.dll files

Please explain the meaning of this.
Where are these files cached.
And how to use them.

**Comment by dexter4** [comment]
The weblink 
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases
contains Windows installation file:
fpcupdeluxe-i386-win32.exe
Instead of “fpcupdeluxe-i386-win32.exe” file there should be ZIP archive file named “fpcupdeluxe-i386-win32.zip” and this ZIP file should contain inside three files:
1) fpcupdeluxe-i386-win32.exe
2) libeay32.dll
3) ssleay32.dll
Additional files “libeay32.dll” and “ssleay32.dll” are need for downloading whole package of Lazarus.
Currently the installer tries to retrieve these two files from gitlab.com portal:
http://gitlab.com/freepascal.com/lazarus/binaries/-raw/main/i386-win32/openssl/libeay32.dll
However downloading of “libeay32.dll” and “ssleay32.dll” files from gitlab.com portal very often fails and then installer simply hangs indefinitely. This happens too much too often, it is very annoying. A lot of people are unable to install fpcupdeluxe due to this bug.
The solution is very simple: please include additional libeay32.dll and ssleay32.dll files into “fpcupdeluxe-i386-win32.zip” archive, and this will solve the problem of crashing installer.
The same applies to 64-bit Windows installer: “fpcupdeluxe-x86_64-win64.exe” – it also needs to be replaced with ZIP archive file, which contains inside two additional files of  libeay32.dll and ssleay32.dll.

**Comment by neurocluster** [comment]
fpcupdeluxe v2.2.0j hangs up on Windows 7 in the beginning of installation, because it fails to download files libeay32.dll and ssleay32.dll.
This bug of fpcupdeluxe should be fixed:
1) the download server address (for files libeay32.dll and ssleay32.dll) should be changed to
https://indy.fulgan.com/SSL/
or
2) files libeay32.dll and ssleay32.dll should be included inside fpcupdeluxe.

**Comment by LongDirtyAnimAlf** [comment]
Should be solved by latest releases.
