### ISSUE TITLE
Cross compiling linux x64 to arm-android

### ISSUE THREAD

**Issue by jgamigo** [LongDirtyAnimAlf/fpcupdeluxe#491]
I m trying build cross compiler for android and constantly stucked in: 
**fpcupdeluxe: WARNING: Skipping cross-compiler cleanstep: compiler seems to be up to date 
fpcupdeluxe: info: FPC arm-android cross-builder: Detected source version FPC (source): 3.3.1
fpcupdeluxe: Start of compile error summary. 
fpcupdeluxe: ERROR: Failed to get crossbinutils 
Missing correct cross libraries**
and i need kill the app for finish
Other cross compilers don´t have problem (to win32/64 or arm-linux).
Button "LAMW" do same.
(checking Extras->Check Tools Location bring me apparently correct info, i can manual download:
...
x86_64-android bins: https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/linuxx64crossbins_v1.1/CrossBinsAndroidAll.zip
x86_64-android libs: https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/crosslibs_v1.1/CrossLibsAndroidx64.zip
arm-android bins: https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/linuxx64crossbins_v1.1/CrossBinsAndroidAll.zip
arm-android libs: https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/crosslibs_v1.1/CrossLibsAndroidARM.zip
aarch64-android bins: https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/linuxx64crossbins_v1.1/CrossBinsAndroidAll.zip
aarch64-android libs: https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/crosslibs_v1.1/CrossLibsAndroidAarch64.zip
...)
Thanks in advance

**Comment by jgamigo** [comment]
Sorry, version is fpcupdeluxe V2.2.0h build 428

**Comment by LongDirtyAnimAlf** [comment]
I am not able to reproduce your problem.
Just did a vanilla install on Linux 64 bit. And cross-install towards arm-android.
Would you mind trying again. Perhaps a GitHub issue of some kind ?

**Comment by jgamigo** [comment]
Yep, is weird ... I try with other versions (other fpcupdeluxe, changing fpc versions, trunk, stable, etc) and same result. 
i use Fedora 35 ... every week some kind of update, maybe some library change. I can´t figure wich step is stucked (search some app, try download, compile some code, some right ...?)
I try recompile all fpcupdeluxe in my system for minimize some kind of "hidden resource"; it would not be the first time that I have to recompile a project due to a mysterious bug :D

**Comment by jgamigo** [comment]
Well, finally solve my issue. 
I recompile sources and error persist. In lazarus generate Release and Debug objectives and i ran it in debug mode. Error again. Finally (short history) the whole problem was caused by Optimization level of compiler, in my case need be "0". After that i recompile in release mode and cross build work as expected (and final size is 6.1MB ... a bit little).
Thank u for ur hard work doing a usefull tool, really saves a lot of time putting everything together.
I close the issue.
Happy new year!!!
