### ISSUE TITLE
Windows 10 x64: Error when compile Lazarus 2.3 and FPC 3.2.2

### ISSUE THREAD

**Issue by josiaslg** [LongDirtyAnimAlf/fpcupdeluxe#492]
Hi.
I'm trying to compile Lazarus 2.3 and FPC 3.2.2. 
In the end of process I have this output (console):
...
(3104) Compiling basebuildmanager.pas
(9022) Compiling resource ..\units\x86_64-win64\nogui\lazbuild.obj
(9015) Linking ..\lazbuild.exe
(1008) 71550 lines compiled, 10.0 sec, 4138496 bytes code, 522788 bytes data
Found valid lazbuild.exe application.
fpcupdeluxe: info: LazarusNativeInstaller (BuildModuleCustom: UserIDE): Running: make useride
fpcupdeluxe: Executing: C:\lazarus3\fpcbootstrap\make.exe --directory=C:\lazarus3\lazarus FPC=C:\lazarus3\fpc\bin\x86_64-win64\fpc.exe PP=C:\lazarus3\fpc\bin\x86_64-win64\ppcx64.exe USESVN2REVISIONINC=0 PREFIX=C:\lazarus3\lazarus INSTALL_PREFIX=C:\lazarus3\lazarus LAZARUS_INSTALL_DIR=C:\lazarus3\lazarus\ FPCDIR=C:\lazarus3\fpcsrc FPCMAKE=C:\lazarus3\fpc\bin\x86_64-win64\fpcmake.exe PPUMOVE=C:\lazarus3\fpc\bin\x86_64-win64\ppumove.exe UPXPROG=echo OPT=-vw-n-h-l-d-u-t-p-c- -g -gl -O1 LAZBUILDJOBS=8 useride CFGFILE=C:\lazarus3\config_lazarus\idemake.cfg (working dir: C:\lazarus3\lazarus)
./lazbuild.exe --max-process-count=8 --lazarusdir=. --build-ide=
using config file C:\lazarus3\lazarus\lazarus.cfg
SetPrimaryConfigPath NewValue="C:\lazarus3\config_lazarus" -> "C:\lazarus3\config_lazarus"
  $000000010005FFC9  DEBUGLNSTACK,  line 899 of lazloggerbase.pas
  $000000010005DD95  DEBUGLNSTACK,  line 11 of LazLoggerImpl.inc
  $00000001000025F0  ONIDEQUESTIONDIALOG,  line 347 of lazbuild.lpr
  $0000000100361C8A  IDEQUESTIONDIALOG,  line 131 of idedialogs.pas
  $0000000100111C37  OPENINSTALLEDDEPENDENCY,  line 6110 of ../packager/packagesystem.pas
  $0000000100101178  LOADLAZARUSBASEPACKAGE,  line 2239 of ../packager/packagesystem.pas
  $0000000100101045  LOADSTATICBASEPACKAGES,  line 2253 of ../packager/packagesystem.pas
  $0000000100005F42  INIT,  line 1174 of lazbuild.lpr
  $00000001000030BD  BUILDLAZARUSIDE,  line 530 of lazbuild.lpr
Error: (lazbuild) Package file not found
The package "IdeDebugger" is installed but no valid package file (.lpk) was found.
A broken dummy package was created.
lazbuild is non interactive, aborting now.
C:\lazarus3\fpcbootstrap\make.exe: *** [useride] Error 2
fpcupdeluxe: ERROR: LazarusNativeInstaller (BuildModuleCustom: UserIDE): make.exe returned exit status #2

ERROR: Fpcupdeluxe fatal error !
Sequencer (UserIDE): Failure running fpcupdeluxe: error executing sequence UserIDE
Sequencer (Lazarus): Failure running fpcupdeluxe: error executing sequence Lazarus
Sequencer (Only): Failure running fpcupdeluxe: error executing sequence Only
....
If i set lazarus 2.2.0, works ok (even FPC 3.2.2).

**Comment by LongDirtyAnimAlf** [comment]
This was a Lazarus issue. And it has been fixed in the meantime.
https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/9cba2f5f48bddd0e7077710e3d21496b4511317a
