### ISSUE TITLE
Win10 x64 unable to install stable lazarus + fpc

### ISSUE THREAD

**Issue by sergeybobko** [LongDirtyAnimAlf/fpcupdeluxe#494]
Error: (lazbuild) Unable to load package
Unable to open the package "virtualtreeview_package".
This package was marked for installation.
lazbuild is non interactive, aborting now.
C:\lazarus_stable\fpcbootstrap\make.exe: *** [useride] Error 2
fpcupdeluxe: ERROR: LazarusNativeInstaller (BuildModuleCustom: UserIDE): make.exe returned exit status #2

ERROR: Fpcupdeluxe fatal error !
Sequencer (UserIDE): Failure running fpcupdeluxe: error executing sequence UserIDE
Sequencer (Lazarus): Failure running fpcupdeluxe: error executing sequence Lazarus
Sequencer (Default): Failure running fpcupdeluxe: error executing sequence Default

**Comment by sergeybobko** [comment]
my fault, sorry

**Comment by josiaslg** [comment]
No problem. 
Thank you very much.
