### ISSUE TITLE
Combo to select the repository origin

### ISSUE THREAD

**Issue by henriquewerlang** [LongDirtyAnimAlf/fpcupdeluxe#495]
One suggestion I have is to modify the edit you have on the main screen, by a combobox, for the user to select which repository you want to install FPC.

The list of repository sources can be loaded with the command "git remote -v".

**Comment by LongDirtyAnimAlf** [comment]
Please elaborate on this request.
At the moment, there is a list of install-targets. What changes into that list should be made ?

**Comment by henriquewerlang** [comment]
Change the source URL of the repository by taking the information from the repository itself.
![image](https://user-images.githubusercontent.com/10869354/150983718-50bff164-6cc8-4b9c-9ab6-57f1b2108eef.png)

I downloaded the fonts locally and forced the URL exchange, to compile from my cloned repository.

**Comment by LongDirtyAnimAlf** [comment]
I am sorry about this, but I really do not understand what you mean and what you want.
And, what have fonts to do with repo's ?

**Comment by henriquewerlang** [comment]
Sorry, I'm using the translator to help me. Is not "font" but "source" the correct word to be used. The correct phare is "I downloaded the code source locally and forced to use the URL of my repository."

**Comment by LongDirtyAnimAlf** [comment]
> Change the source URL of the repository by taking the information from the repository itself.

Again. What info do you mean ?
Do you want fpcupdeluxe to point towards a local repo on your computer, and look into the remote URL that is defined inside this local repo ?

**Comment by henriquewerlang** [comment]
That's right, that's it! With this I can select the source of the search of the sources.

**Comment by LongDirtyAnimAlf** [comment]
I will leave this issue open to remind me to try to implement this if feasible.

**Comment by LongDirtyAnimAlf** [comment]
After long deliberations, I have had to decide not to implement this. Due to my limited time.
Sorry about this.
You can always do a pull for the necessary changes however.
