### ISSUE TITLE
new buttons in UI, are always enabled

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#497]
do we need to disable these 2 buttons until listbox (hash string) gets a selection?

![Screenshot from 2022-01-26 00-54-32](https://user-images.githubusercontent.com/4154978/151066241-1e159a86-37a7-4b35-8478-9e5f6ddf617f.png)

**Comment by LongDirtyAnimAlf** [comment]
Done.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/fbb1211e44c8417b01b701c8f35eb47484da5c0d
