### ISSUE TITLE
cannot install cross 'wasi-wasm32' on Linux x64

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#498]
I got this short log. what did I do wrongly?

![Screenshot from 2022-01-26 00-56-52](https://user-images.githubusercontent.com/4154978/151066543-388e6571-1f47-4004-876e-017287be38e4.png)

**Comment by leejoker** [comment]
you can use the main branch of fpc and  try it again
