### ISSUE TITLE
Modules, Vampyre, needs both

### ISSUE THREAD

**Issue by the-Arioch** [LongDirtyAnimAlf/fpcupdeluxe#500]
d:\fpcupdeluxe\ccr\vampyre\Packages\VampyreImagingPackage.lpk
d:\fpcupdeluxe\ccr\vampyre\Packages\VampyreImagingPackageExt.lpk

Both have to be installed if Vampyre added

Also, Castle Game Engine as of 7-alpha became dependent upon them both, but also makes their local clone of Vampyre library. It is work in progress. So it can keep changing in future. Dunno if CGE installatin from your modules would be compatible from a stand-alone Vampyre installation... 

But if it will it seems to be crucial to make both Vampyre packages installed *before* CGE otherwise Lazarus recompilation seems to fail. At least the recompilation from inside IDE consistently fails for me now, as CGE is tried before Vampyre-Ext and then it all breaks.

**Comment by the-Arioch** [comment]
Same thing with FUD...

```
D:\fpcupdeluxe\ccr\bgrabitmap\bgrabitmap\bgrawinresource.pas(1132,120) Note: (6058) Call to subroutine "function TFPGList<BGRAMultiFileType.TMultiFileEntry>.Get(Index:LongInt):TMultiFileEntry;" marked as inline is not inlined
Fatal: (1018) Compilation aborted
Error: D:\fpcupdeluxe\fpc\bin\x86_64-win64\ppcx64.exe returned an error exitcode
Error: (lazarus) ????? ?? castle_base 6.5: stopped with exit code 1
Error: (lazarus) ????? ?? SynEdit 1.0: terminated
Error: (lazarus) ????? ?? cairocanvas_pkg 0.0: terminated
(3104) Compiling bgralazresource.pas
D:\fpcupdeluxe\ccr\bgrabitmap\bgrabitmap\bgralazresource.pas(337,9) Warning: (5036) Local variable "filePos" does not seem to be initialized
D:\fpcupdeluxe\ccr\bgrabitmap\bgrabitmap\bgralazresource.pas(337,27) Warning: (5089) Local variable "fileContent" of a managed type does not seem to be initialized
(3104) Compiling bgraiconcursor.pas
Error: (lazarus) ????? ?? BGRABitmapPack 11.4: terminated
Error: (lazarus) [TLazPackageGraph.CompileRequiredPackages] "? ??襭?? 1"
Error: (lazarus) Building IDE: Compile AutoInstall Packages failed.
D:\fpcupdeluxe\fpcbootstrap\make.exe: *** [useride] Error 2
D:\fpcupdeluxe\fpcbootstrap\make.exe: Leaving directory `D:/fpcupdeluxe/lazarus'
fpcupdeluxe: ERROR: LazarusNativeInstaller (BuildModuleCustom: UserIDE): make.exe returned exit status #2


ERROR: Fpcupdeluxe fatal error !
Sequencer (UserIDE): Failure running fpcupdeluxe: error executing sequence UserIDE
Sequencer (Lazarus): Failure running fpcupdeluxe: error executing sequence Lazarus
Sequencer (Default): Failure running fpcupdeluxe: error executing sequence Default
```

Yet worse - Windows thrown 3 windows about process ppcx64.exe hard crashing...

**Comment by the-Arioch** [comment]
For future reference, no point in sorting `d:\fpcupdeluxe\config_lazarus\staticpackages.inc` - it gets re-created with broken order...

Editing fpcup.ini in FUD exe folder does not seem fix things too...
```
[FPCUPModule56]
; Vampyre imaging library
Name=vampyre
Description="Vampyre imaging library."
Installdir=$(basedir)/ccr/$(name)
Enabled=0
GITURL=https://github.com/galfar/imaginglib
ArchiveURL=https://github.com/galfar/imaginglib/archive/master.zip
; compile vampyre package
InstallExecute1=$(lazarusdir)/lazbuild --primary-config-path=$(LazarusPrimaryConfigPath) $(Installdir)/Packages/VampyreImagingPackage.lpk

+++ InstallExecute2=$(lazarusdir)/lazbuild --primary-config-path=$(LazarusPrimaryConfigPath) $(Installdir)/Packages/VampyreImagingPackageExt.lpk

UnInstall=rm -Rf $(Installdir)
```

albeit different failure this time

```
(3104) Compiling syneditmarkup.pp
D:\DelphiProjects\Libs\Games\castle-engine\src\images\castleimages_vampyre_imaging.inc(180,42) Error: (4000) Type mismatch
```

**Comment by the-Arioch** [comment]
Yet worse, did not notice...

FUD failed to detect all worker PPCx64.exe processes either quite or crashed.
FUD stil lthinks the cmpilatio nis in process, which it not for 10+ minutes now.

![2022-01-29 15_56_44-FPCUPdeluxe V2 2 0h for x86_64-win64-win32](https://user-images.githubusercontent.com/937774/151661862-845019fc-71b6-41ee-a7b7-ac028111962c.png)

**Comment by the-Arioch** [comment]
HALT button does not work, FUD probably lost links to worker processes/objects...

Can not exit from FUD nnormalyl either.

Was forced to kill the FUD process by OS means...

After restart it compiled OK, however two problems there in FUD: incomplete Vampyre installation and failure to detect compilers crash. 

_Aggravated by #481 and #486 probably._

And also maybe failure to update modules sources, though that is perhaps conceptual problem (probably touching that long thread inside #372).

**Comment by LongDirtyAnimAlf** [comment]
First things first.
Can you advice me on a source of (precompiled) Vampire libs ?
For all systems of (your) interest ?
Thank you.

**Comment by the-Arioch** [comment]
why precompiled? .ppu ABI would be changed by compiler arch, RTL version and even come compiler options. There is little point to make precompiled libs for FPC (Delphi at least has .BPLs, thuogh they are not always stable too, FPC does not)

as of the sources, https://github.com/galfar/imaginglib/ seems ok

**Comment by LongDirtyAnimAlf** [comment]
I misunderstood. Sorry. Done !
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/0aec2667126a947f5395f803e5782cee7cf500cf
