### ISSUE TITLE
custom patch - file path broken

### ISSUE THREAD

**Issue by the-Arioch** [LongDirtyAnimAlf/fpcupdeluxe#501]
```
fpcupdeluxe: WARNING: LazarusNativeInstaller (GetModule: Lazarus): Lazarus patching with D:\fpcupdeluxe\0001-Sparta.Generics-conflicts-with-FPC-3.2.x-makes-Lazar.patch failed due to missing patch file (D:\DelphiProjects\FPC\patchlazarus\D:\fpcupdeluxe\0001-Sparta.Generics-conflicts-with-FPC-3.2.x-makes-Lazar.patch).
```

Notice the `...patchlazarus\D:\fpcupdeluxe...` part.
It seems on Windows platform an absolute path was mis-detected for relative path and double-concatenation happenned.

**Comment by LongDirtyAnimAlf** [comment]
Solved.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/58a013f5c65453e2b9bb37b54782ed52a2be5991
Thanks for reporting.
