### ISSUE TITLE
Lazarus and another version of glibc 

### ISSUE THREAD

**Issue by RDL-28** [LongDirtyAnimAlf/fpcupdeluxe#503]
Hello.
I have glibc 2.33 installed on my system and applications compiled on my system won't run on systems with glibc versions lower than 2.33

Question.
Is it possible to compile Lazarus with a link to another version of glibc?

**Comment by RDL-28** [comment]
I have a suggestion to improve fpcupdelux

1. Create a separate github repository with cross libraries.
2. Add cross-libraries with different versions of glibc
3. Add to fpcupdeluxe the glibc version selection setting for cross-libraries.

Eventually:
The user gets the flexibility to cross compile.

This is very important for Linux systems.

I'm willing to help build some cross-libraries with debian jessie's glibc 2.19, but I need instructions on how to do it.

**Comment by RDL-28** [comment]
Your Linux cross-library build currently uses glibc 2.32, but many users have a lower version.

Accordingly, they will not run compiled applications.

**Comment by resistancelion** [comment]
I'll guess using older system is the answer, you can run (most) of the applications compiled for older glibc

**Comment by RDL-28** [comment]
I currently do this using virtual machines with debian jessie. There glibc 2.19.
All my projects compiled on vbox work on almost all systems.
If you use cross-libraries from fpcupdeluxe, then many of my projects do not start due to the high version of glibc.
That's why I'm asking for cross-libraries with a lower version of glibc.
