### ISSUE TITLE
Release v2.2.0h of fpcupdeluxe-x86_64-win64.exe needs gradle-6.8.3 instead of gradle-7.3.1

### ISSUE THREAD

**Issue by dexter4** [LongDirtyAnimAlf/fpcupdeluxe#507]
Release v2.2.0h of fpcupdeluxe-x86_64-win64.exe
by default installs gradle-7.3.1.

However, after installation, when trying to compile Android project,
gradle-7.3.1 shows error message:
"Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8."

Java 11 needs NDK23.

However the contents of file 
C:\fpcupdeluxe\ccr\lamw\ide_tools\uFormBuildFPCCross.pas 
shows that NDK23 is not supported, only NDK22 is supported.

The workaround solution is to manually use Gradle 6.8.3.
You can download it from:
https://gradle.org/releases/

**Comment by LongDirtyAnimAlf** [comment]
This change was implemented to be able to use the latest NDK version.
However, its very hard to maintain, due to changes in Android and LAMW.
I am willing to follow your advice and switch back to 6.8.3., but I am unsure about this.

**Comment by LongDirtyAnimAlf** [comment]
Done.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/d47f7475c6df0e8bf66cec293d1080548b1ea61f

**Comment by WayneSherman** [comment]
@dexter4 wrote:
> "Java 11 needs NDK23."

This is not the case.  ndk 22 works fine with OpenJDK 11 on both Windows and Linux.  

The Android Gradle Plugin for Gradle 7 requires OpenJDK 11, but that is not related to the ndk version:
https://developer.android.com/studio/releases/gradle-plugin#jdk-11

Gradle-7.3.1 also works for my testing (build APKs for several demos and a simple test app) on both Windows and Linux.

See forum post here:
https://forum.lazarus.freepascal.org/index.php?topic=59214.msg441509
