### ISSUE TITLE
Cross-compiling: cannot find /lib64/ld-linux-x86-64.so.2

### ISSUE THREAD

**Issue by mdbs99** [LongDirtyAnimAlf/fpcupdeluxe#509]
There is a project that I cannot cross-compile from Windows 32 bit to Linux 64 bit.
```
...
Debug: C:\lazarus\cross\bin\x86_64-linux\x86_64-linux-ld.exe: cannot find /lib64/ld-linux-x86-64.so.2
Error: Error while linking
Verbose: There were 1 errors compiling module, stopping
Verbose: Compilation aborted
Verbose: C:\lazarus\fpc\bin\i386-win32\ppcrossx64.exe returned an error exitcode
```
The strange thing is that I can compile a blank/new project—so cross compiling seems working—but not for this (and another) project.

Any tips?

My Environment:
Lazarus 2.0.12 r64642 FPC 3.2.0 i386-win32-win32/win64
![image](https://user-images.githubusercontent.com/1459306/161839326-c2986200-b14e-4e90-ad7e-c406cf15a8b4.png)

**Comment by LongDirtyAnimAlf** [comment]
Educated guess: this is a library that you are trying to compile ?

**Comment by mdbs99** [comment]
Yes, this is a library.

**Comment by mdbs99** [comment]
But I got this error, compiling a normal project (not a library) too:
(I've changed the original name of the project and directory)
```
...
(9015) Linking C:\foo\project1.bin
C:\lazarus\cross\bin\x86_64-linux\x86_64-linux-ld.exe: cannot find /lib/x86_64-linux-gnu/libm.so.6
C:\lazarus\cross\bin\x86_64-linux\x86_64-linux-ld.exe: cannot find /usr/lib/x86_64-linux-gnu/libmvec_nonshared.a
C:\lazarus\cross\bin\x86_64-linux\x86_64-linux-ld.exe: cannot find /lib/x86_64-linux-gnu/libmvec.so.1
Error: (9013) Error while linking
Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: C:\lazarus\fpc\bin\i386-win32\ppcrossx64.exe returned an error exitcode
```

**Comment by LongDirtyAnimAlf** [comment]
Its not the same error. Different libraries are involved.

About the first linking error when compiling a library.
See: https://gitlab.com/freepascal.org/fpc/source/-/blob/main/compiler/systems/t_linux.pas#L600
As you can see, FPC wants to link with the dynamic linker when building a library. And the hardcoded path contains the sysroot !
And that sysroot must be set to the correct path on your system.
AFAIK, this sysroot is set by the compiler option -XR.

**Comment by LongDirtyAnimAlf** [comment]
The second linking error is caused by a wrong library setting. It source is fpcupdeluxe itself. I will try to fix it.

**Comment by mdbs99** [comment]
I also updated my fpcupdeluxe, then use "Cross/Update all", but I got the same errors.

![image](https://user-images.githubusercontent.com/1459306/161947484-12d25287-3457-40c1-93fe-553a0f2df313.png)

**Comment by mdbs99** [comment]
> About the first linking error when compiling a library.
See: https://gitlab.com/freepascal.org/fpc/source/-/blob/main/compiler/systems/t_linux.pas#L600
As you can see, FPC wants to link with the dynamic linker when building a library. And the hardcoded path contains the sysroot!
And that sysroot must be set to the correct path on your system.
AFAIK, this sysroot is set by the compiler option -XR.

I can compile using -XR but for use it, I needed to create a new directory `lib64` into `cross\lib\x86_64-linux\`, and copy all files to there too, as the compiler try to search in path+`lib64`. Then, usind `-XRC:\lazarus\cross\lib\x86_64-linux` it compiles... but it is "fast & dirt" and now I have a duplicate directory.
Another problem is that another programmer will have a different path for the -XR so, it cannot stay in hardcoded.

Or I missed something and doing it wrong?

**Comment by LongDirtyAnimAlf** [comment]
No, you are not missing something.
I have had a lengthy discussion with FPC core developers about this. They did not want to change this behavior. And the workaround you use, is the only correct one to cross-build a library.

I am sorry about this.

I do not understand why the FPC devs want to link a library with the dynamic linker.
And they rejected a patch by me to have two search options: one with the sysroot and one without the sysroot.

Sidenote.
New libs can be found here. These should solve the other linking problem (libm related).
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/crosslibs_v1.3/CrossLibsLinuxx64.zip

**Comment by mdbs99** [comment]
Not sure if you saw my EDIT before so, I will write again:
For do not having a lib directory copy in (new) `lib64 `, is it better change it in fpc.cfg? But does this path will be replaced, if I update cross-compilers using fpccupdeluxe?

Thanks for CrossLibsLinuxx64.zip, I will try and give you a feedback, ASAP.

**Comment by LongDirtyAnimAlf** [comment]
Good.
As per your edit. I do not know unfortunately. Just try !
And feedback is welcome.

**Comment by mdbs99** [comment]
It had no effect changing in fpc.cfg.
So, I will keep this duplicated directory `lib64`, copied from `cross\lib\x86_64-linux`—as FPC team is keeping this wrong design, as you has explained, I guess I can use this "setup" in my computer too :)

Let's move on, you've already helped a lot. Thank you.
