### ISSUE TITLE
Embedded Pico not installing on Raspberry Pi

### ISSUE THREAD

**Issue by Gavinmc42** [LongDirtyAnimAlf/fpcupdeluxe#514]
Fpcupdeluxe installs Pico fpc/laz on Windows and Linux x86_64 but halts at the crosstools section when used on Raspberry Pi OS.
Tried on 32 and 64bit Pi OS armhf/aarch64.
These are more native compiling than cross compiling, so an extra test for Pi Linux Arm might be needed?
It does install fpc for building fpc/laz but not the full embedded fpc.

**Comment by michael-ring** [comment]
This is either totally simple or very difficult to solve. Copying the local binutils on the raspi to arm-none-emberdded-* maybe enough to solve this, I will try today evening or tomorrow.

**Comment by Gavinmc42** [comment]
Thanks guys,

Garry at Ultibo released a new IDE with the more recent fpc/laz that compiled Pi OS fpc/laz code as well Ultibo code.
His rtl/embedded code has the old embedded stuff.
"ppcrossarm -iu" on Windows/Linux does show those old micros plus the ultibo Pi/QEMU rtl.

I was hoping just copying the new rtl/embedded source  and rebuilding would just work or perhaps blowup big time.
No real idea how fpcupdeluxe does it's magic.

This worked on my Pi400 using the new Ultibo IDE, allows me to use i2c etc
https://github.com/rudiratlos/rpi-hal
I was able to port some i2c sensor Ultibo code to rpi-hal, with mostly a single line change.

I did notice the embedded Pico code is not calling SDK version 1.3, that has TinyUSB in it.
PC/Pi to Pico via USB, using fpc, that would be cool.
Some of the Ultibo guys are getting close using Pico C/SDK.

Then it might be possible to use a USB/Pico as a SPI/i2c/Uart dongle on Win/Linux which lack these Pi features.
Anyway, my dream is one day an IDE on Windows/Linux/Pi that compiles native/Pi Ultibo and also for that bunch of embedded micros.

One IDE to rule them all:)

Regards
Gavin

________________________________

**Comment by LongDirtyAnimAlf** [comment]
I have for long disabled the ability to cross-compile on the Pi itself. Under the assumption that nobody would be interested in cross-compiling on the Pi.
Do I understand correctly that you want to do cross-work on the Pi ?

**Comment by Gavinmc42** [comment]
At the moment only "cross" compile to Pico is required.
Pi's with Pico's is a combo that has potential.
This scenario is more native than cross, both are ARM based.

I hope to do RISC-V Laz/fpc for embedded apps on my Pi400's one day.
Cross compiling to x86? That would be cool, but not needed for my apps yet.
AVR and MIPS CPUs have some interest, mainly from my historical use of them.

I have found overclocking Pi400's to 2+GHz make for a reasonable, cheap development box.
The Free Pascal compiler is fast enough not to be annoyingly slow, unlike C.....

So yes "cross" compiling on Pi's is of interest.
If Pi's can fpc compile all those rtl/embedded CPUs, that's a better alternative to C embedded dev.
Fpc/Laz/RAD applied to microcontrollers should save app development time.

Pi5, Pi6 are going to be even more useful as fpc dev tools whenever they show up.


________________________________
