### ISSUE TITLE
install lazarus on aarch64 MacOSX error

### ISSUE THREAD

**Issue by terrylao** [LongDirtyAnimAlf/fpcupdeluxe#515]
fpcupdeluxe: ERROR: LazarusNativeInstaller (GetModule: Lazarus): Could not get version of Lazarus sources. Expect severe errors.
fpcupdeluxe: Executing: /usr/bin/git describe --tags --long --always (working dir: /Users/terrylou/Lazarus/lazarus)
fpcupdeluxe: Executing: /usr/bin/git log -g -1 --pretty=oneline (working dir: /Users/terrylou/Lazarus/lazarus)
fpcupdeluxe: Executing: /usr/bin/git describe --tags --all --long --always (working dir: /Users/terrylou/Lazarus/lazarus)
fpcupdeluxe: info: LazarusNativeInstaller (GetModule: Lazarus): Lazarus is at revision/hash: FRET_UNKNOWN_REVISION
fpcupdeluxe: info: LazarusNativeInstaller (GetModule: Lazarus): No updates for Lazarus found.
fpcupdeluxe: info: LazarusNativeInstaller (GetModule: Lazarus): Adding dragonfly include file for IDE.
fpcupdeluxe: ERROR: LazarusNativeInstaller (BuildModule: Lazarus): /Users/terrylou/Lazarus/lazarus/Makefile not found. Severe error. Should not happen. Aborting build Lazarus.

ERROR: Fpcupdeluxe fatal error !
Sequencer (LazarusSimple): Failure running fpcupdeluxe: error executing sequence LazarusSimple
Sequencer (DefaultSimple): Failure running fpcupdeluxe: error executing sequence DefaultSimple

**Comment by LongDirtyAnimAlf** [comment]
Fpcupdeluxe cannot find the Lazarus sources it seems.
I do not know what causes this error.
Is this error still valid at this moment.
Otherwise, I would like to close.

**Comment by terrylao** [comment]
quarantine problem,
solve:
sudo xattr -r -d com.apple.quarantine fpcupdeluxe-aarch64-darwin-cocoa.app

**Comment by LongDirtyAnimAlf** [comment]
Thanks for the feedback !
Closing.
