### ISSUE TITLE
Access Violation after start fpcupdeluxe-x86_64-darwin-cocoa

### ISSUE THREAD

**Issue by awunnenb** [LongDirtyAnimAlf/fpcupdeluxe#516]
Access Violation after start fpcupdeluxe-x86_64-darwin-cocoa
MacBook Pro Intel with  fresh Installed Monterey 12.3.1

**Comment by LongDirtyAnimAlf** [comment]
I guess you are starting fpcupdeluxe from the Downloads folder.
On startup, fpcupdeluxe needs to create some files. The Downloads folder is privileged, so this will fail.
Please create a folder on your Desktop. Move fpcupdeluxe to this folder and try again from this folder.

**Comment by awunnenb** [comment]
Your are right. This solves the problem.
Info: There is a security warning in the Chrome Browser after download fpxupdeluxe.

**Comment by LongDirtyAnimAlf** [comment]
Good.
The security warning is not something I can fix unfortunately.
