### ISSUE TITLE
fpcupdeluxe can't find fpc.exe

### ISSUE THREAD

**Issue by a-nouri** [LongDirtyAnimAlf/fpcupdeluxe#518]
I installed lazarus 2.2.2 , fpc.exe is in "lazarus\fpc\3.2.2" folder. but fpcupdelux look it in "lazarus\fpc\".
thanks

**Comment by LongDirtyAnimAlf** [comment]
Did you install both FPC and Lazarus using the same fpcupdeluxe into a dedicated directory ?
