### ISSUE TITLE
Error: (5000) Identifier not found "GetCompiledTargetCPU"

### ISSUE THREAD

**Issue by levone1** [LongDirtyAnimAlf/fpcupdeluxe#520]
I get above error when trying to install fpc and lazarus on Linux mint x86_64.  

I have tried setting cpu/os values in "setup", and tried a few differrent menu options, (stable, fixes, gitlab checked, gitlab unchecked, etc.) - always the same.  

apt install lazarus installs fine, but won't build Cudatext, which is really my main goal at this point.  AlexyT directed me here, but now I  can't install this...

Here is full output in minibuffer:
`fpcupdeluxe: Performing SVN/GIT/HG/FTP/URL checkout/download. Please wait, could take some time.
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC was at revision/hash: FRET_UNKNOWN_REVISION
fpcupdeluxe: info: FPCNativeInstaller (GetModule: FPC): FPC is now at revision/hash: release_3_2_2-0-g0d122c4953
fpcupdeluxe: info: FPC native builder: Detected source version FPC (source): 3.2.2
fpcupdeluxe: info: FPC native builder: Using FPC bootstrap compiler with version: 3.2.2
fpcupdeluxe: Performing SVN/GIT/HG/FTP/URL checkout/download. Please wait, could take some time.
fpcupdeluxe: info: LazarusNativeInstaller (GetModule: Lazarus): Lazarus was at revision/hash: FRET_UNKNOWN_REVISION
fpcupdeluxe: info: LazarusNativeInstaller (GetModule: Lazarus): Lazarus is now at revision/hash: lazarus_2_2_2-24-g564f36e8fe
fpcupdeluxe: info: Lazarus native builder: Detected source version Lazarus: 2.2.3
fpcupdeluxe: info: Lazarus native builder: Using FPC compiler with version: 3.2.2
fpcupdeluxe: Start of compile error summary.
/home/disciple/fpcupdeluxe/lazarus/ide/generatefppkgconfigurationdlg.pas(173,25) Error: (5000) Identifier not found "GetCompiledTargetCPU"
fpcupdeluxe: Start of compile error summary.
generatefppkgconfigurationdlg.pas(538) Fatal: (10026) There were 1 errors compiling module, stopping
make[1]: *** [Makefile:3793: idepkg] Error 2
fpcupdeluxe: Start of compile error summary.
Fatal: (1018) Compilation aborted
generatefppkgconfigurationdlg.pas(538) Fatal: (10026) There were 1 errors compiling module, stopping
fpcupdeluxe: Start of compile error summary.
Error: /home/disciple/fpcupdeluxe/fpc/bin/x86_64-linux/ppcx64 returned an error exitcode
fpcupdeluxe: Start of compile error summary.
Error: (lazarus) Build IDE: stopped with exit code 2
fpcupdeluxe: Start of compile error summary.
Error: (lazarus) Building IDE: Building IDE failed.
fpcupdeluxe: Start of compile error summary.
fpcupdeluxe: ERROR: LazarusNativeInstaller (BuildModuleCustom: UserIDE): make returned exit status #512
fpcupdeluxe: Done !!
`

Any help?

**Comment by LongDirtyAnimAlf** [comment]
I just installed fixes/fixes on Mint64 without any problems.
Does this issue still persist ?

**Comment by levone1** [comment]
> I just installed fixes/fixes on Mint64 without any problems. Does this issue still persist ?

sorry, no - I tried again and was successful. .. Thanks
