### ISSUE TITLE
Error odroid C1+ with ubuntu 20.04

### ISSUE THREAD

**Issue by elmarfaber** [LongDirtyAnimAlf/fpcupdeluxe#521]
I try to install it on the following system: odroid C1+ with ubuntu 20.04
and get the following error (stable and trunk):

(3104) Compiling ./frames/env_file_filters.pas
(3104) Compiling ./frames/project_application_optiError: /home/odroid/fpcupdeluxe/fpc/bin/arm-linux/ppcarm can't be executed, error message: Failed to execute "/home/odroid/fpcupdeluxe/fpc/bin/arm-linux/ppcarm", error code: -9
make[2]: *** [Makefile:4667: lazarus] Fehler 1
make[1]: *** [Makefile:5103: ide] Fehler 2
make: *** [Makefile:3789: ide] Fehler 2
make[2]: Verzeichnis „/home/odroid/fpcupdeluxe/lazarus/ide“ wird verlassen
make[1]: Verzeichnis „/home/odroid/fpcupdeluxe/lazarus/ide“ wird verlassen
make: Verzeichnis „/home/odroid/fpcupdeluxe/lazarus“ wird verlassen
fpcupdeluxe: ERROR: LazarusNativeInstaller (BuildModuleCustom: Lazarus): make returned exit status #512

ERROR: Fpcupdeluxe fatal error !
Sequencer (LazarusSimple): Failure running fpcupdeluxe: error executing sequence LazarusSimple
Sequencer (DefaultSimple): Failure running fpcupdeluxe: error executing sequence DefaultSimple

Is there a chance to solve the problem?

**Comment by LongDirtyAnimAlf** [comment]
Do you have enough memory (swap) and disk-space ?

**Comment by elmarfaber** [comment]
You're right - after creating a swap file the error disappears but now I get another error (trunc):
(1008) 39231 lines compiled, 10.9 sec
/usr/bin/make -C ide/packages/idedebugger
/root/fpcupdeluxe/fpc/bin/arm-linux/fpc.sh -MObjFPC -Scghi -O1 -g -gl -l -vewnhibq -dLCL -dLCLgtk2 -Fuframes -Fu../../../packager/units/arm-linux -Fu../../../components/lazdebuggers/lazdebuggerintf/lib/arm-linux -Fu../../../components/lazutils/lib/arm-linux -Fu../../../components/buildintf/units/arm-linux -Fu../../../components/freetype/lib/arm-linux -Fu../../../lcl/units/arm-linux -Fu../../../components/debuggerintf/lib/arm-linux -Fu../../../lcl/units/arm-linux/gtk2 -Fu../../../components/fpdebug/lib/arm-linux -Fu../../../components/lazcontrols/lib/arm-linux/gtk2 -Fu../../../components/lclextensions/lib/arm-linux-gtk2 -Fu../../../components/ideintf/units/arm-linux/gtk2 -Fu../../../components/lazdebuggers/cmdlinedebuggerbase/lib/arm-linux -Fu../../../components/virtualtreeview/lib/arm-linux-gtk2 -Fu../../../components/lazcontrols/design/lib/arm-linux/gtk2 -Fu../../../components/lazdebuggers/lazdebuggerfp/lib/arm-linux -Fu. -Fu/root/fpcupdeluxe/fpcsrc/rtl -FE. -FUlib/arm-linux -Fl/usr/lib/gcc/arm-linux-gnueabihf/9 -vw-n-h-l-d-u-t-p-c- -g -gl -O1 -darm idedebuggerpackage.pas
(1002) Target OS: Linux for ARMHF
(3104) Compiling idedebuggerpackage.pas
(3104) Compiling idedebuggerbase.pas
(3104) Compiling idedebuggerwatchresult.pas
(3104) Compiling idedebuggerutils.pas
(3104) Compiling idedebuggerfpdbgvalueconv.pas
/root/fpcupdeluxe/lazarus/ide/packages/idedebugger/idedebuggerfpdbgvalueconv.pas(8,35) Fatal: (10022) Can't find unit FpDebugValueConvertors used by IdeDebuggerFpDbgValueConv
make: *** [Makefile:3778: basecomponents] Error 2
Fatal: (1018) Compilation aborted
Error: /root/fpcupdeluxe/fpc/bin/arm-linux/ppcarm returned an error exitcode
fpcupdeluxe: ERROR: LazarusNativeInstaller (BuildModuleCustom: Lazarus): make returned exit status #512

ERROR: Fpcupdeluxe fatal error !
Sequencer (LazarusSimple): Failure running fpcupdeluxe: error executing sequence LazarusSimple
Sequencer (DefaultSimple): Failure running fpcupdeluxe: error executing sequence DefaultSimple

**Comment by elmarfaber** [comment]
the stable version can be installed

**Comment by LongDirtyAnimAlf** [comment]
Closing.
This is not an issue of fpcupdeluxe.
FPC trunk and Lazarus trunk may fail at any time due to unforeseen changes that may introduce buggers.
