### ISSUE TITLE
Gus downloader label doesn't fit

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#523]
2.2.0j for linux-gtk2-x64
Ubuntu 20

![gus](https://user-images.githubusercontent.com/4154978/178679523-d012cdc5-96b4-43de-bcca-c4b46dc79635.png)

**Comment by LongDirtyAnimAlf** [comment]
Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/v2.2.0k/fpcupdeluxe-x86_64-linux
