### ISSUE TITLE
[Linux] Error inside worker thread for package utils-h2pas

### ISSUE THREAD

**Issue by rchastain** [LongDirtyAnimAlf/fpcupdeluxe#526]
Hello!

I tried to install Lazarus 2.2.2 plus FPC 3.2.2, using FPCUPdeluxe 2.2.0j.

The installation fails.

```
Error inside worker thread for package utils-h2pas: External command "/bin/pyacc h2pas/h2pas.y h2pas/h2pas.pas" failed with exit code 256. Console output:
TP Yacc Version 4.1a [April 2000], Copyright (c) 1990-2000 Albert Graef                                                                                   
FATAL: cannot open file /usr/lib/fpc/lexyacc/yyparse.cod    
```

**Comment by rchastain** [comment]
I tried another installation, using the "Stable" button. Installation successful. Now I have Lazarus 2.2.2 installed.

**Comment by LongDirtyAnimAlf** [comment]
I have been hunting this bugger for years. To no avail unfortunately.
In most cases, re-running fpcupdeluxe solves.
I will close this issue, due to the fact that it has been reported many times before, and I am not able to solve.
Sorry about this.

**Comment by rchastain** [comment]
> I have been hunting this bugger for years. To no avail unfortunately. In most cases, re-running fpcupdeluxe solves.

Thank you for the answer. I didn't know that it had already been reported.

Regards.

Roland
