### ISSUE TITLE
install fpc+laz error

### ISSUE THREAD

**Issue by Ericwang1104** [LongDirtyAnimAlf/fpcupdeluxe#527]
Checking dev-libs for: win32
Found valid svn.exe application.
Found valid git.exe application.
Found valid hg.exe application.
fpcupdeluxe: ERROR: Tried to get FPC version from version.pas, but no version.pas found
fpcupdeluxe: ERROR: Tried to get FPC version from Makefile.fpc, but no Makefile.fpc found
fpcupdeluxe: info: FPCNativeInstaller (CleanModule: FPC): Running make distclean twice
fpcupdeluxe: Executing: E:\fpcupdeluxe\fpcbootstrap\make.exe FPC=E:\fpcupdeluxe\fpcbootstrap\ppcx64.exe --directory=E:\fpcupdeluxe\fpc FPCMAKE=E:\fpcupdeluxe\fpc\bin\x86_64-win64\fpcmake.exe PPUMOVE=E:\fpcupdeluxe\fpc\bin\x86_64-win64\ppumove.exe FPCDIR=E:\fpcupdeluxe\fpc PREFIX=E:\fpcupdeluxe\fpc INSTALL_PREFIX=E:\fpcupdeluxe\fpc UPXPROG=echo CPU_SOURCE=x86_64 OS_SOURCE=win64 CPU_TARGET=x86_64 OS_TARGET=win64 distclean (working dir: E:\fpcupdeluxe\fpc)
E:\fpcupdeluxe\fpcbootstrap\make.exe: *** No rule to make target `distclean'.  Stop.

ERROR: Fpcupdeluxe fatal error !
Sequencer (FPC): Failure running fpcupdeluxe: error executing sequence FPC
Sequencer (Default): Failure running fpcupdeluxe: error executing sequence Default

**Comment by LongDirtyAnimAlf** [comment]
It seems that fpcupdeluxe did not succeed in getting the sources. Due to a cause unknown to me.
My advice: make a whole new install in a different directory.

**Comment by regs01** [comment]
> It seems that fpcupdeluxe did not succeed in getting the sources. Due to a cause unknown to me. My advice: make a whole new install in a different directory.

When feeding a Zip file from Gitlab it unpacks them into subfolder with archive name. So fpc sources ends up in `./fpcupdelux/fpcsrc/archivename/` instead of just `./fpcupdelux/fpcsrc`
