### ISSUE TITLE
Message after compiling is complete

### ISSUE THREAD

**Issue by han-k59** [LongDirtyAnimAlf/fpcupdeluxe#528]
I like FPCupdeLuxe and use it regularly in Linux and Mac including cross compiling from Linux. 

I have a little problem with the final message:

**SUCCESS: Fpcupdeluxe ended without errors.**

We I read the final message the first thing i see is the word "**error**" making me a little nervous. Did it fail after working so hard??

I would suggest not to use the words "without error" if it all went as plannedl but simple a positive message like:

SUCCESS. 

or

SUCCESS, installation complete!

Thanks, Han

**Comment by LongDirtyAnimAlf** [comment]
Done.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/874561c9f2b7c4cee7dcb408e8831f72db889948
