### ISSUE TITLE
cross compile  x86_64 linux failed

### ISSUE THREAD

**Issue by Ericwang1104** [LongDirtyAnimAlf/fpcupdeluxe#529]
echo ppcrossx64.exe
ppcrossx64.exe
E:/fpcupdeluxe/fpc/bin/x86_64-win64/ginstall.exe -m 755 -d E:\fpcupdeluxe\fpc/bin/x86_64-win64
E:/fpcupdeluxe/fpc/bin/x86_64-win64/cp.exe -fp ppcrossx64.exe E:\fpcupdeluxe\fpc/bin/x86_64-win64/ppcrossx64.exe
fpcupdeluxe: info: FPCCrossInstaller (BuildModuleCustom: FPC): Running E:\fpcupdeluxe\fpcbootstrap\make.exe [step # st_Rtl] (FPC crosscompiler: x86_64-linux) with CROSSOPT: -XPx86_64-linux- -Xd -FlE:\fpcupdeluxe\cross\lib\x86_64-linux
fpcupdeluxe: Executing: E:\fpcupdeluxe\fpcbootstrap\make.exe --directory=E:\fpcupdeluxe\fpc FPCMAKE=E:\fpcupdeluxe\fpc\bin\x86_64-win64\fpcmake.exe PPUMOVE=E:\fpcupdeluxe\fpc\bin\x86_64-win64\ppumove.exe PREFIX=E:\fpcupdeluxe\fpc INSTALL_PREFIX=E:\fpcupdeluxe\fpc FPCDIR=E:\fpcupdeluxe\fpc UPXPROG=echo GIT=C:\PROGRA~1\Git\cmd\git.exe CROSSBINDIR=E:\fpcupdeluxe\cross\bin\x86_64-linux FPCFPMAKE=E:\fpcupdeluxe\fpc\bin\x86_64-win64\fpc.exe FPC=E:\fpcupdeluxe\fpc\bin\x86_64-win64\ppcrossx64.exe rtl_all CROSSINSTALL=1 CPU_SOURCE=x86_64 OS_SOURCE=win64 OS_TARGET=linux CPU_TARGET=x86_64 NOGDBMI=1 BINUTILSPREFIX=x86_64-linux- CROSSOPT=-XPx86_64-linux- -Xd -FlE:\fpcupdeluxe\cross\lib\x86_64-linux OPT=-vw-n-h-l-d-u-t-p-c-  (working dir: E:\fpcupdeluxe\fpc)
E:/fpcupdeluxe/fpcbootstrap/make.exe -C rtl all
E:/fpcupdeluxe/fpcbootstrap/make.exe -C linux all
E:/fpcupdeluxe/fpcbootstrap/make.exe E:/fpcupdeluxe/fpc/rtl/units/x86_64-linux
E:\fpcupdeluxe\cross\bin\x86_64-linux/x86_64-linux-as.exe --64 -o E:/fpcupdeluxe/fpc/rtl/units/x86_64-linux/prt0.o x86_64/prt0.as
E:/fpcupdeluxe/fpcbootstrap/make.exe E:/fpcupdeluxe/fpc/rtl/units/x86_64-linux
E:\fpcupdeluxe\cross\bin\x86_64-linux/x86_64-linux-as.exe --64  -o E:/fpcupdeluxe/fpc/rtl/units/x86_64-linux/dllprt0.o x86_64/dllprt0.as
E:/fpcupdeluxe/fpcbootstrap/make.exe E:/fpcupdeluxe/fpc/rtl/units/x86_64-linux
E:\fpcupdeluxe\cross\bin\x86_64-linux/x86_64-linux-as.exe --64 -o E:/fpcupdeluxe/fpc/rtl/units/x86_64-linux/cprt0.o x86_64/cprt0.as
E:/fpcupdeluxe/fpcbootstrap/make.exe E:/fpcupdeluxe/fpc/rtl/units/x86_64-linux
E:\fpcupdeluxe\cross\bin\x86_64-linux/x86_64-linux-as.exe --64 -o E:/fpcupdeluxe/fpc/rtl/units/x86_64-linux/gprt0.o x86_64/gprt0.as
E:/fpcupdeluxe/fpcbootstrap/make.exe E:/fpcupdeluxe/fpc/rtl/units/x86_64-linux
E:\fpcupdeluxe\cross\bin\x86_64-linux/x86_64-linux-as.exe --64 -o E:/fpcupdeluxe/fpc/rtl/units/x86_64-linux/abitag.o x86_64/abitag.as
E:/fpcupdeluxe/fpc/bin/x86_64-win64/ppcrossx64.exe -Ur -Tlinux -XPx86_64-linux- -Xr -Ur -Xs -O2 -n -Fi../inc -Fi../x86_64 -Fi../unix -Fix86_64 -FDE:\fpcupdeluxe\cross\bin\x86_64-linux -FE. -FUE:/fpcupdeluxe/fpc/rtl/units/x86_64-linux -Cg -vw-n-h-l-d-u-t-p-c- -dx86_64 -dRELEASE -XPx86_64-linux- -Xd -FlE:\fpcupdeluxe\cross\lib\x86_64-linux  -Us -Sg system.pp
system.pp(490,1) Fatal: Internal error 2015030501
Fatal: Compilation aborted
make.exe[1]: *** [linux_all] Error 2
E:\fpcupdeluxe\fpcbootstrap\make.exe: *** [rtl_all] Error 2
fpcupdeluxe: ERROR: FPCCrossInstaller (BuildModuleCustom: FPC): Running cross compiler fpc E:\fpcupdeluxe\fpcbootstrap\make.exe for x86_64-linux failed with an error code.

ERROR: Fpcupdeluxe fatal error !
Sequencer (FPCCleanBuildOnly): Failure running fpcupdeluxe: error executing sequence FPCCleanBuildOnly
Sequencer (Only): Failure running fpcupdeluxe: error executing sequence Only
Building cross-tools failed. Aborting.

**Comment by LongDirtyAnimAlf** [comment]
Please give me more info.
What FPC version do you use in this install ?
Thanks.

**Comment by Ericwang1104** [comment]
my fpc version is 3.2.2   
I think it may be due to the floating point number of x64 platform

**Comment by LongDirtyAnimAlf** [comment]
I can confirm this issue.
Will try to solve !

**Comment by LongDirtyAnimAlf** [comment]
New binary. Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/v2.2.0k/fpcupdeluxe-x86_64-win64.exe
