### ISSUE TITLE
Confusing warning dialog about crosscompiling from Windows 64bits to Linux

### ISSUE THREAD

**Issue by brindys** [LongDirtyAnimAlf/fpcupdeluxe#530]
When you try to add or update the crosscompiler for Linux x86_64 (the most common OS in hosting platforms) from a Windows 64 bits machine, fpcupdeluxe warns about doing so, stating that it is an ill-advised idea, and recommends to install Windows 32 bits.
"Win64 OS disabled extended support for 64-bit applications"  Do you mean that Microsoft disabled the use of 64 bits exes? Where?
This is really confusing.

**Comment by LongDirtyAnimAlf** [comment]
No. It's just that 80 bit floats are not supported by Win64. And thus also not supported when crossing towards other targets.
