### ISSUE TITLE
Cross-compile from Windows to MacOS

### ISSUE THREAD

**Issue by mdbs99** [LongDirtyAnimAlf/fpcupdeluxe#531]
My env is Lazarus 2.3.0 (rev main-2_3-1773-gcbb17d6aeb) FPC 3.2.3 i386-win32-win32/win64

I'm not sure if it is a fpcupdeluxe issue, but if it's not, perhaps you can help me.
I use Windows and installed cross-compile to MacOS. I can compile to MacOS without errors. Then, Lazarus creates a `project1.app` directory and `project1` binary, in the same directory—compile to x86_64 + cocoa.

Shouldn't `project1`  be created into `project1.app\Contents\MacOS` ?
1. if I copy `project1.app`  and `project1` binary to MacOS and try to run, it raises an error.
2. if I copy `project1` binary to `project1.app\Contents\MacOS`, then copy to MacOS, it doesn't work either.

Thanks.

**Comment by LongDirtyAnimAlf** [comment]
First step.
Try to run only the project1 binary on your Mac ! From a terminal to get feedback.

**Comment by mdbs99** [comment]
I understood.
The problem was `access denied` as it was not installed... I gave access and it runs.
As it is a GUI app, it should't see a console, but it is showing one. To "fix" that, I've copied `project1` binary to `project1.app/Contents/MacOS`, run the "package", then the console disapear.

**Comment by LongDirtyAnimAlf** [comment]
Thanks for the feedback.
As a favor, please give as much attention on the forum for the cross-abilities of FPC and Lazarus. I still find it a unique feature of both to be able to build Linux and Mac apps on a Windows PC. That deserves a lot (more) attention.
