### ISSUE TITLE
error updating cross for FreeBSD i386, others were updated OK

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#532]
in this log,
[er.log](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/9387067/er.log)

find thje 'Fatal:' string with FPC error.
or use this full log,

[er2.log](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/9387069/er2.log)

this place:

![Screenshot from 2022-08-20 15-22-41](https://user-images.githubusercontent.com/4154978/185745990-9bed94eb-25c3-4d35-9369-6ff88b6af4ca.png)

**Comment by marcovtje** [comment]
See f341baeaa783fff4b50cec8757e3b7a85837bfd7

**Comment by Alexey-T** [comment]
solved in FPC 'main'.

**Comment by marcovtje** [comment]
Merged to fixes,.
