### ISSUE TITLE
Can not run under macOS 12.5.1 with M1 chips

### ISSUE THREAD

**Issue by exsystem** [LongDirtyAnimAlf/fpcupdeluxe#534]
Simply as the issue title says:

```bash
➜  MacOS pwd
/Applications/FPCUPDeluxe/fpcupdeluxe-aarch64-darwin-cocoa.app/Contents/MacOS
➜  MacOS ./fpcupdeluxe-aarch64-darwin-cocoa
[1]    29024 killed     ./fpcupdeluxe-aarch64-darwin-cocoa
```

**Comment by LongDirtyAnimAlf** [comment]
Two tips.

1:
Run fpcupdeluxe from a custom folder created by yourself.
E.g. create a folder on your desktop, copy fpcupdeluxe into it and run from there and install FPC and Lazarus in there.
2:
Resolve quarantine issues.
sudo xattr -r -d com.apple.quarantine fpcupdeluxe-aarch64-darwin-cocoa.app

**Comment by exsystem** [comment]
No.. It's still not working..

**Comment by LongDirtyAnimAlf** [comment]
As your feedback is very sparse, and I do not have a Mac, I am sorry to tell you I cannot help you any further.
Will leave this issue open for a short while, for others to share their ideas.

**Comment by michael-ring** [comment]
You also need to codesign:
aarch64:
codesign -s - fpcupdeluxe-aarch64-darwin-cocoa.app/Contents/MacOS/fpcupdeluxe-aarch64-darwin-cocoa 
x86_64:
codesign -s - fpcupdeluxe-x86_64-darwin-cocoa.app/Contents/MacOS/fpcupdeluxe-x86_64-darwin-cocoa

**Comment by exsystem** [comment]
code sign works! but the application icon is the default plain macOS application icon, not the lovely monkey head as the x86_64 one like.
however, it is not needed for x86_64, as I just download and double-click to run.
