### ISSUE TITLE
Build IDE failed  

### ISSUE THREAD

**Issue by steveswwei** [LongDirtyAnimAlf/fpcupdeluxe#538]
OS Linux Unbuntu 22.04
fpc 3.2.2
lazarus 2.2.4
Install Directory:
[fpc.cfg.tar.gz](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/9680114/fpc.cfg.tar.gz)
[fppkg.cfg.tar.gz](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/9680115/fppkg.cfg.tar.gz)
  lazfpc-stable
error message :  
lazarus.pp(54,3) Fatal: Cannot find clocale used by Lazarus. Make sure all ppu files of a package are in its output directory. ppu in wrong directory=/home/steve/lazfpc-stable/fpc/units/x86_64-linux/rtl-extra/clocale.ppu..

**Comment by steveswwei** [comment]
Thank you! Don, 
I picked to install both fixed version of fpc (3.2.3-693-g2f8aac770c) and lazarus ( v 2.2.5)
and the lazarus ide can be re-built successfully now.

Maybe I misunderstood the option guideline for choosing fpc and lazarus version.
Thanks again!
Please keep up the good work!

**Comment by LongDirtyAnimAlf** [comment]
Thank you.
