### ISSUE TITLE
Installer requires Big Sur on 64bit Mac

### ISSUE THREAD

**Issue by TommySlokky** [LongDirtyAnimAlf/fpcupdeluxe#539]
I have an old Mac 2012 Pro (upgraded to 16GB memory so OK) and latest MacOS it can run is Catalina.

I can see all installers require Bir Sur. Any chance of doing so older Macs can use fpcupdeluxe?

**Comment by TommySlokky** [comment]
It seems V2.2.0e will run on Catalina but just about any newer will not. I understand time moves on, but still, unless strictly necessary it would be nice to have as much compability as possible.

**Comment by TommySlokky** [comment]
I can try make a screenshot. But the only information I get is macOS stating the executable requires Mac OS 11. 

info.plist looks OK although I am not expert - must be something FPC compiler sets... hmm maybe ask in Lazarus forum

Found thus
My guess is that it is some setting in the executable/metadata (that file that accompanies

I will try research

**Comment by LongDirtyAnimAlf** [comment]
I have tried to make a legacy fpcupdeluxe.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/fixes/fpcupdeluxe-x86_64-darwin-cocoa-legacy.zip
Please test.

**Comment by TommySlokky** [comment]
First saw this now.  Seems link no longer works, but I will be happy to try run it

**Comment by LongDirtyAnimAlf** [comment]
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/v2.2.0n/fpcupdeluxe-x86_64-darwin-cocoa-legacy.zip

**Comment by TommySlokky** [comment]
I just tried it. Sorry for the delay. Well. I do not get the same error. It launches. But crashes with an access violation. But that does mean it runs.

**Comment by LongDirtyAnimAlf** [comment]
Could the access violation be caused by the fact that you run from the Downloads folder ?
Would be good to solve this issue also !

**Comment by TommySlokky** [comment]
You are correct. Access violation disappears when not being run in downloads section. Great. Your cocoa legacy build solves all issues then :)
