### ISSUE TITLE
cannot install FPC 3.2 fixes on macOS 10.10 x64

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#544]
[fp.log](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/10146185/fp.log)

Make shows error about unsupported date format.

**Comment by Alexey-T** [comment]
```
Mac-Admin:~ admin$ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

**Comment by LongDirtyAnimAlf** [comment]
How is it possible that make is an i386 version ?

**Comment by Alexey-T** [comment]
It is clean OSX version, such  Make exists there.
BTW, OSX 10.11 have the same Make version.
It is major problem, coz I cannot upgrade Make on this Mac! why? Brew cannot be installed here (tells that OSX is very old)

**Comment by Alexey-T** [comment]
Can you help to avoid this error or it is FPC's makefile?

![Screenshot from 2022-12-03 14-30-50](https://user-images.githubusercontent.com/4154978/205438830-73fc29e0-6a9f-4aae-b347-cd1d8afe2d2f.png)

**Comment by LongDirtyAnimAlf** [comment]
Fpcupdeluxe cannot solve this.
New version will try to suppress this message.
Closing.
