### ISSUE TITLE
can not install fpcupdeluxe-aarch64-win64.exe

### ISSUE THREAD

**Issue by pityulin** [LongDirtyAnimAlf/fpcupdeluxe#547]
I'm trying to install fpcupdeluxe-aarch64-win64.exe on a windows 11 ARM, installed on a MAC M1 (Parallel Desktop). but this file does not run (no errors and messages)

**Comment by pityulin** [comment]
same result windows 10 arm (virtual machine qemu)

**Comment by Hansaplast** [comment]
+1

**Comment by JohnGaver** [comment]
+1

App launch visible in Task Manager intermittently before disappearing without any error messages or other indication of activity.

**Comment by LongDirtyAnimAlf** [comment]
I am looking into this.
However.
This is not easy, due to the fact that the FPC compiler does not yet work 100% on Windows ARM64.
Please be patient ... ;-)

**Comment by JohnGaver** [comment]
Thank you so much for your quick reply!

As an initial matter, a big thank you once again from all of us here at InstallAware Software for all your invaluable work - which has made possible platforms and deployments of not only Lazarus, but also the software we build on it by implication! Without your efforts, InstallAware Multi Platform for macOS on ARM would have been impossible, as there is still no official Lazarus distribution for it:

https://www.installaware.com/installaware-multi-platform.htm￼
Should you find this cross-platform setup compiler useful, please don’t hesitate to let me know and I shall be glad to authorize a top-tier license for you. I feel it is the least we could do to thank you for all your hard work and tireless efforts!

Furthermore, if there is any direct assistance/testing/anything else we may provide to help you resolve this issue, please don’t hesitate to let us know. Maybe you are not aware of it already, but the latest versions of FPCUP also don’t work for macOS on ARM, so we are using a manually backed up older version.

J Gaver

**Comment by LongDirtyAnimAlf** [comment]
@JohnGaver
Thanks for this info ! I will continue naturally ... ;-)
`Maybe you are not aware of it already, but the latest versions of FPCUP also don’t work for macOS on ARM, so we are using a manually backed up older version`
No, I did not know this. And this issue should be solved.
Would you mind opening a separate issue about this, with detailed info, so I can start bug-hunting !
Thanks.

**Comment by JohnGaver** [comment]
Sorry for the delay.

Just took care of this for you as well.

Happy to provide remote access to a device should you need it!

**Comment by LongDirtyAnimAlf** [comment]
@JohnGaver 
Yes, please give me access. It would make debugging easier I guess.
Thanks.

**Comment by JohnGaver** [comment]
Sure! Please hit me up at msintle at eyecloud dot commie (changed some obvious terms to avoid spam) so I can email you your login details directly. Thanks!

**Comment by Hansaplast** [comment]
Just being curious - is any progress make with this? (trying to be patient haha)
Would love to try Lazarus on Windows running on an AARCH64 machine.

**Comment by LongDirtyAnimAlf** [comment]
No significant progress yet. Just finished arm64 for OSX.
Will dive into arm64 for Windows again.
(the problem to solve for arm64/win: [stack] unwinding)

**Comment by Hansaplast** [comment]
No hurry, take your time! 😊

**Comment by LongDirtyAnimAlf** [comment]
Closing.
I am not able to solve this FPC problem.
We have to wait for the FPC devs to solve this.

**Comment by Hansaplast** [comment]
It may be a good idea to remove **fpcupdeluxe-aarch64-win64.exe** from your releases.

The latest 2.2.20q version silently fails as well (tested it just before you closed this issue).
As mentioned by yourself, this is an issue that cannot be resolved by yourself and we will have to wait for the FPC devs to fix this. 😊
