### ISSUE TITLE
ARM64 Builds of FPCUPDELUXE Fail on macOS

### ISSUE THREAD

**Issue by JohnGaver** [LongDirtyAnimAlf/fpcupdeluxe#549]
The app won't launch despite authorizing manually via GateKeeper et. al.

Previous builds work fine.

<img width="1280" alt="Screenshot 2023-01-16 at 13 56 29" src="https://user-images.githubusercontent.com/122038689/212771403-ad50e715-e799-4549-9a15-8e4408cedee4.png">

No further extended information seems to be available.

**Comment by LongDirtyAnimAlf** [comment]
Do you know which previous build did work (version) ?
Thanks.

**Comment by JohnGaver** [comment]
I don’t know the exact version but I do have the binary file for it still, saved from a backup! Would that help? Happy to put it inside the VM somewhere.

**Comment by LongDirtyAnimAlf** [comment]
No problem. Got the error. Its the linker.
The remote has already a working up-version.

**Comment by LongDirtyAnimAlf** [comment]
@JohnGaver 
Would you mind enabling the remote once again ?
I have now cross-compiled the Mac-binary from Windows with a new linker.
And would like to test if all is ok.
Thanks !

**Comment by LongDirtyAnimAlf** [comment]
Should be resolved.
