### ISSUE TITLE
Error linking fpmake.pp when building fpc 3.2.2 - Manjaro Linux AARCH64 SBC

### ISSUE THREAD

**Issue by HochMartinez** [LongDirtyAnimAlf/fpcupdeluxe#550]
Hi,

I'm trying to install fpc 3.2.2 with fpcupdeluxe in a AARCH64 SBC with Manjaro.

I get the following errors when linking fpmake.pp:
_lib_csu_init and not defined.
_libc_csu_fini not defined.

I append a screenshot below.

Any suggestions on how to fix this?

Thank you and keep up the good work! :)

![error_fpcupdeluxe_2](https://user-images.githubusercontent.com/57639310/214616727-0be392e0-b661-45ab-be14-f0f3dea5ad3f.jpg)

**Comment by elmarfaber** [comment]
Hello,

I get the same error on Armbian 22.11, stable release. Is there a chance to solve this error?

**Comment by LongDirtyAnimAlf** [comment]
Sure !
You can only use FPC trunk. The OS of the newest linux does not have these functions anymore. Trunk has been adapted to handle these changes.

**Comment by elmarfaber** [comment]
Thank you for yure help,
the fpc trunk compiles without errors but the lazarus has an error when I try to open the tools otions menu. The error is in all versions of lazarus. I know it an problem from lazarus but so I couldn't use fcpupdeluxe to get an running version of lazarus.
This is a pity :-( that I could not use fcpupdeluxe for the new linux versions...

**Comment by LongDirtyAnimAlf** [comment]
Closing. Seems to be an issue not related to fpcupdeluxe.
