### ISSUE TITLE
button title don't fit

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#553]
OS Ubuntu 20.04 gtk2.
deluxe 2.2.0k.

btn "Install cross-compiler" title/caption don't fit

![Screenshot from 2023-02-17 21-48-33](https://user-images.githubusercontent.com/4154978/219758576-0e96f293-6336-474e-9203-132ae5109f94.png)

**Comment by LongDirtyAnimAlf** [comment]
Should be resolved by latest pre-release.
