### ISSUE TITLE
please add two new modules

### ISSUE THREAD

**Issue by JanuszChmiel** [LongDirtyAnimAlf/fpcupdeluxe#556]
Dear elite FPCUP Deluxe programmers,
I would like to kindly suggest if you could add The following two packages.
Pandroid package for Windows and Pandroid package for Linux.
It is necessary to emphasyze The fact, that It is The same package but one work only from Windows and second work only from Linux.
Here are github links to those packages.
Windows Pandroid version
https://github.com/zeljkoc/PandroidPackage
Linux Pandroid version
https://github.com/zeljkoc/pandroid
Pandroid allow to create Android apps by also using Android APi Pascal header API files. So developer can use various Android API functions calls.
Even visually impaired programmers with no sight at all can produce apps with no need to specify object position values for every GUI element. 
Rapid applications development is not supported.
But advanced programmers could even extend this package to do that.
Thank you if you will add this package as A module to The modules FPCUP deluxe Tab.

**Comment by LongDirtyAnimAlf** [comment]
Thanks for your request.
I have been looking into this. But I am unsure on how to proceed.
You have to give me more info about how to integrate this into fpcup.
To be clear.
Fcpupdeluxe installs FPC and Lazarus.
Now I want to install pandroid and PandroidPackage into this install.
How would I do this ?
If you give me the detailed step, I will try to add this into fpcup.
Thanks.

**Comment by LongDirtyAnimAlf** [comment]
Closing due to no feedback.
