### ISSUE TITLE
ppc1 not linked/compiled correctly on musl (Alpine Linux)

### ISSUE THREAD

**Issue by Snify89** [LongDirtyAnimAlf/fpcupdeluxe#557]
I get the following error when trying to install fpc compiler and lazarus in alpine linux:

```
/usr/bin/make /config/fpcupdeluxe/fpcsrc/rtl/units/x86_64-linux
as --64 -o /config/fpcupdeluxe/fpcsrc/rtl/units/x86_64-linux/gprt0.o x86_64/gprt0.as
as --64 -o /config/fpcupdeluxe/fpcsrc/rtl/units/x86_64-linux/abitag.o x86_64/abitag.as
/config/fpcupdeluxe/fpcsrc/compiler/ppc1 -Ur -Ur -Xs -O2 -n -Fi../inc -Fi../x86_64 -Fi../unix -Fix86_64 -FE. -FU/config/fpcupdeluxe/fpcsrc/rtl/units/x86_64-linux -Cg -FL/lib/ld-musl-x86_64.so.1 -Sg -vw-n-h-l-d-u-t-p-c- -dx86_64 -dRELEASE  -Us -Sg system.pp
make[7]: *** [Makefile:3848: system.ppu] Segmentation fault
make[6]: *** [Makefile:2037: linux_all] Error 2
make[5]: *** [Makefile:4470: rtl] Error 2
make[4]: *** [Makefile:4330: next] Error 2
make[3]: *** [Makefile:4339: ppc2] Error 2
make[2]: *** [Makefile:4347: cycle] Error 2
make[1]: *** [Makefile:2800: compiler_cycle] Error 2
make: *** [Makefile:2832: build-stamp.x86_64-linux] Error 2

fpcupdeluxe: ERROR: FPC Native Installer (BuildModule: FPC): Error running /usr/bin/make for FPC failed with exit code 512
. Details: .


ERROR: Fpcupdeluxe fatal error !
Sequencer (FPC): Failure running fpcupdeluxe: error executing sequence FPC
Sequencer (Default): Failure running fpcupdeluxe: error executing sequence Default
```

I installed the following packages to make it work this far.

`apk update && apk upgrade && apk add --no-cache build-base make binutils gdb subversion zip unzip libx11-dev gdk-pixbuf-dev gdk-pixbuf-xlib-dev gtk+ pango-dev gdb gtk+2.0-dev git gcompat && ln -s /lib/ld-musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2`

Running ppc1 just standalone gives me a segmentation fault

Any ideas?

**Comment by LongDirtyAnimAlf** [comment]
I guess the bootstrapper was too old.
I have added new and updated bootstrapper for Alpine.
Please delete the ppcx64 from the bootstrap-directory and run fpcupdeluxe again.
It will download a better one (I hope).

**Comment by LongDirtyAnimAlf** [comment]
![Alpine](https://user-images.githubusercontent.com/10783972/223480132-eca60894-f117-4b32-b42a-3f64cb1e24e3.png)

**Comment by LongDirtyAnimAlf** [comment]
Closing. No feedback.
