### ISSUE TITLE
Error installing Lazarus on x86_64-darwin: "Can't find unit DB used by fcllaz"

### ISSUE THREAD

**Issue by seky16** [LongDirtyAnimAlf/fpcupdeluxe#559]
Tried installing fpc+lazarus for the first time on macOS 11.2 with fpcupdeluxe, but building Lazarus fails with this error:

```
/Users/sekaco/fpcupdeluxe/lazarus/packager/registration/fcllaz.pas(11,3) Fatal: (10022) Can't find unit DB used by fcllaz
Fatal: (1018) Compilation aborted
Error: /Users/sekaco/fpcupdeluxe/fpc/bin/x86_64-darwin/ppcx64 returned an error exitcode
fpcupdeluxe: ERROR: Lazarus Native Installer (BuildModuleCustom: Lazbuild): make returned exit status #512.
```

Versions I`m trying to build are fpc 3.2.0 and Lazarus 2.0.10. But I had same error with other Lazarus versions as well (2.2.0 and stable).

Entire log (clean install) attached below:
[fpcupdeluxe.log](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/10897784/fpcupdeluxe.log)

**Comment by LongDirtyAnimAlf** [comment]
Correct.
Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/v2.2.0op/fpcupdeluxe-x86_64-darwin-cocoa.zip

**Comment by seky16** [comment]
I think I got further now but now I got a different error:

```
/Users/sekaco/fpcupdeluxe/lazarus/ide/lazarus.pp(54,3) Fatal: (10022) Can't find unit clocale used by Lazarus
Fatal: (1018) Compilation aborted
Error: /Users/sekaco/fpcupdeluxe/fpc/bin/x86_64-darwin/ppcx64 returned an error exitcode
make: *** [useride] Error 2
Error: (lazarus) Build IDE: stopped with exit code 2
Error: (lazarus) Building IDE: Building IDE failed.

fpcupdeluxe: ERROR: Universal Installer (ConfigModule: suggestedpackages): Failure trying to rebuild Lazarus.
```

entire log below:
[fpcupdeluxe2.log](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/10909647/fpcupdeluxe2.log)

**Comment by LongDirtyAnimAlf** [comment]
My bad.
Please test new binary:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/v2.2.0op/fpcupdeluxe-x86_64-darwin-cocoa.zip

**Comment by seky16** [comment]
Works now, thank you!

**Comment by jinshaopu** [comment]
@LongDirtyAnimAlf    @WIN11  GET  same error
