### ISSUE TITLE
Bad revision history since v2.2.0.o

### ISSUE THREAD

**Issue by totyaxy** [LongDirtyAnimAlf/fpcupdeluxe#560]
https://forum.lazarus.freepascal.org/index.php/topic,34645.msg473819.html#msg473819

https://ibb.co/svxxcDy

I can't say much more than what I wrote on the forum. FPC: fixed, Lazarus 2.3.0 branch
What can I write that will help?

Welcome @ FPCUPdeluxe.
FPCUPdeluxe V2.2.0o for x86_64-win64-win32
Running on Win64-10.0.19045
Build with: FPC 3.2.2 on Win11 x86_64
CPU cores used: 4
Available physical memory: 8190 MB
Current install directory: C:\lazarus
Got settings from install directory.
Please wait. Checking for updates.
No updates found.

**Comment by totyaxy** [comment]
https://ibb.co/khT7k1q

**Comment by LongDirtyAnimAlf** [comment]
This one should be ok I hope.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/v2.2.0o/fpcupdeluxe-x86_64-win64.exe

**Comment by LongDirtyAnimAlf** [comment]
Revision is something from the past, when SVN was still used.
Now only (GIT) hashes are used.
Anyhow.
I will retract the current release 2.2.0o.
And publish version 2.2.0p that has some more fixes besides this one.
Thanks for testing.

**Comment by totyaxy** [comment]
Thank you too, but shouldn't I test it before release to make sure the "hash" will be good?

**Comment by LongDirtyAnimAlf** [comment]
Naturally, you are welcome to test.
What do you need for testing ?

**Comment by totyaxy** [comment]
I only wrote with the help of a translator that before you release the "p" version, I would like to see if the hash (formerly: revision) display was good or not.

**Comment by LongDirtyAnimAlf** [comment]
Fix implemented in release.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/2.2.0p
Closing.

**Comment by totyaxy** [comment]
https://ibb.co/2SNFpdr
