### ISSUE TITLE
Win64 CrossLibsLinuxx64 v.1.4: cross\bin\x86_64-linux\x86_64-linux-ld.exe: cannot find -lrt: No such file or directory

### ISSUE THREAD

**Issue by jonyrh** [LongDirtyAnimAlf/fpcupdeluxe#561]
Hello!

Using Lazarus 2.2.4 and 2.2.6, FPC 3.2.2, CrossLibsLinuxx64 v.1.4

**Error cross-compile from Win64:**
CrossLibsLinuxx64 v.1.4: cross\bin\x86_64-linux\x86_64-linux-ld.exe: cannot find -lrt: No such file or directory

**Fix:**
copy `cross\lib\x86_64-linux\librt.so.1` to `cross\lib\x86_64-linux\librt.so`

**Comment by LongDirtyAnimAlf** [comment]
Solved.
New libs on the same location.
Thanks for reporting.
