### ISSUE TITLE
Bad revision history v2.2.0.o - v2.2.0.p

### ISSUE THREAD

**Issue by totyaxy** [LongDirtyAnimAlf/fpcupdeluxe#562]
https://ibb.co/2SNFpdr

_Originally posted by @totyaxy in https://github.com/LongDirtyAnimAlf/fpcupdeluxe/issues/560#issuecomment-1465020136_

**Comment by totyaxy** [comment]
It's fine with the "N" version, you just have to exit and return to the program.

**Comment by LongDirtyAnimAlf** [comment]
As mentioned in the previous issue, this is how its meant to be.
Fpcupdeluxe now uses the hashes as used by the FPC and Lazarus developers.
This is different from older versions of fpcupdeluxe.
Please explain to me the pro's and con's of the old and new version strings.
Some changes might be needed and added.
Thanks.
