### ISSUE TITLE
Cannot install "pico" from fpcupdeluxe 2.2.0qp on linux (debian 10)

### ISSUE THREAD

**Issue by snfever** [LongDirtyAnimAlf/fpcupdeluxe#566]
Hello !
I want to make applications for my _RPi Pico W_ with lazarus (for linux x86_64) , so I follwed this tutorial :
How to program for RPi Pico with lazarus (https://wiki.freepascal.org/ARM_Embedded_Tutorial_-_Installing_Lazarus_and_Free_Pascal)

but when I click on the "Pico" button in fpcupdeluxe, there is an error on the command screen :

beginning of the command screen (maybe this is important) :
`warning: redirection vers https://gitlab.com/michael-ring/freepascal-sources.git/`
`remote: warning: unable to find all commit-graph files`
then... :
`fpcupdeluxe: ERROR: Lazarus Native Installer (GetModule: Lazarus): Could not get version of Lazarus sources. Expect severe errors.`
followed by :
`fpcupdeluxe: info: Lazarus Native Installer (GetModule: Lazarus): Lazarus is at revision/hash: FRET_UNKNOWN_REVISION.`
`fpcupdeluxe: info: Lazarus Native Installer (GetModule: Lazarus): No updates for Lazarus found.`
`fpcupdeluxe: ERROR: Lazarus Native Installer (BuildModule: Lazbuild): /home/moi/freepascal_pico/lazarus/Makefile not found. Severe error. Should not happen. Aborting build Lazbuild.`
and :
`ERROR: Fpcupdeluxe fatal error !`
`Sequencer (UserIDE): Failure running fpcupdeluxe: error executing sequence UserIDE`
`Sequencer (Lazarus): Failure running fpcupdeluxe: error executing sequence Lazarus`
`Sequencer (Default): Failure running fpcupdeluxe: error executing sequence Default`

Has anyone ever had this error ? this is the last fpcupdeluxe version (2.2.0qp)

**Comment by LongDirtyAnimAlf** [comment]
Should be solved by newest release.
Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.2.0q

**Comment by snfever** [comment]
It's working with the new version,
Thanks !
