### ISSUE TITLE
Can't build lazarus with fpc 3.2.2 on openSUSE Leap 15.4

### ISSUE THREAD

**Issue by cgsousa** [LongDirtyAnimAlf/fpcupdeluxe#570]
When I try to build , I get the following error:

Checking dev-libs for gtk2 LCLWidgetType.
fpcupdeluxe: ERROR: Missing library:
fpcupdeluxe: ERROR: libgdk_pixbuf-2.0.so
fpcupdeluxe: ERROR: libpango-1.0.so
fpcupdeluxe: ERROR: libcairo.so
fpcupdeluxe: ERROR: libgdk-x11-2.0.so
fpcupdeluxe: WARNING: You need to install at least the libraries to get libX11.so and libgdk_pixbuf-2.0.so and libpango-1.0.so and libgdk-x11-2.0.so, but also make and binutils to build Lazarus !!

All these lib's are installed on the system!

note:
FPCUPdeluxe V2.2.0q for x86_64-linux running on openSUSE Leap 15.4
Build with: FPC 3.2.2 on Win11 x86_64

**Comment by LongDirtyAnimAlf** [comment]
Use this script to install all needed dependencies.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/blob/master/installscripts/suse_x86-64.sh

**Comment by cgsousa** [comment]
Thanks @LongDirtyAnimAlf , it worked. There really were some items missing!
It would be interesting to update the wiki!
