### ISSUE TITLE
How to crosscompile armhf from aarch64 linux?

### ISSUE THREAD

**Issue by afuriza** [LongDirtyAnimAlf/fpcupdeluxe#572]
I've tried to install cross compiler from aarch64 but have no success because there's no crossbins provided by default on FPCUpDeluxe Github...
![image](https://user-images.githubusercontent.com/17453269/233232730-0c53b13d-092d-49c8-9703-afdd5947c336.png)

So, I install all binutils, cross-build tools, including gtk2.0 and gtk3.0 dev for armhf libraries, I successfully run fpcupdeluxe-arm-linux 32bit arm but still can't compile the FPC with error: `unrecognized option -meabi=5`
![image](https://user-images.githubusercontent.com/17453269/233232478-ad164e7c-7a0f-4d6a-832d-46a6c041f3c3.png)

Maybe someone can give an advice to build FPC & Laz for arm from aarch64?
Thanks~

**Comment by LongDirtyAnimAlf** [comment]
I have added binutils for armhf.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/linuxaarch64crossbins_v1.0/CrossBinsLinuxARM.zip
Please test.

**Comment by afuriza** [comment]
Thank you for the good work! Now I can compile the cross compiler for the armhf.
![image](https://user-images.githubusercontent.com/17453269/233483436-6e351942-1452-4939-b27a-23748555ecaf.png)
GTK2 seems normal and I can run the app after installing `sudo apt install libgtk2.0-dev:armhf`
![image](https://user-images.githubusercontent.com/17453269/233485491-928c148f-6ea1-4638-b8cb-215e20dcce8d.png)

But I have a problem with lgtk-3, I've installed that by `sudo apt install libgtk-3-dev:armhf` like I installed gtk2
![image](https://user-images.githubusercontent.com/17453269/233483859-16cc48f1-7fdf-4ff6-adca-974ae75efd29.png)

**Comment by LongDirtyAnimAlf** [comment]
You are on a aarch64 system. To compile to a arm system, you needs appropriate libs. Fpcupdeluxe has auto -downloaded and -installed a set of libs for an arm system. These libs, however, do not include libs for gtk3. So, you need to copy the appropriate libs from your arm system to the cross-libs directory on your aarch64 system, so the linker on your aarch64 system can find them and use them while linking.

**Comment by afuriza** [comment]
I archive my copied file I put to `<fpcup target dir>\cross\lib\aarch64-linux` here: [](https://drive.google.com/file/d/1vM_Vot31NmWqZnNkaHUjXGHXswQLH4NB/view?usp=sharing)

I also tried to cross-compile that from Windows, seems only GTK3 that doesn't work for cross-compile to ARM or AArch64, I'm using Ubuntu 22.04 ARM. But when compiling directly from AArch64 to AArch64 is no problem.

I also do the same with X86_64 cross-compiling from Windows X86_64 to Linux X86_64, GTK3 works fine. 

I think something doesn't looks right in ARM and GTK3 when cross compiling.

**Comment by LongDirtyAnimAlf** [comment]
Please note.
This is no longer a fpcupdeluxe issue.
The error when linking will show you exactly which libraries you need. Please use the correct filename for these libraries.

**Comment by afuriza** [comment]
> Please use the correct filename for these libraries.
No, they're all correct.

**Comment by rcla** [comment]
@afuriza 
Reading the lazarus README, one finds:
[Welcome Lazarus](https://gitlab.com/freepascal.org/lazarus/lazarus/-/blob/main/README.md)

The LCL currently supports:

- Linux/FreeBSD (GTK2, Qt4, Qt5 and Qt6)
- all flavors of Windows (even WinCE)
- macOS (Cocoa, Carbon, GTK2, Qt4, Qt5, Qt6)

There is an experimental support for:

- GTK3
- Solaris


And in [GTK3 Interface](https://wiki.freepascal.org/GTK3_Interface): Currently it's in alpha status

That may be the reason why gtk3 libraries are not included in the cross-compile. However, as @LongDirtyAnimAlf said, you can manually include the ones you need from your OS. But it's a tedious job, going through each library and their respective dependencies.

> Last Edit: Seems this is Ubuntu ARM problem (I'm not sure actually, is this FPC bug or Ubuntu bug), the CEF4Delphi seems also have this issue on Ubuntu ARM when trying to load libcef.so. 

This has nothing to do with that other issue.

**Comment by afuriza** [comment]
> However, as @LongDirtyAnimAlf said, you can manually include the ones you need from your OS.

As I said, do you read that properly? I already done that copying each file. Do you even open the link I provided? That's all file required, same count, same library name. It work on X86_64 but not on ARM and AArch64. Alpha status doesn't matter because it works on direct compile but not cross compile on ARM  **EVEN THOUGH I COPIED THE FILES LIKE I DO IN X86_64.**

**Comment by rcla** [comment]
Respectfully, it does matter that the LCL gtk3 widget type is experimental and in alpha stage, since that it means that there are still a lot of things that don't work, regardless of the type of x86 architecture. arm or arm64.

And it has nothing to do with fpcupdeluxe.

**Comment by afuriza** [comment]
@rcla You seem don't read and won't read, no matter how long I typed, I'll close this.
