### ISSUE TITLE
Cannot install OpenBSD i386 cross (x64 cross was installed before)

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#576]
[up.txt](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/11359321/up.txt) <-- Full log

```
make[1]: *** [Makefile:2500: openbsd_all] Error 2
make: *** [Makefile:2592: rtl_all] Error 2
/usr/bin/make -C rtl all
/usr/bin/make -C openbsd all
/home/user/fpcupdeluxe/fpcupdeluxe32/cross/bin/i386-openbsd/i386-openbsd-as -o /home/user/fpcupdeluxe/fpcupdeluxe32/fpcsrc/rtl/units/i386-openbsd/prt0.o i386/prt0.as
fpcupdeluxe: ERROR: FPC Cross Installer (BuildModuleCustom: FPC): Running cross compiler fpc /usr/bin/make for i386-openbsd failed with an error code.


ERROR: Fpcupdeluxe fatal error !
Sequencer (FPCCleanBuildOnly): Failure running fpcupdeluxe: error executing sequence FPCCleanBuildOnly
Sequencer (Only): Failure running fpcupdeluxe: error executing sequence Only
Building cross-tools failed. Aborting.
```

**Comment by LongDirtyAnimAlf** [comment]
See:
https://forum.lazarus.freepascal.org/index.php/topic,58888

**Comment by Alexey-T** [comment]
I see that forum topic is about ` version `GLIBC_2.34' not found (required by ./my_program)` but here we have different error. What did i miss?

**Comment by Alexey-T** [comment]
How can I solve it, please give a hint?

**Comment by LongDirtyAnimAlf** [comment]
You are using binary utilities that have been prepared (compiled) by me on a fairly new Linux system, with a fairly new glibc.
Your system has an older glibc. It would be good for me to know what version you are using.
Do: ldd --version
Do: uname -a
And show me the output.
I might be able to compile new binaries that work on your system.
(I just did the same for another user that used the Darwin binary tools)

**Comment by Alexey-T** [comment]
From my Ubuntu 20.4:

```
user@PC:~$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
user@PC:~$ uname -a
Linux PC 5.4.0-148-generic #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
user@PC:~$ 
```

**Comment by LongDirtyAnimAlf** [comment]
Thanks. This is an old Ubuntu (20.04). Will see what I can do.

**Comment by LongDirtyAnimAlf** [comment]
Will release new binaries that solve next week.

**Comment by Alexey-T** [comment]
Great!

**Comment by LongDirtyAnimAlf** [comment]
Would you mind testing with the latest release and let this latest release install the cross-binaries ?
Thanks.

**Comment by Alexey-T** [comment]
I posted new report about openbsd. Still cannot install it
