### ISSUE TITLE
Please support NetBSD i386 cross, for low-spec PCs

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#577]
On attempt to install cross on Linux x64 (Ubuntu 20.4), I got `No valid CPU / OS crosscompiler found.`.

**Comment by LongDirtyAnimAlf** [comment]
Working on this issue. Will release new binaries and tools that solve this issue next week.

**Comment by Alexey-T** [comment]
Thank you in advance!

**Comment by LongDirtyAnimAlf** [comment]
Implemented in release.

**Comment by Alexey-T** [comment]
Great. Thank you.
