### ISSUE TITLE
Having installing fpcupdeluxe-x86_64-linux (v2.2.0r=April 22, 2023) on Fedora x64 (version 38) VM

### ISSUE THREAD

**Issue by nitinca** [LongDirtyAnimAlf/fpcupdeluxe#578]
Here's log, Any ideas?

Going to install/update FPC and Lazarus with given options.
FPCUP(deluxe) is starting up.

FPCupdeluxe basedir:       /home/askme/fpcupdeluxe
Bootstrap dir:             /home/askme/fpcupdeluxe/fpcbootstrap

FPC URL:                   https://gitlab.com/freepascal.org/fpc/source
FPC source directory:      /home/askme/fpcupdeluxe/fpcsrc
FPC install directory:     /home/askme/fpcupdeluxe/fpc
FPC options:               

Lazarus URL:               https://gitlab.com/freepascal.org/lazarus/lazarus
Lazarus source directory:  /home/askme/fpcupdeluxe/lazarus
Lazarus install directory: /home/askme/fpcupdeluxe/lazarus
Lazarus options:           -g -gl -O1

Please stand back and enjoy !

4-5-23 10:14:18: fpcupdeluxe: V468 (20230422) started.
FPCUPdeluxe V2.2.0r for x86_64-linux running on Fedora Linux
Build with: FPC 3.2.2 on Win11 x86_64

Log file "fpcupdeluxe-x86_64-linux_log.txt" is attached here
[fpcupdeluxe-x86_64-linux_log.txt](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/11399946/fpcupdeluxe-x86_64-linux_log.txt)

**Comment by LongDirtyAnimAlf** [comment]
Very strange error ! I have no clue about its cause.
Enough diskspace ? Virus protection ?

**Comment by LongDirtyAnimAlf** [comment]
As I do not know how to solve this, I am closing this issue.
Please re-open when you have any ideas about this.
