### ISSUE TITLE
on windows system,after rebuild fpc with use unicode checked .lazarus lazutils can't find db.ppu

### ISSUE THREAD

**Issue by jinshaopu** [LongDirtyAnimAlf/fpcupdeluxe#580]
on windows system
after rebuild fpc with use unicode checked .lazarus rebuild lazutils can't find db.ppu
on linux 
it can execute correct

**Comment by jinshaopu** [comment]
Sorry！
FPCUPdeluxe V2.2.0r for x86_64-win64-win32
Running on Win64-10.0.22000
Build with: FPC 3.2.2 on Win11 x86_64
CPU cores used: 16
Available physical memory: 16113 MB
![image](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/14891482/be43847c-630e-4ab4-9ab7-0cbcd2a59a2d)
with "build FPC unicode" checked,build FPC with FPCUPdeluxe  
Lazarus build with Profile Normal IDE

**Comment by LongDirtyAnimAlf** [comment]
Allright. This is more or less my bad.
FPC unicode is a feature of FPC that is not yet ready for use.
By mistake, I have enabled it. And I will disable it for now (with a new release of up).
It will be re-enabled when this feature is ready.
Sorry for the inconvenience.
