### ISSUE TITLE
Cannot install Synapse under Mac M1 12.6.5

### ISSUE THREAD

**Issue by qindj** [LongDirtyAnimAlf/fpcupdeluxe#585]
please see  attached logs, i didn't see any detail error message except a "."

[fpcup-synapse.log](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/11549796/fpcup-synapse.log)

**Comment by LongDirtyAnimAlf** [comment]
Would you mind checking that the sources are downloaded correct (available) inside "/Applications/fpcupdeluxe/ccr/synapse" ?
This might be a permission problem.

**Comment by qindj** [comment]
yes, source code is correct, maybe something wrong because ARM(MAC m1)?

<img width="830" alt="image" src="https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/1707762/6b0e198a-1467-4730-a9ba-0ae582a16e98">

**Comment by LongDirtyAnimAlf** [comment]
Sorry for my long silence, but I do not know what causes this error.
Unfortunately, I do not have a Mac system myself. So, I am not able to reproduce.
I have only one advice/question.
Does the same happen when you install FPC and Lazarus in a directory somewhere inside your home directory ?
(I am not very experienced in a system wide install through fpcupdeluxe: I only use the home directory as target)

**Comment by qindj** [comment]
@LongDirtyAnimAlf Thank you for your suggestion, everything works fine when I set install dir to $home/fpcupdeluxe

I'll try to fix it when i have enough time
