### ISSUE TITLE
xtensa-esp32-elf-as.exe: unrecognized option `-EL'

### ISSUE THREAD

**Issue by lgadina** [LongDirtyAnimAlf/fpcupdeluxe#586]
The cross-compiler for esp32 is not installed
`C:/Work/fpc5/fpc/bin/x86_64-win64/ppcrossxtensa.exe -Cplx6 -Ur -Tfreertos -Pxtensa -XPxtensa-esp32-elf- -Ur -Xs -O2 -n -Fi../inc -Fi../xtensa -FDC:\Users\adm\.espressif\tools\xtensa-esp32-elf\esp-2020r3-8.4.0\xtensa-esp32-elf\bin -FE. -FUC:/Work/fpc5/fpcsrc/rtl/units/xtensa-freertos -vw-n-h-l-d-u-t-p-c- -dxtensa -dRELEASE -Cfhard -FDC:\Users\adm\.espressif\tools\xtensa-esp32-elf\esp-2020r3-8.4.0\xtensa-esp32-elf\bin -XPxtensa-esp32-elf- -Wpesp32 -FlC:\Work\fpc5\cross\lib\xtensa-freertos\lx6 -WP4.3.2 -FlC:\Work\fpc5\cross\lib\xtensa-freertos\lx6  -Us -Sg system.pp @system.cfg 
C:\Users\adm\.espressif\tools\xtensa-esp32-elf\esp-2020r3-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-as.exe: unrecognized option `-EL'
system.pp(308) Error: Error while assembling exitcode 1
system.pp(308) Fatal: There were 2 errors compiling module, stopping
Fatal: Compilation aborted
make.exe[1]: *** [freertos_all] Error 2
C:\Work\fpc5\fpcbootstrap\make.exe: *** [rtl_all] Error 2
fpcupdeluxe: ERROR: FPC Cross Installer (BuildModuleCustom: FPC): Running cross compiler fpc C:\Work\fpc5\fpcbootstrap\make.exe for xtensa-freertos failed with an error code.

ERROR: Fpcupdeluxe fatal error !
Sequencer (FPCCleanBuildOnly): Failure running fpcupdeluxe: error executing sequence FPCCleanBuildOnly
Sequencer (Only): Failure running fpcupdeluxe: error executing sequence Only
Building cross-tools failed. Aborting.`

**Comment by ccrause** [comment]
It is because there isn't yet a Windows snapshot, see list of available platform snapshots here: https://github.com/michael-ring/espsdk4fpc/releases/tag/v1.1.0-4

One can package the xtensa bintools and re-use the compiled libraries , but automatically sorting out the python dependencies to run the python tools such as esptool is a bit tricky.

**Comment by LongDirtyAnimAlf** [comment]
Closing. See comment by @ccrause
