### ISSUE TITLE
Fatal: Can't find unit ESP32 used by consoleio

### ISSUE THREAD

**Issue by limuzi2012** [LongDirtyAnimAlf/fpcupdeluxe#589]
从可获的源文件去安装一个交叉编译器.
fpcupdeluxe: FPC cross-builder: Building compiler for freertos-xtensa [CROSSOPT: -Cfhard] {SUBARCH: lx6}.
FPCUP(deluxe) is starting up.

FPCupdeluxe basedir:       G:\fpcupdeluxe
Binutils dir:              G:\fpcupdeluxe\fpcbootstrap
Bootstrap dir:             G:\fpcupdeluxe\fpcbootstrap

FPC URL:                   https://gitlab.com/freepascal.org/fpc/source
FPC source directory:      G:\fpcupdeluxe\fpcsrc
FPC install directory:     G:\fpcupdeluxe\fpc
FPC options:               

Lazarus URL:               https://gitlab.com/freepascal.org/lazarus/lazarus
Lazarus source directory:  G:\fpcupdeluxe\lazarus
Lazarus install directory: G:\fpcupdeluxe\lazarus
Lazarus options:           -g -gl -O1

Please stand back and enjoy !

2023-06-10 09:10:12: fpcupdeluxe: V468 (20230422) started.
FPCUPdeluxe V2.2.0r for i386-win32 running on Win64-10.0.19045
Build with: FPC 3.2.2 on Win11 x86_64

Found valid svn.exe application.
Found valid git.exe application.
Found valid hg.exe application.
fpcupdeluxe: info: FPC Cross Installer (CleanModule: FPC): Looking for crosstools and crosslibs on system. Please wait.
fpcupdeluxe: Ti386-win32_freertos-xtensa: Found correct binary utilities in directory C:\Users\Administrator\.espressif\tools\xtensa-esp32-elf\esp-2021r2-patch2-8.4.0\xtensa-esp32-elf\bin
fpcupdeluxe: Ti386-win32_freertos-xtensa: Found correct library in directory G:\fpcupdeluxe\cross\lib\xtensa-freertos\lx6
fpcupdeluxe: info: FPC Cross Installer (CleanModule: FPC): Skipping cross-compiler clean step: compiler seems to be up to date !!.
fpcupdeluxe: info: FPC Cross Installer (CleanModule: FPC): Running make rtl_distclean twice for target xtensa-freertos.
fpcupdeluxe: Executing: G:\fpcupdeluxe\fpcbootstrap\make.exe FPC=G:\fpcupdeluxe\fpc\bin\i386-win32\ppc386.exe --directory=G:\fpcupdeluxe\fpcsrc FPCMAKE=G:\fpcupdeluxe\fpc\bin\i386-win32\fpcmake.exe PPUMOVE=G:\fpcupdeluxe\fpc\bin\i386-win32\ppumove.exe FPCDIR=G:\fpcupdeluxe\fpcsrc PREFIX=G:\fpcupdeluxe\fpc INSTALL_PREFIX=G:\fpcupdeluxe\fpc CPU_SOURCE=i386 OS_SOURCE=win32 UPXPROG=echo CPU_TARGET=xtensa OS_TARGET=freertos SUBARCH=lx6 rtl_distclean (working dir: G:\fpcupdeluxe\fpcsrc)
G:/fpcupdeluxe/fpcbootstrap/make -C rtl distclean
G:/fpcupdeluxe/fpcbootstrap/make -C freertos cleanall
G:/fpcupdeluxe/fpcbootstrap/make -C freertos distclean
fpcupdeluxe: Executing: G:\fpcupdeluxe\fpcbootstrap\make.exe FPC=G:\fpcupdeluxe\fpc\bin\i386-win32\ppc386.exe --directory=G:\fpcupdeluxe\fpcsrc FPCMAKE=G:\fpcupdeluxe\fpc\bin\i386-win32\fpcmake.exe PPUMOVE=G:\fpcupdeluxe\fpc\bin\i386-win32\ppumove.exe FPCDIR=G:\fpcupdeluxe\fpcsrc PREFIX=G:\fpcupdeluxe\fpc INSTALL_PREFIX=G:\fpcupdeluxe\fpc CPU_SOURCE=i386 OS_SOURCE=win32 UPXPROG=echo CPU_TARGET=xtensa OS_TARGET=freertos SUBARCH=lx6 rtl_distclean (working dir: G:\fpcupdeluxe\fpcsrc)
G:/fpcupdeluxe/fpcbootstrap/make -C rtl distclean
G:/fpcupdeluxe/fpcbootstrap/make -C freertos cleanall
G:/fpcupdeluxe/fpcbootstrap/make -C freertos distclean
fpcupdeluxe: info: FPC Cross Installer (CleanModule: FPC): Removal of stale build files and directories for i386-win32. May take a while.
fpcupdeluxe: info: FPC Cross Installer (BuildModule: FPC): Going to build FPC.
fpcupdeluxe: info: FPC Cross Installer (BuildModule: FPC): xtensa-freertos cross-builder: Detected source version FPC (source): 3.3.1.
fpcupdeluxe: info: FPC xtensa-freertos cross-builder: Using compiler with version: 3.3.1.
fpcupdeluxe: info: FPC Cross Installer (BuildModuleCustom: FPC): Removing fpc.cfg config snippet for target xtensa-freertos.
fpcupdeluxe: info: FPCCrossInstaller (InsertFPCCFGSnippet: fpc.cfg): Inserting snippet in G:\fpcupdeluxe\fpc\bin\i386-win32\fpc.cfg done.
fpcupdeluxe: info: FPC Cross Installer (BuildModuleCustom: FPC): Skipping cross-compiler build step: compiler seems to be up to date !!.
fpcupdeluxe: info: FPC Cross Installer (BuildModuleCustom: FPC): Running make [Rtl] (FPC crosscompiler: xtensa-freertos) with CROSSOPT: -Cfhard -FDC:\Users\Administrator\.espressif\tools\xtensa-esp32-elf\esp-2021r2-patch2-8.4.0\xtensa-esp32-elf\bin -XPxtensa-esp32-elf- -Wpesp32 -FlG:\fpcupdeluxe\cross\lib\xtensa-freertos\lx6 -WP4.3.2 -FlG:\fpcupdeluxe\cross\lib\xtensa-freertos\lx6.
fpcupdeluxe: Executing: G:\fpcupdeluxe\fpcbootstrap\make.exe --directory=G:\fpcupdeluxe\fpcsrc FPCMAKE=G:\fpcupdeluxe\fpc\bin\i386-win32\fpcmake.exe PPUMOVE=G:\fpcupdeluxe\fpc\bin\i386-win32\ppumove.exe PREFIX=G:\fpcupdeluxe\fpc INSTALL_PREFIX=G:\fpcupdeluxe\fpc FPCDIR=G:\fpcupdeluxe\fpcsrc UPXPROG=echo GIT=C:\PROGRA~1\Git\cmd\git.exe CROSSBINDIR=C:\Users\Administrator\.espressif\tools\xtensa-esp32-elf\esp-2021r2-patch2-8.4.0\xtensa-esp32-elf\bin BINUTILSPREFIX=xtensa-esp32-elf- FPCFPMAKE=G:\fpcupdeluxe\fpc\bin\i386-win32\fpc.exe FPC=G:\fpcupdeluxe\fpc\bin\i386-win32\ppcrossxtensa.exe rtl_all CROSSINSTALL=1 CPU_SOURCE=i386 OS_SOURCE=win32 OS_TARGET=freertos CPU_TARGET=xtensa SUBARCH=lx6 NOGDBMI=1 REVSTR=12745-g3770b55ce1 REVINC=force OPT=-vw-n-h-l-d-u-t-p-c- CROSSOPT=-Cfhard -FDC:\Users\Administrator\.espressif\tools\xtensa-esp32-elf\esp-2021r2-patch2-8.4.0\xtensa-esp32-elf\bin -XPxtensa-esp32-elf- -Wpesp32 -FlG:\fpcupdeluxe\cross\lib\xtensa-freertos\lx6 -WP4.3.2 -FlG:\fpcupdeluxe\cross\lib\xtensa-freertos\lx6 (working dir: G:\fpcupdeluxe\fpcsrc)
G:/fpcupdeluxe/fpcbootstrap/make -C rtl all
G:/fpcupdeluxe/fpcbootstrap/make -C freertos all
G:/fpcupdeluxe/fpc/bin/i386-win32/ppcrossxtensa.exe -Cplx6 -Ur -Tfreertos -Pxtensa -XPxtensa-esp32-elf- -Ur -Xs -O2 -n -Fi../inc -Fi../xtensa -FDC:\Users\Administrator\.espressif\tools\xtensa-esp32-elf\esp-2021r2-patch2-8.4.0\xtensa-esp32-elf\bin -FE. -FUG:/fpcupdeluxe/fpcsrc/rtl/units/xtensa-freertos -vw-n-h-l-d-u-t-p-c- -dxtensa -dRELEASE -Cfhard -FDC:\Users\Administrator\.espressif\tools\xtensa-esp32-elf\esp-2021r2-patch2-8.4.0\xtensa-esp32-elf\bin -XPxtensa-esp32-elf- -Wpesp32 -FlG:\fpcupdeluxe\cross\lib\xtensa-freertos\lx6 -WP4.3.2 -FlG:\fpcupdeluxe\cross\lib\xtensa-freertos\lx6  -Us -Sg system.pp @system.cfg 
G:/fpcupdeluxe/fpc/bin/i386-win32/ppcrossxtensa.exe -Cplx6 -Ur -Tfreertos -Pxtensa -XPxtensa-esp32-elf- -Ur -Xs -O2 -n -Fi../inc -Fi../xtensa -FDC:\Users\Administrator\.espressif\tools\xtensa-esp32-elf\esp-2021r2-patch2-8.4.0\xtensa-esp32-elf\bin -FE. -FUG:/fpcupdeluxe/fpcsrc/rtl/units/xtensa-freertos -vw-n-h-l-d-u-t-p-c- -dxtensa -dRELEASE -Cfhard -FDC:\Users\Administrator\.espressif\tools\xtensa-esp32-elf\esp-2021r2-patch2-8.4.0\xtensa-esp32-elf\bin -XPxtensa-esp32-elf- -Wpesp32 -FlG:\fpcupdeluxe\cross\lib\xtensa-freertos\lx6 -WP4.3.2 -FlG:\fpcupdeluxe\cross\lib\xtensa-freertos\lx6 consoleio.pp
Fatal: Can't find unit ESP32 used by consoleio
Fatal: Compilation aborted
make[1]: *** [freertos_all] Error 2
make: *** [rtl_all] Error 2
fpcupdeluxe: ERROR: FPC Cross Installer (BuildModuleCustom: FPC): Running cross compiler fpc G:\fpcupdeluxe\fpcbootstrap\make.exe for xtensa-freertos failed with an error code.

ERROR: Fpcupdeluxe fatal error !
Sequencer (FPCCleanBuildOnly): Failure running fpcupdeluxe: error executing sequence FPCCleanBuildOnly
Sequencer (Only): Failure running fpcupdeluxe: error executing sequence Only
Building cross-tools failed. Aborting.

**Comment by ccrause** [comment]
The cross setup for Windows is not yet supported, see #586 reply https://github.com/LongDirtyAnimAlf/fpcupdeluxe/issues/586#issuecomment-1563448088

**Comment by LongDirtyAnimAlf** [comment]
Closing. See comment by @ccrause
