### ISSUE TITLE
Cross compiling in Linux to aarch64-Darwin: clang: error: invalid Darwin version number: macosx11.0.0

### ISSUE THREAD

**Issue by han-k59** [LongDirtyAnimAlf/fpcupdeluxe#592]
I get this error:

```
fpcupdeluxe: Start of compile error summary.
clang: error: invalid Darwin version number: macosx11.0.0
fpcupdeluxe: Start of compile error summary.
clang: error: invalid version number in '-target arm64-apple-macosx11.0.0'
```

But in the CMD Window it reports:
`   SUCCESS: installation by fpcupdeluxe complete !`

Using Lazbuild I get this

```
/home/h/fpcupdeluxe/lazarus/components/lazutils/laz_avl_tree.pp(95,33) Hint: (5024) Parameter "aNode" not used
/home/h/fpcupdeluxe/lazarus/components/lazutils/laz_avl_tree.pp(98,30) Hint: (5024) Parameter "aNode" not used
clang: error: invalid Darwin version number: macosx11.0.0
clang: error: invalid version number in '-target arm64-apple-macosx11.0.0'
(9001) Assembling (pipe) /home/h/fpcupdeluxe/lazarus/components/lazutils/lib/aarch64-darwin/laz_avl_tree.s
Error: /home/h/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossa64 can't be executed, error message: Failed to execute "/home/h/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossa64", error code: -13
Error: (lazarus) Compile package LazUtils 1.0: stopped with exit code 1
Error: (lazarus) [TLazPackageGraph.CompileRequiredPackages] "Exit code 1"
Error: (lazbuild) Project dependencies of /home/h/astap.fpc/astap_linux_cross_compile_to_Darwin_M1.lpi
```

Not sure if it is the trunk version or something else.  Cross compile to X86_64-Darwin seems to work.

Han

**Comment by han-k59** [comment]
Same problem when selecting Lazarus 3.3.1 and FPC 2.3.0.  Here is the log:
[log.txt](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/11779777/log.txt)

**Comment by han-k59** [comment]
On my old Mac the cross compiling to aarch64 & Darwin works fine using trunk.

Cross compiling under Linux to aarch64 & Darwin works fine using Lazarus & FPC versions from last year. My guess is that the external cross compiler tools are outdated for latest Lazarus and FPC versions?

**Comment by LongDirtyAnimAlf** [comment]
Fpcupdeluxe uses the clang provided by your Linux system.
Normally, clang will support many targets, including arm64-apple-macosx.
You might want to investigate if clang on your systems supports cross-compiling towards arm64-darwin.

**Comment by han-k59** [comment]
I works fine selecting older version of Lazarus. 

The following clang version is installed:
clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

Trying to update I get:
clang is already the newest version (1:10.0-50~exp1).

**Comment by LongDirtyAnimAlf** [comment]
Please tell me the Ubuntu version of the system you get this error ?

**Comment by han-k59** [comment]
Ubuntu 20.04.5 LTS

It is running in a virtual machine. At the moment I have not updated for some time since the update breaks the copy & paste feature of the virtual machine. I could not fix that. 

I could create a new virtual machine with the latest Lubuntu for testing.

**Comment by LongDirtyAnimAlf** [comment]
No need for a new VM.
This problem is hard to fix. I will explain.
The Darwin cross-tools must be build by me on a Linux machine (or VM).
This machine has a certain clang version. And a certain libc version. Due to this, they will only work out-of-the-box an a more or less similar machine.
I have been trying for some time now to build universal tools that will work on all Ubuntu 20 and newer. However, I have yet to succeed.
Your clang it too old for the tools to work. I can only compile the tools with clang 12 or newer.
Ubuntu 20 is old. You might try Ubuntu 22. And report back if you succeed.

**Comment by han-k59** [comment]
I have made a new VM with Lubuntu 23.  I got the correct warning clang not installed. I installed clang and it all worked as desired.

So problem is solved! :)

Would it make sense to check for clang version and warn for a too old clang version?

 
![Untitled](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/46811539/fe0d5e0e-0af3-43a7-ab33-d8825e099068)

**Comment by Alexey-T** [comment]
clang error is fixable.

- install package `clang-12` in package manager
- go to /usr/bin and see all clang* symlinks. `clang` is symlink to clang-10 , and `clang-12` is symlink to clang-12. adjust symlinks so that `clang` points to clang-12.

**Comment by LongDirtyAnimAlf** [comment]
Thanks for the Wiki-entry !
Closing.
