### ISSUE TITLE
Need Lazarus 1.4.x in Ubuntu 22.04

### ISSUE THREAD

**Issue by 99Percent** [LongDirtyAnimAlf/fpcupdeluxe#593]
(also posted in the Lazarus Forum)

I need to recover and upgrade some very old legacy code written in Lazarus 1.4.4

However it seems like Lazarus 1.4 cannot be compiled with the FPC compiler that Ubuntu supplies through apt (>3.2) fpcupdeluxe throws this error:

```
/home/david/fpcupdeluxe/lazarus/components/codetools/codecache.pas(1173,12) Error: (4103) Invalid assignment, procedures return no value[/code]
```

I tried to install the version of FPC that I had running with my legacy code which is 2.6.4 with fpcupdeluxe but it throws a cryptic error 512 (no "details" given):
```/home/david/fpcupdeluxe/fpcsrc/compiler/ppc1 -Ur -Ur -Xs -O2 -n -Fi../inc -Fi../x86_64 -Fi../unix -Fix86_64 -FE. -FU/home/david/fpcupdeluxe/fpcsrc/rtl/units/x86_64-linux -Cg -Sg -vw-n-h-l-d-u-t-p-c- -dx86_64 -dRELEASE -Us -Sg system.pp

fpcupdeluxe: ERROR: FPC Native Installer (BuildModule: FPC): Error running /usr/bin/make for FPC failed with exit code 512
. Details:
```

Apparently fpcupdeluxe can only compile FPC stable 3.2 in ubuntu 22.04

Is this possible to do or will I have to create a VM with Ubuntu 20.04 or 18.04 to be able to recover my old IDE?

**Comment by LongDirtyAnimAlf** [comment]
For newer Ubuntu, only FPC 3.2.0 and higher will lead to success.
And Lazarus 1.4.4 will not compile with such a new version of FPC.
As this issue is not related to fpcupdeluxe, I will close.
