### ISSUE TITLE
error on installing cross OpenBSD i386 on Linux x64

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#595]
[fpcup.log](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/11925967/fpcup.log)

![Screenshot from 2023-07-01 15-59-43](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/4154978/16a653e9-5eeb-4b0a-a73c-3cc1760de5fd)

**Comment by Alexey-T** [comment]
this is log
[ddd.log](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/11925996/ddd.log)

**Comment by LongDirtyAnimAlf** [comment]
New tools were added. Please delete the old tools and try again.

**Comment by Alexey-T** [comment]
solved
