### ISSUE TITLE
still cannot install cross NetBSD i386

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#596]
related to #577 .

![Screenshot from 2023-07-01 16-45-27](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/4154978/5582b1c6-7410-41d0-a1d8-6aaa5102a0fb)

**Comment by LongDirtyAnimAlf** [comment]
Please try again. Tools have been added.

**Comment by Alexey-T** [comment]
solved
