### ISSUE TITLE
Linux - cant find unit esp32

### ISSUE THREAD

**Issue by SteveGatenby** [LongDirtyAnimAlf/fpcupdeluxe#597]
![Screenshot_2023-07-06_11-21-24](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/108208236/da27974d-1542-45ac-be2a-41302f6140ac)

Attempting install of Esp32 (xtensa) crosscompiler - 
failing with error as shown in screenshot

Running Xubuntu x64 22.04

Have vscode installed and working with esp variants if at all relevant :)

**Comment by LongDirtyAnimAlf** [comment]
I guess you found a bugger.
Please test this pre-release.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/v2.2.0tp/fpcupdeluxe-x86_64-linux

**Comment by SteveGatenby** [comment]
Worked perfectly - Thank you
