### ISSUE TITLE
shorten the msg-string

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#599]
as you can see, the dialog Edit shows:

`fpcupdeluxe: FPC cross-builder: ........`

![Screenshot_2023-08-03_17-59-03](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/4154978/3cff7631-4c6b-42a1-ba44-32547a015b21)

i suggest to remove redundant prefixes in this strring ('fpcupdeluxe' and 'FPC ') to make more room for info.

**Comment by LongDirtyAnimAlf** [comment]
Partly implemented. String 'fpcupdeluxe' will be removed in next release.
