### ISSUE TITLE
Cannot compile using cross to macOS Aarch64 on Linux x64

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#604]
I compile on Linux x64, I am adding cross for Darwin Aarch64.

[mac-arch64.txt](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/12329550/mac-arch64.txt)

**Comment by Alexey-T** [comment]
Later I got linking errors for this cross! Lazarus 3.99.

```
Warning: Object atsynedit_sortedrange.o not found, Linking may fail !
Warning: Object atstringproc_htmlcolor.o not found, Linking may fail !
Warning: Object graphutil.o not found, Linking may fail !
Warning: Object lazcanvas.o not found, Linking may fail !
Warning: Object lazregions.o not found, Linking may fail !
Warning: Object simpleipc.o not found, Linking may fail !
Warning: Object zipper.o not found, Linking may fail !
Warning: Object atsynedit_adapter_simple.o not found, Linking may fail !
Warning: Object ec_proc_lexer.o not found, Linking may fail !
Warning: Object colorbox.o not found, Linking may fail !
Warning: Object lcltranslator.o not found, Linking may fail !
Warning: Object gettext.o not found, Linking may fail !
Warning: Object lclunicodedata.o not found, Linking may fail !
Verbose: Linking /home/user/cuda/cuda/app/builds/macos-aarch64/cudatext
Error: Util aarch64-apple-darwin19-dsymutil not found, switching to external linking
```

**Comment by Alexey-T** [comment]
@fredvs
As you see I have missing tool:
`Error: Util aarch64-apple-darwin19-dsymutil not found, switching to external linking`

do you have this file? where can I get it?

**Comment by fredvs** [comment]
Hello Alexey.

Sadly I dont have a Mac and also no apps to test cross-compile for Mac.

**Comment by fredvs** [comment]
Re-hello Alexey.

For the game, I installed clang and the cross-compiler from Linux x86-64 to Mac Darwin aarch64.
Here are the files I get:
![apple_fpcupdeluxe](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/3421249/650b9d05-3367-4f8a-9fb4-cc3c8359eb6f)

**Comment by Alexey-T** [comment]
Fred,
this is normal content of the https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/linuxx64crossbins_v1.3/CrossBinsAppleAll.zip , ok? But I think this zip misses `aarch64-apple-darwin19-dsymutil` - per FPC error

**Comment by fredvs** [comment]
Yes, maybe but for me Apple is unknown-territory...
OK, I will try to cross compile a simple "Hello world!" to Mac-aarch64 and see what it say (but will not able to run it).

Write you later.

**Comment by Alexey-T** [comment]
Thank you, Fred!

**Comment by fredvs** [comment]
Hello Alexey.

OK, here first jump.
Trying to cross-compile simple writeln("test") prog:

```
Free Pascal Compiler version 3.2.2-r0d122c49 [2023/08/17] for aarch64
Copyright (c) 1993-2021 by Florian Klaempfl and others
(1002) Target OS: Darwin for AArch64
(3104) Compiling test.pas
(9009) Assembling test
test.pas(3,16) Error: (9005) Assembler aarch64-darwin-clang not found, switching to external assembling
test.pas(3,16) Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
```

Then trying with copy of  binary **aarch64-apple-darwin19-clang** --> **aarch64-darwin-clang**

```
Free Pascal Compiler version 3.2.2-r0d122c49 [2023/08/17] for aarch64
Copyright (c) 1993-2021 by Florian Klaempfl and others
(1002) Target OS: Darwin for AArch64
(3104) Compiling test.pas
(9009) Assembling test
test.pas(3,16) Error: (9005) Assembler aarch64-darwin-clang not found, switching to external assembling
test.pas(3,16) Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
```

But it did not help...

**Comment by fredvs** [comment]
Note that I get same error when trying to cross-compile to Darwin x86_64:

`/home/fred/fpcupdeluxe/fpc/bin/x86_64-linux/ppcx64 -Tdarwin -B -FU/home/fred/units /home/fred/test.pas`

Gives:

```
Free Pascal Compiler version 3.2.2-r0d122c49 [2023/08/17] for x86_64
Copyright (c) 1993-2021 by Florian Klaempfl and others
Target OS: Darwin for x86_64
Compiling /home/fred/test.pas
Assembling test
test.pas(3,16) Error: Assembler x86_64-darwin-clang not found, switching to external assembling
test.pas(3,16) Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted
```

But, like already said, maybe I miss something, Mac is jungle for me.

**Comment by fredvs** [comment]
Hum, imho if cross-compiling a simple "writeln('test') fails, no chance to cross-compile something more complicated, like GUI appps. (But with Mac maybe it is the opposite, I dont know).

**Comment by Alexey-T** [comment]
BTW, cross to Mac x64 works good, only the Arm64 is failing

**Comment by fredvs** [comment]
Ha, ok, so indeed I miss something, trying to cross-compile the simple writeln('test') for Darwin x86_64,with this:

`/home/fred/fpcupdeluxe/fpc/bin/x86_64-linux/ppcx64 -Tdarwin -B -FUunits test.pas`

I get this:

```
Free Pascal Compiler version 3.2.2-r0d122c49 [2023/08/17] for x86_64
Copyright (c) 1993-2021 by Florian Klaempfl and others
Target OS: Darwin for x86_64
Compiling /home/fred/test.pas
Assembling test
test.pas(3,16) Error: Assembler x86_64-darwin-clang not found, switching to external assembling
test.pas(3,16) Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted
```

Note that doing the same with all other BSD targets is ok.

**Comment by Alexey-T** [comment]
Hello @LongDirtyAnimAlf . Can something be made to fix this, please? I delay the macOS aarch64 version of my app for 3-4 versions.

**Comment by Alexey-T** [comment]
I cannot test [Release v2.4.0bp](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.4.0bp) becase it misses Linux binary.
Does it solve this issue?
