### ISSUE TITLE
I got compiler error for DragonFly x64 cross on Linux x64

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#607]
```
Verbose: Compiling resource /home/user/cuda/cuda/app/lib/x86_64-dragonfly/cudatext.or
Verbose: Linking /home/user/cuda/cuda/app/builds/dragonflybsd-x64-gtk2/cudatext
Error: /home/user/fpcupdeluxe/fpcupdeluxe32/cross/bin/x86_64-dragonfly/x86_64-unknown-dragonfly-ld.bfd: /home/user/fpcupdeluxe/fpcupdeluxe32/cross/lib/x86_64-dragonfly//libc.so: .dynsym local symbol at index 4 (>= sh_info of 2)
```

Before I didnt have such error. Not I reinstalled Deluxe to 2.4.0a and re-added all crosses.

```
Welcome @ FPCUPdeluxe.
FPCUPdeluxe V2.4.0a for x86_64-linux-gtk2
Running on Ubuntu
Build with: FPC 3.2.2 on Win11 x86_64
CPU cores used: 4
Available physical memory: 11911 MB
Available swap: 12234 MB

Current install directory: /home/user/fpcupdeluxe/fpcupdeluxe32

Found crosscompiler for  i386-windows
Found crosscompiler for  x86_64-windows
Found crosscompiler for  arm-linux
Found crosscompiler for  aarch64-linux
Found crosscompiler for  x86_64-darwin
Found crosscompiler for  aarch64-darwin
Found crosscompiler for  i386-freebsd
Found crosscompiler for  x86_64-freebsd
Found crosscompiler for  i386-netbsd
Found crosscompiler for  x86_64-netbsd
Found crosscompiler for  i386-openbsd
Found crosscompiler for  x86_64-openbsd
Found crosscompiler for  x86_64-dragonfly
Found crosscompiler for  x86_64-solaris

Got settings from install directory.
```

**Comment by Alexey-T** [comment]
FPC 3.2-fixes.

**Comment by fredvs** [comment]
Idem here (sorry for the x2 issue, I have seen your too late)
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/issues/616

**Comment by fredvs** [comment]
@Alexey-T : Were you able to install DragonFly + Xorg on a VM machine (or a real machine) with the keyboard working?

Keyboard works just after booting but when running startx, only the mouse works, not the keyboard.

In msegui mailing list, we are trying to make msegui DragonFly compatible but nobody was able to make DragonFly + Xorg + keyboard work.

Personally I have try witn VWware and OpenBox on Linux 64 and Windows 11 without be able to make the keyboard work.
I did try also with the previuos release but same problem with keyboard not working (but the mouse works).

I also try on a older laptop but without luck, always the same problem with keyboard.
Others  users have try too but they have same problem.
So not possible to test anything without keyboard.

Maybe we all have missing something (but we followed the infos of DragonFly).

Maybe you was able to do the keyboard work on DragonFly + Xorg?

**Comment by Alexey-T** [comment]
>Were you able to install DragonFly + Xorg on a VM machine (or a real machine) with the keyboard working?

yes. On VMWare 15 Workstation on Linux x64.

**Comment by Alexey-T** [comment]
But wait, I'm not sure I tested the keyboard.

**Comment by fredvs** [comment]
Re-hello.

>But wait, I'm not sure I tested the keyboard.

OK, I wait... ;-)

I did re-re-re-...-re try to install DragonFly on VMware 15 then on VMware 17 on Linux 64 bit but still, each time the keyboard is not working on a Xorg session.

And still no help from DragonFly mailing-list.

;-(

And for cross-compiling, (in case I find somebody who has DragonFly keyboard on Xorg working and could test on his system)  I did try with last commit of fpcupdeluxe, the compilation is ok but linking still fails with this message.

```
Hint: (11030) Start of reading config file /etc/fpc.cfg
Hint: (11031) End of reading config file /etc/fpc.cfg
Free Pascal Compiler version 3.2.3-767-gf2c446c29b [2023/07/24] for x86_64
Copyright (c) 1993-2021 by Florian Klaempfl and others
(1002) Target OS: DragonFly for x86-64
(3104) Compiling ideU.pas
...
(9015) Linking ideU
ideU.pas(143,1) Error: (9016) Util x86_64-dragonfly-ld.bfd not found, switching to external linking
ideU.pas(143,1) Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
```

**Comment by LongDirtyAnimAlf** [comment]
Closing as being solved (I guess).
