### ISSUE TITLE
embedded Lazarus installation fails

### ISSUE THREAD

**Issue by ellieEmco** [LongDirtyAnimAlf/fpcupdeluxe#612]
I have tried to install the embeddedlazarus module, but it fails. 

Lazarus options:           -g -gl -O1

Please stand back and enjoy !

16.08.2023 13:56:31: fpcupdeluxe: V476 (20230714) started.
FPCUPdeluxe V2.4.0a for x86_64-win64 running on Win64-10.0.19045
Build with: FPC 3.2.2 on Win11 x86_64

Found valid svn.exe application.
Found valid git.exe application.
Found valid hg.exe application.
Found valid make.exe application.
using config file C:\fpcupdeluxe\lazarus\lazarus.cfg
2.2.6
fpcupdeluxe: info: Universal Installer (GetModule: embedded-lazarus): Getting module embedded-lazarus.
fpcupdeluxe: info: Universal Installer (GetModule: embedded-lazarus): Going to download/update from GIT repository https://github.com/sechshelme/Lazarus-Embedded.
fpcupdeluxe: info: Universal Installer (GetModule: embedded-lazarus): Please wait: this can take some time (if repo is big or has a large history).
fpcupdeluxe: Executing: C:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe status --porcelain --untracked-files=no (working dir: C:\fpcupdeluxe\ccr\embedded-lazarus)
fpcupdeluxe: info: Universal Installer (GitClient: embedded-lazarus): Running GIT checkout or update.
fpcupdeluxe: Executing: C:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe status --porcelain (working dir: C:\fpcupdeluxe\ccr\embedded-lazarus)
fpcupdeluxe: Executing: C:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe config remote.origin.url (working dir: C:\fpcupdeluxe\ccr\embedded-lazarus)
https://github.com/sechshelme/Lazarus-Embedded/
fpcupdeluxe: Executing: C:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe remote -v (working dir: C:\fpcupdeluxe\ccr\embedded-lazarus)
origin	https://github.com/sechshelme/Lazarus-Embedded/ (fetch)
origin	https://github.com/sechshelme/Lazarus-Embedded/ (push)
fpcupdeluxe: Executing: C:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe pull (working dir: C:\fpcupdeluxe\ccr\embedded-lazarus)
Already up to date.
fpcupdeluxe: Executing: C:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe log -1 --pretty=format:%h (working dir: C:\fpcupdeluxe\ccr\embedded-lazarus)
b294918
fpcupdeluxe: info: Universal Installer (GetModule: embedded-lazarus): Download/update from GIT repository ok.
fpcupdeluxe: info: Universal Installer (GetModule: embedded-lazarus): No embedded-lazarus patches defined.
fpcupdeluxe: info: Universal Installer (InstallPackage): Installing embedded_gui_package version 2.0.10.
using config file C:\fpcupdeluxe\lazarus\lazarus.cfg
2.2.6
using config file C:\fpcupdeluxe\lazarus\lazarus.cfg
SetPrimaryConfigPath NewValue="C:\fpcupdeluxe\config_lazarus" -> "C:\fpcupdeluxe\config_lazarus"
fpcupdeluxe: info: Universal Installer (InstallPackage): Checking lpl file for embedded_gui_package.
fpcupdeluxe: info: Universal Installer (ConfigModule: embedded-lazarus): Packages were installed.
fpcupdeluxe: info: Universal Installer (ConfigModule: embedded-lazarus): Going to rebuild Lazarus.
C:\fpcupdeluxe\fpcbootstrap\make.exe: Entering directory `C:/fpcupdeluxe/lazarus'
./lazbuild.exe --max-process-count=12 --lazarusdir=. --build-ide=
using config file C:\fpcupdeluxe\lazarus\lazarus.cfg
SetPrimaryConfigPath NewValue="C:\fpcupdeluxe\config_lazarus" -> "C:\fpcupdeluxe\config_lazarus"
Hint: (lazarus) Last compile was incomplete for Embedded_GUI_Package 2.0.10
  State file="C:\fpcupdeluxe\ccr\embedded-lazarus\Lazarus_Embedded_GUI_Package\tmp\Embedded_GUI_Package.compiled"
Hint: (11030) Start of reading config file C:\fpcupdeluxe\fpc\bin\x86_64-win64\fpc.cfg
Hint: (11031) End of reading config file C:\fpcupdeluxe\fpc\bin\x86_64-win64\fpc.cfg
Free Pascal Compiler version 3.3.1-9929-g8d63a1ddfd [2022/01/18] for x86_64
Copyright (c) 1993-2022 by Florian Klaempfl and others
(1002) Target OS: Win64 for x64
(3104) Compiling embedded_gui_package.pas
(3104) Compiling embedded_gui_project_options_form.pas
(3104) Compiling embedded_gui_common.pas
C:\fpcupdeluxe\ccr\embedded-lazarus\Lazarus_Embedded_GUI_Package\embedded_gui_common.pas(349,30) Hint: (5057) Local variable "col" does not seem to be initialized
C:\fpcupdeluxe\ccr\embedded-lazarus\Lazarus_Embedded_GUI_Package\embedded_gui_common.pas(638,59) Error: (5000) Identifier not found "Default_EPS_Tool_Path"
C:\fpcupdeluxe\ccr\embedded-lazarus\Lazarus_Embedded_GUI_Package\embedded_gui_common.pas(669) Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: C:\fpcupdeluxe\fpc\bin\x86_64-win64\ppcx64.exe returned an error exitcode
Error: (lazarus) Compile package Embedded_GUI_Package 2.0.10: stopped with exit code 1
Error: (lazarus) [TLazPackageGraph.CompileRequiredPackages] "Exit code 1"
Error: (lazarus) Building IDE: Compile AutoInstall Packages failed.
C:\fpcupdeluxe\fpcbootstrap\make.exe: *** [useride] Error 2
C:\fpcupdeluxe\fpcbootstrap\make.exe: Leaving directory `C:/fpcupdeluxe/lazarus'

fpcupdeluxe: ERROR: Universal Installer (ConfigModule: embedded-lazarus): Failure trying to rebuild Lazarus. 
Details: .

ERROR: Fpcupdeluxe fatal error !
Sequencer (embedded-lazarus): Failure running fpcupdeluxe: error executing sequence embedded-lazarus
Sequencer (Only): Failure running fpcupdeluxe: error executing sequence Only

**Comment by LongDirtyAnimAlf** [comment]
This error is not related to fpcupdeluxe.
The package embedded_gui_package is not compatible with the Lazarus-version you have installed.
