### ISSUE TITLE
Could not install fpcdeluxe win11 64 bit

### ISSUE THREAD

**Issue by RakeshShresthaNP** [LongDirtyAnimAlf/fpcupdeluxe#613]
FPCUP(deluxe) is starting up.

FPCupdeluxe basedir:       D:\fpcupdeluxe
Binutils dir:              D:\fpcupdeluxe\fpcbootstrap
Bootstrap dir:             D:\fpcupdeluxe\fpcbootstrap

FPC URL:                   https://gitlab.com/freepascal.org/fpc/source
FPC source directory:      D:\fpcupdeluxe\fpcsrc
FPC install directory:     D:\fpcupdeluxe\fpc
FPC options:               

Lazarus URL:               https://gitlab.com/freepascal.org/lazarus/lazarus
Lazarus source directory:  D:\fpcupdeluxe\lazarus
Lazarus install directory: D:\fpcupdeluxe\lazarus
Lazarus options:           -g -gl -O1

Please stand back and enjoy !

8/17/2023 15:01:02: fpcupdeluxe: V476 (20230714) started.
FPCUPdeluxe V2.4.0a for x86_64-win64 running on Win64-10.0.22621
Build with: FPC 3.2.2 on Win11 x86_64

Checking dev-libs for win32 LCLWidgetType.
Found valid svn.exe application.
Found valid git.exe application.
Found valid hg.exe application.
fpcupdeluxe: info: FPC Native Installer (CheckModule: FPC): Checking FPC sources with Git Client.
fpcupdeluxe: info: FPC Native Installer (GetModule: FPC): Start checkout/update of FPC sources.
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe log -1 --pretty=format:%h (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe describe --tags --long --always (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe log -g -1 --pretty=oneline (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe describe --tags --all --long --always (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: info: FPC Native Installer (GitClient: FPC): Running GIT checkout or update of tag release_3_2_2.
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe status --porcelain (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe clone --recurse-submodules --depth=1 --branch release_3_2_2 https://gitlab.com/freepascal.org/fpc/source.git/ D:\fpcupdeluxe\fpcsrc (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe clone --recurse-submodules --depth=1 --branch release_3_2_2 https://gitlab.com/freepascal.org/fpc/source.git/ D:\fpcupdeluxe\fpcsrc (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe clone --recurse-submodules --depth=1 --branch release_3_2_2 https://gitlab.com/freepascal.org/fpc/source.git/ D:\fpcupdeluxe\fpcsrc (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe remote -v (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe describe --tags --abbrev=0 (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe pull (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe log -1 --pretty=format:%h (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe describe --tags --long --always (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe log -g -1 --pretty=oneline (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe describe --tags --all --long --always (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe describe HEAD (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe describe --tags --exact-match HEAD (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe describe --tags --always HEAD (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe describe --contains --all HEAD (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe name-rev --name-only HEAD (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe show -s --format=%s%b (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe log -1 --pretty=format:%h (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe describe --tags --long --always (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe log -g -1 --pretty=oneline (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe describe --tags --all --long --always (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: ERROR: FPC Native Installer (GetModule: FPC): Could not get version of FPC sources. Expect severe errors.
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe log -1 --pretty=format:%h (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe describe --tags --long --always (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe log -g -1 --pretty=oneline (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe describe --tags --all --long --always (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: info: FPC Native Installer (GetModule: FPC): FPC is at revision/hash: FRET_UNKNOWN_REVISION.
fpcupdeluxe: info: FPC Native Installer (GetModule: FPC): No updates for FPC found.
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe describe HEAD (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe describe --tags --exact-match HEAD (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe describe --tags --always HEAD (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe describe --contains --all HEAD (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: Executing: D:\fpcupdeluxe\fpcbootstrap\git\cmd\git.exe name-rev --name-only HEAD (working dir: D:\fpcupdeluxe\fpcsrc)
fpcupdeluxe: info: FPC Native Installer (BuildModule: FPC): Going to build FPC.
fpcupdeluxe: ERROR: FPC Native Installer (BuildModule: FPC): D:\fpcupdeluxe\fpcsrc\Makefile not found. Severe error. Should not happen. Aborting.

ERROR: Fpcupdeluxe fatal error !
Sequencer (FPC): Failure running fpcupdeluxe: error executing sequence FPC
Sequencer (Default): Failure running fpcupdeluxe: error executing sequence Default

**Comment by LongDirtyAnimAlf** [comment]
The log is clear: the GIT-client is not able to download the FPC sources.
I do not know why.
You might try to install a Win11 GIT client yourself.
E.g.: https://git-scm.com/download/win
After install, fpcupdeluxe should be able to use the system wide GIT client.
