### ISSUE TITLE
[Suggestion] Add a button to add the docking and docked form editor to the modules tab

### ISSUE THREAD

**Issue by gcarreno** [LongDirtyAnimAlf/fpcupdeluxe#620]
Hey @LongDirtyAnimAlf,

As you did with the current `OPM` button, add another button below, or above that one to install the following in one swoop:
- AnchorDocking
- AnchorDockingDsgn
- DockedFormEditor

An image with a suggested positioning:

![image](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/81799/b8156805-a981-4ec9-8a08-ee288a14f262)

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
Good idea ! Done.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/5a1c75253bf3d5cc6b1b3ecbe0df8750fb6682f7
Next release.

![docked](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/10783972/df1a3876-0f9c-4818-9de7-b179ac1430a4)

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

That's **AWESOME**!!

Love your work, and please keep at it !!!

:people_hugging: :heart: 

Cheers,
Gus
