### ISSUE TITLE
Binutils for ARM linux-musl

### ISSUE THREAD

**Issue by SceneCityDev** [LongDirtyAnimAlf/fpcupdeluxe#621]
Hi,

would you be so kind to build cross-binutils (either for win32 and/or win64) to target ARM linux-musl? Right now you are providing aarch64 linux-musl, but no 32 bit version for armv7.

Most routers running OpenWRT are armv5 or up with linux-musl, so these will enable cross-compilation of FPC to the majority of OpenWRT-compatible routers.

Thank you!

Simon

**Comment by LongDirtyAnimAlf** [comment]
Pre-release with some extra MUSL features.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.4.0bp

Please remove previous bins and libs for musl, and let fpcupdeluxe install new.

This release is not meant to be fully working.
I have added some OpenWrt libs for arm. But more are needed.
I would be grateful if you could supply me with all libs that are needed !!

Thanks.
