### ISSUE TITLE
Prerequisites for release with qt6?

### ISSUE THREAD

**Issue by otalado** [LongDirtyAnimAlf/fpcupdeluxe#627]
I've checked on the fpcupdeluxe wiki but found no mention of prerequisites for packages using the qt6 there. I would like to avoid to try installing and failing because of missing package/libraries ...

**Comment by LongDirtyAnimAlf** [comment]
To use QT6, you need to have QT6 installed. That's  it.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/v2.4.0a/fpcupdeluxe-x86_64-linux-qt6.zip
