### ISSUE TITLE
FPCUPdeluxe cannot find libQT5Pas.so.1

### ISSUE THREAD

**Issue by adderthorn** [LongDirtyAnimAlf/fpcupdeluxe#629]
Version: 2.4.0a
Arch: x64 - qt5
OS: Linux (openSUSE Tumbleweed)

This used to work fine, but now complains that it cannot find the libQT5Pas (which I have installed and is located in `/usr/lib64/libQt5Pas.so.1`).

```
No system wide libQt5Pas.so found. Some QT5 trickery will be used
```

Is there some way to tell the application where to look for the lib?

**Comment by LongDirtyAnimAlf** [comment]
I have added this library location into fpcupdeluxe.
Will be included in next release.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/0ada6418faca3870084b6a67abe7eb320d8387b0
