### ISSUE TITLE
2.4.0bp  -XLC

### ISSUE THREAD

**Issue by jinshaopu** [LongDirtyAnimAlf/fpcupdeluxe#635]
win11

2.4.0.bp    
ppcross386  
Invalid paramet   -XLC
2.4.0a  no problem

**Comment by LongDirtyAnimAlf** [comment]
I have uploaded new pre-release binaries.
These should solve.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.4.0bp
