### ISSUE TITLE
Latest PiOS failure

### ISSUE THREAD

**Issue by peardox** [LongDirtyAnimAlf/fpcupdeluxe#637]
Things end badly using PiOS ...

simon@raspberrypi:~ $ uname -a
Linux raspberrypi 6.1.0-rpi6-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.58-1+rpt2 (2023-10-27) aarch64 GNU/Linux
simon@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
simon@raspberrypi:~ $

Clicked the email log button so full logs should be with you

> /usr/bin/make packages_smart FPC=/home/simon/fpcupdeluxe/fpcsrc/compiler/ppca64 FPCFPMAKE=/home/simon/fpcupdeluxe/fpcsrc/compiler/ppca64 RELEASE=1 'OPT=-Sg -vw-n-h-l-d-u-t-p-c-'
/usr/bin/make -C packages smart
/usr/bin/make -C fpmkunit bootstrap
/home/simon/fpcupdeluxe/fpcsrc/compiler/ppca64 src/fpmkunit.pp  -Fu/home/simon/fpcupdeluxe/fpcsrc/rtl/units/aarch64-linux -FUunits_bs/aarch64-linux -Fu../paszlib/src -Fu../hash/src -Fi../paszlib/src  -Fi../fcl-process/src/unix -Fu../fcl-process/src -Fi../fcl-process/src/linux -Fi../fcl-process/src/dummy -Fu../libtar/src -Sg -vw-n-h-l-d-u-t-p-c-
Target OS: Linux for AArch64
Compiling src/fpmkunit.pp
Compiling /home/simon/fpcupdeluxe/fpcsrc/packages/fcl-process/src/process.pp
Compiling /home/simon/fpcupdeluxe/fpcsrc/packages/fcl-process/src/pipes.pp
Compiling /home/simon/fpcupdeluxe/fpcsrc/packages/libtar/src/libtar.pp
Compiling /home/simon/fpcupdeluxe/fpcsrc/packages/paszlib/src/zipper.pp
Compiling /home/simon/fpcupdeluxe/fpcsrc/packages/paszlib/src/zstream.pp
Compiling /home/simon/fpcupdeluxe/fpcsrc/packages/paszlib/src/zbase.pas
Compiling /home/simon/fpcupdeluxe/fpcsrc/packages/paszlib/src/gzio.pas
Compiling /home/simon/fpcupdeluxe/fpcsrc/packages/hash/src/crc.pas
Compiling /home/simon/fpcupdeluxe/fpcsrc/packages/paszlib/src/zdeflate.pas
Compiling /home/simon/fpcupdeluxe/fpcsrc/packages/paszlib/src/trees.pas
Compiling /home/simon/fpcupdeluxe/fpcsrc/packages/paszlib/src/adler.pas
Compiling /home/simon/fpcupdeluxe/fpcsrc/packages/paszlib/src/zinflate.pas
Compiling /home/simon/fpcupdeluxe/fpcsrc/packages/paszlib/src/infblock.pas
Compiling /home/simon/fpcupdeluxe/fpcsrc/packages/paszlib/src/infcodes.pas
Compiling /home/simon/fpcupdeluxe/fpcsrc/packages/paszlib/src/infutil.pas
Compiling /home/simon/fpcupdeluxe/fpcsrc/packages/paszlib/src/inffast.pas
Compiling /home/simon/fpcupdeluxe/fpcsrc/packages/paszlib/src/inftrees.pas
26900 lines compiled, 3.4 sec
/home/simon/fpcupdeluxe/fpcsrc/compiler/ppca64 fpmake.pp  -Fu/home/simon/fpcupdeluxe/fpcsrc/packages/fpmkunit/units_bs/aarch64-linux -Fu/home/simon/fpcupdeluxe/fpcsrc/rtl/units/aarch64-linux  -Sg -vw-n-h-l-d-u-t-p-c-
Target OS: Linux for AArch64
Compiling fpmake.pp
Linking fpmake
/bin/ld: /home/simon/fpcupdeluxe/fpcsrc/rtl/units/aarch64-linux/cprt0.o: in function `_start':
(.text+0x54): undefined reference to `__libc_csu_init'
/bin/ld: (.text+0x58): undefined reference to `__libc_csu_init'
/bin/ld: (.text+0x5c): undefined reference to `__libc_csu_fini'
/bin/ld: (.text+0x60): undefined reference to `__libc_csu_fini'
fpmake.pp(60) Error: Error while linking
fpmake.pp(60) Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted
make[1]: *** [Makefile:2682: packages_smart] Error 2
make: *** [Makefile:2837: build-stamp.aarch64-linux] Error 2

fpcupdeluxe: ERROR: FPC Native Installer (BuildModule: FPC): Error running /usr/bin/make for FPC failed with exit code 512
. Details: .

ERROR: Fpcupdeluxe fatal error !
Sequencer (FPC): Failure running fpcupdeluxe: error executing sequence FPC
Sequencer (Default): Failure running fpcupdeluxe: error executing sequence Default

**Comment by LongDirtyAnimAlf** [comment]
You need FPC trunk on these newer systems.
https://gitlab.com/freepascal.org/fpc/source/-/issues/39295

**Comment by peardox** [comment]
Trying that now - thx

There's also a GTK Critical (with no real helpful info) that occurs when launching fpcupdeluxe. I think this is down to Wayland being the default WM for new PiOS as switching to X11 stops it occurring. That said I'm installing with Wayland enabled as that's what joe average will use

**Comment by peardox** [comment]
Here's the launch message under Wayland...

> simon@raspberrypi:~/src/fpc $ ./fpcupdeluxe-aarch64-linux 

(fpcupdeluxe-aarch64-linux:1911): GLib-GObject-CRITICAL **: 08:16:41.569: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

I've got the Pi connected to a HDMI Switch - swiching away from and back to the Pi makes FPCUpDeluxe show so presumably switching monitor off/on would have the same effect

VNC is extremely ropey ATM for new PiOS :(

**Comment by michaliskambi** [comment]
I see this error was also discussed on fpc-pascal mailing list a few days too, thread _"Cannot build fpc on Raspberry Pi4B running PiOS 64 bit (aarch64 Linux)"_, https://lists.freepascal.org/pipermail/fpc-pascal/2023-November/061860.html .

I just tested and (this confirms Sven Barth's answer in that thread):

- Building FPC 3.2.2 (starting from FPC 3.2.2 installed using Debian packages) fails with above error

- Building latest FPC 3.2.3 (latest state of `fixes_3_2` branch of FPC) works OK

- (I didn't test with FPC 3.3.1, I assume it would also work.)

Note that I didn't use fpcupdeluxe for this, instead my own super-minimal script to install FPC/Lazarus: https://github.com/castle-engine/cge-scripts/blob/master/install_fpc_lazarus . 

So in case anyone else is struggling with this, trying 3.2.3 (fixes_3_2 branch) instead of 3.2.2 may be all you need :)

**Comment by peardox** [comment]
I installed 3.3.1 on the same system so know that works (although the Lazarus Debugger breaks)
