### ISSUE TITLE
raspberry 6.1.0-rpi6-rpi-v8 install fpc error

### ISSUE THREAD

**Issue by szlbz** [LongDirtyAnimAlf/fpcupdeluxe#638]
When compiling fpc in the new system kernel ( 6.1.0-rpi6-rpi-v8 ) of Raspberry Pi, the following error occurred，Please ask how to handle this error：
/bin/ld: (.text+0x54): undefined reference to '__libc_csu_init'
/bin/ld: ( .text+0x58): undefined reference to '__libc_csu_init' 
/bin/ld: ( .text+0x5c): undefined reference to '__libc_csu_fini'
/bin/ld: (.text+0x60): undefined reference to '__libc_csu_fini'
Thank 
![微信图片_20231114130219](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/109887617/399c2947-94a0-4a31-af2c-5ecd05810f9a)

**Comment by LongDirtyAnimAlf** [comment]
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/issues/637
