### ISSUE TITLE
Start UpDeluxe on Haiku R1 beta4

### ISSUE THREAD

**Issue by Tango600** [LongDirtyAnimAlf/fpcupdeluxe#639]
How run the utility. Attributes are given. (chmod 777 fpcupdeluxe-x86_64-haiku-qt5)
![VirtualBox_Haiku_21_11_2023_16_02_16](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/5998520/0455f068-4bca-495a-af87-eccc252de56d)
![VirtualBox_Haiku_21_11_2023_16_00_15](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/5998520/3b61e7bd-3bf3-46f8-8587-70f9cc36a2b4)

Package qt5, is installed.

**Comment by LongDirtyAnimAlf** [comment]
Strange.
I just did a new install in a brand new VM, and all worked 100%.


![haiku64](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/10783972/63042b84-2de7-4e0a-9b11-34d288a1d90b)

**Comment by Tango600** [comment]
Downloaded just time. May be do any one manipulations?

**Comment by LongDirtyAnimAlf** [comment]
Dunno.
Please try this release.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/v2.4.0bp/fpcupdeluxe-x86_64-haiku-qt5.zip
It is exactly the same as I have used just a few minutes ago.

**Comment by Tango600** [comment]
I'm nube, I break normal mechanizm of running application, I open FileType app, and set attributes.
![VirtualBox_Haiku_21_11_2023_18_08_11](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/5998520/46ab2d82-bd5e-49c9-a5be-becce8fb0900)
![VirtualBox_Haiku_21_11_2023_18_08_28](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/5998520/336cbc3f-796d-4fab-9164-f92231116142)
