### ISSUE TITLE
On Windows Platform " pangocairo.o"   can't be found when link for linux-aarch64

### ISSUE THREAD

**Issue by jinshaopu** [LongDirtyAnimAlf/fpcupdeluxe#640]
On Windows Platform " pangocairo.o"   can't be found when link for linux-aarch64
but for linux-arm is ok
![image](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/14891482/7f257c5d-3a18-4887-87db-b9483c7fcae7)

but the file is existed

**Comment by jinshaopu** [comment]
how to set the linker path or target?   Is there some file to set these information

**Comment by jinshaopu** [comment]
how to set the linker path or target?   Is there some file to set these information

**Comment by LongDirtyAnimAlf** [comment]
I have no clue whatsoever about this error. And I guess it is not related to fpcupdeluxe.
So, I am closing this issue.
Please re-open if needed or in case you have found a fix for this problem yourself.
Thanks.
