### ISSUE TITLE
use depth 1 for slow internet

### ISSUE THREAD

**Issue by zaher** [LongDirtyAnimAlf/fpcupdeluxe#641]
When pulling/clone repo please use depth 1 in git command line to save some bandwidth for slow internet.

**Comment by gcarreno** [comment]
Hey Zaher(@zaher),

`fpcupdeluxe` will only perform a full history download when you install `main` aka `trunk`.

If you opt for installing the stable tag or any other versioned tag, it will use `--depth=1`.

So, can you be more clear where you want this on?

Cheers,
Gus

**Comment by zaher** [comment]
I want the trunk too, at least add option for it.

**Comment by gcarreno** [comment]
Hey Zaher(@zaher)

Humm, you do have a point in the fact that it **could** be an option.

Let's see what @LongDirtyAnimAlf has to say about it.

Cheers,
Gus

**Comment by zaher** [comment]
I use trunk for my project on windows , I want to compile it to Linux, but Linux snapshots broken, 
Trying to get one using FPCDelux need ages for me and it cut, and keep repeat to download the whole repo, for both FPC and Lazarus.

**Comment by LongDirtyAnimAlf** [comment]
If you install stable versions of FPC and Lazarus, up will use depth = 1 to get the sources.
Moving targets like fixes and trunk download the whole source repo.
