### ISSUE TITLE
Cross compiling to Android aarch64

### ISSUE THREAD

**Issue by han-k59** [LongDirtyAnimAlf/fpcupdeluxe#645]
In Linux I'm cross compling a command line program to aarch64, Android. Compiling doesn't give any error but in Lubuntu 22 the Android executable file created is reported as a shared object: 

file astap_cli:
astap_cli: ELF 64-bit **LSB shared object, ARM** aarch64, version 1 (SYSV), dynamically linked, interpreter libdl.so, BuildID[sha1]=bb58f96998c6d55628402334f44e928c1cbd56cc, stripped

Using an older setup Lubuntu 20.4 it is reporting correctly as:

file astap_cli:
astap_cli: ELF 64-bit **LSB executable, ARM** aarch64, version 1 (SYSV), statically linked, stripped

I'm using Fpcupdeluxe version 2.4.0a and tried several FPC/Lazarus installations either stable or trunk but the result is the same. The older (trunk) setup doesn't have that problem. Any idea why this is happening? Is this related to Fpcupdeluxe or libdl.so or Lubuntu version?

Han

**Comment by han-k59** [comment]
This is a false alarm. The application still runs in a terminal of the BlueStacks emulator. So the reporting has changed but it is still executable. This case can be closed

**Comment by han-k59** [comment]
I have to reopen this. In a real Android system the executable doesn't run. Only in emulation.

I have tried with older versions of FPC & Lazarus the cross compiling to Android but all produce a shared object file instead of an executable. I have also tried Lubuntu 20.4 which used to work but it doesn't any longer (due to update?). 

So I like to have this fixed, but don't understand where the problem originates from.

**Comment by han-k59** [comment]
I assume I have to compile with the option -kno-pie   but it doesn't work.  I'm out of ideas now.

**Comment by han-k59** [comment]
I tried today Fpcupdeluxe v2.0.1. Same result it produces an:

"ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter libdl.so"

Still not the executable file as it did 6 months ago.

Something has changed in the last 6 months. I just can't figure out where and how to fix it.

**Comment by LongDirtyAnimAlf** [comment]
I do not have any clue about what caused this. And how to solve this.

My advice. Or question.
Try to setup FPC and Lazarus and crossing towards Android without fpcupdeluxe.
If it works in that normal setup, it is likely caused by fpcupdeluxe.
If the same error occurs, we might file a bugger for FPC.

**Comment by han-k59** [comment]
With FPCupdeluxe I have tried to install older versions Lazarus & FPC versions but it did not help. I also tried installing them on an older Linux version. That all did not help. So at the moment I suspect the "cross compiling tools".  The older version of the cross compile tools are not available at least I could find.  I like to try that first. Do you still have them available?

**Comment by LongDirtyAnimAlf** [comment]
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/linuxx64crossbins_v1.0/CrossBinsAndroidAarch64.zip
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/linuxx64crossbins_v1.1/CrossBinsAndroidAarch64.zip

**Comment by han-k59** [comment]
Version 1.1.was installed.  I unpacked version 1 but it did not fix it. 

Resume, 
1) Older versions of Fpcupdeluxe do not fix it
2) Older versions of Lazarus/FPC also do not fix it.
3) Operating system?

I will check 3).

**Comment by han-k59** [comment]
I created a new Lubuntu 18 virtual machine. Used FPcupdeluxe 2.2.0q to create a Lazarus 2.26 and  FPC3.2.2. Created the simplest program "Hello world" for Anstroid. Instead of an executable is still creates a "LSB shared object". So no success.

This doesn't match up.  I will try to setup cross compiling myself but foresee a lot of problems to do that.

**Comment by LongDirtyAnimAlf** [comment]
Have you tried the compiler option -Cg- ?
This should force-OFF the generation of PIC-code.

**Comment by han-k59** [comment]
Yes that works!! Finally.

I have tried in the past "-Cg" but not "-Cg-". Why the second minus sign? I don't see that in the commands of FPC. Fpc just report the option as:

      -Cg        Generate PIC code

**Comment by han-k59** [comment]
It must be this:

`Only options valid for the default or selected platform are listed.
 Put + after a boolean switch option to enable it, - to disable it.`

**Comment by han-k59** [comment]
All clear now.
