### ISSUE TITLE
On 2.4.0b: Missing Lazarus 3.0 tag on the list

### ISSUE THREAD

**Issue by gcarreno** [LongDirtyAnimAlf/fpcupdeluxe#646]
Hey Don(@LongDirtyAnimAlf),

Repeating the issue reported on the Lazarus Forum so it's more handy.

As mentioned on that post, you're missing the Lazarus 3.0 tag on the Lazarus versions list.

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
Also. New binaries. Again, please keep quiet ... ;-)

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

Thanks man, and I will keep quiet :stuck_out_tongue_winking_eye: 

Cheers,
Gus
