### ISSUE TITLE
On 2.4.0b: The hint for the Docking button is still the same as the OPM button

### ISSUE THREAD

**Issue by gcarreno** [LongDirtyAnimAlf/fpcupdeluxe#647]
Hey Don(@LongDirtyAnimAlf),

I guess you did a copy/paste of the `OPM` button to the Docking button and then forgot to change the hint on it.

Quick fix, amirite?! 🫂 ❤️

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
New binaries. Please keep quiet ... ;-)

**Comment by gcarreno** [comment]
Hey Don(@LongDirtyAnimAlf),

Ehehehe!!

Thanks man!!

Cheers,
Gus
