### ISSUE TITLE
Depends on gdb for MacOS

### ISSUE THREAD

**Issue by Tj85710** [LongDirtyAnimAlf/fpcupdeluxe#65]
Hello,

Could you mention this dependency in the README.MD file ? Moreover, according to Jerome Delauney  (https://www.developpez.net/forums/blogs/912403-beanzmaster/) it is necessary to stick to the 8.0.1 version. 
It can be installed with : 
$ brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/9ec9fb27a33698fc7636afce5c1c16787e9ce3f3/Formula/gdb.rb

Than it must be code signed. By following this, it is possible to debug with dbg on HighSierra. This process is described in details in a lot of places over the net.

By the way, QT5 is very nice on Mac. In my opinion it would be the perfect graphic standard library for all of the Lazarus platforms...

Thierry

**Comment by LongDirtyAnimAlf** [comment]
On Mac, lldb is now used.
Please re-open when issues persist.

**Comment by Tj85710** [comment]
On my Macs I am using the version 1.6.2.x with Cocoa since monthes, it works perfectly. LLDB is taken in charge, it does what it can, it's still a work in progress but this is not your problem.
You have done a real great job. Thank you.
