### ISSUE TITLE
AArch64 MacOS Build Missing?

### ISSUE THREAD

**Issue by mrunion** [LongDirtyAnimAlf/fpcupdeluxe#650]
More of a question than an issue, but is there going to be an Apple Silicon version of 2.4.0b? I don't see it in the release builds. (For example, 2.4.0a had fpcupdeluxe-aarch64-darwin-cocoa.zip)

**Comment by LongDirtyAnimAlf** [comment]
Yep. Was missing.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/v2.4.0b/fpcupdeluxe-aarch64-darwin-cocoa.zip
