### ISSUE TITLE
Gitlab alias lookup of Lazarus tag/branch/url failed.

### ISSUE THREAD

**Issue by dkounal** [LongDirtyAnimAlf/fpcupdeluxe#651]
With yesterday's version I am getting the following error:
fpcupdeluxe: ERROR: Gitlab alias lookup of Lazarus tag/branch/url failed. Expect errors.

**Comment by LongDirtyAnimAlf** [comment]
I need much more info.
System. CPU. OS. FPC target. Lazarus target. Print of screen with error.

**Comment by dkounal** [comment]
Welcome @ FPCUPdeluxe.
FPCUPdeluxe V2.4.0b for x86_64-win64-win32
Running on Win64-10.0.22631
Build with: FPC 3.2.2 on Win11 x86_64
CPU cores used: 12
Available physical memory: 32374 MB

Current install directory: C:\fpcupdeluxe\fpcupdeluxe
![εικόνα](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/37013295/ee1051b1-f2dc-4829-9066-46f28585eb15)

**Comment by dkounal** [comment]
Clean installation
Installing/Updating "Stable" for both FPC/Lazarus works without such error
The problem seems to be caused by "fixes-3.0" in Lazarus. 
Selecting "stable" for Lazarus does not produces this error

**Comment by LongDirtyAnimAlf** [comment]
Confirmed. Will solve.

**Comment by LongDirtyAnimAlf** [comment]
Solved. New binaries, replacing the old binaries. Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.4.0b
