### ISSUE TITLE
fpcupdeluxe 2.4b, on Linux x64, getting cross-bins error

### ISSUE THREAD

**Issue by uvwx413** [LongDirtyAnimAlf/fpcupdeluxe#652]
......
fpcupdeluxe: ERROR: Failure due to missing cross binary tools.
fpcupdeluxe: ERROR: Failure due to missing cross libraries.

Looking for FPCUPdeluxe cross-tools on GitHub (if any).
Going to look for the right cross-bins. Can (will) take some time !
Looking for: CrossBinsLinuxAarch64

......
fpcupdeluxe: ERROR: Failure due to missing cross binary tools.
fpcupdeluxe: ERROR: Failure due to missing cross libraries.

Looking for FPCUPdeluxe cross-tools on GitHub (if any).
Going to look for the right cross-bins. Can (will) take some time !
Looking for: CrossBinsFreeBSDx64

**Comment by gcarreno** [comment]
Hey @uvwx413,

We're gonna wait for a final on this from @LongDirtyAnimAlf, but if I'm not mistaken, this is as intended.

What do I mean by this?
When you do a fresh install of any cross compiler that needs tools and libs, those are missing from your folder.
That's what `fpcupdeluxe` is relating to you, that they are missing, since they have never been downloaded.

I'm quite sure that, immediately, after that message was shown, the downloader began to get them, right?

Hope this clarifies your doubts.
Nonetheless, let's wait to see what @LongDirtyAnimAlf has to say.

Cheers,
Gus

**Comment by LongDirtyAnimAlf** [comment]
You might give me some more info. Please show me a screenshot of fpcupdeluxe with the error.
And FPC and Lazarus version.
Thanks.

**Comment by uvwx413** [comment]
Thanks! 
This is the screen shot.  if press OK button(right of Abort Button), downloading not startup.
Yes, this is a fresh installation of cross compiler.  

![截图_2023-12-24_17-46-54](https://github.com/LongDirty if AnimAlf/fpcupdeluxe/assets/72081475/dfb13baa-5d05-4b0b-949b-76dcee6a0bd2)

**Comment by uvwx413** [comment]
Thanks!
This is the screen shot. FPC is stable version(3.2.2),  Lazarus is stable version(3.0)
if press OK button(right of Abort Button), downloading not startup.
Yes, this is a fresh installation of cross compiler.
![2023-12-24_17-46-54](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/72081475/bcadbec5-8758-4c54-af9e-0e6e8a799df8)

**Comment by uvwx413** [comment]
The previous  information window is:
![2023-12-24_17-47-52](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/72081475/d11b90cc-1963-4f6b-b9b2-7f7fa2db7d4a)

**Comment by LongDirtyAnimAlf** [comment]
You seem to use the zip-install of FPC and Lazarus.
Please tell me the reason to do so. Thanks.

**Comment by uvwx413** [comment]
> You seem to use the zip-install of FPC and Lazarus. Please tell me the reason to do so. Thanks.

Yes, This is a ZIP-install. 
The fpcupdeluxe  report downloading error now and then, if I use git-install. Sometimes the network is slow, sometimes the connection times out（downloading interrupted） or the downloaded file cannot be found. Normally，zip-Install has a high chance of success。

But fpcupdeluxe is indeed a good tool for installing Lazarus, as it supports different platforms and provides cross compilation tools.
Thank you very much！

**Comment by LongDirtyAnimAlf** [comment]
Thanks for explaining !
The tools and libs that are needed for cross-compiling are also downloaded from GitHub. So you might suffer from a bad connection also when trying to install a cross-compiler.
However. You can also install the tools by yourself.
Download the binaries and the libraries and unpack them in the correct location. Fpcupdeluxe will find them and build the cross-compiler.

![upbins](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/10783972/574a9f3e-665c-4a22-b8ef-572839bc6d4d)
![uplibs](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/10783972/76e20a85-5913-4c45-b804-973dd109b2ea)

**Comment by uvwx413** [comment]
Yes, Its OK.
if download the *.zip file directly and unpack it to fpcupdeluxe/cross/....  
the downloading speed is 350KB/s

I have found that if try N+1 times, fpcupdeluxe  downloads the croosbins* and crosslibs* file sometimes succeeds.
Thanks！
