### ISSUE TITLE
Pi4 Aarch64 PiOS Bookworm link errors

### ISSUE THREAD

**Issue by peardox** [LongDirtyAnimAlf/fpcupdeluxe#654]
Using trunk/trunk 2.4.0b
https://gitlab.com/freepascal.org/fpc/source/-/issues/39295

=========================
Target OS: Linux for AArch64
Compiling fpmake.pp
Linking fpmake
/bin/ld: /home/simon/fpcupdeluxe/fpcsrc/rtl/units/aarch64-linux/cprt0.o: in function `_start':
(.text+0x54): undefined reference to `__libc_csu_init'
/bin/ld: (.text+0x58): undefined reference to `__libc_csu_init'
/bin/ld: (.text+0x5c): undefined reference to `__libc_csu_fini'
/bin/ld: (.text+0x60): undefined reference to `__libc_csu_fini'
make[1]: *** [Makefile:2682: packages_smart] Error 2
make: *** [Makefile:2837: build-stamp.aarch64-linux] Error 2
fpmake.pp(60) Error: Error while linking
fpmake.pp(60) Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted

fpcupdeluxe: ERROR: FPC Native Installer (BuildModuleCustom: FPC): Error running /usr/bin/make for FPC failed with exit code 512
. Details: .

**Comment by LongDirtyAnimAlf** [comment]
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/issues/637
