### ISSUE TITLE
Unable to compile on FreeBSD 14.0-RELEASE

### ISSUE THREAD

**Issue by trivthebofh** [LongDirtyAnimAlf/fpcupdeluxe#657]
When I try compiling FPC + Lazarus on FreeBSD 14.0-RELEASE-p3 an error. **AFTER** encountering this with fpcupdeluxe I was able to compile FPC + Lazarus from ports.

I get the following error. If there is any more useful information I can provide I'm happy to do so:

/usr/local/bin/gmake -C freebsd all
as --64 -o /home/ullr/fpcupdeluxe/fpcsrc/rtl/units/x86_64-freebsd/prt0.o x86_64/prt0.as
as --64 -o /home/ullr/fpcupdeluxe/fpcsrc/rtl/units/x86_64-freebsd/cprt0.o x86_64/cprt0.as
as --64 -o /home/ullr/fpcupdeluxe/fpcsrc/rtl/units/x86_64-freebsd/gprt0.o x86_64/gprt0.as
as --64 -o /home/ullr/fpcupdeluxe/fpcsrc/rtl/units/x86_64-freebsd/dllprt0.o x86_64/dllprt0.as
An unhandled exception occurred at $0000000000422C7B:
EAccessViolation: Access violation
  $0000000000422C7B
gmake[7]: *** [Makefile:3201: system.ppu] Error 217
gmake[6]: *** [Makefile:2217: freebsd_all] Error 2
gmake[5]: *** [Makefile:4470: rtl] Error 2
gmake[4]: *** [Makefile:4330: next] Error 2
gmake[3]: *** [Makefile:4339: ppc2] Error 2
/usr/home/ullr/fpcupdeluxe/fpcsrc/compiler/ppc1 -Ur -Ur -Xs -O2 -n -Fi../inc -Fi../x86_64 -Fi../unix -Fi../bsd -Fi../bsd/x86_64 -Fi../freebsd/x86_64 -FE. -FU/home/ullr/fpcupdeluxe/fpcsrc/rtl/units/x86_64-freebsd -Cg -Sg -vw-n-h-l-d-u-t-p-c- -Fl/usr/local/lib -Fl/usr/pkg/lib -Fl/usr/pkg/lib -dFPC_USE_LIBC -dx86_64 -dRELEASE  -Us -Sg ../bsd/system.pp
gmake[2]: *** [Makefile:4347: cycle] Error 2
gmake[1]: *** [Makefile:2800: compiler_cycle] Error 2
gmake: *** [Makefile:2832: build-stamp.x86_64-freebsd] Error 2

fpcupdeluxe: ERROR: FPC Native Installer (BuildModule: FPC): Error running /usr/local/bin/gmake for FPC failed with exit code 512
. Details: .

ERROR: Fpcupdeluxe fatal error !
Sequencer (FPC): Failure running fpcupdeluxe: error executing sequence FPC
Sequencer (Default): Failure running fpcupdeluxe: error executing sequence Default

[fpcup.log](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/13835547/fpcup.log)

**Comment by trivthebofh** [comment]
Thank you, yes!. When I built fpc from fixes-3.2 and trunk, along with Lazarus 3.0 it worked perfectly! I appreciate the advice and the great program!

**Comment by LongDirtyAnimAlf** [comment]
Thanks.
