### ISSUE TITLE
Removed Compilers still show when reloaded the tool

### ISSUE THREAD

**Issue by Coldzer0** [LongDirtyAnimAlf/fpcupdeluxe#658]
Hello @LongDirtyAnimAlf 

I removed some of the installed cross compilers I no longer need. 
Then, after restarting the tool, I still can see the cross compilers printed as Found.

And after doing an "update all", it still re-installed all the ones I removed.

**Comment by LongDirtyAnimAlf** [comment]
Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.4.0dp

**Comment by Coldzer0** [comment]
> Please test. https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.4.0dp

I've tested it, But the removed cross-compilers still appear in the list of the installed ones.
And If I do update all, It still reinstalls them.

**Comment by LongDirtyAnimAlf** [comment]
Would you mind sending me your fpc.cfg ?
Thanks.

**Comment by Coldzer0** [comment]
Here it is
[fpc_cfg.zip](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/14075985/fpc_cfg.zip)

**Comment by LongDirtyAnimAlf** [comment]
Thanks. The bugger has been found. Please test (again).
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.4.0dp

**Comment by Coldzer0** [comment]
> Thanks. The bugger has been found. Please test (again). https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.4.0dp

Everything Works fine, thanks.
