### ISSUE TITLE
Cross compiling from linux x86_64 to darwin x86_64

### ISSUE THREAD

**Issue by fredvs** [LongDirtyAnimAlf/fpcupdeluxe#659]
Hello.

I use last fpcupdeluxe version 2.4.0, installing the cross compiler was ok and clang too.

But when trying to compile a test demo with this:

`> /home/fred/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossx64 -Tdarwin test.pas`

 there is that error message: 

`test.pas(533) Error: (9005) Assembler x86_64-darwin-clang not found, switching to external assembling`

Must I install something more?

Thanks

**Comment by fredvs** [comment]
Hello.

OK, I found a solution.
It is to copy the fpc.cfg of fpcupdeluxe into /etc, like this:

`$ sudo cp /home/fred/fpcupdeluxe/fpc/bin/x86_64-linux/fpc.cfg /etc/`

Now it cross-compile like charm.

EXCELLENT and many thanks for that great project.

**Comment by fredvs** [comment]
Hum, nearly all is working.
Assembling is ok but linking not yet:

`ld: file not found: Foundation`

**Comment by fredvs** [comment]
OK, needed to use **-sh** to get the script.
So the steps:

-Compile with **-sh** parameter to get the script **ppas.sh** for the linker.

- Edit **ppas.sh**

- Remove "_-framework AppKit Foundation CoreFoundation_"

- Run the **ppas.sh** script.

The project I want to compile uses _XQuartz_ and for linking _libX11.dylib_ and _fontconfig.dylib_ are needed
So _libX11.dylib_ and _fontconfig.dylib_ were copied into /fpcupdeluxe/cross/lib/all-darwin/.

Here those libraries, maybe it could be good that fpcupdeluxe has those libraries and then apps using XQuartz can be cross-compiled out of the box.
[lib_X11_mac.zip](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/13994274/lib_X11_mac.zip)

About the linker parameter "-framework AppKit Foundation CoreFoundation", is it possible to disable it and not be obliged to edit the script?

Anyway, time to exclamation: WOOOOW, I just have try the cross-compiled binary of MSEide for the Mac and it works,
So BIG congratulation to fpcupdeluxe, you are still in the mood of Big Chimp, with always good stuffs.
Even without install XCode, the binary works!

 
![mse_darwin](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/3421249/55ee2411-31c3-4e62-8af4-5adb76cf08c2)

Many thanks Don.

Fre;D

**Comment by LongDirtyAnimAlf** [comment]
Good.
You might be right about linking with AppKit+Foundation+CoreFoundation.
But I am not 100% sure.
Could you please give me more details about the errors that you encounter with this setup ?
I guess some changes are needed, but I a still not certain about it.

**Comment by fredvs** [comment]
Hello.

When I compile the project without **-sh** parameter, I get that error:

>(9009) Assembling mseide
>ld: file not found: Foundation

Note that the compilation end with  no other error message.
Note too that only "_Foundation_" is noted, not the all "_AppKit Foundation CoreFoundation_", like in the **ppas.sh**.

If I compile the project directly on Mac the compilation + linking is ok.

Note that cross compiling+linking from from _linux x86_64_ to _darwin Aaarch64_, there is exactly the same problem.
But using the **-sh** parameter and editing the script like explained, the cross compilation is OK (**BIG WOW**).

Fre;D

**Comment by fredvs** [comment]
Hello.

Here is the result of **ppas.sh** when compiling a project on a real Mac with **-sh** fpc parameter:

```
...
echo Linking apps/ide/mseide
OFS=$IFS
IFS="
"
/Library/Developer/CommandLineTools/usr/bin/ld       -dead_strip -no_dead_strip_inits_and_terms -x  -order_file symbol_order.fpc -multiply_defined suppress -L. -o apps/ide/mseide `cat link897.res` -filelist linkfiles897.res
if [ $? != 0 ]; then DoExitLink apps/ide/mseide; fi
IFS=$OFS
```

This script produces a working binary.

And here the result of **ppas.sh** when cross-compiling the same project on a  Linux x86_64 machine using _fpcupdeluxe_ with **-sh** parameter:

```
...
echo Linking mseide
OFS=$IFS
IFS="
"
/home/fred/fpcupdeluxe/cross/bin/all-apple/bin/x86_64-apple-darwin19-ld     -framework AppKit Foundation CoreFoundation   -dead_strip -no_dead_strip_inits_and_terms -x  -order_file symbol_order.fpc -multiply_defined suppress -L. -o mseide `cat link17950.res` -filelist linkfiles17950.res
if [ $? != 0 ]; then DoExitLink mseide; fi
IFS=$OFS

```

Here  **-framework AppKit Foundation CoreFoundation** was added and produces a error at linking.

**Comment by LongDirtyAnimAlf** [comment]
Ok. Thanks. I guess its this fpcupdeluxe bugger.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/issues/655
Please test the latest [pre-]release.

https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.4.0c
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.4.0dp

**Comment by fredvs** [comment]
Hello Don.

Ok, cross compiling to _darwin_x84_64_ and _darwin_aarch6_4 is ok now, many thanks.

But, like explained in  https://github.com/LongDirtyAnimAlf/fpcupdeluxe/issues/659#issuecomment-1901091985 I have to copy **libX11.dylib** and **libfontconfig.dylib** into **/fpcupdeluxe/cross/lib/all-darwin**.
Also add this fpc parameter:-**Fl/fpcupdeluxe/cross/lib/all-darwin/** to enable the linking of those libraries.

Many thanks for your wonderful work.

Fre;D

**Comment by LongDirtyAnimAlf** [comment]
What version of the SDK has these libs ?
I can see them in 10.5 and 10.6, but not in 10.13 and newer.
And, if you install X11 on Mac in another way, how do you do this.

**Comment by fredvs** [comment]
>I can see them in 10.5 and 10.6, but not in 10.13 and newer.

I suppose it is not in the newer SDK when **XQuartz** was not installed by default anymore on OSX.

**Comment by LongDirtyAnimAlf** [comment]
Implemented.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/10e722a564c202118fa11f1f5ad648cd606010bb
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/crosslibs_all/Darwin_All_OSXQuartz_1203.zip

Next release.

**Comment by fredvs** [comment]
Fantastic!

Many thanks.

**Comment by fredvs** [comment]
Re-hello.

Your cross-compiler to Darwin is a gem.
So bright that I have a question: is it possible to use your cross-compil libraries directly on a Mac?

I mean be able to compile a Mac application on the Mac but without the obligation to install XCode (that needs lot of gigas and a Mac-user account)?

It would be great for Mac-users ( maybe, I am only a virtual-Mac user).

**Comment by LongDirtyAnimAlf** [comment]
If I am not wrong, "xcode-select –-install" is the only thing you need on Mac to get things going.

https://mac.install.guide/commandlinetools/4.html
https://mac.install.guide/commandlinetools/index.html

**Comment by LongDirtyAnimAlf** [comment]
That is what I meant. If I remember well, with only that command, you can use fpcupdeluxe for crossing on Mac.
You are welcome to try and give feedback.

**Comment by fredvs** [comment]
OK, I will try.

But the magic is that when I did cross-compilation from Linux to Mac, using only fpcupdeluxe, the result-binary is working out-of-the-box on a Mac, without installing anything.

For a not-Mac user like me it is fantastic.
I have to find somebody that has a Mac with the aarch64 arm cpu to see if the crosscompilation gives also a working binary (the cross compilation from Linux x86_64 to Darwin aarch64 was also ok but I did not test it yet on a real machine).

**Comment by LongDirtyAnimAlf** [comment]
Aarch64 will also work flawless.
But you have to "codesign" the binary.
See first fixed issue about this !

**Comment by fredvs** [comment]
>See first fixed issue about this !

Huh, sorry but I dont see it.  Where must I look?

**Comment by LongDirtyAnimAlf** [comment]
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/issues/567

**Comment by fredvs** [comment]
Ha, ok, some joy of the Mac that I have to discover.
OK, noted, thanks.
