### ISSUE TITLE
Error on install crosscompiler from Freebsd-14 to linux X86_64 

### ISSUE THREAD

**Issue by nummer8** [LongDirtyAnimAlf/fpcupdeluxe#660]
Hi,

My system is freebsd-14.
fpcup version : FPCUPdeluxe V2.4.0dp build 490
Install with fpcupdeluxe went fine.
Install to crosscompiler x86_64 -> Windows worked withoud a problem

If I want to install a x86_64 -> Linux crosscompiler I get several errors:
Binarys are not found and can't be downloaded.
Same goes for cross librarys
Download files can't be found.
Could you help me out here?
If there is a description some where that I have't found yet. Can you point me to them.

If you need more information please let me know.
Thanks in advance.

**Comment by LongDirtyAnimAlf** [comment]
I have not build any cross-compilers for FreeBSD. Will see if I can build some today.

**Comment by LongDirtyAnimAlf** [comment]
Please test the new binaries. The should be able to install a cross-compiler for Linux on FreeBSD.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.4.0dp

**Comment by nummer8** [comment]
Tested on a FreeBSD 14.0 version with the fpcupdeluxe-x86_64-freebsd version V2.4.0dp build 490.
Installed crosscompiler CPU: x86_64 OS: Linux 
Works perfectly.
Thanks Don!
