### ISSUE TITLE
Error install - PICO package

### ISSUE THREAD

**Issue by cybersmurf** [LongDirtyAnimAlf/fpcupdeluxe#662]
Windows 32bit version
when i install RPi Pico package i get this errors - install via bottom button

fpcupdeluxe: info: FPC Native Installer (CheckModule: FPC): Checking FPC sources with Git Client.
fpcupdeluxe: Start of compile error summary.
fpcupdeluxe: ERROR: FPC Native Installer (CheckModule: FPC): sources error (URL mismatch).
fpcupdeluxe: Start of compile error summary.
fpcupdeluxe: ERROR: FPC Native Installer (CheckModule: FPC): Desired URL=https://gitlab.com/michael-ring/freepascal-sources/.
fpcupdeluxe: Start of compile error summary.
fpcupdeluxe: ERROR: FPC Native Installer (CheckModule: FPC): Source URL=https://gitlab.com/freepascal.org/fpc/source.git/.

**Comment by LongDirtyAnimAlf** [comment]
Well, the error message shows you the cause.
You try to install a special FPC version over another FPC version.

My advice.
Always install different versions of FPC into different install-directories.

In your case.
Keep the existing install.
Create a new directory and install rPI Pico into this new directory.
If anything goes wrong with your new Pico install, your normal install is not touched and will remain working.

**Comment by ccrause** [comment]
The RP2040 changes have been  merged into FPC (https://gitlab.com/freepascal.org/fpc/source/-/commit/652f21b656cf37ad7cd5c627cf9fece13a86ab8f), so can the Pico installer not simply use latest development branch of FPC?

**Comment by LongDirtyAnimAlf** [comment]
This is good to know !
I will change up to use trunk for pico.
