### ISSUE TITLE
Intallation on Raspberry Pi 5 8Gb  ( X backend enabled)

### ISSUE THREAD

**Issue by otalado** [LongDirtyAnimAlf/fpcupdeluxe#665]
Installation of fpcupdeluxe V2.4.0c fails. As it looks like a library is missing I verified if I installed all required prerequisites on https://wiki.lazarus.freepascal.org/fpcupdeluxe and found no problem there.

**Installation log:**

/home/pi/fpcupdeluxe/fpcsrc/compiler/ppca64 src/fpmkunit.pp  -Fu/home/pi/fpcupdeluxe/fpcsrc/rtl/units/aarch64-linux -FUunits_bs/aarch64-linux -Fu../paszlib/src -Fu../hash/src -Fi../paszlib/src  -Fi../fcl-process/src/unix -Fu../fcl-process/src -Fi../fcl-process/src/linux -Fi../fcl-process/src/dummy -Fu../libtar/src -Sg -vw-n-h-l-d-u-t-p-c-
/home/pi/fpcupdeluxe/fpcsrc/compiler/ppca64 fpmake.pp  -Fu/home/pi/fpcupdeluxe/fpcsrc/packages/fpmkunit/units_bs/aarch64-linux -Fu/home/pi/fpcupdeluxe/fpcsrc/rtl/units/aarch64-linux  -Sg -vw-n-h-l-d-u-t-p-c-
/bin/ld: /home/pi/fpcupdeluxe/fpcsrc/rtl/units/aarch64-linux/cprt0.o: in function `_start':
(.text+0x54): undefined reference to `__libc_csu_init'
/bin/ld: (.text+0x58): undefined reference to `__libc_csu_init'
/bin/ld: (.text+0x5c): undefined reference to `__libc_csu_fini'
/bin/ld: (.text+0x60): undefined reference to `__libc_csu_fini'
make[1]: *** [Makefile:2682: packages_smart] Error 2
make: *** [Makefile:2837: build-stamp.aarch64-linux] Error 2
fpmake.pp(60) Error: Error while linking
fpmake.pp(60) Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted

fpcupdeluxe: ERROR: FPC Native Installer (BuildModule: FPC): Error running /usr/bin/make for FPC failed with exit code 512
. Details: .

ERROR: Fpcupdeluxe fatal error !
Sequencer (FPC): Failure running fpcupdeluxe: error executing sequence FPC

**Comment by LongDirtyAnimAlf** [comment]
Before reporting an issue like this, search the Lazarus forum and the (closed) issues for similar errors.
This will give you a ton of info.
Search for: "libc_csu_fini".
