### ISSUE TITLE
Installation of trunk / trunk works not

### ISSUE THREAD

**Issue by HaraldNieswandt** [LongDirtyAnimAlf/fpcupdeluxe#666]
Hello,
the try to install Fpc trunk with Laz trunk ending with Errors. My first plan was to install FPC & Laz with WebAssembly - ended also with Errors  ...
Best Regards
Harald

![Bildschirmfoto Systeminfo](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/156097283/582508cb-7154-4b84-a63c-4cd9885f85b8)
![Bildschirmfoto vom 2024-02-17 18-21-19](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/156097283/b122ab65-6ca8-4be2-866d-f28c880ae786)

ake[2]: Verzeichnis „/home/harald/Programs/LazFpc_I/lazarus/components/fpdebug“ wird betreten
/home/harald/Programs/LazFpc_I/fpc/bin/x86_64-linux/fpc.sh -MObjFPC -Scghi -O1 -g -gl -l -venibq -vw-h- -vm6058,3057 -Fu. -Fu../../packager/units/x86_64-linux -Fu../lazdebuggers/lazdebuggerintf/lib/x86_64-linux -Fu../lazutils/lib/x86_64-linux -Fu../debuggerintf/lib/x86_64-linux -Fu../freetype/lib/x86_64-linux -Fu../../lcl/units/x86_64-linux -Fu/home/harald/Programs/LazFpc_I/fpcsrc/rtl -FE. -FUlib/x86_64-linux -Cg -Fl/usr/lib/gcc/x86_64-linux-gnu/11 -vw-n-h-l-d-u-t-p-c- -g -gl -dx86_64 fpdebug.pas
(1002) Target OS: Linux for x86-64
(3104) Compiling fpdebug.pas
(3104) Compiling fpdbgclasses.pp
(3104) Compiling fpdbgutil.pp
/home/harald/Programs/LazFpc_I/lazarus/components/fpdebug/fpdbgutil.pp(115,52) Error: (4003) Type identifier expected
/home/harald/Programs/LazFpc_I/lazarus/components/fpdebug/fpdbgutil.pp(115,52) Error: (4009) Class type expected, but got "<erroneous type>"
/home/harald/Programs/LazFpc_I/lazarus/components/fpdebug/fpdbgutil.pp(116,16) Error: (3058) There is no method in an ancestor class to be overridden: "PushItem(const TFpThreadWorkerItem):System.Boolean;"
/home/harald/Programs/LazFpc_I/lazarus/components/fpdebug/fpdbgutil.pp(229,1) Fatal: (10026) There were 3 errors compiling module, stopping
make[2]: *** [Makefile:3435: fpdebug.ppu] Fehler 1
make[1]: *** [Makefile:1910: lazbuildlclpackages] Fehler 2
make: *** [Makefile:3129: lazbuild] Fehler 2
Fatal: (1018) Compilation aborted
Error: /home/harald/Programs/LazFpc_I/fpc/bin/x86_64-linux/ppcx64 returned an error exitcode
make[2]: Verzeichnis „/home/harald/Programs/LazFpc_I/lazarus/components/fpdebug“ wird verlassen
make[1]: Verzeichnis „/home/harald/Programs/LazFpc_I/lazarus/components“ wird verlassen
make: Verzeichnis „/home/harald/Programs/LazFpc_I/lazarus“ wird verlassen
fpcupdeluxe: ERROR: Lazarus Native Installer (BuildModuleCustom: Lazbuild): make returned exit status #512.

ERROR: Fpcupdeluxe fatal error !
Sequencer (UserIDE): Failure running fpcupdeluxe: error executing sequence UserIDE
Sequencer (Lazarus): Failure running fpcupdeluxe: error executing sequence Lazarus
Sequencer (Default): Failure running fpcupdeluxe: error executing sequence Default

**Comment by LongDirtyAnimAlf** [comment]
I guess this is a problem of Lazarus itself. Not related to fpcupdeluxe. Therefor closing.
