### ISSUE TITLE
Icons for ESP, mORMot, Pico, Ultibo and Wio.

### ISSUE THREAD

**Issue by sesvena** [LongDirtyAnimAlf/fpcupdeluxe#672]
Enclosed are the icons for ESP, mORMot, Pico, Ultibo and Wio.
[2024-03-11 fpcupdeluxe-HighDPI.zip](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/14562417/2024-03-11.fpcupdeluxe-HighDPI.zip)

**Comment by LongDirtyAnimAlf** [comment]
Implemented. https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/462950ea58e00f3ef64dbc819ea18a0a505d0a00

However. I am not that happy with the Ultibo icon. Would you mind having a second look at that icon ?
Perhaps you have some better ideas about it than just me, reverting to the original icon.

**Comment by sesvena** [comment]
Hello LongDirtyAnimAlf,

I wanted to create the ultibo icon in size 32x32 to match the other buttenicons.
I also changed the proportions a bit, which may not look quite as good.

Here are four variants of the icon:
Variant 1 is 32x32 pixels in size and has a small white background.
Variant 2 is 32x32 pixels in size and has a large white background.
Variant 3 is 32x32 pixels in size and has no background.
Variant 4 is 88x32 pixels in size and has no background. (corresponds to the original)

I created the icons with the white background because I think they are easier to recognize in a dark theme.

I hope there is something you like.
If you have any change requests, please let me know.

[2024-03-12 ultibo icons.zip](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/14576398/2024-03-12.ultibo.icons.zip)

**Comment by sesvena** [comment]
Hello LongDirtyAnimAlf,

I have reworked the ultibo icons from yesterday and added another variant with a round background.

[2024-03-13 ultibo icons.zip](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/14586299/2024-03-13.ultibo.icons.zip)

**Comment by LongDirtyAnimAlf** [comment]
Thanks for the new icons.
I have used the large icons, without button caption.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/f2641bf0542f4737cf8c1d88effd9eae9376e1ab

**Comment by sesvena** [comment]
Hello LongDirtyAnimAlf,

I noticed that GitLab has a new logo.
Enclosed are the correspondingly adapted icons.
[2024-04-15 GitLab.zip](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/14976038/2024-04-15.GitLab.zip)


Best regards
Roland

**Comment by LongDirtyAnimAlf** [comment]
Implemented.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/29c1f4e1864ef31935c09830b776dcf53d2c6693

**Comment by LongDirtyAnimAlf** [comment]
Thanks !!
