### ISSUE TITLE
Fatal: Can't find unit TTRaster used by EasyLazFreeType

### ISSUE THREAD

**Issue by dxbit** [LongDirtyAnimAlf/fpcupdeluxe#675]
I'm trying to install FPC 3.3.1 and Lazarus 3.2. But in the process it gives an error.

PPU Loading D:\fpcupdeluxe\lazarus\components\freetype\lib\i386-win32\ttraster.ppu
PPU Source: ttraster.pas not found
PPU Source: ttconfig.inc not available
PPU Source: ttraster_sweep.inc not available
Recompiling TTRaster, checksum changed for D:\fpcupdeluxe\lazarus\components\freetype\lib\i386-win32\ttprofile.ppu
Fatal: Can't find unit TTRaster used by EasyLazFreeType
Fatal: Compilation aborted
Error: D:\fpcupdeluxe\fpc\bin\i386-win32\ppc386.exe returned an error exitcode
make: *** [lazbuild] Error 2
fpcupdeluxe: ERROR: Lazarus Native Installer (BuildModuleCustom: Lazbuild): make.exe returned exit status #2.

ERROR: Fpcupdeluxe fatal error !
Sequencer (UserIDE): Failure running fpcupdeluxe: error executing sequence UserIDE
Sequencer (Lazarus): Failure running fpcupdeluxe: error executing sequence Lazarus
Sequencer (Defaultwin32): Failure running fpcupdeluxe: error executing sequence Defaultwin32

**Comment by LongDirtyAnimAlf** [comment]
This is not related to fpcupdeluxe.
FPC 3.3.1 is not [yet] compatible with Lazarus.
