### ISSUE TITLE
Announce: Linux on RISC-V notebook

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#678]
https://www.tomshardware.com/laptops/chinese-startup-launching-risc-v-laptop-for-devs-and-engineers-priced-at-around-dollar300

It would be good to have cross for it, on x64 Linux.

**Comment by overanalytcl** [comment]
I asked for that in #674 and yet the maintainer ignored me :/
But it looks like there's an unwillingness on the part of the FP team itself to provide a RISC-V bootstrap so we could do this ourselves, so we should take this to the official FP Gitlab as well

**Comment by LongDirtyAnimAlf** [comment]
Done.
