### ISSUE TITLE
Cross from Linux x86_64 to Windows aarch64?

### ISSUE THREAD

**Issue by fredvs** [LongDirtyAnimAlf/fpcupdeluxe#681]
Hello.

I try to install the cross compiler from Linux x86_64 to Windows aarch64 but get that error:

![fpcup_aarch64_win](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/3421249/07e9d0b2-8f0c-4c19-9ded-1b2090539fb9)

Did I miss something?

(Maybe fpc for Windows-aarch64 is not yet ready, if so, sorry for the noise.)

**Comment by synopse** [comment]
Perhaps the trunk could do something, but AFAICT this target is not yet available.

There are at least two bounties open for some huge work to make it ready:
https://forum.lazarus.freepascal.org/index.php/topic,66952.15.html

**Comment by fredvs** [comment]
Ha, ok, thanks for the info.

**Comment by fredvs** [comment]
Re-hello.

But in previous version I was able to cross compile to darwin-aarch64...
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/issues/659#issuecomment-1904117166
