### ISSUE TITLE
Lazarus 3.4 was released, please append this version

### ISSUE THREAD

**Issue by tony2u** [LongDirtyAnimAlf/fpcupdeluxe#685]
The Lazarus team was just announced the release of Lazarus 3.4 recently.

**Comment by overanalytcl** [comment]
Or even better, find the Lazarus releases programatically so we wouldn't have to deal with this

**Comment by CharlyTango** [comment]
In such cases of a normal version change, it would be sufficient if we could enter any Lazarus version in the tags tab ourself. This function seems to be intended and prepared, but it does not seem to work. This would significantly reduce the update pressure for fpcupdeluxe

**Comment by LongDirtyAnimAlf** [comment]
You can add an entry in fpcup.ini
However.
I might add a better method.

**Comment by mobius1qwe** [comment]
btw I could install FPC/Laz using fixes branch via fpcup 2.4.0d, seems like the branch fixes you are consulting the repo directly

**Comment by dkounal** [comment]
why tags is always like that? 
![εικόνα](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/37013295/5c1dd412-5858-4d02-9ec6-2d785d625a9e)

**Comment by LongDirtyAnimAlf** [comment]
Done.
