### ISSUE TITLE
Error: /home/h/fpcupdeluxe/cross/bin/arm-linux/arm-linux-gnueabihf-ld.bfd: cannot find -lpangocairo-1.0

### ISSUE THREAD

**Issue by han-k59** [LongDirtyAnimAlf/fpcupdeluxe#686]
Cross compiling under Linux works fine for me but now I tried to compile my second application and I get this link problem at the end of compiling:

Verbose: Linking /home/h/hnsky.fpc/hnsky
Error: /home/h/fpcupdeluxe/cross/bin/arm-linux/arm-linux-gnueabihf-ld.bfd: cannot find -lpangocairo-1.0
hnsky.lpr(81,1) Error: Error while linking

I found a fix at at a Chines webpage I could not translate:
https://www-khcloud-net.translate.goog/?thread-668.htm&_x_tr_sch=http&_x_tr_port=4082&_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=sc

This is the solution:
ln -s /home/h/fpcupdeluxe/cross/lib/arm-linux/libpangocairo-1.0.so.0   /home/h/fpcupdeluxe/cross/lib/arm-linux/libpangocairo-1.0.so
ln -s /home/h/fpcupdeluxe/cross/lib/aarch64-linux/libpangocairo-1.0.so.0   /home/h/fpcupdeluxe/cross/lib/aarch64-linux/libpangocairo-1.0.so
ln -s /home/h/fpcupdeluxe/cross/lib/i386-linux/libpangocairo-1.0.so.0   /home/h/fpcupdeluxe/cross/lib/i386-linux/libpangocairo-1.0.so

**Comment by LongDirtyAnimAlf** [comment]
I have updated the library archives.
Should be solved.
Thanks for reporting.
