### ISSUE TITLE
Replacing with new version will not compile Lazarus - Tag mismatch

### ISSUE THREAD

**Issue by dkounal** [LongDirtyAnimAlf/fpcupdeluxe#689]
I just replaced the executable fpcupdeluxe-x86_64-win64.exe with the new version in an existing directory with compiled fpc+lazarus
I requested to recompile FPC+lazarus from the buttons at the left. 
I got the following error in the image:
![εικόνα](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/37013295/5bfaf8f8-98e3-4eb9-9888-570d07160b86)
Also I have the following issue (lists will never be available) from previous versions that can be linked to this error:
![εικόνα](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/37013295/5ad2f24f-e65f-446e-841f-85b42d4f263f)
Thank you for this excellent work!

**Comment by LongDirtyAnimAlf** [comment]
You need to install in a new, empty directory !
I cannot reproduce your issue with the tags unfortunately.

**Comment by dkounal** [comment]
Is there a way to help?

**Comment by afriess** [comment]
No, i see the same problem here. I think it is more a GIT-Problem or the way of working, how fpcupdeluxe is checking out. 

The old Tag was eg. Lazarus_3_2 and the new Tag is Lazarus_3_4, so the tag-mismatch was triggered. If you check out for a specific Tag (not the whole git with the complete history), it look like, you can not checkout for another Tag.

So inplace upgrades to another Tagversion looks actual not possible with fpcupdeluxe, as Alfred mentions.

**Comment by LongDirtyAnimAlf** [comment]
Regarding the Tags list ?
The tags are fetched from GitLab the moment the Tags-tab is selected. This needs a few seconds. And works well on my own Windows 11 system. I cannot think of a reason that it does not work on your system.

And again, with the current FPC and Lazarus on GitLab, fpcupdeluxe will NOT allow you to change towards another tag (or branch) on an existing install. This has been made possible in earlier versions of fpcupdeluxe, but resulted in many many problems.

**Comment by dkounal** [comment]
Ok thanks a lot then. Thank you again for your time

**Comment by dkounal** [comment]
Concerning tags list, 20 minutes later I do not have a list of tags
