### ISSUE TITLE
how to fix these error:   wrong version of bootstrapper !!  and  Error: Path "./" does not exist

### ISSUE THREAD

**Issue by liu2018** [LongDirtyAnimAlf/fpcupdeluxe#690]
/usr/bin/make revision.inc
/bin/echo "'15785-g15b3f16646'" > revision.inc
fpcupdeluxe: info: FPC Native Installer (BuildModuleCustom: FPC): Using FPC bootstrap compiler with version: 3.3.1.
fpcupdeluxe: info: FPC Native Installer (BuildModuleCustom: FPC): Now building FPC.
fpcupdeluxe: WARNING: FPC Native Installer (BuildModuleCustom: FPC): **Adding OVERRIDEVERSIONCHECK=1 due to wrong version of bootstrapper !!**
fpcupdeluxe: Executing: /usr/bin/make --jobs=8 FPMAKEOPT=--threads=8 PP=/home/lqf/fpcupdeluxe/fpcbootstrap/ppcloongarch64 FPCDIR=/home/lqf/fpcupdeluxe/fpcsrc FPCMAKE=/home/lqf/fpcupdeluxe/fpc/bin/loongarch64-linux/fpcmake PPUMOVE=/home/lqf/fpcupdeluxe/fpc/bin/loongarch64-linux/ppumove PREFIX=/home/lqf/fpcupdeluxe/fpc INSTALL_PREFIX=/home/lqf/fpcupdeluxe/fpc INSTALL_SOURCEDIR=/home/lqf/fpcupdeluxe/fpcsrc INSTALL_BASEDIR=/home/lqf/fpcupdeluxe/fpc/bin/loongarch64-linux INSTALL_UNITDIR=/home/lqf/fpcupdeluxe/fpc/units/loongarch64-linux INSTALL_BINDIR=/home/lqf/fpcupdeluxe/fpc/bin/loongarch64-linux INSTALL_LIBDIR=/home/lqf/fpcupdeluxe/fpc/lib INSTALL_SHAREDDIR=/home/lqf/fpcupdeluxe/fpc/share INSTALL_DATADIR=/home/lqf/fpcupdeluxe/fpc/data INSTALL_DOCDIR=/home/lqf/fpcupdeluxe/fpc/doc INSTALL_EXAMPLEDIR=/home/lqf/fpcupdeluxe/fpc/examples OS_SOURCE=linux CPU_SOURCE=loongarch64 OS_TARGET=linux CPU_TARGET=loongarch64 OVERRIDEVERSIONCHECK=1 OPT=-Sg -vw-n-h-l-d-u-t-p-c- -dREVINC --directory=/home/lqf/fpcupdeluxe/fpcsrc all (working dir: /home/lqf/fpcupdeluxe/fpcsrc)
/usr/bin/make compiler_cycle RELEASE=1
You have overriden the starting compiler versioncheck while using starting compiler version 3.3.1. This situation is not supported and strange things and errors may happen. Remove OVERRIDEVERSIONCHECK=1 to fix this.
/usr/bin/make -C compiler cycle
/usr/bin/make tempclean
/usr/bin/make ppc3
/usr/bin/make 'OLDFPC=' next CYCLELEVEL=1 'COMPILEREXENAME=ppc1'
/usr/bin/make rtlclean
/usr/bin/make -C /home/lqf/fpcupdeluxe/fpcsrc/rtl clean
/usr/bin/make -C linux clean
/usr/bin/make rtl
/usr/bin/make -C /home/lqf/fpcupdeluxe/fpcsrc/rtl 'OPT=-Sg -vw-n-h-l-d-u-t-p-c- -dREVINC' all
/usr/bin/make -C linux all
/home/lqf/fpcupdeluxe/fpcbootstrap/ppcloongarch64 -Ur -Ur -Xs -O2 -n -Fi../inc -Fi../loongarch64 -Fi../unix -Filoongarch64 -FE. -FU/home/lqf/fpcupdeluxe/fpcsrc/rtl/units/loongarch64-linux -Fl/usr/lib/gcc/loongarch64-unknown-linux-gnu/14.0.1 -Sg -vw-n-h-l-d-u-t-p-c- -dREVINC -dloongarch64 -dRELEASE  -Us -Sg system.pp
**Error: Path "./" does not exist**
make[6]: *** [Makefile:2367: linux_all] Error 2
make[5]: *** [Makefile:5486: rtl] Error 2
make[4]: *** [Makefile:5319: next] Error 2
make[3]: *** [Makefile:5325: ppc1] Error 2
make[2]: *** [Makefile:5337: cycle] Error 2
make[1]: *** [Makefile:3256: compiler_cycle] Error 2
make: *** [Makefile:3288: build-stamp.loongarch64-linux] Error 2

fpcupdeluxe: ERROR: FPC Native Installer (BuildModuleCustom: FPC): Error running /usr/bin/make for FPC failed with exit code 512
. Details: .

ERROR: Fpcupdeluxe fatal error !
Sequencer (FPC): Failure running fpcupdeluxe: error executing sequence FPC
Sequencer (Only): Failure running fpcupdeluxe: error executing sequence Only

how to fix these errors:   
Adding OVERRIDEVERSIONCHECK=1 -->how remove this condition:
wrong version of bootstrapper !!  ---> why it would happen?
Error: Path "./" does not exist   --->where file or place  to modify as correct path?

**Comment by LongDirtyAnimAlf** [comment]
Bootstrapper.
When building FPC, a bootstrapper is needed. The FPC makefile describes what versions are allowed. For trunk:
```
REQUIREDVERSION=3.2.2
REQUIREDVERSION2=3.2.0
```
However, loongarch64 is not supported by either 3.2.2 or 3.2.0, so we set the OVERRIDEVERSIONCHECK=1 to allow for a trunk bootstrapper.

Error: Path "./" does not exist
I have no clue about this error. Many changes have gone into trunk. I might try to build a new trunk bootstrapper. Will keep you updated.

**Comment by liu2018** [comment]
> Bootstrapper. When building FPC, a bootstrapper is needed. The FPC makefile describes what versions are allowed. For trunk:
> 
> ```
> REQUIREDVERSION=3.2.2
> REQUIREDVERSION2=3.2.0
> ```
> 
> However, loongarch64 is not supported by either 3.2.2 or 3.2.0, so we set the OVERRIDEVERSIONCHECK=1 to allow for a trunk bootstrapper.
> 
> Error: Path "./" does not exist I have no clue about this error. Many changes have gone into trunk. I might try to build a new trunk bootstrapper. Will keep you updated.

Good answer!,tha make me clear,really really  thankful!

**Comment by LongDirtyAnimAlf** [comment]
I have uploaded a new bootstrapper. It might work better.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/bootstrappers_v1.0/fpcup-3_3_1-loongarch64-linux-ppcloongarch64
