### ISSUE TITLE
FPCUPdeluxe V2.4.0e for x86_64-linux running on Zorin OS Lazarus QT5 cannot find -lQt5Pas: No such file or directory

### ISSUE THREAD

**Issue by AndiB74** [LongDirtyAnimAlf/fpcupdeluxe#691]
FPCUP(deluxe) is starting up.

FPCupdeluxe basedir:       /home/andib/fpcupdeluxe
Bootstrap dir:             /home/andib/fpcupdeluxe/fpcbootstrap

FPC URL:                   https://gitlab.com/freepascal.org/fpc/source
FPC source directory:      /home/andib/fpcupdeluxe/fpcsrc
FPC install directory:     /home/andib/fpcupdeluxe/fpc
FPC options:               

Lazarus URL:               https://gitlab.com/freepascal.org/lazarus/lazarus
Lazarus source directory:  /home/andib/fpcupdeluxe/lazarus
Lazarus install directory: /home/andib/fpcupdeluxe/lazarus
Lazarus options:           -g -gl -O1

Please stand back and enjoy !

8-6-24 19:25:53: fpcupdeluxe: V502 (20240605) started.
FPCUPdeluxe V2.4.0e for x86_64-linux running on Zorin OS
Build with: FPC 3.2.3 on Win11 x86_64

Checking dev-libs for qt5 LCLWidgetType.
Found valid as application.
Found valid gunzip application.
Found valid tar application.
Found valid make application.
fpcupdeluxe: info: FPC Native Installer (CheckModule: FPC): Checking FPC sources with Git Client.
fpcupdeluxe: info: FPC Native Installer (GetModule: FPC): Start checkout/update of FPC sources.
fpcupdeluxe: Executing: /usr/bin/git log -1 --pretty=format:%h (working dir: /home/andib/fpcupdeluxe/fpcsrc)
fpcupdeluxe: Executing: /usr/bin/git describe --tags --long --always (working dir: /home/andib/fpcupdeluxe/fpcsrc)
fpcupdeluxe: Executing: /usr/bin/git log -g -1 --pretty=oneline (working dir: /home/andib/fpcupdeluxe/fpcsrc)
fpcupdeluxe: Executing: /usr/bin/git describe --tags --all --long --always (working dir: /home/andib/fpcupdeluxe/fpcsrc)
fpcupdeluxe: info: FPC Native Installer (GitClient: FPC): Running GIT checkout or update of branch fixes_3_2.
fpcupdeluxe: Executing: /usr/bin/git status --porcelain (working dir: /home/andib/fpcupdeluxe/fpcsrc)
fpcupdeluxe: Executing: /usr/bin/git clone --branch fixes_3_2 https://gitlab.com/freepascal.org/fpc/source.git/ /home/andib/fpcupdeluxe/fpcsrc (working dir: /home/andib/fpcupdeluxe/fpcsrc)
fpcupdeluxe: Executing: /usr/bin/git config --local advice.detachedHead false (working dir: /home/andib/fpcupdeluxe/fpcsrc)
fpcupdeluxe: Executing: /usr/bin/git remote -v (working dir: /home/andib/fpcupdeluxe/fpcsrc)
fpcupdeluxe: Executing: /usr/bin/git rev-parse --abbrev-ref HEAD (working dir: /home/andib/fpcupdeluxe/fpcsrc)
fpcupdeluxe: Executing: /usr/bin/git pull (working dir: /home/andib/fpcupdeluxe/fpcsrc)
fpcupdeluxe: Executing: /usr/bin/git log -1 --pretty=format:%h (working dir: /home/andib/fpcupdeluxe/fpcsrc)
fpcupdeluxe: Executing: /usr/bin/git describe HEAD (working dir: /home/andib/fpcupdeluxe/fpcsrc)
fpcupdeluxe: info: FPC Native Installer (GitClient: FPC): Current commit name: 3.2.3-1389-gece914d007.
fpcupdeluxe: Executing: /usr/bin/git show -s --format=%s%b (working dir: /home/andib/fpcupdeluxe/fpcsrc)
fpcupdeluxe: info: FPC Native Installer (GitClient: FPC): Current commit message: Make sure libressl is loaded correctly. Patch from Zeljko.(cherry picked from commit ab827e233f9c059e561774b74bda151daaaaca8f).
fpcupdeluxe: info: FPC Native Installer (GetModule: FPC): FPC was at revision/hash: FRET_UNKNOWN_REVISION.
fpcupdeluxe: info: FPC Native Installer (GetModule: FPC): FPC is now at revision/hash: ece914d007.
fpcupdeluxe: Executing: /usr/bin/git describe HEAD (working dir: /home/andib/fpcupdeluxe/fpcsrc)
fpcupdeluxe: info: FPC Native Installer (GetModule: FPC): No FPC patches defined.
fpcupdeluxe: info: FPC Native Installer (BuildModule: FPC): Going to build FPC.
fpcupdeluxe: info: FPC Native Installer (BuildModule: FPC): Detected source version FPC (source): 3.2.3.
fpcupdeluxe: info: FPC Native Installer (BuildModule: FPC): To compile this FPC, we need (required) a compiler with version 3.2.0 or 3.2.2.
fpcupdeluxe: info: FPC Native Installer (BuildModule: FPC): FPCUP bootstrapper was not available. Found another one. Going to it: /home/andib/fpcupdeluxe/fpcbootstrap/ppcx64.
fpcupdeluxe: info: FPC Native Installer (BuildModule: FPC): To compile this FPC, we will use the (already available) compiler with version : 3.2.2.
Found valid make application.
Found valid ld application.
fpcupdeluxe: Executing: /usr/bin/make --jobs=16 FPMAKEOPT=--threads=16 PP=/home/andib/fpcupdeluxe/fpcbootstrap/ppcx64 FPCDIR=/home/andib/fpcupdeluxe/fpcsrc FPCMAKE=/home/andib/fpcupdeluxe/fpc/bin/x86_64-linux/fpcmake PPUMOVE=/home/andib/fpcupdeluxe/fpc/bin/x86_64-linux/ppumove PREFIX=/home/andib/fpcupdeluxe/fpc INSTALL_PREFIX=/home/andib/fpcupdeluxe/fpc INSTALL_SOURCEDIR=/home/andib/fpcupdeluxe/fpcsrc INSTALL_BASEDIR=/home/andib/fpcupdeluxe/fpc/bin/x86_64-linux INSTALL_UNITDIR=/home/andib/fpcupdeluxe/fpc/units/x86_64-linux INSTALL_BINDIR=/home/andib/fpcupdeluxe/fpc/bin/x86_64-linux INSTALL_LIBDIR=/home/andib/fpcupdeluxe/fpc/lib INSTALL_SHAREDDIR=/home/andib/fpcupdeluxe/fpc/share INSTALL_DATADIR=/home/andib/fpcupdeluxe/fpc/data INSTALL_DOCDIR=/home/andib/fpcupdeluxe/fpc/doc INSTALL_EXAMPLEDIR=/home/andib/fpcupdeluxe/fpc/examples OS_SOURCE=linux CPU_SOURCE=x86_64 OS_TARGET=linux CPU_TARGET=x86_64 OPT=-Sg -vw-n-h-l-d-u-t-p-c- --directory=/home/andib/fpcupdeluxe/fpcsrc/compiler revision (working dir: /home/andib/fpcupdeluxe/fpcsrc/compiler)
make: Verzeichnis „/home/andib/fpcupdeluxe/fpcsrc/compiler“ wird betreten
/usr/bin/make revision.inc
make[1]: Verzeichnis „/home/andib/fpcupdeluxe/fpcsrc/compiler“ wird betreten
/bin/echo "'1389-gece914d007'" > revision.inc
make[1]: Verzeichnis „/home/andib/fpcupdeluxe/fpcsrc/compiler“ wird verlassen
make: Verzeichnis „/home/andib/fpcupdeluxe/fpcsrc/compiler“ wird verlassen
fpcupdeluxe: info: FPC Native Installer (BuildModuleCustom: FPC): Using FPC bootstrap compiler with version: 3.2.2.
fpcupdeluxe: info: FPC Native Installer (BuildModuleCustom: FPC): Running CleanModule once more, due to previous clean failure.
fpcupdeluxe: info: FPC Native Installer (CleanModule: FPC): Running make distclean twice.
fpcupdeluxe: Executing: /usr/bin/make --jobs=16 FPMAKEOPT=--threads=16 --directory=/home/andib/fpcupdeluxe/fpcsrc FPC=/home/andib/fpcupdeluxe/fpcbootstrap/ppcx64 FPCMAKE=/home/andib/fpcupdeluxe/fpc/bin/x86_64-linux/fpcmake PPUMOVE=/home/andib/fpcupdeluxe/fpc/bin/x86_64-linux/ppumove FPCDIR=/home/andib/fpcupdeluxe/fpcsrc PREFIX=/home/andib/fpcupdeluxe/fpc INSTALL_PREFIX=/home/andib/fpcupdeluxe/fpc CPU_SOURCE=x86_64 OS_SOURCE=linux CPU_TARGET=x86_64 OS_TARGET=linux distclean (working dir: /home/andib/fpcupdeluxe/fpcsrc)
make: Verzeichnis „/home/andib/fpcupdeluxe/fpcsrc“ wird betreten
/usr/bin/make -C compiler distclean
make[1]: Verzeichnis „/home/andib/fpcupdeluxe/fpcsrc/compiler“ wird betreten
/usr/bin/make -C utils cleanall
make[2]: Verzeichnis „/home/andib/fpcupdeluxe/fpcsrc/compiler/utils“ wird betreten
make[2]: Verzeichnis „/home/andib/fpcupdeluxe/fpcsrc/compiler/utils“ wird verlassen
/usr/bin/make -C utils distclean
make[2]: Verzeichnis „/home/andib/fpcupdeluxe/fpcsrc/compiler/utils“ wird betreten
make[2]: Verzeichnis „/home/andib/fpcupdeluxe/fpcsrc/compiler/utils“ wird verlassen
make[1]: Verzeichnis „/home/andib/fpcupdeluxe/fpcsrc/compiler“ wird verlassen
/usr/bin/make -C rtl distclean
.
.
.
.
(9015) Linking ../lazarus
/usr/bin/ld: cannot find -lQt5Pas: No such file or directory
make[1]: *** [Makefile:4801: ide] Error 2
make: *** [Makefile:3116: ide] Error 2
/home/andib/fpcupdeluxe/lazarus/ide/lazarus.pp(171,1) Error: (9013) Error while linking
/home/andib/fpcupdeluxe/lazarus/ide/lazarus.pp(171,1) Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted

**Comment by rcla** [comment]
If you want to run Lazarus with Qt5, you need to install "libqt5pas" and "libqt5pas-dev" on Zorin OS to develop applications.

In this [repository](https://github.com/davidbannon/libqt5pas) from Davo @davidbannon, he explains in detail if you need a more current version of those libraries.

[Download v1.2.15](https://github.com/davidbannon/libqt5pas/releases/tag/v1.2.15)

If you need them and want to install:
`sudo apt install ./libqt5pas1_2.15-1_amd64.deb ./libqt5pas-dev_2.15-1_amd64.deb`

**Comment by LongDirtyAnimAlf** [comment]
See comment by @rcla
Thanks for your help.
