### ISSUE TITLE
Missing files..

### ISSUE THREAD

**Issue by FezaCakir** [LongDirtyAnimAlf/fpcupdeluxe#693]
at the first step:
1) there is no "secrets.inc" in project folders.
2) mormotdatamodelclient.pas(17,3) Error: unit not found: SynCrossPlatformJSON

Debian GNU/Linux+Lazarus

**Comment by LongDirtyAnimAlf** [comment]
Should be fixed by this commit.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/f43e73fdc1af3d59e8df4f05d96b261e1a29cfdb

Ps.
Please create an empty secret.inc yourself for testing.
