### ISSUE TITLE
How to build Lazarus in a minimal IDE?

### ISSUE THREAD

**Issue by dxbit** [LongDirtyAnimAlf/fpcupdeluxe#699]
I'm trying to build FPC 3.3.1 and Lazarus 3.4. The FPC is build, but Lazarus is not. Errors appear. I found out that Lazarus is builds in a minimal configuration using command make without parameters. Is it possible to somehow specify in the fpcupdeluxe itself that Lazarus is builds in a minimal configuration? Without bigide.

**Comment by LongDirtyAnimAlf** [comment]
Lazarus is already build in a minimal config. After a successfull build, some packages are added.
