### ISSUE TITLE
Access Violation on Mac

### ISSUE THREAD

**Issue by Sod-Almighty** [LongDirtyAnimAlf/fpcupdeluxe#701]
I run `fpcupdeluxe-x86_64-darwin-cocoa` on my Intel-based Mac running Monterey 12.6.4, and I get an access violation. If I allow it to continue anyway, I get the FUD GUI, but nothing listed and no way to proceed.

![Downloads Finder, Today at 9 43 41 am](https://github.com/user-attachments/assets/05f88a0c-0934-4ab5-bea6-3cc33b86e7ba)

![FPCUPdeluxe V2 4 0e for x86_64-darwin-cocoa fpcupdeluxe, Today at 9 45 34 am](https://github.com/user-attachments/assets/479d7dc9-97df-4498-9c50-bf8e057b11ec)

**Comment by LongDirtyAnimAlf** [comment]
I guess you are running fpcupdeluxe from a privileged folder like the Downloads folder.
This will result in the mentioned error.
Make a new folder in your home-directory. Copy fpcupdeluxe ito it. Run it. That should do it.

**Comment by Sod-Almighty** [comment]
That fixed it, thanks.

Might be helpful if the software could detect this situation and pop up an explanatory dialog. Or alternatively, I believe there are ways to request the necessary access from the OS, which prompts the user for permission.

**Comment by LongDirtyAnimAlf** [comment]
Thanks for the feedback.
Fpcupdeluxe should show a warning in the green command screen when run from a privileged folder.
