### ISSUE TITLE
Error installing FPC and Lazarus on Windows 11   

### ISSUE THREAD

**Issue by Dinarisch** [LongDirtyAnimAlf/fpcupdeluxe#703]
Hello. I'm getting this error when I'm installing FPC and Lazarus on Windows 11 (Win64):

info: FPC Native Installer (CleanModule: FPC): Running  distclean failed: could not find cleanup compiler. Will try again later.
info: FPC Native Installer (CheckModule: FPC): Checking FPC sources with Git Client.
info: FPC Native Installer (GetModule: FPC): Start checkout/update of FPC sources.
info: FPC Native Installer (GitClient: FPC): Running GIT checkout or update of branch main.
info: FPC Native Installer (GitClient: FPC): Current commit name: 3.3.1-16149-g780c1f9c49.
info: FPC Native Installer (GitClient: FPC): Current commit message: Reduce number of warnings and hints.
info: FPC: WARNING: found modified files.
info: FPC Native Installer (GetModule: FPC): FPC is at revision/hash: 780c1f9c49.
info: FPC Native Installer (GetModule: FPC): No updates for FPC found.
info: FPC Native Installer (GetModule: FPC): No FPC patches defined.
info: FPC Native Installer (BuildModule: FPC): Going to build FPC.
info: FPC Native Installer (BuildModule: FPC): Detected source version FPC (source): 3.3.1.
info: FPC Native Installer (BuildModule: FPC): To compile this FPC, we need (required) a compiler with version 3.2.0 or 3.2.2.
info: FPC Native Installer (BuildModule: FPC): FPCUP bootstrapper was not available. Found another one. Going to it: C:\Program Files\fpc\bin\i386-Win32\fpc.exe.
info: FPC Native Installer (BuildModule: FPC): To compile this FPC, we will use the (already available) compiler with version : 3.2.2.
info: FPC Native Installer (BuildModuleCustom: RevisionFPC): Adding -dFPC_SOFT_FPUX80 to compiler option to enable 80bit (soft)float support (trunk only).
info: FPC Native Installer (BuildModuleCustom: FPC): Using FPC bootstrap compiler with version: 3.2.2.
info: FPC Native Installer (BuildModuleCustom: FPC): Running CleanModule once more, due to previous clean failure.
info: FPC Native Installer (CleanModule: FPC): Running make distclean twice.
info: FPC Native Installer (CleanModule: FPC): Removal of stale build files and directories for x86_64-win64. May take a while.
info: FPC Native Installer (BuildModule: FPC): Now building FPC.
info: FPC Native Installer (BuildModule: FPC): Adding -dFPC_SOFT_FPUX80 to compiler option to enable 80bit (soft)float support (trunk only).
Start of compile error summary.
system.inc(177,4) Fatal: Cannot open include file "i386.inc"
C:/PROGRA~1/fpc/bin/I386-W~1/fpc.exe -Ur -Xs -O2 -n -Fi../inc -Fi../x86_64 -Fix86_64 -Fi../x86_64 -Fi../win/wininc -FE. -FUC:/Lazarus_fpc/fpcsrc/rtl/units/x86_64-win64 -vw-n-h-l-d-u-t-p-c- -g -gl -O- -dREVINC -dFPC_SOFT_FPUX80 -dx86_64 -dRELEASE -Fi../win -Us -Sg system.pp
Start of compile error summary.
Fatal: Compilation aborted
system.inc(177,4) Fatal: Cannot open include file "i386.inc"
Start of compile error summary.
Error: C:\PROGRA~1\fpc\bin\I386-W~1\ppc386.exe returned an error exitcode
Start of compile error summary.
ERROR: FPC Native Installer (BuildModule: FPC): Error running C:\Lazarus_fpc\fpcbootstrap\make.exe for FPC failed with exit code 2
. Details: .
fpcupdeluxe: Done !!

Image Error:
![Error](https://github.com/user-attachments/assets/f64a3b3a-d7f5-483b-9307-953fe8578639)

**Comment by LongDirtyAnimAlf** [comment]
This seems to be a GIT checkout error, due to unknown cause.
Please delete the fpcsrc directory and run fpcupdeluxe again.
