### ISSUE TITLE
Schrödinger's lazbuild on macOS Sonoma

### ISSUE THREAD

**Issue by dertuxmalwieder** [LongDirtyAnimAlf/fpcupdeluxe#704]
This problem did not exist a few months ago just yet, so I presume that something has changed (using 2.4.0e): The Lazarus installation fails, these are the last lines.

```
Found valid lazbuild application.
fpcupdeluxe: info: Lazarus Native Installer (BuildModuleCustom: UserIDE): Now building UserIDE.
fpcupdeluxe: ERROR: Lazarus Native Installer (BuildModuleCustom: UserIDE): Lazbuild could not be found, so cannot build USERIDE.


ERROR: Fpcupdeluxe fatal error !
Sequencer (UserIDE): Failure running fpcupdeluxe: error executing sequence UserIDE
Sequencer (Lazarus): Failure running fpcupdeluxe: error executing sequence Lazarus
Sequencer (Default): Failure running fpcupdeluxe: error executing sequence Default
``` 

How could lazbuild be found and not found at the same time?

*edit:* Deleting the previous version of Lazarus (from March-or-so) manually fixes the problem. I would have thought that `fpcupdeluxe` cleans up itself?

**Comment by LongDirtyAnimAlf** [comment]
This is a nice cat(ch) !!
;-)
I have changed the second lazbuild error message.
However.
I am in the (quantum) dark about the cause of this issue.
