### ISSUE TITLE
Raspberry Pi splash screen

### ISSUE THREAD

**Issue by ertankucukoglu** [LongDirtyAnimAlf/fpcupdeluxe#707]
Hello,

Recent versions of Raspberry Pi seems to add a splash window for the X applications.
After running fpxupdeluxe that window is displayed and only after a while it auto closes itself and fpcupdeluxe main window is displayed.
If user manually close that splash window, fpcupdeluxe instantly displays itself.
It would be great if fpcupdeluxe can dismiss that splash screen when running Raspberry Pi.

Please check the attached video for better understanding. Video is recorded on Linux raspberrypi 6.6.31+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux

Thanks & Regards,
Ertan

https://github.com/user-attachments/assets/5e541a23-66fc-4909-8c2b-fc64cd6be594

**Comment by LongDirtyAnimAlf** [comment]
For user I understand that this is unwanted.
I will try to reproduce and fix it.

**Comment by LongDirtyAnimAlf** [comment]
I saw that you posted this issue on the Lazarus mailing list also. And that you mention that the Lazarurus IDE itself suffers also from it.
That means it in not an fpcupdeluxe specific issue. So, I will close.
However. Recent RPi distro's use Wayland as default windows manager. Wayland causes troubles with Lazarus and Lazarus build apps.
Use "sudo raspi-config" to switch from Wayland to X. That might solve this issue.
