### ISSUE TITLE
Lazarus Release 3.6

### ISSUE THREAD

**Issue by tony2u** [LongDirtyAnimAlf/fpcupdeluxe#708]
This is a bugfix release and was built with FPC 3.2.2.
Please add the v3.6 to fpcupdeluxe.

**Comment by mdalacu** [comment]
Yes, we are all waiting for an update on your great app in order to be able to install v3.6!
Thank you!

**Comment by TB1234** [comment]
Here is a fix: https://www.lazarusforum.de/viewtopic.php?f=9&t=16202&hilit=fpcup

**Comment by LongDirtyAnimAlf** [comment]
Fixed with latest release.
