### ISSUE TITLE
Add Russian language

### ISSUE THREAD

**Issue by AndrewKusov** [LongDirtyAnimAlf/fpcupdeluxe#712]
I have created a Russian localization for fpcupdeluxe, you can add it
[fpcupdeluxe.ru.txt](https://github.com/user-attachments/files/17345110/fpcupdeluxe.ru.txt)

**Comment by LongDirtyAnimAlf** [comment]
Implemented.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/6dc8658866c7281fc06adc0ae5515a18a22d7015
Next release.
Thanks !!
