### ISSUE TITLE
lazarus windows version qt5-qt6 install?

### ISSUE THREAD

**Issue by qwer0123456** [LongDirtyAnimAlf/fpcupdeluxe#713]
lazarus windows version qt5-qt6 install guide?
(windows qt , no Linux)

Is this file possible to install Lazarus QT5-QT6 Windows version?

**Comment by LongDirtyAnimAlf** [comment]
There is no QT5/6 install for Windows. And this will also not be implemented due to limited use.
Naturally, you can compile towards QT5/6 on Windows.
