### ISSUE TITLE
Error in Lazarus when crosscompiling to aarch64 Linux on Linux 

### ISSUE THREAD

**Issue by KeesBleijenberg** [LongDirtyAnimAlf/fpcupdeluxe#717]
On Linux Mint I've installed the 64 bits versions of fpcupdeluxe and lazarus. Lazarus works fine.
I want to cross compile code for a Raspberry PI 4B. In fpcupdeluxe I installed the cross compiler for aarch64 on linux. No errors in fpcupdeluxe.
But in Lazarus when I chose OS = Linux and target CPU family = aarch64 I get 
Compiler "/media/WDBlack/fpc_lazarus/fpc/bin/x86_64-linux/fpc.sh" does not support target aarch64-linux
When I start fpcupDeLuxe it says: Found crosscompiler for  aarch64-linux
What is wrong?

Versions:
Lazarus 3.2
fpc  3.2.2
revision: lazarus_3_2
FpcUpDeluxe:  V2.4.0.d Linux-86_64-gtk2, fpc 3.2.3

**Comment by LongDirtyAnimAlf** [comment]
This is a strange error.  Would you mind posting your fpc.cfg file ?

**Comment by magorium** [comment]
@KeesBleijenberg
Can you put the text of that config file between 3 backticks (3 ticks before and 3 ticks after) ?

Right now, the software now interprets the configuration as markup text.

I've tried quoting but the editor seems to combine lines (so that the output still stays invalid for a fpc.cfg file)

**Comment by magorium** [comment]
@KeesBleijenberg 
If you write "Remaining files everywhere" then that can only mean one thing and that there is something else at play.

FPCUpDeluxe does not scatter files around. It stores everything contained inside a single directory (of your choice) (*).

That means that there shouldn't be any Lazarus configuration and/or FPC configuration files (or any other files for that matter) around in your system.

(*) unless specifically told or have done a manual rebuild of either FPC/Lazarus and used custom options to build them.

**Comment by KeesBleijenberg** [comment]
a while ago I installed Lazarus and tried to install 2 cross compilers. That did not work. So I uninstalled lazarus and cross compilers. At least, I tried to uninstall. But that's not so easy..... the "Remaining files everywhere".
After cleaning up I installed fpcupdeluxe, In fpcupdeluxe I installed lazarus and the cross compilers.
I'am not totally sure, but I think aarch64 did work, but not any more.

**Comment by LongDirtyAnimAlf** [comment]
You could try to use the command "Rescan FPC Source Directory" in the Lazarus tools directory. That helps often !

**Comment by KeesBleijenberg** [comment]
'Rescan FPC source Directory' works! I'am quit sure I already tried this a few times without success. 
Anyway, problem solved. Thanks.

**Comment by LongDirtyAnimAlf** [comment]
Thanks for reporting back !
