### ISSUE TITLE
Dialog box text cropped

### ISSUE THREAD

**Issue by JonnyTech** [LongDirtyAnimAlf/fpcupdeluxe#718]
Test is cropped in dialog box after selecting install

https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/v2.4.0e/fpcupdeluxe-x86_64-linux-qt5

![image](https://github.com/user-attachments/assets/d78b1339-bfb4-4320-9765-b7546379e329)

**Comment by LongDirtyAnimAlf** [comment]
Nothing fpcupdeluxe can do about this. Its a standard Lazarus MessageBox. So, this is a Lazarus issue.
