### ISSUE TITLE
Hot to install multiple LCL Widgetsets?

### ISSUE THREAD

**Issue by JonnyTech** [LongDirtyAnimAlf/fpcupdeluxe#719]
If I install using fpcupdeluxe-x86_64-linux then Lazarus with compile only GTK2 executables.

If I install using fpcupdeluxe-x86_64-linux-qt5 then Lazarus with compile only QT5 executables.

Is there a way to install such that fpcupdeluxe will install both LCL widgetsets automatically?

Currently, one has to:

Start Lazarus
Menu: Project >> Project Options...
Side tree: Project Options >> Additions and Overrides
Dropdown: Set "LCLWidgetType" >> Value "gtk2" or "qt5"
Unselect the value that is not required
Side tree: Project Options >> Config and Target
Check that "Current LCL widgetset" is correct
Rebuild project

The same if I need to build for win32/64 too. I know that it only had to be done once, but it is an inconvenience that I always forget when reinstalling.

**Comment by LongDirtyAnimAlf** [comment]
One thing is for sure. After installing the normal gtk2 version of Lazarus, you will be able to compile also for QT5/QT6 !
So, please show me the error when doing just that. Thanks.

**Comment by JonnyTech** [comment]
There was no error, just my misunderstanding. I thought that by installing a cross compiler then I could immediately compile for that platform and widgetset. But it seems like I have to run Lazarus and build once from there before I can compile manually. I write the code from a text editor and compile from terminal so never use Lazarus as an IDE. Thanks for your reply.
