### ISSUE TITLE
Building qt6-only Lazarus

### ISSUE THREAD

**Issue by Hendi48** [LongDirtyAnimAlf/fpcupdeluxe#723]
Hi,

my Linux system does not have gdk-x11-2.0/gtk-x11-2.0 and I'd rather not install them. I downloaded the `x86_64-linux-qt6` variant of fpcupdeluxe in the hopes that I'd get a qt6 Lazarus, but it doesn't seem to be the case.

I'm seeing `-dlclgtk2` in various command lines and it generally tries to base everything on gtk2 when I look at the unit paths. Is there a way to force a build with `LCL_PLATFORM=qt6`? I see a bunch of references to that variable in the source, but no way to set it in the GUI.

**Comment by LongDirtyAnimAlf** [comment]
Lots of bugger regarding qt6.
I hope to have fixed all of them.
Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/v2.4.0fp/fpcupdeluxe-x86_64-linux-qt6.zip

**Comment by Hendi48** [comment]
> Lots of bugger regarding qt6. I hope to have fixed all of them. Please test. https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/v2.4.0fp/fpcupdeluxe-x86_64-linux-qt6.zip

Nice, that one is working fine for me :+1: 

Thank you!
