### ISSUE TITLE
Ubuntu 22 x64 - buttons overlap in the right-lower corner

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#726]
![Screenshot from 2024-12-28 10-10-55](https://github.com/user-attachments/assets/557380c9-e3d6-4571-8dfa-43a174d01cbb)

**Comment by LongDirtyAnimAlf** [comment]
Done.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/ec8c061a475a612ef02e9bd43432a0e0b1674bdc
