### ISSUE TITLE
Small fixes for Russian localization

### ISSUE THREAD

**Issue by AndrewKusov** [LongDirtyAnimAlf/fpcupdeluxe#728]
[fpcupdeluxe.ru.po.txt](https://github.com/user-attachments/files/18274657/fpcupdeluxe.ru.po.txt)

**Comment by LongDirtyAnimAlf** [comment]
Thanks !
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/commit/53a58eb8aa1f34040f0d8caf170b8b0d85457610
