### ISSUE TITLE
Put FPCUpdate into Chocolatey

### ISSUE THREAD

**Issue by turric4n** [LongDirtyAnimAlf/fpcupdeluxe#73]
Most of FPCUpdate project are Windows users. We can put this project into Chocolatey package manager.

**Comment by LongDirtyAnimAlf** [comment]
You're welcome to implement.
I have never used this !

**Comment by turric4n** [comment]
Ok, I will begin asap :)

**Comment by mdbs99** [comment]
@turric4n do you have any news about it? Thanks.

**Comment by mdbs99** [comment]
I discovered today that Lazarus is already there -> https://chocolatey.org/packages/lazarus

**Comment by LongDirtyAnimAlf** [comment]
Thanks.
