### ISSUE TITLE
Added building of native cross-compiler when building on Windows

### ISSUE THREAD

**Issue by mdbs99** [LongDirtyAnimAlf/fpcupdeluxe#76]
In the release [1.6.2d](https://github.com/newpascal/fpcupdeluxe/releases/tag/1.6.2d), was wrote this:
> Added building of native cross-compiler when building on Windows.

We already had this so, what are the differences?

**Comment by LongDirtyAnimAlf** [comment]
There were some deep problems with the make-files of FPC (and Lazarus). These problems became visible on Darwin and other Unixes, causing problems with other installs on these systems.
Some other problems were masked by the fact that it was presumed that FPC could be found in the path.
Some other problems were solved (masked)  by adding extra paths when building and using FPC (and Lazarus).

The above meant that the whole process of building cross-compilers has to be split-up in distinct (make-)parts, each with their own settings. Previous it was just a single "make all crossinstall".
Release 1.6.2b and 1.6.2c had the building of a native compiler disabled in these separate steps.
Release 1.6.2d and newer will build these native compilers again, to allow me to generate native bootstrappers on my windows system !

**Comment by mdbs99** [comment]
This new way of installation setting on Windows will impact, in some how, the previous installations of cross-compilers that used old versions than `1.6.2d`? I mean, when I will update my environment, by just clicking on Update button, may I can have some issues because the installation was different than the new one?
And what about updating the fpcupdeluxe itself and clicking on Update, it will be smart enough to update things, being transparent for the user?

Thanks

**Comment by LongDirtyAnimAlf** [comment]
If all goes well as planned by me, the functionality of fpcupdeluxe will remain 100% the same.
However, there is always a chance to stumble upon a regression.
But be assured: I need fpcupdeluxe myself.

**Comment by mdbs99** [comment]
Ok, thanks. 
If you agree, let's keep this ticket open until you/we are done updating fpc/lazarus/fpcupdeluxe for Windows without any issues or until you're sure about those possible regression. Otherwise, let's go post here.

/cc @synopse

**Comment by LongDirtyAnimAlf** [comment]
Agreed.

**Comment by mdbs99** [comment]
@LongDirtyAnimAlf any news about this issue?

**Comment by LongDirtyAnimAlf** [comment]
At the moment, all looks good !!

**Comment by mdbs99** [comment]
@LongDirtyAnimAlf I already used the newer version to install/update on Windows and everything worked properly. We can close this issue or are you continue testing?

**Comment by LongDirtyAnimAlf** [comment]
We can close I suppose !
