### ISSUE TITLE
could not convert variant Errror

### ISSUE THREAD

**Issue by sstvmaster** [LongDirtyAnimAlf/fpcupdeluxe#78]
Hi with v1.6.2f i got this error message on startup:

"Could not convert variant of (Null) into type (String)"

OS Win7 x64 / fpcupdeluxe 1.6.2f win32

Maik

**Comment by mdbs99** [comment]
I can confirm, same here.
v1.6.2c I386-win32

**Comment by LongDirtyAnimAlf** [comment]
Would you mind trying the new pre-release ?
Thanks.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.2g-pre

**Comment by sstvmaster** [comment]
Hi Don, works! It was the update check, right?
