### ISSUE TITLE
trend micro scan

### ISSUE THREAD

**Issue by mehmetulukaya** [LongDirtyAnimAlf/fpcupdeluxe#80]
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/blob/17c35db0fafa224d96cf1da5f1a45f9f1eae768b/installercore.pas#L1798

Hello trend micro scan blocking this link : http://www.magsys.co.uk/download/software/openssl-1.0.2o-win32.zip

Is there any alternative method?

Log:

FPCUPdeluxe V1.6.2g for i386-win32-win32

FPCUP(deluxe) is starting up.

Binutils/make dir:     D:\lazarus_trunk\fpcbootstrap
Bootstrap dir:         D:\lazarus_trunk\fpcbootstrap
FPC URL:               https://github.com/graemeg/freepascal.git
FPC options:           
FPC source directory:  D:\lazarus_trunk\fpcsrc
FPC install directory: D:\lazarus_trunk\fpc
Lazarus URL:           https://github.com/graemeg/lazarus.git
Lazarus options:       
Lazarus directory:     D:\lazarus_trunk\lazarus

Please stand back and enjoy !

fpcupdeluxe: info: 6.12.2018 17:29:06: fpcupdeluxe: V067 (20181114) started.
fpcupdeluxe: info: Windows major version: 10
fpcupdeluxe: info: Windows minor version: 0
fpcupdeluxe: info: Windows build number:  17134
fpcupdeluxe: WARNING: FPCNativeInstaller (CheckAndGetTools): OpenSLL library files have wrong CPU signature.
fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Getting correct OpenSLL library files.
fpcupdeluxe: WARNING: FPCNativeInstaller (DownloadOpenSSL): No OpenSLL library files available for SSL. Going to download them
fpcupdeluxe: info: FPCNativeInstaller (GetFile): Downloading https://indy.fulgan.com/SSL/openssl-1.0.2p-i386-win32.zip
fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2p-i386-win32.zip from https://indy.fulgan.com/SSL/
fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2p-i386-win32.zip from https://indy.fulgan.com/SSL/
fpcupdeluxe: info: FPCNativeInstaller (GetFile): Could not download file with URL https://indy.fulgan.com/SSL/openssl-1.0.2p-i386-win32.zip into C:\Users\xxx\AppData\Local\Temp (filename: FPCUPTMP00009.zip)
fpcupdeluxe: info: FPCNativeInstaller (GetFile): Downloading https://indy.fulgan.com/SSL/openssl-1.0.2p-i386-win32.zip
fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2p-i386-win32.zip from https://indy.fulgan.com/SSL/
fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2p-i386-win32.zip from https://indy.fulgan.com/SSL/
fpcupdeluxe: info: FPCNativeInstaller (GetFile): Could not download file with URL https://indy.fulgan.com/SSL/openssl-1.0.2p-i386-win32.zip into C:\Users\xxx\AppData\Local\Temp (filename: FPCUPTMP00009.zip)
fpcupdeluxe: info: FPCNativeInstaller (GetFile): Downloading http://wiki.overbyte.eu/arch/openssl-1.0.2p-win32.zip
fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2p-win32.zip from http://wiki.overbyte.eu/arch/
fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2p-win32.zip from http://wiki.overbyte.eu/arch/
fpcupdeluxe: info: FPCNativeInstaller (GetFile): Could not download file with URL http://wiki.overbyte.eu/arch/openssl-1.0.2p-win32.zip into C:\Users\xxx\AppData\Local\Temp (filename: FPCUPTMP00009.zip)
fpcupdeluxe: info: FPCNativeInstaller (GetFile): Downloading http://wiki.overbyte.eu/arch/openssl-1.0.2p-win32.zip
fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2p-win32.zip from http://wiki.overbyte.eu/arch/
fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2p-win32.zip from http://wiki.overbyte.eu/arch/
fpcupdeluxe: info: FPCNativeInstaller (GetFile): Could not download file with URL http://wiki.overbyte.eu/arch/openssl-1.0.2p-win32.zip into C:\Users\xxx\AppData\Local\Temp (filename: FPCUPTMP00009.zip)
fpcupdeluxe: info: FPCNativeInstaller (GetFile): Downloading http://www.magsys.co.uk/download/software/openssl-1.0.2o-win32.zip
fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2o-win32.zip from http://www.magsys.co.uk/download/software/
fpcupdeluxe: info: TNormalUnzipper: Going to extract files from C:\Users\xxx\AppData\Local\Temp\FPCUPTMP00009.zip into C:\Users\xxx\Downloads\fpcupdeluxe\

**Comment by LongDirtyAnimAlf** [comment]
Please try the latest release. It could solve this issue.
