### ISSUE TITLE
"No valid CPU / OS crosscompiler found" when trying to install i386 android

### ISSUE THREAD

**Issue by c600g** [LongDirtyAnimAlf/fpcupdeluxe#81]
I am using fpcupdeluxe 1.6.2g on x86_64 linux, and have successfully installed fpc and lazarus stable. I've also installed the arm-android cross compiler, and am looking to do the same for i386-android. However, when I select this combination, I am given the "No valid CPU / OS crosscompiler found" error message.

**Comment by LongDirtyAnimAlf** [comment]
Solved in latest release.
