### ISSUE TITLE
Paths with blank space don't work.

### ISSUE THREAD

**Issue by yanndias** [LongDirtyAnimAlf/fpcupdeluxe#83]
If I use "/home/xxx/Lazarus IDE" on path, it don't work. I needed to rename my directory. Well... It's not a problem, but I think everything should work fine... thanks!

**Comment by Raincode** [comment]
Is there a way to add double quotes around the path before passing it to svn?

**Comment by LongDirtyAnimAlf** [comment]
I have tried everything, but to no avail !

**Comment by LongDirtyAnimAlf** [comment]
Closing as cannot be resolved.
