### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by Raincode** [LongDirtyAnimAlf/fpcupdeluxe#85]
Hello,

first off I wan't to say I really can see how much love is put into this tool, it's very nice!

I have a few ideas for improvement to speed up the installation procedure:
- Use multithreading to compile. Not sure if make -j Option works with fpc as well, it should have make spawn multiple processes at once (so on a 6 Thread 12 Core CPU, I can compile say 10 .pas units concurrently).
- Start compiling FPC/Lazarus once one is downloaded and the other is still being checked out (not sure if this is done already).
- Bonus Feature Request: ProgressBar (e. g. for downloads)

Cheers and thank's for the tool!

**Comment by LongDirtyAnimAlf** [comment]
I second your feature requests !
However, fpcupdeluxe is based on fpcup, a command line tool designed and maintained by the original author (BigChimp, he passed away).
This limits the possibilities to add advanced features. Extra features could require massive code rewrites.
About multi-threading: this sometimes gives errors, so it can be disabled, but should be enabled by default (not for cross-compilers: this certainly gives errors).
