### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by lpvm** [LongDirtyAnimAlf/fpcupdeluxe#87]
There are the pre-requisites, other information, but how to run this in Linux?

**Comment by cpicanco** [comment]
Yes, you may need to install some dependencies on linux machines. Please,
take a look at the README file.

**Comment by lpvm** [comment]
I've read the README, but can't find info on how to use this.  Never installed fpc or Lazarus before.  After cloning this repo, what should I do?  Is it written somewhere?

**Comment by cpicanco** [comment]
Please, take a look at the README file. Carefully.

![screenshot_2019-01-12_13-48-09](https://user-images.githubusercontent.com/6511849/51075964-49654580-1671-11e9-86e3-7c57e162c1ff.png)

**Comment by lpvm** [comment]
Maybe I'm at the wrong place.
I've read that this is a GUI tool to automate installation of Lazarus and FPC.
Those are the requirements.  I think I have all of them.
And next?

**Comment by cpicanco** [comment]
Sorry @lpvm , please, don't get me wrong. You are at the right place. Maybe we are in front of some communication issue here. I thought you were looking for dependencies for the executable to run under linux. If you are looking for step-by-step instructions on how to use the graphical user interface, I am afraid there is none in this repository. If you are looking for the executable, you can found it here:

https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases

Download the right one for you machine (possibly, the `fpcupdeluxe-x86_64-linux` one). Also, you may need to change permissions (allowing it to run as an executable) before running it.

**Comment by lpvm** [comment]
That's it @cpicanco.
I'll bother you just a little bit more.  After cloning, to build an executable - at least for amd64, what shall be done?

**Comment by tondrej** [comment]
To build an executable from Free Pascal source code, you need a Free Pascal compiler... It's a bit of a chicken-egg problem.

You could start by installing Free Pascal and Lazarus from a release for your distro. Then you can build fpcupdeluxe from sources.
Or you could start by downloading a released fpcupdeluxe executable and using it to install Free Pascal and Lazarus.

Once you have Free Pascal and Lazarus, you can build fpcupdeluxe.
Once you have fpcupdeluxe, you can install Free Pascal and Lazarus.

The bonus with fpcupdeluxe is that you can install multiple versions of Free Pascal and Lazarus "side by side" into separate directories.

I hope this helps.

**Comment by lpvm** [comment]
Thank you very much all of you.
