### ISSUE TITLE
Please add a arm-linux ARMEL option

### ISSUE THREAD

**Issue by BeRo1985** [LongDirtyAnimAlf/fpcupdeluxe#88]
Please add an arm-linux ARMEL option, because Viprinet is a Object-Pascal-based company, where the embedded Linux on the Viprinet routers is ARMEL-EABI-based and not AMRHF-based. Being ARMHF-only is really the wrong way.

**Comment by adromir** [comment]
Does FPC itself supports it? If not, then the better place to suggest that would be to Ask the Developers of FPC for it

**Comment by BeRo1985** [comment]
Of course, FPC itself is supporting the ARMEL ABI target without problem (Hint: I'm the co-author of CrossFPC http://www.crossfpc.com/ , which integrates FPC in the Delphi IDE, where a AERMEL-based ARM target exists from the beginning on (since 2005)). 

The problem is, that fpcupdeluxe is setting probably always -dFPC_ARMHF, when it builds the arm-linux crosscompiler, even if you're overriding the cross build parameters by omitting -CaEABIHF and so on, also which leads to /lib/ld-linux-armhf.so.3 always being used as the dynamic linker library, which does not exist on ARMEL systems, but only /lib/ld-linux.so.3 . Which prevents actually binary code ARMEL-compatible binaries from running on ARMEL systems because it uses the wrong dynamic linking library, until you patching the binary with `patchelf --set-interpreter /lib/ld-linux.so.2 binaryfilename`, but this should not be the final solution at fpcupdeluxe for the ARMEL ABI target.

**Comment by BeRo1985** [comment]
A suggestion, instead of having only one "arm" target in the fpcupdeluxe cpu selection list, splits it into virtual "armel", "armeb" and "armhf" cpu targets in the cpu selection list.

**Comment by adromir** [comment]
Can't you override the Options in Setup+? Or doesnt that work

**Comment by BeRo1985** [comment]
> Can't you override the Options in Setup+? Or doesnt that work

If you did read my answer fully and correctly, then you should know the answer to it that already: Even overriding options with Setup+ doesn't help in this case.

Und a here a quote from the fpcupdeluxe source code:

```
             // what to do ...                                                                                                                                                                                  
             // always build hardfloat for ARM ?                                                                                                                                                                
             // or default to softfloat for ARM ?                                                                                                                                                               
             // if (Pos('-dFPC_ARMEL',Options)=0) then Options:=Options+' -dFPC_ARMEL';                                                                                                                         
             // decision: (nearly) always build hardfloat ... not necessary correct however !
```
So the developer of fpcupdeluxe notes himself in his code comment that it is probably not correct.

**Comment by LongDirtyAnimAlf** [comment]
I am working on it.
You could compile fpcupdeluxe 1.6.2i yourself and test it, with the option -dFPC_ARMEL added in Setup+ (FPC options).
Its a bit of a hack, but it could work.

**Comment by BeRo1985** [comment]
Then it exits with a "Error: Illegal parameter: -CaEABIHF" error at the last step.

**Comment by LongDirtyAnimAlf** [comment]
I will look at your pull-request.

**Comment by BeRo1985** [comment]
But as said, it's still incomplete/not final yet, so you must
complete/finalize it then, if you take my pull reuest as basis for the
armel/armeb/armhf support.

**Comment by LongDirtyAnimAlf** [comment]
Sources are updated.
Binaries also.
Please try:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.2i

**Comment by LongDirtyAnimAlf** [comment]
Marking as resolved.
