### ISSUE TITLE
Modules Installation

### ISSUE THREAD

**Issue by adromir** [LongDirtyAnimAlf/fpcupdeluxe#89]
I had a few suggestions Concerning the Modules Installation:

1. It would be Nice, if every Module hat a Status shown if it is Installed and in which Version it's installed
2. Refering to 1 an Updatenotification would be great, if the Module has been Updated
3. More Infos on Each Module. Maybe The Link to the original Repository of source
4. Adding Dependencies. I had it happen several Times that modules couldn't compile because of missing dependencies. Sometimes I got it solved by checking the Log, find the Code Repository and find the Dependencies there

But this is really a very Helpful piece of Work. Thanks for all your Effort!

with best regards
Adromir

**Comment by LongDirtyAnimAlf** [comment]
I understand your requests.
However, the module installation feature of fpcupdeluxe is just an extra. No extra functionality will be added to it, besides better dependency checks.
Lazarus has now the OPM (Online Package Manager). That will offer all features that you need. And is much better and feature-rich than fpcupdeluxe will ever become.
