### ISSUE TITLE
FPC Crosscompiler for Java

### ISSUE THREAD

**Issue by adromir** [LongDirtyAnimAlf/fpcupdeluxe#91]
So I am trying to compile the Crosscompiler for Java (on Windows) and just can't make it work. It always stops with 

"Error: Assembler java.exe not found, switching to external assembling"

I have Java 8 Installed, both JDK and JRE and correctly in Path (at least I think, because i can call java.exe from a Windows Shell from anywhere). I saw that the line before says

C:/fpcupdeluxe/fpcsrc/compiler/ppcjvm.exe -Ur -Tjava -Pjvm -Ur -Xs -O2 -n -Fi../inc -Fi../jvm -FDC:\Program Files (x86)\Common Files\Oracle\Java\javapath -FE. -FUC:/fpcupdeluxe/fpcsrc/rtl/units/jvm-java -vw-n-h-l-d-u-t-p-c- -djvm -dRELEASE  -Us -Sg @rtl.cfg system.pp 

WHere -FDC points to a folder that doesnt exist, because I am working with the 64Bit Java . I tried to override that but no Luck so far

**Comment by LongDirtyAnimAlf** [comment]
Will look into it !
But not today: busy. Be back tomorrow !
Thanks for the feedback.

**Comment by adromir** [comment]
No Hurry. Enjoy your weekend

**Comment by LongDirtyAnimAlf** [comment]
Please try:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.2i

**Comment by adromir** [comment]
Now it points to an Installed Java Version from Smartgit, which brings its own bundled Java exe.. Maybe A Fix Could be to use JAVA_HOME Environmentvariable if set?

**Comment by LongDirtyAnimAlf** [comment]
Ok. Thanks.
Please try new 1.6.2i.
Sorry for the inconvenience.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.2i

**Comment by adromir** [comment]
Now it finds the JAVA installation correctly and Cross Compiling works with FPC trunk

**Comment by mdbs99** [comment]
What kind of cross compiler for Java we are talking?
I know that FPC has some cross for Java, but for me it was just an experimental...

@adromir could you give us some example about which kind of application are you working on? Thanks.

**Comment by adromir** [comment]
Not working on a specific App right now.. I have something in planning and want to make it Cross Platform and just want to see which option works best
