### ISSUE TITLE
Q4OS Compile Error

### ISSUE THREAD

**Issue by mehmetulukaya** [LongDirtyAnimAlf/fpcupdeluxe#92]
Hello I am trying to install fpc & lazarus with fpcupdeluxe in q4os 2.7 64bits scorpion.
My aim is compile without install any distrubuted fpc but fpcres needed.

Maybe you should check the compile order , I mean fpcres sources has already downloaded by fpcupdeluxe but not compiled or there is miss linking to binary.

I think I can pass by install fpc by apt-get install but I prefer fpcupdeluxe does this operation.

FYI Log:
3104) Compiling showdeletingfilesdlg.pas
(3104) Compiling compatibilityrestrictions.pas
(3104) Compiling restrictionbrowser.pas
(3104) Compiling projectwizarddlg.pas
(3104) Compiling sourcefilemanager.pas
(3104) Compiling notifyprocessend.pas
(9022) Compiling resource /home/q4osx/Genel/lazarus_trunk_64/lazarus/units/x86_64-linux/gtk2/lazarus.or
/home/q4osx/Genel/lazarus_trunk_64/lazarus/ide/lazarus.pp(167,1) Error: (9030) Can't call the resource compiler "/home/q4osx/Genel/lazarus_trunk_64/fpc/bin/x86_64-linux/fpcres", switching to external mode
/home/q4osx/Genel/lazarus_trunk_64/lazarus/ide/lazarus.pp(167,1) Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: /home/q4osx/Genel/lazarus_trunk_64/fpc/bin/x86_64-linux/ppcx64 returned an error exitcode
Makefile:4144: recipe for target 'lazarus' failed
make[2]: *** [idepkg] Error 2
Makefile:4574: recipe for target 'idepkg' failed
make[1]: *** [idepkg] Error 2
Makefile:3277: recipe for target 'idepkg' failed
Error: (lazarus) Build IDE: stopped with exit code 2
Error: (lazarus) Building IDE: Building IDE failed.
Makefile:3282: recipe for target 'useride' failed
make: *** [useride] Error 2
fpcupdeluxe: ERROR: LazarusNativeInstaller (BuildModuleCustom: UserIDE): make returned error code #512

ERROR: Fpcupdeluxe fatal error !

**Comment by LongDirtyAnimAlf** [comment]
I just did an install with fpcupdeluxe on q4os (in a VM on Windows).
It ran without any problems ! The fpcres was build together with all other fpc binaries.
Your problem could be related to a memory problem or a swap problem.
Can you increase swap and/or memory to check.

**Comment by mehmetulukaya** [comment]
thank you so much I think it is about memory
