### ISSUE TITLE
fpcupdeluxe does not work 

### ISSUE THREAD

**Issue by sstvmaster** [LongDirtyAnimAlf/fpcupdeluxe#95]

**Comment by sstvmaster** [comment]
With 1.6.2c:

> fpcupdeluxe: info: 03.02.2019 21:05:18: fpcupdeluxe: V062 (20181018) started.
> fpcupdeluxe: info: Windows major version: 6
> fpcupdeluxe: info: Windows minor version: 1
> fpcupdeluxe: info: Windows build number:  7601
> fpcupdeluxe: info: FPCNativeInstaller (CleanModule: FPC): No FPC source [yet] ... nothing to be done
> fpcupdeluxe: info: FPCNativeInstaller (CheckAndGetTools): Getting OpenSLL library files.
> fpcupdeluxe: WARNING: FPCNativeInstaller (DownloadOpenSSL): No OpenSLL library files available for SSL. Going to download them
> fpcupdeluxe: info: FPCNativeInstaller (GetFile): Downloading https://indy.fulgan.com/SSL/openssl-1.0.2p-i386-win32.zip
> fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2p-i386-win32.zip from https://indy.fulgan.com/SSL/
> fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2p-i386-win32.zip from https://indy.fulgan.com/SSL/
> fpcupdeluxe: info: FPCNativeInstaller (GetFile): Could not download file with URL https://indy.fulgan.com/SSL/openssl-1.0.2p-i386-win32.zip into C:\Users\Maik\AppData\Local\Temp (filename: FPCUPTMP00002.zip)
> fpcupdeluxe: info: FPCNativeInstaller (GetFile): Downloading https://indy.fulgan.com/SSL/openssl-1.0.2p-i386-win32.zip
> fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2p-i386-win32.zip from https://indy.fulgan.com/SSL/
> fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2p-i386-win32.zip from https://indy.fulgan.com/SSL/
> fpcupdeluxe: info: FPCNativeInstaller (GetFile): Could not download file with URL https://indy.fulgan.com/SSL/openssl-1.0.2p-i386-win32.zip into C:\Users\Maik\AppData\Local\Temp (filename: FPCUPTMP00002.zip)
> fpcupdeluxe: info: FPCNativeInstaller (GetFile): Downloading http://wiki.overbyte.eu/arch/openssl-1.0.2p-win32.zip
> fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2p-win32.zip from http://wiki.overbyte.eu/arch/
> fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2p-win32.zip from http://wiki.overbyte.eu/arch/
> fpcupdeluxe: info: FPCNativeInstaller (GetFile): Could not download file with URL http://wiki.overbyte.eu/arch/openssl-1.0.2p-win32.zip into C:\Users\Maik\AppData\Local\Temp (filename: FPCUPTMP00002.zip)
> fpcupdeluxe: info: FPCNativeInstaller (GetFile): Downloading http://wiki.overbyte.eu/arch/openssl-1.0.2p-win32.zip
> fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2p-win32.zip from http://wiki.overbyte.eu/arch/
> fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2p-win32.zip from http://wiki.overbyte.eu/arch/
> fpcupdeluxe: info: FPCNativeInstaller (GetFile): Could not download file with URL http://wiki.overbyte.eu/arch/openssl-1.0.2p-win32.zip into C:\Users\Maik\AppData\Local\Temp (filename: FPCUPTMP00002.zip)
> fpcupdeluxe: info: FPCNativeInstaller (GetFile): Downloading http://www.magsys.co.uk/download/software/openssl-1.0.2o-win32.zip
> fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2o-win32.zip from http://www.magsys.co.uk/download/software/
> fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2o-win32.zip from http://www.magsys.co.uk/download/software/
> fpcupdeluxe: info: FPCNativeInstaller (GetFile): Could not download file with URL http://www.magsys.co.uk/download/software/openssl-1.0.2o-win32.zip into C:\Users\Maik\AppData\Local\Temp (filename: FPCUPTMP00002.zip)
> fpcupdeluxe: info: FPCNativeInstaller (GetFile): Downloading http://www.magsys.co.uk/download/software/openssl-1.0.2o-win32.zip
> fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2o-win32.zip from http://www.magsys.co.uk/download/software/
> fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2o-win32.zip from http://www.magsys.co.uk/download/software/
> fpcupdeluxe: info: FPCNativeInstaller (GetFile): Could not download file with URL http://www.magsys.co.uk/download/software/openssl-1.0.2o-win32.zip into C:\Users\Maik\AppData\Local\Temp (filename: FPCUPTMP00002.zip)
> fpcupdeluxe: info: FPCNativeInstaller (GetFile): Downloading https://indy.fulgan.com/SSL/Archive/openssl-1.0.2o-i386-win32.zip
> fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2o-i386-win32.zip from https://indy.fulgan.com/SSL/Archive/
> fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2o-i386-win32.zip from https://indy.fulgan.com/SSL/Archive/
> fpcupdeluxe: info: FPCNativeInstaller (GetFile): Could not download file with URL https://indy.fulgan.com/SSL/Archive/openssl-1.0.2o-i386-win32.zip into C:\Users\Maik\AppData\Local\Temp (filename: FPCUPTMP00002.zip)
> fpcupdeluxe: info: FPCNativeInstaller (GetFile): Downloading https://indy.fulgan.com/SSL/Archive/openssl-1.0.2o-i386-win32.zip
> fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2o-i386-win32.zip from https://indy.fulgan.com/SSL/Archive/
> fpcupdeluxe: info: Native downloader: Getting openssl-1.0.2o-i386-win32.zip from https://indy.fulgan.com/SSL/Archive/
> fpcupdeluxe: info: FPCNativeInstaller (GetFile): Could not download file with URL https://indy.fulgan.com/SSL/Archive/openssl-1.0.2o-i386-win32.zip into C:\Users\Maik\AppData\Local\Temp (filename: FPCUPTMP00002.zip)

**Comment by sstvmaster** [comment]
So digging depper, so istart taskmanager (processes).
If i press button "Install/Update..." windows powershell.exe appears and fpcupdeluxe hangs.

Do you use powershell to download on windows?

**Comment by LongDirtyAnimAlf** [comment]
Yes, fpcupdeluxe also uses powershell to download.
I am sorry that it will not work for you.
Please use the latest version of fpcupdeluxe (1.6.2k) and try again !
However, it should not be necessary to run as  Admin !

**Comment by sstvmaster** [comment]
Hi,
i found the solution. i test it my own 2 pc's w7prof 32bit + w7prof 64bit.

i checked whitch version of powershell were installed. On both machines there was Version 2 installed and
fpcupdeluxe hangs. 
I downloaded Version 3 / 4 / 5.1 from here and instal one after another: 
https://docs.microsoft.com/en-us/powershell/scripting/install/installing-windows-powershell?view=powershell-6

Now fpcupdeluxe works fine (1.6.2k).

So i think it would be better that you check PS Version first and show a message if it is lower than 3 and point to the link.

To check version you can use:

get-host | select-object version

Output:
Version
-------
5.1.14409.1005

rgr Maik

**Comment by sstvmaster** [comment]
You can also use from Windows Commandline:

`powershell.exe $PSVersionTable.PSVersion.Major`

this returns 5 as output and should from Powershell Version 2 and up

**Comment by LongDirtyAnimAlf** [comment]
I have added BitsAdmin for an extra OpenSSL download option on older Windows versions.
Its included in release 1.6.2m. Would you mind testing ?

**Comment by AlessandroNava** [comment]
Go on Total Commander page and download them
https://www.totalcommander.ch/win/openssl/openssl-1.0.2u-i386-win32.zip
it's work for me
